#!/usr/bin/env python3
"""Replace Q001-Q010 in weeks 29-32 fundamentals Q&A with premium format."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = """# Week {week:02d} — Fundamentals Interview Q&A

> Q001–Q010: Premium format (Week 1 quality). Q011–Q030: Practice bank.  
> See also: [DevOps Top 50](../../../interview-prep/devops-top-50-index.md)

---

"""

QA_TEMPLATE = """
## Q{num:03d}: {title}

| Attribute | Value |
|-----------|-------|
| **Difficulty** | Fundamentals |
| **Category** | {category} |
| **Frequency** | {frequency} |

### Question

{question}

### Short Answer (30 seconds)

{short}

### Detailed Answer (3–5 minutes)

{detailed}

### Architecture Perspective

{perspective}

### Follow-up Questions

{followups}

### Common Mistakes in Interviews

{mistakes}

---
"""


def q(title, category, frequency, question, short, detailed, perspective, fu1, fu2, m1, m2, m3):
    return dict(title=title, category=category, frequency=frequency, question=question,
                short=short, detailed=detailed, perspective=perspective,
                followups=f"1. {fu1}\n2. {fu2}",
                mistakes=f"- {m1}\n- {m2}\n- {m3}")


WEEKS = {
    29: [
        q("DORA Four Key Metrics", "DORA Metrics", "Very Common",
          "What are the four DORA metrics and how do elite performers benchmark against low performers?",
          "Deployment Frequency, Lead Time for Changes, Change Failure Rate, and MTTR. Elite teams deploy multiple times daily with <15% CFR and <1 hour MTTR. I baseline all four before recommending any tooling investment.",
          "The Accelerate/DORA research defines four metrics that predict organizational performance. **Deployment Frequency** measures how often you ship to production. **Lead Time** is commit to production — includes CI, review, and deploy time. **Change Failure Rate** is the percentage of deploys causing failure. **MTTR** is recovery time after incidents.\n\nFor a .NET team I assess: monthly deploys + 30% CFR = start with CI and automated tests on every PR. Daily deploys + high CFR = feature flags and canary deploys before adding more services.\n\nI present DORA to executives as a balanced scorecard — optimizing deploy frequency alone while CFR spikes is a warning sign.",
          "Interviewers want diagnostics, not buzzwords. Tie each metric to an architectural lever: smaller services improve frequency, automated rollback improves MTTR, contract tests reduce CFR.",
          "Lead time vs cycle time? — Cycle time ends at merge; lead time ends in production.",
          "How measure in Azure DevOps? — Deployment records linked to commit SHA and environment.",
          "Listing metrics without elite benchmarks",
          "Proposing tools without identifying which metric they improve",
          "Confusing lead time with cycle time"),
        q("Trunk-Based vs GitFlow", "Branching Strategy", "Very Common",
          "When would you recommend trunk-based development over GitFlow for a .NET enterprise?",
          "Trunk-based with feature flags for most .NET microservice teams — short-lived branches merged to main within 1–2 days. GitFlow only for versioned libraries or strict regulatory release branches.",
          "**Trunk-based:** `main` always deployable, branches live hours not weeks, incomplete work behind feature flags. Correlates with elite DORA.\n\n**GitFlow:** long-lived develop, release branches, suited to semver NuGet packages and mobile store releases.\n\nFor 5 product teams on microservices, I mandate trunk-based per repo. For a shared domain library consumed by 20 services, GitFlow with semver tags prevents breaking consumers.\n\nFeature flags are non-negotiable for trunk-based — without them you cannot merge incomplete checkout redesigns safely.",
          "Branching is an architecture decision affecting release coupling and incident response speed.",
          "Can large PRs work with trunk-based? — No. Enforce <400 line PRs or split work.",
          "Monorepo? — Trunk-based still applies; use path filters in CI.",
          "Calling GitFlow enterprise best practice without trade-offs",
          "Omitting feature flags as prerequisite",
          "Ignoring monorepo vs polyrepo impact"),
        q("Feature Flags for Safe CD", "Feature Flags", "Common",
          "How do feature flags decouple deployment from release in a regulated .NET environment?",
          "Code deploys to production with flags off; business release happens when compliance approves flag enable. CAB reviews flag rollout, not every binary deploy. Azure App Configuration provides audit history.",
          "Three flag types: **release** (short-lived, new checkout), **ops** (permanent kill switch for payment provider), **experiment** (A/B test).\n\nRegulated flow: automated deploy to prod (standard change) → CAB approves enabling `CheckoutV2` for 5% of users → monitor CFR and conversion → expand.\n\n.NET: `Microsoft.FeatureManagement` + `TargetingFilter` for internal testers first, then `PercentageFilter`.\n\nFlag hygiene: backlog ticket to remove flag and dead code within 2 sprints after 100% rollout.",
          "This is how architects sell CD to compliance — deploy is low risk when code path is dark.",
          "Flags vs slots? — Slots swap versions; flags control logic within a version.",
          "Test matrix? — CI runs tests with flag on and off.",
          "Permanent flags becoming spaghetti",
          "Using flags for security boundaries",
          "No monitoring during percentage rollout"),
        q("Platform Engineering", "Platform Engineering", "Common",
          "What is an Internal Developer Platform and what would you include for .NET teams?",
          "Self-service golden paths: .NET 8 API template, reusable GitHub Actions workflow with OIDC, Bicep modules, App Insights wired, feature flags ready. Platform team measures time-to-first-deploy and developer satisfaction.",
          "IDP layers: **templates** (scaffold), **pipelines** (reusable workflows), **environments** (ephemeral PR envs), **docs** (Backstage catalog).\n\nFor 10 teams without IDP, each reinvents CI/CD — inconsistent security, 2-week onboarding. With IDP, clone to deployed hello-world in <1 day.\n\nPlatform team owns the paved road; product teams own services. Teams may go off-road but assume operational burden.",
          "IDP scales architect influence — encodes Managed Identity, no secrets in config, OTel mandatory.",
          "Platform team size? — Roughly 1 platform engineer per 5–8 product teams at maturity.",
          "Build vs buy? — Backstage + custom templates is common.",
          "Platform team approving every deploy (bottleneck)",
          "No adoption metrics",
          "Over-engineering Kubernetes for App Service workloads"),
        q("Blameless Postmortems", "Incident Culture", "Common",
          "How do you facilitate a blameless postmortem after a production incident?",
          "Focus on systems not individuals. Timeline, root cause, contributing factors, action items with owners. Architect owns actions for observability gaps, missing failure modes, and ADR updates.",
          "Structure: impact summary → UTC timeline → root cause (technical) → contributing factors (missing alert, no runbook) → what went well → SMART actions.\n\nAfter payment API outage from connection pool exhaustion: actions included SQL pool metric alert, load test at 2x peak in CI, ADR for read replica.\n\nBlameless does not mean no accountability — malicious acts are HR matters, but still fix the system.",
          "Postmortems are architecture feedback loops — interviewers want leaders who improve systems.",
          "Near-misses? — Run postmortems for near-misses too — cheaper learning.",
          "Repeat incidents? — Track action item completion rate.",
          "Root cause = human error",
          "No measurable action items",
          "Postmortem only for major outages"),
        q("DevOps Culture for Architects", "DevOps Culture", "Common",
          "What is the architect role in building DevOps culture in a traditional enterprise?",
          "Design for deployability and observability, partner with ops early, embed quality gates in golden paths, celebrate learning from incidents. Remove structural barriers — not mandate Kubernetes.",
          "CALMS: Culture, Automation, Lean, Measurement, Sharing.\n\nArchitect actions: involve ops in design reviews; include runbooks in sign-off; measure DORA after platform investments; admit when designs fail.\n\nAnti-pattern: tool mandates without cultural readiness — Jenkins installed, nobody trusts automated deploy.",
          "Behavioral interviews probe influence without authority — DevOps transformation is a strong STAR story.",
          "DevOps vs SRE? — SRE applies software engineering to ops; DevOps is broader cultural movement.",
          "Fund platform team? — Quantify lead time reduction and incident cost savings.",
          "Equating DevOps with developers doing all ops alone",
          "Tool-first answers without cultural elements",
          "Ignoring organizational change management"),
        q("CAB vs Continuous Delivery", "Governance", "Common",
          "How do you reconcile Change Advisory Board processes with continuous delivery?",
          "Automate deploy continuously; CAB approves production flag enable or standard change catalog. Pipeline generates audit evidence — test results, scans, commit SHA, approver identity.",
          "Hybrid model: PR → CI → auto staging → integration tests → artifact signed → CAB reviews automated packet for normal changes → prod promotion.\n\nStandard changes (template microservice deploy) pre-approved. Normal changes get weekly CAB with machine-generated evidence.\n\nSOC 2 CC8 satisfied by environment protection rules and deployment audit logs — not meeting minutes per deploy.",
          "Real stakeholder tension — show you understand compliance AND modern delivery.",
          "Manual prod deploys? — Start with automated deploy + manual approval gate; narrow scope over time.",
          "Auditor concerns? — Demo immutable pipeline logs and segregation of duties.",
          "CAB is always wrong",
          "No hybrid model",
          "Manual evidence collection per release"),
        q("Measuring Platform Success", "Platform Engineering", "Occasional",
          "What metrics prove an Internal Developer Platform is working?",
          "Time from clone to first production deploy, platform adoption rate (% repos on golden path), DORA metrics per team, developer satisfaction survey, and platform support ticket volume trending down.",
          "Leading indicators: template adoption, PRs to platform repos. Lagging: deployment frequency increase, CFR decrease, MTTR decrease.\n\nIf adoption is low, platform failed — investigate friction, not mandate harder.\n\nTarget: 80% of new services use golden path within 6 months of IDP launch.",
          "Platform engineering must prove ROI — architects speak business and engineering metrics.",
          "Vanity metrics? — Number of pipelines created means nothing if teams don't use them.",
          "Team opts out? — Allowed with documented operational burden.",
          "No metrics on platform team success",
          "Measuring only infrastructure uptime",
          "Mandating platform without developer input"),
        q("Reducing Change Failure Rate", "DORA Metrics", "Common",
          "A team has daily deploys but 25% change failure rate. What architectural changes do you recommend?",
          "Canary deploys with automatic rollback on error spike, feature flags to limit blast radius, contract tests in CI, deployment slots with health checks including DB, and expand-contract database migrations.",
          "High CFR with high frequency means you're moving fast and breaking things. Fixes:\n1. **Blast radius** — smaller services, flags off by default\n2. **Detection** — synthetic tests post-deploy\n3. **Rollback** — one-click slot swap, pipeline auto-rollback on 5xx > 1%\n4. **Prevention** — integration + contract tests block merge\n\nMeasure CFR per service — one bad service drags team average.",
          "CFR is the metric that proves whether speed is sustainable.",
          "Freeze deploys? — Worst response — slows learning. Fix quality gates instead.",
          "Who owns CFR? — Service owner, visible on team dashboard.",
          "Blaming developers without systemic fixes",
          "Removing deploy frequency to improve CFR",
          "No per-service CFR breakdown"),
        q("Reducing Lead Time", "DORA Metrics", "Common",
          "Lead time from commit to production is 3 weeks. What do you investigate first?",
          "Map the value stream: PR review wait time, CI duration, manual QA queue, CAB schedule, manual deploy steps. Attack the longest wait first — often manual gates or monolith deploy coupling.",
          "Value stream mapping example:\n- PR review: 2 days (acceptable)\n- CI: 45 min (optimize caching)\n- QA queue: 5 days (add automated integration tests)\n- CAB: weekly meeting (move to standard changes)\n- Deploy: 4 hours manual (automate with slots)\n\nArchitectural fix: extract independently deployable microservice so order team isn't blocked by billing team's release train.",
          "Lead time exposes organizational and architectural coupling — architects see both.",
          "CI too slow? — Parallel jobs, affected-only builds, NuGet cache.",
          "Monolith? — Strangler extraction reduces coupling.",
          "Only optimizing CI while QA/CAB waits remain",
          "No value stream measurement",
          "Ignoring cross-team release train coupling"),
    ],
    30: [
        q("CI/CD Pipeline Stages", "CI/CD", "Very Common",
          "What stages should a production CI/CD pipeline include for a .NET 8 microservice?",
          "Build, unit test, SAST/dependency scan, package immutable artifact, deploy dev, integration test, deploy staging, approval, deploy prod with health check. Same artifact promotes through all environments.",
          "Fail fast at each gate. Typical timing: build 2m, test 3m, scan 2m, deploy staging 5m, integration 5m.\n\nArchitect principles: never rebuild for prod; parallelize security scan with tests; cache NuGet.\n\nE2E tests run in staging nightly or pre-prod — not blocking every PR if >15 min.",
          "Pipeline design reflects quality priorities — skipping integration tests means prod is your test env.",
          "PR vs main pipeline? — PR: build+test only. Main: full deploy path.",
          "Target CI time? — <15 min for PR feedback.",
          "Rebuilding per environment",
          "No security scan stage",
          "Manual deploy steps that should be automated"),
        q("GitHub Actions OIDC to Azure", "GitHub Actions", "Very Common",
          "How does OIDC federation work between GitHub Actions and Azure? Why prefer it over service principal secrets?",
          "GitHub issues short-lived JWT; Entra validates federated credential trusting repo/environment; Azure token returned. No long-lived secret to leak or rotate.",
          "Configure federated credential: issuer `token.actions.githubusercontent.com`, subject `repo:org/app:environment:production`.\n\nMandate OIDC for all new repos. Block `AZURE_CREDENTIALS` JSON pattern in platform lint rules.",
          "Security baseline for cloud CI/CD — expected knowledge for senior architects.",
          "AWS equivalent? — IAM OIDC trust to GitHub.",
          "Self-hosted runners? — When VNet access to private resources required.",
          "Long-lived SP secrets in GitHub",
          "Federated credential scoped to entire org",
          "Running deploy on PR to production"),
        q("App Service Deployment Slots", "Deployment Strategy", "Common",
          "How do Azure App Service deployment slots enable blue-green deployment for .NET APIs?",
          "Deploy to staging slot, warm up, run health checks including DB, swap with production. Instant rollback by swapping back. Slots share App Service Plan.",
          "Slot config: `WEBSITE_SWAP_WARMUP_PING_PATH=/health`. Health check must validate SQL and Redis — not just `return Ok()`.\n\nPair with backward-compatible EF migrations — expand before deploy, contract after all instances on new version.",
          "Blue-green at PaaS layer without Kubernetes complexity — right choice for many .NET APIs.",
          "SignalR/WebSockets? — Drain connections before swap.",
          "Cost? — Staging slot on same plan shares compute.",
          "Swap without health check",
          "Breaking DB migration with slot swap",
          "Health check without dependency validation"),
        q("Blue-Green vs Canary vs Rolling", "Deployment Strategy", "Very Common",
          "Compare deployment strategies for a high-traffic .NET order API.",
          "Rolling for low-risk stateless updates. Blue-green (slots) for instant swap. Canary when high-risk — route 5% traffic, monitor 5xx and p99, auto-rollback on breach.",
          "| Strategy | Rollback | Risk |\n|----------|----------|------|\n| Rolling | Slow | Medium |\n| Blue-green | Instant swap | Low |\n| Canary | Stop traffic shift | Lowest |\n\nAKS: rolling default, Argo Rollouts for canary.",
          "Strategy is risk management — justify choice with failure blast radius.",
          "Canary metrics? — 5xx rate, p99 latency, business conversion.",
          "Database? — Expand-contract required for all except recreate.",
          "Canary without automated rollback",
          "Blue-green ignoring schema compatibility",
          "Recreate deploy in production"),
        q("Build Once Deploy Many", "Artifacts", "Common",
          "Why must the same artifact promote through dev, staging, and production?",
          "Rebuild introduces non-determinism — different NuGet resolution, wrong build config. What you tested is not what you ship. Audit trail breaks.",
          "Flow: commit abc123 → `order-api:1.2.3` in ACR → same tag to staging and prod.\n\nNever `dotnet publish` on production VM. Config per environment via App Settings and Key Vault — not recompile.",
          "Supply chain integrity — connects SLSA, SBOM, and compliance audits.",
          "latest tag? — Anti-pattern in production; use semver + git SHA label.",
          "Config differences? — Outside artifact via Key Vault references.",
          "Rebuilding on prod server",
          "Different binaries in staging vs prod",
          "Cannot answer what code is in prod"),
        q("Secret Management in Pipelines", "Security", "Common",
          "How should secrets be managed in CI/CD for .NET on Azure?",
          "OIDC for CI auth. Runtime secrets in Key Vault via Managed Identity. Build-time tokens in GitHub Environments scoped to environment. Never commit appsettings with secrets.",
          "Pre-commit hooks + GitGuardian on all repos. Rotate immediately on any leak suspicion — `git filter-repo` does not eliminate exposure if key was public.",
          "Golden path templates make secure path the easy path.",
          "Secrets in ARM/Bicep? — Reference Key Vault secrets, never plain text.",
          "CI access to Key Vault? — Separate OIDC scope for deploy-time only.",
          "Connection strings in App Service plain text",
          "Shared secrets across environments",
          "Secrets echoed in pipeline logs"),
        q("SAST and Dependency Scanning", "DevSecOps", "Common",
          "What security scanning belongs in a .NET CI pipeline?",
          "Dependabot/Snyk for CVEs, CodeQL/SonarQube for SAST, GitGuardian for secrets, Trivy for containers. Gate on critical/high; medium to backlog.",
          "Baseline existing debt — block new critical issues, not all historical. Parallelize scan with tests to avoid slowing CI.",
          "DevSecOps shifts left — architects define non-negotiable gates.",
          "DAST? — Staging nightly, not every PR.",
          "Alert fatigue? — Severity-based gates only.",
          "No scanning because slow",
          "Blocking on informational findings",
          "No baseline for legacy debt"),
        q("Contract Testing with Pact", "Testing", "Common",
          "How does Pact fit into microservices CI/CD?",
          "Consumer defines contract; provider verifies in CI before deploy. Broken contract blocks merge — prevents integration failures across independent deploys.",
          "Order API (consumer) publishes pact → broker → Payment API verifies on every PR.\n\nComplements staging integration tests — faster, runs without full stack.",
          "Contract tests are the safety net for independent deployment at scale.",
          "Pact vs integration tests? — Pact is consumer-driven and faster.",
          "Broker required? — Yes for sharing contracts across teams.",
          "Only staging integration tests",
          "No versioned contracts",
          "Skipping provider verification in CI"),
        q("Database Migrations in CD", "CI/CD", "Common",
          "How do you run EF Core migrations in a zero-downtime pipeline?",
          "Expand-contract pattern: backward-compatible migrations only. Run expand migration before app deploy. Contract phase after all instances on new code.",
          "Pipeline order: migrate (expand) → deploy v2 (dual-write) → backfill → deploy v3 → migrate (contract).\n\nNever breaking schema change with rolling deploy or slot swap.",
          "Schema strategy constrains deployment strategy — architects align both.",
          "Who approves prod migrations? — Automated for expand-only; manual for contract.",
          "Rollback? — Tested forward-fix or down migration script.",
          "Migration after deploy with breaking change",
          "No rollback plan",
          "Manual migration on production server"),
        q("CI/CD Security Checklist", "Pipeline Security", "Common",
          "What security controls are non-negotiable in an enterprise CI/CD pipeline?",
          "OIDC auth, branch protection, environment approval for prod, secret scanning, SAST, dependency CVE gate, signed artifacts, segregation of duties, immutable audit logs.",
          "Architect sign-off checklist: no long-lived cloud credentials; CodeQL on every PR; Dependabot enabled; production reviewers configured; deployment linked to commit SHA; SBOM for containers.",
          "Security checklist is architecture governance encoded in pipelines.",
          "Self-hosted runner security? — Harden VM, rotate tokens, network isolate.",
          "Supply chain? — Pin action versions to commit SHA.",
          "Security as optional stage",
          "Developer approves own production deploy",
          "Floating `@v4` action tags without pinning"),
    ],
    31: [
        q("Terraform vs Bicep", "IaC", "Very Common",
          "When do you choose Terraform vs Bicep for Azure infrastructure?",
          "Bicep for Azure-only — day-zero resources, no state file. Terraform for multi-cloud or existing HCL investment. Document choice in ADR.",
          "| Factor | Bicep | Terraform |\n|--------|-------|----------|\n| Azure | Day-zero | Slight lag |\n| State | ARM tracks | Remote state required |\n| Multi-cloud | No | Yes |\n\n.NET Azure shop default: Bicep.",
          "IaC choice is a 5-year decision — migration cost is high.",
          "Coexist? — Yes with clear resource ownership boundaries.",
          "AKS + multi-cloud? — Terraform or split by domain.",
          "Terraform always better in Azure-only context",
          "Ignoring state management overhead",
          "No ADR documenting choice"),
        q("Terraform Remote State", "Terraform", "Common",
          "How should Terraform state be stored for production?",
          "Azure Storage or S3 with locking, encryption, versioning, RBAC restricted to platform team. Separate state per environment. Never commit state to Git.",
          "State loss requires painful `terraform import` — treat as DR-critical. State contains sensitive values — encrypt and restrict access.",
          "Junior architects design resources; senior architects design state strategy.",
          "Workspaces vs separate state? — Separate state files for prod isolation.",
          "State in Git? — Never; secrets leak in state files.",
          "Local state for production",
          "One state file for all environments",
          "No versioning on state blob"),
        q("Bicep Module Structure", "Bicep", "Common",
          "How do you structure Bicep modules for multi-environment .NET platforms?",
          "`/modules/` for reusable resources, `/environments/{dev,staging,prod}/` with `.bicepparam` differing SKUs. Same modules, different parameters — never fork module code.",
          "Outputs: Key Vault URI, app name — consumed by app CI pipeline as environment variables.",
          "Module boundaries mirror platform service catalog.",
          "Bicep registry? — OCI artifacts for cross-subscription reuse.",
          "Too many modules? — Balance granularity vs maintenance.",
          "Copy-paste Bicep per environment",
          "Modules too monolithic",
          "Hardcoded prod values in shared module"),
        q("IaC Drift Detection", "IaC", "Common",
          "How do you detect and prevent infrastructure drift?",
          "Nightly `terraform plan` or `what-if` in CI alerts on diff. Azure Policy denies manual SKU changes. Emergency portal changes backported to IaC within 24 hours.",
          "Drift scenario: manual SQL scale-up reverted by Monday apply → outage. Layers: Policy prevent → CI detect → apply correct OR update IaC if intentional.",
          "Drift is governance failure — connects IaC, ops culture, incidents.",
          "Intentional drift? — Break-glass with ticket and backport.",
          "Black Friday freeze? — No prod IaC applies during peak.",
          "IaC without Policy enforcement",
          "Apply without reviewing plan diff",
          "Assuming teams won't use portal"),
        q("Policy as Code", "Governance", "Common",
          "How does Azure Policy complement IaC?",
          "IaC defines desired state proactively; Policy enforces guardrails on any creation path including portal. Require tags, deny public storage, enforce regions.",
          "Defense in depth: Bicep deploys compliant resources; Policy catches manual mistakes and shadow IT. Initiative bundles map to SOC 2 controls.",
          "Don't rely on IaC discipline alone at enterprise scale.",
          "Terraform Sentinel? — Plan-time policy for TF shops.",
          "Too restrictive? — Sandbox subscription for experimentation.",
          "Policy so strict developers cannot work",
          "No tag enforcement",
          "Policy without exemption process"),
        q("Environment Promotion with IaC", "IaC", "Common",
          "How do you promote infrastructure changes from dev to production?",
          "Same modules; PR triggers plan on dev+staging; merge applies staging; production requires approval gate. Never `terraform apply` prod from laptop.",
          "Parameter differences: dev S1 SQL, prod P2 with zone redundancy. Prod apply only from pipeline service principal with separate state file.",
          "Environment promotion integrates IaC and CI/CD design.",
          "Ephemeral PR environments? — Deploy on PR open, destroy on close.",
          "Blue-green infra? — Separate resource groups + traffic switch.",
          "Different module code per environment",
          "Manual prod changes",
          "Prod apply from developer laptop"),
        q("Brownfield IaC Import", "IaC", "Occasional",
          "How do you bring manually created Azure resources under IaC?",
          "Inventory, write matching Bicep/Terraform, import, verify plan shows zero changes, enable Policy to prevent drift.",
          "`terraform import` or Bicep `existing` keyword. Prioritize by blast radius — prod SQL before dev storage. `az bicep decompile` is starting point only — needs cleanup.",
          "Most architects inherit brownfield — import strategy is practical gold.",
          "Delete and recreate? — Downtime and data loss — avoid.",
          "Import all at once? — Phased by resource group.",
          "Assuming decompile is production-ready",
          "No drift prevention after import",
          "Managing same resource in TF and Bicep"),
        q("IaC Testing in Pull Requests", "IaC", "Common",
          "How do you test IaC changes before production apply?",
          "`terraform validate`, Checkov/tfsec, plan/what-if commented on PR, ephemeral environment smoke test.",
          "Prod plan with read-only SP — preview without apply. Auto-destroy ephemeral envs after 24h.",
          "IaC CI as important as application CI — misconfigured NSG worse than a bug.",
          "fmt check? — `terraform fmt -check` in CI.",
          "Cost of ephemeral envs? — Budget alerts and auto-teardown.",
          "First apply in prod without plan review",
          "No static analysis",
          "Skipping what-if on Bicep PRs"),
        q("GitOps vs Push Deployment", "Deployment", "Common",
          "Compare GitOps and push-based CI/CD for Kubernetes vs App Service.",
          "Push: pipeline calls deploy API. GitOps: Argo CD reconciles cluster to Git. GitOps ideal for AKS; push fine for App Service and Bicep pipelines.",
          "AKS 10+ services → GitOps reduces kubectl-from-CI risk. App Service + Bicep → push model with desired-state in pipeline is equivalent.",
          "Model choice depends on compute platform — not universal GitOps.",
          "GitOps for App Service? — Less common; Bicep pipeline is desired-state pattern.",
          "Rollback? — Git revert vs redeploy artifact.",
          "GitOps without understanding reconciliation loop",
          "kubectl apply from laptop to prod",
          "Mandating GitOps for 3 App Service APIs"),
        q("FinOps Tags in IaC", "FinOps", "Common",
          "How do you enforce cost allocation tags through IaC?",
          "Mandatory tags in modules: Environment, CostCenter, Owner, Application. Azure Policy denies untagged resources.",
          "FinOps reports impossible without tags at provision time. Limit to 5–7 mandatory tags to avoid sprawl.",
          "FinOps starts at provision — retrofitting 500 resources is painful.",
          "Showback? — Tags enable team cost dashboards.",
          "Optional tags? — Policy should enforce, not audit only.",
          "Optional tags in modules",
          "No Policy enforcement",
          "15+ mandatory tags slowing deployments"),
    ],
    32: [
        q("Three Pillars of Observability", "Observability", "Very Common",
          "What are the three pillars of observability and how do they work together during incidents?",
          "Logs (what), metrics (how much/fast), traces (where time went). Alert on metric → trace finds slow span → logs show exception. All linked by trace/correlation ID.",
          "During checkout slowdown: metric alert on p99 → trace shows Payment API span 4.8s → log shows `PaymentTimeoutException` on correlation ID.\n\nArchitect mandate: every microservice exports all three via OpenTelemetry.",
          "Observability is part of definition of done for every service.",
          "Fourth pillar? — Profiling for CPU flame graphs.",
          "Logs vs traces? — Complementary; traces show structure, logs add detail.",
          "Logs only, no metrics or traces",
          "String interpolation breaking structured query",
          "No correlation ID standard"),
        q("OpenTelemetry for .NET", "OpenTelemetry", "Very Common",
          "How do you instrument ASP.NET Core 8 with OpenTelemetry?",
          "Add OTel hosting extensions, enable ASP.NET Core/HttpClient/EF instrumentations, export to Azure Monitor or OTLP collector. Propagate W3C traceparent on all outbound calls.",
          "Custom spans around payment processing. Service name matches deployment name. Version tag = container image tag for deploy correlation.",
          "OTel is vendor-neutral — standardize on OTel, swap backends per environment.",
          "Sampling? — 100% dev; tail-based or probabilistic prod keeping all errors.",
          "Service Bus? — Inject trace context in message properties.",
          "Legacy App Insights SDK only for new services",
          "Broken trace propagation",
          "Missing EF Core instrumentation"),
        q("SLI SLO and Error Budget", "SRE", "Very Common",
          "Define SLI, SLO, SLA, and error budget for an order API.",
          "SLI: % successful requests. SLO: 99.9% availability (43 min/month budget). SLA: 99.95% with credits. Exhausted budget → freeze features, fix reliability.",
          "Latency SLI: p99 < 300ms measured at load balancer.\n\nError budget policy: >50% budget → normal dev; <20% → reliability sprint; exhausted → exec escalation.",
          "SLOs connect architecture to business risk with numbers.",
          "100% SLO? — Impossible and paralyzing.",
          "Client vs server SLI? — User-facing synthetic + RUM beats server-only.",
          "Confusing SLO with SLA",
          "No error budget policy",
          "SLOs without measurement implementation"),
        q("RED vs USE Methods", "Monitoring", "Common",
          "Explain RED and USE monitoring methods.",
          "RED (Rate, Errors, Duration) for request-driven services. USE (Utilization, Saturation, Errors) for resources like CPU, SQL DTU, Redis memory.",
          "Order API → RED dashboard. SQL Server → USE dashboard (DTU utilization, connection saturation).\n\nAlert on saturation before utilization hits 100% — thread pool starvation at 60% CPU.",
          "Dashboard design reflects system thinking.",
          "Google golden signals? — Latency, traffic, errors, saturation — overlaps RED+USE.",
          "Service Bus? — USE on dead letter queue depth.",
          "CPU-only alerts missing saturation",
          "Wrong method for resource type",
          "No dashboards per component"),
        q("Structured Logging in .NET", "Logging", "Common",
          "Why use structured logging instead of string interpolation?",
          "Named properties (`OrderId`, `CustomerId`) are queryable in Log Analytics. `$\"Order {id}\"` breaks field extraction and increases ingestion cost.",
          "Wrap requests in correlation ID scope. Never log PII/passwords. Information for business events; Debug off in production.",
          "Unstructured logs waste MTTR minutes during outages.",
          "Serilog? — Rich sinks; built-in sufficient with App Insights exporter.",
          "Log levels in prod? — Debug floods ingestion and cost.",
          "Interpolated strings in logs",
          "No correlation ID across services",
          "Logging PII/card numbers"),
        q("Alert Design", "Alerting", "Common",
          "How do you design alerts without causing alert fatigue?",
          "Page on user-impacting symptoms (SLO burn, 5xx rate). Ticket for warnings. Every page alert needs runbook. Weekly alert review — delete noisy rules.",
          "SLO multi-window burn rate: fast burn pages, slow burn tickets.\n\nAnti-patterns: single failed health check, no runbook, 50 cascading alerts.",
          "Alert design is on-call UX — bad alerts cause burnout and missed real incidents.",
          "Who gets paged? — Service owner rotation, not entire platform team.",
          "Flapping? — Require N consecutive failures before page.",
          "Alert on everything",
          "No page vs ticket distinction",
          "Alerts without runbook links"),
        q("Distributed Tracing Debug", "Tracing", "Common",
          "How do you use distributed tracing to debug a 5-second API response?",
          "Find slow trace by duration, examine span waterfall, identify bottleneck span (Payment API, SQL), check logs on correlation ID.",
          "Waterfall: checkout 5.2s → payment-api 4.8s → stripe.com 4.6s. Fix: circuit breaker, timeout tuning — not SQL index guesswork.",
          "Tracing turns vague slowness into actionable service boundaries.",
          "Broken traces? — Missing traceparent on HttpClient or Service Bus.",
          "Regression detection? — Compare p99 before/after deploy.",
          "Adding cache without finding bottleneck",
          "grep logs across 15 services without traces",
          "No custom spans on critical paths"),
        q("PowerShell Azure Automation", "Automation", "Occasional",
          "What Azure operations would you automate with PowerShell?",
          "Cost reports by resource group, untagged resource audits, bulk diagnostic settings, incident scale-out/restart, certificate expiry reports.",
          "Prefer Bash/Azure CLI on Linux CI agents; PowerShell for Windows-centric enterprise reporting and FinOps dashboards.",
          "Automation scripts are operational runbooks — architects provide templates.",
          "PowerShell in GitHub Actions? — Windows runners or Az CLI on ubuntu.",
          "Idempotency? — Scripts safe to re-run.",
          "Manual portal clicks during incidents",
          "Non-idempotent scripts",
          "No documented runbooks"),
        q("Synthetic Monitoring", "Monitoring", "Common",
          "Why is synthetic monitoring critical for multi-region architectures?",
          "Internal health checks in failed region show green while customers fail. Probes from multiple geographies detect user-facing outages — especially after failover.",
          "Design: availability tests from US, EU, APAC every 60s on critical journeys (login, checkout). Alert when 2+ locations fail.\n\n`/health` must check DB connectivity — not just process alive.",
          "Validates user experience — internal metrics lie during partial failures.",
          "Synthetic vs canary? — Synthetic is fixed probe traffic; canary is prod users to new version.",
          "Post-failover? — Probes must follow traffic manager weights.",
          "Health check returns 200 without dependencies",
          "Single-region probes only",
          "No alert on synthetic failure"),
        q("Observability Cost Control", "FinOps", "Occasional",
          "Application Insights costs grew 40% month-over-month. How do you optimize?",
          "Trace sampling (keep 100% errors), reduce verbose logging in prod, daily cap alerts, drop unused custom metrics, archive old data to Storage.",
          "Tail-based sampling at OTel collector — central control. Don't sample so aggressively you cannot debug incidents.",
          "FinOps applies to observability — set standards in platform templates.",
          "Collector filtering? — Drop health check traces before export.",
          "Retention? — 30 days hot, archive cold.",
          "100% trace sampling at high RPS",
          "No observability because too expensive",
          "Debug logging enabled in production"),
    ],
}


def main():
    for week, questions in WEEKS.items():
        path = ROOT / f"weeks/week-{week:02d}/interview-questions/01-fundamentals-qa.md"
        existing = path.read_text(encoding="utf-8")
        idx = existing.find("## Q011:")
        if idx == -1:
            raise ValueError(f"Q011 not found in week {week}")
        tail = existing[idx:]

        parts = [HEADER.format(week=week)]
        for i, item in enumerate(questions, 1):
            parts.append(QA_TEMPLATE.format(num=i, **item))

        path.write_text("".join(parts) + tail, encoding="utf-8")
        print(f"Week {week:02d} Q001-Q010 deepened")


if __name__ == "__main__":
    main()
