"""Hand-crafted premium Q011–Q030 for Weeks 3–4."""

from premium_qa_data import q

WEEK3_Q011_Q030 = [
    q("Hexagonal Architecture Ports", "Hexagonal", "Common",
      "Explain ports and adapters in Clean/Hexagonal architecture.",
      "Ports are interfaces the application defines (inbound/outbound). Adapters implement them — SQL adapter, REST adapter, message adapter.",
      "**Dependency rule:** Application core depends on port abstractions; infrastructure implements adapters.\n\n**Example:** `IOrderRepository` port, `SqlOrderRepository` adapter.\n\n**Architect:** Enables testing with in-memory adapters; swap ERP adapter without domain change.",
      "Ports/adapters is interview vocabulary for clean boundaries.",
      "Driving vs driven ports? — Inbound (API) vs outbound (DB, messaging).",
      "How many adapters per port? — Multiple implementations valid (cache decorator).",
      "Domain references SqlClient package",
      "Adapter leaks EF entities to API",
      "Port interface mirrors entire database"),
    q("Application Layer Use Cases", "Clean Arch", "Common",
      "What belongs in the application layer?",
      "Use case orchestration: command/query handlers, transaction boundaries, authorization checks, DTO mapping — not business rules.",
      "**Contains:** `CreateOrderHandler`, validators, unit of work coordination.\n\n**Not:** HTTP concerns, SQL, domain invariants (those in domain).\n\n**Architect:** Thin handlers — delegate to domain methods.",
      "Application layer is orchestration not logic dump.",
      "Application service vs handler? — MediatR handler is application service unit.",
      "Cross-cutting in behaviors? — Pipeline behaviors for logging/validation.",
      "Business rules in handler if/else",
      "DbContext in application layer interface",
      "God handler 500 lines"),
    q("Domain Layer Purity Rules", "DDD", "Very Common",
      "What must NOT be in the domain layer?",
      "No EF attributes, no HTTP, no configuration, no DTOs, no infrastructure interfaces with tech details.",
      "**Domain has:** Entities, value objects, domain events, domain services, repository interfaces (optional purist debate).\n\n**Architect:** Enforce with architecture tests (NetArchTest.Rules).\n\n**Violation smell:** `using Microsoft.EntityFrameworkCore` in Domain project.",
      "Domain purity enables testability and longevity.",
      "Anemic domain still in domain project? — Rich behavior required not just POCOs.",
      "Domain events vs integration events? — Domain inside; integration at boundary.",
      "EF Core attributes on entities",
      "HttpClient in domain service",
      "Domain depends on Infrastructure project"),
    q("Infrastructure Layer Boundaries", "Clean Arch", "Common",
      "Infrastructure layer responsibilities?",
      "Implements repositories, EF mappings, external API clients, message publishers, file storage — all driven adapters.",
      "**One Infrastructure project or per-bounded-context?** Start one; split when boundaries clear.\n\n**Architect:** Infrastructure references Application/Domain — never reverse.",
      "Infrastructure is replaceable detail.",
      "DbContext location? — Always Infrastructure.",
      "Integration tests on Infrastructure? — Testcontainers for SQL.",
      "Business logic in repository",
      "Infrastructure referenced by Domain",
      "Leaking IQueryable to application"),
    q("Thin Controllers and Endpoints", "Presentation", "Common",
      "How thin should API controllers be?",
      "Map request → command/query → send to mediator → map result to HTTP. No business logic.",
      "```csharp\n[HttpPost]\npublic async Task<IActionResult> Create(CreateOrderRequest req)\n    => Ok(await _mediator.Send(req.ToCommand()));\n```\n\n**Architect:** Controller knows HTTP; application knows use cases.",
      "Fat controllers are maintainability debt.",
      "Minimal API same rule? — Delegate to mediator in lambda.",
      "Filter vs controller validation? — Input format in filter; business in handler.",
      "Controller calls 5 repositories",
      "Try/catch per action with custom errors",
      "Controller builds SQL"),
    q("Cross-Cutting Middleware vs Behaviors", "Design", "Common",
      "Middleware vs MediatR pipeline behaviors?",
      "Middleware: HTTP pipeline (auth, correlation, exception). Behaviors: per-request use case wrapper (validation, logging, transactions).",
      "**Order:** Middleware first; behaviors around handler.\n\n**Architect:** Don't duplicate validation in both middleware and handler.",
      "Clear placement reduces duplicate cross-cutting code.",
      "OpenTelemetry span per behavior? — Yes for handler-level visibility.",
      "Transaction behavior? — UnitOfWork behavior wraps handler.",
      "Same validation middleware and FluentValidation",
      "Behavior order undocumented",
      "Business rules in logging behavior"),
    q("FluentValidation Placement", "Validation", "Common",
      "Where run FluentValidation in Clean Architecture?",
      "Validate commands/queries in application layer — MediatR `ValidationBehavior` before handler.",
      "**Not in:** Domain for input format (null, length) — domain validates invariants (cannot ship cancelled order).\n\n**Architect:** Validation rules colocated with command class or separate validator class per team standard.",
      "Input validation vs domain invariants — know both.",
      "Api behavior automatic validation? — ModelState for API models separate from domain commands.",
      "Validate in controller and handler duplicate?",
      "Domain exception for invalid email format",
      "No validation on internal commands",
      "500 lines in one validator class"),
    q("Mapping Strategy ADR", "Design", "Common",
      "AutoMapper vs manual mapping — architect decision?",
      "AutoMapper: large DTO surface, convention-based — speed. Manual: complex aggregates, explicit control, easier debug.",
      "**Architect:** Mapperly source generator middle ground — compile-time.\n\n**Rule:** Map at boundaries only — never map entity to entity across contexts.\n\n**Review:** Mapping profiles in PR review — silent null mapping bugs.",
      "Mapping is boundary concern not domain.",
      "Bidirectional map entities? — Dangerous — one direction preferred.",
      "Projection in repository? — Select DTO in query for read side.",
      "AutoMapper everywhere including domain",
      "Map GET mutates entity accidentally",
      "No tests on critical mappings"),
    q("Global Exception Handling", "API Design", "Common",
      "Design global exception handling for .NET API?",
      "Middleware catches exceptions → maps domain exceptions to HTTP status → ProblemDetails.",
      "**Mapping:** `OrderNotFoundException` → 404. `ValidationException` → 400. Unknown → 500 logged with correlation ID.\n\n**Architect:** Domain exceptions carry no HTTP knowledge; middleware translates.",
      "Consistent errors improve client and ops experience.",
      "ExceptionHandlerMiddleware vs filter? — Middleware catches all pipeline.",
      "Development vs prod detail? — Stack trace dev only.",
      "catch(Exception) return 200",
      "Different error shape per team",
      "Log same exception 5 times"),
    q("Result Pattern vs Exceptions", "Design", "Common",
      "When `Result<T>` instead of exceptions for flow control?",
      "Expected failures (not found, conflict) → Result. Exceptional failures (null ref, DB down) → throw.",
      "**Architect:** Result in application API reduces exception overhead for business cases.\n\n**Library:** FluentResults, ErrorOr, or custom `Result<T>`.\n\n**Don't:** Result for everything — exceptions still valid.",
      "Flow control style is team consistency choice.",
      "Railway oriented programming? — Bind/Map on Result chains.",
      "HTTP mapping from Result? — Extension ToActionResult().",
      "Exception for validation expected case",
      "Result ignored without check",
      "Mixed Result and throw randomly"),
    q("Specification Pattern", "Patterns", "Occasional",
      "Specification pattern for complex queries?",
      "Encapsulate query criteria in reusable spec objects — `ActiveOrdersSpec`, compose with And/Or.",
      "**Benefits:** DRY query logic, testable criteria, repository stays clean.\n\n**Architect:** Use when same filter in multiple handlers; avoid for one-off simple queries.",
      "Specification reduces repository method explosion.",
      "Ardalis.Specification library? — Popular EF integration.",
      "Spec in domain or infrastructure? — Domain defines; infra implements.",
      "GetOrdersByStatusAndDate method per combo",
      "IQueryable leaked to application",
      "Untestable 200-line LINQ in handler"),
    q("Unit of Work with EF Core", "Persistence", "Common",
      "Unit of Work pattern with DbContext in .NET?",
      "DbContext is UoW — `SaveChangesAsync` commits transaction. One UoW per request scope.",
      "**Architect:** Single `SaveChanges` per request unless explicit batch. Repository + UoW abstraction optional — DbContext often sufficient.\n\n**Multiple contexts:** Distributed transaction avoided — saga instead.",
      "Transaction boundary clarity prevents partial commits.",
      "Explicit Database.BeginTransaction? — When multiple SaveChanges need one TX.",
      "Retry on SaveChanges failure? — Execution strategy for transient SQL.",
      "SaveChanges in loop per item",
      "Multiple DbContext same request uncoordinated",
      "Long transaction with HTTP call inside"),
    q("Integration vs Unit Test Layers", "Testing", "Common",
      "Testing strategy per Clean Architecture layer?",
      "Domain: pure unit tests. Application: handler tests with mocked ports. Infrastructure: integration tests (Testcontainers). API: contract/E2E selective.",
      "**Architect:** Testing pyramid — many fast domain tests, fewer E2E.\n\n**WebApplicationFactory:** API integration without full browser.",
      "Test placement mirrors architecture boundaries.",
      "Architecture tests? — NetArchTest enforce layer rules.",
      "Testcontainers SQL? — Real DB integration in CI.",
      "E2E only no unit tests",
      "Mock entire domain in unit tests",
      "Tests hit production database"),
    q("Modular Monolith Modules", "Architecture", "Common",
      "Design modules in modular monolith?",
      "Separate projects per module (Orders, Billing) with explicit public API — internal classes invisible.",
      "**Communication:** Module interface or domain events in-process.\n\n**Architect:** Stepping stone to microservices — boundaries already drawn.",
      "Modular monolith defers distributed complexity.",
      "Shared database modules? — Schema separation or table prefixes.",
      "Extract module to service? — When team and scale justify.",
      "Everything public internal classes",
      "Circular module references",
      "Shared EF DbContext god context"),
    q("Vertical Slice vs Layers", "Architecture", "Very Common",
      "Team debates vertical slice vs horizontal layers — guidance?",
      "Layers: shared technical grouping. Vertical slice: feature folders (CreateOrder, ShipOrder) with handler + validator + endpoint together.",
      "**Architect:** Vertical slice improves feature velocity in large teams. Layers familiar for CRUD enterprise.\n\n**Hybrid common:** Vertical slice folders inside application layer.",
      "Organization should match change frequency.",
      "Jimmy Bogard vertical slice? — Reference architecture inspiration.",
      "Shared kernel between slices? — Minimize — shared value objects only.",
      "Religious layers only for 3 endpoints",
      "Vertical slice with no layer rules at all",
      "Copy-paste between slices"),
    q("CQRS Without Event Sourcing", "CQRS", "Common",
      "CQRS without event sourcing — when and how?",
      "Separate read models (queries) from write models (commands) — same database OK initially.",
      "**Start:** Different handlers and DTOs; optimize read queries with projections.\n\n**Avoid:** Separate databases day one without need.\n\n**Architect:** Logical CQRS first; physical split when read scale demands.",
      "CQRS ≠ event sourcing — common confusion.",
      "Read model rebuild? — Without ES, from current DB state.",
      "MediatR natural fit? — IRequest handlers per command/query.",
      "CQRS with two databases day one",
      "Confuse CQRS with CRUD split only names",
      "No sync strategy read/write"),
    q("MediatR Pipeline Behaviors", "Patterns", "Common",
      "Order and examples of MediatR pipeline behaviors?",
      "Validation → Logging → Transaction → Handler. Behaviors implement `IPipelineBehavior<TRequest,TResponse>`.",
      "**Architect:** Open generic behaviors registered once. Ordering via `Order` property or registration order.\n\n**Test:** Mock pipeline or test behavior in isolation.",
      "Pipeline is clean cross-cutting for use cases.",
      "Pre-processor vs behavior? — Behaviors wrap entire pipeline.",
      "Notification handlers? — Domain events in-process.",
      "Duplicate transaction in behavior and handler",
      "Behavior swallows exceptions",
      "10 behaviors deep opaque pipeline"),
    q("Feature Flags in Clean Architecture", "Release", "Common",
      "Feature flags without polluting domain?",
      "Check flag in application layer or infrastructure adapter — domain stays flag-agnostic.",
      "**Providers:** Azure App Configuration, LaunchDarkly.\n\n**Architect:** Flag drives adapter selection or handler branch — not `if (flag)` scattered in domain entity.",
      "Flags decouple deploy from release.",
      "Kill switch pattern? — Disable feature without redeploy.",
      "Flag debt cleanup? — Remove flags after full rollout.",
      "Feature flag in domain entity method",
      "100 permanent flags",
      "No monitoring per flag evaluation"),
    q("API Contract Versioning", "API Design", "Common",
      "Version DTOs and handlers together?",
      "V2 command/DTO separate from V1 — shared domain where possible. Handlers may diverge per version.",
      "**Architect:** Controllers map v1/v2 routes to version-specific commands. Domain aggregates version-agnostic when possible.\n\n**Deprecation:** Sunset header on v1 responses.",
      "Contract versioning is client empathy.",
      "OpenAPI per version? — Swagger doc v1 and v2.",
      "Shared handler both versions? — Risky — separate clearer.",
      "Break DTO without version",
      "Domain changes for API tweak only",
      "Infinite version support"),
    q("When to Simplify Architecture", "Pragmatism", "Very Common",
      "When would you NOT use Clean Architecture?",
      "Internal admin CRUD 5 endpoints, prototype, throwaway — simple 3-layer or even minimal API + DbContext is fine.",
      "**Architect honesty:** CA has ceremony cost — justify with team size, lifespan, complexity.\n\n**Signals for CA:** Multiple integrations, complex domain rules, 5+ year lifespan, multiple teams.\n\n**Graduate into CA** when pain appears — not day-one mandate for all apps.",
      "Pragmatism earns trust in architecture reviews.",
      "Strangler to CA? — Extract domain gradually from monolith.",
      "Document simplification ADR? — Yes — explain why not CA.",
      "CA for every console utility",
      "Big Design Up Front CA weeks before code",
      "Shame teams for simple layering"),
]

WEEK4_Q011_Q030 = [
    q("Chain of Responsibility", "Behavioral", "Common",
      "Chain of Responsibility for request validation pipeline?",
      "Each handler validates one concern, passes to next — composable validation without god method.",
      "**Example:** Auth check → rate limit → schema validate → business handler.\n\n**Architect:** ASP.NET middleware is chain of responsibility at HTTP level.",
      "Chain composes cross-cutting steps cleanly.",
      "Pipeline vs chain? — Similar concepts different scales.",
      "Short-circuit on failure? — Stop chain return error.",
      "God validator 50 checks",
      "Chain order wrong silent bypass",
      "No test per chain link"),
    q("Command Pattern with Handlers", "Behavioral", "Very Common",
      "Command pattern in .NET with MediatR?",
      "Command object encapsulates request; handler executes — single responsibility per use case.",
      "**Benefits:** Testable units, discoverable handlers, pipeline behaviors.\n\n**Architect:** One command per write operation — not generic `Execute(string action)`.",
      "Commands are application layer backbone.",
      "ICommand vs IRequest? — MediatR IRequest naming.",
      "Undo command? — Memento + command for editor apps.",
      "God command with 20 properties optional",
      "Handler calls handler directly not mediator",
      "No idempotency on retryable commands"),
    q("State Pattern for Order Workflow", "Behavioral", "Common",
      "State pattern vs switch for order status?",
      "Each state class implements transitions — `ConfirmedState.Ship()` vs giant switch on enum.",
      "**When:** Many states, complex transition rules.\n\n**Modern C#:** Switch expressions OK for simple; State pattern for rich behavior per state.\n\n**Architect:** Align with domain-driven design — `order.Confirm()` delegates to state.",
      "State pattern tames workflow complexity.",
      "Stateless state pattern? — Stateless singleton state objects possible.",
      "Persist state how? — Status enum + behavior from factory.",
      "switch on status 40 cases",
      "Invalid transitions throw generic Exception",
      "State logic in controller"),
    q("Template Method Pattern", "Behavioral", "Occasional",
      "Template Method in export/report generation?",
      "Base class defines algorithm skeleton; subclasses override steps — `FetchData`, `Format`, `Deliver`.",
      "**Architect:** Prefer composition (strategy for steps) over inheritance when possible — .NET favors composition.\n\n**Use inheritance template** when framework defines lifecycle (ASP.NET middleware base).",
      "Template Method vs Strategy — inheritance vs composition.",
      "Hook methods? — Optional override points in template.",
      "Virtual methods fragility? — Document extension points.",
      "Deep inheritance hierarchy",
      "Template with 15 abstract methods",
      "Subclass breaks base invariant"),
    q("Proxy Pattern for Lazy Loading", "Structural", "Occasional",
      "Proxy for lazy loading expensive dependency?",
      "Proxy implements same interface, defers real object creation until first use — caching proxy, remote proxy, protection proxy.",
      "**Architect:** DI can register decorator proxy. EF lazy loading is proxy-based — understand N+1 risk.\n\n**Remote proxy:** gRPC client wrapper.",
      "Proxy controls access and initialization.",
      "DispatchProxy in .NET? — Dynamic proxy for interfaces.",
      "Virtual proxy vs remote? — Know types for interviews.",
      "EF lazy loading N+1 unnoticed",
      "Proxy without interface",
      "Hidden side effects in proxy"),
    q("Composite Pattern", "Structural", "Occasional",
      "Composite pattern real enterprise example?",
      "Tree structures treated uniformly — org chart, menu permissions, file system folders.",
      "**Component interface:** `GetTotal()`, `Render()` on leaf and composite alike.\n\n**Architect:** Useful for hierarchical permissions and nested product categories.",
      "Composite models part-whole hierarchies.",
      "Iterator over composite? — Recursive traversal or stack-based.",
      "Cycle detection? — Guard parent pointers in mutable trees.",
      "Special case every leaf in client code",
      "Composite allows cycles",
      "No interface for leaf vs composite"),
    q("Bridge Pattern", "Structural", "Occasional",
      "Bridge pattern vs Strategy — difference?",
      "Bridge splits abstraction and implementation hierarchies independently — `Message` abstraction × `Sender` implementation (Email, SMS).",
      "**Strategy:** interchangeable algorithm. **Bridge:** structural decoupling of two dimensions.\n\n**Architect:** Bridge when both hierarchies evolve independently.",
      "Naming confusion common in interviews.",
      "Adapter vs Bridge? — Adapter fixes interface; Bridge designs separation upfront.",
      "DI replaces some Bridge uses? — Often inject implementation.",
      "Multiply inheritance instead of bridge",
      "Confuse with Strategy always",
      "Two dimensions coupled in one class"),
    q("Memento for Audit Trail", "Behavioral", "Occasional",
      "Memento pattern for undo/audit?",
      "Capture object state externally without exposing internals — undo in editor, audit snapshots.",
      "**Enterprise:** Event sourcing is scalable memento — state as event log.\n\n**Architect:** Memento for simple undo; event sourcing for audit at scale.",
      "Audit requirements drive pattern choice.",
      "Caretaker role? — Stores mementos without peeking.",
      "Immutable memento? — Safer for audit history.",
      "Expose all fields for audit copy",
      "Unbounded memento memory",
      "Memento instead of domain events at scale"),
    q("Visitor vs Pattern Matching", "Behavioral", "Common",
      "When Visitor still needed in modern C#?",
      "Open hierarchy, many operations across types — tax calculation on expression tree. Pattern matching for closed simple hierarchies.",
      "**Visitor:** Add new operation without changing element classes. **Pattern matching:** Add new types requires updating switches (exhaustiveness helps).\n\n**Architect:** Prefer pattern matching for `OrderStatus`; Visitor for compiler/AST style problems.",
      "Modern C# reduces Visitor need but not eliminate.",
      "Double dispatch explained? — Visitor achieves via Accept method.",
      "Source generators for visitors? — Reduce boilerplate.",
      "Visitor for 3-type hierarchy",
      "Pattern matching without exhaustiveness",
      "Visitor every tax line item"),
    q("Repository Pattern Debate", "Enterprise", "Very Common",
      "Repository pattern — still use with EF Core?",
      "Debate continues. EF DbContext already repository+UoW. Generic `IRepository<T>` often leaky abstraction.",
      "**Architect position:** Repository per aggregate meaningful interface — `IOrderRepository.GetWithLines(id)` — not generic CRUD on 50 entities.\n\n**Skip when:** Simple app, DbContext directly in handler acceptable for small teams.",
      "Repository should add value not pass-through.",
      "Specification + repository? — Compose query logic.",
      "Cosmos repository? — Same interface different adapter.",
      "IRepository<T> all entities",
      "Repository returns IQueryable",
      "Repository with no aggregate focus"),
    q("Unit of Work Enterprise Pattern", "Enterprise", "Common",
      "Unit of Work coordinating multiple repositories?",
      "One transaction across repositories sharing same DbContext/session.",
      "**EF:** Single DbContext scope = UoW. Multiple repos inject same context.\n\n**Architect:** `IUnitOfWork.CommitAsync()` abstraction when testing commit behavior.",
      "Transaction boundary is architect concern.",
      "Distributed UoW? — Avoid — saga pattern instead.",
      "Mock UoW in tests? — Fake in-memory UoW for unit tests.",
      "SaveChanges per repository method",
      "UoW without clear scope",
      "Mock UoW 10 layers deep"),
    q("Domain Events and Outbox", "Enterprise", "Very Common",
      "Raise domain events and publish reliably?",
      "Raise events in aggregate; dispatch after SaveChanges; outbox table for reliable publish to broker.",
      "**Flow:** Handler saves aggregate + outbox row same transaction → relay publishes to Service Bus.\n\n**Architect:** Never publish before commit — lost message or inconsistent state.",
      "Reliable messaging is architect integration pattern.",
      "MediatR notification vs domain event? — Domain in aggregate; MediatR dispatches in-process.",
      "Transactional outbox library? — MassTransit, custom relay.",
      "Publish before SaveChanges",
      "No idempotent consumer",
      "Domain event = integration event same class"),
    q("Saga Orchestration Introduction", "Enterprise", "Common",
      "Orchestrated saga for checkout — components?",
      "Orchestrator coordinates: reserve inventory → charge payment → confirm order → compensate on failure.",
      "**Implement:** Durable Functions, MassTransit, custom state machine.\n\n**Architect:** Choreography for simple; orchestration when visibility and compensation complex.",
      "Sagas replace 2PC in microservices.",
      "Compensating transaction? — Refund, release inventory.",
      "Saga timeout? — Auto-compensate stuck steps.",
      "Sync chain 5 services no compensation",
      "Saga state only in memory",
      "No idempotency on saga steps"),
    q("CQRS with Repository Together", "Patterns", "Common",
      "CQRS handlers with repositories — read side optimization?",
      "Write handler uses aggregate repository. Read handler uses Dapper/raw SQL or denormalized view — skip domain load.",
      "**Architect:** Read model can bypass domain — that's the point. Don't force repository on queries needing joins.",
      "CQRS read side freedom is performance win.",
      "Separate read database? — When scale requires.",
      "Projections from events? — With event sourcing.",
      "Load full aggregate for list screen",
      "Same model read write forever",
      "ORM on complex report query"),
    q("God Object Anti-Pattern", "Anti-Pattern", "Common",
      "Identify and refactor God Object?",
      "Class knowing/doing too much — `ApplicationService` with 80 methods.",
      "**Refactor:** Extract by feature command handlers, vertical slices, domain services by capability.\n\n**Architect:** Code review rule max methods per class; SonarQube cognitive complexity gate.",
      "God objects signal missing boundaries.",
      "Facade vs God Object? — Facade coordinates subservices doesn't implement all logic.",
      "Extract class refactoring? — Safe incremental.",
      "Ignore 5000-line service",
      "Add method 81 to god class",
      "No module ownership"),
    q("Spaghetti Callback Anti-Pattern", "Anti-Pattern", "Common",
      "Spaghetti callbacks in async code — fix?",
      "Nested callbacks → async/await, or events, or reactive streams.",
      "**Legacy:** Callback hell in old JS/Node patterns. .NET: `ContinueWith` chains — use async/await.\n\n**Architect:** Mandate async/await; analyzers flag ContinueWith.",
      "Control flow clarity is maintainability.",
      "Reactive Extensions? — When stream processing fits.",
      "Channel for pipeline? — Structured producer-consumer.",
      "ContinueWith chains in new code",
      "async void except events",
      "Fire-and-forget Task no log"),
    q("Service Locator Anti-Pattern", "Anti-Pattern", "Common",
      "Why service locator is anti-pattern vs DI?",
      "Hidden dependencies — `ServiceLocator.Get<IRepo>()` — untestable, unclear constructor contract.",
      "**Architect:** Constructor injection only in application code. Service locator acceptable only in legacy bridge code being removed.",
      "Explicit dependencies are architect standard.",
      "IServiceProvider direct inject? — Service locator smell if abused in domain.",
      "Factory vs locator? — Factory creates known types; locator hides.",
      "Static ServiceLocator class",
      "Resolve in domain entity",
      "Test can't mock dependencies"),
    q("Pattern Selection ADR Framework", "Process", "Common",
      "Framework for choosing design pattern in review?",
      "Problem statement → forces → pattern candidates → trade-offs → decision → consequences.",
      "**Questions:** Variation in algorithm (Strategy)? Tree structure (Composite)? Object creation (Factory)? Integration reliability (Outbox)?\n\n**Architect:** Simplest solution first — pattern when force justifies complexity.",
      "ADR documents pattern choice prevents gold plating.",
      "YAGNI vs pattern? — Don't add pattern for one use case.",
      "Team pattern glossary? — Shared vocabulary.",
      "Pattern because blog post",
      "15 patterns one feature",
      "No ADR for Outbox adoption"),
    q("Flyweight Pattern", "Structural", "Occasional",
      "Flyweight pattern — when relevant in .NET?",
      "Share intrinsic state across many fine-grained objects — character formatting, icon caches, repeated metadata keys.",
      "**Architect:** Rare in business LOB apps. Useful when millions of similar objects — memory optimization.\n\n**.NET:** string interning is flyweight-like.",
      "Know flyweight — don't force into CRUD apps.",
      "Intrinsic vs extrinsic state? — Flyweight holds shared; client passes extrinsic.",
      "Object pool vs flyweight? — Pool reuses instances; flyweight shares state.",
      "Flyweight for 50 order objects",
      "Thread-unsafe shared flyweight",
      "Premature flyweight complexity"),
    q("Over-Engineering Patterns Smell", "Pragmatism", "Very Common",
      "Signs pattern use is over-engineering?",
      "Abstract factory for one implementation, strategy with one strategy, observer for single listener.",
      "**Architect:** Refactor when abstraction cost exceeds change frequency. Rule of three — third duplication justifies abstraction.\n\n**Interview:** Show judgment — patterns are tools not goals.",
      "Senior architects know when to stop abstracting.",
      "Rule of three? — Third similar case extract abstraction.",
      "Delete abstraction? — Valid refactor when YAGNI wins.",
      "Interface per class",
      "Factory for single type",
      "Shame simple code"),
]

ALL_WEEKS_3_4_Q011_Q030 = {3: WEEK3_Q011_Q030, 4: WEEK4_Q011_Q030}
