"""Hand-crafted premium Q001–Q010 for AWS / multi-cloud weeks 17–20."""

from premium_qa_data import q

WEEK_17 = [
    q("AWS Well-Architected Framework", "AWS WAF", "Very Common",
      "What are the six AWS WAF pillars and how do you use them in reviews?",
      "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability. Score each design decision; prioritize by business risk.",
      "AWS WAF adds **Sustainability** as a sixth pillar vs Azure's five.\n\n1. **Operational Excellence** — IaC, runbooks, CI/CD, observability\n2. **Security** — IAM least privilege, encryption, GuardDuty\n3. **Reliability** — Multi-AZ, auto scaling, backup/DR\n4. **Performance Efficiency** — Right instance types, caching, serverless where fit\n5. **Cost Optimization** — Reserved/Savings Plans, rightsizing, lifecycle policies\n6. **Sustainability** — Graviton, efficient regions, workload scheduling\n\n**Review process:** Map each component to pillars; payment API leads Security + Reliability.",
      "Structured WAF reviews beat listing service names.",
      "AWS WAF vs Azure WAF? — Same philosophy; sustainability explicit on AWS.",
      "Well-Architected Tool? — Free workload review in console — document findings.",
      "Security-only reviews",
      "Ignoring cost pillar on prod estates",
      "No remediation priorities"),
    q("AWS Organizations and OU Strategy", "Governance", "Very Common",
      "Design AWS Organizations for 5 product teams with SOC 2 requirements.",
      "Root org → Security OU (audit/logging) + Workloads OU. Per team: prod and nonprod accounts. SCPs at OU level. Central security account for CloudTrail/Config.",
      "**Structure:**\n```\nOrganization\n├── Security OU (audit, log archive, security tooling)\n└── Workloads OU\n    ├── Team A (prod + nonprod accounts)\n    └── Team B (prod + nonprod accounts)\n```\n\n**SOC 2:** Consolidated billing, SCP deny root API keys, mandatory CloudTrail to log archive, break-glass separate from daily IAM users.\n\n**Architect:** Account = blast radius + billing boundary — not one account per microservice.",
      "Organizations design is foundational — painful to retrofit.",
      "Control Tower vs manual org? — Control Tower accelerates landing zone — customize guardrails.",
      "How many accounts? — Enough isolation; not hundreds unmanaged.",
      "Single prod account for all teams",
      "No centralized audit logging",
      "SCPs only on root without testing"),
    q("IAM Policies vs SCPs vs Permission Boundaries", "Governance", "Very Common",
      "Difference between IAM policy, SCP, and permission boundary?",
      "IAM policy: what identity can do. SCP: max permissions for accounts/OUs (guardrail). Permission boundary: max permissions for IAM user/role.",
      "**IAM policy** on role `DeployRole`: allows `ecs:UpdateService` on specific cluster.\n\n**SCP** on Workloads OU: denies `ec2:RunInstances` without tag `Environment` — applies to all identities including admin.\n\n**Permission boundary** on developer role: caps even if admin attaches broader policy.\n\n**Architect:** SCPs for org-wide guardrails; IAM for workload least privilege; boundaries for delegated admin scenarios.",
      "Confusing IAM layers fails senior AWS interviews.",
      "Resource-based policies? — S3 bucket policy — different axis — know cross-account access.",
      "IAM Access Analyzer? — Finds unintended external access.",
      "SCP as only security control",
      "Admin users without MFA",
      "Overly broad `*` actions on roles"),
    q("AWS Regions and Availability Zones", "Reliability", "Very Common",
      "When deploy multi-AZ vs single-AZ? Cost trade-off?",
      "Multi-AZ for production RDS, ALB, ECS/EKS across AZs. Single-AZ for dev. Multi-AZ RDS ~2x database cost — worth for revenue workloads.",
      "**AZ:** isolated datacenters within region.\n\n**Region:** geographic — choose for latency, compliance (eu-west-1 for GDPR).\n\n**SLA math:** Single-AZ RDS has lower SLA than Multi-AZ.\n\n**Architect:** Document RTO/RPO per tier; Multi-AZ protects AZ failure not region failure — DR is separate.",
      "AZ vs region confusion is common failure mode.",
      "Local Zones / Wavelength? — Edge extensions — latency-sensitive use cases.",
      "Opt-in regions? — Enable before deploy — automation must handle.",
      "Single-AZ RDS for payment prod",
      "No cross-region DR plan",
      "Random region without compliance check"),
    q("AWS Migration and CAF", "CAF", "Common",
      "Summarize AWS Cloud Adoption Framework for enterprise migration.",
      "Envision → Align → Map → Migrate → Optimize → Scale. Architects lead Map/Migrate waves; platform team owns landing zone.",
      "**Map:** Application Portfolio Service (APS), 7 Rs (rehost, replatform, refactor...).\n\n**Migrate:** Waves by risk and dependency — not big-bang.\n\n**Architect deliverable:** Migration plan with TCO, wave schedule, rollback criteria per workload.",
      "CAF shows enterprise adoption beyond single-app deploy.",
      "Migration Hub / Application Discovery Service? — Discovery and tracking.",
      "Rehost vs refactor decision? — Document per workload in ADR.",
      "Lift-and-shift everything without assessment",
      "No wave prioritization",
      "Skip landing zone"),
    q("AWS Cost Allocation Tags", "FinOps", "Very Common",
      "Mandatory tags for enterprise AWS? How enforce?",
      "Environment, CostCenter, Owner, Application. Enforce via SCP + Config rules + tag-on-create IAM condition keys. Cost Explorer allocation reports.",
      "**Enforcement:**\n- SCP: require tags on resource creation\n- AWS Config: noncompliant resource report\n- Lambda remediation for drift\n\n**Architect:** Tags drive chargeback, Instance Scheduler shutdown, and incident routing.",
      "Tags are FinOps foundation on AWS.",
      "Tag propagation from org? — Tag policies in Organizations.",
      "Cost anomaly detection? — Cost Anomaly Detection alerts.",
      "Optional tags nobody uses",
      "No SCP tag enforcement",
      "Untagged prod resources after 30 days"),
    q("AWS Landing Zone (Control Tower)", "Landing Zone", "Very Common",
      "Platform landing zone vs application account in AWS?",
      "Platform: shared networking (Transit Gateway), security tooling, logging — central team. Application accounts: workload deploy with guardrails from Control Tower.",
      "**Control Tower provides:** Account Factory, guardrails (SCPs), centralized logging account.\n\n**Application team gets:** Account with VPC from blueprint, deploy ECS/RDS within guardrails.\n\n**Architect:** Start from Control Tower + customize — don't reinvent org structure.",
      "Landing zone vocabulary expected in AWS architect interviews.",
      "Terraform vs CloudFormation for LZ? — Team skill; CloudFormation native.",
      "Brownfield? — Import accounts into org; retrofit SCPs carefully.",
      "Every team builds own Transit Gateway",
      "No centralized CloudTrail",
      "Landing zone never updated post-launch"),
    q("IAM Custom Policies and Roles", "Security", "Common",
      "When create custom IAM policy vs AWS managed policy?",
      "Custom when managed too broad. CI/CD role: `ecs:UpdateService` + `ecr:GetAuthorizationToken` only — not PowerUserAccess.",
      "**Pattern:** `GitHubActionsDeployRole` with OIDC trust + minimal policy on one cluster.\n\n**Principle:** Least privilege per workload. Prefer roles over long-lived access keys.\n\n**Architect:** IAM Access Analyzer in CI; no access keys in repos.",
      "Custom IAM shows production governance experience.",
      "IAM Roles Anywhere? — On-prem workloads need AWS creds — certificate-based.",
      "Cross-account roles? — Hub account assumption pattern for centralized ops.",
      "PowerUserAccess for CI/CD",
      "Long-lived IAM user access keys",
      "Root account for daily operations"),
    q("AWS Budgets and Cost Explorer", "FinOps", "Common",
      "Prevent surprise AWS bill for new product team?",
      "AWS Budgets at 80%/100%, Cost Anomaly Detection, Instance Scheduler for dev, Savings Plans for baseline, weekly rightsizing review.",
      "**Onboarding checklist:**\n- Budget per linked account\n- SCP deny expensive instance types in nonprod\n- CloudWatch log retention limits\n- Compute Optimizer recommendations monthly\n\n**Unit economics:** Track $/transaction as feature scales.",
      "FinOps is architect responsibility from day one.",
      "CUR vs Cost Explorer? — Cost and Usage Report for detailed analysis.",
      "RI vs Savings Plans? — SP more flexible for mixed compute.",
      "No budget alerts",
      "m5.24xlarge in dev accounts",
      "Unbounded CloudWatch Logs retention"),
    q("Choose AWS vs On-Premises", "Strategy", "Common",
      "Stakeholder asks 'why AWS?' — architect response framework?",
      "Agility, global reach, managed services reduce undifferentiated ops, pay-as-you-go for variable load. Honest TCO including egress, support, and ops labor — not 'always cheaper'.",
      "**When AWS wins:** Elastic scale, global footprint, serverless/event-driven, rapid experimentation.\n\n**When hybrid/on-prem:** Factory floor latency, sunk datacenter, strict data sovereignty without approved region.\n\n**Architect:** Hybrid common — Outposts or Direct Connect for extension.",
      "Balanced advocacy impresses executives.",
      "Repatriation? — Some workloads return on-prem — stay workload-driven.",
      "Egress in TCO? — Cross-AZ and internet egress often underestimated.",
      "Cloud lift without ops model change",
      "Ignoring data transfer costs",
      "100% cloud mandate without exceptions"),
]

WEEK_18 = [
    q("EC2 vs Lambda vs Fargate", "Compute", "Very Common",
      "When EC2 vs Lambda vs Fargate for .NET workload?",
      "EC2: full control, steady traffic, Windows/.NET Framework legacy. Lambda: event-driven, spiky, short requests. Fargate: containers without managing EC2 — middle ground for .NET Core APIs.",
      "**Lambda:** API Gateway + Lambda for low-traffic internal APIs; watch cold start and 15min limit.\n\n**Fargate:** ECS/EKS serverless tasks — .NET 8 containers, no EC2 patching.\n\n**EC2:** Always-on high RPS, WebSockets, custom AMIs.\n\n**Architect:** Default Fargate/ECS for containerized .NET Core; Lambda for async processors.",
      "Compute choice drives ops model and cost.",
      "Lambda .NET cold start? — Provisioned concurrency for latency-sensitive.",
      "App Runner? — Simpler than ECS for container web apps.",
      "Lambda for steady 10K RPS API",
      "EC2 for every cron job",
      "Ignoring Lambda concurrency limits"),
    q("ECS vs EKS Decision", "Compute", "Very Common",
      "Team wants Kubernetes. You have 3 microservices and 4 developers. Recommendation?",
      "ECS Fargate unless team has K8s operational maturity. EKS justified at 10+ services, multi-cloud K8s skill, or service mesh needs.",
      "**ECS pros:** AWS-native, simpler, lower ops overhead.\n\n**EKS pros:** Portable K8s, rich ecosystem, multi-cloud.\n\n**Architect:** Honest assessment — EKS tax is real (control plane cost, upgrades, add-ons). Start ECS; migrate to EKS when triggers hit.",
      "Right-sizing orchestration is senior architect judgment.",
      "EKS Fargate vs EC2 nodes? — Fargate reduces node ops; EC2 for GPU/custom.",
      "ECS Service Connect? — Service discovery without full mesh.",
      "EKS for 2 services because 'industry standard'",
      "No cluster upgrade plan",
      "Developers running kubectl to prod"),
    q("Lambda Cold Starts and Provisioned Concurrency", "Serverless", "Very Common",
      "User-facing API on Lambda has 2s cold starts. Options?",
      "Provisioned concurrency (cost), SnapStart for Java (not .NET), reduce package size, ARM Graviton, avoid VPC unless required, API Gateway caching, or move steady traffic to Fargate.",
      "**Architect analysis:** Cold start acceptable for async; not for sync user path at P99.\n\n**Mitigations:** Minimize init code, reuse HttpClient, lazy DI, smaller deployment package.\n\n**Trade-off:** Provisioned concurrency = always-on cost — compare to Fargate baseline.",
      "Serverless latency requires architect-level trade-offs.",
      "Lambda in VPC? — Adds ENI cold start — use VPC only when required.",
      "Lambda vs Lambda@Edge? — Edge for CloudFront-triggered only.",
      "Provisioned concurrency on all functions blindly",
      "Heavy DI container in Lambda init",
      "Ignore P99 latency in SLOs"),
    q("Auto Scaling Groups", "Compute", "Common",
      "Design ASG for variable traffic .NET API on EC2?",
      "ALB target tracking on request count or CPU; min 2 across AZs; scale-out fast, scale-in slow with cooldown; health checks on `/health`.",
      "**Policies:** Target tracking preferred over step scaling for web.\n\n**Architect:** Warm pool for faster scale-out on known events (Black Friday).\n\n**Mixed instances:** On-Demand base + Spot for burst capacity.",
      "ASG design ties to reliability and cost.",
      "Predictive scaling? — ML-based pre-scale before demand.",
      "Lifecycle hooks? — Graceful drain before terminate.",
      "Single instance ASG in prod",
      "Scale-in kills instances mid-request",
      "No ALB health check grace period"),
    q("Elastic Beanstalk When", "Compute", "Occasional",
      "When still recommend Elastic Beanstalk?",
      "Rapid .NET deploy without container/K8s ops; small teams; platform handles capacity/provisioning. Declining vs ECS/Fargate for new greenfield.",
      "**Good fit:** Internal tools, prototypes, teams avoiding Docker.\n\n**Avoid:** Complex microservices, custom networking, multi-region active-active.\n\n**Architect:** Honest — Beanstalk is underrated for simple web apps; not default for microservices.",
      "Knowing when NOT to use K8s shows maturity.",
      "Beanstalk .NET on Linux? — Supported — prefer over Windows workers for cost.",
      "Blue/green on Beanstalk? — Swap environment URLs.",
      "Beanstalk for 20 microservices",
      "Ignore platform deprecation notices",
      "No environment separation"),
    q("API Gateway + Lambda Pattern", "Serverless", "Very Common",
      "Design public REST API with API Gateway and Lambda. Key decisions?",
      "HTTP API vs REST API (cost/features), JWT authorizer vs Cognito, throttling per client, request validation, Lambda integration timeout 29s, structured logging, X-Ray tracing.",
      "**Architect checklist:**\n- WAF on API Gateway for public APIs\n- Usage plans + API keys for partners\n- Idempotency for POST from clients\n- DLQ on async invocations\n\n**Alternative:** ALB + Fargate if WebSockets or long requests.",
      "API Gateway is edge architecture decision.",
      "HTTP API vs REST API? — HTTP API cheaper; REST API more features.",
      "Lambda response streaming? — Large payloads — know limits.",
      "No throttling on public API",
      "29s timeout on long-running sync work",
      "Secrets in Lambda environment plaintext"),
    q("ALB vs NLB", "Networking", "Common",
      "Application Load Balancer vs Network Load Balancer?",
      "ALB: Layer 7, path/host routing, HTTP/HTTPS, WebSockets, Lambda targets. NLB: Layer 4, ultra-low latency, static IP, TCP/UDP, millions RPS.",
      "**ALB:** Default for .NET HTTP APIs behind ECS/EC2.\n\n**NLB:** Gaming, IoT, TLS passthrough, extreme performance.\n\n**Architect:** ALB + WAF for public web; NLB for non-HTTP protocols.",
      "Load balancer choice affects security and routing.",
      "Gateway Load Balancer? — Inline security appliances — niche.",
      "Cross-zone load balancing cost? — NLB charges per AZ — model in TCO.",
      "NLB for standard REST API unnecessarily",
      "ALB for raw TCP gaming traffic",
      "No connection draining on deploy"),
    q("Graviton (ARM) Instances", "Performance", "Common",
      "When recommend Graviton for .NET workloads?",
      ".NET 8+ runs well on ARM64. Graviton3 offers better price-performance for Linux containers and Lambda. Validate with load test before migration.",
      "**Benefits:** ~20-40% better price-performance for compatible workloads.\n\n**Caveats:** Native dependencies must support ARM; Windows Graviton limited.\n\n**Architect:** Pilot on nonprod; benchmark P99 latency and cost; Savings Plans after validation.",
      "Hardware choice is architect cost/perf lever.",
      "Lambda Graviton? — arm64 architecture flag.",
      "RDS Graviton? — Supported for many engines.",
      "Migrate without compatibility testing",
      "Assume all NuGet packages support ARM",
      "Ignore performance regression in P99"),
    q("Spot vs On-Demand Instances", "Cost", "Common",
      "When use Spot instances in production architecture?",
      "Fault-tolerant batch, CI runners, K8s node groups with diversification, render farms — NOT single-instance stateful primary without interruption handling.",
      "**Patterns:** Spot Fleet, mixed On-Demand + Spot ASG, Karpenter Spot provisioning.\n\n**Architect:** 2-minute interruption notice — workloads must checkpoint or drain.",
      "Spot is cost lever with architect safeguards.",
      "Spot placement score? — Choose pools with capacity.",
      "Capacity Rebalancing? — ASG replaces at-risk Spot instances.",
      "Spot for single-AZ primary database",
      "No interruption handling",
      "One instance type only — capacity risk"),
    q("Serverless Anti-Patterns", "Architecture", "Common",
      "Common serverless anti-patterns you've seen?",
      "Lambda for long sync chains, chatty Lambda-to-Lambda without queue, huge deployment packages, VPC everything, no DLQ, treating DynamoDB like SQL, ignoring concurrency account limits.",
      "**Architect remediation:**\n- Step Functions for orchestration\n- SQS between functions\n- Right-size memory (affects CPU)\n- Reserved concurrency on critical paths only\n\n**When to exit serverless:** Steady high RPS — Fargate often cheaper.",
      "Knowing anti-patterns shows production experience.",
      "Lambda monolith? — 10K lines in one function — split by trigger.",
      "Serverless framework lock-in? — Prefer SAM/CDK for AWS-native.",
      "15-function sync chain for checkout",
      "No idempotency on SQS consumer",
      "Ignore account concurrency soft limits"),
]

WEEK_19 = [
    q("VPC Design (Public/Private Subnets)", "Networking", "Very Common",
      "Design VPC for 3-tier .NET app (web, API, database)?",
      "Public subnets: ALB only. Private subnets: ECS/EC2 app tier. Isolated subnets: RDS. NAT Gateway per AZ (or NAT instance for cost at scale). VPC endpoints for S3/DynamoDB to avoid NAT egress.",
      "**CIDR planning:** /16 VPC, /24 per AZ per tier — room for growth.\n\n**Security:** NACLs stateless edge; security groups stateful per tier.\n\n**Architect:** No public IPs on app instances — ALB is sole public entry.",
      "VPC design is foundational AWS architect skill.",
      "IPv6 dual-stack? — Consider for future; plan CIDR carefully.",
      "Subnet calculator mistakes? — Overlap breaks peering.",
      "RDS in public subnet",
      "Single NAT Gateway (AZ SPOF)",
      "0.0.0.0/0 open on database SG"),
    q("S3 Storage Classes", "Storage", "Very Common",
      "Choose S3 storage class for backups, logs, and user uploads?",
      "Standard for frequent access uploads. Intelligent-Tiering for unknown patterns. Glacier Instant/Flexible for backups per RTO. Lifecycle policies automate transition.",
      "**Lifecycle example:** Logs → IA after 30d → Glacier after 90d → delete 365d.\n\n**Architect:** Model retrieval cost for Glacier — restore time affects DR drills.\n\n**Security:** Block public access at account level; bucket policies deny insecure transport.",
      "Storage class choice affects cost and DR.",
      "S3 Express One Zone? — Ultra-low latency single-AZ — know trade-off.",
      "Versioning + MFA delete? — Protect against ransomware on critical buckets.",
      "Standard for all backup data forever",
      "Public bucket for user uploads",
      "No lifecycle policy on log buckets"),
    q("RDS vs Aurora vs DynamoDB", "Data", "Very Common",
      "When RDS vs Aurora vs DynamoDB for order data?",
      "RDS/Aurora: relational orders with joins and transactions. Aurora: higher scale MySQL/Postgres with faster failover. DynamoDB: key-value access patterns at massive scale, not ad-hoc SQL reporting.",
      "**Decision tree:**\n- Complex queries + ACID → Aurora PostgreSQL\n- Simple key access 100K+ WPS → DynamoDB\n- SQL Server requirement → RDS SQL Server\n\n**Architect:** Start relational unless proven access pattern needs NoSQL.",
      "Database choice is hardest to reverse.",
      "Aurora Serverless v2? — Variable relational workload.",
      "DynamoDB single-table design? — Requires access pattern upfront design.",
      "DynamoDB for reporting-heavy OLTP",
      "RDS without Multi-AZ in prod",
      "Ignore connection pool limits on Lambda→RDS"),
    q("NAT Gateway vs VPC Endpoints", "Networking", "Common",
      "Reduce NAT Gateway costs for S3-heavy workload?",
      "Gateway endpoints for S3 and DynamoDB (free). Interface endpoints for other AWS services. Keep NAT only for true internet egress.",
      "**Cost:** NAT Gateway per-AZ hourly + per-GB — adds up at scale.\n\n**Architect:** Endpoint policy least privilege; private DNS for interface endpoints.\n\n**Pattern:** App in private subnet reaches S3 via gateway endpoint — no NAT traversal.",
      "Egress architecture is FinOps topic.",
      "Interface endpoint per AZ? — HA vs cost trade-off.",
      "Egress-only internet gateway? — IPv6 outbound pattern.",
      "All AWS API traffic through NAT",
      "No endpoint policies",
      "Ignore NAT data processing charges"),
    q("Route 53 Routing Policies", "DNS", "Common",
      "Route 53 policies for DR failover and geolocation?",
      "Failover: primary/secondary health checks. Geolocation: route EU users to eu-west-1. Weighted: canary traffic split. Latency: lowest latency region.",
      "**DR pattern:** Failover record with health check on primary ALB — secondary in passive region.\n\n**Architect:** DNS TTL affects failover speed — lower TTL before migration events.\n\n**Combine with:** Global Accelerator for static anycast entry.",
      "DNS is architect-level traffic management.",
      "Alias vs CNAME? — Alias to ALB/CloudFront free.",
      "Private hosted zones? — Internal service discovery.",
      "Geolocation without compliance review",
      "Health check on wrong endpoint",
      "TTL 86400 during migration weekend"),
    q("DynamoDB Partition Key Design", "NoSQL", "Very Common",
      "Design DynamoDB keys for orders table at 50K WPS?",
      "Partition key with high cardinality — `orderId` or composite `tenantId#orderId`. Avoid hot partitions (celebrity tenant). GSI for alternate access patterns.",
      "**Anti-pattern:** `status` as partition key — throttling on `PENDING`.\n\n**Patterns:** Write sharding with suffix, GSI for customerId lookup.\n\n**Architect:** Access patterns first — single-table design workshop before schema.",
      "DynamoDB failures are design failures.",
      "On-demand vs provisioned? — On-demand for unknown; provisioned + auto scaling for predictable.",
      "DAX? — Microsecond cache for read-heavy hot keys.",
      "Low-cardinality partition key",
      "Scan for reporting in production",
      "No GSI for secondary access pattern"),
    q("S3 Event Notifications", "Integration", "Common",
      "User uploads to S3 trigger virus scan and thumbnail. Architecture?",
      "S3 event → SQS (buffer) → Lambda scan → second Lambda thumbnail → metadata in DynamoDB. Idempotent consumers; DLQ on failure.",
      "**Why SQS:** Decouple burst uploads from Lambda concurrency.\n\n**Architect:** EventBridge for multi-subscriber; S3 notifications simpler for single consumer.\n\n**Security:** Pre-signed URLs for upload; block public read.",
      "Event-driven S3 is common interview scenario.",
      "S3 Event Notifications vs EventBridge? — EventBridge richer filtering.",
      "Lambda timeout on large files? — Step Functions or ECS for big objects.",
      "Synchronous Lambda chain on every upload",
      "No virus scan on user content",
      "Public read on upload bucket"),
    q("RDS Multi-AZ vs Read Replicas", "Database", "Very Common",
      "RDS Multi-AZ vs read replica — when each?",
      "Multi-AZ: synchronous standby for HA failover (same region). Read replicas: async read scale and DR copy (can cross-region).",
      "**HA:** Multi-AZ automatic failover ~60-120s.\n\n**Scale reads:** Replicas with connection router aware of lag.\n\n**Architect:** Multi-AZ for prod OLTP; replicas when read:write > 3:1 and lag tolerable.",
      "Confusing Multi-AZ with read scaling fails interviews.",
      "Aurora replicas? — Up to 15; faster failover than RDS.",
      "Replica lag monitoring? — CloudWatch `ReplicaLag`.",
      "Read replica for HA instead of Multi-AZ",
      "Strong consistency reads on replica",
      "No failover drill documented"),
    q("VPC Peering vs Transit Gateway", "Networking", "Common",
      "Connect 8 VPCs across 3 regions. Peering or Transit Gateway?",
      "Transit Gateway — full mesh peering doesn't scale (n(n-1)/2 connections). TGW hub-spoke with route tables per environment.",
      "**TGW benefits:** Centralized routing, cross-region peering via TGW peering, shared services VPC attachment.\n\n**Peering:** OK for 2-3 VPCs same region simple case.\n\n**Architect:** Document CIDR non-overlap across entire org upfront.",
      "Network topology scales with hub-spoke.",
      "TGW route table segmentation? — Isolate prod/nonprod traffic.",
      "PrivateLink vs peering? — SaaS consumer pattern different.",
      "Full mesh peering at 10 VPCs",
      "Overlapping CIDRs discovered late",
      "No network diagram maintained"),
    q("EBS vs Instance Store", "Storage", "Common",
      "When use instance store vs EBS for database EC2?",
      "EBS: persistent, snapshots, most workloads. Instance store: ephemeral, highest IOPS local NVMe — cache layers only, data lost on stop.",
      "**Architect:** RDS/Aurora preferred over self-managed DB on EC2 unless extreme customization.\n\n**gp3 vs io2:** gp3 baseline for most; io2 for sustained high IOPS.\n\n**Encryption:** EBS encryption by default — KMS CMK for compliance.",
      "Storage durability is architect concern.",
      "EBS Multi-Attach? — io2 only — clustered file systems niche.",
      "Snapshot lifecycle? — Automate via Data Lifecycle Manager.",
      "Instance store for production database",
      "No EBS snapshot DR plan",
      "Unencrypted volumes in prod"),
]

WEEK_20 = [
    q("Portable Cloud Abstractions", "Multi-Cloud", "Very Common",
      "What abstractions are genuinely portable across Azure and AWS?",
      "Kubernetes workloads, PostgreSQL, object storage (S3/Blob API via SDK abstraction), Terraform/Pulumi, OpenTelemetry, OAuth/OIDC — not proprietary PaaS lock-in without adapter.",
      "**Portable:** Containers on K8s, standard SQL, message semantics (with adapter), IaC modules per cloud.\n\n**Not portable:** App Service vs Elastic Beanstalk configs, Azure Service Bus vs SQS feature parity.\n\n**Architect:** Portability where business requires; embrace managed services where one cloud is primary.",
      "Pragmatic portability beats theoretical multi-cloud.",
      "MinIO for S3 API on-prem? — Hybrid object storage pattern.",
      "Cross-cloud K8s? — EKS + AKS similar; networking/IAM differ.",
      "Abstract every service behind lowest common denominator",
      "Multi-cloud day one without business driver",
      "Ignore operational cost of abstraction layer"),
    q("Azure vs AWS Service Mapping", "Multi-Cloud", "Very Common",
      "Map key services: compute, identity, messaging, data — Azure vs AWS?",
      "Compute: App Service/AKS ↔ ECS/EKS/Lambda. Identity: Entra ID ↔ IAM/Cognito. Messaging: Service Bus ↔ SQS/SNS/EventBridge. Data: Azure SQL ↔ RDS/Aurora; Cosmos ↔ DynamoDB.",
      "**Interview tip:** Know equivalents but explain *differences* — not 1:1.\n\n**Example:** Azure MI vs AWS IAM roles — similar concept, different implementation.\n\n**Architect:** Migration estimates need feature gap analysis per service.",
      "Mapping shows breadth without shallow name-dropping.",
      "APIM vs API Gateway? — Feature and pricing differ.",
      "Key Vault vs Secrets Manager? — Rotation patterns differ.",
      "Assume feature parity across clouds",
      "Map only names not capabilities",
      "No gap analysis in migration plan"),
    q("Multi-Cloud Anti-Patterns", "Multi-Cloud", "Very Common",
      "Multi-cloud anti-patterns architects should call out?",
      "Active-active multi-cloud without 2x ops team, lowest-common-denominator platform, split brain data writes, ignoring egress between clouds, compliance complexity multiplied.",
      "**Valid multi-cloud:** Acquisition integration, regulatory residency, vendor negotiation, DR to second cloud.\n\n**Invalid:** 'Avoid lock-in' on 3 services without TCO model.\n\n**Architect:** Primary cloud + DR secondary is common; dual primary is rare and expensive.",
      "Calling out anti-patterns shows senior judgment.",
      "Cloud-agnostic Terraform only? — Still need cloud-specific modules.",
      "Anthos/Azure Arc? — Hybrid management — know positioning.",
      "Dual write to Azure SQL and RDS",
      "Multi-cloud for 5-person startup",
      "No primary cloud designated"),
    q("Hybrid Connectivity Comparison", "Networking", "Common",
      "ExpressRoute vs AWS Direct Connect — hybrid design considerations?",
      "Both: private dedicated connection to cloud, bypass internet, predictable latency. Design: redundant connections, separate providers, BGP routing, on-prem firewall inspection.",
      "**Architect checklist:**\n- Dual circuits different carriers\n- Encryption in transit (MACsec optional)\n- Bandwidth headroom for DR sync\n- Split tunnel vs full tunnel from on-prem\n\n**VPN backup:** Site-to-Site VPN as failover path.",
      "Hybrid connectivity is enterprise architect bread and butter.",
      "ExpressRoute Global Reach? — Cross-region private connectivity.",
      "Direct Connect Gateway? — Multi-VPC/VIF aggregation.",
      "Single circuit no redundancy",
      "No bandwidth monitoring",
      "Treat VPN as primary production path"),
    q("Cross-Cloud Disaster Recovery", "DR", "Common",
      "Design DR with primary Azure and secondary AWS?",
      "Async replication, RPO measured in minutes-hours, runbook for DNS failover (Route 53/Traffic Manager), data sync via DB replication or event streaming, regular DR drills documented.",
      "**Patterns:**\n- Backup blobs cross-cloud (egress cost!)\n- Kafka/Event Hubs replication niche\n- Terraform dual-region modules\n\n**Architect:** DR to different cloud is expensive — justify vs same-cloud region pair DR.",
      "Cross-cloud DR is advanced scenario.",
      "RTO for DNS failover? — TTL + health check propagation.",
      "Immutable backups? — Ransomware protection cross-cloud.",
      "DR never tested",
      "Ignore cross-cloud egress in RPO math",
      "Assume automatic failover without runbook"),
    q("Identity Federation Multi-Cloud", "Identity", "Common",
      "Single corporate identity accessing Azure and AWS?",
      "Entra ID (or Okta) → SAML/OIDC federation to AWS IAM Identity Center and Azure native SSO. No duplicate user stores; conditional access policies unified where possible.",
      "**AWS:** IAM Identity Center permission sets per account.\n\n**Azure:** Entra ID app registrations and RBAC.\n\n**Architect:** Central IdP; cloud-specific authorization; no long-lived cloud passwords for humans.",
      "Identity is multi-cloud integration cornerstone.",
      "SCIM provisioning? — Automate user lifecycle to both clouds.",
      "Break-glass accounts? — Separate process per cloud audited.",
      "Duplicate IAM users per cloud manually",
      "Shared admin password in vault",
      "No MFA on federated access"),
    q("FinOps Across Cloud Providers", "FinOps", "Common",
      "CFO wants unified cloud cost view across Azure and AWS?",
      "Tags/labels standardized (Environment, CostCenter), export CUR + Azure Cost Management to FinOps tool (CloudHealth, Finout), unit economics dashboard, anomaly alerts per provider.",
      "**Architect:** Mandate tag policy both clouds before scale.\n\n**Challenge:** Different billing granularity — normalize in warehouse.\n\n**Governance:** Monthly review with engineering managers by CostCenter.",
      "Multi-cloud FinOps requires discipline upfront.",
      "Reserved capacity strategy per cloud? — Separate RI/SP purchases.",
      "Commitment exchange? — Provider-specific — no cross-cloud.",
      "No tag standards across clouds",
      "Finance sees invoice surprise monthly",
      "Optimize one cloud while other bleeds"),
    q("Egress and Data Transfer Costs", "FinOps", "Very Common",
      "Why is multi-cloud data transfer expensive? Mitigations?",
      "Cross-cloud egress charged per GB both sides; cross-AZ also adds up. Mitigate: data locality, compression, CDN, batch sync off-peak, process data where stored.",
      "**Architect modeling:** Include egress in TCO for replication, DR, and analytics pipelines.\n\n**Azure:** Egress to internet and inter-region.\n\n**AWS:** Data transfer out + cross-AZ.\n\n**Pattern:** Analytics in same region as data lake.",
      "Egress ignorance causes budget overruns.",
      "CloudFront/CDN reduce origin egress? — Cache hit ratio matters.",
      "Private connectivity egress? — Still often charged — read fine print.",
      "Replicate all data bidirectionally realtime",
      "No egress alerts",
      "Cross-cloud analytics without locality plan"),
    q("Vendor Lock-In Mitigation", "Strategy", "Common",
      "Mitigate vendor lock-in without full multi-cloud?",
      "Open formats (Parquet, Postgres), containerized workloads, IaC, avoid proprietary-only APIs in core domain, exit plan ADR per critical service, data export tested annually.",
      "**Pragmatic:** Lock-in is trade-off for velocity — document accepted lock-in.\n\n**High lock-in:** DynamoDB-specific queries, Step Functions orchestration, Cosmos DB RU model.\n\n**Architect:** ADR: 'We accept Azure Service Bus lock-in because...'",
      "Mature architects document lock-in decisions.",
      "Abstraction layer cost? — Team maintains adapters — budget for it.",
      "Open source on cloud? — Still operational lock-in on that cloud.",
      "Fear lock-in blocks all managed services",
      "No export test of critical data",
      "Abstraction without business justification"),
    q("Choosing Primary Cloud per Workload", "Strategy", "Very Common",
      "Framework for assigning workloads to Azure vs AWS in enterprise?",
      "Team skill, existing commitments, service feature fit, compliance region availability, commercial EA/discounts, acquisition inherited estate, latency to users.",
      "**Decision matrix:** Score each workload 1-5 on criteria; weighted sum.\n\n**Example:** .NET team on Azure EA → new .NET APIs on Azure; acquired Java shop on AWS stays until migration wave.\n\n**Architect:** Polite truth — two clouds have cost; consolidate when possible.",
      "Workload placement is political and technical.",
      "Landing zone both clouds? — Only if business requires — cost it.",
      "Exit criteria? — When to consolidate clouds — define upfront.",
      "Religious one-cloud-only without assessment",
      "Split monolith across two clouds randomly",
      "No documented placement criteria"),
]

ALL_AWS_WEEKS = {
    17: WEEK_17, 18: WEEK_18, 19: WEEK_19, 20: WEEK_20,
}
