"""Hand-crafted premium Q001–Q005 for Weeks 45–48 — .NET, Cloud, System Design, Whiteboard Mock intros."""

from premium_qa_data import q

WEEK_45_Q001_Q005 = [
    q("C# Fundamentals Interview Approach", "C# Fundamentals", "Very Common",
      "How should a solution architect approach C# fundamentals questions in a senior .NET interview?",
      "Lead with trade-offs and production context — value vs reference, async I/O, nullable types, records — not syntax trivia. Structure answers: definition → when to use → when to avoid → real API example → architect consequence (perf, safety, team conventions).",
      "**Interview structure (3–5 min per topic):**\n1. **One-sentence definition** — precise, not textbook length\n2. **Decision criteria** — workload shape drives choice\n3. **Production example** — payment API, order handler, hot path\n4. **Architect angle** — team standards, analyzers, CI gates\n\n**High-yield topics interviewers probe:**\n| Topic | Architect answer hook |\n|-------|----------------------|\n| Value vs reference | `record struct Money` for hot DTOs; avoid large structs on stack |\n| Nullable reference types | Enable on new projects; warnings-as-errors in CI |\n| `record` vs `class` | Immutable API contracts vs domain entities with behavior |\n| async/await | I/O-bound handlers only; `ConfigureAwait` in library code |\n| `Span<T>` / `Memory<T>` | Parsing/serialization hot paths — not CRUD APIs |\n\n**How to open:** 'Before I answer, I'll state the trade-off I'd document in an ADR...'\n\n**Red flags to avoid:** Quoting language spec without use case; ignoring thread-safety with `DbContext`; claiming async makes CPU work faster.\n\n**Practice:** Pick 5 fundamentals — answer in 90 seconds each with one .NET 8+ feature mention.",
      "Architects are evaluated on judgment under constraints — C# fundamentals are the vocabulary for reliability and performance decisions.",
      "Generics variance? — Know `in`/`out` for library design — rare but senior signal.",
      "LINQ deferred execution trap? — Multiple enumeration — materialize once or use `IAsyncEnumerable`.",
      "Reciting syntax without production trade-off",
      "Treating `async void` as acceptable pattern",
      "Ignoring nullable reference types in API contracts"),
    q("ASP.NET Core Architecture Interview", "ASP.NET Core", "Very Common",
      "How do you structure answers for ASP.NET Core architecture questions at architect level?",
      "Frame ASP.NET Core as a composable pipeline: host → middleware → routing → endpoints → cross-cutting (auth, validation, logging). Answer with layer boundaries, DI lifetimes, and operational concerns — not controller trivia alone.",
      "**Reference mental model:**\n```\nClient → Reverse Proxy / WAF → ASP.NET Host\n  → Middleware pipeline (exception, HTTPS, CORS, auth)\n  → Endpoints (Minimal API / Controllers)\n  → Application layer (MediatR handlers)\n  → Domain → Infrastructure (EF, HTTP clients, messaging)\n```\n\n**Architect talking points:**\n- **Middleware order** — auth before authz; exception handler outermost\n- **DI lifetimes** — scoped `DbContext`; no captive dependencies in singletons\n- **API surface** — thin endpoints, ProblemDetails, versioning, rate limits\n- **Observability** — correlation ID middleware, OpenTelemetry, health checks (`/health/live`, `/health/ready`)\n- **Resilience** — `IHttpClientFactory`, Polly policies, timeouts\n\n**Answer template:**\n1. Draw or describe request flow\n2. Name the layer owning each concern\n3. State one production failure you've prevented (CORS, scope bug, socket exhaustion)\n4. Mention deployment target (App Service, AKS, container)\n\n**Common interview prompts:** middleware order, minimal APIs at scale, global exception handling, validation pipeline.\n\n**Differentiator:** Connect ASP.NET choices to blast radius — feature flags, blue-green, config per environment.",
      "ASP.NET Core architecture interviews test whether you design operable APIs — pipeline, DI, and observability are the architect's toolkit.",
      "Minimal API vs controllers? — Team consistency and filter ecosystem — not performance religion.",
      "YARP reverse proxy? — Gateway pattern in .NET — mention when API aggregation asked.",
      "Fat controllers with business logic",
      "Wrong middleware order without explaining why",
      "Singleton service holding scoped DbContext"),
    q("SOLID Principles Interview", "SOLID", "Very Common",
      "How approach SOLID principles questions in a .NET architect interview?",
      "Don't recite definitions — give violation → refactor → architectural consequence. Map each principle to service boundaries, testability, and change isolation. Acknowledge when over-application creates distributed monolith.",
      "**Interview framework per principle:**\n| Principle | Strong answer pattern |\n|-----------|----------------------|\n| **S**RP | One reason to change — split `OrderService` god class |\n| **O**CP | Strategy/handlers — extend without editing stable code |\n| **L**SP | Substitutable interfaces — no `NotSupportedException` surprises |\n| **I**SP | Segregate read/write/admin repository interfaces |\n| **D**IP | Domain depends on ports; `Program.cs` is composition root |\n\n**Example arc (SRP):**\n```csharp\n// Violation: validate + save + email + PDF in one class\n// Fix: OrderValidator, IOrderRepository, INotificationService\n// Architecture: same logic at microservice boundary — one bounded context\n```\n\n**Architect nuance:**\n- SOLID at class level ≠ microservice per class\n- SRP at deployable unit aligns with team ownership (Conway's law)\n- DIP enables hexagonal architecture — domain never references EF\n\n**Follow-up readiness:** 'How does OCP relate to MediatR behaviors?' 'When is repository pattern violating YAGNI?'\n\n**Score higher:** Mention contract tests verifying interface implementations across teams.",
      "SOLID interviews reward refactor instinct and boundary judgment — principles are tools for change management, not badges.",
      "SOLID vs microservices? — Bounded context per service is SRP at architecture scale.",
      "When skip repository? — EF DbContext is UoW — justify seams with testing needs.",
      "Defining SRP as one method per class",
      "Abstract factory for every `new` statement",
      "SOLID buzzwords without .NET code example"),
    q("Design Patterns Interview", "Design Patterns", "Very Common",
      "How should architects answer design pattern questions without sounding like a Gang of Four textbook?",
      "Connect patterns to .NET idioms: Strategy → DI keyed services; Decorator → `HttpMessageHandler` chain; Observer → MediatR domain events; Factory → plugin registration. State problem, pattern, .NET implementation, and when NOT to use.",
      "**Pattern → .NET mapping (interview cheat sheet):**\n| Pattern | Enterprise .NET use | Skip when |\n|---------|---------------------|----------|\n| Strategy | `IShippingCalculator`, payment gateways | Single algorithm forever |\n| Factory | `INotificationFactory` by channel | DI handles all cases |\n| Decorator | Caching repository, logging handler | Decorator stack >4 deep |\n| Observer | MediatR `INotification`, outbox events | Static C# events in web app |\n| Repository | Aggregate persistence seam | Thin EF CRUD wrapper |\n| Unit of Work | `DbContext.SaveChanges()` | Cross-service 'UoW' fantasy |\n\n**Answer structure:**\n1. **Problem** — interchangeable behavior or cross-cutting concern\n2. **Pattern** — name it once, then show code\n3. **DI wiring** — how it registers in `Program.cs`\n4. **Distributed boundary** — in-proc pattern vs message bus\n\n**Architect distinction:** Patterns solve *local* coupling; microservices solve *organizational* coupling — don't confuse.\n\n**Anti-pattern callout:** Abstract factory when only one product type exists — YAGNI.\n\n**Bonus:** Mention Scrutor `Decorate<T>()` for decorator registration.",
      "Pattern interviews test whether you map structure to maintainability — .NET DI and MediatR are the modern pattern runtime.",
      "Mediator vs MediatR? — CQRS command/query dispatch — not chat room pattern.",
      "Chain of Responsibility? — Middleware pipeline and Polly policy wrap — good follow-up.",
      "Listing 23 GoF patterns from memory",
      "Pattern for every line of code",
      "Static events for cross-service communication"),
    q("EF Core Architecture Interview", "EF Core", "Very Common",
      "How approach Entity Framework Core architecture questions as a solution architect?",
      "Position EF Core as data access infrastructure — not the domain model. Cover DbContext lifetime, query strategy (projection vs Include), transaction boundaries, migrations governance, and when raw SQL or read replicas belong in the architecture.",
      "**Architectural layers:**\n```\nAPI → Application handler → Domain (entities, invariants)\n                              ↓\n                    Infrastructure (EF Core DbContext, configurations)\n```\n\n**Key interview topics:**\n| Concern | Architect answer |\n|---------|------------------|\n| DbContext scope | Scoped per HTTP request — never singleton |\n| N+1 queries | `.Include`, projection `.Select()`, split queries |\n| Tracking | `AsNoTracking()` on read APIs |\n| Transactions | `SaveChanges()` once per request; explicit tx for multi-step |\n| Migrations | CI pipeline, backward-compatible, separate from app deploy |\n| Raw SQL | Isolated query classes; parameterized; ADR with plan evidence |\n| Distributed data | Saga/outbox — not shared DbContext across services |\n\n**Repository pattern stance:** Use when aggregate boundary, multiple stores, or test seam — anti-pattern when generic `IRepository<T>` wraps `DbSet` with no value.\n\n**Performance narrative:** Detect with App Insights SQL deps → fix projection → measure → document.\n\n**Migration governance:** Idempotent scripts, rollback plan, expand-contract for zero-downtime schema changes.",
      "EF Core architecture is about boundaries and query discipline — architects prevent ORM leaks into domain and API contracts.",
      "DbContext pooling? — Performance optimization — distinct from connection pooling.",
      "Compiled queries? — Hot path micro-optimization after projection and indexes.",
      "Expose `IQueryable` from repository to controllers",
      "Lazy loading enabled globally in APIs",
      "One SaveChanges per row in a loop"),
]

WEEK_46_Q001_Q005 = [
    q("SQL Interview Architecture Angle", "Database", "Very Common",
      "How do solution architects approach SQL questions differently from DBA trivia interviews?",
      "Lead with workload classification (OLTP vs analytics), consistency requirements, scale path (indexes → read replicas → sharding), and operational governance — not just 'add an index.' Show execution-plan methodology and business impact.",
      "**Architect answer framework:**\n1. **Classify workload** — transactional, reporting, mixed\n2. **State SLAs** — p99 latency, RPO/RTO, consistency\n3. **Diagnose** — execution plan, logical reads, waits\n4. **Remediate** — sargable predicates, composite indexes, partition, cache\n5. **Govern** — index review cadence, migration strategy, connection pooling\n\n**High-value topics:**\n| Topic | Architecture hook |\n|-------|-------------------|\n| Index design | Leading column selectivity; covering indexes; write overhead |\n| Query tuning | Filter early; avoid functions on indexed columns |\n| Replication lag | Classify reads: payment balance → primary; catalog → replica |\n| Sharding | Shard key = tenantId; avoid cross-shard joins in OLTP |\n| Connection pools | Pods × pool size vs DB max connections |\n\n**Example opener:** 'For a 5:1 read/write ratio and 30s stale tolerance, I'd route analytics to a read replica and keep financial reads on the primary.'\n\n**Tools to mention:** Azure SQL Query Store, missing index DMVs, EF Core SQL logging in staging.\n\n**Avoid:** Index every column; optimize without baseline metrics.",
      "SQL architecture interviews test data scale path and consistency trade-offs — architects own the decision, DBAs often own the tuning.",
      "Columnstore vs rowstore? — Analytics vs OLTP — different index models.",
      "Hyperscale / Citus? — When vertical scale exhausts — mention shard router.",
      "Jump to sharding on day one with 100 users",
      "Assume read replica is always current",
      "SELECT * on hot API paths"),
    q("Azure Services Interview Map", "Azure", "Very Common",
      "How map Azure services quickly in a cloud architect interview?",
      "Organize by capability layers — identity, networking, compute, data, messaging, observability, security — not alphabetical service lists. Map each requirement to a managed service with trade-off (PaaS vs IaaS vs serverless).",
      "**Capability map (interview whiteboard):**\n| Layer | Azure services |\n|-------|----------------|\n| Edge | Front Door, CDN, WAF |\n| API | API Management, App Service, AKS ingress |\n| Compute | App Service, Functions, AKS, Container Apps |\n| Data | Azure SQL, Cosmos DB, Blob, Redis Cache |\n| Messaging | Service Bus, Event Hubs, Event Grid |\n| Identity | Entra ID, managed identity, Key Vault |\n| Ops | Monitor, Log Analytics, App Insights, Policy |\n| Integration | Logic Apps, Data Factory |\n\n**Answer technique:**\n1. Restate requirement (global web app, 10K RPS, PCI)\n2. Pick entry (Front Door + WAF)\n3. Compute (App Service vs AKS — team skill decides)\n4. Data (SQL + Redis cache-aside)\n5. Identity (managed identity to Key Vault — no secrets in config)\n\n**Frameworks to cite:** Well-Architected pillars, CAF landing zones, subscription segmentation.\n\n**Differentiator:** Name what you would NOT use — 'Not AKS here because team has no platform engineers and traffic is steady.'",
      "Azure interviews reward capability thinking — interviewers want justified service selection, not certification recall.",
      "Cosmos vs SQL? — Multi-region write vs relational transactions — consistency model drives choice.",
      "Event Hubs vs Service Bus? — Streaming telemetry scale vs enterprise messaging features.",
      "Naming services without requirement context",
      "Single subscription for all environments",
      "Public endpoints on PaaS without Private Link discussion"),
    q("AWS Fundamentals Interview", "AWS", "Very Common",
      "What AWS fundamentals must a multi-cloud architect demonstrate in interviews?",
      "Cover shared responsibility model, core services (EC2, S3, IAM, VPC, RDS, Lambda, SQS/SNS), region/AZ design, and IAM least privilege — framed with Azure equivalents when asked for comparison.",
      "**Foundational concepts:**\n1. **Shared responsibility** — AWS secures cloud; you secure data, IAM, network config\n2. **Regions & AZs** — multi-AZ for HA; data residency by region choice\n3. **IAM** — users, roles, policies; instance profiles; no long-lived keys in apps\n4. **VPC** — subnets public/private, security groups, NACLs, NAT gateway\n\n**Core service map:**\n| Need | AWS | Quick note |\n|------|-----|------------|\n| VM | EC2 | ASG for scale |\n| Object storage | S3 | Lifecycle tiers, versioning |\n| Relational DB | RDS / Aurora | Multi-AZ failover |\n| Serverless | Lambda | Cold start, 15 min limit |\n| Queue | SQS | Visibility timeout, DLQ |\n| Identity | IAM + Cognito | Federation with Entra possible |\n| K8s | EKS | Control plane managed |\n\n**Interview structure:** Define → production example → Azure parallel → operational concern (cost, monitoring CloudWatch).\n\n**Architect angle:** Landing zone (Control Tower), Organizations, SCPs — enterprise guardrails.\n\n**Honest stance:** 'Primary on Azure; AWS fluent for DR, acquisition, or multi-cloud ADR.'",
      "AWS fundamentals prove multi-cloud literacy — architects compare capabilities, not logo loyalty.",
      "Well-Architected Framework? — Six pillars parallel Azure WAF — good bridge answer.",
      "RDS Proxy? — Connection pooling at scale — pairs with Lambda/RDS discussion.",
      "Assume IAM is same as Entra ID RBAC",
      "S3 bucket public by default acceptable",
      "Ignore egress cost between AZs and regions"),
    q("Multi-Cloud Strategy Interview", "Cloud Strategy", "Very Common",
      "How answer multi-cloud strategy questions with architectural maturity?",
      "Distinguish multi-cloud by accident, DR backup, vs active-active. Acknowledge abstraction tax, egress costs, duplicated ops, and IAM sprawl. Recommend deliberate strategy: primary cloud + portable interfaces + tested exit — not lowest-common-denominator everywhere.",
      "**Multi-cloud patterns:**\n| Pattern | Description | Common? |\n|---------|-------------|--------|\n| Primary + DR | Prod Azure, DR failover AWS | Moderate |\n| Acquisition blend | Integrate purchased company's cloud | Common |\n| Active-active dual | Same workload both clouds | Rare, expensive |\n| Portable K8s | EKS + AKS same manifests | Ops-heavy |\n\n**Pitfalls to articulate:**\n- Lowest-common-denominator services (self-managed everything)\n- 2× operational expertise (Terraform multi-provider still ops burden)\n- Cross-cloud egress fees\n- Inconsistent security baselines\n- 'Multi-cloud' without tested failover\n\n**Mitigation strategies:**\n1. Open formats — Parquet, OAuth, Postgres, Kubernetes\n2. Abstraction at boundaries — S3-compatible API wrapper\n3. Identity federation — Entra as IdP across clouds\n4. DR runbooks tested quarterly\n\n**Strong interview close:** 'We optimize for Azure time-to-market; DR objects in S3 with quarterly restore test; revisit if regulatory or contract requires active dual.'",
      "Multi-cloud maturity is skepticism with valid exceptions — architects quantify cost and ops before endorsing dual active.",
      "Terraform multi-cloud? — Modules per provider — doesn't eliminate operational duplication.",
      "Vendor negotiation? — Credible exit strategy improves pricing — pragmatic reason for portability.",
      "Multi-cloud for buzzword compliance",
      "Active-active dual cloud without budget 2×",
      "No shared identity or observability plane"),
    q("Cloud Migration Interview", "Migration", "Very Common",
      "How structure cloud migration answers using architect frameworks?",
      "Use 6 Rs portfolio (rehost, replatform, refactor, repurchase, retire, retain), wave planning, dependency ordering, and explicit phase 2 modernization. Always state RTO/RPO, identity first, and landing zone prerequisites.",
      "**6 Rs quick reference:**\n| Strategy | When | Example |\n|----------|------|--------|\n| Rehost | Fast deadline, low change | VM → Azure VM (ASR) |\n| Replatform | Managed wins | SQL Server → Azure SQL |\n| Refactor | Strategic apps | Monolith → App Service + Functions |\n| Repurchase | SaaS replaces custom | CRM → Dynamics 365 |\n| Retire | Decommission zombie | Turn off unused LOB |\n| Retain | Compliance/latency | Mainframe stays |\n\n**Migration architecture sequence:**\n1. **Assess** — Azure Migrate, dependency map, 6 R classification\n2. **Foundation** — landing zone, identity, networking hub\n3. **Wave 1** — low-risk rehost + retire quick wins\n4. **Wave 2** — replatform databases, replatform middleware\n5. **Wave 3** — refactor strategic workloads\n6. **Operate** — FinOps, monitoring, security baseline\n\n**Risks to mention:** Lift-shift cost surprise, license BYOL audit, latency assumptions, no rollback.\n\n**Architect deliverable:** Migration ADR per app — R choice, cutover plan, rollback, phase 2 roadmap.\n\n**Interview tip:** Give portfolio percentages — '70% rehost/replatform wave 1; 15% refactor over 18 months.'",
      "Migration interviews test portfolio thinking — architects sequence waves and retain honesty about lift-shift limits.",
      "Azure Migrate / AWS MGN? — Discovery and replication tools — mention assessment phase.",
      "Data migration cutover? — Minimal downtime strategies — DMS, transactional replication.",
      "Refactor everything in wave one",
      "Migrate without landing zone or identity plan",
      "No retire — carry all technical debt to cloud"),
]

WEEK_47_Q001_Q005 = [
    q("Microservices Interview Decomposition", "Microservices", "Very Common",
      "How approach microservices decomposition questions in system design interviews?",
      "Decompose by bounded context and team topology — not entity-per-service. State criteria: independent deploy, different scale profiles, change frequency. Recommend modular monolith first; strangler fig extraction when metrics prove pain.",
      "**Decomposition criteria:**\n| Criterion | Question to ask |\n|-----------|----------------|\n| Business capability | Does this map to a domain experts own? |\n| Data ownership | Can one team own this schema? |\n| Scale profile | Does search need 10× checkout QPS? |\n| Deploy independence | Can we ship without coordinating 6 teams? |\n| Failure isolation | Should payment outage block catalog browse? |\n\n**Anti-patterns to call out:**\n- Microservice per database table\n- Distributed monolith — 6 synchronous HTTP calls, shared DB\n- Split before identifying aggregate roots\n\n**Migration pattern:** Strangler fig — route `%` traffic to new service via gateway; retire monolith module when stable.\n\n**Conway's law:** Service boundaries should align with team boundaries — or expect friction.\n\n**Interview structure:**\n1. Clarify org and scale\n2. Identify bounded contexts (payments, catalog, notifications)\n3. Draw services with owned data stores\n4. Async where possible (events, not chains)\n5. Acknowledge operational cost (K8s, tracing, CI × N)",
      "Microservices decomposition is organizational architecture — interviewers want bounded contexts, not box explosion.",
      "Modular monolith first? — .NET vertical slices in one deployable — extract when proven.",
      "Shared database anti-pattern? — Integration via APIs/events — not shared tables.",
      "50 services sharing one SQL database",
      "Synchronous chain across six services",
      "Split monolith before measuring team or scale pain"),
    q("Resilience Patterns Interview", "Resilience", "Very Common",
      "What resilience patterns should architects prioritize in system design interviews?",
      "Layer timeouts, retries (idempotent only), circuit breakers, bulkheads, fallbacks, and graceful degradation. State delivery semantics (at-least-once + idempotency) and never retry non-idempotent POSTs blindly.",
      "**Resilience stack (outer to inner):**\n```\nTimeout → Retry (with jitter) → Circuit Breaker → Bulkhead → Fallback\n```\n\n**Pattern guide:**\n| Pattern | Purpose | Example |\n|---------|---------|--------|\n| Timeout | Bound wait | 300ms gateway budget |\n| Retry | Transient failures | 3× on 5xx GET with jitter |\n| Circuit breaker | Fail fast when downstream sick | Open after 5 fails / 30s |\n| Bulkhead | Isolate thread pools | Separate pool per dependency |\n| Fallback | Degraded UX | 'Payment pending' queue |\n| Rate limit | Protect self and neighbor | 429 at gateway |\n\n**Critical rules:**\n- Retry POST payments only with `Idempotency-Key`\n- No nested retries across layers (3×3×3 = 27 attempts)\n- Circuit half-open: single probe — avoid thundering herd\n- Pair resilience with observability — breaker state metric\n\n**Implementations:** Polly (.NET), Istio (service mesh), API gateway policies.\n\n**Interview deep dive pick:** Payment dependency — draw states closed/open/half-open with fallback queue.",
      "Resilience interviews separate seniors who've seen outages — idempotency and timeout budgets are non-negotiable.",
      "Chaos engineering? — Inject failures in staging — validate breakers work.",
      "Saga vs 2PC? — Distributed transactions — compensation not locks.",
      "Infinite retry on failing payment API",
      "No timeout on 5-deep microservice chain",
      "Retry at gateway, service, and client all maxed"),
    q("Kubernetes Interview for Architects", "Kubernetes", "Very Common",
      "What Kubernetes topics matter for solution architects — not cluster admin trivia?",
      "Focus on workload placement (Deployments, HPA), networking (Ingress, services), config/secrets, health probes, rollout strategies, and when AKS/EKS beats PaaS. Defer CNI plugin details unless platform role.",
      "**Architect K8s checklist:**\n| Topic | What to say |\n|-------|-------------|\n| Workloads | Deployment, StatefulSet for stateful, Job/CronJob |\n| Scaling | HPA on CPU/custom metrics; cluster autoscaler |\n| Networking | Service ClusterIP → Ingress → TLS |\n| Config | ConfigMap, Secret — externalize; never bake in image |\n| Health | Liveness vs readiness — readiness removes from LB |\n| Rollouts | Rolling update, maxUnavailable 0; canary via mesh/Argo |\n| Observability | Prometheus metrics, OTel collectors, log sidecars |\n| Security | RBAC, network policies, pod identity to cloud IAM |\n\n**When K8s vs PaaS:**\n- **AKS/EKS** — polyglot, custom sidecars, GPU, portable workloads\n- **App Service** — .NET team, steady traffic, less ops headcount\n\n**Production narrative:**\n```\nCI → container registry → GitOps (ArgoCD) → Deployment\nReadiness probe gates traffic; preStop drain connections\n```\n\n**Architect pitfalls:** Running K8s without platform team; no resource requests/limits; singleton DB in pod without PVC strategy.",
      "Kubernetes for architects is deployability and operability — probes, rollouts, and identity — not kubectl trivia.",
      "Service mesh when? — mTLS, canary, observability — cost of complexity.",
      "Pod Disruption Budget? — HA during node drains — mention in rollout mock.",
      "K8s chosen because 'industry standard' without ops team",
      "Liveness and readiness identical probe",
      "No resource limits — noisy neighbor OOM kills"),
    q("System Design Interview Framework", "System Design", "Very Common",
      "What framework should architects use to structure a 45-minute system design interview?",
      "Use RESHADED or equivalent: Requirements → Estimation → Storage → High-level design → APIs → Deep dive → Edge cases → Distinctive points. Never jump to Redis before clarifying read/write ratio and latency SLA.",
      "**RESHADED (45-min time box):**\n| Phase | Minutes | Actions |\n|-------|---------|--------|\n| **R**equirements | 5 | Functional + NFR; state assumptions |\n| **E**stimation | 5 | QPS, storage, bandwidth |\n| **S**torage | 5 | Schema, DB choice, sharding |\n| **H**igh-level design | 10 | Boxes, arrows, data flow |\n| **A**PIs | 5 | Key endpoints, contracts |\n| **D**eep dive | 10 | Bottleneck — cache, queue, fanout |\n| **E**dge cases | 3 | Failures, hot keys, duplicates |\n| **D**istinctive | 2 | Trade-offs, monitoring, evolution |\n\n**Requirements must clarify:**\n- DAU, read/write ratio, p99 latency, consistency, geography, retention\n\n**Estimation template:**\n`QPS = DAU × actions/day ÷ 86400 × peak factor 3`\n\n**Distinctive close:** 'Phase 1 monolith + cache; Phase 2 shard writes; monitor queue depth and p99.'\n\n**Self-check before ending:** Did I address failures, security, and observability?",
      "Framework discipline signals senior judgment — interviewers forgive imperfect depth if structure and assumptions are clear.",
      "C4 model relation? — Context/container in HLD phase — component detail only if time.",
      "Similar frameworks? — REPE, FAST — same intent — pick one and practice.",
      "Jump to components without requirements",
      "Skip estimation entirely",
      "Deep dive before drawing high-level diagram"),
    q("Scalability Interview Patterns", "Scalability", "Very Common",
      "What scalability patterns should architects rehearse for system design interviews?",
      "Master horizontal scale, caching tiers, async decoupling, read replicas, sharding, CDN, and load balancing — each tied to a trigger (read-heavy, write-heavy, global users, hot keys).",
      "**Pattern selection matrix:**\n| Bottleneck signal | Pattern |\n|-------------------|--------|\n| Read-heavy | Cache-aside, CDN, read replicas |\n| Write-heavy | Sharding, queue buffering, partition keys |\n| Traffic spikes | Autoscale, queue absorption, rate limits |\n| Global latency | CDN, multi-region read, geo DNS |\n| Hot key | Key splitting, local L1, request coalescing |\n| Heavy processing | Async workers, scale on queue depth |\n\n**Layered scale story:**\n1. **Stateless app** — horizontal pods behind LB\n2. **Cache** — Redis cluster, TTL + invalidation\n3. **DB** — read replicas → shard when write ceiling hit\n4. **Async** — Service Bus/Kafka decouple peak\n5. **Edge** — CDN for static and cacheable API responses\n\n**Architect rules:**\n- Scale stateless first — session in JWT/Redis\n- Measure before shard — operational cost is high\n- Document consistency trade-off per read path\n\n**Interview phrase:** 'At 100:1 read/write, I'd add Redis cache-aside before considering write sharding.'",
      "Scalability patterns are conditional — architects match pattern to measured bottleneck, not checklist architecture.",
      "Vertical scale when? — Short-term relief — not long-term strategy; mention before horizontal.",
      "Database connection storm? — Pooler, PgBouncer, limit pods × pool size.",
      "Shard on day one without write pressure",
      "Cache with no invalidation strategy",
      "Scale servers without fixing N+1 queries first"),
]

WEEK_48_Q001_Q005 = [
    q("Notification System Mock Intro", "Whiteboard Mock", "Very Common",
      "How open and structure a 45-minute notification system whiteboard mock?",
      "Spend first 5 minutes on channels, volume, latency (OTP vs marketing), and compliance. Then HLD: ingest → queue → workers → provider adapters. Deep dive channel fanout, idempotency, and DLQ — not email HTML.",
      "**Minute-by-minute script:**\n| Time | Focus |\n|------|-------|\n| 0–5 | Requirements — email/SMS/push; 1M/day; OTP <10s |\n| 5–15 | HLD — API/event → Service Bus → worker pool → SendGrid/Twilio/FCM |\n| 15–30 | Deep dive — priority queues, user prefs, template i18n, idempotency key |\n| 30–40 | Failures — provider down, DLQ, retry backoff, rate limits |\n| 40–45 | Trade-offs — at-least-once + dedup vs exactly-once fantasy |\n\n**Components to label:**\n- Template service (versioned content)\n- User preference store (opt-out per channel — CAN-SPAM/GDPR)\n- Separate queues: transactional vs marketing\n- Delivery status webhook + audit log\n\n**Clarifying questions:**\n- 'Is OTP latency hard SLA?'\n- 'Do users set quiet hours?'\n- 'Duplicate notification acceptable or not?'\n\n**Self-score:** Did I mention idempotency and opt-out before scale?",
      "Notification mock intro sets scope — interviewers reward compliance and delivery semantics early.",
      "Exactly-once delivery? — Honest at-least-once + idempotent consumers.",
      "Scale to 1B/day? — Partition queues; batch digest emails.",
      "Spend 25 minutes on template HTML design",
      "Synchronous send in API request path",
      "No DLQ or provider failure handling"),
    q("E-Commerce Cart Mock Intro", "Whiteboard Mock", "Very Common",
      "How begin an e-commerce shopping cart whiteboard mock for architect interviews?",
      "Clarify concurrent users, flash sale scenario, guest vs logged-in, inventory rules. Propose Redis-backed cart per user, separate inventory reservation, saga on checkout — draw before deep-diving inventory.",
      "**Opening questions (5 min):**\n- Peak concurrent add-to-cart? (e.g. 50K flash sale)\n- Guest cart merge on login?\n- Inventory oversell tolerance? (zero for most retailers)\n- Checkout payment sync or async?\n\n**HLD sketch (10 min):**\n```\nClient → Cart API → Redis (cart:{userId})\nCheckout → Inventory Service (reserve) → Payment → Order DB\nFlash sale → waiting room / token queue optional\n```\n\n**Deep dive target (15 min):** Inventory reservation with timeout; optimistic concurrency; saga compensation on payment fail.\n\n**Patterns to mention:**\n- Cart TTL 7–30 days\n- Product catalog cached — short TTL during sale\n- Idempotent checkout with `Idempotency-Key`\n\n**Trade-off close:** Redis cart for speed; SQL order of record on commit only.\n\n**Trap to avoid:** Cart rows in SQL at 50K RPS without cache.",
      "Cart mock intro frames concurrency and inventory — the deep dive is oversell prevention, not CRUD.",
      "Virtual waiting room? — Flash sale admission control — mention when 50K concurrent stated.",
      "Saga on checkout? — Release inventory if payment fails.",
      "Cart in SQL without cache at flash sale scale",
      "No inventory reservation timeout",
      "Ignore guest-to-logged-in cart merge"),
    q("Queue Design Mock Intro", "Whiteboard Mock", "Very Common",
      "How structure the opening of a message queue design whiteboard mock?",
      "Establish producer volume, processing time, ordering needs, failure tolerance, and consumer scale signal. Draw upload/event → durable queue → autoscaling workers → status callback — state visibility timeout math early.",
      "**Requirements checklist (5 min):**\n- Throughput — 10K jobs/hour vs 10K/sec\n- Job duration — 30s vs 5 min (drives visibility timeout)\n- Ordering — FIFO per user or global order irrelevant?\n- Priority lanes — paid vs free tier?\n- Delivery — at-least-once acceptable with idempotent workers?\n\n**HLD template (10 min):**\n```\nProducer → Blob (payload) → Queue (metadata) → Worker pool\n                              ↓\n                         DLQ (poison messages)\nStatus API / webhook on completion\n```\n\n**Deep dive (15 min):** Autoscale on queue depth; `visibility timeout > max processing time`; `maxReceiveCount` before DLQ.\n\n**Example narrative:** Image processing — S3 event → SQS → GPU workers scale 0→N.\n\n**Say aloud:** 'I choose queue over Kafka here because task distribution, not replay log, is the primary need.'",
      "Queue mock intro is semantics and ops — visibility timeout and DLQ before drawing microservices.",
      "FIFO queue when? — Strict per-entity ordering — costs throughput.",
      "Poison message? — DLQ + alert — don't infinite redrive.",
      "Sync processing in upload API for long jobs",
      "Visibility timeout 30s for 5-minute job",
      "No dead-letter queue configured"),
    q("API Design Mock Intro", "Whiteboard Mock", "Very Common",
      "How open an API design whiteboard mock for architect-level interviews?",
      "Clarify client types (mobile, partner, internal), consistency needs, and scale profile per endpoint. Sketch versioned REST resources, pagination strategy, auth, rate limits, and separate hot read path from write API.",
      "**First 5 minutes — ask:**\n- Who consumes — mobile, third-party, browser?\n- Read vs write ratio per endpoint?\n- Pagination — live feed (cursor) vs admin list (offset OK)?\n- Auth — API key, OAuth, JWT scope?\n\n**API skeleton (10 min):**\n```\nPOST /v1/resources     — create (idempotent key header)\nGET  /v1/resources/{id}\nGET  /v1/resources?cursor=&limit=\nPATCH /v1/resources/{id}\n```\n\n**Architect concerns to voice:**\n- Version prefix `/v1` — breaking change policy\n- ProblemDetails (RFC 7807) errors\n- Rate limit 429 + Retry-After\n- Cursor pagination for live feeds — avoid offset skip/duplicate\n\n**Deep dive pick:** URL shortener redirect (hot read) vs create API (write) — different scale.\n\n**Close:** 'Redirect service minimal deps; analytics async via event.'",
      "API mock intro separates read/write paths and client constraints — versioning and pagination are scoring points.",
      "GraphQL when? — Complex mobile clients — REST fine for focused mock.",
      "gRPC internal? — Edge HTTP public, gRPC service-to-service.",
      "Unversioned public API",
      "OFFSET pagination on real-time feed",
      "Analytics on synchronous hot read path"),
    q("Scale Estimation Mock Intro", "Whiteboard Mock", "Very Common",
      "How lead scale estimation in the first 10 minutes of a system design mock?",
      "State assumptions explicitly, compute DAU → daily ops → average QPS → peak QPS, then storage and bandwidth. Use results to justify cache, queue, shard, or CDN — estimation drives architecture.",
      "**Estimation script:**\n1. **Users** — 'Assume 10M DAU'\n2. **Actions** — '10 actions/user/day → 100M ops/day'\n3. **QPS** — `100M ÷ 86400 ≈ 1.2K avg`; `×3 peak ≈ 3.5K QPS`\n4. **Read/write** — '100:1 → ~35 write QPS, ~3.5K read QPS'\n5. **Storage** — `posts/day × size × retention`\n6. **Bandwidth** — `QPS × payload KB`\n\n**Quick mental math:**\n- 1M seconds ≈ 11.5 days\n- 1 billion bytes ≈ 1 GB\n\n**Translate to decisions:**\n| Result | Architecture hint |\n|--------|-------------------|\n| Read-heavy | CDN + Redis |\n| 3K read QPS | Cache mandatory |\n| 10GB/day growth | Shard later; plan retention |\n| Large payloads | Async upload + queue |\n\n**Say aloud:** 'These are order-of-magnitude — if DAU 10×, cache tier becomes insufficient.'\n\n**Avoid:** Random 'billions of requests' without derivation.",
      "Scale estimation mock intro proves architectural thinking — math links directly to component choices.",
      "Power-of-two shortcuts? — 1M sec ≈ 11.5 days — speeds mental division.",
      "Sensitivity analysis? — 'If actions 50/day not 10, QPS 5×' — shows rigor.",
      "No written assumptions on board",
      "Skip estimation and jump to Redis",
      "Memorized QPS without showing derivation"),
]

ALL_WEEKS_45_48_Q001_Q005 = {
    45: WEEK_45_Q001_Q005,
    46: WEEK_46_Q001_Q005,
    47: WEEK_47_Q001_Q005,
    48: WEEK_48_Q001_Q005,
}
