"""Premium Microservices Top 50 interview Q&A — Part 2 (Q009–Q030) and Part 3 (Q031–Q050)."""


def q(title, difficulty, category, week, question, short, detailed, fu1, fu2, m1, m2):
    return dict(
        title=title,
        difficulty=difficulty,
        category=category,
        week=week,
        question=question,
        short=short,
        detailed=detailed,
        followups=f"1. **{fu1}**\n2. **{fu2}**",
        mistakes=f"- {m1}\n- {m2}",
    )


MICROSERVICES_PART2_Q009_Q030 = [
    q(
        "Saga — Orchestration vs Choreography",
        "Intermediate",
        "Distributed Transactions",
        24,
        "Compare saga orchestration and choreography for order checkout. When do you choose each?",
        "Choreography — services react to domain events without a central coordinator. Orchestration — a saga coordinator drives each step and compensation. Choreography for 2–4 simple steps; orchestration when you need visibility, timeouts, and complex compensation across 5+ steps.",
        "**Choreography:** Order service publishes `OrderPlaced` → Inventory reserves → Payment charges → Shipping creates label. No central brain — flow emerges from event handlers.\n\n**Pros:** loose coupling, no orchestrator SPOF, natural fit for event-driven teams.\n**Cons:** implicit flow (hard to read), debugging requires distributed tracing, compensation logic scattered.\n\n**Orchestration:** Durable Functions / custom saga service calls Inventory → Payment → Shipping; on failure runs compensations in reverse order.\n\n**Pros:** explicit state machine, centralized timeout/retry, easier audit for regulated checkout.\n**Cons:** orchestrator is a dependency; can become a mini-monolith if it holds domain logic.\n\n| Factor | Choreography | Orchestration |\n|--------|--------------|---------------|\n| Steps | ≤4, linear | 5+, branching |\n| Visibility | Low | High |\n| Team maturity | Strong event culture | Mixed |\n| Compliance audit | Harder | Easier |\n\n**Architect:** Start choreography for notifications; orchestrate payment + inventory + fraud because money is involved.",
        "Can you mix both? — Yes — orchestrate payment path, choreograph downstream fulfillment events.",
        "How test sagas? — State-machine unit tests + contract tests per step + chaos on compensation paths.",
        "Choosing orchestration for 3-step happy path only",
        "No saga log or correlation ID across steps",
    ),
    q(
        "Transactional Outbox Pattern",
        "Intermediate",
        "Messaging",
        24,
        "Why use the transactional outbox instead of publishing events immediately after SaveChanges?",
        "Dual-write problem — DB commits but broker publish fails (or the reverse). Outbox writes the event in the same DB transaction as business data; a relay publishes reliably with at-least-once delivery.",
        "**Anti-pattern:**\n```csharp\nawait _db.Orders.AddAsync(order);\nawait _db.SaveChangesAsync();\nawait _bus.PublishAsync(new OrderPlaced(order)); // can fail after commit\n```\n\n**Outbox fix:**\n1. INSERT order + INSERT outbox row in one transaction\n2. Relay polls or CDC reads outbox → publishes to Service Bus / Kafka\n3. Mark row processed (or delete with retention policy)\n\n**Relay options:**\n- **Polling** with `FOR UPDATE SKIP LOCKED` — simple, slight lag\n- **CDC (Debezium)** — scales, captures all changes, more ops\n- **Azure SQL trigger → Service Bus** — managed middle ground\n\n**Architect checklist:** index on unprocessed rows, partition key = aggregate ID for ordering, consumer idempotency mandatory, monitor relay lag SLO.",
        "Outbox vs inbox? — Outbox is publisher-side guarantee; inbox deduplicates on consumer.",
        "Exactly-once end-to-end? — Effectively-once: outbox + idempotent consumer + inbox.",
        "Publishing before DB commit",
        "Outbox table without index on unprocessed rows",
    ),
    q(
        "Strangler Fig Migration",
        "Intermediate",
        "Decomposition",
        23,
        "Describe the strangler fig pattern for extracting a module from a .NET monolith.",
        "Route increasing traffic through a proxy/gateway to the new microservice while the legacy monolith handles the remainder. Extract highest-value module first; retire legacy paths when metrics show 100% migration.",
        "**Steps:**\n1. **Facade** — APIM / YARP / nginx in front of monolith\n2. **Identify seam** — order placement API is a clean boundary\n3. **Build new service** — owns Order DB, implements same contract (or versioned)\n4. **Route by path/header** — `/api/v2/orders` → new service; legacy → monolith\n5. **Migrate data** — dual-write or CDC sync until cutover\n6. **Retire** — delete monolith order module when error rate and traffic = 0\n\n**Example routing:**\n```\nif (featureFlag \"OrderServiceV2\" && path.StartsWith(\"/orders\"))\n    proxy to order-service\nelse\n    proxy to monolith\n```\n\n**Architect:** Never big-bang. Measure extraction with traffic %, error parity, and latency delta. Document ADR per extracted context.",
        "Which module first? — Highest pain: deploy frequency blocker, scale bottleneck, or team boundary.",
        "Data migration strategy? — CDC + reconciliation job; avoid stop-the-world dump.",
        "Big-bang rewrite instead of incremental routing",
        "No rollback path when new service error rate spikes",
    ),
    q(
        "Backend-for-Frontend (BFF)",
        "Intermediate",
        "API Design",
        22,
        "When should you add a Backend-for-Frontend layer in a microservices architecture?",
        "When mobile, web, and partner clients need different aggregation shapes and latency budgets. Separate BFFs prevent a lowest-common-denominator API that over-fetches for mobile and under-serves web dashboards.",
        "**Without BFF:** Mobile app calls 8 services for homepage — battery drain, fragile on 3G.\n\n**With BFF:**\n- `mobile-bff` — 1 aggregated `/home` response, image URLs resized\n- `web-bff` — richer payload, server-driven pagination\n- `partner-bff` — strict rate limits, API-key auth, stable v1 contract\n\n**BFF responsibilities:** aggregation, protocol translation (GraphQL optional), auth token exchange, response shaping — **not** domain business rules.\n\n**Placement:** BFF sits behind API gateway; calls domain services via internal network.\n\n| Anti-pattern | Fix |\n|--------------|-----|\n| BFF owns order business logic | Move rules to Order service |\n| One BFF for all clients | Split by client persona |\n| BFF writes to multiple DBs | BFF orchestrates via APIs only |",
        "BFF vs API gateway? — Gateway = cross-cutting edge (TLS, rate limit); BFF = client-specific composition.",
        "Can BFF call BFF? — Avoid chains; flatten to domain services.",
        "Putting domain validation only in BFF",
        "Single BFF becoming a new monolith with shared DB access",
    ),
    q(
        "Database Per Service",
        "Intermediate",
        "Data",
        22,
        "Explain database-per-service. How do you handle cross-service queries and reporting?",
        "Each microservice owns its schema and storage — no foreign keys across service boundaries. Cross-service data via APIs, cached snapshots, events, or read models. Analytics uses a warehouse fed by domain events.",
        "**Principle:** Order service has `Orders` DB; Catalog has `Products` DB. Order line stores `productId` + denormalized `productName` snapshot — never JOIN across DBs at runtime.\n\n**Cross-service read patterns:**\n1. **API composition** — BFF calls Catalog for product details (acceptable for low volume)\n2. **Cache** — Redis materialized product card keyed by `productId`\n3. **Event-driven projection** — `ProductUpdated` event updates read model in Order service\n4. **CQRS read store** — dedicated query DB fed by event stream\n5. **Data warehouse** — nightly / streaming ETL for BI\n\n**Architect:** Choose consistency per use case — checkout needs strong order write; product name on receipt can be eventually consistent snapshot.",
        "Polyglot persistence? — Order = SQL, Search = Elasticsearch, Cart = Redis — each fits the access pattern.",
        "Shared read replica? — Still violates ownership if services write to same tables.",
        "Shared database antipattern (hidden monolith)",
        "Distributed JOIN attempts across service databases",
    ),
    q(
        "Sync vs Async Communication",
        "Intermediate",
        "Communication",
        22,
        "When do you use synchronous HTTP vs asynchronous messaging between microservices?",
        "Sync when the caller needs an immediate result for the user (checkout total, fraud check). Async for fire-and-forget, long-running work, or decoupling peak load (email, analytics, report generation). Avoid sync chains deeper than 2–3 hops.",
        "**Synchronous (HTTP/gRPC):**\n- User waits for response\n- Simpler mental model and debugging\n- Couples availability in time — downstream outage blocks caller\n- Requires timeout + circuit breaker + bulkhead\n\n**Asynchronous (events/queues):**\n- Temporal decoupling — producer doesn't wait\n- Natural load leveling and retry\n- Complexity: ordering, idempotency, poison messages, eventual consistency UX\n\n**Decision matrix:**\n| Scenario | Choice |\n|----------|--------|\n| Get order status for user | Sync (or sync + cache) |\n| Send confirmation email | Async |\n| Payment authorization | Sync with 3s timeout |\n| Update search index | Async |\n\n**Architect rule:** If failure must be shown to the user immediately → sync with resilience patterns. Otherwise → prefer events.",
        "gRPC vs REST? — gRPC for internal east-west, low latency, strong contracts; REST at edge for browser clients.",
        "Request-reply over queue? — Valid pattern when you need async but still need a response (correlation ID + reply queue).",
        "Six-service sync chain for page load",
        "Async for user-facing status query without polling or WebSocket",
    ),
    q(
        "Circuit Breaker Pattern",
        "Intermediate",
        "Resilience",
        21,
        "How does a circuit breaker protect a microservices system? How do you tune it per dependency?",
        "After a failure threshold, stop calling the failing dependency — fail fast instead of hanging. Half-open sends probe requests to detect recovery. Prevents thread pool exhaustion and cascading failures.",
        "**States:** Closed (normal) → Open (fail fast) → Half-open (test probe) → Closed or re-Open.\n\n**Polly / .NET resilience pipeline example:**\n- Payment: 30% failures in 20s window, minimum 10 requests → open 60s\n- Recommendations: 50% failures, open 10s, fallback to cached defaults\n\n**Pair with:**\n- **Timeout** — shorter than client SLA\n- **Fallback** — cached response, degraded mode, empty list\n- **Bulkhead** — isolate thread pools per dependency\n\n**Monitor:** `circuit_state` metric; alert if open > 2 minutes.\n\n**Architect:** Document fallback behavior in ADR — users see empty recommendations, not a 500 homepage.",
        "Circuit breaker vs retry? — Don't retry when circuit is open; retry only on transient errors when closed.",
        "Hedging requests? — Send duplicate to backup after delay — use sparingly, doubles load.",
        "Same breaker settings for payment and recommendations",
        "Circuit open with no fallback UX or cached response",
    ),
    q(
        "Bulkhead Pattern",
        "Intermediate",
        "Resilience",
        21,
        "How does the bulkhead pattern prevent one slow dependency from starving others?",
        "Isolate resources (thread pools, connections, semaphores) per downstream dependency — email slowness cannot exhaust the pool used for payment calls.",
        "**Without bulkhead:** Shared `HttpClient` pool of 100 threads — slow email service blocks all 100 → payment requests queue → checkout times out.\n\n**With bulkhead:**\n```csharp\n// Separate pipelines per downstream\nservices.AddHttpClient(\"Payment\").AddStandardResilienceHandler(...);\nservices.AddHttpClient(\"Email\").AddStandardResilienceHandler(...);\n// Polly bulkhead: max 10 parallel, queue 20 for email only\n```\n\n**K8s variant:** Separate deployments for critical vs batch workloads; different node pools.\n\n**Sizing:** Load test at 2× peak — payment pool sized for Black Friday checkout, email pool sized for async notification backlog.\n\n**Defense in depth:** Bulkhead + circuit breaker + timeout = three independent failure containment layers.",
        "Bulkhead vs rate limiting? — Bulkhead limits concurrent calls to one dependency; rate limit caps requests per time window (often per client).",
        "Thread pool vs connection pool? — Both can be bulkheaded; HttpClient handler isolation is the .NET pattern.",
        "Single shared HttpClient for all downstreams",
        "Unbounded queue on bulkhead — still risks memory pressure",
    ),
    q(
        "Service Mesh — When to Adopt",
        "Advanced",
        "Infrastructure",
        23,
        "At what scale and maturity should you adopt a service mesh (Istio, Linkerd, Dapr)?",
        "Typically 15+ services needing uniform mTLS, traffic splitting, and observability without library sprawl. Overkill for 3–5 services — use Polly, OpenTelemetry SDK, and APIM first.",
        "**Service mesh provides:**\n- **mTLS** east-west without app code changes\n- **Traffic management** — canary, A/B, fault injection\n- **Observability** — automatic metrics, traces per hop\n- **Policy** — rate limits, authz at L7\n\n**Cost:** Operational complexity, sidecar CPU/memory overhead (~50–100MB per pod), steep learning curve.\n\n**Decision framework:**\n| Signal | Action |\n|--------|--------|\n| <10 services, one team | Libraries + gateway |\n| 15+ services, polyglot | Evaluate mesh |\n| Strict zero-trust east-west | Mesh or service-level mTLS |\n| AKS + GitOps mature | Istio/Linkerd viable |\n\n**Dapr alternative:** Portable building blocks (pub/sub, state, secrets) without full mesh — good for .NET teams on Azure.",
        "Sidecar vs node agent? — Sidecar per pod is standard; node agent reduces overhead but weaker isolation.",
        "Mesh vs API gateway? — Gateway = north-south; mesh = east-west between services.",
        "Adopting Istio before CI/CD and observability baselines exist",
        "Mesh for 3 services — operational tax exceeds benefit",
    ),
    q(
        "Contract Testing",
        "Intermediate",
        "Testing",
        24,
        "How do contract tests avoid the integration test grid explosion in microservices?",
        "Consumer-driven contracts (Pact) define expected API shapes; provider verifies against published contracts in CI — no need to spin up all 20 services for every PR.",
        "**Problem:** 15 services × 15 consumers = 225 integration combinations — E2E suite takes hours, flakes constantly.\n\n**Contract testing flow:**\n1. Order service (consumer) defines: `POST /payments` expects `{ amount, currency }` → `{ transactionId }`\n2. Pact file published to broker\n3. Payment service (provider) CI runs `verify pact` — fails if response shape changes\n4. Deploy independently with confidence\n\n**Scope:** HTTP request/response, message schemas (asyncAPI), event payloads.\n\n**Not a replacement for:** A thin smoke E2E suite (5 critical journeys) and production synthetic monitoring.\n\n**Architect:** Mandate contract tests in platform golden path template; broker (Pactflow) for cross-team visibility.",
        "Contract vs schema registry? — Schema registry (Avro/Protobuf) for events; Pact for behavioral HTTP contracts.",
        "Who owns breaking changes? — Provider notifies consumers; run v1/v2 parallel during deprecation window.",
        "Replacing all E2E with contracts — miss wiring bugs",
        "Contracts that test implementation details instead of public interface",
    ),
    q(
        "API Versioning Strategy",
        "Intermediate",
        "API Design",
        22,
        "A payment API needs a breaking change. What versioning strategy do you recommend?",
        "Run v1 and v2 in parallel with a published deprecation timeline. Prefer URL path versioning (`/v2/payments`) for clarity; header versioning for internal services. Never break consumers without 90-day notice.",
        "**Strategies:**\n| Approach | Pros | Cons |\n|----------|------|------|\n| URL `/v2/` | Explicit, cacheable | URL proliferation |\n| Header `Api-Version: 2` | Clean URLs | Harder to test in browser |\n| Query `?version=2` | Easy | Easy to forget |\n\n**Breaking change playbook:**\n1. Announce deprecation in changelog + email\n2. Deploy v2 alongside v1 (separate controllers or route maps)\n3. Monitor v1 traffic — alert when >5% remains at day 60\n4. Sunset v1 after 90 days (or contractual SLA)\n\n**.NET:** `[ApiVersion(\"2.0\")]` + `AddApiVersioning()` with default version reporting.\n\n**Architect:** Prefer additive changes (new optional fields) over breaking — event schema evolution uses same discipline.",
        "GraphQL versioning? — Avoid — deprecate fields with `@deprecated` directive instead.",
        "Internal vs public API versioning? — Internal can move faster; public needs longer deprecation.",
        "Breaking change without parallel version running",
        "Version in URL for events — use schema version in payload instead",
    ),
    q(
        "Event Choreography",
        "Intermediate",
        "Event-Driven",
        24,
        "Explain event choreography and its trade-offs compared to orchestrated sagas.",
        "Choreography coordinates workflows through domain events — each service knows only what to do when it sees an event. No central coordinator. Works for simple flows; becomes hard to reason about at scale.",
        "**Example — order fulfillment:**\n```\nOrderPlaced → Inventory: ReserveStock\nStockReserved → Payment: Charge\nPaymentCompleted → Shipping: CreateLabel\nLabelCreated → Notification: SendEmail\n```\n\nEach handler is independent — adding FraudCheck means subscribing to `OrderPlaced`, not editing orchestrator code.\n\n**Risks:**\n- **Implicit process** — new engineer can't read one state machine\n- **Cyclic events** — A triggers B triggers A without guard\n- **Compensation scatter** — refund logic in 3 services\n- **Debugging** — need correlation ID + distributed trace\n\n**Mitigation:** Event catalog documenting publishers/subscribers; process manager only for compensation; saga log table per aggregate.",
        "Event notification vs event-carried state transfer? — Notification carries ID only (extra API call); ECST carries data (larger messages, fewer calls).",
        "How avoid infinite loops? — Idempotent handlers + processed-event inbox + version checks.",
        "Choreography for 8-step payment saga with compliance audit",
        "No event catalog or ownership matrix",
    ),
    q(
        "Shared Database Anti-Pattern",
        "Fundamentals",
        "Data",
        22,
        "Why is a shared database among microservices considered an anti-pattern?",
        "Shared DB creates a hidden monolith — services couple through schema, deploy together for migrations, and fight over indexes. You lose independent deployment, team autonomy, and clear ownership.",
        "**Symptoms:**\n- Three services `UPDATE` the same `Orders` table\n- Schema migration requires coordinating 5 deploys\n- No one owns the `Customers` table — everyone adds columns\n- Foreign keys across logical service boundaries\n\n**Why teams do it:** Faster initial extraction, fear of distributed queries, legacy inertia.\n\n**Escape path:**\n1. Assign table ownership per bounded context\n2. Other services access via API or events only\n3. Database views as temporary ACL (read-only) during migration\n4. Strangler extracts write ownership first\n\n**Architect:** Shared DB is acceptable as a **temporary** migration state with a dated exit ADR — not a target architecture.",
        "Shared read replica OK? — Read-only replica of owned data is fine; shared writable tables are not.",
        "Database-per-service with shared server? — Acceptable isolation step — separate schemas, no cross-schema FKs.",
        "Calling it microservices while sharing one SQL instance with cross-service FKs",
        "No migration plan off shared schema",
    ),
    q(
        "Distributed Tracing",
        "Intermediate",
        "Observability",
        21,
        "How do you trace a single user request across 8 microservices in production?",
        "Propagate W3C `traceparent` on every HTTP call and message metadata. OpenTelemetry SDK in each service exports spans to App Insights, Jaeger, or Grafana Tempo — one trace ID ties the full journey.",
        "**Implementation:**\n1. Edge gateway creates or forwards `traceparent`\n2. Each service: `ActivitySource` → span per operation\n3. Outbound HTTP: inject trace context headers\n4. Message bus: add `traceparent` to message properties\n5. Correlate with `correlation-id` for business logs\n\n**.NET:**\n```csharp\nbuilder.Services.AddOpenTelemetry()\n    .WithTracing(t => t.AddAspNetCoreInstrumentation()\n        .AddHttpClientInstrumentation()\n        .AddAzureMonitorTraceExporter());\n```\n\n**Architect SLO:** 100% of production services export traces; sampling at 10% for cost, 100% on errors. Dashboard: p95 per hop to find slow service in chain.",
        "Trace vs log correlation? — Trace shows span tree; logs attach `trace_id` for drill-down.",
        "Sampling strategy? — Head-based for volume; tail-based (always keep slow/error traces) for debugging.",
        "Different trace IDs per hop — broken propagation",
        "Tracing only at gateway — blind to internal service latency",
    ),
    q(
        "Health Checks — Liveness vs Readiness",
        "Fundamentals",
        "Operations",
        21,
        "Explain liveness and readiness probes in Kubernetes for .NET microservices.",
        "Liveness — is the process alive? Restart if deadlocked. Readiness — can this instance accept traffic? Remove from load balancer during startup, migration, or dependency outage.",
        "**Liveness probe:** `GET /health/live` — returns 200 if app process responds. Fails → K8s restarts pod.\n- Keep lightweight — no DB calls\n- Detect deadlocks and infinite loops\n\n**Readiness probe:** `GET /health/ready` — checks DB connection, cache, critical downstream.\n- Fails → pod removed from Service endpoints\n- Use during: EF migration on startup, warming cache, dependency temporarily down\n\n**.NET:**\n```csharp\nbuilder.Services.AddHealthChecks()\n    .AddSqlServer(conn)\n    .AddCheck(\"downstream\", () => _paymentHealth.IsHealthy());\napp.MapHealthChecks(\"/health/ready\", new() { Predicate = r => r.Tags.Contains(\"ready\") });\n```\n\n**Architect:** Never put slow external calls in liveness — cascading restart storm. Startup probe for slow .NET cold start.",
        "Startup probe? — K8s 1.16+ — allows long startup before liveness kills the pod.",
        "Health check in load balancer vs K8s? — Same endpoints; ALB/App Gateway can use `/health/ready`.",
        "DB check in liveness probe — restart loop when SQL blips",
        "Readiness always 200 — traffic sent to instance still starting",
    ),
    q(
        "Configuration Externalization",
        "Intermediate",
        "Operations",
        23,
        "How should microservices externalize configuration per the twelve-factor app methodology?",
        "Store config in environment — Azure App Configuration, Key Vault, K8s ConfigMaps/Secrets. No secrets in source control. Validate at startup; support reload without redeploy for non-secret toggles.",
        "**Hierarchy (lowest → highest precedence):**\n1. `appsettings.json` (defaults only)\n2. `appsettings.{Environment}.json`\n3. Environment variables\n4. Azure App Configuration (with Key Vault references)\n5. Feature flags (dynamic)\n\n**.NET pattern:**\n```csharp\nbuilder.Configuration.AddAzureAppConfiguration(options =>\n    options.Connect(conn).ConfigureKeyVault(kv => kv.SetCredential(credential)));\nbuilder.Services.Configure<PaymentOptions>(builder.Configuration.GetSection(\"Payment\"));\n```\n\n**Per-service config:** Each service owns its config namespace — `OrderService:Database`, not one giant shared file.\n\n**Architect:** `IOptionsMonitor<T>` for hot reload; `IValidateOptions<T>` fail fast on invalid config; audit who changed production config.",
        "ConfigMap vs Secret in K8s? — ConfigMap for non-sensitive; Secret (encrypted at rest) for connection strings.",
        "GitOps for config? — Store non-secret config in repo; secrets via External Secrets Operator → Key Vault.",
        "Connection strings committed to Git",
        "One global config file shared across all services — coupling and blast radius",
    ),
    q(
        "Feature Flags in Microservices",
        "Intermediate",
        "Release Engineering",
        23,
        "How do feature flags enable independent deployment and safe rollout per microservice?",
        "Deploy code to production with features dark; enable per service, per tenant, or per user percentage without redeploy. Decouples deployment from release — critical for trunk-based development across teams.",
        "**Flag types:**\n- **Release** — short-lived (`CheckoutV2`), remove after 100%\n- **Ops** — permanent kill switch (`UseBackupPaymentProvider`)\n- **Experiment** — A/B test with metrics\n\n**Per-service independence:** Order service ships `ExpressCheckout` flag; Payment service unaffected. Shared platform: Azure App Configuration Feature Manager or LaunchDarkly.\n\n**.NET:**\n```csharp\nif (await _featureManager.IsEnabledAsync(\"CheckoutV2\"))\n    return await _checkoutV2.ProcessAsync(order);\n```\n\n**Architect:** Flag hygiene — ticket to remove flag + dead code within 2 sprints after full rollout. Monitor error rate per flag variant.",
        "Flags vs API versioning? — Flags toggle behavior within a version; versioning for contract breaks.",
        "Test matrix? — CI runs integration tests with flag on AND off.",
        "Permanent flags becoming spaghetti conditionals",
        "Using flags as security boundary instead of proper auth",
    ),
    q(
        "Testing Pyramid for Microservices",
        "Intermediate",
        "Testing",
        24,
        "Describe the test pyramid for microservices. What belongs at each layer?",
        "Many fast unit tests, fewer integration tests, contract tests between services, minimal E2E. Unit tests domain logic; contract tests API boundaries; E2E only for critical revenue paths.",
        "**Pyramid layers:**\n```\n        /  E2E  \\        ← 5–10 critical journeys\n       / Contract \\      ← every service boundary\n      / Integration \\    ← DB, message bus, one service\n     /     Unit      \\   ← domain, handlers, policies\n```\n\n| Layer | Scope | Speed | Example |\n|-------|-------|-------|--------|\n| Unit | Pure logic | ms | Saga compensation rules |\n| Integration | Service + DB | sec | Order repo with Testcontainers |\n| Contract | Consumer ↔ Provider | sec | Pact verify payment API |\n| E2E | Full stack | min | Place order smoke in staging |\n\n**Architect:** If E2E suite > 30 min, teams stop running it — invest in contracts. Testcontainers for SQL/Redis in CI without shared staging env.",
        "Component tests? — Test one service with mocked external HTTP — between integration and contract.",
        "Chaos testing layer? — Production/staging fault injection — not daily CI, scheduled game days.",
        "E2E-only strategy — slow, flaky, blocks deploys",
        "No contract tests — breaking changes discovered in production",
    ),
    q(
        "Domain Events",
        "Intermediate",
        "DDD",
        23,
        "What are domain events and how do they differ from integration events in microservices?",
        "Domain events represent something that happened in the domain (`OrderPlaced`, `PaymentFailed`) — past tense, immutable. Integration events are the cross-service message format; domain events may be translated before publishing.",
        "**Domain event (in-process):**\n```csharp\npublic record OrderPlaced(Guid OrderId, decimal Total) : IDomainEvent;\n// Raised inside aggregate, handled by same bounded context handlers\n```\n\n**Integration event (cross-service):**\n```json\n{ \"type\": \"orders.placed.v1\", \"orderId\": \"...\", \"total\": 99.99 }\n```\n\n**Flow:** Aggregate raises domain event → handler persists to outbox → relay publishes integration event → other services consume.\n\n**Rules:**\n- Name in past tense\n- Carry minimal data (ID + changed fields)\n- Version schema (`v1`, `v2` additive)\n- One publisher per event type (clear ownership)\n\n**Architect:** Event storming workshop produces the catalog before writing code.",
        "Domain event vs command? — Command is intent (`PlaceOrder`); event is fact (`OrderPlaced`).",
        "Event sourcing? — Store events as source of truth — domain events are the persistence model.",
        "Publishing domain model entities directly as integration events",
        "Events named as commands (`PlaceOrder` on the bus)",
    ),
    q(
        "Deployment Independence",
        "Intermediate",
        "Operations",
        22,
        "What does deployment independence mean for microservices and how do you achieve it?",
        "Each service deploys on its own schedule without coordinating other teams. Achieved via versioned APIs, backward-compatible events, contract tests, feature flags, and database-per-service.",
        "**Enablers:**\n1. **Database per service** — no shared schema migrations\n2. **Contract tests** — detect breaking API changes in CI\n3. **Additive event schemas** — new fields optional; consumers ignore unknown\n4. **Feature flags** — dark deploy new behavior\n5. **Independent CI/CD pipelines** — one repo per service or monorepo with path filters\n\n**Blockers to fix:**\n- Shared library version lockstep (treat as product with semver)\n- Distributed monolith — must deploy A+B together\n- Shared database foreign keys\n\n**Metric:** Deployment frequency per service — elite teams deploy individual services multiple times daily.\n\n**Architect:** If two services always deploy together, they are one service until you fix the coupling.",
        "Monorepo vs polyrepo? — Both work — key is independent pipeline per service artifact.",
        "Shared NuGet domain package? — Version with semver; consumers upgrade on their schedule.",
        "Coordinated big-bang releases across all services",
        "Breaking API change without deprecation period",
    ),
    q(
        "Consumer-Driven Contracts",
        "Intermediate",
        "Testing",
        24,
        "Explain consumer-driven contract testing and how it shifts the testing responsibility.",
        "Consumers define the API contract they need; providers verify they satisfy it. Shifts from provider-defined specs (often ignored) to consumer-defined expectations (enforced in CI).",
        "**Traditional:** Payment team publishes OpenAPI → Order team hopes it's accurate.\n\n**CDC:** Order team (consumer) writes Pact: \"When I POST `{amount}`, I expect 201 + `{transactionId}`\". Payment CI must pass `pact verify` before deploy.\n\n**Workflow:**\n1. Consumer PR generates pact JSON\n2. Publish to Pact Broker\n3. Provider `can-i-deploy` check before production\n4. Breaking change → provider negotiates with consumers\n\n**Benefits:** Independent deploy velocity, living documentation, fails in minutes not hours.\n\n**Architect:** Platform provides Pact template in .NET service scaffold; broker is shared infrastructure.",
        "Provider-driven vs consumer-driven? — Provider-driven (OpenAPI) documents intent; CDC enforces what consumers actually use.",
        "Message contracts? — Pact supports async — message pact for event payloads.",
        "Contracts testing unused endpoints",
        "No broker — contracts only on developer laptops",
    ),
    q(
        "API Gateway Patterns",
        "Intermediate",
        "Gateway",
        22,
        "What patterns belong in an API gateway vs individual microservices?",
        "Gateway handles cross-cutting edge concerns: TLS, authentication, rate limiting, routing, WAF, request size limits. Services own business logic, domain validation, and data access.",
        "**Gateway responsibilities:**\n- TLS termination and certificate management\n- JWT validation / OAuth token introspection\n- Rate limiting per client/API key\n- Path-based routing (`/orders` → order-service)\n- Request/response transformation (header injection)\n- API product management (APIM developer portal)\n\n**Service responsibilities:**\n- Business rules and domain invariants\n- Authorization (can this user cancel this order?)\n- Data persistence and transactions\n\n**Patterns:**\n| Pattern | Where |\n|---------|-------|\n| BFF aggregation | Behind gateway |\n| Strangler routing | Gateway/YARP |\n| mTLS east-west | Service mesh, not gateway |\n\n**Azure:** APIM + App Gateway or AKS Ingress + internal services.\n\n**Anti-pattern:** All validation in gateway — duplicates service logic, drifts, can't enforce on internal calls.",
        "Ocelot vs APIM? — Ocelot for OSS/K8s ingress; APIM for enterprise governance, monetization, developer portal.",
        "GraphQL gateway? — Federation gateway routes to subgraph services — different from REST gateway.",
        "Domain business rules enforced only at gateway",
        "Gateway calling 10 services synchronously per request without BFF",
    ),
]

MICROSERVICES_PART3_Q031_Q050 = [
    q(
        "Scenario — Payment Double Charge",
        "Advanced",
        "Scenario",
        24,
        "A customer was charged twice when the mobile app retried checkout after a timeout. Design the fix.",
        "Require `Idempotency-Key` header on payment API; store key→result mapping 24h; same key returns cached response without re-charging. Pair with saga compensation if partial failure after charge.",
        "**Root cause:** Client timeout ≠ server failure — payment succeeded but client retried.\n\n**Fix layers:**\n1. **Client:** Generate UUID idempotency key per checkout attempt; retry with same key\n2. **Payment API:**\n```sql\nINSERT INTO idempotency_keys (key, response, created_at)\nVALUES (@key, @response, NOW())\nON CONFLICT (key) DO NOTHING RETURNING response;\n```\n3. **Store result** before returning 200 — include `transactionId`\n4. **Saga:** If charge succeeded but order creation failed → compensating refund (idempotent refund API)\n\n**Monitoring:** Alert on duplicate key hits > baseline — may indicate client bug.\n\n**Architect:** Idempotency is mandatory for all money-moving POST endpoints — document in API standards.",
        "Idempotency key TTL? — 24h typical; 7d for B2B with slow retries.",
        "Stripe-style approach? — Same pattern — `Idempotency-Key` header is industry standard.",
        "Relying on client to never retry",
        "Idempotency check after side effect executes",
    ),
    q(
        "Scenario — Inventory Oversell",
        "Advanced",
        "Scenario",
        24,
        "During a flash sale, 100 units were sold to 150 customers. How do you prevent inventory oversell?",
        "Use atomic reservation with optimistic or pessimistic concurrency — never read-then-write without version check. Reserve with TTL; confirm on payment; release on timeout.",
        "**Anti-pattern:**\n```sql\nSELECT stock FROM products WHERE id = @id; -- reads 1\n-- 150 concurrent requests all see stock >= 1\nUPDATE products SET stock = stock - 1 WHERE id = @id;\n```\n\n**Fix — optimistic concurrency:**\n```sql\nUPDATE inventory SET quantity = quantity - 1, version = version + 1\nWHERE product_id = @id AND quantity > 0 AND version = @expectedVersion;\n-- rows affected = 0 → return 409 Conflict to client\n```\n\n**Reservation pattern:**\n1. `Reserve(quantity)` → hold with 15-min TTL\n2. Payment succeeds → `ConfirmReservation`\n3. Payment fails / timeout → `ReleaseReservation`\n\n**Overflow:** Queue excess orders; show \"waitlisted\" UX.\n\n**Architect:** Flash sale = load test scenario — Redis atomic DECR or SQL row lock — pick based on consistency needs.",
        "Redis vs SQL for inventory? — Redis for speed with periodic reconciliation to SQL source of truth.",
        "Oversell acceptable? — Some catalogs allow 2% oversell — business decision, not technical default.",
        "Read-then-write without locking or version column",
        "No reservation TTL — orphan holds block inventory",
    ),
    q(
        "Scenario — Cascading Failure",
        "Advanced",
        "Scenario",
        21,
        "A slow recommendation service took down the entire homepage. How do you contain the failure?",
        "Circuit breaker + aggressive timeout + fallback (empty recommendations) + bulkhead isolation. Homepage must degrade gracefully — never fail because a non-critical dependency is slow.",
        "**Failure chain:** Homepage → Recommendations (30s timeout) → thread pool exhausted → all requests queue → 503 everywhere.\n\n**Containment:**\n1. **Timeout:** 500ms for recommendations — not 30s\n2. **Circuit breaker:** Open after 50% failures in 10s\n3. **Fallback:** Return cached popular items or empty section\n4. **Bulkhead:** Separate thread pool for recommendations vs core content\n5. **Async load:** Fetch recommendations client-side or via edge cache\n\n**UX:** Hide recommendations section vs show skeleton — A/B test; empty is better than spinner forever.\n\n**Architect:** Classify dependencies Tier 1 (must work) vs Tier 3 (nice to have) — different resilience policies per tier.",
        "Chaos engineering validation? — Inject latency on recommendations in staging — verify homepage SLO holds.",
        "Retry storm? — Don't retry slow dependency when circuit open — amplifies load.",
        "Same timeout for payment and recommendations",
        "No fallback — 500 when non-critical service fails",
    ),
    q(
        "Scenario — Schema Migration Zero Downtime",
        "Advanced",
        "Scenario",
        23,
        "You must add a non-null column to the orders table in production with zero downtime. Walk through the approach.",
        "Use expand-contract: add nullable column → deploy code that writes both old and new → backfill → enforce NOT NULL → remove old column. Never breaking schema + code in same deploy.",
        "**Expand-contract phases:**\n1. **Expand:** `ALTER TABLE orders ADD new_status VARCHAR(20) NULL`\n2. **Deploy app v1:** Writes to both `status` and `new_status`; reads from `status`\n3. **Backfill:** `UPDATE orders SET new_status = status WHERE new_status IS NULL` (batched)\n4. **Deploy app v2:** Reads from `new_status`; still writes both\n5. **Contract:** `ALTER TABLE orders ALTER COLUMN new_status SET NOT NULL`\n6. **Deploy app v3:** Drop `status` column reference\n7. **Cleanup:** `ALTER TABLE orders DROP COLUMN status`\n\n**Rolling deploy:** Old and new pods coexist — schema must support both versions.\n\n**EF Core:** Multiple migrations across releases, not one big migration.\n\n**Architect:** Document in ADR; run during low traffic; monitor replication lag on backfill.",
        "Rename column? — Add new → copy → switch reads → drop old — never `RENAME` in one step with live traffic.",
        "Blue/green DB? — Dual-write to both databases during migration — higher cost, faster cutover.",
        "NOT NULL column added and populated in single deploy",
        "Breaking rename without dual-write period",
    ),
    q(
        "Scenario — 90-Day Microservices Plan",
        "Advanced",
        "Scenario",
        23,
        "You inherit a .NET monolith. Outline a 90-day plan to extract the first microservice safely.",
        "Days 1–30: domain discovery, CI/CD, observability, pick extraction candidate. Days 31–60: strangler routing, build service, 5% traffic. Days 61–90: ramp to 100%, retire legacy path, document playbook for service #2.",
        "**Days 1–30:** Domain discovery (event storming), DORA baseline, CI/CD + observability on monolith, pick extraction candidate (highest pain module), ADR for boundaries.\n\n**Days 31–60:** Strangler proxy routing, build new service with contract tests, dual-write/CDC data sync, deploy to production behind feature flag at 5% traffic.\n\n**Days 61–90:** Ramp to 100%, retire monolith path, postmortem retrospective, document playbook for service #2.\n\n**Prerequisites before day 1 extract:** Automated deploy, centralized logging, distributed tracing, on-call rotation.\n\n**Architect deliverables:** Bounded context map, context integration diagram, saga/outbox decision, team topology alignment (Conway's Law).",
        "Which service first? — Highest business value + clearest boundary — often notifications or catalog read path.",
        "Team structure? — Stream-aligned team owns extracted service before extraction completes.",
        "Extracting without observability baseline",
        "Big-bang rewrite in 90 days instead of strangler",
    ),
    q(
        "Strangler Fig Success Metrics",
        "Intermediate",
        "Migration",
        23,
        "What metrics prove a strangler fig migration is succeeding and ready for legacy retirement?",
        "Track traffic % on new path, error rate parity, p95 latency delta, data reconciliation drift, and monolith code deletion progress. Retire legacy only when all SLOs match for 2+ weeks at 100% traffic.",
        "**Migration dashboard:**\n| Metric | Target |\n|--------|--------|\n| Traffic on new service | → 100% |\n| Error rate vs monolith | ≤ monolith baseline |\n| p95 latency | ≤ monolith + 10% |\n| Data reconciliation | 0 drift rows |\n| Monolith LOC removed | Increasing weekly |\n\n**Data sync:** Nightly job compares monolith vs new service row counts and checksums — alert on mismatch.\n\n**Rollback criteria:** Error rate 2× baseline for 15 min → flip feature flag to 0%.\n\n**Architect:** Define retirement ceremony — delete routing rule, archive monolith module, update CMDB.",
        "Canary analysis? — Compare golden signals (errors, latency, throughput) between old and new during ramp.",
        "Business metrics? — Conversion rate parity — technical metrics aren't sufficient alone.",
        "Retiring legacy at 95% traffic with known edge cases",
        "No data reconciliation between old and new stores",
    ),
    q(
        "Scenario — Homepage Fan-Out",
        "Advanced",
        "Scenario",
        22,
        "The homepage calls 20 microservices synchronously and is slow. Redesign the architecture.",
        "Introduce BFF with aggregated endpoint, materialized read model, or GraphQL federation. Target ≤3 network calls from client; parallelize server-side fetches with bounded concurrency.",
        "**Current:** Mobile → 20 sequential HTTP calls → 3s page load.\n\n**Redesign options:**\n1. **BFF `/home` endpoint** — server parallelizes 20 fetches with `Task.WhenAll`, 200ms internal budget\n2. **Materialized view** — `HomepageProjection` updated by `ProductUpdated`, `PromoChanged` events — single DB read\n3. **Edge cache** — CDN caches `/home` JSON 60s for anonymous users\n4. **GraphQL** — single request, resolver batching (DataLoader)\n\n**Anti-patterns to eliminate:**\n- Sequential awaits in BFF\n- No timeout per downstream\n- Fetching full objects when IDs suffice\n\n**Architect:** CQRS read model is best for high-traffic homepage; BFF is faster to ship.",
        "GraphQL vs BFF REST? — GraphQL flexible for web; BFF REST simpler for mobile teams.",
        "Cache invalidation? — Event-driven purge on product/price change.",
        "BFF that sequentially calls 20 services",
        "No caching on read-heavy homepage",
    ),
    q(
        "Build vs Buy Framework",
        "Advanced",
        "Architecture Decision",
        24,
        "Present a framework for build vs buy decisions when adding capability to a microservices platform.",
        "Score on strategic differentiation, team capacity, TCO (3-year), time-to-market, and exit risk. Buy commodity (auth, email, payments); build core domain differentiators.",
        "**Decision matrix:**\n| Factor | Build | Buy |\n|--------|-------|-----|\n| Competitive advantage | Core domain | Commodity |\n| Team expertise | Strong | Weak |\n| Time to market | Months OK | Days matter |\n| Customization need | High | Standard fits |\n| Compliance | Full control needed | Vendor certified |\n\n**Examples:**\n- **Buy:** SendGrid (email), Stripe (payments), Auth0 (identity)\n- **Build:** Pricing engine, fraud rules, product catalog with domain logic\n\n**Platform middle ground:** Buy vendor, wrap in internal ACL + anti-corruption layer — swap vendor without domain pollution.\n\n**Architect:** Document ADR with 3-year TCO including integration maintenance, not just license fee.",
        "Open source vs SaaS? — OSS reduces license cost, increases ops burden — factor SRE headcount.",
        "When regret buy? — Vendor roadmap misaligns — ACL enables migration.",
        "Build everything — NIH syndrome",
        "Buy core domain logic — lose differentiation",
    ),
    q(
        "Event Ordering Guarantees",
        "Intermediate",
        "Messaging",
        21,
        "How do you guarantee event ordering per customer in a distributed event system?",
        "Partition messages by `customerId` — single consumer per partition preserves order. Use sequence numbers for cross-partition total order only when strictly required.",
        "**Kafka / Event Hubs:**\n```\nProducer: partition key = customerId\nConsumer: one consumer instance per partition\n→ Order of events for customer A is preserved\n```\n\n**When global order needed (rare):** Single partition (limits throughput) or sequence number with ordered processing buffer.\n\n**Out-of-order handling:** Consumers should be idempotent; use `sequenceNumber` to detect gaps and defer processing.\n\n**Cloud:** Azure Event Hubs with partition key; Service Bus sessions (`SessionId = customerId`) for ordered delivery.\n\n**Architect:** Order per aggregate, not per system — `orderId` partition for order events, `customerId` for customer profile events.",
        "FIFO queue vs partitioned log? — SQS FIFO limited throughput; partitioned log scales with partition count.",
        "Clock-based ordering? — Never sort events by `DateTime.UtcNow` from different producers.",
        "Global ordering requirement on all events — throughput bottleneck",
        "Multiple consumers on same partition — order broken",
    ),
    q(
        "Multi-Tenant — Silo vs Pool",
        "Advanced",
        "Architecture",
        24,
        "Compare silo and pool multi-tenancy models for microservices. When do you choose each?",
        "Pool: shared infrastructure, `tenantId` column — cost-efficient, ops simple. Silo: dedicated DB/compute per tenant — isolation for compliance and noisy-neighbor protection. Hybrid for enterprise tier.",
        "**Pool model:**\n- One deployment, shared DB with `tenantId` discriminator\n- Row-level security or application-level filter\n- Cost: $ per tenant low; risk: data leak if filter bug\n\n**Silo model:**\n- Dedicated database or schema per tenant\n- Dedicated App Service plan or namespace for large tenants\n- Cost: high; isolation: strong (SOC2, HIPAA)\n\n**Hybrid (common in SaaS):**\n| Tier | Model |\n|------|-------|\n| Free/Pro | Pool |\n| Enterprise | Silo |\n\n**Architect:** Tenant context middleware injects `tenantId` from JWT; integration tests verify cross-tenant isolation. Never trust client-supplied tenant ID without auth.",
        "Bridge model? — Shared app, separate DB per tenant — middle ground.",
        "Noisy neighbor? — Silo or rate limits per tenant in pool.",
        "Pool without row-level security tests",
        "Silo for all tenants — unsustainable unit economics",
    ),
    q(
        "Observability Maturity Model",
        "Intermediate",
        "Observability",
        21,
        "Describe observability maturity levels for a microservices platform. What should exist before scaling to 20+ services?",
        "Level 1: centralized logs. Level 2: metrics + dashboards per service. Level 3: distributed tracing with SLOs. Level 4: proactive alerting, runbooks, error budgets. Don't extract service 10 without Level 2 minimum.",
        "**Maturity stages:**\n| Level | Capabilities |\n|-------|-------------|\n| 0 | SSH and grep |\n| 1 | Structured logs → Log Analytics / ELK |\n| 2 | RED/USE metrics, service dashboards |\n| 3 | OpenTelemetry traces, correlation IDs |\n| 4 | SLOs, error budgets, synthetic monitoring |\n| 5 | AIOps anomaly detection, auto-remediation |\n\n**Before 20+ services:**\n- Every service exports logs, metrics, traces with `service.name`\n- Golden signals dashboard per service\n- On-call runbook linked in service catalog\n- Alert routing — not email to entire company\n\n**Architect:** Observability is not optional infrastructure — budget 10–15% of platform team capacity.",
        "RED vs USE? — RED (Rate, Errors, Duration) for services; USE (Utilization, Saturation, Errors) for resources.",
        "Cardinality explosion? — Avoid high-cardinality labels (userId) in metrics.",
        "Scaling services before centralized logging exists",
        "Alerts with no runbook — on-call pages with no action",
    ),
    q(
        "Team Topology for Microservices",
        "Intermediate",
        "Organization",
        23,
        "How does team topology align with microservices boundaries per Team Topologies?",
        "Stream-aligned teams own end-to-end business capabilities (one or few services). Platform team provides paved road. Enabling team coaches on DDD. Complexity team handles legacy ACL integrations.",
        "**Team Topologies mapping:**\n- **Stream-aligned** → Order team owns Order + Fulfillment services\n- **Platform** → Internal developer platform (templates, CI/CD, observability)\n- **Enabling** → Temporary DDD/event storming coaching\n- **Complicated-subsystem** → Legacy ERP ACL team\n\n**Conway's Law:** Architecture will mirror communication structure — design teams before drawing service boxes.\n\n**Anti-pattern:** Feature team touches 8 services — no ownership, no on-call accountability.\n\n**Architect:** Two-pizza team per stream; clear service catalog ownership in Backstage.",
        "One team per service? — Too granular — team owns a bounded context (1–3 services).",
        "Shared on-call rotation across all services? — Stream team owns their services' pages.",
        "Organizing by technology layer (all DB teams)",
        "No platform team — every stream reinvents CI/CD",
    ),
    q(
        "Platform Engineering for Microservices",
        "Intermediate",
        "Platform",
        22,
        "What should an Internal Developer Platform include for .NET microservices teams?",
        "Golden-path templates: .NET 8 API with health checks, OpenTelemetry, Polly resilience, EF migrations, GitHub Actions OIDC deploy, Bicep modules, and service catalog entry. Measure time-to-first-production-deploy.",
        "**IDP components:**\n1. **Templates** — `dotnet new microservice` scaffolds structure\n2. **Pipelines** — reusable workflow: build, test, contract verify, deploy to AKS/App Service\n3. **Observability** — App Insights wired, standard dashboards\n4. **Secrets** — Key Vault integration, no secrets in repo\n5. **Catalog** — Backstage with owner, runbook, SLO links\n\n**Metrics:** Time-to-first-deploy < 1 day; developer satisfaction survey; % services on golden path.\n\n**Architect:** Platform team owns the paved road; product teams can go off-road but assume ops burden. Encode security defaults (Managed Identity, mTLS option).",
        "Platform vs enablement? — Platform builds tools; enablement team coaches adoption temporarily.",
        "Build vs buy IDP? — Backstage + custom templates is common; avoid over-building K8s abstractions early.",
        "Platform team approving every deploy — bottleneck",
        "Golden path so rigid teams can't ship",
    ),
    q(
        "Data Consistency Patterns",
        "Advanced",
        "Data",
        24,
        "Compare strong consistency, eventual consistency, and read-your-writes patterns across microservices.",
        "Strong consistency within one service/aggregate (ACID). Eventual consistency across services via sagas and events. Read-your-writes via session affinity, version tokens, or synchronous read-after-write to owning service.",
        "**Pattern selection:**\n| Use case | Pattern |\n|----------|--------|\n| Payment debit | Strong (single service TX) |\n| Product catalog | Eventual (minutes OK) |\n| User sees own order after submit | Read-your-writes |\n| Cross-service balance | Saga + eventual |\n\n**Read-your-writes techniques:**\n- Route read to primary replica\n- Return entity version in write response; client sends `If-None-Match`\n- Short TTL cache keyed by user session\n- Sticky sessions (fragile — prefer version token)\n\n**Architect:** Document consistency level per integration in context map — interviewers want business-aware trade-offs, not \"always strong.\"",
        "CAP during partition? — Choose availability with eventual consistency for catalog; CP for ledger.",
        "CRDTs? — Conflict-free types for collaborative editing — niche in microservices.",
        "Strong consistency required everywhere — kills availability",
        "Eventual consistency without UX strategy for stale reads",
    ),
    q(
        "Service Discovery",
        "Intermediate",
        "Infrastructure",
        21,
        "How does service discovery work in Kubernetes vs traditional VM deployments?",
        "K8s: DNS (`order-service.namespace.svc.cluster.local`) + kube-proxy load balances to healthy pods. VMs: consul/etcd registry or load balancer with health-checked backend pool. Client-side vs server-side discovery trade-offs.",
        "**Kubernetes (server-side):**\n- Service resource → ClusterIP → kube-proxy routes to ready endpoints\n- Readiness probe controls endpoint list\n- No client-side registry needed for internal calls\n\n**VM / hybrid:**\n- **Client-side:** Service queries Consul → gets instance list → load balances (Ribbon pattern)\n- **Server-side:** ALB/App Gateway → static or dynamic backend pool\n\n**.NET in K8s:**\n```csharp\n// HttpClient factory with K8s DNS\nservices.AddHttpClient(\"OrderService\")\n    .ConfigureHttpClient(c => c.BaseAddress = new Uri(\"http://order-service:8080/\"));\n```\n\n**Architect:** Prefer platform-native discovery (K8s DNS) over custom registry unless multi-cluster or multi-cloud mesh required.",
        "Headless service? — DNS returns pod IPs directly — for StatefulSets.",
        "Service mesh discovery? — Sidecar intercepts — transparent to app.",
        "Hardcoded IP addresses in service config",
        "Discovery without health check integration — routes to dead instances",
    ),
    q(
        "Configuration Drift",
        "Intermediate",
        "Operations",
        23,
        "How do you detect and prevent configuration drift across 15 microservice environments?",
        "GitOps for desired state, automated drift detection, immutable infrastructure, and config validation at deploy. Alert when runtime config differs from declared manifest.",
        "**Drift sources:** Manual kubectl edit, portal hotfix, secret rotated without repo update, feature flag changed without ticket.\n\n**Prevention:**\n1. **GitOps** — Argo CD / Flux reconciles cluster to Git manifest\n2. **IaC** — Bicep/Terraform for Azure resources; PR review for changes\n3. **App config** — Azure App Configuration with audit log\n4. **Immutable deploys** — new image + config bundle, not SSH patch\n\n**Detection:**\n- Argo CD `OutOfSync` alert\n- Nightly config diff job: running vs Git\n- Policy-as-code (OPA/Kyverno) rejects non-compliant deploys\n\n**Architect:** Drift is a security risk — unauthorized config change = incident.",
        "Config vs secret drift? — Secrets rotate more often — automate sync from Key Vault.",
        "Emergency break-glass? — Allow manual change with mandatory post-incident Git reconcile.",
        "Production config changed only in portal — Git stale",
        "No audit trail on configuration changes",
    ),
    q(
        "Zero-Downtime Deployment",
        "Intermediate",
        "Operations",
        22,
        "What deployment strategies enable zero-downtime releases for stateful .NET microservices?",
        "Rolling update with readiness probes, blue/green for instant cutover, canary for risk reduction. Schema changes use expand-contract. Drain connections on shutdown.",
        "**Strategies:**\n| Strategy | Downtime | Risk | Use when |\n|----------|----------|------|----------|\n| Rolling | None* | Medium | Default K8s |\n| Blue/green | None | Low | DB migration cutover |\n| Canary | None | Lowest | High-risk payment change |\n\n**Rolling deploy requirements:**\n- `preStop` hook drains in-flight requests (30s grace)\n- Readiness only true when warmed up\n- Backward-compatible API during roll\n\n**Stateful concerns:**\n- EF migrations run as init container or job before new pods serve traffic\n- Message consumers: cooperative rebalance — finish in-flight before partition move\n\n**Feature flags:** Dark deploy new logic; enable after pods healthy.\n\n**Architect:** Define max unavailable (1) and max surge (1) for critical services.",
        "Database migration job ordering? — Migrate schema → deploy new code reading new column — never reverse.",
        "IIS vs K8s? — App Service deployment slots = blue/green for PaaS.",
        "Breaking schema + code in same release",
        "No connection draining — in-flight requests killed on pod terminate",
    ),
    q(
        "Capstone Review — Month 6 Readiness",
        "Advanced",
        "Capstone",
        24,
        "What should a Month 6 microservices capstone demonstrate to prove architect readiness?",
        "Bounded context map, saga/outbox diagram for one workflow, 4+ weeks study ≥70%, independent deploy of 2+ services, observability dashboard, and ability to whiteboard strangler migration for legacy system.",
        "**Capstone checklist:**\n- [ ] Context map with 4+ bounded contexts and integration patterns\n- [ ] One saga (orchestrated or choreographed) with compensation documented\n- [ ] Outbox or inbox pattern implemented in code or detailed design\n- [ ] Contract test between two services\n- [ ] Distributed trace screenshot for multi-hop request\n- [ ] ADR for one significant decision (DB choice, sync vs async)\n- [ ] Verbal 2-minute microservices pitch with trade-offs\n\n**Rubric:** Can explain when NOT to use microservices. Can design flash-sale inventory without oversell. Can contain cascading failure scenario.\n\n**Architect:** Capstone is communication proof — diagrams + spoken defense, not just code.",
        "Portfolio structure? — 3 ADRs, 1 context map, 1 sequence diagram, 1 postmortem writeup.",
        "Mock interview? — 45-min system design: decompose e-commerce monolith.",
        "Capstone that's only slides without trade-off discussion",
        "Cannot articulate downsides of microservices",
    ),
    q(
        "Production Readiness Checklist",
        "Advanced",
        "Operations",
        24,
        "What belongs on a production readiness review before launching a new microservice?",
        "SLOs defined, runbook written, on-call rotation assigned, load tested at 2× expected peak, security review (auth, secrets, OWASP), backup/restore tested, rollback verified, and dashboards/alerts configured.",
        "**Production readiness gates:**\n| Area | Requirement |\n|------|-------------|\n| Reliability | SLO, error budget, load test report |\n| Observability | Logs, metrics, traces, dashboards |\n| Security | Threat model, pen test or scan, secrets in Key Vault |\n| Operations | Runbook, on-call, escalation path |\n| Data | Backup RPO/RTO tested, migration plan |\n| Resilience | Timeouts, circuit breakers, bulkheads configured |\n| Compliance | PII handling, audit log, retention policy |\n\n**Go/no-go meeting:** Service owner presents; platform SRE signs off.\n\n**Architect:** PRR is not bureaucracy — it's how you avoid being paged on launch night for missing health checks.",
        "SRE engagement when? — At design phase, not week before launch.",
        "Progressive rollout? — 1% → 10% → 50% → 100% with metric gates.",
        "Launch without load test",
        "No rollback tested — forward-only deploy hope",
    ),
    q(
        "Graduation Scenarios — Architect Interview",
        "Advanced",
        "Capstone",
        24,
        "Deliver a 2-minute architect pitch: why microservices, when to avoid them, and your top three lessons from this program.",
        "Microservices trade organizational autonomy and independent deploy for operational complexity. Use when team scale, deployment pain, and domain clarity justify the cost. Avoid for small teams, unclear boundaries, or immature DevOps. Top lessons: start modular monolith, invest in observability first, database-per-service is non-negotiable.",
        "**2-minute pitch structure:**\n1. **Why:** Autonomous teams, scale independent components, technology fit per context (15 sec)\n2. **When not:** <10 engineers, shared unclear domain, no CI/CD — modular monolith first (20 sec)\n3. **Lessons:**\n   - Observability before service #5\n   - Sagas/outbox over distributed 2PC\n   - Conway's Law — align teams to contexts (30 sec)\n4. **Trade-off close:** \"I choose microservices when deployment coupling hurts business velocity more than ops overhead hurts reliability\" (15 sec)\n\n**Graduation scenarios to practice:**\n- Board asks why not stay on monolith — quantify deploy frequency and incident blast radius\n- CTO wants 50 services in 6 months — push back with team topology and ops capacity\n- Production double-charge incident — walk through idempotency fix calmly\n\n**Architect:** Graduation is demonstrating judgment under ambiguity — not pattern name-dropping.",
        "Favorite pattern? — Pick one with war story — outbox after production dual-write incident.",
        "What's next after graduation? — Platform engineering, multi-region, or AI service mesh — tie to career goal.",
        "Pitch that's only benefits — no trade-offs",
        "Cannot whiteboard a saga compensation flow",
    ),
]
