"""Hand-crafted premium Q031–Q070 for Week 1 intermediate — C# / ASP.NET Core."""

from premium_qa_data import q

WEEK1_INTERMEDIATE_Q031_Q070 = [
    q("Interface vs Abstract Class", "C# OOP", "Very Common",
      "When choose interface over abstract class in enterprise .NET?",
      "Interface: multiple inheritance, behavior contract without implementation. Abstract class: shared base state/implementation, single inheritance.",
      "**Interface:** `IPaymentGateway`, `IRepository<T>` — swap implementations, test doubles, plugin architecture.\n\n**Abstract class:** shared template method, common fields, protected helpers — `EntityBase` with Id and audit.\n\n**Architect rule:** Default to interface for DI dependencies; abstract class when genuine shared implementation exists — not as a dumping ground for duplicate code.\n\n```csharp\npublic interface IOrderNotifier { Task NotifyAsync(Order order); }\npublic abstract class EntityBase { public Guid Id { get; protected set; } }\n```",
      "Contract design drives testability and team boundaries.",
      "Default interface methods C# 8? — Use sparingly — breaks binary compatibility if changed.",
      "Sealed abstract class? — Prevent further inheritance when hierarchy complete.",
      "Abstract class for every service",
      "Fat interface with 15 unrelated methods",
      "Interface on concrete class already — redundant abstraction"),
    q("Composition over Inheritance", "Design Principles", "Very Common",
      "Explain composition over inheritance with ASP.NET Core example.",
      "Favor has-a over is-a — inject behaviors (`IValidator`, `ICache`) instead of deep inheritance trees.",
      "**Bad:** `PremiumOrderService : BaseOrderService : OrderService` — fragile base class, hidden coupling.\n\n**Good:**\n```csharp\npublic class OrderService(IValidator<Order> validator, IOrderRepository repo, IEventPublisher events)\n```\n\n**Architect:** Decorator pattern (`CachingOrderRepository` wraps `OrderRepository`) over subclassing. Inheritance for true subtype polymorphism only — domain entities, strategy hierarchies with shared algorithm skeleton.",
      "Composition aligns with DI and microservice boundaries.",
      "When is inheritance OK? — Framework hooks (Controller base), domain taxonomy with invariants.",
      "Mixin via extension methods vs inheritance? — Extensions for stateless helpers only.",
      "Five-level service inheritance chain",
      "Override base method breaks LSP silently",
      "Composition replaced by service locator"),
    q("DI Lifetimes — Singleton, Scoped, Transient", "DI", "Very Common",
      "Explain singleton, scoped, and transient lifetimes. Common pitfalls?",
      "Singleton: one per app — config, caches. Scoped: one per request — DbContext, user context. Transient: new each resolve — lightweight stateless services.",
      "**Captive dependency:** Singleton holding Scoped service — stale DbContext, memory leak, wrong tenant data.\n\n```csharp\n// WRONG: singleton injecting scoped DbContext\nservices.AddSingleton<BadService>(); // if ctor takes DbContext\n```\n\n**Architect:** Lifetime validation at startup (`ValidateOnBuild`). Document lifetime rules in platform template. BackgroundService gets its own scope per iteration.",
      "Lifetime bugs are subtle production data-corruption causes.",
      "DbContext singleton? — Never — always scoped or factory per operation.",
      "IServiceScopeFactory in singleton? — Create scope manually for background work.",
      "Singleton captures scoped DbContext",
      "Transient DbContext per call — connection storm",
      "No ValidateOnBuild in production templates"),
    q("Options Pattern — IOptions", "Configuration", "Very Common",
      "How use IOptions, IOptionsSnapshot, and IOptionsMonitor?",
      "`IOptions<T>`: singleton, bound at startup — immutable. `IOptionsSnapshot<T>`: scoped, reloads per request. `IOptionsMonitor<T>`: singleton with change callbacks — hot reload.",
      "```csharp\nservices.Configure<PaymentOptions>(config.GetSection(\"Payment\"));\npublic class PaymentService(IOptions<PaymentOptions> opts) { }\n```\n\n**Architect:** Strongly typed options classes with validation (`IValidateOptions<T>`, DataAnnotations). Never inject `IConfiguration` into business services — hides config surface.\n\n**Secrets:** bind from Key Vault; options class holds structure, not raw secrets in appsettings.json.",
      "Options pattern is the config contract for services.",
      "Named options? — Multiple registrations same type — `IOptionsSnapshot<AuthOptions>` with name.",
      "PostConfigure? — Layer defaults then environment overrides.",
      "IConfiguration injected everywhere",
      "IOptions for values that change per request without Snapshot",
      "No validation on critical options at startup"),
    q("Hosted Services and BackgroundService", "ASP.NET Core", "Common",
      "When use BackgroundService vs Hangfire/queue for background work?",
      "BackgroundService: in-process, host-lifetime tied, simple periodic or long-running tasks. Queue/Hangfire: durable, retriable, scale-out workers.",
      "```csharp\npublic class OutboxProcessor(IServiceScopeFactory scopeFactory) : BackgroundService\n{\n    protected override async Task ExecuteAsync(CancellationToken ct)\n    {\n        while (!ct.IsCancellationRequested)\n        {\n            using var scope = scopeFactory.CreateScope();\n            // process outbox\n            await Task.Delay(TimeSpan.FromSeconds(5), ct);\n        }\n    }\n}\n```\n\n**Architect:** BackgroundService for lightweight polling (outbox drain). Never heavy job processing on web tier — use dedicated worker + queue. Honor `IHostApplicationLifetime` shutdown token.",
      "Background work placement affects reliability and scale.",
      "IHostedService vs BackgroundService? — BackgroundService abstracts ExecuteAsync loop.",
      "Graceful shutdown timeout? — Configure `HostOptions.ShutdownTimeout`.",
      "Long CPU work on web pod BackgroundService",
      "No scope in background loop — captive DbContext",
      "Ignore cancellation on shutdown"),
    q("Middleware Pipeline Ordering", "ASP.NET Core", "Very Common",
      "Why does middleware order matter? Show critical ordering rules.",
      "Middleware runs as onion — first registered runs first on request, last on response. Wrong order breaks auth, routing, exception handling.",
      "**Correct order (simplified):**\n1. Exception handler (early)\n2. HTTPS redirection\n3. Static files\n4. Routing\n5. CORS (before auth if needed)\n6. Authentication\n7. Authorization\n8. Endpoints\n\n**Architect:** Document standard pipeline in platform template. `UseAuthentication` before `UseAuthorization`. Endpoint middleware after routing.",
      "Pipeline order bugs manifest as 401 on valid tokens or CORS failures.",
      "Terminal middleware? — Short-circuits pipeline — no next() call.",
      "Branching pipeline MapWhen? — Path-specific middleware — order still matters per branch.",
      "CORS after authorization",
      "Exception handler after endpoints",
      "Custom middleware before routing reads route data"),
    q("Action Filters vs Middleware", "ASP.NET Core", "Common",
      "When use action filters vs middleware?",
      "Middleware: all requests, transport-level, no MVC knowledge. Action filters: MVC pipeline, per-controller/action, model binding aware.",
      "**Middleware:** correlation ID, global exception wrapper, request logging.\n\n**Action filters:** `[Authorize]`-style custom rules, model validation short-circuit, per-action timing, audit logging with action name.\n\n**Architect:** Cross-cutting HTTP concerns → middleware. MVC-specific behavior (action arguments, IActionResult) → filters. Avoid duplicate logic in both.",
      "Right layer reduces coupling to MVC.",
      "IAsyncActionFilter vs middleware perf? — Filters skip non-MVC endpoints — minimal APIs need middleware or endpoint filters.",
      "Endpoint filters .NET 7+? — Minimal API equivalent of action filters.",
      "Duplicate auth in middleware and filter",
      "Action filter for static file requests",
      "Middleware tries to read action parameters"),
    q("Minimal APIs vs Controllers", "ASP.NET Core", "Common",
      "When choose Minimal APIs over controllers?",
      "Minimal APIs: small microservices, simple CRUD, low ceremony. Controllers: complex routing, filters, versioning, large teams needing convention.",
      "**Minimal API strengths:**\n```csharp\napp.MapGet(\"/orders/{id}\", async (Guid id, IOrderService svc) =>\n    await svc.GetAsync(id));\n```\n\n**Controller strengths:** `[ApiController]` automatic 400, filter ecosystem, clear folder structure for 200+ endpoints.\n\n**Architect:** Microservice with 10 endpoints → Minimal API. Bounded context with rich validation, versioning, multiple content types → Controllers. Can mix in same app.",
      "API style is team-scale and complexity decision.",
      "Minimal API validation? — `AddEndpointsApiExplorer`, FluentValidation filter, or `Results.ValidationProblem`.",
      "OpenAPI both styles? — Swashbuckle supports both — same doc standard.",
      "Controllers for 5-endpoint internal tool",
      "Minimal APIs without versioning plan at 50 endpoints",
      "No separation — business logic inline in MapGet lambdas"),
    q("IHttpClientFactory Rationale", "HTTP", "Very Common",
      "Why architect mandates IHttpClientFactory over new HttpClient()?",
      "Factory manages `HttpMessageHandler` lifetime — prevents socket exhaustion and stale DNS from misused HttpClient patterns.",
      "**Problems solved:**\n- `new HttpClient()` per request → socket port exhaustion\n- Singleton HttpClient → DNS never refreshes\n\n```csharp\nservices.AddHttpClient<IInventoryClient, InventoryClient>(c =>\n{\n    c.BaseAddress = new Uri(config[\"Inventory:BaseUrl\"]);\n    c.Timeout = TimeSpan.FromSeconds(30);\n});\n```\n\n**Architect:** Typed clients as standard. Centralize Polly handlers, default headers, resilience. Ban raw `new HttpClient()` via analyzer.",
      "HttpClient misuse causes classic scale outages.",
      "SocketsHttpHandler.PooledConnectionLifetime? — Rotate connections — default 2 min in factory.",
      "DelegatingHandler chain? — Auth token injection, correlation ID propagation.",
      "new HttpClient() in repository",
      "Singleton HttpClient for all outbound calls forever",
      "No timeout configured on outbound clients"),
    q("Polly Resilience Policies", "Resilience", "Common",
      "Design resilience pipeline for external payment API calls.",
      "Combine retry (transient failures), circuit breaker (cascade prevention), timeout (bounded wait), optional bulkhead (concurrency limit).",
      "**Order matters:** timeout wraps retry or vice versa — document team standard.\n\n```csharp\nservices.AddHttpClient<IPaymentGateway>()\n    .AddStandardResilienceHandler(); // .NET 8+\n```\n\n**Architect:** Retry only idempotent ops or with idempotency keys. Circuit breaker open → fail fast, shed load. Per-dependency policies — not one global retry for everything. Log breaker state changes.",
      "Resilience policies are dependency contracts.",
      "Jitter on retry? — Prevents thundering herd when dependency recovers.",
      "Hedging vs retry? — Parallel duplicate requests — rare, costly — architect approval.",
      "Infinite retry on POST without idempotency key",
      "Circuit breaker never configured half-open",
      "Same 5 retries for read and write endpoints"),
    q("Structured Logging with Serilog", "Observability", "Very Common",
      "Serilog structured logging standards for ASP.NET Core microservices?",
      "Message templates with named properties — `{OrderId}` not string interpolation — enables query and alerting.",
      "```csharp\nLog.Information(\"Order {OrderId} shipped to {Region}\", order.Id, region);\n// NOT: Log.Information($\"Order {order.Id} shipped\");\n```\n\n**Architect mandates:** JSON to stdout in containers, `CorrelationId` enricher from middleware, log level overrides per namespace, PII redaction destructuring. Sinks: Console (K8s), Application Insights, Seq dev.\n\n**Request logging:** `UseSerilogRequestLogging` with level based on status code.",
      "Structured logs are searchable production signals.",
      "LogContext.PushProperty? — Scope OrderId for entire request handler.",
      "Serilog.Exceptions? — Structured exception details without stack string concat.",
      "String interpolation in log messages",
      "Debug logging enabled in production always",
      "Logging credit card numbers or JWT tokens"),
    q("Health Checks — Liveness vs Readiness", "ASP.NET Core", "Very Common",
      "Difference between liveness and readiness probes in ASP.NET Core?",
      "Liveness: is process alive? — fail → restart pod. Readiness: can accept traffic? — fail → remove from load balancer.",
      "```csharp\nservices.AddHealthChecks()\n    .AddCheck(\"self\", () => HealthCheckResult.Healthy())\n    .AddSqlServer(connString, name: \"sql\")\n    .AddRedis(redisConn);\n\napp.MapHealthChecks(\"/health/live\", new() { Predicate = _ => false }); // or dedicated\napp.MapHealthChecks(\"/health/ready\", new() { Predicate = check => check.Tags.Contains(\"ready\") });\n```\n\n**Architect:** Liveness lightweight — don't check SQL (restart loop risk). Readiness checks DB, Redis, downstream dependency. Tag checks appropriately.",
      "Probe design prevents cascading restarts and bad traffic routing.",
      "Startup probe? — Slow-starting apps — K8s waits before liveness kills.",
      "Health check UI package? — Dev only — never expose detailed deps publicly.",
      "SQL check on liveness — DB blip restarts all pods",
      "Readiness always healthy — traffic to broken instances",
      "Detailed health JSON public in production"),
    q("API Versioning Strategies", "API Design", "Common",
      "Compare URL, header, and query string API versioning.",
      "URL (`/v2/orders`): explicit, cache-friendly, visible. Header (`Api-Version`): clean URLs, harder to test in browser. Query (`?api-version=2.0`): easy override, messy caching.",
      "**Architect recommendation:** URL path or header with `Asp.Versioning` package — deprecate with sunset headers.\n\n```csharp\nservices.AddApiVersioning(o => o.DefaultApiVersion = new(1, 0));\n```\n\n**Policy:** Support N and N-1 versions. Document breaking vs additive changes. OpenAPI one doc per version or aggregated.",
      "Versioning strategy affects clients, gateways, and caching.",
      "Media type versioning? — `application/vnd.company.orders.v2+json` — content negotiation coupling.",
      "Version in route constraint? — `MapToApiVersion` on minimal APIs and controllers.",
      "Breaking change without version bump",
      "Three versioning schemes mixed in one API",
      "No deprecation timeline communicated to consumers"),
    q("Problem Details — RFC 7807", "API Design", "Common",
      "How implement RFC 7807 Problem Details in ASP.NET Core?",
      "`ProblemDetails` standard error body: `type`, `title`, `status`, `detail`, `instance` — machine-readable, consistent across services.",
      "```csharp\nservices.AddProblemDetails();\n// or custom\nreturn Results.Problem(\n    title: \"Order not found\",\n    statusCode: StatusCodes.Status404NotFound,\n    type: \"https://api.example.com/errors/order-not-found\",\n    detail: $\"Order {id} does not exist.\");\n```\n\n**Architect:** Global exception handler maps domain exceptions to ProblemDetails. Stable `type` URIs per error code — not stack traces in `detail`. Extensions for `traceId`, `errors` validation array.",
      "Consistent errors reduce client integration cost.",
      "ValidationProblemDetails? — 400 with field-level errors array.",
      "ProblemDetails in non-API contexts? — gRPC status, SignalR hub errors — parallel standards.",
      "Stack trace in detail field production",
      "Different error shape per endpoint",
      "Generic 500 with no correlation id"),
    q("FluentValidation Integration", "Validation", "Common",
      "Integrate FluentValidation in ASP.NET Core pipeline?",
      "Register validators from assembly; auto-validate on model binding via filter or `AddFluentValidationAutoValidation`.",
      "```csharp\nservices.AddValidatorsFromAssemblyContaining<CreateOrderValidator>();\n\npublic class CreateOrderValidator : AbstractValidator<CreateOrderCommand>\n{\n    public CreateOrderValidator() {\n        RuleFor(x => x.Email).EmailAddress();\n        RuleFor(x => x.Lines).NotEmpty();\n    }\n}\n```\n\n**Architect:** Validators for commands/DTOs — not entities with DB calls (use async validator sparingly). Separate from domain invariants — FluentValidation at boundary, domain rules inside aggregate.",
      "Validation layer placement is architectural boundary.",
      "Async validation RuleForAsync? — DB uniqueness check — acceptable at API boundary.",
      "MediatR ValidationBehavior? — Pipeline validates before handler — clean CQRS.",
      "Validation logic duplicated in controller and domain",
      "Heavy DB calls in every RuleFor",
      "No localization on validation messages"),
    q("DTO Mapping — Mapster vs AutoMapper", "Mapping", "Common",
      "When choose Mapster over AutoMapper in .NET projects?",
      "AutoMapper: convention-based, mature, runtime mapping. Mapster: compile-time code gen, faster, less magic.",
      "**AutoMapper:** `CreateMap<Order, OrderDto>()` — profile classes, team knows it.\n\n**Mapster:** `[Adapt]` or `TypeAdapterConfig` — source generator option, zero runtime reflection on hot paths.\n\n**Architect:** Pick one per org — document in template. Mapster for performance-critical high-RPS read models. AutoMapper for large legacy migration. Never manual mapping in 50 places when codegen works.",
      "Mapping tool choice affects build time and runtime perf.",
      "Projection EF + Mapster? — `ProjectToType<OrderDto>()` — SQL-level select.",
      "Manual mapping when? — Complex domain transforms with business rules — not property copy.",
      "Both AutoMapper and Mapster in same solution",
      "Mapping in controller action bodies",
      "Ignore null propagation bugs on nested DTOs"),
    q("EF Core Tracking vs AsNoTracking", "EF Core", "Very Common",
      "When use AsNoTracking in EF Core queries?",
      "AsNoTracking: read-only queries — no change tracker overhead, lower memory. Tracking: default for updates.",
      "```csharp\nvar orders = await db.Orders.AsNoTracking()\n    .Where(o => o.CustomerId == id)\n    .ToListAsync();\n```\n\n**Architect:** All list/search/report endpoints → AsNoTracking by default. Global `NoTracking` with explicit `AsTracking()` for writes. Mis-tracked graphs cause stale data and surprise `SaveChanges` updates.",
      "Tracking defaults drive API performance and correctness.",
      "AsNoTrackingWithIdentityResolution? — Deduplicate included entities in graph read.",
      "ProjectTo vs AsNoTracking? — DTO projection avoids entity materialization entirely.",
      "AsNoTracking then attach and update — subtle bugs",
      "Tracking on read-heavy report returning 10K rows",
      "NoTracking on entity you then modify and save"),
    q("EF Core Zero-Downtime Migrations", "EF Core", "Common",
      "Strategies for zero-downtime EF Core schema migrations?",
      "Expand-contract pattern: additive changes first, deploy code reading both, backfill, remove old — never destructive column drop in single deploy.",
      "**Safe:** add nullable column → deploy app writing new column → backfill → make NOT NULL → remove old.\n\n**Risky:** rename column, drop column, change type — require multi-phase.\n\n**Architect:** Migrations in CI reviewed like code. `dotnet ef migrations script` for DBA review. Feature flags gate code paths using new schema. Consider separate migration runner job, not app startup `Migrate()` in multi-instance.",
      "Schema changes are deployment architecture decisions.",
      "Idempotent SQL scripts? — Flyway-style vs EF migrations — pick team standard.",
      "Online index creation? — SQL Server `ONLINE=ON` for large tables.",
      "Drop column same release as code stops reading it",
      "Database.Migrate() on every pod startup race",
      "Breaking rename in single migration"),
    q("Specification Pattern", "DDD", "Common",
      "Implement specification pattern for repository queries?",
      "Encapsulate query criteria as composable `ISpecification<T>` objects — reusable, testable, keeps LINQ out of handlers.",
      "```csharp\npublic class ActiveOrdersSpec : Specification<Order>\n{\n    public ActiveOrdersSpec(Guid customerId) =>\n        Query.Where(o => o.CustomerId == customerId && o.Status == OrderStatus.Active);\n}\n// Compose: activeSpec.And(new DateRangeSpec(from, to))\n```\n\n**Architect:** Specifications in domain or application layer — repository accepts `ISpecification<T>`. Avoid specification explosion — group common specs. Works with Ardalis.Specification library.",
      "Query logic reuse without repository god methods.",
      "Specification vs inline LINQ? — Inline OK for one-off; spec when reused or complex.",
      "Include expressions in spec? — `Query.Include(o => o.Lines)` centralized.",
      "GetOrdersByCustomerAndStatusAndDate repository method proliferation",
      "Specification with IQueryable leaked to API layer",
      "Untestable 200-line LINQ in handler"),
    q("MediatR CQRS Introduction", "Architecture", "Very Common",
      "Introduce MediatR CQRS in ASP.NET Core service — architect view?",
      "Commands mutate, queries read — handlers isolated, controllers thin, cross-cutting via pipeline behaviors.",
      "```csharp\npublic record CreateOrderCommand(string CustomerId) : IRequest<OrderId>;\n\npublic class CreateOrderHandler : IRequestHandler<CreateOrderCommand, OrderId>\n{\n    public async Task<OrderId> Handle(CreateOrderCommand cmd, CancellationToken ct) { ... }\n}\n```\n\n**Architect:** One handler per use case — clear boundaries. Pipeline behaviors: validation, logging, transactions. Don't MediatR for every CRUD if team is 2 people — ceremony cost. Great at 20+ use cases per bounded context.",
      "CQRS scales team parallelism on features.",
      "IRequest vs INotification? — Commands return value; notifications publish to multiple handlers.",
      "Query side read models? — Separate handlers hitting optimized views — full CQRS split.",
      "MediatR for simple pass-through CRUD only",
      "Handler calls handler via MediatR recursively",
      "God IRequestHandler with switch on request type"),
    q("Repository Pattern — When to Use", "Architecture", "Common",
      "When is repository pattern justified over DbContext directly?",
      "Justified: domain-centric persistence abstraction, swap storage, test without EF. Overkill: thin CRUD wrapping every DbSet call.",
      "**Use when:** aggregate roots with persistence ignorance, multiple data sources, strict unit test boundaries.\n\n**Skip when:** simple API with EF — `DbContext` is already unit of work; extra `IRepository<Order>` adds no value.\n\n**Architect:** `IOrderRepository` with domain meaningful methods (`GetByCustomerWithLines`) — not `GetAll`, `GetById`, `Delete` generics on everything.",
      "Repository is abstraction cost — apply where it earns value.",
      "Generic IRepository<T>? — Often leaky — encourages anemic queries.",
      "Specification + repository? — Repository accepts spec — clean query composition.",
      "Repository per entity table — 40 interfaces",
      "Repository re-exposes IQueryable to callers",
      "Mock repository integration test replaces real DB unnecessarily"),
    q("Unit of Work Pattern", "Architecture", "Common",
      "Unit of Work pattern with EF Core — still relevant?",
      "DbContext already implements UoW — `SaveChanges` commits unit. Explicit `IUnitOfWork` wraps context when multiple repositories share one transaction.",
      "```csharp\npublic interface IUnitOfWork { Task<int> SaveChangesAsync(CancellationToken ct); }\n// Implementation holds DbContext\n```\n\n**Architect:** Single `SaveChanges` per request in MediatR transaction behavior. Multi-DbContext scenarios need `TransactionScope` or explicit database transaction. Don't nest multiple SaveChanges without reason.",
      "Transaction boundary clarity prevents partial commits.",
      "Ambient transactions TransactionScope? — Cross-database — distributed — avoid if possible.",
      "MediatR TransactionBehavior? — One UoW commit per command pipeline.",
      "SaveChanges after every repository method call",
      "Multiple DbContexts without distributed transaction plan",
      "Unit of Work interface with 20 unrelated repos"),
    q("Domain Events in .NET", "DDD", "Common",
      "Raise and dispatch domain events in .NET cleanly?",
      "Entities collect events; dispatch after successful persistence — decouple side effects from aggregate logic.",
      "```csharp\npublic class Order : Entity\n{\n    public void Ship() { Status = Shipped; AddDomainEvent(new OrderShippedEvent(Id)); }\n}\n// Dispatch in SaveChanges interceptor or MediatR after SaveChanges\n```\n\n**Architect:** In-process MediatR `INotification` for same bounded context. Outbox pattern for cross-service — never dual-write DB + message bus. Handlers idempotent.",
      "Domain events enable loose coupling within and across services.",
      "Event vs integration event? — Domain internal; integration crosses boundary with schema contract.",
      "Dispatch before SaveChanges? — Side effects on uncommitted data — dangerous.",
      "Publish to Kafka inside entity method",
      "Non-idempotent event handler on retry",
      "Domain event storm — 50 events per SaveChanges"),
    q("Background Jobs — Hangfire vs Queue", "Architecture", "Common",
      "Hangfire vs Azure Service Bus / RabbitMQ for background jobs?",
      "Hangfire: in-process/SQL-backed scheduler — dashboards, cron, fire-and-forget in same app. Queue: durable async messaging — scale workers independently.",
      "**Hangfire when:** internal ops jobs, retry UI, team already on SQL, moderate volume.\n\n**Queue when:** high throughput, microservice workers, cloud-native scale, poison message handling.\n\n**Architect:** Never Hangfire on web tier at scale — dedicated worker role. Queue + outbox for transactional consistency. Hangfire SQL storage becomes bottleneck.",
      "Job infrastructure is reliability and scale decision.",
      "Hangfire recurring jobs vs IHostedService cron? — Hangfire gives dashboard and persistence.",
      "Idempotency keys on queue consumers? — Mandatory for at-least-once delivery.",
      "Hangfire on every API instance processing same jobs",
      "Fire-and-forget Task.Run for critical payments",
      "No dead-letter queue monitoring"),
    q("IMemoryCache vs Distributed Redis Cache", "Caching", "Very Common",
      "When IMemoryCache vs distributed Redis cache?",
      "IMemoryCache: per-instance, fastest, not shared — good for reference data, config snapshots. Redis: shared across instances, session, rate limit counters.",
      "```csharp\nservices.AddMemoryCache();\nservices.AddStackExchangeRedisCache(o => o.Configuration = redisConn);\n```\n\n**Architect:** Memory cache for read-heavy static catalog with short TTL + Redis pub/sub invalidation optional. Redis for user session, shopping cart, distributed locks. Always set size limits and eviction on MemoryCache.",
      "Cache tier choice affects consistency across scaled pods.",
      "Cache-aside vs read-through? — Document pattern per use case.",
      "IDistributedCache serialization? — JSON overhead — consider MessagePack for large objects.",
      "IMemoryCache for user-specific cart in K8s 10 replicas",
      "Unbounded MemoryCache — OOM kill",
      "Cache without TTL on mutable data"),
    q("ASP.NET Core Rate Limiting", "Security", "Common",
      "Implement rate limiting in ASP.NET Core 7+?",
      "Built-in `Microsoft.AspNetCore.RateLimiting` — fixed window, sliding window, token bucket, concurrency limiter.",
      "```csharp\nbuilder.Services.AddRateLimiter(o => o.AddFixedWindowLimiter(\"api\", opt =>\n{\n    opt.PermitLimit = 100;\n    opt.Window = TimeSpan.FromMinutes(1);\n}));\napp.UseRateLimiter();\napp.MapGet(\"/orders\", ...).RequireRateLimiting(\"api\");\n```\n\n**Architect:** Per-IP for anonymous, per-API-key or per-user for authenticated. Return 429 with `Retry-After`. Gateway-level (APIM, Cloudflare) + app-level for defense in depth.",
      "Rate limiting protects dependencies and fair usage.",
      "Partitioned rate limiter? — Rate limit by user ID not just IP.",
      "Rate limit vs throttling downstream? — App limits ingress; bulkhead limits egress.",
      "No rate limit on expensive export endpoint",
      "429 without Retry-After header",
      "Rate limit only at app — DDoS overwhelms before Kestrel"),
    q("JWT Authentication Architecture", "Security", "Very Common",
      "JWT authentication architecture for microservices?",
      "Identity provider issues signed JWT; resource APIs validate signature, issuer, audience, expiry — stateless auth.",
      "**Flow:** Login → IdP (Entra, Auth0) → access token + refresh token → API validates with `AddJwtBearer`.\n\n```csharp\nservices.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)\n    .AddJwtBearer(o => {\n        o.Authority = \"https://login.example.com\";\n        o.Audience = \"orders-api\";\n    });\n```\n\n**Architect:** Short-lived access tokens (15 min), refresh rotation, never store JWT in localStorage if XSS risk — HttpOnly cookie pattern for SPAs. Validate `aud`, `iss`, clock skew minimal.",
      "Token design affects security posture and scale.",
      "Reference tokens vs JWT? — Opaque tokens validated via introspection — more server calls.",
      "JWT in BFF pattern? — Backend-for-frontend holds tokens — SPA never sees access token.",
      "Accept JWT without audience validation",
      "Long-lived JWT (30 days) as access token",
      "Symmetric key shared across 20 microservices leaked"),
    q("Authorization Policies vs Roles", "Security", "Very Common",
      "Policies vs roles in ASP.NET Core authorization?",
      "Roles: coarse group membership (`Admin`, `User`). Policies: composable requirements — role + claim + custom handler.",
      "```csharp\nservices.AddAuthorization(o => o.AddPolicy(\"CanRefund\", p =>\n    p.RequireClaim(\"permission\", \"orders:refund\")));\n\n[Authorize(Policy = \"CanRefund\")]\n```\n\n**Architect:** Prefer policy-based and permission claims over role explosion (`Admin`, `SuperAdmin`, `RegionalAdmin`...). `IAuthorizationHandler` for resource-based auth (`CanEditOrder` checks order owner).",
      "Authorization model must scale with product complexity.",
      "FallbackPolicy? — Default deny all endpoints — explicit `[AllowAnonymous]`.",
      "Resource-based auth IAuthorizationService? — `AuthorizeAsync(user, order, \"EditPolicy\")`.",
      "Role checks scattered as string literals in controllers",
      "Authorize attribute without authentication middleware",
      "God role with all permissions"),
    q("CORS Architecture Decisions", "Security", "Common",
      "CORS architecture for SPA + multiple APIs?",
      "CORS is browser enforcement — server returns `Access-Control-Allow-Origin`. Not a substitute for auth.",
      "**Architect:** Explicit allowed origins — never `*` with credentials. BFF or API gateway as single origin to SPA reduces CORS surface.\n\n```csharp\nservices.AddCors(o => o.AddPolicy(\"Spa\", p => p\n    .WithOrigins(\"https://app.example.com\")\n    .AllowCredentials()));\n```\n\n**Preflight:** OPTIONS handled before auth middleware for anonymous preflight. Document which APIs need CORS vs server-to-server (no CORS needed).",
      "CORS misconfiguration is common production bug.",
      "SameSite cookies vs CORS? — Related but different — cookie CSRF protection.",
      "Wildcard subdomain WithOrigins? — Avoid overly broad `*.example.com` parsing limits.",
      "AllowAnyOrigin with AllowCredentials",
      "CORS on internal service-to-service calls unnecessarily",
      "Auth middleware blocks OPTIONS preflight"),
    q("Content Negotiation and Versioning", "API Design", "Occasional",
      "How content negotiation relates to API versioning?",
      "Content negotiation: client sends `Accept` header — server returns JSON, XML, or versioned media type. Versioning can live in URL, header, or `Accept: application/vnd.api.v2+json`.",
      "**Architect:** Prefer URL or header versioning for clarity — media type versioning couples format and version (`vnd.company.order.v2+json`). `AddMvc().AddXmlSerializerFormatters()` only if enterprise clients require XML.\n\n**Default:** `application/json` with URL `/v1/` — simplest ops and gateway routing.",
      "Negotiation complexity should match actual client needs.",
      "406 Not Acceptable when? — No formatter matches Accept — rare if JSON default always offered.",
      "Producing custom format? — `return Results.Content(data, \"application/custom\");`",
      "Media type versioning without client support",
      "XML formatter enabled nobody uses — attack surface",
      "Version in URL and Accept header disagree"),
    q("IAsyncEnumerable API Streaming", "ASP.NET Core", "Common",
      "Expose IAsyncEnumerable from ASP.NET Core for large datasets?",
      "Stream results incrementally — lower memory, faster time-to-first-byte for exports and live feeds.",
      "```csharp\napp.MapGet(\"/orders/export\", async IAsyncEnumerable<OrderDto> (\n    IOrderService svc, [EnumeratorCancellation] CancellationToken ct) =>\n{\n    await foreach (var order in svc.StreamOrdersAsync(ct))\n        yield return order;\n});\n```\n\n**Architect:** Prefer streaming for million-row exports over `ToListAsync`. Set response timeout accordingly. NDJSON or SSE for browser clients. `[EnumeratorCancellation]` propagates client disconnect.",
      "Streaming is memory architecture for data-heavy APIs.",
      "EF Core AsAsyncEnumerable? — Forward-only read — don't compose then ToList.",
      "Backpressure IAsyncEnumerable? — Consumer speed limits producer — Channel alternative.",
      "ToListAsync on million row query then return",
      "No cancellation — client disconnect leaves DB cursor open",
      "Buffer entire export in memory 'for simplicity'"),
    q("gRPC vs REST Decision", "API Design", "Common",
      "When choose gRPC over REST for internal microservices?",
      "gRPC: HTTP/2, protobuf binary, streaming, strong contracts — internal east-west. REST/JSON: browser-friendly, human-debuggable, public APIs.",
      "**gRPC when:** service-to-service, high throughput, bi-directional streaming, polyglot with `.proto` contract.\n\n**REST when:** public API, mobile/web clients, caching with HTTP semantics, teams without proto toolchain.\n\n**Architect:** gRPC behind mesh (mTLS); REST at edge via gateway translation if needed. Don't expose raw gRPC to browsers without gRPC-Web proxy.",
      "Protocol choice is boundary and consumer decision.",
      "gRPC transcoding? — REST facade on gRPC — Envoy, YARP.",
      "Versioning proto breaking changes? — Field numbers never reuse — additive only.",
      "gRPC for public browser API without gRPC-Web",
      "REST binary payloads for 10K RPS internal fan-out",
      "No deadline/timeout propagation in gRPC metadata"),
    q("SignalR Scale-Out Redis Backplane", "Real-Time", "Occasional",
      "Scale SignalR across multiple servers with Redis backplane?",
      "Without backplane, WebSocket messages stay on one server. Redis backplane broadcasts hub messages to all instances.",
      "```csharp\nservices.AddSignalR().AddStackExchangeRedis(redisConn, o => o.Configuration.ChannelPrefix = \"MyApp\");\n```\n\n**Architect:** Sticky sessions not required with Redis backplane but connection affinity helps. Azure SignalR Service preferred at scale — offloads connection management. Group names consistent across instances. Monitor Redis pub/sub latency.",
      "Real-time scale requires shared message fabric.",
      "Azure SignalR vs self-hosted Redis? — Managed removes connection limit ops burden.",
      "SignalR with JWT? — Pass token in query string WebSocket or use cookies — document security.",
      "Scale SignalR horizontally without backplane",
      "Group message only reaches users on same pod",
      "Redis backplane single point of failure unmonitored"),
    q("Configuration and Azure Key Vault", "Configuration", "Very Common",
      "Load secrets from Azure Key Vault in ASP.NET Core?",
      "Use `Azure.Extensions.AspNetCore.Configuration.Secrets` — merge Key Vault into configuration at startup with managed identity.",
      "```csharp\nbuilder.Configuration.AddAzureKeyVault(\n    new Uri(\"https://myvault.vault.azure.net/\"),\n    new DefaultAzureCredential());\n```\n\n**Architect:** No secrets in appsettings committed to git. Managed identity in Azure — no client secrets in config. Reload with `AddAzureKeyVault` + `IOptionsMonitor` for rotatable secrets. Separate vault per environment.",
      "Secret management is security baseline for cloud apps.",
      "Key Vault references App Service? — `@Microsoft.KeyVault(...)` — no code change deploy.",
      "Local dev Key Vault? — `DefaultAzureCredential` + Azure CLI login or user secrets locally.",
      "Connection strings in appsettings.Production.json in repo",
      "Service principal secret expires — no rotation runbook",
      "All config in Key Vault — non-secrets too — slow startup"),
    q("Feature Flags — Microsoft.FeatureManagement", "Configuration", "Common",
      "Adopt Microsoft.FeatureManagement in ASP.NET Core?",
      "Decouple deploy from release — toggle features via config, App Configuration, or LaunchDarkly adapter.",
      "```csharp\nservices.AddFeatureManagement();\n\n[FeatureGate(\"NewCheckout\")]\npublic class CheckoutV2Controller { }\n\nif (await featureManager.IsEnabledAsync(\"BetaSearch\"))\n```\n\n**Architect:** Percentage rollout, time window filters, targeting by user ID. Flags in Azure App Configuration with refresh. Remove stale flags quarterly — tech debt accumulates.",
      "Feature flags enable safe progressive delivery.",
      "IFeatureFilter custom? — Tenant-based, region-based enablement.",
      "Flags in zero-downtime migration? — Dual-write behind flag — expand-contract ally.",
      "Permanent if-feature-flag else legacy",
      "No flag cleanup — 200 dead flags",
      "Flag default true in production by mistake"),
    q("Unit Testing — xUnit Best Practices", "Testing", "Common",
      "xUnit best practices for .NET service unit tests?",
      "Arrange-Act-Assert, one logical assertion per test, descriptive names, avoid test inheritance, use fixtures sparingly.",
      "```csharp\n[Fact]\npublic async Task CreateOrder_ValidCommand_ReturnsOrderId()\n{\n    var handler = new CreateOrderHandler(_fakeRepo, _fakeClock);\n    var result = await handler.Handle(new CreateOrderCommand(...), CancellationToken.None);\n    Assert.NotEqual(Guid.Empty, result);\n}\n```\n\n**Architect:** Test behavior not implementation — mock ports, not every private method. `Theory` + `InlineData` for parameter matrix. No shared mutable state between tests. CI runs unit tests < 2 min.",
      "Test quality gates merge confidence.",
      "IClassFixture vs ICollectionFixture? — Expensive setup once per class/collection.",
      "FluentAssertions? — Readable — org standard optional.",
      "Mocking concrete classes instead of interfaces",
      "Tests hit real database labeled unit tests",
      "Async void test methods"),
    q("WebApplicationFactory Integration Tests", "Testing", "Common",
      "Integration test ASP.NET Core API with WebApplicationFactory?",
      "Bootstraps real app in memory with test server — exercises middleware, DI, routing, database (often Testcontainers).",
      "```csharp\npublic class OrdersApiTests : IClassFixture<WebApplicationFactory<Program>>\n{\n    private readonly HttpClient _client;\n    public OrdersApiTests(WebApplicationFactory<Program> factory)\n    {\n        _client = factory.WithWebHostBuilder(b => b.ConfigureServices(s => {\n            // replace DbContext with test DB\n        })).CreateClient();\n    }\n}\n```\n\n**Architect:** `partial class Program` for test visibility. Replace external HTTP with `TestHandler`. Testcontainers SQL for realistic migrations test. Separate integration from unit in CI jobs.",
      "Integration tests catch wiring bugs unit tests miss.",
      "CustomWebApplicationFactory pattern? — Shared seed data and auth header helpers.",
      "Respawn DB reset? — Fast DB cleanup between tests.",
      "Mock entire DbContext in integration test",
      "Shared production database connection string",
      "No assertion on HTTP status code and body shape"),
    q("Containerizing ASP.NET Core", "DevOps", "Very Common",
      "Dockerfile best practices for ASP.NET Core microservice?",
      "Multi-stage build: SDK stage publish, runtime aspnet stage copy — small image, non-root user.",
      "```dockerfile\nFROM mcr.microsoft.com/dotnet/sdk:8.0 AS build\nWORKDIR /src\nCOPY . .\nRUN dotnet publish -c Release -o /app\n\nFROM mcr.microsoft.com/dotnet/aspnet:8.0\nWORKDIR /app\nCOPY --from=build /app .\nUSER $APP_UID\nENTRYPOINT [\"dotnet\", \"Orders.Api.dll\"]\n```\n\n**Architect:** Pin image digests in prod. Health check `HEALTHCHECK` instruction. `ASPNETCORE_URLS=http://+:8080`. Read-only root filesystem where possible. Distroless or chiseled images for attack surface reduction.",
      "Container hygiene affects security and deploy speed.",
      "K8s resources requests/limits? — Set from load test — not unset.",
      "Graceful shutdown SIGTERM? — Kestrel drains — configure `terminationGracePeriodSeconds`.",
      "SDK image as production runtime",
      "Running as root in container",
      "No health check — K8s sends traffic to starting pod"),
    q("CI Pipeline for .NET Microservice", "DevOps", "Common",
      "Essential CI pipeline stages for .NET microservice?",
      "Restore → build → test (unit + integration) → analyze (Sonar) → pack/publish → container build → push → deploy staging.",
      "**Architect gates:**\n- `dotnet test` with coverage threshold\n- `dotnet format --verify-no-changes`\n- Security scan (Dependabot, Trivy image scan)\n- EF migration script artifact for DBA review\n\n**GitHub Actions / Azure DevOps:** cache NuGet, matrix SDK version only if multi-target. Fail fast on analyzer warnings as errors in main.",
      "CI is quality contract before production.",
      "Trunk-based vs GitFlow CI? — Main branch always deployable — feature flags for incomplete.",
      "Integration test in CI with Testcontainers? — Docker-in-Docker service required.",
      "Deploy without running tests",
      "No lock file — floating package versions break main",
      "Skip container scan — vulnerable base image shipped"),
    q("Performance Profiling Workflow", "Performance", "Common",
      "Performance profiling workflow for slow ASP.NET Core endpoint?",
      "Reproduce → measure (dotnet-counters, App Insights) → profile (dotnet-trace, dotMemory) → fix → verify.",
      "**Steps:**\n1. Load test baseline (k6, NBomber)\n2. `dotnet-counters monitor System.Runtime` — GC, thread pool\n3. `dotnet-trace collect` during load — analyze in Speedscope\n4. Check SQL execution plan, N+1 queries\n\n**Architect:** Profile in staging with production-like data volume. Fix biggest bottleneck first — often DB not CPU. Establish perf budget per endpoint in CI smoke load test.",
      "Systematic profiling beats guessing optimizations.",
      "EventPipe vs Application Insights profiler? — EventPipe local deep dive; App Insights production sampling.",
      "BenchmarkDotNet for micro-optimization? — Library code — not full HTTP stack.",
      "Optimize code before measuring",
      "Profile dev laptop with 100 rows seed data",
      "string concatenation optimized while SQL does table scan"),
]
