"""Hand-crafted premium Q001–Q005 for Weeks 41–44 — ADRs, FinOps/DR, Frontend, Enterprise Case Studies."""

from premium_qa_data import q

WEEK_41_Q001_Q005 = [
    q("ADR Workflow Overview", "ADRs", "Very Common",
      "Describe the end-to-end ADR workflow in an enterprise engineering organization.",
      "ADR workflow: identify significant decision → draft ADR in Git → async review (RFC optional) → architecture board or PR approval → merge Accepted → implement → monitor → supersede when context changes. Decisions are versioned artifacts, not meeting notes.",
      "**Enterprise ADR workflow:**\n```\nTrigger (spike, RFC, incident, compliance)\n    → Draft ADR PR (Proposed)\n    → Review (architect, security, data, FinOps as needed)\n    → Accepted (merged) or Returned for revision\n    → Implementation tracked in tickets (link ADR number)\n    → Monitor outcomes vs consequences section\n    → Supersede with new ADR when decision reverses\n```\n\n**Key roles:**\n- **Author** — team lead or architect closest to problem\n- **Reviewers** — domain delegates per decision tier\n- **Deciders** — named in ADR metadata; accountable for outcome\n\n**Tooling:** Markdown in `docs/adr/`, PR comments = review trail, decision log index in README or Backstage.\n\n**Architect:** Publish workflow in engineering handbook — reduces 'should we ADR this?' debate every sprint. SLA: Tier-0 decisions documented within 5 business days of review meeting.",
      "ADR workflow turns architecture from oral tradition into auditable engineering practice.",
      "ADR without RFC? — Acceptable for smaller teams; RFC recommended when multiple options need broad input.",
      "Who owns the decision log? — Platform architecture team maintains index; authors own individual ADRs.",
      "Decisions captured only in Confluence with no Git history",
      "Accepted ADR never linked from implementation tickets",
      "Proposed ADRs left open indefinitely without resolution"),
    q("C4 Model Introduction", "C4 Model", "Very Common",
      "Introduce the C4 model and explain why architects use it for documentation.",
      "C4 = four zoom levels: Context (system in world), Container (deployable units), Component (internals of one container), Code (optional class detail). Simple boxes and lines — stakeholders at every level understand the same notation.",
      "**Four levels (Simon Brown):**\n| Level | Name | Shows | Audience |\n|-------|------|-------|----------|\n| 1 | Context | System + users + externals | Executives, security |\n| 2 | Container | Apps, APIs, DBs, queues | Architects, tech leads |\n| 3 | Component | Modules inside one container | Build team |\n| 4 | Code | Classes (optional) | Developers |\n\n**Why C4 over UML-only:**\n- Consistent vocabulary across teams\n- Zoom in/out without redrawing everything\n- Tool-agnostic — Structurizr, Mermaid, draw.io, whiteboard\n- Forces separation of concerns — no microservices on context diagram\n\n**Enterprise adoption:**\n- Context + Container required for Tier-1 services\n- Component optional unless complexity warrants\n- Store diagrams as code in Git alongside ADRs\n\n**Architect:** C4 is communication framework — one diagram set per system, not one style per architect.",
      "C4 answers 'who sees what detail?' — interviewers expect you to name all four levels.",
      "C4 vs ArchiMate? — C4 for software delivery teams; ArchiMate for enterprise portfolio — can coexist.",
      "Diagrams as code? — Structurizr DSL or Mermaid in repo — diffable in PR review.",
      "Single diagram mixing context and class level",
      "No legend or technology labels on container diagram",
      "Diagrams stored only in PowerPoint never updated"),
    q("Architecture Governance Board", "Governance", "Very Common",
      "What is an architecture governance board and how should it operate?",
      "Governance board: cross-functional forum (architecture, security, data, platform, product) that sets standards, reviews Tier-0/1 designs, resolves conflicts, and approves exceptions. Operates on published charter, tiered review, and time-boxed decisions — not a design-by-committee bottleneck.",
      "**Board charter elements:**\n- **Mission** — Protect NFRs, reduce duplication, enable safe speed\n- **Scope** — What requires board review vs team autonomy\n- **Membership** — Rotating domain delegates + enterprise architect chair\n- **Cadence** — Weekly 60-min + async pre-read 48h before\n- **Outputs** — Decision, waiver with expiry, or return with required changes\n\n**Tiered intake:**\n| Tier | Examples | Review |\n|------|----------|--------|\n| 0 | Payment, PHI, identity | Full board + security |\n| 1 | New microservice, data store | Architect delegate async |\n| 2 | Internal tool, POC | Team self-serve checklist |\n\n**Anti-patterns to avoid:**\n- Board designs every API field — reviews architecture not implementation\n- No published golden paths — board becomes approval factory\n\n**Architect:** Board succeeds when 80% of teams pass lightweight checklist without meeting — standards enable autonomy.",
      "Governance board balances control and velocity — architects design the tiering model.",
      "ARB vs guild? — ARB decides and gates; architecture guild shares patterns without veto power.",
      "Exception process? — Time-boxed waiver with compensating controls and executive sponsor.",
      "Every PR requires board meeting approval",
      "Board has no published standards — only reactive veto",
      "Security absent from healthcare or payment reviews"),
    q("Legacy System Architecture Review", "Reviews", "Very Common",
      "How do you approach reviewing the architecture of a legacy system you did not build?",
      "Start with business criticality and evidence: interviews, metrics, dependency maps, incident history, and code archaeology. Document as-is C4 (approximate is OK), score risks, recommend contain/wrap/replace/retire — never big-bang rewrite without TCO data.",
      "**Review phases:**\n1. **Scoping** — What capability does system support? Revenue/regulatory criticality?\n2. **Discovery** — CMDB, APM traces, batch schedules, integration inventory, on-call tribal knowledge\n3. **As-is documentation** — Context + container diagram even if dotted lines for unknowns\n4. **Risk register** — Unsupported runtime, security debt, bus factor, data quality, hidden integrations\n5. **Recommendations** — Prioritized roadmap with strangler fig, API facade, or retirement\n\n**Outputs:**\n- Architecture assessment report (executive summary + technical detail)\n- ADR for modernization approach\n- Funding ask with 3-year sustain vs transform TCO\n\n**Interview signal:** Treat 'unknown integration' as a finding, not embarrassment. Recommend evidence-gathering spikes before commitment.\n\n**Architect:** Legacy review is forensic architecture — production behavior beats original design docs.",
      "Legacy reviews separate evidence from nostalgia — architects quantify risk before recommending rewrite.",
      "Document as code for legacy? — Baseline as-is diagram in Git enables drift detection on future changes.",
      "When recommend rewrite? — When sustain cost exceeds transform cost over 3-year TCO with confidence interval.",
      "Recommend cloud lift without understanding batch windows",
      "Skip interviews with ops/on-call team",
      "Ignore undeclared FTP or file-based integrations"),
    q("RFC Process for Proposals", "Governance", "Very Common",
      "Explain the RFC process for architecture proposals before a decision is finalized.",
      "RFC (Request for Comments) is a time-boxed proposal for gathering feedback before commitment. Author publishes problem, goals, options, and open questions; stakeholders comment async; facilitator synthesizes; outcome is recorded in ADR — not on the RFC itself.",
      "**RFC lifecycle:**\n```\nDraft RFC (Markdown in Git) → Announce (#architecture, email)\n    → Comment period (5–10 business days)\n    → Facilitator resolves threads / decision meeting if conflict\n    → Write ADR (Accepted / Rejected option documented)\n    → Close RFC as Resolved or Withdrawn\n```\n\n**RFC template sections:**\n- Problem statement and urgency\n- Goals and explicit **non-goals**\n- Proposed approach + at least one alternative\n- Migration/rollback considerations\n- Open questions with owners\n\n**Rules:**\n- RFC proposes; ADR decides — RFC never has status 'Accepted'\n- Required reviewers by domain (security, data, platform)\n- Stale RFCs closed as Withdrawn — no ambiguous limbo\n\n**Architect:** RFC democratizes input for distributed teams; ADR preserves output for audit. Async-first with optional 30-min conflict-resolution meeting.",
      "RFC separates exploration from commitment — architects facilitate, not dictate, before ADR.",
      "RFC vs design doc? — RFC gathers input pre-decision; design doc explains implementation post-decision.",
      "Comment period length? — 5 days standard; 10 for org-wide impact; emergency track with explicit risk acceptance.",
      "Decision made in Slack never captured in ADR",
      "RFC with single option and no alternatives considered",
      "Unlimited comment period blocking delivery"),
]

WEEK_42_Q001_Q005 = [
    q("FinOps Principles Overview", "FinOps", "Very Common",
      "What are the core FinOps principles and how do architects participate?",
      "FinOps = cultural practice where engineering, finance, and business share cloud cost accountability. Core principles: teams need visibility; everyone takes ownership; central team enables (not controls); decisions driven by business value. Architects embed cost into design — tagging, right-sizing, and unit economics.",
      "**FinOps Foundation principles:**\n1. **Teams need to collaborate** — Finance alone cannot optimize; engineers change 80% of spend\n2. **Everyone takes ownership** — Cost per team visible via tags and showback\n3. **Central team enables** — FinOps provides tooling, standards, and education — not gatekeeping\n4. **Reports should be accessible** — Engineers see daily cost, not quarterly surprise\n5. **Decisions driven by business value** — Optimize unit economics, not just total bill\n\n**Architect responsibilities:**\n- Mandatory cost tags in IaC (costCenter, env, service, owner)\n- Cost estimate section in every Tier-0/1 ADR\n- Design for linear cost scaling — avoid exponential surprises (unbounded logs, cross-AZ chatter)\n- Partner with FinOps on capacity plans and RI baseline\n\n**Three phases (Inform → Optimize → Operate):** Visibility first, then rate/usage optimization, then governance policies.\n\n**Interview framing:** FinOps is not 'finance tells engineering to cut' — it's engineering accountability with finance partnership.",
      "Architects who ignore FinOps design invoices they cannot explain to executives.",
      "Showback vs chargeback? — Showback reports cost; chargeback bills internal teams — political sensitivity.",
      "Unit economics? — Cost per order/API call/tenant — architects define measurable denominator.",
      "FinOps treated as finance-only problem",
      "No cost estimate in architecture review package",
      "Optimizing reserved instances before tagging and visibility exist"),
    q("DR Tier Classification", "DR", "Very Common",
      "How do you classify workloads into DR tiers and what drives tier assignment?",
      "DR tiers map business impact to recovery patterns: Tier 0 (no DR, dev only), Tier 1 (backup/restore, hours–days RTO), Tier 2 (warm standby, minutes–hours), Tier 3 (active-active, near-zero RTO/RPO). Assignment comes from Business Impact Analysis — not engineer preference.",
      "**Standard tier model:**\n| Tier | RTO | RPO | Pattern | Example |\n|------|-----|-----|---------|--------|\n| 0 | N/A | N/A | None | Dev sandboxes, POC |\n| 1 | 24h+ | 24h | Backup restore | Internal wiki, reporting |\n| 2 | 1–4h | 15m–1h | Warm standby, ASR | Order API, CRM |\n| 3 | <15m | ~0 | Active-active multi-region | Payment auth, core banking |\n\n**Assignment process:**\n1. Business Impact Analysis (BIA) — revenue/hour, regulatory penalty, reputational harm\n2. Map capability to tier — per workload, not per company\n3. Document in NFR matrix linked to ADR\n4. FinOps validates tier cost against business case\n\n**Architect guardrails:**\n- Resist tier inflation — everything labeled Tier 3 doubles cloud spend\n- Tier 3 requires proven failover drills, not aspiration\n- Tier 0 acceptable for non-production only\n\n**Cost signal:** Tier 3 typically costs 1.5–2.5× Tier 2 — justify with revenue at risk.",
      "DR tier is business classification that becomes infrastructure topology — architects facilitate BIA, not guess.",
      "Tier 2 vs 3 decision? — Revenue per minute of outage + regulatory RTO mandate drives tier.",
      "Tier documented where? — NFR matrix + ADR + CMDB — not orphaned spreadsheet.",
      "Production payment path on Tier 0",
      "Same DR tier applied to batch reporting and checkout",
      "DR tier in spreadsheet not linked to infrastructure design"),
    q("RTO and RPO Fundamentals", "DR", "Very Common",
      "Define RTO and RPO and explain how they drive architectural decisions.",
      "RPO (Recovery Point Objective) = maximum acceptable data loss measured in time. RTO (Recovery Time Objective) = maximum acceptable downtime. Lower targets require more replication, redundancy, automation, and cost — architects translate business tolerance into infrastructure design.",
      "**Definitions:**\n- **RPO 15 minutes** — At worst, lose 15 minutes of data since last durable copy\n- **RTO 1 hour** — Service must be restored within 1 hour of outage declaration\n\n**How targets drive architecture:**\n| Target | Typical pattern |\n|--------|----------------|\n| RPO 24h | Nightly backup sufficient |\n| RPO 15m | Async geo-replication + lag monitoring |\n| RPO ~0 | Sync replication, dual-write complexity, latency trade-off |\n| RTO 4h | Backup restore + documented runbook |\n| RTO 15m | Warm standby with automated failover (ASR, DNS flip) |\n| RTO <5m | Active-active, health-checked traffic shift |\n\n**Stakeholder conversation:**\n```\n'How much data can we afford to lose?' → RPO\n'How long can customers wait?' → RTO\n```\n\n**Architect:** Document assumptions — 'RPO 15 min assumes replication lag alert at 5 min.' Untested runbooks mean fantasy RTO.",
      "RTO/RPO are business numbers that become replication topology — confuse them in interviews at your peril.",
      "RPO 0 across regions? — Synchronous replication — watch cross-region write latency impact.",
      "RTO without tested runbook? — Drill proves real RTO; paper target is worthless.",
      "Confusing RTO with RPO in interview answers",
      "Promising RTO 5 min with cold backup-only architecture",
      "No replication lag monitoring despite 15-minute RPO claim"),
    q("Load Testing Strategy", "Performance", "Very Common",
      "Design a load testing strategy for an enterprise system approaching production.",
      "Load testing strategy defines scenarios (smoke, load, stress, soak), environments (prod-like staging), tools (k6, JMeter), thresholds tied to NFRs, CI integration, and go/no-go gates. Architects ensure tests validate realistic user journeys — not just health-check endpoints.",
      "**Test scenario pyramid:**\n| Scenario | Purpose | Scale |\n|----------|---------|-------|\n| Smoke | Pipeline sanity | 10 VU, 2 min |\n| Load | Expected peak | 1× peak QPS, 30 min |\n| Stress | Breaking point | 2–3× peak until failure |\n| Soak | Memory leak, drift | 1× load, 12–24h |\n\n**Architecture integration:**\n```\nNFR matrix → k6 thresholds → CI gate on staging → pre-release sign-off\n```\n\n**Environment requirements:**\n- Prod-like data volume (anonymized), network topology, and dependency mocks where unsafe\n- Isolated from production — never load test prod without explicit chaos program\n- Results stored as CI artifacts + Grafana dashboard\n\n**Go/no-go criteria:**\n- p95 latency within performance budget\n- Error rate <0.1% under expected peak\n- No resource exhaustion (connection pool, thread leak) in soak test\n\n**Architect:** Map every performance NFR to a named test scenario — 'we load tested once' is not a strategy.",
      "Load testing strategy connects NFRs to release confidence — architects define thresholds, not just ops.",
      "Synthetic prod monitoring? — Small constant k6 run against canary post-deploy catches regression.",
      "When skip stress test? — Never for Tier-0; acceptable for internal tools with documented risk.",
      "Load test only localhost dev machine",
      "Health-check endpoint only — misses real user journey latency",
      "No CI integration — load test run manually once before launch"),
    q("Performance Budgets Definition", "Performance", "Very Common",
      "What are performance budgets and how do architects define them for web applications?",
      "Performance budgets are measurable limits on latency, bundle size, and resource consumption — e.g., p95 API <300ms, JS bundle <200KB, LCP <2.5s. Defined per user journey, enforced in CI, and owned by product + engineering — not optional nice-to-haves.",
      "**Budget categories:**\n| Layer | Example budget | Enforcement |\n|-------|----------------|-------------|\n| Frontend | LCP <2.5s, JS <200KB gzipped | Lighthouse CI, bundle analyzer |\n| API | Checkout p95 <300ms | k6 thresholds in pipeline |\n| Database | Query p95 <50ms | APM + slow query alerts |\n| Third-party | Payment SDK <500ms | Synthetic monitoring |\n\n**Definition process:**\n1. Identify critical user journeys (checkout, search, login)\n2. Set budgets from NFR matrix and UX research (53% abandon >3s load)\n3. Allocate budget across layers — BFF 100ms, DB 50ms, network 50ms = 200ms headroom\n4. Add CI gates — PR fails if bundle grows >5% without approval\n\n**Architect:** Performance budget ADR documents trade-offs — 'rich personalization costs 80KB JS; accepted with lazy load.'\n\n**Regression response:** Budget breach blocks deploy or triggers optimization sprint — same rigor as security CVE.",
      "Performance budgets make NFRs enforceable — architects define them before optimization debates start.",
      "Budget per journey vs global? — Per journey — homepage and checkout have different tolerance.",
      "Mobile vs desktop budgets? — Separate budgets — mobile networks need stricter targets.",
      "Budgets defined but never enforced in CI",
      "Single global latency number for all APIs",
      "Frontend bundle grows unbounded — no analyzer in pipeline"),
]

WEEK_43_Q001_Q005 = [
    q("React Architecture for Enterprise", "Frontend", "Very Common",
      "How do you structure React architecture for a large enterprise single-page application?",
      "Enterprise React = feature-based folders, container/presentational split, shared design system, server state via TanStack Query, client state only where needed, lazy-loaded routes, TypeScript strict mode, and ESLint boundary rules between domains.",
      "**Recommended structure:**\n```\nsrc/\n  features/orders/     — components, hooks, api, types\n  features/checkout/\n  shared/ui/           — design system primitives\n  shared/hooks/\n  app/                 — routing, providers, layout shell\n```\n\n**Key patterns:**\n- **Container components** — fetch/orchestrate; pass data to **presentational** pure UI\n- **Custom hooks** — `useOrderList()` encapsulates React Query + error handling\n- **Design system package** — shared Button, Modal, tokens — versioned independently\n- **Code splitting** — `React.lazy` per route; monitor bundle with webpack analyzer\n\n**State ownership (frontend ADR):**\n| Data type | Tool |\n|-----------|------|\n| Server/API cache | TanStack Query |\n| URL state | React Router search params |\n| Complex client-only | Context or Zustand (sparingly) |\n| Form transient | React Hook Form local state |\n\n**Architect:** Feature-first structure maps to team boundaries — layer-first (all components together) couples teams at scale.",
      "Enterprise React architecture is team topology — interviewers probe folder structure and state ownership.",
      "Server Components? — Next.js App Router shifts data fetch server-side — document boundary in ADR.",
      "Monorepo vs multirepo? — Nx/Turborepo for shared design system across multiple SPAs.",
      "God component 2000 lines mixing fetch and UI",
      "Redux store for all API response caching",
      "No shared design system — 12 inconsistent button implementations"),
    q("Angular Enterprise Structure", "Frontend", "Very Common",
      "How should a large enterprise Angular application be structured?",
      "Enterprise Angular uses domain feature folders, lazy-loaded routes, core module (singleton services once), shared module (dumb UI), strict import boundaries, and standalone components for new code. Prevents circular dependencies and enables independent team delivery.",
      "**Folder layout:**\n```\nsrc/app/\n  core/           — auth, interceptors, guards (import once in AppConfig)\n  shared/         — pipes, directives, presentational components\n  features/\n    checkout/     — lazy route, feature-specific services\n    account/\n```\n\n**Modern Angular (v17+):**\n- Standalone components + `provideRouter` with `loadComponent`\n- Signals for reactive state where appropriate\n- NgModules acceptable for legacy maintenance — new code standalone-first\n\n**Boundary enforcement:**\n- ESLint `import/no-restricted-paths` — features cannot import sibling features\n- Shared services only via `core/` or explicit public API barrel\n\n**Architect concerns:**\n- HttpClient interceptors centralized in core (auth token, correlation ID, error handling)\n- One `providedIn: 'root'` singleton per domain service — avoid duplicate providers\n- Lazy loading mandatory for features >50KB — initial bundle budget enforcement",
      "Angular enterprise structure prevents dependency spaghetti — architects enforce boundaries, not just recommend folders.",
      "NgModule vs standalone migration? — Incremental: new features standalone; migrate legacy on touch.",
      "Nx monorepo? — Enforces module boundaries with tags (`scope:checkout`, `type:feature`).",
      "Everything imported in AppModule — no lazy loading",
      "Feature-to-feature direct imports causing circular deps",
      "Shared module re-providing HttpClient in every feature"),
    q("BFF Pattern Fundamentals", "Frontend", "Very Common",
      "Explain the Backend-for-Frontend (BFF) pattern and when to use it.",
      "BFF is a dedicated API layer per frontend experience (web, mobile) that aggregates microservices, shapes DTOs for UI screens, and handles browser-specific auth. Prevents SPA from calling many microservices directly and coupling UI to internal service topology.",
      "**Architecture:**\n```\nWeb SPA → Web BFF → Order MS, Payment MS, Inventory MS\nMobile  → Mobile BFF → (same or subset of services)\n```\n\n**BFF responsibilities:**\n- Aggregate parallel downstream calls into one screen payload\n- Transform internal domain models to UI-friendly DTOs\n- Handle cookie/session auth appropriate for browser\n- Apply per-client rate limiting and caching\n\n**BFF vs API Gateway:**\n| Concern | API Gateway | BFF |\n|---------|-------------|-----|\n| Auth, TLS, WAF | ✅ | Delegates to gateway |\n| Screen-specific aggregation | ❌ | ✅ |\n| Per-client DTO shaping | ❌ | ✅ |\n\n**When to use:** 3+ microservices per screen, different web/mobile needs, or auth token exchange complexity.\n**When to skip:** Small team, monolith backend, simple CRUD — BFF adds operational overhead.\n\n**Architect:** One BFF per frontend type — not one BFF per developer.",
      "BFF is the UI's API contract — architects prevent SPAs from becoming distributed monolith clients.",
      "GraphQL as BFF? — Possible for flexible queries; adds schema governance and N+1 risk.",
      "BFF business logic limit? — Orchestration yes; core domain rules stay in microservices.",
      "SPA calls 15 microservices directly from browser",
      "Single BFF serving web and mobile with divergent screen needs",
      "BFF becomes dumping ground for all business logic"),
    q("Micro-Frontends Overview", "Frontend", "Very Common",
      "What are micro-frontends and when should an enterprise adopt them?",
      "Micro-frontends decompose a web UI into independently deployable frontend applications composed at runtime (Module Federation, single-spa) or build time (monorepo packages). Adopt when team autonomy and release cadence pain exceed integration complexity cost — not for small teams.",
      "**Composition models:**\n| Model | How | Trade-off |\n|-------|-----|----------|\n| Build-time | npm packages in monorepo | Simple; coupled deploy |\n| Run-time (Module Federation) | Shell loads remote bundles | Independent deploy; version matrix |\n| iframe | Isolated embed | Strong isolation; UX limitations |\n\n**Typical architecture:**\n- **Shell** — routing, auth, design system, layout\n- **Remote MFEs** — checkout, catalog, account — separate repos and pipelines\n- **Shared dependencies** — React singleton via federation shared config\n\n**Adopt when:**\n- 5+ teams blocked on unified SPA release train\n- Clear domain boundaries map to UI slices\n- Organization accepts contract testing and version compatibility overhead\n\n**Skip when:**\n- <20 frontend developers — feature folders in monolith SPA simpler\n- Tight UX consistency requirements without design system discipline\n\n**Architect:** Micro-frontends are organizational architecture — technical cost is real; document decision in ADR.",
      "Micro-frontends trade integration complexity for team autonomy — architects quantify when the trade is worth it.",
      "Module Federation vs single-spa? — Federation shares DOM seamlessly; single-spa orchestrates framework-agnostic mounts.",
      "Shared design system? — Mandatory — without it MFEs look like different products.",
      "Micro-frontends adopted for 5 developers because it's trendy",
      "No contract tests between shell and remotes",
      "Duplicate React versions loaded — bundle bloat and hook errors"),
    q("SPA Security Fundamentals", "Frontend", "Very Common",
      "What are the essential security considerations for enterprise single-page applications?",
      "SPA security: OIDC/OAuth with PKCE (no implicit flow), tokens in memory or HttpOnly cookies (not localStorage for refresh), CSP headers, XSS prevention (sanitize, avoid dangerouslySetInnerHTML), CORS strict origin, BFF for token handling, and security headers on HTML shell.",
      "**Authentication:**\n- Authorization Code + PKCE for public SPA clients\n- Short-lived access token; refresh via HttpOnly Secure SameSite cookie or BFF session\n- Never store refresh tokens in localStorage — XSS exfiltration risk\n\n**XSS defense:**\n- Content-Security-Policy: `script-src 'self'`; nonce for inline if required\n- Sanitize user HTML (DOMPurify); encode output in templates\n- Avoid embedding secrets or API keys in client bundle — use BFF\n\n**API security:**\n- CORS: explicit allowed origins — not `*` with credentials\n- CSRF: SameSite cookies or anti-CSRF tokens for cookie-based auth\n- Rate limiting at gateway/BFF per session/IP\n\n**Supply chain:**\n- Lockfile + `npm audit` in CI; Dependabot for CVE patches\n- Subresource Integrity (SRI) on CDN scripts\n\n**Architect:** SPA security ADR documents token storage decision and threat model summary — security headers on API alone miss the HTML attack surface.",
      "SPA security failures are architecture failures — token storage and CSP are interview staples.",
      "BFF for token exchange? — Keeps client secret and refresh handling server-side.",
      "Third-party scripts? — Analytics/chat widgets are XSS vectors — load async with strict CSP.",
      "Refresh token in localStorage",
      "API keys embedded in React bundle",
      "Security headers configured on API but not on HTML shell"),
]

WEEK_44_Q001_Q005 = [
    q("Healthcare Architecture Constraints", "Enterprise", "Very Common",
      "What architectural constraints apply when designing systems that handle protected health information (PHI)?",
      "Healthcare architecture requires BAA with cloud provider, PHI encryption at rest and in transit, minimum-necessary access, audit logging (6+ years), private networking, no prod PHI in dev, de-identified test data, and breach notification runbooks. HIPAA is law — technical and administrative controls both mandatory.",
      "**Key constraints:**\n| Domain | Requirement |\n|--------|-------------|\n| Cloud | BAA only with HIPAA-eligible services |\n| Network | Private endpoints; no public PHI APIs |\n| Identity | MFA, RBAC, break-glass access audited |\n| Data | Encryption AES-256; field-level PHI tagging |\n| Audit | Immutable logs; who accessed what PHI when |\n| Dev/test | De-identified or synthetic data only |\n\n**Architecture zones:**\n```\n[PHI Zone: EHR API, Clinical DB] ←private link→ [Integration]\n[Non-PHI: Marketing site] — no PHI data paths\n[Analytics: De-identified warehouse only]\n```\n\n**Azure specifics:** Verify service HIPAA eligibility before design — not all services covered under BAA.\n\n**Architect:** Document PHI data flows on context diagram; every external integration gets DLP review. HIPAA violation cost >> architecture review time.",
      "Healthcare interviews test PHI boundaries and BAA — architects design zones, not just encrypt databases.",
      "HIPAA vs HITRUST? — HIPAA is legal requirement; HITRUST certifies control implementation — both may apply.",
      "ePHI in logs? — Redact at ingestion — logging PHI is common violation vector.",
      "HIPAA-eligible service used without signed BAA",
      "Production PHI copied to developer laptops for debugging",
      "Analytics data lake contains raw PHI for convenience"),
    q("Fintech PCI Architecture", "Enterprise", "Very Common",
      "How does PCI DSS influence payment system architecture?",
      "PCI architecture minimizes Cardholder Data Environment (CDE) scope: tokenization, hosted payment fields (iframe/JS SDK), no PAN/CVV on merchant servers, network segmentation, no PAN in logs, and annual SAQ or audit based on scope level. Design goal: SAQ A or A-EP instead of full SAQ D.",
      "**Scope reduction patterns:**\n```\nBrowser → PSP hosted fields (PAN never touches merchant)\nMerchant server receives token only → reduced PCI scope\n```\n\n**Architecture layers:**\n- **Out of scope** — Systems handling only tokens, never PAN\n- **CDE** — Any system storing, processing, or transmitting card data\n- **Connected to** — Systems on same network segment as CDE — may inherit scope\n\n**Controls regardless of scope:**\n- TLS 1.2+ for all payment traffic\n- No PAN storage post-authorization (token vault only)\n- Webhook signature verification on payment events\n- Segmented network; WAF on payment-facing endpoints\n\n**SAQ types:**\n| SAQ | When |\n|-----|------|\n| A | Fully outsourced card entry (iframe) |\n| A-EP | Merchant website affects payment security |\n| D | Full card data environment |\n\n**Architect:** PCI scope directly drives cost — custom card forms posting PAN to your API triggers full audit.",
      "PCI scope minimization is primary fintech architecture skill — tokenization beats encryption-in-your-DB.",
      "PAN in logs? — Automatic PCI failure — structured logging must redact payment payloads.",
      "Network segmentation? — CDE isolated VLAN; firewall rules documented and reviewed annually.",
      "Custom card form posting PAN to merchant API",
      "Encrypted PAN stored in application database instead of PSP token",
      "Full PCI audit triggered for entire datacenter unnecessarily"),
    q("Retail Peak Scale Patterns", "Enterprise", "Very Common",
      "What architecture patterns prepare retail e-commerce for predictable peak traffic (e.g., Black Friday)?",
      "Peak retail patterns: pre-scale capacity weeks ahead, CDN for product pages, read replicas, checkout queue/virtual waiting room, autoscale with tested caps, feature freeze, degrade non-critical paths, synthetic monitoring, and load test at 3× expected peak.",
      "**Peak preparation playbook:**\n1. **Capacity** — Pre-warm AKS nodes, Redis, connection pools 4–6 weeks prior\n2. **CDN/edge** — Static product catalog, ISR, long TTL on fingerprinted assets\n3. **Read scaling** — DB read replicas; cache hot product/inventory queries\n4. **Checkout protection** — Virtual waiting room when origin overload; bulkhead thread pool for payment path\n5. **Degradation** — Disable recommendations, reviews, non-critical personalization first\n6. **Operational** — War room, feature freeze 2 weeks before, synthetic monitors every 60s\n\n**Load validation:**\n- k6 stress test at 3× peak — 6 weeks before event\n- Measure p99 checkout latency and error budget consumption\n- Document headroom in peak architecture ADR\n\n**Architect:** Peak is predictable chaos — architecture plans months ahead; day-before load test is malpractice.",
      "Retail peak architecture is rehearsed reliability — interviewers want specific patterns, not 'we'll autoscale.'",
      "Virtual waiting room? — Azure Front Door or custom queue — protects origin from stampede.",
      "Multi-region for peak? — Active-active or warm DR region for geographic traffic distribution.",
      "First load test the day before Black Friday",
      "Autoscale limits never validated at 3× expected traffic",
      "Single region serving global retail customers"),
    q("Multi-Tenant SaaS Isolation", "Enterprise", "Very Common",
      "How do you design tenant isolation in a multi-tenant SaaS architecture?",
      "Tenant isolation models range from pooled (shared DB, row-level tenantId) to siloed (database per tenant). Choose based on compliance, noisy-neighbor tolerance, and cost. Defense in depth: middleware enforces tenant context on every query, integration tests for cross-tenant leaks, and rate limits per tenant.",
      "**Isolation models:**\n| Model | Isolation | Cost | Best for |\n|-------|-----------|------|----------|\n| Pooled (shared schema) | Low | Lowest | SMB SaaS |\n| Schema per tenant | Medium | Medium | Mid-market |\n| Database per tenant | High | High | Enterprise/regulated |\n| Silo per tenant (dedicated stack) | Highest | Highest | Government, healthcare |\n\n**Defense in depth:**\n- Tenant context from JWT claim — middleware injects `tenantId` into every DB query\n- Row-level security (PostgreSQL RLS) as safety net\n- Separate encryption keys per tenant for regulated data\n- No shared cache keys without tenant prefix\n- Automated cross-tenant penetration tests in CI\n\n**Noisy neighbor:**\n- Per-tenant rate limits and fair-queue scheduling\n- Dedicated resource pool for whale tenants\n\n**Architect:** Cross-tenant data leak is company-ending — isolation model is Tier-0 ADR with rejected alternatives documented.",
      "Tenant isolation is trust architecture — architects choose model from compliance and blast radius, not convenience.",
      "Tenant in subdomain vs JWT? — Subdomain routing + JWT claim double-validation for defense in depth.",
      "Migration between models? — Pooled to silo is multi-year event — choose early for regulated verticals.",
      "tenantId passed only from client query parameter without server validation",
      "Shared Redis cache keys without tenant prefix",
      "No automated test proving Tenant A cannot read Tenant B data"),
    q("Enterprise Architecture Review Process", "Enterprise", "Very Common",
      "Describe a structured enterprise architecture review process before production approval.",
      "Enterprise review process: tiered intake → pre-read package (C4, ADRs, NFR matrix, threat summary) → facilitated review meeting or async approval → checklist sign-off → production gate. Outputs are documented decisions, waivers with expiry, or required changes — not informal verbal OK.",
      "**Review package contents:**\n1. Context + container C4 diagrams\n2. ADRs for significant decisions (linked, Accepted status)\n3. NFR matrix (latency, availability, RTO/RPO, cost)\n4. STRIDE threat model summary\n5. Cost estimate with FinOps tags\n6. Migration/rollback and runbook outline\n\n**Process flow:**\n```\nTeam submits package → Tier classification → Async pre-review (security, data)\n    → Review meeting (Tier-0) or delegate approval (Tier-1)\n    → Checklist sign-off recorded in PR/ticket\n    → Production deploy authorized\n```\n\n**Checklist categories:** Requirements traceability, security, data classification, reliability, observability, operations, cost, governance.\n\n**Facilitation:** Time-boxed agenda — presenter 15 min, structured Q&A, action items with owners. Conflict escalates to architecture board.\n\n**Architect:** Tiered process ensures Tier-0 rigor without making every team wait weeks for internal tool approval.",
      "Enterprise review process makes quality repeatable — architects design tiers, checklists, and artifacts.",
      "Pre-review vs full review? — Pre-review at RFC stage catches issues early; full review at production gate.",
      "Waivers? — Documented exception with expiry, compensating controls, executive sponsor.",
      "Verbal VP approval with no recorded sign-off",
      "Same heavyweight checklist for POC and payment system",
      "Security not involved in external-facing API review"),
]

ALL_WEEKS_41_44_Q001_Q005 = {
    41: WEEK_41_Q001_Q005,
    42: WEEK_42_Q001_Q005,
    43: WEEK_43_Q001_Q005,
    44: WEEK_44_Q001_Q005,
}
