"""Hand-crafted premium Q001–Q010 for Azure weeks 9–16."""

from premium_qa_data import q

WEEK_9 = [
    q("Azure Well-Architected Framework", "Azure WAF", "Very Common",
      "What are the five WAF pillars and how do you use them in an architecture review?",
      "Reliability, Security, Cost Optimization, Operational Excellence, Performance Efficiency. I score each design decision against all five and prioritize gaps by business risk.",
      "The Azure WAF pillars guide trade-off conversations:\n\n1. **Reliability** — HA, DR, autoscale, health probes\n2. **Security** — identity, encryption, network isolation, Defender\n3. **Cost Optimization** — right-sizing, reservations, tagging, lifecycle policies\n4. **Operational Excellence** — IaC, monitoring, runbooks, CI/CD\n5. **Performance Efficiency** — caching, CDN, appropriate SKU, async I/O\n\n**Review process:** For each component, ask which pillar it serves and which pillar might be neglected. Payment API: Security + Reliability first; internal admin tool: Cost + Operational Excellence may lead.\n\nDocument findings in architecture review template — not just verbal opinions.",
      "Interviewers want structured reviews, not random service name drops.",
      "Sixth pillar sustainability? — Azure adds sustainability — consider carbon footprint for large estates.",
      "WAF vs CAF? — WAF optimizes workloads; CAF guides cloud adoption journey.",
      "Naming services without pillar mapping",
      "Security-only reviews ignoring cost",
      "No prioritized remediation list"),
    q("Subscription and Management Group Strategy", "Governance", "Very Common",
      "Design Azure subscriptions for 5 product teams with SOC 2 requirements.",
      "Management groups: Platform (connectivity, identity) + Application (workloads). Per team: prod and nonprod subscriptions. Separate security/audit subscription. Policy at MG level.",
      "**Hierarchy example:**\n```\nRoot MG\n├── Platform MG (sub-connectivity, sub-management)\n└── Application MG\n    ├── Team A (sub-prod, sub-nonprod)\n    └── Team B (sub-prod, sub-nonprod)\n```\n\n**SOC 2 drivers:** audit log retention subscription, deny public endpoints via policy, break-glass admin separate from daily ops.\n\n**Architect:** Subscription = blast radius + billing boundary. Not one sub per microservice — operational overhead.",
      "Subscription design is day-one architect decision — painful to fix later.",
      "How many subscriptions? — Enough for isolation, not so many nobody can manage.",
      "Enterprise Agreement vs MCA billing? — Affects invoice structure not technical design.",
      "Single subscription for all prod workloads",
      "No nonprod isolation",
      "Policies only at resource group level"),
    q("Azure Policy vs RBAC", "Governance", "Very Common",
      "Difference between Azure Policy and RBAC? Give examples of each.",
      "RBAC: who can do what (Authorization). Policy: what is allowed in environment regardless of who (Governance guardrails).",
      "**RBAC:** 'Dev team Contributor on nonprod RG' — they can deploy VMs if policy allows.\n\n**Policy:** 'Deny creation of VMs without tag Environment' — applies even to Owner.\n\n**Combine:** Least privilege RBAC + deny policies for compliance (no public SQL, required tags, allowed regions only).\n\n**Architect:** Policy initiatives bundle related policies — 'SOC2 baseline' assigned to prod MG.",
      "Confusing Policy and RBAC is common interview failure.",
      "Policy effect types? — Deny, Audit, DeployIfNotExists, Modify.",
      "Blueprint vs Bicep stack? — Blueprints legacy; template specs + Bicep for landing zones now.",
      "Using RBAC alone for compliance",
      "Policy without exemption process",
      "Contributor on subscription for developers"),
    q("Regions and Availability Zones", "Reliability", "Very Common",
      "When deploy zone-redundant vs single-zone? Cost trade-off?",
      "Zone-redundant for 99.99% SLA on critical paths (App Service Premium v3, SQL zone redundant, AKS across AZs). Single-zone for dev and non-critical internal tools.",
      "**Availability Zone:** separate datacenters within region — protects datacenter failure.\n\n**Region pair:** DR geography — async replication for DR (not same as AZ).\n\n**Cost:** Zone-redundant SKUs ~1.5-2x compute; worth it for revenue-critical workloads.\n\n**Architect:** Document SLA math — 99.95% App Service ≈ 22 min/month downtime; zone-redundant improves within region.",
      "AZ vs region confusion fails senior interviews.",
      "Region pairs and DR? — Paired region for Microsoft's DR recommendations — not automatic failover.",
      "Sovereign clouds? — Azure Government/China — separate regions and compliance.",
      "Single zone for production payment API",
      "Confusing region with availability zone",
      "No DR plan because 'Azure is reliable'"),
    q("Cloud Adoption Framework (CAF)", "CAF", "Common",
      "Summarize CAF methodology stages for enterprise Azure migration.",
      "Strategy → Plan → Ready → Adopt → Govern → Manage. Architects lead Ready (landing zone) and Govern; Adopt is iterative migration waves.",
      "**Ready:** Deploy platform landing zone — networking, identity, policy, monitoring.\n**Adopt:** Migrate workloads in waves — assess, migrate, optimize.\n**Govern:** Policy, cost, security baselines ongoing.\n\n**Architect deliverable:** Migration plan with wave prioritization by risk and business value — not big-bang.",
      "CAF shows you know enterprise adoption beyond single-app deploy.",
      "Assess phase tools? — Azure Migrate for discovery and sizing.",
      "Innovate vs Migrate? — Modernize during migrate vs lift-and-shift — document per workload.",
      "Skip landing zone — deploy apps directly",
      "No wave plan — migrate everything at once",
      "Govern only after everything deployed"),
    q("Resource Tagging Strategy", "FinOps", "Very Common",
      "Mandatory tags for enterprise Azure? How enforce?",
      "Environment, CostCenter, Owner, Application (minimum). Enforce via Azure Policy deny deploy without tags. FinOps reports by CostCenter.",
      "**Implementation:**\n```json\n// Policy: require tag Environment on resource groups\n```\n\n**Architect:** Tag at resource group inheritance where possible. Automation runbook fixes drift. Monthly untagged resource report to owners.\n\nTags drive chargeback, automation (shutdown dev nights), and incident routing.",
      "Tags are architect-level FinOps foundation.",
      "Inherited tags from RG? — Prefer RG-level tags applied to resources.",
      "Case sensitivity? — Tag keys case-sensitive — standardize casing doc.",
      "Optional tags nobody fills",
      "No policy enforcement",
      "Tags only for cost — ignore Owner for incidents"),
    q("Azure Landing Zone", "Landing Zone", "Very Common",
      "Platform landing zone vs application landing zone?",
      "Platform LZ: shared connectivity, DNS, firewall, identity, monitoring — central platform team. Application LZ: workload-specific subscriptions inheriting platform policies.",
      "**Platform provides:** Hub VNet, ExpressRoute gateway, Entra ID integration, Log Analytics workspace, Policy assignments.\n\n**Application team gets:** Spoke subscription, deploy App Service/SQL with guardrails.\n\n**Architect:** Start from [Azure landing zone accelerator](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/) — customize don't reinvent.",
      "Landing zone vocabulary expected in Azure architect interviews.",
      "Terraform vs Bicep for LZ? — Team skill; Bicep native for Azure-only.",
      "Brownfield landing zone? — Retrofit policies and networking on existing estate.",
      "Every team builds own hub VNet",
      "No shared monitoring workspace",
      "Landing zone as one-time project never updated"),
    q("Azure RBAC Custom Roles", "Security", "Common",
      "When create custom RBAC role vs built-in?",
      "Custom when built-in too broad (Contributor) or too narrow. CI/CD deploy role: deploy App Service + read Key Vault secrets — not full Contributor.",
      "**Pattern:** `Deploy-AppService-Prod` custom role at resource group scope for pipeline SP.\n\n**Principle:** Least privilege per workload. Use [custom role definition](https://learn.microsoft.com/azure/role-based-access-control/custom-roles) in Bicep.\n\n**PIM:** Just-in-time elevation for admin roles — reduce standing access.",
      "Custom roles show production Azure governance experience.",
      "Role assignment scope? — Narrowest scope possible — RG not subscription.",
      "Managed identity RBAC? — Grant MI access to Key Vault/SQL — no secrets in pipeline.",
      "Contributor for CI/CD service principal",
      "Owner for developers on prod",
      "No PIM for subscription admins"),
    q("Cost Management and Budgets", "FinOps", "Common",
      "Prevent surprise Azure bill for new product team?",
      "Budget alerts at 80%/100%, cost allocation tags, dev environment auto-shutdown, right-size recommendations review monthly, Azure Reservations for stable baseline.",
      "**Architect onboarding checklist:**\n- Budget on subscription\n- Policy: deny expensive SKUs in nonprod\n- Log Analytics daily cap\n- Review Advisor cost recommendations\n\n**Unit economics:** Track $/transaction as feature scales.",
      "FinOps is architect responsibility from day one.",
      "Cost anomaly detection? — Smart alerts on unusual spend patterns.",
      "DevTest subscription benefit? — Reduced rates for nonprod — use where eligible.",
      "No budget alerts",
      "Production SKUs in dev subscriptions",
      "Verbose logging to Log Analytics unbounded"),
    q("Choose Azure vs On-Premises", "Strategy", "Common",
      "Stakeholder asks 'why cloud?' — architect response framework?",
      "FARCS: Flexibility, Availability, Recovery, Cost (TCO over 3-5 years), Security (shared responsibility). Not 'cloud is always cheaper' — honest TCO with ops labor.",
      "**When Azure wins:** Variable scale, global reach, managed PaaS reduces ops, rapid experimentation.\n\n**When hybrid/on-prem:** Strict latency to factory floor, existing sunk datacenter cost, regulatory constraints.\n\n**Architect:** Hybrid common — Azure Arc for governance across environments.",
      "Balanced cloud advocacy impresses executives.",
      "Repatriation trend? — Some workloads move back — architect stays workload-driven.",
      "Egress cost in TCO? — Model data transfer out — often underestimated.",
      "Cloud lift without ops model change",
      "Ignoring egress and support costs in TCO",
      "100% cloud mandate without exception process"),
]

WEEK_10 = [
    q("App Service vs Azure Functions", "Compute", "Very Common",
      "When App Service vs Functions for .NET HTTP API?",
      "App Service: always-on APIs, WebSockets, long requests, predictable traffic. Functions: event-driven, spiky, short-lived, pay-per-execution.",
      "**App Service:** full ASP.NET Core, deployment slots, Always On, VNet integration.\n\n**Functions:** trigger-based (HTTP, Queue, Timer), consumption plan cold starts, Premium plan for pre-warmed.\n\n**Architect:** Default App Service for primary REST API; Functions for async processors and webhooks.",
      "Compute choice drives ops model and cost profile.",
      "Container Apps vs App Service? — Microservices with scale-to-zero — Container Apps.",
      "Premium Functions plan? — When cold start unacceptable.",
      "Functions for main CRUD API with steady traffic",
      "App Service Consumption tier confusion",
      "Ignoring cold start on user-facing HTTP"),
    q("AKS vs App Service Decision", "Compute", "Very Common",
      "Team wants Kubernetes. You have 3 microservices and 4 developers. Recommendation?",
      "App Service or Container Apps first — AKS when team has K8s ops skill, 10+ services, or need portable K8s APIs. AKS ops burden real for small teams.",
      "**AKS when:** custom networking, service mesh, multi-cloud K8s, GPU workloads.\n\n**App Service when:** .NET APIs, fast path to prod, built-in slots and autoscale.\n\n**Architect:** Honest TCO — AKS needs platform team or managed add-ons (Istio, monitoring).",
      "Right-sizing platform complexity is core architect judgment.",
      "AKS Automatic? — Reduced ops for node management — evaluate preview/GA status.",
      "Web App for Containers? — Middle ground — containers without full K8s.",
      "AKS for resume on 3-service system",
      "No observability plan for K8s",
      "Ignoring control plane cost"),
    q("Deployment Slots", "DevOps", "Very Common",
      "Explain App Service deployment slots for zero-downtime release.",
      "Staging slot runs new version; warm up; swap with production — instant traffic flip. Rollback = swap back.",
      "**Best practices:**\n- Slot settings sticky (connection strings per slot)\n- Run smoke tests on staging\n- Auto-swap with webhook on CI success\n\n**Architect:** Slots cheaper than blue/green second App Service. Pair with feature flags for release decoupling.",
      "Slots are Azure PaaS advantage architects should mandate.",
      "Slot swap what travels? — Content swaps; some settings sticky per config.",
      "Database migration with slot? — Backward-compatible migrations only during swap.",
      "Deploy direct to production",
      "Swap without staging warm-up",
      "Breaking schema change during swap"),
    q("Autoscale Rules for App Service", "Scale", "Common",
      "Configure autoscale for .NET API — what metrics?",
      "Scale on CPU > 70%, HTTP queue length, or custom App Insights metric (requests/sec). Scale-in cooldown 5+ min to prevent flapping.",
      "**Example:** Min 2 instances prod (HA), max 10, scale out +1 when CPU > 70% for 5 min.\n\n**Architect:** Load test to find saturation point — don't scale on CPU alone if I/O bound.",
      "Autoscale policy is architecture not just ops config.",
      "Schedule-based scale? — Scale up before business hours — predictable traffic.",
      "Per-instance connection limits? — Scale before connection exhaustion.",
      "Min 1 instance production HA",
      "Instant scale-in on brief CPU dip",
      "No load test before max instance setting"),
    q("Azure Functions Cold Start", "Serverless", "Common",
      "Mitigate cold start for latency-sensitive Functions?",
      "Premium plan with pre-warmed instances, always-ready instances count > 0, minimize assembly size, Native AOT where supported, avoid huge DI graph.",
      "**Consumption plan:** cold start 1-10+ seconds .NET — unacceptable for sync user API.\n\n**Architect:** Profile with Application Insights dependency tracking. Consider minimum instances on Premium or move to App Service.",
      "Cold start is common Functions interview topic.",
      "Durable Functions cold start? — Orchestrator replay — separate consideration.",
      "Place function in VNet? — Premium required — adds cold start complexity.",
      "Consumption plan for checkout API",
      "Ignore startup trace in App Insights",
      "500MB deployment package"),
    q("Container Apps on Azure", "Containers", "Common",
      "When Azure Container Apps vs AKS?",
      "Container Apps: serverless containers, KEDA scale, simpler ops, internal ingress. AKS: full K8s control, service mesh, complex networking.",
      "**Container Apps:** microservices with scale-to-zero, Dapr built-in, revision management.\n\n**Architect:** Container Apps for team without K8s expertise; AKS when need full Kubernetes API.",
      "Container Apps fills gap between App Service and AKS.",
      "Dapr sidecar? — Service invocation, pub/sub, state — reduces custom glue code.",
      "Consumption vs dedicated? — Dedicated for predictable performance isolation.",
      "AKS for 2 container microservices",
      "No revision management strategy",
      "Public ingress without WAF"),
    q("App Service VNet Integration", "Networking", "Common",
      "Why integrate App Service with VNet?",
      "Reach private resources: SQL with private endpoint, internal APIs, on-prem via ExpressRoute. Outbound traffic through VNet for network isolation.",
      "**Regional VNet Integration:** outbound to VNet. **Private Endpoint:** inbound to App Service.\n\n**Architect:** Production APIs accessing private SQL must use VNet integration + private DNS zones.",
      "Networking integration is production App Service requirement.",
      "DNS resolution in VNet? — Azure DNS private resolver or custom DNS.",
      "NSG on integration subnet? — Required for App Service outbound.",
      "Public SQL connection string from App Service prod",
      "Forget private DNS for private endpoint",
      "All traffic public internet"),
    q("Managed Identity for App Service", "Identity", "Very Common",
      "Connect App Service to Key Vault and SQL without secrets?",
      "Enable system-assigned managed identity on App Service. Grant MI access to Key Vault (RBAC) and SQL (Entra auth). Reference secrets via Key Vault references in app settings.",
      "**No secrets in appsettings.json in repo.** CI/CD uses federated credential OIDC — not SP password.\n\n**Architect:** Standard template for all App Services in platform.",
      "Managed identity is non-negotiable for modern Azure apps.",
      "User-assigned vs system-assigned? — User-assigned shared across slots/resources.",
      "DefaultAzureCredential chain? — Local dev uses VS credentials; prod uses MI.",
      "Connection string with SQL password in config",
      "SP client secret in GitHub Actions",
      "MI without RBAC on Key Vault"),
    q("App Service Plan Sizing", "Cost", "Common",
      "Choose App Service Plan SKU for 2K RPS .NET API?",
      "Load test first. Start P1v3 (2 cores) × 2 instances, scale out. Premium v3 for deployment slots and autoscale. Isolated only for compliance isolation needs.",
      "**Tiers:** Free/Shared dev only. Basic no slots. Standard slots. Premium v3 zone balance + autoscale.\n\n**Architect:** Right-size with load test — P2v3 vs P1v3 × 2 often similar cost, better HA.",
      "SKU choice affects SLA and features — not just CPU.",
      "Linux vs Windows plan? — .NET 8 Linux often preferred cost/perf.",
      "Reserved instances on ASP? — 1-3 year commit for stable baseline.",
      "Premium for dev environment waste",
      "Single instance production",
      "No load test before SKU selection"),
    q("Multi-Region App Service", "Reliability", "Common",
      "Design multi-region active-active for App Service API.",
      "Front Door or Traffic Manager → regional App Services. Session state external (Redis). SQL geo-replication or Cosmos multi-region. Health probes per region.",
      "**Challenges:** Data consistency across regions, deployment coordination, config drift.\n\n**Architect:** Active-passive simpler for relational data; active-active for read-heavy stateless APIs.",
      "Multi-region is reliability architecture with data trade-offs.",
      "Front Door vs Traffic Manager? — Front Door L7 + WAF; TM DNS-level.",
      "Sticky sessions multi-region? — Prefer external session store.",
      "Active-active without data strategy",
      "Deploy regions manually divergent",
      "No health probe on Front Door"),
]

# Weeks 11-16

WEEK_11 = [
    q("Azure SQL Database vs Cosmos DB", "Data", "Very Common",
      "Choose Azure SQL or Cosmos DB for multi-tenant SaaS orders and catalog?",
      "SQL for orders — ACID, transactions, complex queries. Cosmos for catalog — global distribution, flexible schema, high read scale with partition key design.",
      "**Orders:** relational integrity, foreign keys (within service), T-SQL reporting.\n\n**Catalog:** `tenantId` + `productId` partition key, session consistency, multi-region reads.\n\n**Architect:** Polyglot persistence per bounded context — not one database for everything.",
      "Data store per workload is architect interview staple.",
      "Hyperscale SQL when? — Large OLTP >4TB, fast scale requirements.",
      "Cosmos serverless? — Dev/test and unpredictable traffic.",
      "Cosmos for financial transactions needing ACID",
      "SQL for global 1M RPS reads without design",
      "No partition key design before Cosmos"),
    q("Cosmos DB Partition Key Design", "Cosmos DB", "Very Common",
      "Design partition key for multi-tenant SaaS in Cosmos DB.",
      "`tenantId` — co-locate tenant data, efficient tenant-scoped queries. Avoid low-cardinality keys (`status`) — hot partitions.",
      "**Rules:**\n- High cardinality\n- Include in most queries\n- Even distribution — watch for large tenants (dedicated partition or sub-shard)\n\n**RU/s:** Hot partition causes 429 throttling on single partition limit (20GB, 10K RU/s max per partition).",
      "Bad partition key causes unfixable scale ceiling.",
      "Synthetic partition key? — `tenantId + hash bucket` for mega-tenants.",
      "Cross-partition query cost? — Expensive — design to avoid.",
      "Partition key you cannot query by",
      "/id as partition key on high volume",
      "No 429 monitoring"),
    q("Azure SQL HA and DR", "SQL", "Very Common",
      "RPO/RTO for Azure SQL production?",
      "Active geo-replication: readable secondaries, manual failover RPO ~5s. Auto-failover groups: RPO ~5s automated. Zone-redundant for HA within region.",
      "**Architect documents:**\n- HA: zone redundant or geo-secondary same region pair\n- DR: failover group to paired region\n- App: retry transient errors, `MultiSubnetFailover=True`\n\nTest failover quarterly.",
      "SQL HA options map directly to SLA promises.",
      "Hyperscale HA? — Different architecture — read replicas, fast scale.",
      "Backup retention? — LTR for compliance — 7-10 years some industries.",
      "Single database no geo-replica prod",
      "Never tested failover",
      "Assume geo-replica RPO=0"),
    q("Blob Storage Tiers and Lifecycle", "Storage", "Common",
      "Design blob lifecycle for 7-year audit log retention.",
      "Hot 30 days → Cool 90 days → Cold 1 year → Archive 7 years. Lifecycle management policy automated. Immutable storage for compliance if required.",
      "**Cost:** Archive cheapest, retrieval cost high — right for audit rarely accessed.\n\n**Architect:** Lifecycle policies in IaC — Bicep `Microsoft.Storage/storageAccounts/blobServices`.\n\nImmutable blob storage (WORM) for regulatory immutability.",
      "Storage tiering is FinOps architecture.",
      "Versioning enabled? — Protect against overwrite — cost consideration.",
      "Soft delete? — Recover accidental deletion — enable prod.",
      "All data Hot tier forever",
      "No lifecycle policy automation",
      "Archive for frequently accessed reports"),
    q("DTU vs vCore SQL Model", "SQL", "Common",
      "DTU vs vCore for Azure SQL?",
      "vCore: production — predictable CPU/memory, Hyperscale, reserved capacity. DTU: simple bundled model, dev/test, small databases.",
      "**Architect:** Standardize on vCore for prod in enterprise. DTU acceptable dev.\n\n**Elastic pool:** Many small databases share resources — SaaS with many tenant DBs.",
      "Model choice affects scaling and cost transparency.",
      "Serverless SQL? — Intermittent workloads — auto-pause dev.",
      "Reserved vCore? — 1-3 year for baseline production.",
      "DTU prod without cost analysis",
      "Wrong pool eDTU sizing",
      "No performance baseline before purchase"),
    q("Synapse vs SQL for Analytics", "Analytics", "Common",
      "Operational reporting: SQL read replica or Synapse?",
      "Read replica or columnstore on SQL for moderate reporting. Synapse dedicated pool for large-scale DW, complex aggregations, data lake integration.",
      "**Architect:** Don't run heavy analytics on OLTP primary — replica or separate DW path.\n\n**Modern:** Export to Data Lake (Parquet) → Synapse serverless SQL or Fabric.",
      "Analytics path protects OLTP.",
      "CDC to data lake? — Near real-time analytics pipeline.",
      "Power BI DirectQuery vs Import? — Scale and freshness trade-off.",
      "Heavy reports on primary OLTP",
      "Synapse for simple 10GB reporting",
      "No data pipeline ownership"),
    q("Event Hubs vs Service Bus for Ingestion", "Streaming", "Common",
      "10M telemetry events/day — Event Hubs or Service Bus?",
      "Event Hubs for high-volume streaming ingest (Kafka protocol). Service Bus for business messages, transactions, lower volume, sessions.",
      "**Event Hubs:** partitions, retention, stream analytics, Kafka ecosystem.\n\n**Service Bus:** queues/topics, dead letter, duplicate detection, lower latency messaging patterns.",
      "Right messaging tech prevents re-platforming.",
      "Capture to Data Lake? — Event Hubs archive feature.",
      "Partition count Event Hubs? — Throughput units — plan upfront.",
      "Service Bus for million events/sec",
      "Event Hubs for order payment commands",
      "No consumer scaling plan"),
    q("Elastic Pools for SaaS", "SQL", "Common",
      "1000 small tenant databases — elastic pool strategy?",
      "Elastic pool shares eDTU/vCore across DBs — cost efficient when tenants don't peak simultaneously. Monitor pool DTU utilization.",
      "**Per-tenant DB:** isolation, easy export/delete tenant. **Shared DB with RLS:** fewer DBs, harder isolation.\n\n**Architect:** Per-tenant DB in pool for B2B SaaS with compliance per tenant.",
      "SaaS data architecture common scenario.",
      "Pool exhaustion? — Move hot tenant to own pool or single DB.",
      "Geo-replication elastic pool? — Secondary pool in DR region.",
      "1000 separate servers",
      "Single shared table without RLS",
      "No pool utilization monitoring"),
    q("Data Encryption on Azure", "Security", "Common",
      "TDE vs customer-managed keys for healthcare data?",
      "TDE with Microsoft-managed keys default. CMK (Key Vault) when compliance requires customer key control, key rotation audit, crypto-officer separation.",
      "**Layer:** encryption at rest (TDE), in transit (TLS), column-level Always Encrypted for sensitive fields (SSN).\n\n**Architect:** CMK adds ops — Key Vault availability becomes data availability.",
      "Encryption choices are compliance architecture.",
      "Always Encrypted? — Client-side encryption — DBA cannot read.",
      "Double encryption? — Infrastructure + CMK — defense in depth.",
      "CMK without HA Key Vault plan",
      "No TLS on internal connections",
      "PII in plain text columns"),
    q("Polyglot Data on Azure Reference", "Architecture", "Common",
      "Draw data stores for e-commerce on Azure.",
      "SQL: orders/payments. Cosmos: product catalog global. Redis: cart/sessions. Blob: images. Event Hubs: clickstream. Synapse: analytics.",
      "Each store owns bounded context. Sync via events — not distributed JOINs.\n\n**Integration:** Service Bus domain events, CDC to warehouse.",
      "Reference architecture synthesis question.",
      "Cache aside Redis? — Product pages — TTL + invalidation on update event.",
      "Search? — Azure AI Search index from catalog events.",
      "One SQL database for everything",
      "Cosmos and SQL joined in app",
      "No event-driven sync"),
]

WEEK_12 = [
    q("Entra ID vs Active Directory", "Identity", "Very Common",
      "Explain Entra ID role in Azure architecture vs on-prem AD.",
      "Entra ID: cloud identity provider — users, apps, SSO, Conditional Access. AD DS on VM: legacy LDAP/Kerberos apps. Sync hybrid with Entra Connect for many enterprises.",
      "**Modern apps:** OAuth/OIDC with Entra ID. **Legacy:** AD DS lift or extend.\n\n**Architect:** New apps use Entra — no new AD DS unless required.",
      "Identity foundation for all Azure designs.",
      "Entra Domain Services? — Managed AD-compatible — lift legacy LDAP apps.",
      "B2C vs workforce? — Separate tenant for consumer identities.",
      "New apps authenticating to on-prem AD directly",
      "No Conditional Access on admin accounts",
      "Shared break-glass without procedure"),
    q("Managed Identity Types", "Identity", "Very Common",
      "System-assigned vs user-assigned managed identity?",
      "System-assigned: lifecycle tied to resource — deleted with App Service. User-assigned: independent, shared across resources (slots, functions).",
      "**Use user-assigned:** same identity across deployment slot swap, multiple apps sharing access.\n\n**Architect:** Default system-assigned for single app; user-assigned for complex slot/failover scenarios.",
      "MI eliminates secrets — architect standard.",
      "MI across subscriptions? — Possible with RBAC — cross-subscription grants.",
      "Local dev without secrets? — DefaultAzureCredential — dev uses VS/Azure CLI.",
      "SQL connection string password in Key Vault only — still a secret to rotate",
      "No MI on CI/CD — long-lived SP secret",
      "MI with excessive RBAC scope"),
    q("OAuth 2.0 Flows on Azure", "Identity", "Very Common",
      "Which OAuth flow for SPA, mobile, and service-to-service?",
      "SPA/mobile: Authorization Code + PKCE. Service-to-service: Client Credentials. User context to downstream API: On-Behalf-Of (OBO).",
      "**Never:** implicit flow (deprecated). **API permissions:** least privilege app registration scopes.\n\n**Architect:** APIM validates JWT at edge; services validate audience and issuer.",
      "OAuth flow selection is security architecture.",
      "PKCE why? — Public clients cannot store secret — code challenge prevents interception.",
      "Client secret in mobile app? — Never — use PKCE or native broker.",
      "Implicit flow for new SPA",
      "ROPC password grant",
      "No audience validation on API"),
    q("Conditional Access Policies", "Security", "Very Common",
      "Design Conditional Access for production admin access.",
      "Require MFA, compliant device, block legacy auth, sign-in risk medium+ requires MFA, block non-trusted locations for admins.",
      "**Break-glass accounts:** excluded from CA with monitoring alerts on usage.\n\n**Architect:** CA is Zero Trust enforcement layer — document policies per persona (admin, developer, external).",
      "CA policies are production security baseline.",
      "Report-only mode? — Test policy impact before enforcement.",
      "Continuous access evaluation? — Revoke session when risk changes.",
      "No MFA on global admin",
      "CA not applied to service principals appropriately",
      "Break-glass unmonitored"),
    q("Key Vault Architecture", "Security", "Very Common",
      "Design Key Vault for 10 microservices.",
      "Separate vault per environment (prod/nonprod). RBAC not legacy access policies. Soft delete + purge protection prod. References in App Service config.",
      "**Secrets rotation:** automated rotation for SQL passwords, cert renewal alerts.\n\n**Architect:** No secrets in Git — Key Vault references + MI. Pipeline OIDC for deployment secrets.",
      "Key Vault design prevents secret sprawl.",
      "Private endpoint Key Vault? — Required for network-isolated workloads.",
      "HSM-backed keys? — Regulatory requirements — Premium SKU.",
      "One vault all environments",
      "Secrets copied to appsettings",
      "No purge protection — ransomware deletes vault"),
    q("App Registration vs Enterprise App", "Identity", "Common",
      "Difference in Entra app registration?",
      "App registration: definition (client ID, permissions, redirect URIs). Enterprise application: instance in tenant (assignment, SSO config, consent).",
      "**Multi-tenant SaaS:** one registration, enterprise apps per customer tenant.\n\n**Architect:** Document app registration ownership and secret rotation owners.",
      "Entra app model clarity shows identity depth.",
      "API permissions delegated vs application? — User context vs app-only.",
      "Admin consent workflow? — Required for application permissions.",
      "Permissions not granted after registration",
      "Confuse audience in token",
      "Over-scoped Microsoft Graph permissions"),
    q("On-Behalf-Of Flow", "Identity", "Common",
      "API A calls API B on behalf of user — pattern?",
      "OBO: Client gets user token for API A; API A exchanges for token to API B with user context preserved via `acquireTokenOnBehalfOf`.",
      "**Use when:** downstream API needs user identity/permissions.\n\n**Client credentials when:** background job without user — no OBO.",
      "OBO is common microservices identity pattern.",
      "Token cache OBO? — MSAL serializable cache — avoid token request per call.",
      "Chained OBO depth? — Limit chain — latency and consent complexity.",
      "Pass user JWT to downstream without validation",
      "Client credentials when user context needed",
      "Infinite OBO chain"),
    q("Key Vault Reference in App Service", "Configuration", "Common",
      "How reference Key Vault secret in App Service without code change?",
      "`@Microsoft.KeyVault(SecretUri=https://vault.vault.azure.net/secrets/name/)` in app setting. App Service MI needs GET secret permission.",
      "**Rotation:** update secret version — restart or refresh depending on config.\n\n**Architect:** Bicep deploys references — no manual portal config.",
      "Configuration externalization best practice.",
      "Slot setting sticky with KV ref? — Per-slot secrets for staging vs prod.",
      "Managed identity required? — Yes for reference resolution.",
      "Secret value pasted in app setting",
      "KV reference without MI permission",
      "No rotation process"),
    q("Zero Trust on Azure", "Security", "Common",
      "Implement Zero Trust principles on Azure landing zone?",
      "Verify explicitly (CA, MFA), least privilege (RBAC, PIM), assume breach (segment networks, Private Link, Defender, Sentinel).",
      "**Network:** no public PaaS endpoints — private endpoints. **Identity:** managed identities over secrets. **Monitor:** Sentinel analytics, Defender alerts.",
      "Zero Trust is architecture philosophy not one product.",
      "Micro-segmentation? — NSG + Azure Firewall application rules.",
      "Just-in-time VM access? — Defender for Cloud JIT.",
      "Flat network all resources public",
      "VPN as only security boundary",
      "Standing global admin access"),
    q("Identity for CI/CD Pipelines", "DevOps", "Very Common",
      "GitHub Actions deploy to Azure without client secret?",
      "OIDC federated credential on app registration — GitHub workflow requests token from Entra, deploys with RBAC-scoped role.",
      "**Setup:** `azure/login@v2` with `client-id`, `tenant-id`, `subscription-id`, federated token.\n\n**Architect:** Ban long-lived SP secrets in GitHub — enforce OIDC in platform template.",
      "Pipeline identity is security-critical architect decision.",
      "Workload identity federation? — Same pattern Azure DevOps and other CI.",
      "Scope deploy role? — Resource group level custom role — not subscription Owner.",
      "SP secret in GitHub secrets 2 years old",
      "Owner role for pipeline",
      "No branch protection on workflow files"),
]

WEEK_13 = [
    q("Hub-Spoke Network Topology", "Networking", "Very Common",
      "Design hub-spoke for 3 application teams on Azure.",
      "Hub: firewall, VPN/ExpressRoute gateway, DNS, optional Bastion. Spokes: team VNets peered to hub — no spoke-to-spoke without hub.",
      "**Traffic:** spoke → hub firewall → internet or on-prem. **UDR:** default route 0.0.0.0/0 to firewall private IP.\n\n**Architect:** Azure Firewall or NVA in hub — centralized egress control and logging.",
      "Hub-spoke is enterprise Azure networking default.",
      "VWAN vs manual hub? — Virtual WAN simplifies many spokes at scale.",
      "Peering transitive? — Non-transitive — spoke cannot reach spoke direct.",
      "Full mesh spoke peering chaos",
      "No centralized egress filtering",
      "Overlapping IP address spaces"),
    q("Private Link vs Service Endpoints", "Networking", "Very Common",
      "Private Endpoint vs Service Endpoint for Azure SQL?",
      "Private Endpoint: SQL gets private IP in your VNet, traffic stays private, strongest isolation. Service Endpoint: route to Azure backbone, simpler, less isolation.",
      "**Architect prod default:** Private Link for SQL, Storage, Key Vault.\n\n**DNS:** private DNS zone `privatelink.database.windows.net` linked to VNet.",
      "Private Link is interview answer for secure PaaS access.",
      "DNS private resolver? — Hybrid DNS resolution for on-prem.",
      "Dual-stack? — Private endpoint for inbound, service endpoint legacy — prefer PE.",
      "Public SQL endpoint prod",
      "Private endpoint without DNS zone",
      "Assume service endpoint stops all exfiltration"),
    q("Application Gateway vs Azure Front Door", "Networking", "Very Common",
      "Regional App Gateway vs global Front Door?",
      "App Gateway: regional L7 load balancer + WAF, VMs/internal apps in one region. Front Door: global anycast, multi-region, CDN-like edge, global WAF.",
      "**Pattern:** Front Door → regional App Gateway/App Service for global users + regional origin.\n\n**Architect:** Front Door for internet-facing multi-region; App Gateway for hub VNet internal apps.",
      "L7 product selection maps to user geography.",
      "WAF mode? — Detection then prevention after tuning false positives.",
      "SSL termination? — At edge — certificate management at Front Door.",
      "App Gateway for global users single region",
      "No WAF on public endpoints",
      "Wrong tier WAF (regional vs global)"),
    q("Network Security Groups", "Security", "Common",
      "NSG design for 3-tier app (web, app, data)?",
      "Web subnet: allow 443 inbound from App Gateway/Front Door. App subnet: allow from web only. Data subnet: allow SQL port from app only. Deny all else implicit.",
      "**Micro-segmentation:** NSG + ASG (application security groups) for cleaner rules — `WebServers` ASG to `AppServers` ASG port 443.\n\n**Architect:** Default deny mindset — explicit allow rules only.",
      "NSG rules are defense in depth.",
      "NSG flow logs? — Send to Log Analytics — traffic analysis.",
      "Service tags? — `Sql`, `Storage` — simplify PaaS rules.",
      "Allow all internal VNet inbound",
      "NSG on subnet and NIC conflicting",
      "No logging on deny rules"),
    q("ExpressRoute vs VPN", "Hybrid", "Common",
      "Connect on-prem datacenter to Azure — VPN or ExpressRoute?",
      "VPN: quick, lower cost, internet/IPsec — moderate bandwidth. ExpressRoute: dedicated private connection, predictable latency, higher bandwidth, compliance.",
      "**Architect:** VPN for pilot/dev hybrid. ExpressRoute production with redundant circuits (provider diversity).\n\n**ExpressRoute Gateway:** required in hub VNet.",
      "Hybrid connectivity is common enterprise requirement.",
      "ExpressRoute FastPath? — Data plane bypass gateway for performance.",
      "Dual VPN active-active? — Possible for resilience — lower than ER.",
      "Single VPN circuit production no backup",
      "No bandwidth planning",
      "Assume ExpressRoute immune to outages"),
    q("Azure DNS Private Zones", "DNS", "Common",
      "Why private DNS zone for private endpoints?",
      "Public DNS resolves SQL to public IP. Private zone linked to VNet resolves `sqlserver.database.windows.net` to private IP — apps use same connection string name.",
      "**Split-horizon:** different resolution internal vs external.\n\n**Architect:** Central DNS zone in hub, linked to all spokes.",
      "DNS is overlooked until private link breaks apps.",
      "Auto-registration? — VM DNS in Azure — private zones manual A records or auto.",
      "Conditional forwarding? — On-prem DNS forward Azure private zones.",
      "Private endpoint without DNS config",
      "Hardcode private IPs in connection strings",
      "Forget hub-spoke DNS linking"),
    q("User-Defined Routes", "Routing", "Common",
      "Force all spoke internet egress through hub firewall?",
      "UDR on spoke subnet: `0.0.0.0/0` → Virtual Appliance (firewall private IP). Disable BGP route override if needed.",
      "**Asymmetric routing:** ensure return path through firewall — SNAT on firewall.\n\n**Architect:** Test with Network Watcher — verify effective routes on VM.",
      "UDR mistakes cause subtle connectivity failures.",
      "Service endpoints and UDR? — May need specific routes — test PaaS connectivity.",
      "Route Server? — BGP between firewall and VNet — advanced hub.",
      "Spoke direct internet bypass firewall",
      "UDR without effective route validation",
      "Blackhole routing misconfiguration"),
    q("Bastion and Jump Hosts", "Operations", "Common",
      "Secure admin access to VMs without public RDP?",
      "Azure Bastion in hub — RDP/SSH over HTTPS through portal, no public VM IP. Or private jump box with JIT access.",
      "**Architect:** No public IPs on servers. PIM + Bastion + logging.\n\n**Just-in-time:** Defender opens port temporarily for approved admin.",
      "Admin access architecture is security review item.",
      "Bastion SKU? — Basic vs Standard — session recording Standard.",
      "Session recording compliance? — Store logs for audit.",
      "Public RDP for convenience",
      "Shared admin password",
      "Jump box without MFA"),
    q("DDoS Protection", "Security", "Common",
      "When enable Azure DDoS Network Protection?",
      "Public-facing endpoints with revenue impact — Front Door origin, public IPs. DDoS IP Protection per protected resource or Network Protection per VNet.",
      "**Architect:** Pair with WAF at edge. DDoS alerts to SOC.\n\n**Cost:** Network Protection fixed monthly — justify for critical internet properties.",
      "DDoS is availability architecture.",
      "DDoS vs WAF? — DDoS volume attacks; WAF application layer.",
      "Telemetry? — DDoS diagnostic logs during attack.",
      "No DDoS on public ecommerce",
      "Assume Front Door alone stops all attacks",
      "No runbook for DDoS event"),
    q("VNet Peering Data Transfer Cost", "FinOps", "Common",
      "Hub-spoke peering cost consideration?",
      "Peering ingress/egress charged within same region (minimal) — cross-region peering costs more. Egress to internet expensive — centralize through firewall with monitoring.",
      "**Architect:** Model data flow — heavy spoke-to-spoke via hub doubles hub traffic.\n\n**Optimize:** private endpoints reduce internet egress for Azure PaaS.",
      "Network architecture affects monthly bill.",
      "VWAN hub routing? — May simplify billing complexity at scale.",
      "Same region deployment? — Keep peering same region when possible.",
      "Unnecessary cross-region peering",
      "Ignore egress in architecture review",
      "Chatty microservices across regions"),
]

WEEK_14 = [
    q("Defense in Depth on Azure", "Security", "Very Common",
      "Map defense in depth layers for Azure web application.",
      "Identity (Entra, CA) → Perimeter (Front Door, WAF) → Network (NSG, Private Link) → Compute (patching, Defender) → Data (TDE, CMK) → App (input validation).",
      "Each layer independent failure — WAF bypass still hits NSG and authZ.\n\n**Architect:** Threat model STRIDE per layer — document controls.",
      "Layered security is WAF pillar implementation.",
      "Which layer stops SQL injection? — App validation + parameterized queries + WAF.",
      "Shared responsibility model? — Customer secures app and data; Microsoft secures platform.",
      "Single security product 'does it all'",
      "Ignore app layer validation",
      "Public data plane endpoints"),
    q("Azure WAF Rules", "Security", "Very Common",
      "WAF false positives blocking legitimate traffic — approach?",
      "Start detection mode, tune exclusions for known false positives, custom rules for rate limit, move to prevention after 2 weeks baseline.",
      "**Managed rule sets:** OWASP 3.2 baseline. **Geo-block** if business allows.\n\n**Architect:** WAF logs to Log Analytics — correlate blocked requests with support tickets.",
      "WAF operations realism impresses interviewers.",
      "Custom rule example? — Block countries except operating regions.",
      "Bot protection? — Front Door Premium bot manager.",
      "Prevention mode day one — blocks customers",
      "Disable rules causing false positives globally",
      "No WAF log analysis"),
    q("Microsoft Defender for Cloud", "Security", "Common",
      "How use Defender for Cloud in architecture governance?",
      "Secure score tracks posture. Enable Defender plans (Servers, SQL, Storage, Key Vault). Regulatory compliance dashboard maps to SOC2/ISO.",
      "**CI/CD:** Defender for DevOps scans IaC and secrets in repos.\n\n**Architect:** Weekly secure score review in platform team — block deploy on critical findings.",
      "Defender is continuous compliance monitoring.",
      "Agentless scanning? — VM scanning without agent — preview features evolve.",
      "CSPM vs CWP? — Posture management vs workload protection.",
      "Defender disabled for cost",
      "Critical alerts unmonitored",
      "No owner for recommendations"),
    q("Encryption at Rest and Transit", "Security", "Very Common",
      "Encryption requirements for PCI workload on Azure?",
      "TLS 1.2+ in transit. TDE at rest all data stores. CMK if PCI DSS requires key custody. Always Encrypted for cardholder data fields if stored.",
      "**Better:** tokenization — Stripe/Adyen — card data never touches your DB.\n\n**Architect:** Scope reduction beats encryption complexity.",
      "PCI scope reduction is architect-first answer.",
      "Certificate management? — Key Vault auto-renew or App Service managed cert.",
      "Internal TLS? — mTLS service mesh for east-west.",
      "PAN stored encrypted in your SQL",
      "TLS 1.0 enabled",
      "Self-signed certs production"),
    q("Managed Identity Security", "Identity", "Common",
      "Compromised App Service — blast radius with managed identity?",
      "MI limited to RBAC granted — scope MI to minimum resources. Separate MI per app. Monitor MI authentication logs in Entra sign-in logs.",
      "**Rotation:** no secret to steal — attacker uses MI from compromised app — containment via RBAC scope and network isolation.",
      "MI reduces but doesn't eliminate blast radius.",
      "Audit MI permissions? — Quarterly access review.",
      "Disable MI when not needed? — Delete user-assigned MI explicitly.",
      "MI Contributor on subscription",
      "Shared MI across unrelated apps",
      "No logging on MI token requests"),
    q("DevSecOps on Azure", "DevSecOps", "Common",
      "Security scanning in GitHub Actions pipeline for Bicep and .NET?",
      "CodeQL SAST, secret scanning, Bicep what-if + defender for IaC, container Trivy scan, deploy to staging, OWASP ZAP DAST optional.",
      "**Quality gates:** block merge on critical CVE, failed secret scan, policy what-if deny.\n\n**Architect:** Golden pipeline template all teams inherit.",
      "Shift-left security is architect pipeline design.",
      "SBOM generation? — Supply chain security — export on release.",
      "Signed commits? — Optional enhanced integrity.",
      "Deploy without vulnerability scan",
      "Secrets in Bicep parameters file in git",
      "No IaC policy validation"),
    q("OWASP API Security Top 10", "Security", "Common",
      "Top API risks for Azure APIM-protected API?",
      "BOLA (broken object level authZ), authN failures, excessive data exposure, rate limiting missing, misconfiguration.",
      "**Mitigations:** authZ on every resource ID, APIM rate limits, JWT validation, response filtering, audit logging.\n\n**Architect:** Threat model each public API endpoint.",
      "API security beyond network WAF.",
      "APIM validate JWT? — `validate-jwt` policy — issuer, audience, signature.",
      "Subscription keys enough? — Not without per-user authZ — keys are coarse.",
      "Trust client to filter data",
      "No object-level authZ",
      "APIM as only security layer"),
    q("Security Incident Response on Azure", "Operations", "Common",
      "Suspected Key Vault secret exfiltration — steps?",
      "Rotate secrets immediately, review Key Vault diagnostic logs, Entra sign-in logs for MI/SP, isolate compromised resource, Sentinel incident, preserve evidence.",
      "**Runbook:** detection → containment → eradication → recovery → lessons learned.\n\n**Architect:** Pre-document contacts, rotation automation, break-glass procedure.",
      "Incident response shows operational maturity.",
      "Sentinel automation? — Playbooks automate containment.",
      "Communication plan? — Legal/comms for breach notification.",
      "No secret rotation runbook",
      "Delete logs during incident",
      "No forensic snapshot"),
    q("Azure Policy for Security", "Governance", "Common",
      "Policies to enforce security baseline?",
      "Deny public IP on VMs, require TLS on Storage, deploy diagnostic settings, require Private Link for SQL, allowed locations only.",
      "**Initiative:** assign 'Azure Security Benchmark' or custom SOC2 initiative to prod MG.\n\n**Exemptions:** documented with expiry — not permanent bypass.",
      "Policy encodes security architecture at scale.",
      "DeployIfNotExists diagnostic? — Auto-configure logging — critical for audit.",
      "Guest configuration? — VM baseline settings — Azure Policy machine config.",
      "Manual compliance checks quarterly",
      "Permanent policy exemptions",
      "Audit-only policies never remediated"),
    q("Secrets Rotation Strategy", "Security", "Common",
      "Automate SQL password rotation without downtime?",
      "Dual-user pattern or Entra ID auth for SQL (no password). Key Vault rotation function updates secret, App Service picks up on restart/refresh.",
      "**Best:** Entra authentication for SQL — eliminate SQL password entirely.\n\n**Architect:** Rotation runbook tested — quarterly game day.",
      "Rotation architecture prevents stale credential incidents.",
      "Event Grid Key Vault rotation? — Near-expiry cert alerts.",
      "Blue-green for secret-dependent deploy? — Staging slot tests new secret.",
      "Password never rotated 3 years",
      "Manual rotation during business hours only",
      "Single SQL login shared by all apps"),
]

WEEK_15 = [
    q("Service Bus vs Event Grid", "Messaging", "Very Common",
      "Order placed event — Service Bus or Event Grid?",
      "Service Bus: ordered processing, transactions, competing consumers, dead letter. Event Grid: reactive routing, fan-out, Azure resource events, serverless trigger.",
      "**Domain event to microservices:** Service Bus topic. **React to Blob upload:** Event Grid.\n\n**Architect:** Service Bus for business workflows; Event Grid for event-driven automation.",
      "Messaging product fit is Azure architect essential.",
      "Service Bus sessions? — Ordered processing per orderId.",
      "Event Grid delivery retry? — 24 hours with exponential backoff.",
      "Event Grid for payment command processing",
      "Service Bus for simple blob notification only",
      "No DLQ on Service Bus"),
    q("Event Hubs for Streaming", "Streaming", "Common",
      "Design clickstream pipeline with Event Hubs.",
      "Producers → Event Hubs partitions (key=userId) → Stream Analytics or Spark → Synapse/Data Lake. Capture to Blob for replay.",
      "**Partitions:** throughput scale unit — plan partition count — hard to change later.\n\n**Consumer groups:** independent readers — analytics vs real-time dashboard.",
      "Streaming architecture common retail scenario.",
      "Kafka protocol? — Event Hubs Kafka endpoint — existing clients migrate.",
      "Retention? — Days to weeks — replay vs cost.",
      "Single partition 10M events/sec",
      "Consumer without checkpoint store",
      "No dead letter for poison events in stream processing"),
    q("API Management Role", "APIM", "Very Common",
      "Why APIM in front of microservices?",
      "Single entry, JWT validation, rate limiting, versioning, developer portal, request transformation, analytics.",
      "**Architect:** External clients → APIM → internal services on private network.\n\n**Policies:** `rate-limit`, `validate-jwt`, `set-backend-service` for routing.",
      "APIM is API governance layer.",
      "Internal vs external APIM? — Developer SKU dev; Premium VNet internal prod.",
      "Self-hosted gateway? — Hybrid on-prem gateway.",
      "Clients call 10 microservices direct",
      "No rate limiting public API",
      "Business logic in APIM policy"),
    q("Outbox with Azure Service Bus", "Patterns", "Very Common",
      "Implement transactional outbox with SQL + Service Bus?",
      "Same SQL transaction: insert order + insert outbox row. Azure Function or worker polls outbox, sends to Service Bus, marks processed.",
      "**Alternatives:** Debezium CDC from SQL to Event Hubs. **Idempotent consumers** mandatory.\n\n**Architect:** At-least-once publish + idempotent handlers = effectively once.",
      "Outbox is correct Azure integration pattern.",
      "Logic Apps poll outbox? — Possible low volume — Function more control.",
      "Service Bus duplicate detection? — MessageId window — complement outbox.",
      "Publish before DB commit",
      "No idempotent consumer",
      "Outbox relay single instance no HA"),
    q("Message Duplication and Idempotency", "Reliability", "Very Common",
      "Service Bus delivers message twice — handle?",
      "Idempotent handler with business key dedup table. Service Bus duplicate detection window. Application checks `messageId` processed.",
      "**Payment:** idempotency key + unique constraint on payment reference.\n\n**Architect:** Design all consumers for at-least-once semantics.",
      "Messaging semantics literacy required.",
      "Exactly-once Service Bus? — Not guaranteed end-to-end — design idempotent.",
      "Peek-lock vs receive-delete? — Peek-lock with complete after success.",
      "Assume single delivery",
      "Complete message before processing",
      "No dedup store"),
    q("Event-Driven Choreography on Azure", "Architecture", "Common",
      "Choreography with Service Bus topics — pitfalls?",
      "Hard to see global flow, cyclic dependencies, debugging distributed transactions. Mitigate: distributed tracing, event catalog documentation, compensation events.",
      "**When orchestration better:** Durable Functions for visible saga state.\n\n**Architect:** Start choreography simple; move to orchestration when steps > 5 or compensation complex.",
      "Choreography vs orchestration Azure implementation.",
      "Event schema registry? — Azure Schema Registry for Service Bus.",
      "Dead letter monitoring? — Alert on DLQ depth per subscription.",
      "Circular event dependencies",
      "No correlation ID in messages",
      "Missing compensation events"),
    q("Integration Account and B2B", "Integration", "Occasional",
      "EDI B2B integration on Azure?",
      "Logic Apps + Integration Account for EDI schemas, partners, agreements. Maps to canonical XML/JSON for internal microservices.",
      "**Modern:** prefer API/JSON partners; EDI when retail/manufacturing requires.\n\n**Architect:** Anti-corruption layer from EDI to domain events.",
      "Shows breadth beyond greenfield APIs.",
      "Logic Apps vs Functions integration? — Logic Apps low-code connectors; Functions code-heavy.",
      "IPaaS cost? — Logic Apps per action — model high volume cost.",
      "Custom EDI parser in monolith",
      "No partner certificate rotation",
      "Logic Apps without error handling"),
    q("Dead Letter Queue Handling", "Operations", "Common",
      "Service Bus DLQ growing — operational response?",
      "Alert on DLQ count, dashboard per queue, runbook: inspect message, fix consumer bug, replay to main queue after fix, root cause in postmortem.",
      "**Tools:** Service Bus Explorer, programmatic receive from DLQ.\n\n**Architect:** DLQ not garbage — operational signal.",
      "DLQ operations separate mature teams.",
      "Auto-replay dangerous? — Only after fix deployed — manual gate.",
      "Poison message quarantine? — Separate storage for analysis.",
      "Ignore DLQ alerts",
      "Delete DLQ messages without analysis",
      "No DLQ on critical queues"),
    q("Messaging Cost Optimization", "FinOps", "Common",
      "Reduce Service Bus and Event Hubs costs?",
      "Right-size tier, batch messages, compress payloads, archive to Blob not retain in queue long, serverless Event Hubs for variable load.",
      "**Architect:** Large payloads → Blob storage + event with URL reference.\n\n**Review:** messages per business transaction — optimize chatty publishers.",
      "Messaging cost scales with volume — design efficiently.",
      "Premium Service Bus when? — Predictable latency, higher throughput isolation.",
      "Event Hubs throughput units? — Start low scale with auto-inflate.",
      "Send full document in every message",
      "Premium tier for dev environment",
      "No message size limits documented"),
    q("APIM + Functions Integration", "Architecture", "Common",
      "Expose Azure Functions through APIM — pattern?",
      "Functions behind internal network or with function key; APIM validates JWT, strips keys, routes `/api/orders` to function backend.",
      "**Security:** never expose function key to clients — APIM injects backend auth.\n\n**Versioning:** `/v1/orders` APIM revision routes to function version.",
      "Standard serverless API gateway pattern.",
      "Consumption Functions behind APIM? — Cold start at edge — consider Premium plan.",
      "OpenAPI import? — APIM imports function OpenAPI definition.",
      "Function key in mobile app",
      "Public function URL bypassing APIM",
      "No JWT validation at gateway"),
]

WEEK_16 = [
    q("Production Architecture Review Checklist", "Capstone", "Very Common",
      "Lead architecture review for Azure production SaaS — checklist?",
      "WAF all pillars, threat model, HA/DR RPO/RTO, identity MI+CA, network hub-spoke+PE, observability SLOs, FinOps tags+budgets, IaC deployment, runbooks.",
      "**Deliverable:** findings ranked Critical/High/Medium with owners and dates.\n\n**Architect:** Review is collaborative — not gatekeeping without alternatives.",
      "Review checklist is capstone synthesis.",
      "Sign-off criteria? — No Critical open, High has mitigation plan.",
      "Re-review trigger? — Major design change or quarterly.",
      "Checklist only security",
      "No documented findings",
      "Review without workload owners"),
    q("Multi-Region Production SLA Math", "Reliability", "Very Common",
      "Calculate composite SLA for Front Door + App Service + SQL geo-replica.",
      "Multiply independent SLAs: 99.99% × 99.95% × 99.99% ≈ 99.93%. Weakest link dominates — document dependency chain.",
      "**Improve:** redundant paths, circuit breakers, graceful degradation when dependency down.\n\n**Architect:** Don't promise 99.99% if chain multiplies to 99.9% without mitigation.",
      "SLA math is executive-facing architect skill.",
      "Parallel vs series dependencies? — Series multiplies; parallel improves.",
      "Error budget? — 99.9% = 43 min/month downtime budget.",
      "Sum SLAs instead of multiply",
      "Ignore dependency chain",
      "100% SLA promise"),
    q("DR Runbook Essentials", "DR", "Very Common",
      "DR runbook outline for Azure SQL failover group?",
      "Detection (alerts), decision criteria (RTO threshold), failover execution (manual/auto), validation (synthetic tests), communication (status page), rollback criteria.",
      "**Test:** game day quarterly — measure actual RTO/RPO.\n\n**Architect:** Runbook in wiki + automated scripts where possible — not panic documentation.",
      "DR without tested runbook is wishful thinking.",
      "Failback plan? — Reverse replication after primary healthy.",
      "Data loss acceptance? — Document RPO business sign-off.",
      "Runbook untested since creation",
      "No communication templates",
      "Failover without app connection string plan"),
    q("C4 Diagram for Azure Capstone", "Documentation", "Very Common",
      "What to include in C4 Container diagram for Azure capstone?",
      "Users, SPA, APIM, microservices (App Service/AKS), Service Bus, SQL, Cosmos, Redis, Key Vault, Entra ID, App Insights, Front Door.",
      "**Per container:** technology choice, responsibilities, sync/async links.\n\n**Level 1 Context:** system boundary and external actors only.",
      "C4 is architect documentation standard.",
      "Dynamic diagram? — Show request flow for checkout scenario.",
      "Deployment diagram? — Map containers to Azure resources.",
      "Deployment diagram only no C4",
      "Missing external systems",
      "No legend or technology labels"),
    q("ADR for Azure Service Choices", "Governance", "Very Common",
      "Write ADR: App Service vs AKS for order API.",
      "Context: team skill, scale, 3 services. Decision: App Service P1v3. Consequences: faster ops, less K8s portability. Rejected: AKS — ops overhead unjustified.",
      "**ADR template:** status, date, deciders, context, decision, consequences, alternatives.\n\n**Architect:** ADRs in git next to Bicep — living documents.",
      "ADR quality demonstrates architect thinking.",
      "Supersede ADR when? — Trigger metrics hit — document revision.",
      "Link ADR to cost estimate? — Strengthens business case.",
      "Decision without alternatives section",
      "ADR never revisited",
      "Verbal decision only"),
    q("Security Controls Mapping", "Security", "Common",
      "Map WAF security pillar to controls in capstone?",
      "Entra auth, CA MFA, Private Link SQL, Key Vault secrets, WAF OWASP, NSG segmentation, Defender enabled, audit logs to Sentinel.",
      "**Traceability matrix:** SOC2 control → Azure implementation → evidence (policy assignment ID, screenshot, IaC reference).",
      "Compliance mapping is enterprise architect work.",
      "Pen test before launch? — External validation of controls.",
      "Threat model STRIDE? — Link threats to mitigations.",
      "Controls list without implementation",
      "No evidence collection plan",
      "Security bolted on last week"),
    q("Cost Estimate Order of Magnitude", "FinOps", "Common",
      "Estimate monthly Azure cost for capstone architecture?",
      "Pricing calculator: App Service P1v3×2, SQL S3, Redis C1, Service Bus standard, Front Door, Log Analytics ingestion GB/day.",
      "**Document assumptions:** DAU, requests/day, log volume, retention.\n\n**Sensitivity:** 2x traffic = ~1.5x cost if autoscale — not linear.",
      "Order-of-magnitude cost expected in capstone.",
      "Reserved instance savings? — Note 1-year RI option in estimate.",
      "Dev vs prod cost split? — Separate subscriptions — show both.",
      "No cost section in architecture",
      "Copy-paste calculator without assumptions",
      "Ignore Log Analytics cost"),
    q("Integration Architecture Synthesis", "Integration", "Common",
      "Show async flows in capstone e-commerce.",
      "OrderPlaced → Service Bus topic → [Inventory, Notification, Analytics subscribers]. Outbox from order service. APIM sync for client-facing API.",
      "**Sync path:** checkout API only. **Async:** everything post-confirm.\n\n**Diagram:** numbered steps with failure compensation.",
      "Integration synthesis ties week 15 to capstone.",
      "Event catalog? — List events, schema version, publisher, subscribers.",
      "Correlation ID? — Propagate through Service Bus application properties.",
      "All sync microservice calls",
      "No outbox on order write",
      "Missing DLQ strategy"),
    q("Operational Excellence Capstone", "Operations", "Common",
      "Observability stack for capstone?",
      "OpenTelemetry SDK → App Insights, Log Analytics workspace, workbooks dashboards, SLO alerts, action groups to on-call, runbooks linked in alerts.",
      "**Golden signals:** latency, traffic, errors, saturation per service.\n\n**Architect:** Same observability template for all services in platform.",
      "Operability proves production readiness.",
      "Synthetic tests? — Availability tests from 3 regions.",
      "Alert fatigue? — Actionable alerts only — SLO burn rate.",
      "Logs only no distributed tracing",
      "Alerts to unused email",
      "No runbook links in alerts"),
    q("Capstone Presentation Defense", "Communication", "Very Common",
      "Defend capstone when interviewer challenges over-engineering.",
      "Acknowledge trade-off, cite requirement (SLA, compliance, scale), offer phased simplification MVP vs target state, quantify cost/complexity of alternative.",
      "**Structure:** 'You're right that X adds complexity. We accepted it because Y requirement. Phase 1 could defer Z until metric M hit.'\n\n**Architect:** Intellectual honesty > defending every box.",
      "Defense communication is interview skill.",
      "What would you cut for MVP? — Have answer ready — scope triage.",
      "Metrics to validate design? — SLOs, cost per order, deploy frequency.",
      "Defensive or dismissive tone",
      "Cannot simplify design when asked",
      "No phased roadmap"),
]

ALL_AZURE_WEEKS = {
    9: WEEK_9, 10: WEEK_10, 11: WEEK_11, 12: WEEK_12,
    13: WEEK_13, 14: WEEK_14, 15: WEEK_15, 16: WEEK_16,
}
