"""Hand-crafted premium Q011–Q030 for Weeks 33–36 — System Design tails."""

from premium_qa_data import q

WEEK_33_Q011_Q030 = [
    q("Functional vs Non-Functional Requirements", "Requirements", "Very Common",
      "How separate functional and non-functional requirements in a system design interview?",
      "Functional: what the system does (create short URL, redirect). Non-functional: how well (latency, scale, availability, consistency, cost). Clarify both before drawing.",
      "**Functional examples:** user registration, post tweet, send message, search products.\n\n**NFR examples:** 99.9% availability, p99 read < 100ms, 10M DAU, GDPR data residency, $X/month budget.\n\n**Interview technique:** Write two columns on board. For each feature ask 'what breaks if we ignore NFR?' — e.g., feed without latency target leads to wrong fan-out choice.\n\n**Architect habit:** NFRs drive technology choices; functional reqs drive API and data model.",
      "Senior candidates surface NFRs proactively — juniors only list features.",
      "Which NFR first for URL shortener? — Read latency and availability — write is rare.",
      "Implicit NFR trap? — 'Real-time' undefined — ask: p99 under 200ms?",
      "Only listing features",
      "Treating all NFRs as hard constraints without trade-offs",
      "No prioritization when NFRs conflict"),
    q("Back-of-Envelope QPS", "Estimation", "Very Common",
      "Estimate peak QPS for 50M DAU social app, each user 20 actions/day.",
      "50M × 20 / 86400 ≈ 11,600 avg QPS. Peak 3–5× → ~35K–58K QPS. Split read/write if ratio known.",
      "**Formula:** `QPS = DAU × actions_per_user / 86400`.\n\n**Peak factor:** Lunch/evening spikes, viral events — state assumption (3× or 5×).\n\n**Read/write split:** If 90% read, 10% write → 52K read, 5.8K write at 5× peak.\n\n**Why it matters:** 5K write QPS fits single primary DB with tuning; 500K needs sharding. Show math — interviewers score process not exact number.",
      "QPS estimation gates every scaling decision in the interview.",
      "MAU vs DAU? — Use DAU for capacity — MAU overestimates.",
      "Global vs single-region QPS? — Shard estimate per region if geo-distributed.",
      "Using MAU as DAU",
      "No peak multiplier",
      "Single QPS number without read/write split"),
    q("Storage Estimation", "Estimation", "Very Common",
      "Estimate 5-year storage for photo-sharing: 200M users, 5 photos/week, 2MB average.",
      "200M × 5 × 52 × 5 = 260B photos. × 2MB ≈ 520PB raw. Metadata ~1KB/photo adds ~260TB. Replication 3× → ~1.5EB class — CDN/object store not single DB.",
      "**Steps:** objects/year × years × size + metadata overhead + indexes (often 10–20%).\n\n**Compression:** JPEG already compressed — don't double-count.\n\n**Tiering:** Hot 30 days SSD, warm S3, cold Glacier — effective cost not raw PB.\n\n**Interview:** Round to nearest order of magnitude. State 'object storage + CDN, not relational DB for blobs.'",
      "Storage math proves you won't put petabytes in PostgreSQL.",
      "Thumbnail storage? — 10× originals if not deduplicated — call out.",
      "Delete/account erasure? — Tombstone + async purge — retention policy affects storage.",
      "Storing blobs in SQL",
      "Forgetting metadata and index overhead",
      "No replication factor in estimate"),
    q("Bandwidth Estimation", "Estimation", "Common",
      "Bandwidth for video streaming: 1M concurrent viewers, 5 Mbps stream.",
      "1M × 5 Mbps = 5 Tbps egress. Requires CDN edge — origin cannot serve directly.",
      "**Ingress:** Upload 10K creators × 5 Mbps = 50 Gbps — smaller than egress.\n\n**CDN absorbs** 95%+ of viewer traffic — origin bandwidth = cache miss rate × viewers.\n\n**Cost driver:** Egress is often largest cloud bill line — architect mentions CDN and peering.\n\n**Units:** Watch Mbps vs MBps. 1 byte = 8 bits.",
      "Bandwidth estimation connects QPS to infrastructure cost.",
      "API JSON bandwidth? — QPS × avg payload — often smaller than media.",
      "Cross-AZ egress? — Same-region traffic pricing — design data locality.",
      "Origin serves all video traffic",
      "Confuse Mbps and MBps",
      "Ignore CDN in bandwidth math"),
    q("REST API Design for System Design", "API", "Very Common",
      "Design REST resources for a ride-sharing system.",
      "`POST /v1/rides` request ride. `GET /v1/rides/{id}` status. `PATCH /v1/rides/{id}` cancel. `GET /v1/drivers/{id}/location` — separate resources, nouns not verbs.",
      "**Principles:** Resource-oriented URLs, HTTP verbs match semantics, versioning in path, pagination on collections, HATEOAS optional in interview.\n\n**Status codes:** 201 Created + Location header, 409 conflict on double-book, 202 Accepted for async dispatch.\n\n**Internal vs external:** Public REST; internal may use gRPC — mention both layers.",
      "REST sketch shows API thinking beyond boxes and arrows.",
      "RPC-style `/createRide`? — Acceptable if team standard — justify consistency.",
      "Idempotency on POST? — `Idempotency-Key` header — critical for payments/rides.",
      "Verb in URL `/getRide`",
      "200 for everything",
      "No versioning strategy"),
    q("Idempotency Keys in API Design", "API", "Very Common",
      "How implement idempotency keys for `POST /payments`?",
      "Client sends `Idempotency-Key: uuid`. Server stores key + response in Redis/DB with TTL 24h. Duplicate key returns cached response without re-charging.",
      "**Flow:** Receive request → check key exists → if yes return stored response → if no process in TX, store result, return.\n\n**Scope:** Per merchant or per user. Key collision across users acceptable if UUID.\n\n**Stripe pattern:** Standard industry reference — architects cite it.\n\n**Failure:** Store result before returning 200 — crash after charge but before store causes duplicate on retry without key.",
      "Idempotency is mandatory for any money or inventory mutation API.",
      "Key TTL? — 24h typical — balance storage vs client retry window.",
      "Same key different body? — Reject 422 — key body mismatch.",
      "Idempotency only on GET",
      "No storage of idempotent responses",
      "Assume network never retries"),
    q("Pagination Cursor vs Offset", "API", "Common",
      "When cursor pagination vs offset for social feed API?",
      "Cursor (keyset): stable under inserts, efficient at depth — `?after=tweetId&limit=20`. Offset: simple but slow `OFFSET 100000` and duplicates/skips under concurrent writes.",
      "**Cursor:** Encode `(timestamp, id)` tuple — unique sort key. O(limit) per page.\n\n**Offset:** OK for admin tables < 10K rows. Bad for infinite scroll feeds.\n\n**Bidirectional:** `before` and `after` cursors for scroll up/down.\n\n**Interview:** Default recommend cursor for user-facing feeds; offset for internal reports.",
      "Pagination choice affects DB index design and UX consistency.",
      "Opaque cursor? — Base64 encode — hide internal IDs.",
      "Total count header? — Expensive on large tables — optional `X-Total-Count`.",
      "OFFSET on billion-row feed",
      "Cursor without stable sort key",
      "Page number API for real-time feed"),
    q("Rate Limiting Design", "Rate Limiting", "Very Common",
      "Design rate limiting for public API: 1000 req/min per API key, burst allowed.",
      "Token bucket in Redis: refill 1000/60 tokens/sec, bucket capacity 100 for burst. Return 429 + `Retry-After` + `X-RateLimit-Remaining`.",
      "**Layers:** Edge (CloudFront/WAF), API gateway (APIM), app middleware — defense in depth.\n\n**Distributed:** Central Redis — not per-node counters (uneven under LB).\n\n**Tiers:** Free 100/min, paid 10K/min — keyed by API key or tenantId.\n\n**Grace:** Soft limit warn header; hard limit 429.",
      "Rate limiting protects platform and is architect-level API contract.",
      "Global vs per-endpoint limits? — Stricter on expensive endpoints (search, export).",
      "Internal service bypass? — mTLS identity whitelist — not IP alone.",
      "Per-server rate limit only",
      "429 without Retry-After",
      "No rate limit on auth/login endpoints"),
    q("Authentication at Scale", "Security", "Very Common",
      "Design auth for 100M-user SaaS: sessions vs JWT?",
      "JWT access token (short TTL 15m) + refresh token (rotating, HttpOnly cookie or secure store). Validate JWT at gateway without DB hit. Revocation list for compromised tokens.",
      "**Scale path:** Stateless JWT verification at edge — O(1) per request.\n\n**Session store:** Redis for server-side session if needed — sticky avoided via shared store.\n\n**OAuth2/OIDC:** Delegate to Entra/Auth0 for enterprise SSO.\n\n**Architect:** Never put PII in JWT payload. Key rotation via JWKS endpoint.",
      "Auth at scale requires stateless verification and clear token lifecycle.",
      "Refresh token rotation? — Detect reuse — revoke family on theft.",
      "Service-to-service? — mTLS or client credentials — not user JWT.",
      "Long-lived JWT with no revocation",
      "Session in server memory behind LB",
      "Validate auth only in app not gateway"),
    q("Multi-Tenant SaaS Design", "Multi-Tenancy", "Very Common",
      "Design data isolation for B2B SaaS with 10K tenants.",
      "Pool model: `tenantId` on every row + row-level security. Bridge: pool for SMB, dedicated DB for enterprise. Cache keys always include `tenantId`.",
      "**Isolation levels:** Pool (shared schema), bridge (pools by tier), silo (DB per tenant).\n\n**Auth:** Resolve tenant from subdomain or JWT claim — inject into request context — every query scoped.\n\n**Noisy neighbor:** Per-tenant rate limits and fair queue scheduling.\n\n**Compliance:** Enterprise may require silo + encryption per tenant CMK.",
      "Multi-tenancy is cross-cutting — data, cache, queue, and billing.",
      "Cross-tenant query leak test? — Automated security tests mandatory.",
      "Tenant migration silo? — Dual-write + cutover playbook.",
      "Missing tenantId in cache key",
      "Global admin API without tenant scope",
      "One shard key ignoring hot enterprise tenant"),
    q("URL Shortener System Design", "System Design", "Very Common",
      "Design URL shortener for 100M URLs/month, 10:1 read/write ratio.",
      "Write: hash or base62 counter → store in SQL/NoSQL. Read: cache (Redis) → redirect 301. LB + stateless API. 7-char base62 ≈ 3.5T codes.",
      "**Key components:** API, ID generator, DB (shortCode PK, longUrl, userId, createdAt), cache, analytics async.\n\n**Custom alias:** Unique constraint — 409 on collision.\n\n**Expiration:** TTL column + lazy delete.\n\n**Scale read path:** 99% cache hit — DB handles miss only.",
      "URL shortener is canonical interview — know cold.",
      "Base62 vs hash? — Counter + base62 sequential; hash risks collision.",
      "Analytics separate? — Async click event to Kafka — don't block redirect.",
      "DB hit on every redirect",
      "MD5 truncate without collision handling",
      "302 vs 301 choice unexplained"),
    q("Paste Bin System Design", "System Design", "Common",
      "Design Pastebin: 10M pastes/month, some expire in 10 minutes, some never.",
      "Object storage (S3) for content + metadata DB. TTL index for expiry. CDN for popular pastes. Key: random 8-char ID — not sequential (security).",
      "**Write:** Store blob → return URL. **Read:** CDN → origin on miss.\n\n**Expiry:** DynamoDB TTL or cron sweeper. **Max size:** 1MB limit — reject larger.\n\n**Privacy:** Unlisted vs public — no search index for unlisted.\n\n**Syntax highlighting:** Pre-render or client-side — async job for large files.",
      "Pastebin exercises blob + metadata split and TTL design.",
      "Sequential IDs? — Enumeration attack — use random keys.",
      "Encryption at rest? — Optional private pastes — per-object KMS.",
      "Store megabyte pastes in SQL row",
      "No expiry mechanism",
      "Public listing of all pastes"),
    q("News Feed System Design", "System Design", "Very Common",
      "Design Twitter-style news feed for 300M users.",
      "Hybrid fan-out: normal users fan-out on write to follower feeds (Redis sorted sets). Celebrities fan-out on read — merge at read time.",
      "**Components:** post service, timeline service, social graph, media CDN, fan-out workers.\n\n**Celebrity problem:** User with 50M followers — write fan-out impossible — detect threshold.\n\n**Ranking:** Score = time decay + engagement — precompute vs real-time — trade latency.",
      "Feed design tests fan-out strategy — the core scaling fork.",
      "Consistent ordering global? — Usually per-user timeline — not global total order.",
      "Delete/edit tweet? — Fan-out cleanup job or tombstone in feed.",
      "Fan-out on write for all users including celebrities",
      "Single DB for all timelines",
      "No cache for home timeline read"),
    q("Chat System Design", "System Design", "Very Common",
      "Design WhatsApp-scale 1:1 chat: delivery and read receipts.",
      "WebSocket gateway per user connection. Message service stores in Cassandra/Scylla partitioned by `(conversationId, timestamp)`. Push via APNs/FCM when offline.",
      "**Flow:** Send → persist → ack sender → push recipient → delivery receipt → read receipt.\n\n**Ordering:** Per-conversation sequence number — not global.\n\n**Group chat:** Separate fan-out to members — message ID idempotency.\n\n**Presence:** Heartbeat + Redis presence store — 'last seen'.",
      "Chat combines real-time connections with durable message store.",
      "WebSocket scaling? — Sticky connection to gateway node — Redis pub/sub cross-node.",
      "E2E encryption? — Server stores ciphertext only — architect acknowledges trade-off.",
      "HTTP poll for real-time chat",
      "No offline message queue",
      "Global message ordering requirement"),
    q("Notification System Design", "System Design", "Very Common",
      "Design notification system: email, SMS, push — 1B notifications/day.",
      "Event bus → router by channel → priority queues → worker pools → provider adapters. Template service. User preference store. Idempotent `notificationId`.",
      "**Priority:** OTP > transactional > marketing. **Rate limit:** Per user per channel per hour.\n\n**Retry:** Exponential backoff — DLQ after N failures.\n\n**Providers:** Abstract SendGrid/Twilio/FCM behind adapter interface.\n\n**Digest:** Scheduler batches low-priority email.",
      "Notification platform is common whiteboard — prepare template answer.",
      "Unsubscribe compliance? — CAN-SPAM/GDPR — preference honored before send.",
      "Fan-out cost? — 1 event × 3 channels — budget provider API costs.",
      "Synchronous send in user request path",
      "No user preference check",
      "Single thread for all email"),
    q("Search Autocomplete System Design", "System Design", "Common",
      "Design search autocomplete for e-commerce: 10M queries/day, p99 < 50ms.",
      "Trie or prefix index in Redis/memory + popular queries precomputed. Data pipeline aggregates search logs → updates top-K suggestions nightly + trending real-time stream.",
      "**Architecture:** Typeahead API → cache layer → prefix index. Fallback to full search on miss.\n\n**Personalization:** Optional user history segment — separate index per segment or post-filter.\n\n**Bad words:** Blocklist filter before return.",
      "Autocomplete is read-heavy prefix problem — not full Elasticsearch per keystroke.",
      "Elasticsearch completion suggester? — Valid at scale — shard by prefix.",
      "Debouncing? — Client 200ms debounce — reduces QPS 5×.",
      "Full search index per keystroke",
      "No trending update pipeline",
      "Return unfiltered user-generated suggestions"),
    q("Distributed ID Generation", "System Design", "Very Common",
      "Compare approaches for globally unique order IDs at 10K/sec.",
      "Options: DB auto-increment (bottleneck), UUID v4 (random, index fragmentation), UUID v7 (time-sortable), Snowflake (64-bit structured), DB sequence per shard + offset.",
      "**Requirements:** Unique, roughly sortable by time, no coordination hot spot, fits in 64 bits preferred.\n\n**Snowflake:** 41-bit timestamp + 10-bit machine + 12-bit sequence — 4096/ms per machine.\n\n**DB sequences:** `shardId << 48 | localSequence` — embed shard in ID.\n\n**Interview:** State trade-offs — pick Snowflake or UUID v7 for distributed write-heavy.",
      "ID generation is early deep-dive in order/payment systems.",
      "Clock skew Snowflake? — Wait or use logical clock — NTP discipline.",
      "Expose sequential IDs publicly? — Enumeration risk — opaque encoding.",
      "Single DB auto-increment at 10K writes/sec",
      "UUID v4 as clustered index in SQL",
      "No plan for machine ID assignment"),
    q("Snowflake ID Architecture", "IDs", "Common",
      "Explain Twitter Snowflake ID layout and operational concerns.",
      "64 bits: 1 unused, 41 timestamp ms, 10 datacenter+worker, 12 sequence. Sortable, no DB coordination, ~4096 IDs/ms per worker.",
      "**Deployment:** ZooKeeper/etcd assigns worker IDs — avoid manual collision.\n\n**Clock backward:** Refuse to generate until caught up — or use sequence borrow.\n\n**vs UUID v7:** Snowflake denser, custom layout; UUID v7 standard interoperable.\n\n**Storage:** BIGINT column — efficient index vs 36-char UUID string.",
      "Snowflake is production-proven pattern architects should detail.",
      "Sequence exhaustion 4096/ms? — Add worker IDs or microshard generators.",
      "Parse ID for debugging? — Extract timestamp from bits — ops convenience.",
      "Duplicate worker IDs across datacenters",
      "Ignore clock synchronization",
      "Snowflake for public-facing sequential exposure without encoding"),
    q("UUID vs Sequential IDs", "IDs", "Common",
      "When UUID vs sequential BIGINT primary key?",
      "Sequential: better B-tree locality, smaller indexes, predictable — risk enumeration, single-writer hotspot. UUID: distributed generation, opaque — worse index fragmentation (v4), larger keys.",
      "**Mitigations:** UUID v7 time-ordered reduces fragmentation. **Hybrid:** BIGINT internal + public UUID external.\n\n**Postgres:** `gen_random_uuid()` vs `BIGSERIAL` — measure insert TPS.\n\n**Security:** Public APIs use opaque IDs — not sequential orderId.",
      "PK choice affects insert performance and security surface.",
      "COMB GUID? — Legacy SQL Server pattern — similar to UUID v7 goal.",
      "Distributed sequences? — Hi/Lo, segment allocation from DB.",
      "UUID v4 as PK on billion-row insert-heavy table without testing",
      "Sequential ID in public URL",
      "Ignore index fragmentation in estimate"),
    q("Design Interview Communication", "Interview Skill", "Very Common",
      "How structure thinking aloud in a 45-minute system design interview?",
      "Narrate framework: 'I'll clarify requirements, estimate, sketch high-level, then deep dive.' Pause for interviewer input. State assumptions explicitly. Check time at 15 and 30 minutes.",
      "**Techniques:** Think aloud not silent drawing. Label arrows. Say trade-offs: 'I chose X over Y because...'\n\n**Engagement:** 'Does this match what you're looking for?' after requirements.\n\n**Recovery:** Stuck → state options, pick one, justify. Better than freeze.\n\n**Close:** Reserve 5 min for failures, monitoring, evolution.",
      "Communication score is separate from technical score — practice narrating.",
      "Interviewer redirect? — Follow hint — they want specific depth.",
      "Whiteboard vs virtual? — Excalidraw — pre-practice tool fluency.",
      "Silent diagramming 10 minutes",
      "Defensive when challenged",
      "No time check — skip failure modes"),
]

WEEK_34_Q011_Q030 = [
    q("Cache-Aside Deep Dive", "Caching", "Very Common",
      "Walk through cache-aside on product detail page: read, write, delete flows.",
      "Read: cache get → miss → DB → set cache TTL 5m. Write: update DB → delete cache key (invalidate). Delete: DB delete → cache delete.",
      "**Why invalidate not update on write?** Avoid race: two writes reorder → stale cache if update not delete.\n\n**TTL:** Safety net if invalidation missed. **Jitter:** Random ±10% TTL prevents simultaneous expiry.\n\n**Negative cache:** Cache 'not found' briefly — prevent DB hammer on invalid SKU.",
      "Cache-aside nuances beyond the one-liner — interviewers probe write path.",
      "Read-through difference? — Cache layer loads on miss — app simpler.",
      "Write-through? — Write cache and DB sync — higher write latency.",
      "Update cache on write without invalidation strategy",
      "No TTL safety net",
      "Cache product object without version field"),
    q("Read-Through vs Write-Through Cache", "Caching", "Common",
      "When read-through or write-through vs cache-aside?",
      "Read-through: cache library loads from DB on miss — good when cache product owns loading. Write-through: every write goes to cache and DB synchronously — strong consistency, slower writes.",
      "**Cache-aside:** App orchestrates — most flexible, common in microservices.\n\n**Write-behind:** Write cache async flush to DB — fast writes, data loss risk on crash.\n\n**Choose write-through:** Financial balance display where cache must match DB. **Choose aside:** General CRUD with tolerance for brief staleness.",
      "Pattern choice reflects consistency vs latency trade-off.",
      "Write-behind use case? — Analytics counters — loss acceptable.",
      "Cache coherency multi-region? — Invalidation pub/sub across regions.",
      "Write-behind for payment balances",
      "Read-through without stampede protection",
      "Same pattern for all data types"),
    q("Cache Stampede Prevention", "Caching", "Very Common",
      "Hot product expires from cache — 10K requests hit DB simultaneously. Fix?",
      "Mutex per key: first request rebuilds, others wait or serve stale. Probabilistic early refresh. Request coalescing (singleflight pattern).",
      "**Singleflight:** `sync.Map` or Redis lock `SET key NX` — one winner rebuilds.\n\n**Stale-while-revalidate:** Return stale value while async refresh — user sees old price briefly.\n\n**Never:** Infinite TTL on hot keys without invalidation path.",
      "Stampede kills DB during exactly the moment cache should help.",
      "Lock timeout? — Prevent dead lock if builder crashes — TTL on lock key.",
      "Thundering herd on app deploy? — Warm cache before traffic shift.",
      "No protection on popular key expiry",
      "Blocking lock without timeout",
      "Drop requests instead of stale-while-revalidate"),
    q("CDN Cache Invalidation", "CDN", "Common",
      "Deploy new React bundle — how invalidate CDN without downtime?",
      "Prefer cache busting: filename hash `app.a1b2c3.js` — new deploy = new URL — no invalidation needed. Purge API only for HTML entry or emergency.",
      "**Immutable assets:** Long `Cache-Control: max-age=31536000, immutable` on hashed files.\n\n**HTML:** Short TTL or no-cache — points to latest hashed assets.\n\n**Invalidation cost:** CloudFront invalidation has limits and propagation delay — design around versioning.\n\n**API cache:** Selective purge by tag if edge caches API responses.",
      "Versioned filenames beat purge APIs in production deploys.",
      "Wildcard purge? — Expensive — last resort.",
      "Stale CDN after deploy? — Users on old HTML until TTL — acceptable brief window.",
      "Same filename every deploy",
      "Rely on manual CDN purge in CI without automation",
      "Cache personalized API responses at CDN without Vary"),
    q("Horizontal vs Vertical Scaling", "Scale", "Very Common",
      "When scale up (bigger VM) vs scale out (more instances)?",
      "Vertical first for stateful legacy or quick fix — ceiling at largest SKU. Horizontal for stateless web/API tiers — preferred long-term. DB vertical until shard required.",
      "**Vertical limits:** Single machine max RAM/CPU, no HA. **Horizontal needs:** Stateless app, shared session store, load balancer.\n\n**Cost curve:** 2× large VM often > 2× small VMs — but ops simplicity varies.\n\n**Interview:** 'Start vertical for DB primary; scale out app tier from day one if stateless.'",
      "Scale direction shows production pragmatism vs textbook only.",
      "Kubernetes vertical pod autoscaler? — Niche — horizontal default.",
      "DB scale up then read replicas then shard — classic sequence.",
      "Horizontal stateful app with in-memory session",
      "Vertical scale forever ignoring ceiling",
      "Shard before read replicas exhausted"),
    q("Database Read Replica Lag Handling", "Replication", "Very Common",
      "User updates profile then sees old name on next read — replica lag 2s. Solutions?",
      "Read-your-writes: route user's reads to primary for N seconds after write, or session stickiness to primary, or version check client-side.",
      "**Patterns:**\n1. **Primary read after write** — flag in session\n2. **Synchronous replica** — for critical reads (inventory)\n3. **Client polling** — return version token, client retries until match\n\n**Product tolerance:** Profile 2s lag maybe OK; payment status not OK.",
      "Replica lag is default — architects design read routing explicitly.",
      "Global Database (Spanner/Cosmos multi-write)? — Strong consistency — higher cost/latency.",
      "Monitor lag? — Alert replica lag > 5s — auto-failover read to primary.",
      "All reads to replica always",
      "No lag metric monitored",
      "Inventory check on async replica"),
    q("Sharding Key Selection Deep Dive", "Sharding", "Very Common",
      "Evaluate shard keys for global payments ledger.",
      "`userId`: good user history queries, hot whale users. `paymentId`: even write spread, bad user history (scatter). `regionId+userId`: locality + isolation.",
      "**Criteria:** High cardinality, even distribution, query patterns include shard key, avoid cross-shard transactions.\n\n**Hot key mitigation:** Salting `userId#bucket`, dedicated shard for whales.\n\n**Resharding:** Consistent hashing, dual-write migration — plan before 1TB.\n\n**Interview:** Justify with access patterns — no universal best key.",
      "Shard key is hardest migration — defend choice with queries listed.",
      "Cross-shard ACID? — Avoid — saga per payment flow.",
      "Monotonic shard split? — Split hot shard into two — rehash subset.",
      "Shard by month on infinite growth table",
      "Key not in 80% of queries",
      "No hot key detection plan"),
    q("Hot Partition Mitigation Strategies", "Sharding", "Common",
      "DynamoDB partition throttling on single hot partition — mitigation playbook?",
      "Detect via `ConsumedWriteCapacityUnits` per key. Write sharding: append random suffix to sort key. Burst capacity credits temporary. DAX cache for hot reads.",
      "**AWS:** Partition limit 3000 RCU/1000 WCU per partition — design sort key distribution.\n\n**Application:** Local in-process cache for celebrity key — 1s TTL.\n\n**Architecture:** Separate hot path — celebrity table or dedicated shard.\n\n**Prevention:** Load test with realistic Zipf distribution not uniform.",
      "Hot partitions appear at scale — proactive detection in design review.",
      "Write sharding read cost? — Scatter-gather on read — acceptable for writes.",
      "Kafka hot partition? — More partitions + keyed sub-partition salt.",
      "Assume uniform key distribution forever",
      "No CloudWatch per-key metrics",
      "Infinite retry on throttling"),
    q("Custom Autoscaling Metrics", "Cloud Scale", "Common",
      "Design autoscaling beyond CPU: custom metrics for order API.",
      "Scale on `requests_per_second`, `p95_latency`, and `queue_depth` composite. K8s HPA with Prometheus adapter. Scale-out aggressive, scale-in slow with cooldown.",
      "**Metrics:**\n- RPS from load balancer\n- Custom app metric: checkout queue length\n- Saturation: thread pool queue depth\n\n**Predictive:** Scheduled scale before Black Friday + reactive on RPS.\n\n**Avoid:** CPU-only when I/O bound waiting on DB.",
      "Custom metrics tie scaling to user-visible SLO not infrastructure proxy.",
      "KEDA? — Scale on Service Bus queue depth — event-driven workloads.",
      "Max instances cap? — Cost guardrail — alert before cap hit.",
      "CPU-only HPA on I/O-bound API",
      "Scale-in during active requests",
      "No cooldown — flapping"),
    q("Connection Pool Storms", "Database", "Common",
      "Deploy 50 new API pods — DB connections spike to 5000, DB max 500. Fix?",
      "Reduce per-pod pool size (10 not 100). PgBouncer/RDS Proxy connection multiplexer. Stagger rollout. Right-size pool: `max_connections / expected_pods`.",
      "**Formula:** `pool_per_instance = floor(DB_max * 0.8 / max_instances)`.\n\n**Proxy:** Transaction vs session pooling mode — know ORM compatibility.\n\n**Architect:** Connection budget in deployment checklist — same importance as CPU.",
      "Connection storms cause outages on deploy — architect prevents by math.",
      "RDS Proxy vs PgBouncer? — Managed vs self-hosted — similar role.",
      "Long idle connections? — Pool timeout — release to proxy.",
      "Default pool 100 per pod",
      "No connection proxy at scale",
      "Big bang deploy all pods simultaneously"),
    q("Async Processing at Scale", "Async", "Very Common",
      "Move order confirmation email off sync path — async architecture?",
      "Order API writes DB + outbox row → returns 201. Relay worker publishes `OrderConfirmed` → email consumer sends async. User sees confirmation page immediately.",
      "**Benefits:** Shorter p99 API latency, independent scaling of email workers, retry without blocking user.\n\n**UX:** Poll status or WebSocket if user must see 'email sent'.\n\n**Backpressure:** Queue depth triggers scale-out of consumers.",
      "Async is default architect response to non-critical path work.",
      "Transactional outbox? — Guarantees event published iff order saved.",
      "Poison email template? — DLQ — don't block order queue.",
      "Sync SMTP in checkout request",
      "No outbox — dual-write race",
      "Unbounded queue without consumer scale"),
    q("Message Queue Backpressure", "Messaging", "Common",
      "Queue depth growing faster than consumers process — backpressure strategy?",
      "Scale consumers (KEDA on queue depth). Throttle producers when depth > threshold. Shed load: reject new orders with 503. Priority queue: process paid orders first.",
      "**Signals:** Age of oldest message, depth, consumer lag.\n\n**Prevention:** Capacity plan consumers for peak × 1.5 headroom.\n\n**Cascading:** Don't unbounded buffer — memory explodes — push back to caller.",
      "Backpressure protects system from overload collapse.",
      "Dead letter before infinite retry? — Yes — poison stops pipeline.",
      "Batch consume? — Higher throughput — tune batch size vs latency.",
      "Unbounded in-memory queue",
      "Scale producers not consumers",
      "No alert on queue age"),
    q("Stateless Application Design", "Architecture", "Very Common",
      "What must leave the app server for true horizontal scale?",
      "Session state → Redis. Uploaded files → object storage. Job state → queue/DB. In-memory caches → shared Redis. Config → env/Key Vault not local file.",
      "**Stateless checklist:** Any pod can handle any request. Rolling deploy safe. No sticky session requirement.\n\n**Exceptions:** WebSocket connection state on gateway node — use Redis pub/sub bridge.\n\n**12-factor:** Processes disposable — crash OK, restart clean.",
      "Stateless is prerequisite for autoscale and zero-downtime deploy.",
      "Sticky sessions workaround? — Admit state on connection — document limitation.",
      "Local disk temp? — Ephemeral OK if reconstructable.",
      "Session in Tomcat memory",
      "Local file upload storage",
      "Assuming sticky LB solves everything"),
    q("Session Externalization with Redis", "Caching", "Common",
      "Design shared session store for 20 API instances.",
      "ASP.NET `AddStackExchangeRedisCache` or JWT-only stateless. Session: `sessionId` cookie → Redis hash `session:{id}` TTL 24h sliding.",
      "**Data in session:** UserId, tenantId, cartId — not large objects.\n\n**Security:** HttpOnly, Secure, SameSite cookie. Rotate session ID on login.\n\n**Failover:** Redis cluster with replication — session loss on failover acceptable brief re-login.",
      "External session enables scale and deploy without drain.",
      "JWT vs server session? — JWT scales better — revocation harder.",
      "GDPR session delete? — User delete purges Redis keys.",
      "20MB session object in Redis",
      "No TTL on session keys",
      "Redis single node no HA"),
    q("Content Hashing for Cache and CDN", "Caching", "Common",
      "Use content hashing in architecture — examples?",
      "Asset URLs: `bundle.[contenthash].js` — immutable CDN cache. API: ETag `If-None-Match` — 304 saves bandwidth. Dedup storage: hash blob → skip upload if exists.",
      "**ETag flow:** Server hashes response body → client sends `If-None-Match` → 304 no body.\n\n**Storage dedup:** Same file uploaded twice → one physical copy — backup systems use this.\n\n**Cache key:** Hash of normalized query params for search cache.",
      "Hashing enables efficient cache validation and storage deduplication.",
      "Weak vs strong ETag? — Byte-identical vs semantic equivalence.",
      "Hash algorithm? — SHA-256 for dedup; MD5 OK for cache key non-security.",
      "ETag ignored on large API responses",
      "Hash in URL for dynamic personalized content",
      "MD5 for security-sensitive dedup keys"),
    q("Edge Computing Architecture", "Edge", "Common",
      "When use edge compute (CloudFront Functions, Lambda@Edge) vs origin?",
      "Edge: auth token validation, geo routing, A/B test assignment, header rewrite, bot detection — sub-ms cold start. Origin: business logic, DB access.",
      "**Limits:** Edge runtime restricted CPU/memory — no DB connection pool.\n\n**Examples:** Block country at edge, inject `X-Experiment` header, resize image at edge.\n\n**Cost:** Per-invocation — cheap at volume vs round-trip to origin.",
      "Edge moves latency-sensitive logic closer to users.",
      "Workers vs Lambda@Edge? — Cloudflare Workers global — similar pattern.",
      "Edge KV cache? — Small config at edge — reduce origin hits.",
      "Full checkout logic at edge",
      "Edge function calls origin DB directly",
      "Ignore edge execution limits"),
    q("Global Traffic Routing", "Networking", "Common",
      "Route users to nearest healthy region — design?",
      "GeoDNS (Route 53 latency routing) or Anycast (Cloudflare). Health checks remove unhealthy region. Active-active or active-passive per SLA.",
      "**Latency routing:** Resolve to lowest-latency ALB. **Failover:** Primary unhealthy → secondary region.\n\n**Data:** Active-active needs conflict resolution or read-local write-global strategy.\n\n**Compliance:** EU users → EU region only — geofencing policy.",
      "Global routing is architecture for international products.",
      "DNS TTL trade-off? — Low TTL faster failover — higher DNS load.",
      "Split horizon DNS? — Internal vs external routing different.",
      "Single region for global users",
      "DNS TTL 3600 with no health check",
      "Active-active without conflict strategy"),
    q("Capacity Headroom Planning", "Capacity", "Common",
      "How much headroom above peak load should production maintain?",
      "20–40% headroom above measured peak for compute. 50% for critical path before auto-scale lag catches up. Load test at 2× expected peak annually.",
      "**Headroom covers:** Auto-scale delay (2–5 min), deploy surge, viral spike, AZ failure (lose 33% capacity).\n\n**Document:** Peak RPS from last Black Friday + growth factor.\n\n**Cost trade-off:** Reserved baseline + burst on-demand for headroom.",
      "Headroom is explicit capacity NFR — not accidental over-provision.",
      "Chaos test headroom? — Kill AZ during load test — validate surviving capacity.",
      "Queue-based absorption? — Queue adds temporal headroom — bounded buffer.",
      "100% utilized at peak — no scale room",
      "Never load test above production peak",
      "Headroom only on CPU not connections"),
    q("Performance Budgets at Scale", "Performance", "Common",
      "Define performance budget for search API at 50K RPS.",
      "p99 < 150ms end-to-end. Max 2 internal hops. Elasticsearch query < 80ms. Serialization < 10ms. Zero N+1 DB calls on search path.",
      "**Enforcement:** Load test gate in CI on PR touching search. RUM vs synthetic gap tracked.\n\n**Budget breakdown:** Network 20ms + gateway 10ms + service 80ms + ES 80ms — identify slack.\n\n**Regression:** Alert when p99 degrades 10% week-over-week.",
      "Performance budgets make NFR measurable and enforceable.",
      "Mobile budget? — Add 100ms RTT for 3G — separate target.",
      "Third-party API in budget? — Include or async exclude from sync path.",
      "No per-component budget",
      "Budget only measured in dev laptop",
      "Ignore regression alerts"),
    q("Load Test Interpretation", "Testing", "Common",
      "Load test: p50 50ms, p99 2000ms, errors 0.1% at target RPS. Interpret.",
      "Tail latency problem — likely GC pause, lock contention, slow dependency, or connection pool wait. 0.1% errors may be timeout under load — investigate before launch.",
      "**Analysis steps:**\n1. Trace slow p99 requests — distributed tracing\n2. Check DB slow query log during test\n3. Thread pool queue depth correlation\n4. Compare ramp vs steady state\n\n**Pass criteria:** p99 within SLO at 1.5× target RPS with <0.01% errors.",
      "Architects interpret load tests — not just run and screenshot.",
      "Coordinated omission? — Gatling/k6 handle better than naive JMeter — know tool bias.",
      "Soak test? — 4h run detects memory leak invisible in 10min test.",
      "Only report p50",
      "Ignore 0.1% errors as noise",
      "Load test without production-like data volume"),
]

WEEK_35_Q011_Q030 = [
    q("At-Least-Once Semantics Explained", "Semantics", "Very Common",
      "Why is at-least-once the practical default for distributed messaging?",
      "Networks, crashes, and ack timing make exactly-once delivery impossible without cooperation. Broker redelivers if ack lost — consumer may see duplicate — design idempotent handlers.",
      "**Guarantees:** At-most-once (fire forget, may lose). At-least-once (no loss, duplicates). Effectively-once (at-least-once + idempotency).\n\n**Examples:** Kafka, SQS, Service Bus default to at-least-once with ack.\n\n**Architect language:** Say 'we achieve effectively-once via idempotent consumer' not 'exactly-once'.",
      "Semantic precision is messaging interview baseline.",
      "Kafka exactly-once? — Transactional producer + idempotent consumer — bounded scope.",
      "Ordering + at-least-once? — Duplicates may arrive out of order — version handling.",
      "Assume broker delivers exactly once",
      "Ack before processing complete",
      "No dedup strategy documented"),
    q("The Exactly-Once Myth", "Semantics", "Very Common",
      "Interviewer asks for exactly-once payment processing. Respond?",
      "Acknowledge end-to-end exactly-once is impossible across heterogeneous systems. Propose effectively-once: idempotent payment API + unique business key + dedup store + outbox.",
      "**Layers:** DB TX exactly-once within one database. Cross-service: saga + idempotency keys.\n\n**Kafka EOS:** Exactly-once within Kafka streams pipeline — not your credit card processor.\n\n**Honest architect:** Name the boundary where guarantee holds and where idempotency takes over.",
      "Calling out the myth shows seniority — don't pretend magic broker flag.",
      "Two-phase commit across microservices? — Avoid — operational pain.",
      "Idempotency key storage? — Unique constraint on `paymentIdempotencyKey`.",
      "Claim exactly-once because Kafka flag enabled",
      "Distributed 2PC for all microservices",
      "No idempotency on payment handler"),
    q("Dead Letter Queue Operations", "Reliability", "Very Common",
      "Design operational runbook for DLQ depth > 100 messages.",
      "Alert on-call → sample 5 messages → classify: poison (bad schema), transient (downstream), bug. Fix root cause → replay tool re-publishes with same idempotency key → monitor DLQ drain.",
      "**Dashboards:** DLQ depth, age of oldest message, rate in vs out.\n\n**Access control:** DLQ may contain PII — restrict replay tool.\n\n**Automation:** Auto-replay transient after dependency healthy — manual approval for poison schema.",
      "DLQ ops separate toy design from production-ready messaging.",
      "DLQ per queue? — Payment DLQ pages immediately; analytics DLQ daily review.",
      "Retention? — DLQ messages retained 14 days — compliance.",
      "DLQ messages deleted without analysis",
      "No replay tooling",
      "Infinite retry instead of DLQ"),
    q("Poison Message Handling", "Reliability", "Very Common",
      "Message crashes consumer every time — poison pill. Architecture response?",
      "Max delivery count (SQS `maxReceiveCount: 5`) → route to DLQ. Circuit breaker stop consuming queue until fix deployed. Schema validation reject before handler.",
      "**Detection:** Same `messageId` in DLQ repeatedly after replay — classify poison.\n\n**Quarantine:** Move to poison store for manual inspection — don't block entire queue.\n\n**Prevention:** Contract tests on schema before deploy.",
      "Poison messages happen — architecture includes ejection not infinite loop.",
      "Skip poison without DLQ? — Lose message — unacceptable for payments.",
      "Canary consumer? — New version processes 1% traffic first.",
      "Infinite retry on same message",
      "No maxReceiveCount configured",
      "Replay poison without code fix"),
    q("Outbox Relay Worker Design", "Patterns", "Very Common",
      "Design outbox relay: poll interval, failure handling, ordering.",
      "Relay polls `Outbox` table `WHERE published_at IS NULL` batch 100. Publish to broker → mark published in same TX or follow-up TX with idempotent publish ID.",
      "**Polling vs CDC:** Debezium/Logic Apps trigger on insert — lower latency than 1s poll.\n\n**Failure:** Publish succeeds, mark fails → duplicate on retry — consumers idempotent.\n\n**Ordering:** Per-aggregate sequence in outbox — relay preserves order for same `aggregateId`.",
      "Outbox relay is critical path — design for failure not happy path.",
      "Relay lag metric? — `now() - min(unpublished.created_at)` — alert > 30s.",
      "Multiple relay instances? — `SELECT FOR UPDATE SKIP LOCKED` — no duplicate publish.",
      "Dual write API and broker without outbox",
      "Single-thread relay bottleneck unscaled",
      "No lag monitoring on outbox"),
    q("Inbox Pattern for Consumers", "Patterns", "Very Common",
      "Implement inbox pattern on order consumer.",
      "BEGIN TX → insert `Inbox(messageId)` unique → if conflict skip (duplicate) → process business logic → mark processed → COMMIT. Ack broker after TX commit.",
      "**Effectively-once:** Same `messageId` cannot process twice — DB constraint enforces.\n\n**Cleanup:** Archive processed inbox rows > 7 days.\n\n**Pair with outbox:** Producer outbox + consumer inbox = robust cross-service.",
      "Inbox completes the consumer side of reliable messaging.",
      "Inbox same DB as business data? — Yes — same TX boundary.",
      "Ack before commit? — Message lost if crash after ack — ack after commit.",
      "Process then check duplicate",
      "Ack before DB commit",
      "Inbox without unique constraint on messageId"),
    q("Event Choreography Walkthrough", "Events", "Common",
      "Choreograph `OrderPlaced` across inventory, payment, shipping without orchestrator.",
      "`OrderPlaced` → Inventory reserves → `InventoryReserved` → Payment charges → `PaymentCaptured` → Shipping labels → `OrderShipped`. Failures emit compensating events.",
      "**Pros:** Loose coupling, services autonomous. **Cons:** Hard to visualize — need event catalog diagram.\n\n**Compensation:** `PaymentFailed` → `InventoryReleased` listener.\n\n**Observability:** CorrelationId on every event — distributed trace across choreography.",
      "Choreography example shows you can narrate multi-step flows.",
      "Circular dependency? — Event cycle detection in CI catalog review.",
      "Timeout? — `OrderPlacementExpired` after 30 min no payment.",
      "Hidden orchestrator in monolith",
      "No compensation events defined",
      "Missing correlation ID"),
    q("Saga Orchestration on Azure", "Saga", "Common",
      "Implement orchestrated saga for checkout on Azure.",
      "Durable Functions orchestrator: call Inventory → Payment → Shipping activity functions. Built-in compensation handlers on failure. State persisted in orchestration history.",
      "**vs Service Bus sessions choreography:** Orchestrator central visibility — easier debug.\n\n**Timeout:** Orchestration timeout 30 min — auto compensate.\n\n**Idempotency:** Each activity checks idempotency key before side effect.",
      "Azure architects should know Durable Functions as saga engine option.",
      "Logic Apps for saga? — Low-code alternative — simpler flows.",
      "Human approval step? — External event wait in orchestrator.",
      "Choreography when team needs central visibility",
      "No compensation in orchestrator",
      "Orchestrator calls HTTP sync chain 30s each"),
    q("Message Ordering Keys", "Ordering", "Common",
      "Guarantee order of status updates per `orderId` — how?",
      "Partition key = `orderId` (Kafka) or Service Bus session = `orderId`. Single consumer per partition/session processes sequentially.",
      "**Trade-off:** Hot `orderId` with flood of updates — single consumer bottleneck — acceptable for order state machine.\n\n**Global order:** Not needed — per-aggregate order sufficient.\n\n**Out-of-order detection:** `version` field — ignore stale.",
      "Ordering keys scope parallelism correctly in messaging design.",
      "Kafka partition count? — More partitions more parallelism — order only within partition.",
      "Reorder buffer? — Small heap wait for gap fill — adds latency.",
      "Require global total order",
      "Random partition key for related events",
      "No version on status events"),
    q("Kafka Partition Strategy", "Kafka", "Common",
      "Choose partition count and key for clickstream topic: 100K events/sec.",
      "Partition key = `userId` — user session events ordered. Partition count ≥ max consumer parallelism — start 48–96, scale with throughput. Avoid key skew — monitor per-partition bytes/sec.",
      "**Rule of thumb:** Target 10–50 MB/s per partition. 100K small events/sec → many partitions.\n\n**Rebalance:** Add partitions — existing keys may move — plan consumer rebalance.\n\n**Compacted topic:** Config changes — key = config name — one value per key.",
      "Partition strategy directly caps throughput and ordering scope.",
      "Too few partitions? — Consumer idle — cannot scale past partition count.",
      "Hot key skew? — Salt key for writes — accept order loss on salted sub-key.",
      "Single partition for 'simplicity'",
      "Partition = consumer always false",
      "Never monitor partition skew"),
    q("Schema Registry with Avro", "Governance", "Common",
      "Why Avro + Schema Registry for event platform?",
      "Avro binary compact with embedded schema ID. Registry enforces backward/forward compatibility. Producers register schema v3 — consumers with v2 reader still work if compatible.",
      "**Azure:** Event Hubs with Schema Registry preview / Confluent on AKS.\n\n**Compatibility modes:** BACKWARD (new schema, old reader) — default for consumers-first deploy.\n\n**vs JSON:** Enforced contract — breaking changes caught in CI not production.",
      "Schema registry is governance for event-driven architecture at scale.",
      "Subject naming? — `order-value` per topic value schema.",
      "Delete schema? — Soft delete — old messages still reference ID.",
      "Unversioned JSON events in production",
      "Breaking field rename without version bump",
      "Deploy producer before consumer on backward incompatible change"),
    q("CloudEvents Envelope Standard", "Standards", "Occasional",
      "Wrap domain events in CloudEvents — what fields and why?",
      "Required: `id`, `source`, `specversion`, `type`, `time`. Optional: `datacontenttype`, `subject`, `data`. Enables uniform routing, logging, and cross-cloud tooling.",
      "**Example:**\n```json\n{\"specversion\":\"1.0\",\"type\":\"com.shop.order.placed\",\"source\":\"/orders\",\"id\":\"uuid\",\"data\":{...}}\n```\n\n**Benefits:** Azure Event Grid native support, observability filters on `type`.",
      "Standards literacy shows maturity in event platform design.",
      "CloudEvents vs custom envelope? — Standard wins multi-team integration.",
      "Binary mode? — HTTP headers carry metadata — smaller body.",
      "Bare JSON blob no metadata",
      "Duplicate `id` across events",
      "No `type` for router filtering"),
    q("Message Size Limits and Blob Reference", "Patterns", "Common",
      "Event payload is 5MB PDF — Service Bus limit 256KB. Pattern?",
      "Upload blob to storage → event carries `{ blobUrl, contentType, checksum }` only. Consumer fetches blob on process. Claim check pattern.",
      "**Limits:** SQS 256KB, Service Bus 256KB standard, Event Hubs 1MB. Kafka configurable ~1MB default.\n\n**Security:** SAS token or managed identity on blob read — not public URL.\n\n**Cleanup:** Lifecycle policy delete blob after consumer ack.",
      "Large payload reference pattern is messaging essential.",
      "Compress then send? — May still exceed limit — blob reference safer.",
      "Inline base64 5MB? — Blocks broker and consumers — anti-pattern.",
      "5MB in message body",
      "Public blob URL in event",
      "No blob cleanup after process"),
    q("Idempotent Consumer Design", "Patterns", "Very Common",
      "Design idempotent `PaymentCaptured` consumer.",
      "Unique `messageId` in `ProcessedEvents` table. Business logic in TX: if already processed return success. Use natural idempotency: `UPDATE balance WHERE paymentId=X` idempotent.",
      "**Levels:**\n1. Message dedup (inbox)\n2. Business key idempotency (paymentId)\n3. State check (if status already Captured, skip)\n\n**Ack:** Only after durable record of processing.",
      "Idempotent consumer is non-negotiable for at-least-once brokers.",
      "Redis dedup set? — Faster than DB — TTL matches broker retention.",
      "Partial failure? — TX rollback — message redelivered — safe retry.",
      "Insert without unique constraint",
      "Side effect before dedup check",
      "Ack on receive not process"),
    q("Retry with Exponential Backoff", "Resilience", "Very Common",
      "Configure retry for transient downstream failure in message handler.",
      "Retry 1: 1s, 2: 2s, 3: 4s, 4: 8s + jitter. Max 5 attempts → DLQ. Non-transient (400 validation) → DLQ immediately no retry.",
      "**Jitter:** `delay * (0.5 + random())` — desynchronize consumers.\n\n**Visibility timeout:** SQS visibility ≥ max processing time — else duplicate processing.\n\n**Idempotency:** Required — retry causes duplicate attempts.",
      "Retry policy is architect-specified not library default.",
      "Infinite retry? — Blocks queue — always cap.",
      "Retry storm on outage? — Circuit breaker pause all retries.",
      "Fixed 1s retry forever",
      "Retry on validation error",
      "No jitter — thundering herd on recovery"),
    q("Circuit Breaker in Messaging", "Resilience", "Common",
      "Payment service down — message consumers keep retrying. Circuit breaker design?",
      "After 5 failures in 60s, open circuit — nack messages to queue with delay without calling payment. Half-open: probe one message. Close on success.",
      "**Polly / custom:** Share circuit state across consumer instances via Redis.\n\n**Queue growth:** Expected during outage — alert depth not false positive if circuit working.\n\n**Bulkhead:** Separate consumer pool for payment vs notification.",
      "Circuit breaker prevents retry storm amplifying outage.",
      "Fallback on open? — Queue for manual review — not fake success.",
      "Health check endpoint? — Probe payment `/health` before half-open.",
      "Tight retry loop hammers dead service",
      "Per-message circuit without shared state",
      "Circuit open drops messages"),
    q("Additive Event Versioning", "Governance", "Common",
      "Evolve `OrderPlaced` v1 → v2 adding optional `loyaltyPoints` field.",
      "Additive only — v2 consumers read v1 events (default 0 points). v1 consumers ignore unknown fields if using tolerant reader. Schema registry BACKWARD compatibility.",
      "**Deploy order:** Register v2 schema → deploy consumers → deploy producers.\n\n**Breaking change:** New event type `OrderPlacedV2` or new topic — parallel run migration.",
      "Additive versioning is default safe evolution strategy.",
      "Remove field? — Breaking — new event type required.",
      "Rename field? — Add new, deprecate old, dual-write transition.",
      "Rename `amount` to `total` in place",
      "Required new field on old events",
      "No schema compatibility check in CI"),
    q("Pub/Sub vs Queue Decision Matrix", "Patterns", "Very Common",
      "Invoice generated — notify accounting (one consumer) and email (another). Pattern?",
      "Pub/sub topic `InvoiceGenerated` — accounting subscription + email subscription independent. If accounting must process exactly once alone — dedicated queue for accounting, pub/sub for fan-out notifications.",
      "**Queue:** Competing consumers, work distribution, one processor wins. **Pub/sub:** Broadcast, each subscriber gets copy.\n\n**Hybrid:** Topic → subscriptions some queue-backed (Service Bus topics/subscriptions).",
      "Pattern matrix prevents wrong semantics under load.",
      "Fan-out cost? — N subscribers × message size — FinOps aware.",
      "Filter subscriptions? — `amount > 10000` routing — avoid wrong handlers.",
      "Queue for email+SMS+push broadcast",
      "Pub/sub for job queue work distribution",
      "No dead letter on subscriptions"),
    q("Webhook Reliability Design", "Integration", "Common",
      "Your SaaS sends webhooks to customer endpoints — reliability design?",
      "At-least-once delivery with signed payload, exponential retry 24h, DLQ for failed endpoints, customer idempotency via `eventId`, disable endpoint after 7 days failure.",
      "**Security:** HMAC signature `X-Signature`, timestamp anti-replay.\n\n**UX:** Customer dashboard shows delivery log, manual replay button.\n\n**Ordering:** Per-customer sequence number — customer handles out-of-order.",
      "Webhook design mirrors event platform consumer concerns in reverse.",
      "Stripe webhook pattern? — Reference implementation study.",
      "Concurrent webhooks? — Limit per customer — don't DDoS their server.",
      "Fire-and-forget single HTTP attempt",
      "No signature verification docs",
      "No endpoint health disable logic"),
    q("Async API SLA Definition", "SLA", "Common",
      "Define SLA for async `POST /reports` returning 202 Accepted.",
      "202 immediately < 500ms. Report ready within 15 min p99. Status endpoint `GET /reports/{id}`. Webhook or poll when complete. Failed generation alert within 1 min.",
      "**SLA components:** Acceptance latency, processing duration, availability of status API, delivery notification latency.\n\n**User contract:** Document percentiles not averages.\n\n**Overload:** 503 with `Retry-After` when queue > capacity — SLA excludes customer retry after 503.",
      "Async APIs need processing SLA — not just HTTP response time.",
      "Cancellation SLA? — `DELETE /reports/{id}` stops job if not started.",
      "Priority tiers? — Enterprise 5 min p99, free 60 min.",
      "202 with no processing time commitment",
      "No status endpoint",
      "SLA on average only hiding tail"),
]

WEEK_36_Q011_Q030 = [
    q("E-Commerce Cart and Checkout", "Capstone", "Very Common",
      "Design cart and checkout for 50K orders/hour peak.",
      "Cart in Redis (userId/session keyed, TTL 7d). Checkout: validate cart → reserve inventory (TTL 15m) → payment → create order → clear cart. Idempotent checkout endpoint.",
      "**Cart merge:** Login merges anonymous cart to user cart — conflict resolution last-write-wins per SKU.\n\n**Abandoned cart:** Event for marketing — async.\n\n**Scale:** Redis cluster, checkout API stateless, order write to primary DB.",
      "Cart/checkout is capstone bread-and-butter — practice end-to-end.",
      "Guest checkout? — Session cart — email capture before payment.",
      "Cart price staleness? — Revalidate prices at checkout — not cart add time.",
      "Cart in SQL row per session",
      "No inventory reservation TTL",
      "Checkout without idempotency key"),
    q("Payment PCI Boundaries", "Security", "Very Common",
      "Draw PCI scope boundary for e-commerce checkout.",
      "Card data never touches merchant servers — Stripe Elements/Adyen hosted fields tokenize → merchant gets `paymentMethodId` only. SAQ A scope smallest.",
      "**In scope if:** You store, process, or transmit PAN. **Out of scope:** Token references only.\n\n**Architect diagram:** Browser → payment provider → webhook → order service. Merchant DB stores last4 + brand only.\n\n**Network:** CDE segmented if any custom card handling — avoid.",
      "PCI boundary drawing is security capstone question.",
      "Webhook authenticity? — Verify Stripe signature — prevent fake paid events.",
      "Refund flow? — API to provider with original charge ID — idempotent.",
      "POST card number to your API",
      "Log full payment request body",
      "PAN in database encrypted 'for convenience'"),
    q("Order Fulfillment Flow", "Capstone", "Very Common",
      "Design order fulfillment from payment capture to delivery notification.",
      "`PaymentCaptured` → warehouse pick list → ship label API → `ShipmentCreated` → carrier tracking webhook → `Delivered` → customer notification.",
      "**WMS integration:** Async queue to warehouse system — not sync in checkout.\n\n**Partial shipment:** Order line items ship independently — sub-state per line.\n\n**Saga:** Cancel order before ship → refund + restock compensation.",
      "Fulfillment connects e-commerce to logistics — common extension question.",
      "Split warehouse? — Route line items to nearest stock — orchestration rules.",
      "International customs? — Hold state until docs — async step.",
      "Sync warehouse API in checkout",
      "No shipment state machine",
      "Missing carrier webhook idempotency"),
    q("Inventory Consistency Model", "Consistency", "Very Common",
      "Prevent overselling 1 unit left, two buyers checkout simultaneously.",
      "Optimistic: `UPDATE stock SET qty=qty-1 WHERE sku=X AND qty>0` — rows affected 0 → sold out. Or pessimistic lock row for high contention SKU.",
      "**Reservation:** Hold stock on checkout start, release on timeout/payment fail.\n\n**Read path:** Product browse may use replica; stock check at payment uses primary or sync read.\n\n**Eventual:** Analytics inventory OK lagging; checkout not.",
      "Inventory is classic consistency interview fork.",
      "Distributed inventory multi-warehouse? — Reserve at specific warehouse node.",
      "Negative stock allowed? — Backorder business rule — explicit ADR.",
      "Check-then-act race on replica read",
      "No reservation TTL",
      "Cache stock count for checkout decision"),
    q("Product Catalog at Scale", "Capstone", "Common",
      "10M SKUs, 100K catalog reads/sec — architecture?",
      "CDN for product images. API cache (Redis) for product JSON. DB sharded by `categoryId` or read replicas. Search index separate (Elasticsearch) fed by CDC.",
      "**Write:** Admin updates infrequent — invalidate cache on change.\n\n**Bulk import:** Nightly batch — not inline API.\n\n**Attributes:** JSONB or EAV for variant attributes — index hot facets in search only.",
      "Catalog read-heavy — optimize read path not write.",
      "GraphQL product API? — DataLoader batch — prevent N+1.",
      "Seasonal catalog? — Pre-warm cache before campaign launch.",
      "10M JOIN query per product page",
      "No CDN on product images",
      "Single MySQL for 100K reads/sec"),
    q("Recommendation Pipeline Architecture", "ML Ops", "Common",
      "Design product recommendation for homepage — real-time vs batch?",
      "Batch: nightly collaborative filtering → feature store. Real-time: session events (views, cart) → stream processor updates short-term scores. API merges batch + real-time at request.",
      "**Components:** Clickstream → Kafka → Flink/Spark → Redis feature store → Rec API → fallback popular items.\n\n**Cold start:** New user → category bestsellers.\n\n**Latency budget:** Rec service < 50ms — precompute heavy work.",
      "Recommendation shows batch + stream hybrid thinking.",
      "A/B test rec models? — Shadow traffic compare CTR.",
      "Explainability? — 'Because you viewed X' — product requirement.",
      "ML model inference 2s in request path",
      "No fallback when rec service down",
      "Train on production checkout without PII governance"),
    q("Fraud Detection Hook", "Security", "Common",
      "Where hook fraud check in checkout without blocking p99?",
      "Sync rules engine (< 50ms): velocity, blocklist, AVS mismatch → decline. Async ML scoring post-auth → cancel/shipment hold if fraud score high. Risk tier by order amount.",
      "**Integration:** Stripe Radar or custom rules service. **False positive:** Manual review queue not auto-cancel happy customers.\n\n**Data:** Device fingerprint, IP geo, account age signals.",
      "Fraud is risk trade-off — architect shows layered sync/async approach.",
      "Chargeback workflow? — Evidence collection automated — ops tooling.",
      "Guest checkout fraud? — Stricter rules — higher friction acceptable.",
      "No fraud check on high-value orders",
      "2s ML model in sync checkout",
      "Auto-decline with no review path"),
    q("Multi-Region Active-Active E-Commerce", "Availability", "Common",
      "Active-active regions for global storefront — hardest problems?",
      "Inventory split per region, cart/session sticky or replicated, price catalog eventually consistent, payment in local currency region, conflict on rare cross-region account edits.",
      "**Cosmos DB / CRDTs:** For session-like data. **Inventory:** Don't share single stock pool without reservation protocol.\n\n**DNS:** Geo route to nearest. **Compliance:** EU data stays EU.",
      "Active-active capstone shows you know conflict resolution cost.",
      "Split brain inventory? — Regional stock pools — transfer between regions async.",
      "Global cart? — Replicate cart state — merge on conflict — last-write-wins SKU qty.",
      "Single global inventory counter active-active",
      "No conflict resolution strategy",
      "Sync replication cross-region for all data"),
    q("DR RPO and RTO Targets", "DR", "Very Common",
      "Set RPO/RTO for e-commerce: payments vs catalog vs analytics.",
      "Payments: RPO 0–1 min, RTO 15 min (sync/near-sync). Catalog: RPO 1h, RTO 4h. Analytics: RPO 24h, RTO 48h acceptable.",
      "**RPO:** Max data loss tolerated. **RTO:** Max downtime tolerated.\n\n**Mechanisms:** Sync repl for payments, async for catalog, rebuild analytics from raw events.\n\n**Game day:** Quarterly failover drill measures actual RTO.",
      "Tiered RPO/RTO by data class is mature DR answer.",
      "Backup encryption? — Separate keys per region.",
      "Runbook automation? — Terraform failover — reduce human RTO.",
      "Same RPO=0 for analytics warehouse",
      "Untested backup restore",
      "No business sign-off on RPO trade-offs"),
    q("Cost Model at Scale", "FinOps", "Common",
      "Build order-of-magnitude cost model for 10K orders/hour platform.",
      "Compute: 20 API instances $2K/mo. DB: RDS multi-AZ $3K. Redis $800. Egress/CDN $1.5K. Messaging $400. Search cluster $2K. Total ~$10K/mo — validate with pricing calculator.",
      "**Unit economics:** $/1000 orders — track as scale metric.\n\n**Drivers:** DB and egress dominate — cache and CDN reduce both.\n\n**Optimize:** Reserved instances baseline, spot for batch workers.",
      "Cost model closes capstone — architects speak finance.",
      "Serverless checkout? — Compare step functions cost at volume.",
      "FinOps tagging? — Cost per tenant/team allocation.",
      "No egress in model",
      "On-demand only at steady high load",
      "Ignore messaging and search cost"),
    q("Observability SLO Dashboard", "Observability", "Common",
      "Design SLO dashboard for e-commerce platform launch.",
      "Tiles: checkout success rate (SLO 99.5%), p99 checkout latency, payment provider error rate, order queue depth, error budget burn rate. RED metrics per service.",
      "**Layers:** Business (orders/min), golden signals (latency, traffic, errors, saturation), infrastructure.\n\n**Burn alert:** 2% budget burn in 1h pages on-call.\n\n**Launch:** Compare canary vs baseline dashboard side-by-side.",
      "SLO dashboard proves operability not just feature design.",
      "Synthetic checkout? — Probe every 1 min from 3 regions.",
      "Trace sampling? — 100% on checkout path errors.",
      "CPU dashboard only",
      "No error budget concept",
      "SLO measured after launch not before"),
    q("On-Call Escalation Design", "Operations", "Common",
      "Design on-call escalation for payment failures spike.",
      "L1 alert → primary on-call 5 min. Unacked → secondary 10 min. Sev1 → engineering manager + incident channel. Runbook link in alert. Auto-incident ticket.",
      "**Severity matrix:** Sev1 payment down all users, Sev2 elevated errors, Sev3 single tenant.\n\n**Noise reduction:** Alert on SLO burn not single error.\n\n**Handoff:** Document timeline in status page.",
      "Operations design completes production-ready capstone.",
      "PagerDuty vs Opsgenie? — Tool agnostic — workflow matters.",
      "Post-incident review? — Blameless RCA within 48h mandatory.",
      "Alert every error log line",
      "No runbook linked",
      "Escalation to wrong team no routing"),
    q("Launch Checklist Architecture", "Operations", "Common",
      "Architecture items on go-live checklist for new marketplace?",
      "Load test 2× peak passed, DR drill completed, secrets rotated, WAF rules active, rate limits configured, rollback tested, feature flags default safe, monitoring dashboards live, on-call schedule confirmed.",
      "**Rollback:** Blue-green or canary — one-click revert validated.\n\n**Data migration:** Verified row counts checksum.\n\n**Compliance:** PCI scan, privacy policy updated.",
      "Launch checklist separates architect from diagram-only designer.",
      "Dark launch? — Traffic mirror to new stack — compare responses.",
      "Kill switch? — Feature flag disable checkout v2 instantly.",
      "Go live Friday 5pm",
      "No rollback test",
      "Skip load test 'we'll monitor'"),
    q("Post-Launch Hypercare", "Operations", "Common",
      "First 72 hours after launch — hypercare architecture focus?",
      "War room dashboard, 2× on-call staffing, lowered alert thresholds, hourly error budget review, freeze non-critical deploys, capture top 10 errors for hotfix priority.",
      "**Metrics watch:** Conversion funnel drop, p99 regression, new error types, queue depth trends.\n\n**Feedback loop:** Support ticket tags → engineering triage daily.\n\n**Exit criteria:** 48h within SLO → return to normal ops.",
      "Hypercare plan shows you've shipped production systems.",
      "Canary metrics? — 5% traffic 24h before 100% ramp.",
      "Rollback trigger? — Pre-defined: checkout success < 98% for 10 min.",
      "Immediate feature deploys day 1",
      "Normal alert thresholds too noisy day 1",
      "No war room communication channel"),
    q("Technical Debt Paydown Strategy", "Evolution", "Common",
      "Year 2 platform — prioritize tech debt: monolith checkout, no tests, manual deploy.",
      "Score by risk × pain: checkout modularity first (revenue), CI/CD second (deploy risk), test coverage on payment path third. 20% sprint capacity reserved.",
      "**Strangler:** Extract payment service first — highest change frequency.\n\n**ADR:** Document debt accepted vs scheduled paydown.\n\n**Metrics:** Deploy frequency, MTTR, change failure rate — DORA metrics improve as debt pays down.",
      "Debt strategy shows strategic architect not rewrite zealot.",
      "Boy scout rule? — Leave module better than found — incremental.",
      "Debt budget negotiation? — Product buys 20% with velocity data.",
      "Big bang rewrite year 2",
      "Pay down cosmetic debt first",
      "No measurable outcome for debt sprint"),
    q("Monolith to Services Evolution", "Evolution", "Very Common",
      "Extract services from e-commerce monolith — extraction order?",
      "1) Notifications (low risk), 2) Search (read-only), 3) Catalog (read-heavy), 4) Checkout (high risk last). Strangler route traffic via gateway.",
      "**Triggers:** Team size > 8 on monolith, deploy weekly → daily need, independent scale search.\n\n**Data:** Start with shared DB anti-pattern acceptable briefly — split DB per service later.\n\n**Events:** Introduce bus at first extraction — enables next.",
      "Evolution order minimizes revenue risk — architects sequence carefully.",
      "Checkout first? — Highest risk — extract after pattern proven.",
      "Shared database forever? — Interim — plan bounded context split.",
      "Microservices day 1 for 5 devs",
      "Extract without integration tests",
      "Big bang database split"),
    q("ADR for Major Architecture Decisions", "Governance", "Common",
      "Write ADR outline for choosing SQL vs NoSQL for orders.",
      "Title, status, context, decision, consequences. Orders: need ACID, relations, reporting → PostgreSQL. Consequences: shard later at write limit, team SQL skilled.",
      "**ADR library:** Checkout SQL, catalog flexible attributes JSONB, search Elasticsearch.\n\n**Review:** Architecture review board quarterly reads ADRs.\n\n**Supersede:** ADR-012 replaces ADR-003 when migrate to Cockroach — link history.",
      "ADR practice shows governance maturity in capstone.",
      "When not ADR? — Reversible trivial choices — library version bump.",
      "Stakeholder sign-off? — ADR appendix with product/security approval.",
      "Verbal decision no record",
      "ADR without rejected alternatives",
      "Decision without consequences listed"),
    q("Stakeholder Architecture Review", "Communication", "Common",
      "Present architecture to non-technical executives — structure?",
      "Business outcome first (faster checkout → +2% conversion). One diagram max. Three risks with mitigations. Cost range not false precision. Decision needed from them.",
      "**Avoid:** Technology alphabet soup. **Use:** Analogies, SLA in business terms (downtime = $X/hour).\n\n**Q&A:** Prepare 'why not build in-house payment' answer.",
      "Stakeholder communication is architect core skill tested in capstone.",
      "Technical deep-dive appendix? — Optional doc for CTO not in meeting.",
      "Record decision? — Meeting notes → ADR status accepted.",
      "60-slide architecture deck",
      "No ask — meeting without decision",
      "Dismiss budget concerns"),
    q("10x Growth Plan", "Evolution", "Very Common",
      "Platform at 1K orders/hour — plan for 10K (10x) without rewrite.",
      "Phase 1: Redis cache catalog (10× read relief). Phase 2: read replicas. Phase 3: checkout async notifications. Phase 4: DB shard by tenant. Metrics trigger each phase.",
      "**Bottleneck order:** Usually read path → connection pool → write DB → external APIs.\n\n**Cost:** Linear if cache effective; superlinear if skip cache and shard late.\n\n**Team:** Don't extract microservices until org scale warrants.",
      "10x plan shows measured evolution not premature scale.",
      "100x same plan? — Identify which phase breaks — Kafka, regional, etc.",
      "Load test per phase? — Validate headroom before next growth wave.",
      "Shard at 1K orders/hour",
      "10x plan requires full rewrite",
      "No metrics-defined triggers between phases"),
    q("Whiteboard Mock Evaluation Rubric", "Interview Skill", "Common",
      "Self-evaluate whiteboard mock — scoring rubric categories?",
      "Requirements (15%), estimation (10%), diagram (15%), deep dive (25%), failures (15%), evolution (10%), communication (10%). Score 0–5 each → /100. Target ≥75 pass.",
      "**Deep dive:** Trade-offs named, schema shown, numbers used.\n\n**Failures:** At least 3 scenarios with mitigation.\n\n**Practice log:** Track weak category weekly — estimation common gap.",
      "Rubric turns vague 'practice more' into measurable improvement.",
      "Peer review? — Partner scores blind — calibrate harshness.",
      "Record replay? — Catch filler words and silent periods.",
      "Score only 'felt ok'",
      "Skip failure section every time",
      "No timed 45-min practice"),
]

ALL_WEEKS_33_36_Q011_Q030 = {
    33: WEEK_33_Q011_Q030,
    34: WEEK_34_Q011_Q030,
    35: WEEK_35_Q011_Q030,
    36: WEEK_36_Q011_Q030,
}
