"""Hand-crafted premium Q011–Q030 for Weeks 7–8 — SQL Server and PostgreSQL."""

from premium_qa_data import q

WEEK_7_Q011_Q030 = [
    q("Non-Clustered Covering Index", "Indexing", "Very Common",
      "Design a non-clustered covering index for a high-volume order lookup query. What goes in the key vs INCLUDE?",
      "Key columns: equality and range predicates in WHERE/JOIN order. INCLUDE: SELECT columns only — avoids key lookup. Covering index serves query entirely from NC index leaf.",
      "**Example query:**\n```sql\nSELECT OrderId, Status, TotalAmount\nFROM Orders\nWHERE CustomerId = @id AND OrderDate >= @from\nORDER BY OrderDate DESC;\n```\n\n**Index:**\n```sql\nCREATE NONCLUSTERED INDEX IX_Orders_CustomerDate\nON Orders (CustomerId, OrderDate DESC)\nINCLUDE (Status, TotalAmount);\n```\n\n**Architect rules:**\n- Leading key column = most selective equality filter (`CustomerId`)\n- `OrderDate` in key supports range + sort — avoids separate sort operator\n- INCLUDE only columns needed — wider index = slower writes\n\n**Verify:** Plan shows **Index Seek** + **Key Lookup absent** — `SELECT` columns in INCLUDE only.\n\n**Trade-off:** Each NC index adds write overhead on INSERT/UPDATE — cap indexes per table via review.",
      "Covering indexes are the primary tool architects use to eliminate key lookups at scale.",
      "When is key lookup acceptable? — Few rows returned (<100) — lookup cost negligible.",
      "INCLUDE vs composite key? — Key affects sort/group; INCLUDE is payload only.",
      "INCLUDE every SELECT column — bloated index",
      "Wrong key column order — scan instead of seek",
      "No plan verification after index deploy"),
    q("Query Execution Plan Reads", "Performance", "Very Common",
      "How do you interpret logical reads vs physical reads in a SQL Server execution plan?",
      "Logical reads = pages read from buffer cache (8 KB pages). Physical reads = disk I/O. High logical reads on hot query = missing/wrong index or scan. Physical reads on repeat execution = memory pressure or cold cache.",
      "**Reading plans:**\n- **Table/Index Scan** — high reads, bad on large tables\n- **Index Seek** — starts at key, reads subset\n- **Key Lookup (RID/Bookmark Lookup)** — NC seek + clustered fetch per row — expensive at volume\n\n**SET STATISTICS IO ON:**\n```\nTable 'Orders'. Scan count 1, logical reads 45000\n```\n\n**Architect workflow:**\n1. Baseline logical reads per critical query at p95 row count\n2. Compare after index change — target 10–100x reduction on scans\n3. Correlate with `sys.dm_os_wait_stats` PAGEIOLATCH if physical reads dominate\n\n**Cardinality estimates:** Wildly wrong estimates → bad join order — update statistics or use Query Store forced plan only after root-cause fix.",
      "Logical reads are the architect's unit of cost — cheaper than guessing from elapsed time alone.",
      "Actual vs estimated rows? — >10x off signals stale stats or parameter sniffing.",
      "Read-ahead reads? — Sequential prefetch — normal for large scans.",
      "Tune only elapsed time ignoring IO",
      "Accept 50K logical reads on OLTP point query",
      "Force plan without measuring reads before/after"),
    q("Isolation Levels Deep Dive", "Transactions", "Very Common",
      "Walk through a money-transfer scenario under Read Committed, Repeatable Read, Serializable, and RCSI. What anomalies remain?",
      "Read Committed: no dirty reads; balance can change between statements. Repeatable Read: same row stable; phantoms possible. Serializable: range locks prevent phantoms; deadlock risk. RCSI: row versions — readers don't block writers; statement-level consistency.",
      "**Transfer $100 A→B under RC:**\n1. Read A balance 500 ✓\n2. Concurrent debit A 400 → committed\n3. Read A again 100 — overdraft if app assumed 500\n\n**Fix with app:** `UPDLOCK, HOLDLOCK` on debit row or Serializable for transfer SP only.\n\n**RCSI:** `READ_COMMITTED_SNAPSHOT ON` — readers use tempdb version store. Writers never blocked by readers — great for read-heavy OLTP. **Cost:** tempdb version store growth; long transactions block cleanup.\n\n**Snapshot isolation (allow_snapshot_isolation):** Transaction sees point-in-time start snapshot — good for long report inside txn.\n\n**Architect:** Default RC + RCSI for most OLTP; escalate to Serializable only on ledger critical sections; document in ADR.",
      "Isolation is a product decision — architects map financial rules to SQL semantics.",
      "Lost update without proper locking? — Two reads same balance both write — use rowversion optimistic concurrency.",
      "Hint OPTIMIZE FOR SERIALIZABLE scope? — Prefer explicit isolation in procedure.",
      "Serializable on all API calls",
      "RCSI without tempdb monitoring",
      "No rowversion on balance updates"),
    q("Always On AG Failover", "HA/DR", "Very Common",
      "Design automatic failover for Always On AG. What must the application handle?",
      "Sync replica + cluster quorum + listener. Automatic failover on node failure ~30–90s. App: `MultiSubnetFailover=True`, retry transient errors (40613, 40197), connection pool drain on failover.",
      "**Topology:**\n- Primary + sync secondary same region (RPO=0)\n- Async DR replica (RPO = lag)\n- Cloud witness or file share witness for quorum\n\n**Failover sequence:**\n1. WSFC detects node loss\n2. Secondary promoted\n3. Listener DNS updates to new primary\n4. In-flight connections fail — **apps must retry**\n\n**.NET pattern:**\n```csharp\nservices.AddDbContext<AppDb>(o => o.UseSqlServer(conn,\n    sql => sql.EnableRetryOnFailure(maxRetryCount: 5)));\n```\n\n**Readable secondary:** `ApplicationIntent=ReadOnly` — route reports; accept replication lag.\n\n**Architect:** Load test failover quarterly — measure RTO against SLO.",
      "Failover is an application contract — not invisible to code.",
      "Forced manual failover when? — Patching primary — planned failover to secondary.",
      "Distributed AG for geo? — Chain AGs across regions — complex DR topology.",
      "Hard-coded server name not listener",
      "No retry on failover during deploy",
      "Assume readable secondary is real-time"),
    q("Partitioning SWITCH", "Scale", "Common",
      "Explain `ALTER TABLE ... SWITCH PARTITION` for archive. What constraints must hold?",
      "SWITCH moves data between aligned partitioned tables instantly — metadata operation. Staging table must match schema, indexes, check constraints, and live on same filegroup/partition scheme.",
      "**Archive pattern:**\n```sql\n-- Staging table same structure as Orders\nALTER TABLE Orders SWITCH PARTITION 1 TO OrdersArchive PARTITION 1;\n```\n\n**Requirements:**\n- Partition schemes aligned (same function)\n- Indexes aligned on partition key\n- CHECK constraint on staging enforces partition boundary\n- No foreign keys referencing switched partition without disable\n\n**Architect:** Monthly sliding window — new empty partition, switch old to archive, backup/drop archive partition. **Sub-second** vs DELETE millions of rows.\n\n**Pitfall:** SWITCH to table on different filegroup without alignment fails.",
      "SWITCH is how architects meet data-retention SLAs without maintenance-window DELETE.",
      "Split partition function? — Add boundary before SWITCH IN new month.",
      "MERGE partition boundary? — Remove old boundary after archive dropped.",
      "Non-aligned indexes on partitioned table",
      "SWITCH without matching CHECK on staging",
      "FK constraints blocking SWITCH"),
    q("Tempdb Contention Fixes", "Performance", "Common",
      "Production shows PFS/SGAM latch waits on tempdb. What is your remediation plan?",
      "Add tempdb data files (1 per CPU up to 8), equal size/growth, right-size memory to reduce spills, tune RCSI version store, fix queries with sort/hash warnings.",
      "**Diagnosis:**\n```sql\nSELECT * FROM sys.dm_os_wait_stats\nWHERE wait_type LIKE 'PAGE%LATCH%';\n```\nLatch contention on allocation bitmap pages when many sessions create temp objects concurrently.\n\n**Fix checklist:**\n1. **Multiple data files** — same initial size (e.g. 8 files × 4 GB on 16-core)\n2. **Uniform autogrowth** — prevent one file absorbing all growth\n3. **Reduce tempdb pressure** — fix queries spilling (sort warning, hash warning in plan)\n4. **RCSI audit** — version store in tempdb — long txn blocks cleanup\n5. **Temp table** → table variable only when stats not needed (optimizer estimates 1 row)\n\n**Architect:** tempdb on fast local SSD (Azure tempdb optimization on MI). Alert on tempdb data file >80% full.",
      "Tempdb is shared infrastructure — architects treat it like a critical service.",
      "Trace flag 1118/1117 still needed? — Modern SQL reduces need — verify version docs.",
      "Temp table indexing? — Index large temp tables used in joins.",
      "Single 1 GB tempdb file on 32-core",
      "Ignore sort warnings in top queries",
      "Long transactions with RCSI unmonitored"),
    q("Deadlock Graph Analysis", "Concurrency", "Common",
      "How do you read a SQL Server deadlock graph and fix the root cause?",
      "Extended Events `xml_deadlock_report` — victim marked with X. Cycle shows resources (key/page) and statements. Fix: consistent lock order, shorter txns, better indexes, retry 1205.",
      "**Reading graph:**\n- **Process nodes** — SPIDs, isolation level, statement text\n- **Resource nodes** — lock type (Key, Page, Object), mode (S, X, U)\n- **Cycle** — A holds R1 wants R2; B holds R2 wants R1\n\n**Common architect fixes:**\n1. **Lock order** — always update `Accounts` before `Transactions`\n2. **Shrink transaction** — no HTTP call inside `BEGIN TRAN`\n3. **Index** — reduce lock footprint (seek vs scan locks more rows)\n4. **Snapshot** — RCSI removes reader/writer deadlocks\n5. **App retry** — catch error 1205 with jittered retry (max 3)\n\n**Not a fix:** `SET DEADLOCK_PRIORITY LOW` on reports — moves problem, doesn't solve.",
      "Deadlock graphs connect application transaction design to DBA symptoms.",
      "Lock escalation in graph? — Row → table lock — partition or ROWLOCK hint sparingly.",
      "Deadlock vs blocking? — Blocking is wait chain; deadlock is cycle.",
      "Kill victim SPID as permanent fix",
      "Different table order in two services",
      "Deadlock graph never captured in prod"),
    q("Columnstore for Analytics", "Analytics", "Common",
      "When deploy clustered vs nonclustered columnstore for analytics on SQL Server?",
      "CCI on DW fact tables (bulk load, segment compression). NCCI on OLTP for selective analytics without duplicating warehouse. Batch mode execution requires columnstore segment.",
      "**CCI (Clustered Columnstore):**\n- Fact tables millions+ rows\n- Bulk insert / minimal singleton updates\n- 10x compression; segment elimination on date filters\n\n**NCCI on OLTP:**\n- Hybrid — operational reports without ETL delay\n- Trade-off: NC columnstore maintenance on hot writes\n\n**Architect pattern:**\n- OLTP rowstore primary\n- Nightly ETL to DW with CCI\n- Or readable AG secondary with CCI for reporting\n\n**Avoid:** CCI on small dimension tables — rowstore + B-tree faster for lookups.",
      "Columnstore placement separates OLTP path from analytics path.",
      "Tuple mover? — Closed rowgroups — rebuild if too many open deltas.",
      "Batch mode on rowstore? — Limited — columnstore is the analytics enabler.",
      "CCI on high-update OLTP table",
      "Analytics on primary without replica",
      "No segment health monitoring"),
    q("Connection Pooling Sizing", ".NET + SQL", "Very Common",
      "How do you size `Max Pool Size` and SQL Server `max connections` for a .NET API farm?",
      "Pool size ≈ (instances × pool max) < SQL max connections − headroom. Default 100 per connection string. Size from concurrent requests × avg query duration, not thread count.",
      "**Formula (starting point):**\n```\nRequired connections ≈ RPS × avg_query_seconds × safety_factor\n```\nExample: 500 RPS × 0.02s × 2 = 20 concurrent — pool 50–100 sufficient per instance.\n\n**Architect checklist:**\n- One pool per unique connection string (different DB = different pool)\n- `Min Pool Size` warm pool for burst APIs\n- `Connection Timeout=30` — fail fast don't hang\n- **Never** `Pooling=false`\n- EF Core: scoped DbContext — one connection per request typically\n\n**Azure SQL:** DTU/vCore tier caps connections — validate tier before scaling instances.\n\n**Monitor:** `sys.dm_exec_connections`, app `NumberOfActiveConnectionPools`.",
      "Connection math prevents the silent 'server max connections' outage.",
      "DbContext pool vs connection pool? — DbContext pool reuses context; still uses SqlConnection pool underneath.",
      "MARS impact? — Multiple active result sets — rarely needed; disable.",
      "10 instances × default 100 pool > SQL limit",
      "Singleton DbContext on web API",
      "No alert on connection exhaustion"),
    q("Parameter Sniffing", "Performance", "Very Common",
      "Explain parameter sniffing and your escalation ladder for fixing bad plans.",
      "Optimizer compiles plan using first parameter values — great for one shape, catastrophic for another. Fix: statistics, indexes, rewrite; last resort: `OPTIMIZE FOR`, `RECOMPILE`, Query Store forced plan.",
      "**Symptom:** Same SP fast for `@id=1` (one row), slow for `@id` rare (millions) — plan optimized for wrong cardinality.\n\n**Escalation ladder:**\n1. **Index** — eliminate scan regardless of parameter\n2. **Update statistics** with full scan on skewed column\n3. **`OPTION (RECOMPILE)`** — compile per execution — CPU cost\n4. **`OPTIMIZE FOR (@id UNKNOWN)`** — average plan\n5. **Query Store forced plan** — after A/B validation only\n6. **Local variable / dynamic SQL** — sometimes helps — test carefully\n\n**Architect:** Ban plan hints without documented incident ticket. Enable Query Store on all prod DBs — catch regressions on deploy.",
      "Parameter sniffing is why 'works in dev, fails in prod' on stored procedures.",
      "Local variable sniffing? — Assign param to local — sometimes different estimate.",
      "Query Store wait stats? — Identify plans with regression after release.",
      "OPTIMIZE FOR hint as first fix",
      "No Query Store on production",
      "Ignore skewed column statistics"),
    q("Statistics Auto-Update", "Performance", "Common",
      "How do SQL Server statistics affect plans and when override auto-update?",
      "Statistics histograms drive cardinality estimates. Auto-update async (2014+) reduces blocking. Override: manual UPDATE STATISTICS on large tables post bulk load; incremental stats on partitioned tables.",
      "**Auto-update triggers:**\n- SQL Server tracks modification counter vs rowcount threshold\n- Stale stats → scan instead of seek, bad join order, hash spills\n\n**Architect practices:**\n```sql\nUPDATE STATISTICS Orders WITH FULLSCAN;\n-- Or incremental on partitioned:\nUPDATE STATISTICS Orders PARTITION 3;\n```\n- Post ETL bulk load: manual stats update job\n- `AUTO_UPDATE_STATISTICS_ASYNC ON` for OLTP — compile with old stats, update in background\n- Monitor: `sys.dm_db_stats_properties` — modification_count vs rows\n\n**Filtered indexes** need separate statistics on filter column.",
      "Statistics hygiene is preventive architecture — cheaper than firefighting bad plans.",
      "Auto_create_statistics off? — Rare — leave on unless proven harm.",
      "Stats on computed columns? — Needed if queried.",
      "Rebuild index without updating stats",
      "Bulk load Friday no stats job",
      "Never check modification_count"),
    q("Index Maintenance Strategy", "Operations", "Common",
      "Design index maintenance for a 2TB OLTP database. Rebuild vs reorganize?",
      "Reorganize online for 5–30% fragmentation; rebuild for >30% or legacy editions. Partition-level maintenance; avoid full nightly rebuild all indexes.",
      "**Ola Hallengren pattern** (industry standard):\n- `IndexOptimize` procedure — thresholds per index\n- **Reorganize:** online, log-light, mild fragmentation\n- **Rebuild:** `ONLINE=ON` (Enterprise) — heavier but fixes fragmentation + updates stats\n\n**Architect rules:**\n- Maintain hot indexes weekly; cold indexes monthly\n- **Don't** rebuild every index nightly — IO storm\n- Align with backup window — log growth during rebuild\n- Columnstore: `REORGANIZE`/`REBUILD` for open rowgroups\n\n**Azure SQL:** Auto-tuning may recommend — review before auto-apply in prod.",
      "Index maintenance is capacity planning — not religion about nightly rebuild.",
      "Fill factor when? — Reduce page splits on random insert keys — not default 100 on GUID PK.",
      "Fragmentation on SSD? — Less seek penalty — maintain less aggressively than HDD era.",
      "REBUILD ALL every night",
      "No fragmentation monitoring",
      "Maintenance during peak traffic"),
    q("Query Store Regression", "Performance", "Very Common",
      "Query Store shows plan regression after deploy. What is your response?",
      "Identify regressed query in Query Store, compare plans, force last good plan short-term, fix root cause (stats, index, code), remove force after fix verified.",
      "**Workflow:**\n1. Query Store → Regressed Queries report post-deploy\n2. Compare plans: operator change (seek→scan), CE version change\n3. **Emergency:** `sp_query_store_force_plan` last known good\n4. **Root cause:** missing index, stats, parameter sniffing, CE upgrade\n5. **Verify** under production load — unforce when fixed\n\n**Architect:** CI gate — compare Query Store baseline in staging with production-like data volume. Block release if critical query regresses >2x duration.\n\n**Compatibility level** change can flip CE — test before upgrade.",
      "Query Store turns plan regression from mystery to managed incident.",
      "Query Store capture mode? — AUTO default — ALL for short debug window only.",
      "Plan forcing persistence? — Survives restart — document forced plans.",
      "Force plan without root-cause ticket",
      "Query Store OFF on production",
      "Upgrade compatibility without CE testing"),
    q("Lock Escalation Prevention", "Concurrency", "Common",
      "When does lock escalation happen and how do architects prevent it?",
      "SQL escalates row/page locks to table lock when ~5000 locks on single statement. Prevention: partition table, index for seek, `ALTER TABLE SET LOCK_ESCALATION AUTO|DISABLE|TABLE`, shorten transactions.",
      "**Symptom:** One UPDATE blocks entire table — `LCK_M_X` waits spike.\n\n**Mitigations:**\n1. **Partition** — escalation per partition not whole table\n2. **Better index** — fewer rows locked per seek\n3. **`LOCK_ESCALATION = AUTO`** (default) or `TABLE` for staging tables only\n4. **`DISABLE`** — rare; risk memory for lock objects\n5. **Batch updates** — `UPDATE TOP (1000)` loops\n\n**Architect:** Never `DISABLE` on core OLTP without load test — 100K row locks consume memory.\n\n**Rowlock hint** — doesn't prevent escalation alone.",
      "Lock escalation turns row-level design into table-level outage.",
      "Partition elimination + escalation? — Locks scoped to touched partitions.",
      "Table variable escalation? — Different rules — often fewer locks.",
      "Single UPDATE touching 1M rows one statement",
      "LOCK_ESCALATION DISABLE without memory test",
      "No index on WHERE column in bulk update"),
    q("RCSI vs Snapshot Isolation", "Transactions", "Common",
      "Compare Read Committed Snapshot Isolation vs Snapshot isolation level in SQL Server.",
      "RCSI: database option, statement-level consistent reads, default for new readers. Snapshot: transaction-level point-in-time, `SET TRANSACTION ISOLATION LEVEL SNAPSHOT`, `ALLOW_SNAPSHOT_ISOLATION ON`.",
      "| Feature | RCSI | Snapshot |\n|---------|------|----------|\n| Scope | DB-wide default RC | Per-transaction opt-in |\n| Consistency | Per statement | Entire transaction |\n| Version store | tempdb | tempdb |\n| Update conflicts | N/A (writers block writers) | Reader-writer conflict error 3960 |\n\n**RCSI:** Readers never block writers — default architect choice for OLTP read-heavy.\n\n**Snapshot:** Long report sees stable snapshot — no phantoms within txn — good for consistent export.\n\n**Both:** Version store in tempdb — monitor `sys.dm_tran_version_store`.",
      "Choosing RCSI vs Snapshot is consistency-duration trade-off.",
      "Enable both? — Common — RCSI default + snapshot for long reads.",
      "Version store cleanup blocked? — Find oldest active transaction.",
      "RCSI without tempdb sizing",
      "Snapshot txn hours long blocking cleanup",
      "Confuse RCSI with Read Uncommitted"),
    q("Filegroup Strategy", "Storage", "Occasional",
      "When use multiple filegroups in SQL Server architecture?",
      "Separate data filegroups for partitioning, tiered storage (hot SSD vs cold), piecemeal restore, and controlling file placement — not default single PRIMARY only at scale.",
      "**Patterns:**\n- **PRIMARY** — system objects\n- **FG_HOT** — current year data on premium storage\n- **FG_ARCHIVE** — old partitions on cheaper storage\n- **FILESTREAM** filegroup for blobs\n\n**Piecemeal restore:** Restore one filegroup while others online — enterprise DR pattern.\n\n**Architect:** Align filegroups with partition scheme — `ON FG_2024` per year partition.\n\n**Avoid:** Many empty filegroups without partition strategy — operational noise.",
      "Filegroups are the physical layer under logical partitioning.",
      "Log file separate disk? — Transaction log on low-latency disk — sequential write.",
      "Multiple data files per filegroup? — Proportional fill for IO parallelism.",
      "Everything on PRIMARY single file",
      "Filegroup without partition alignment",
      "Archive on same tier as hot data"),
    q("Log File Sizing", "Storage", "Common",
      "How do you size and manage the SQL Server transaction log?",
      "Pre-size log to avoid autogrowth during peak. Size for largest bulk operation + replication/AG lag headroom. Backup log frequently in FULL recovery — log reuse depends on backup.",
      "**Sizing approach:**\n1. Measure log generation during peak hour (MB/min)\n2. Add headroom for AG sync lag or long txn\n3. Set fixed size + growth increment (e.g. 8 GB chunks not 10%)\n\n**Recovery models:**\n- **SIMPLE:** log truncates at checkpoint — dev/test\n- **FULL:** log backup required — production with point-in-time restore\n\n**Architect alerts:**\n- Log >80% full\n- `LOG_BACKUP` wait — AG replica not applying\n- VLF count high from tiny autogrowths — rebuild log after right-size\n\n**Never** shrink log routinely — regrows cause VLFs and perf hit.",
      "Transaction log is the durability backbone — architects size it proactively.",
      "Log reuse wait? — `CHECKPOINT` or log backup not occurring.",
      "Bulk-logged recovery? — Bulk load window — understand PITR gap.",
      "Log autogrowth 10% on 100GB log",
      "FULL recovery without log backup job",
      "Shrink log file after every backup"),
    q("Backup Strategy FULL DIFF LOG", "HA/DR", "Very Common",
      "Design backup strategy for SQL Server with RPO 15 minutes and RTO 1 hour.",
      "FULL weekly, DIFF daily, LOG every 15 min. Test restore monthly. Copy backups to geo-redundant storage. AG sync replica is HA not backup substitute.",
      "**Schedule example:**\n| Backup | Frequency | Retention |\n|--------|-----------|----------|\n| FULL | Weekly Sunday | 4 weeks |\n| DIFF | Daily | 7 days |\n| LOG | Every 15 min | 7 days |\n\n**RPO 15 min:** log backup interval ≤15 min.\n**RTO 1 hr:** restore FULL + latest DIFF + log chain to target time — practice runbook.\n\n**Architect:**\n- `CHECKSUM` on backups — verify restore\n- Immutable/offsite copy (Azure Backup, S3 Object Lock)\n- **AG is not backup** — logical corruption replicates\n- Encrypt backups (TDE encrypts at rest; backup encryption optional layer)",
      "Backup strategy is tested restore — not backup job existence.",
      "Piecemeal restore? — Filegroup restore for large DB partial recovery.",
      "Azure SQL automated backup? — PITR built-in — know retention by tier.",
      "AG replica instead of backups",
      "Never test restore",
      "LOG backup every 6 hours with RPO 15 min claim"),
    q("Security TDE and Always Encrypted", "Security", "Common",
      "When use TDE vs Always Encrypted for SQL Server compliance?",
      "TDE: encrypt data at rest transparently — DBA sees plaintext. Always Encrypted: client-side encryption — DBA/cloud admin cannot read column values.",
      "**TDE:**\n- Protects disk/backup theft\n- Minimal app change\n- Azure SQL TDE on by default\n- Key in Key Vault (BYOK)\n\n**Always Encrypted:**\n- SSN, PCI columns — even sysadmin can't SELECT plaintext\n- Deterministic vs randomized encryption — deterministic allows equality, weaker\n- App uses Always Encrypted provider in SqlClient\n\n**Architect matrix:**\n| Threat | TDE | AE |\n|--------|-----|----|\n| Stolen backup file | ✓ | ✓ |\n| Malicious DBA | ✗ | ✓ |\n| App compromise | ✗ | ✗ (keys in app) |\n\nCombine TDE (at-rest) + AE (sensitive columns) for defense in depth.",
      "Encryption choice maps to threat model — architects document which threat each layer addresses.",
      "Column encryption key rotation? — AE supports rotation workflow.",
      "Ledger tables? — Tamper-evident audit — complement encryption.",
      "TDE alone for PCI column from DBA",
      "AE on all columns — query limitations",
      "CMK in same account as database"),
    q("SQL Server on VM vs Azure SQL", "Cloud", "Very Common",
      "Decision framework: SQL Server on Azure VM vs Azure SQL Database vs Managed Instance?",
      "Azure SQL DB: new cloud-native, per-DB scale, serverless dev. MI: near 100% compatibility, instance features. VM: OS control, legacy extensions, bring-your-own-license.",
      "**Decision tree:**\n1. Need linked server, SQL Agent jobs, cross-DB queries? → **MI** or **VM**\n2. New microservice single DB, elastic scale? → **Azure SQL DB** (Hyperscale for large OLTP)\n3. Custom OS, third-party DLL, legacy? → **VM**\n4. Minimize ops? → **PaaS** (DB or MI)\n\n| Factor | SQL DB | MI | VM |\n|--------|--------|----|----|\n| Ops burden | Low | Medium | High |\n| Feature parity | Subset | ~100% | 100% |\n| Cost predictability | Per DB | Per vCore | VM + license |\n\n**Architect:** ADR with compatibility checklist. Start Azure SQL DB unless MI feature gate. VM last resort for lift-and-shift debt.",
      "Cloud SQL choice locks ops model for years — framework prevents default-to-VM.",
      "Hyperscale limits? — 100TB, fast scale — verify feature gaps vs MI.",
      "Azure Arc SQL? — Hybrid management — on-prem + cloud policy.",
      "VM for greenfield simple API",
      "MI when single Azure SQL DB suffices",
      "No private endpoint on production PaaS"),
]

WEEK_8_Q011_Q030 = [
    q("MVCC Vacuum Tuning", "Concurrency", "Very Common",
      "How do you tune autovacuum for a high-update PostgreSQL table?",
      "Lower `autovacuum_vacuum_scale_factor` per table, raise `autovacuum_vacuum_cost_limit`, monitor `n_dead_tup`, set `idle_in_transaction_session_timeout`.",
      "**Per-table settings:**\n```sql\nALTER TABLE orders SET (\n  autovacuum_vacuum_scale_factor = 0.02,\n  autovacuum_analyze_scale_factor = 0.01,\n  autovacuum_vacuum_cost_delay = 2\n);\n```\n\n**Why:** Default scale 0.2 means vacuum after 20% dead tuples — on 100M row table that's 20M dead rows before cleanup.\n\n**Architect monitoring:**\n```sql\nSELECT relname, n_dead_tup, last_autovacuum\nFROM pg_stat_user_tables ORDER BY n_dead_tup DESC;\n```\n\n**Blockers:** Long transactions hold xmin — vacuum can't remove dead tuples — causes bloat.\n\n**PgBouncer:** transaction pooling reduces idle-in-txn sessions holding snapshots.",
      "Vacuum tuning is production architecture for Postgres — not optional DBA trivia.",
      "autovacuum_max_workers? — Increase on large instances with many tables.",
      "Manual VACUUM ANALYZE when? — After bulk load before critical query window.",
      "Default autovacuum on 500M row hot table",
      "ETL job idle in transaction 8 hours",
      "No alert on n_dead_tup threshold"),
    q("JSONB GIN Indexing", "Indexing", "Very Common",
      "Index JSONB columns for containment queries. Which operators and index type?",
      "GIN index with `jsonb_ops` (default) or `jsonb_path_ops` (smaller, `@>` only). Query with `@>`, `?`, `?&`, `?|` operators — B-tree cannot help.",
      "**Create:**\n```sql\nCREATE INDEX idx_product_attrs ON products\nUSING GIN (attributes jsonb_path_ops);\n\n-- Query uses index:\nSELECT * FROM products\nWHERE attributes @> '{\"category\": \"electronics\"}';\n```\n\n**jsonb_path_ops vs jsonb_ops:**\n- `path_ops` — smaller index, only `@>` containment\n- `jsonb_ops` — supports `?` key existence too — larger\n\n**Architect:** Index only queried paths — not whole blob if subset hot.\n\n**Expression index alternative:** `(attributes->>'sku')` B-tree for equality on single field.",
      "JSONB indexing strategy determines whether hybrid schema scales.",
      "GIN pending list? — Fast insert batch — merge with vacuum.",
      "jsonb vs JSON type? — Always JSONB for indexing and storage.",
      "No index on hot @> queries",
      "jsonb_ops when only @> used — wasted size",
      "Huge JSONB document in every row indexed wholly"),
    q("GiST vs GIN Choice", "Indexing", "Common",
      "When choose GiST vs GIN index in PostgreSQL?",
      "GIN: exact containment, arrays, full-text, JSONB — larger, slower build, fast lookup. GiST: geometric, range types, full-text (slower build, smaller), nearest-neighbor queries.",
      "| Use Case | Index |\n|----------|-------|\n| JSONB `@>` | GIN |\n| `tsvector` full-text | GIN (default) or GiST |\n| PostGIS geometry | GiST |\n| IP range, int4range overlap | GiST |\n| Array `@>` | GIN |\n\n**Rule of thumb:** GIN for 'contains' on static data; GiST for overlap/nearest-neighbor spatial.\n\n**Architect:** Run `EXPLAIN ANALYZE` both ways on production-like volume — GIN build can lock writes during CREATE INDEX — use `CONCURRENTLY`.",
      "Wrong index type means seq scan on million-row tables.",
      "BRIN vs GiST for geo? — BRIN not for point queries — GiST/SP-GiST.",
      "SP-GiST? — Partitioned search trees — phone routing, some geo.",
      "GiST for JSONB containment",
      "GIN for nearest-neighbor geo",
      "CREATE INDEX without CONCURRENTLY on prod"),
    q("Streaming Replication Slots", "HA/DR", "Common",
      "What are replication slots and what happens if a replica stops consuming?",
      "Slots track WAL position per consumer — prevent WAL deletion until consumed. Stopped replica with slot → WAL accumulates → disk full on primary.",
      "**Physical replication slot:**\n```sql\nSELECT slot_name, active, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn) AS lag_bytes\nFROM pg_replication_slots;\n```\n\n**Architect rules:**\n- Monitor `lag_bytes` and `active=false`\n- Drop orphaned slots after replica decommission\n- `max_slot_wal_keep_size` (PG13+) — limit WAL retention\n- Logical slots for logical replication — same disk risk\n\n**Never** leave inactive slot on production without alert — classic Postgres outage cause.",
      "Replication slots are durability contracts — architects monitor them like disk space.",
      "Temporary vs permanent slot? — Temp dies with session — prefer named permanent with monitoring.",
      "pg_receivewal slot? — Third-party backup tools use slots.",
      "Drop replica VM but not slot",
      "No alert on inactive slot",
      "Unlimited WAL keep with dead replica"),
    q("PgBouncer Transaction Mode", "Operations", "Very Common",
      "Explain PgBouncer transaction pooling mode and ORM compatibility.",
      "Transaction mode: server connection returned to pool after each transaction. Thousands of clients, tens of server connections. Breaks session-level features (prepared statements, temp tables, LISTEN).",
      "**Modes:**\n- **Session** — 1:1 until disconnect — compatible, less multiplexing\n- **Transaction** — pool per txn — best for stateless web APIs\n- **Statement** — pool per statement — rare, breaks multi-statement txn\n\n**Npgsql + EF Core:**\n- Disable prepared statements or use session mode if issues\n- `Maximum Pool Size` on client still applies above PgBouncer\n\n**Architect sizing:**\n```\npgbouncer max_client_conn = 2000\npgbouncer default_pool_size = 50\npostgres max_connections = 100 (reserved superuser)\n```",
      "Transaction pooling is mandatory architecture for Postgres at hundreds of app instances.",
      "Prepared statement error? — Switch session mode or `PrepareThreshold=0`.",
      "SET search_path in transaction mode? — Must SET each transaction — or use connect query.",
      "Session mode with 5000 app connections",
      "Temp tables in transaction pooling",
      "max_connections 500 on Postgres directly"),
    q("BRIN for Time-Series", "Indexing", "Common",
      "When use BRIN indexes for time-series data in PostgreSQL?",
      "BRIN on naturally ordered column (timestamp, serial ID) — tiny index size, block-range min/max summary. Ideal append-only logs, metrics, events billions of rows.",
      "**Create:**\n```sql\nCREATE INDEX idx_events_created ON events\nUSING BRIN (created_at) WITH (pages_per_range = 128);\n```\n\n**Query:**\n```sql\nWHERE created_at BETWEEN '2024-01-01' AND '2024-01-31'\n```\n\n**Works when:** Physical row order correlates with time (insert order). **Fails when:** Random insert order — reorder or use B-tree.\n\n**Architect:** BRIN + declarative partitioning by month — partition pruning + BRIN per partition.\n\n**Size:** BRIN index MB vs B-tree GB on billion-row table.",
      "BRIN is the architect's secret for cheap time-range scans at scale.",
      "pages_per_range tuning? — Smaller = more precise, larger index.",
      "CLUSTER on time column? — Improves BRIN correlation after bulk load.",
      "BRIN on random UUID insert order",
      "B-tree on billion-row log table",
      "No partition + BRIN on single huge table only"),
    q("Expand-Contract Migrations", "Migrations", "Very Common",
      "Walk through expand-contract for renaming a column with zero downtime.",
      "Add new column (expand) → dual-write both → backfill → switch reads → stop old writes → drop old (contract). Never rename in single deploy.",
      "**Phases:**\n1. **Expand:** `ADD COLUMN new_email TEXT` nullable\n2. **Deploy app v2:** write both `email` and `new_email`\n3. **Backfill:** `UPDATE ... SET new_email = email WHERE new_email IS NULL` batched\n4. **Deploy app v3:** read `new_email`\n5. **Contract:** drop `email` after all instances on v3\n\n**Postgres:** `ADD COLUMN` with volatile default locks table — add nullable, backfill, then `SET DEFAULT`.\n\n**Architect:** Migration pipeline blocks destructive DDL without expand-contract review.",
      "Expand-contract is how architects enable continuous deployment on Postgres.",
      "CONCURRENTLY for indexes? — `CREATE INDEX CONCURRENTLY` during expand phase.",
      "Flyway vs Liquibase? — Tool agnostic — process matters.",
      "RENAME COLUMN in Friday deploy",
      "NOT NULL without backfill complete",
      "Single-phase breaking migration"),
    q("Partial Indexes", "Indexing", "Common",
      "Design partial indexes for PostgreSQL. When do they win?",
      "Index subset with WHERE clause — smaller, faster, less write overhead. Ideal sparse predicates: active rows, unpaid orders, non-null subset.",
      "**Example:**\n```sql\nCREATE INDEX idx_orders_open ON orders (customer_id)\nWHERE status IN ('pending', 'processing');\n```\n\n**Wins when:**\n- Query always includes same filter\n- Small fraction of rows match (5–20%)\n- Hot path queries only touch active subset\n\n**Planner requirement:** Query WHERE must imply index predicate — `status = 'pending'` uses index; `status = 'shipped'` does not.\n\n**Architect:** Document partial index predicates in data dictionary — devs must know query shape.",
      "Partial indexes are free performance when workload is skewed.",
      "Unique partial index? — `WHERE deleted_at IS NULL` for soft-delete uniqueness.",
      "Multiple partial indexes? — Different status values — evaluate write cost.",
      "Partial index predicate not in queries",
      "Full index when 95% rows filtered out",
      "Forget UNIQUE constraint needs partial for soft delete"),
    q("Expression Indexes", "Indexing", "Common",
      "When create expression indexes in PostgreSQL?",
      "Index on expression or function result — when queries use `LOWER(email)`, date truncation, or computed JSON path — not column directly.",
      "**Examples:**\n```sql\nCREATE INDEX idx_users_email_lower ON users (LOWER(email));\n\nCREATE INDEX idx_orders_month ON orders (date_trunc('month', created_at));\n```\n\n**Query must match expression exactly:**\n```sql\nWHERE LOWER(email) = LOWER(@input)  -- uses index\nWHERE email = @input                 -- does not\n```\n\n**Architect:** Prefer generated stored column (PG12+) + B-tree if expression reused — clearer than opaque function index.\n\n**Immutable functions only** in index — `LOWER` yes; `now()` no.",
      "Expression indexes bridge app normalization and query patterns.",
      "Functional dependency? — PG14+ infer uniqueness on dependent cols sometimes.",
      "jsonb path expression index? — `(data->>'type')` B-tree for equality.",
      "Index column but query uses LOWER()",
      "Mutable function in index expression",
      "Expression mismatch — planner can't use index"),
    q("Declarative Table Partitioning", "Scale", "Common",
      "Design declarative partitioning in PostgreSQL for a multi-tenant events table.",
      "RANGE or LIST partition on `created_at` or `tenant_id`. PG10+ declarative — attach/detach partitions for archive. Unique constraints must include partition key.",
      "**Monthly range:**\n```sql\nCREATE TABLE events (\n  id BIGSERIAL, tenant_id INT, created_at TIMESTAMPTZ, payload JSONB,\n  PRIMARY KEY (id, created_at)\n) PARTITION BY RANGE (created_at);\n\nCREATE TABLE events_2024_01 PARTITION OF events\n  FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');\n```\n\n**Architect:**\n- Partition key in PK and unique constraints\n- `DETACH PARTITION` for archive — instant\n- Default partition catches overflow — monitor\n- Prune with `WHERE created_at >= ...` in every query\n\n**pg_partman** extension automates partition creation.",
      "Declarative partitioning is Postgres answer to SQL Server SWITCH — different mechanics, same lifecycle goal.",
      "HASH partition tenants? — Even distribution — cross-partition queries expensive.",
      "Sub-partitioning? — RANGE then HASH — advanced multi-tenant.",
      "PK without partition key",
      "No default partition — INSERT fails new month",
      "Queries missing partition key filter"),
    q("Connection Limits Tuning", "Operations", "Common",
      "How size `max_connections` vs PgBouncer pool for PostgreSQL?",
      "Postgres `max_connections` low (100–200) — process-per-connection expensive. PgBouncer multiplexes thousands of clients. Reserve `superuser_reserved_connections`.",
      "**Sizing:**\n```\npostgres max_connections = pgbouncer default_pool_size + admin_headroom\n```\n\n**Memory:** Each connection ~5–10 MB work_mem dependent — 500 connections ≠ free.\n\n**Architect:**\n- PgBouncer between app and Postgres (or Azure Flexible Server built-in pooler)\n- App connection string points to PgBouncer port 6432\n- Monitor `pg_stat_activity` count vs `max_connections`\n- `idle_in_transaction_session_timeout = 60s`\n\n**Serverless burst:** Pooler essential — Lambda/container scale connections faster than Postgres accepts.",
      "Connection limits are hard caps — architects design pooler-first.",
      "RDS/Azure connection limits? — Tier-based — upgrade or pool.",
      "Connection leak detection? — `pg_stat_activity` state idle age.",
      "max_connections 1000 no pooler",
      "Each microservice instance 100 direct connections",
      "No idle_in_transaction timeout"),
    q("EXPLAIN ANALYZE", "Performance", "Very Common",
      "How do architects use EXPLAIN ANALYZE safely in production troubleshooting?",
      "Run on representative query with ANALYZE in staging first. Production: use `EXPLAIN (ANALYZE, BUFFERS)` on isolated replica or limited window — executes query, adds overhead.",
      "**Read plan:**\n```sql\nEXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)\nSELECT ...;\n```\n\n**Key nodes:**\n- **Seq Scan** on large table — index opportunity\n- **Index Only Scan** — covering index win\n- **Nested Loop** with high loops — bad estimate or missing index\n- **Hash Join** — build side should be smaller\n- **Buffers: shared hit/read** — cache vs disk\n\n**Architect workflow:**\n1. Capture from `pg_stat_statements` top queries\n2. EXPLAIN on read replica\n3. Compare estimates vs actual rows\n4. Fix index, stats (`ANALYZE`), or rewrite\n\n**Never** EXPLAIN ANALYZE destructive UPDATE on prod primary without transaction rollback test.",
      "EXPLAIN ANALYZE is the architect's microscope — use on replica when possible.",
      "auto_explain extension? — Log slow plans automatically.",
      "Generic vs custom plan? — Prepared statement plans — use `EXPLAIN GENERIC_PLAN`.",
      "EXPLAIN without ANALYZE and guess",
      "ANALYZE heavy query on primary peak",
      "Ignore actual vs estimated row mismatch"),
    q("Autovacuum Freeze", "Operations", "Common",
      "What is transaction ID wraparound and how does autovacuum freeze prevent it?",
      "Postgres 32-bit transaction IDs wrap ~2 billion. Dead tuples must be frozen to mark all-visible — autovacuum freeze reclaims XID space. Failure → database shutdown to prevent corruption.",
      "**Monitor:**\n```sql\nSELECT datname, age(datfrozenxid) FROM pg_database;\n-- Alert if age > 200M (default autovacuum_freeze_max_age 200M)\n```\n\n**Causes of freeze lag:**\n- Long transactions block vacuum\n- `autovacuum_freeze_max_age` too high on busy DB\n- Tables never vacuumed — `n_mod_since_analyze` stale\n\n**Architect:**\n- Alert `age(datfrozenxid) > 150M`\n- `idle_in_transaction_session_timeout`\n- Schedule manual `VACUUM FREEZE` on catalog-heavy tables if needed\n\n**Emergency:** `VACUUM FREEZE VERBOSE` — not `VACUUM FULL` unless bloat crisis.",
      "XID wraparound is existential Postgres risk — architects monitor age, not just disk.",
      "multixact wraparound? — Similar risk for row locks — `pg_multixact` age.",
      "vacuum_defer_cleanup_age? — Usually leave default — deferring increases wrap risk.",
      "Ignore datfrozenxid age alerts",
      "Weekend ETL idle in transaction",
      "Disable autovacuum on any production table"),
    q("Logical Replication", "HA/DR", "Common",
      "When use logical vs physical replication in PostgreSQL?",
      "Physical: byte-for-byte WAL, full cluster, low lag, replica read-only. Logical: row-level, selective tables, version upgrades, CDC to external systems — more overhead.",
      "**Logical replication use cases:**\n- PG major version upgrade (17 → 18) with minimal downtime\n- Replicate subset of tables to analytics DB\n- CDC to Kafka/Debezium\n- Multi-master conflict scenarios (advanced — avoid without expertise)\n\n**Setup:**\n```sql\nCREATE PUBLICATION orders_pub FOR TABLE orders;\nCREATE SUBSCRIPTION orders_sub CONNECTION '...' PUBLICATION orders_pub;\n```\n\n**Architect:** Logical replication slot holds WAL — monitor like physical slot. Initial sync locks source table briefly.\n\n**Not for:** Sub-millisecond HA failover — use physical + Patroni/cloud HA.",
      "Logical replication is migration and CDC architecture — not primary HA.",
      "Replica identity FULL? — Needed for UPDATE/DELETE without PK on all columns.",
      "Conflict resolution? — Logical multi-master needs strategy — last-write-wins dangerous.",
      "Logical replication for HA failover only",
      "No monitoring on replication lag",
      "Upgrade without logical replication test"),
    q("Citus Extension Sharding", "Scale", "Occasional",
      "When recommend Citus for PostgreSQL sharding?",
      "Citus when single Postgres node exceeds vertical scale (CPU, storage, write throughput) and workload shards by tenant_id or distribution key — multi-tenant SaaS, real-time analytics.",
      "**Distribution:**\n```sql\nSELECT create_distributed_table('events', 'tenant_id');\n```\n\n**Good fit:**\n- Queries filter by distribution column (`tenant_id`)\n- Tenant count >> single node capacity\n- Azure Cosmos DB for PostgreSQL (Citus managed)\n\n**Bad fit:**\n- Cross-shard JOINs dominate\n- No natural distribution key\n- Small DB that fits one Flexible Server\n\n**Architect:** Shard key is permanent architecture decision — resharding is painful. Co-locate related tables same distribution key.",
      "Citus is horizontal scale when partition-on-one-node is exhausted.",
      "Reference tables? — Small lookup tables replicated to all nodes.",
      "Coordinator bottleneck? — Query routing — scale coordinator tier.",
      "Citus without tenant isolation in key",
      "Cross-shard JOIN heavy reporting",
      "Citus for 50GB database"),
    q("PostGIS When", "Extensions", "Occasional",
      "When add PostGIS to PostgreSQL vs store lat/long in app or use external geo service?",
      "PostGIS when queries need distance, containment, spatial joins, geofencing in SQL — not just display markers. GiST index on geometry.",
      "**Use PostGIS:**\n- Find stores within 5 km of user\n- Polygon containment (delivery zones)\n- Route-adjacent spatial joins\n\n**Skip PostGIS:**\n- Store coordinates for map pin display only\n- Simple bounding box in app code at low volume\n- Azure Maps / Google Maps API handles geo logic externally\n\n**Example:**\n```sql\nSELECT * FROM stores\nWHERE ST_DWithin(location::geography, ST_MakePoint(@lon,@lat)::geography, 5000);\n```\n\n**Architect:** PostGIS adds operational complexity — extension upgrades tied to PG version. Bounded context owns spatial data.",
      "PostGIS is for spatial queries in SQL — not coordinates in a JSON blob.",
      "geometry vs geography? — Geography for lat/lon meters; geometry for projected CRS.",
      "Spatial index? — `CREATE INDEX ON stores USING GIST (location);`",
      "PostGIS for lat/long display only",
      "No GiST index on geometry column",
      "Haversine in app on 10M rows"),
    q("TimescaleDB", "Extensions", "Common",
      "When choose TimescaleDB over native Postgres partitioning for metrics?",
      "TimescaleDB for high-ingest time-series (metrics, IoT, logs) needing automatic chunking, compression, retention policies, continuous aggregates — reduces ops vs hand-rolled partitions.",
      "**Hypertable:**\n```sql\nSELECT create_hypertable('metrics', 'time');\n```\n\n**Features architects use:**\n- **Compression** — older chunks compressed 90%+\n- **Retention policies** — drop chunks older than N days\n- **Continuous aggregates** — materialized rollups refresh incrementally\n\n**Native partitioning enough when:**\n- Low ingest, monthly manual partitions OK\n- Team knows pg_partman\n\n**TimescaleDB when:**\n- Millions inserts/min\n- Standard Prometheus/Grafana stack on SQL\n\n**Azure:** Timescale on Flexible Server or self-managed.",
      "TimescaleDB is architect shortcut for time-series ops Postgres can do manually.",
      "Chunk interval tuning? — 1 day vs 1 week — match query window.",
      "Hypercore columnstore? — Recent Timescale compression evolution — evaluate version.",
      "Hand-rolled partitions at IoT ingest scale",
      "No retention policy on metrics table",
      "Timescale for relational OLTP core"),
    q("Row-Level Security Policies", "Security", "Common",
      "Implement multi-tenant isolation with PostgreSQL RLS.",
      "Enable RLS on table, create policy filtering `tenant_id = current_setting('app.tenant_id')::int`. App sets tenant per connection/transaction.",
      "**Setup:**\n```sql\nALTER TABLE orders ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY tenant_isolation ON orders\n  USING (tenant_id = current_tenant_id());\n```\n\n**App (Npgsql):**\n```csharp\nawait cmd.ExecuteNonQueryAsync(\"SET app.tenant_id = '42'\");\n```\n\n**Architect:**\n- RLS is defense in depth — not replacement for app filtering\n- Superuser bypasses RLS — no superuser in app role\n- Test policies with integration tests per tenant\n- **Bypass risk:** SQL injection setting wrong tenant — parameterize everything\n\n**Performance:** Index on `tenant_id` — policy adds filter every query.",
      "RLS encodes tenant isolation in database — architects layer with app auth.",
      "FORCE ROW LEVEL SECURITY? — Applies to table owner too — stricter.",
      "BYPASSRLS role attribute? — Migration admin only — not app.",
      "RLS without index on tenant_id",
      "App uses superuser connection",
      "Forget SET tenant on pooled connection"),
    q("pg_stat_statements", "Observability", "Very Common",
      "How use pg_stat_statements for performance architecture?",
      "Extension tracks normalized query text, calls, total_time, mean_time, rows — identify top CPU/IO queries without full query logging.",
      "**Enable:**\n```sql\nCREATE EXTENSION pg_stat_statements;\nSELECT query, calls, mean_exec_time, total_exec_time\nFROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 20;\n```\n\n**Architect workflow:**\n1. Weekly review top 10 by `total_exec_time` and `mean_exec_time`\n2. Correlate with `EXPLAIN ANALYZE` on replica\n3. Reset stats after major release for clean baseline: `pg_stat_statements_reset()`\n\n**Azure Flexible Server:** extension available — enable in server parameters.\n\n**Pair with:** `pg_stat_user_tables` (seq scans), auto_explain for slow plans.",
      "pg_stat_statements is Postgres Query Store equivalent — architects mandate it on prod.",
      "track_io_timing? — `shared_preload_libraries` — I/O per query.",
      "Query normalization? — Literals replaced — group similar queries.",
      "No extension on production Postgres",
      "Tune queries never ranked by total_time",
      "Never reset stats after major migration"),
    q("Postgres on Azure Flexible HA", "Cloud", "Very Common",
      "Design HA and DR for Azure Database for PostgreSQL Flexible Server.",
      "Zone-redundant HA: standby in another AZ, automatic failover ~60–120s. Read replicas up to 5 for read scale. Geo-redundant backup for DR — not synchronous geo replica by default.",
      "**HA modes:**\n- **Same zone** — single AZ, lower cost, AZ outage risk\n- **Zone redundant** — production default for tier-1\n\n**Architect checklist:**\n- Private endpoint + VNet integration\n- Connection string retry on failover (Npgsql `KeepAlive`, Polly)\n- Read replica for reporting — monitor replication lag\n- PITR backup retention per compliance (7–35 days)\n- **Built-in PgBouncer** — enable for connection pooling\n\n**RPO/RTO:**\n- HA failover RPO=0 within region, RTO ~2 min\n- Geo-DR: restore from geo backup — RPO = backup interval, RTO hours — document acceptance\n\n**vs SQL Server AG:** Postgres Flexible uses different failover semantics — test app behavior.",
      "Azure Flexible HA is managed Patroni — architects still own app retry and replica lag routing.",
      "Accelerated logs? — IO optimization for write-heavy — enable for OLTP.",
      "Burstable vs General Purpose? — Burstable dev only — prod GP or Memory Optimized.",
      "Single zone for production payments",
      "No retry logic on Npgsql connection",
      "Assume read replica zero lag"),
]
