"""Hand-crafted premium Q011–Q030 for Weeks 29–32 — DevOps, CI/CD, IaC, Observability."""

from premium_qa_data import q

WEEK_29_Q011_Q030 = [
    q("Value Stream Mapping for DevOps", "Value Stream", "Very Common",
      "How do you run a value stream mapping workshop for a .NET team with 3-week lead time?",
      "Map commit-to-production flow on a wall: wait times vs process times. Attack the longest wait first — often manual QA queue or CAB scheduling, not compile time.",
      "**Workshop steps:**\n1. Identify start (commit merged) and end (running in prod)\n2. List every step: PR review, CI, security scan, QA, CAB, deploy, smoke test\n3. Measure **wait time** (work sitting idle) vs **process time** (active work)\n4. Calculate **process efficiency** = process / (process + wait)\n\n**Example finding:** CI 45 min (process), QA queue 5 days (wait), CAB weekly (wait). Fix: automated integration tests eliminate QA queue; standard changes eliminate CAB wait.\n\n**Architect role:** Facilitate cross-functional map — dev, QA, ops, security. Present business case: 5-day QA wait blocks revenue features.",
      "Value stream mapping connects DORA lead time to organizational bottlenecks — not just tooling.",
      "VSM vs process mapping? — VSM adds wait/processing time and % complete-and-accurate.",
      "Remote teams? — Miro board with sticky notes — same methodology.",
      "Optimizing CI while 5-day QA wait remains",
      "No wait time measurement — only process time",
      "VSM without follow-up action owners"),
    q("Team Topologies Stream-Aligned Teams", "Team Topologies", "Very Common",
      "What is a stream-aligned team in Team Topologies and how does it change architecture?",
      "Stream-aligned team owns a business capability end-to-end — order checkout from API to deploy to on-call. Platform and enabling teams reduce their cognitive load.",
      "**Four team types:**\n- **Stream-aligned** — delivers customer value (Order Team)\n- **Platform** — internal product (CI/CD golden path, IDP)\n- **Enabling** — temporary coaching (observability rollout)\n- **Complicated-subsystem** — deep specialty (fraud ML)\n\n**Architecture impact:** Bounded context maps to stream-aligned team. Conway's Law: design services team can own independently.\n\n**Anti-pattern:** Stream team depends on 4 other teams to deploy — not truly stream-aligned.",
      "Team Topologies is org design for DevOps — architects align service boundaries to team ownership.",
      "Platform team as gatekeeper? — Platform provides paved road; stream teams choose adoption.",
      "Two-pizza team vs stream-aligned? — Overlap — stream-aligned is capability scope, not just size.",
      "Component teams owning layers (UI team, API team)",
      "Platform team approving every production deploy",
      "Stream-aligned team spanning 12 microservices they cannot deploy alone"),
    q("Cognitive Load in Platform Design", "Team Topologies", "Common",
      "How do you reduce cognitive load on product teams through platform engineering?",
      "Hide infrastructure complexity behind golden-path templates: .NET 8 API scaffold, OIDC pipeline, Bicep modules, App Insights wired. Product teams focus on domain logic only.",
      "**Three cognitive load types (Team Topologies):**\n1. **Intrinsic** — domain complexity (unavoidable)\n2. **Extraneous** — tooling friction (platform removes)\n3. **Germane** — learning new patterns (enabling team helps)\n\n**Tactics:**\n- Abstract Kubernetes behind Container Apps or App Service\n- Reusable GitHub Actions workflow — teams pass `serviceName` only\n- Standard observability — no per-team dashboard DIY\n\n**Measure:** Developer survey + time-to-first-deploy. High extraneous load → low adoption of good practices.",
      "Cognitive load explains why teams bypass security — make secure path the easy path.",
      "When expose complexity? — Power users may need escape hatches — document off-road burden.",
      "Thinnest viable platform? — Start minimal golden path; expand on demand.",
      "Mandating raw Terraform for all product developers",
      "Platform with 47 configuration options per service",
      "No feedback loop on developer friction"),
    q("Westrum Organizational Culture", "DevOps Culture", "Common",
      "What is Westrum's organizational culture typology and why does DORA research cite it?",
      "Westrum: Pathological (blame), Bureaucratic (rules), Generative (learning). Elite DORA performers correlate with generative culture — information flows freely, failures are learning opportunities.",
      "**Generative signals:**\n- Cross-functional collaboration is rewarded\n- Messengers not shot — bad news travels fast\n- Failures lead to inquiry not punishment\n- New ideas welcomed\n\n**Architect influence:** Design blameless postmortems, visible incident learning, psychological safety in architecture reviews.\n\n**Assessment:** Westrum survey (7 questions) baseline before DevOps transformation — retest quarterly.",
      "Culture predicts delivery performance — tools alone on pathological culture fail.",
      "Westrum vs CALMS? — Westrum measures culture type; CALMS is DevOps capability framework.",
      "Can architects change culture? — Influence via systems: postmortems, metrics transparency, golden paths.",
      "Declaring DevOps culture without measuring Westrum baseline",
      "Blameful incident reviews while claiming generative culture",
      "Tool rollout as culture change strategy"),
    q("SRE Error Budgets in Practice", "SRE", "Very Common",
      "How do error budgets change prioritization when a .NET API exhausts its monthly SLO budget?",
      "Error budget = 1 − SLO. At 99.9% SLO, 43 min/month downtime allowed. Budget exhausted → freeze feature work, reliability sprint, exec escalation.",
      "**Policy tiers:**\n- **>50% budget remaining** — normal feature velocity\n- **20–50%** — caution; no risky deploys Friday\n- **<20%** — reliability work prioritized\n- **Exhausted** — feature freeze until budget resets\n\n**Example:** Order API burned budget on 3 incidents from connection pool exhaustion. Actions: pool metrics alert, load test in CI, circuit breaker on payment dependency.\n\n**Architect:** Error budget is negotiation tool between product and SRE — data-driven not opinion.",
      "Error budgets make reliability trade-offs explicit — interviewers want policy not just definition.",
      "100% SLO? — Impossible; creates paralysis and hides real trade-offs.",
      "Budget per service or team? — Per user-facing service with distinct SLO.",
      "Error budget with no enforcement mechanism",
      "Exhausted budget but features still ship unchecked",
      "SLO defined but never measured"),
    q("Toil Reduction for SRE", "SRE", "Common",
      "What is toil in SRE and how do you measure and reduce it?",
      "Toil is manual, repetitive, automatable ops work that scales linearly with service growth. Target <50% of SRE time on toil; automate or eliminate the rest.",
      "**Toil examples:**\n- Manual certificate renewal checks\n- Clicking through portal to scale instances\n- Copy-pasting deployment commands\n- Manually correlating logs across 15 services\n\n**Reduction playbook:**\n1. Measure toil hours/week per on-call rotation\n2. Prioritize highest-frequency tasks\n3. Automate with runbooks → scripts → pipelines\n4. Track toil ratio quarterly\n\n**Architect:** Design self-healing patterns — auto-scale, auto-restart, automated rollback — to prevent toil at source.",
      "Toil reduction is how SRE teams buy time for engineering — architects enable automation.",
      "Toil vs overhead? — Overhead (meetings) is not automatable; toil is.",
      "When toil is acceptable? — Brief manual intervention during novel incidents — then automate.",
      "Hero culture rewarding manual firefighting",
      "Automating without measuring toil baseline",
      "SRE team spending 80% on ticket queue"),
    q("Continuous Learning Culture", "DevOps Culture", "Common",
      "How do architects embed continuous learning into a DevOps transformation?",
      "Learning loops: blameless postmortems, game days, internal tech talks, ADR library, chaos experiments with documented outcomes. Celebrate learning from failures publicly.",
      "**Practices:**\n- **Postmortem library** — searchable incident learnings\n- **Game days** — quarterly failure injection (kill AZ, corrupt cache)\n- **Brown bags** — teams demo what they learned from outages\n- **Guilds** — .NET, security, observability communities of practice\n\n**Architect actions:** Present ADR decisions including rejected options — models learning. Fund conference attendance tied to internal presentation.\n\n**Anti-pattern:** Postmortem actions never completed — learning theater without improvement.",
      "Continuous learning is CALMS 'Sharing' — architects institutionalize knowledge transfer.",
      "Learning vs blame? — Blameless does not mean no accountability for malicious acts.",
      "Measure learning? — Postmortem action completion rate, repeat incident rate.",
      "Incidents closed without postmortem",
      "Same root cause incident three times",
      "Knowledge locked in senior engineers' heads"),
    q("DevSecOps Shift Left", "DevSecOps", "Very Common",
      "What does shift left mean in DevSecOps for a .NET microservices platform?",
      "Security earlier in SDLC: threat modeling at design, SAST/dependency scan in PR, secrets in Key Vault, container scan before deploy — not penetration test after launch.",
      "**Shift-left layers:**\n1. **Design** — STRIDE threat model in architecture review\n2. **Code** — CodeQL, SonarQube on every PR\n3. **Build** — Dependabot, NuGet CVE gate\n4. **Pipeline** — Trivy image scan, SBOM generation\n5. **Runtime** — WAF, Defender for Cloud\n\n**Gate policy:** Block critical/high new issues; baseline legacy debt. Parallelize scans with tests.\n\n**Architect:** Golden path templates include security by default — OIDC not secrets, Managed Identity mandatory.",
      "Shift left is architectural — security gates encoded in platform not optional checklist.",
      "Shift left vs shift everywhere? — Runtime detection still needed — defense in depth.",
      "DAST placement? — Staging nightly — not blocking every PR.",
      "Security review only before production launch",
      "Blocking all PRs on medium SonarQube findings in legacy code",
      "Developers responsible for manual security checklist per deploy"),
    q("Change Failure Root Cause Analysis", "DORA Metrics", "Common",
      "A team has 20% change failure rate. How do you perform root cause analysis?",
      "Classify failures: code defect, config drift, dependency break, schema incompatibility, infrastructure. Measure CFR per service and per change type — one bad service skews average.",
      "**RCA process:**\n1. Tag every failed deploy in deployment system\n2. Categorize: test gap, missing contract test, bad migration, env config diff\n3. Pareto chart — top 3 categories get architectural fixes\n\n**Example findings:**\n- 40% failures from breaking EF migrations → expand-contract policy\n- 30% from missing payment contract test → Pact in CI\n- 20% from staging/prod config drift → IaC for all env config\n\n**Architect:** CFR is lagging indicator — fix systemic gates not individual developers.",
      "CFR RCA connects metrics to architectural quality gates.",
      "CFR vs incident rate? — CFR is deploy-triggered failure; incidents include non-deploy causes.",
      "Target CFR? — Elite <15%; start by halving current rate.",
      "Reacting to CFR with deploy freeze",
      "No per-service CFR breakdown",
      "Root cause = human error without systemic fix"),
    q("Deployment Freeze Anti-Pattern", "Release Management", "Common",
      "Why are deployment freezes before holidays a DevOps anti-pattern and what do you do instead?",
      "Freezes stop learning, accumulate big-bang releases, and often fail anyway — outages spike when frozen code finally deploys. Replace with smaller changes, feature flags, and heightened monitoring.",
      "**Problems with freeze:**\n- Risk concentrates in post-freeze mega-deploy\n- Security patches delayed\n- Team velocity drops; morale suffers\n- False sense of safety — prod still drifts\n\n**Alternatives:**\n- Feature flags — dark deploy risky code\n- Canary with tighter thresholds during peak\n- On-call staffing increase\n- Automated rollback on SLO burn\n\n**Exception:** Regulated blackout windows — negotiate automated low-risk changes still allowed.",
      "Architects argue against freeze with risk math — smaller batches beat big-bang.",
      "Black Friday? — Freeze new features via flags; allow hotfixes and security patches.",
      "Stakeholder fear? — Show CFR data for big-bang vs continuous deploy.",
      "Annual freeze becoming permanent risk management",
      "No exception process for critical security patches",
      "Freeze without reducing change size after thaw"),
    q("MTTR Reduction via Runbook Automation", "SRE", "Common",
      "How do runbook automation and Azure Automation reduce MTTR?",
      "Codify incident response: diagnostic queries, scale-out scripts, slot swap rollback, cache flush — triggered from alert or runbook button. MTTR drops when L1 executes automation instead of paging senior engineer.",
      "**Automation tiers:**\n1. **Diagnostic** — auto-run KQL query, attach results to incident ticket\n2. **Remediation** — restart app, scale SQL DTU, swap deployment slot\n3. **Escalation** — auto-page if automation fails\n\n**Example:** Payment API 5xx alert → runbook checks SQL DTU saturation → auto-scale + notify on-call → if unresolved in 10 min, page SRE.\n\n**Architect:** Design services for operability — health endpoints checking dependencies, graceful degradation paths documented in runbooks.",
      "MTTR is a DORA metric architects improve through operability design.",
      "Runbook vs playbook? — Runbook is technical steps; playbook includes comms and escalation.",
      "Azure Automation vs GitHub Actions? — Automation for hybrid/runbook response; Actions for deploy.",
      "Runbooks as Word docs nobody reads during incidents",
      "Automation without idempotency testing",
      "MTTR measured but no runbook linked to alerts"),
    q("Incident Commander Role", "Incident Management", "Common",
      "What does an incident commander do during a Sev1 outage?",
      "IC coordinates response — not the person fixing. Owns timeline, communication, decision log, resource allocation. Ensures parallel workstreams don't conflict.",
      "**IC responsibilities:**\n- Declare incident severity and channel\n- Assign roles: ops lead (technical), comms lead (status page), scribe (timeline)\n- Regular status cadence every 15 min\n- Decision authority: rollback vs fix-forward\n- End incident when SLO restored; schedule postmortem\n\n**Architect as IC:** Technical depth helps prioritize — payment down beats cosmetic CSS bug. Defer root cause to postmortem during incident.\n\n**Training:** Rotate IC role in game days — not only managers.",
      "IC role shows operational leadership — senior architects expected to lead Sev1.",
      "IC vs ops lead? — IC coordinates; ops lead executes technical investigation.",
      "When no IC? — Small teams — on-call lead assumes IC informally.",
      "Everyone debugging with no coordination",
      "IC also deep-diving logs — role confusion",
      "No external communication during customer-impacting outage"),
    q("SRE vs DevOps Organizational Models", "Org Design", "Common",
      "Compare embedding SREs in product teams vs centralized SRE platform team.",
      "Embedded SRE: deep product knowledge, faster trust. Centralized: consistent practices, tooling standards. Hybrid common: platform SRE builds tools, embedded SRE partners with 2–3 product teams.",
      "**Models:**\n| Model | Pros | Cons |\n|-------|------|------|\n| Embedded | Context, ownership | Inconsistent practices |\n| Centralized | Standards, career path | Ticket queue bottleneck |\n| Hybrid | Balance | Coordination overhead |\n\n**DevOps vs SRE:** DevOps is cultural movement; SRE is concrete implementation with error budgets and toil metrics.\n\n**Architect:** Define SRE engagement model in platform ADR — when embedded SRE joins new product team.",
      "Org model affects reliability outcomes — architects influence structure.",
      "SRE team as ops rename? — SRE must do engineering work — automation, not ticket routing.",
      "DevOps engineer title? — Often platform engineering — clarify expectations.",
      "SRE team that only pages and escalates",
      "No engagement model — SRE pulled into every project ad hoc",
      "Confusing DevOps culture with eliminating ops entirely"),
    q("Conway's Law in Microservices", "Architecture", "Very Common",
      "How does Conway's Law affect microservice decomposition decisions?",
      "Organizations produce systems mirroring communication structure. Split services along team boundaries — if two teams must coordinate daily, don't split their services without API contract discipline.",
      "**Implications:**\n- 4 teams → aim for ~4–8 services with clear ownership\n- Split by bounded context matching team cognitive load\n- **Inverse Conway maneuver:** Restructure teams to desired architecture (risky but intentional)\n\n**Anti-pattern:** 50 microservices, 5 developers — coordination overhead kills velocity.\n\n**Architect:** Present org chart alongside architecture diagram in reviews — misalignment predicts integration pain.",
      "Conway's Law is why architects need org design literacy.",
      "Monorepo effect? — Teams can still own directories — Conway applies to ownership.",
      "Outsourced integration? — Vendor boundary becomes service boundary — plan ACL.",
      "50 services for 8 developers",
      "Service split without team ownership assignment",
      "Ignoring communication overhead in integration design"),
    q("Technical Debt vs Delivery Velocity", "Engineering Culture", "Common",
      "How do you balance technical debt paydown with feature velocity for executives?",
      "Reserve 15–20% capacity for debt; quantify debt cost in DORA metrics (CFR, lead time). Present debt as risk with business impact — not engineering wish list.",
      "**Framework:**\n- **Interest payments** — incidents, slow deploys, developer attrition from frustration\n- **Principal** — refactoring cost to fix\n- **Prioritize** debt touching revenue path (checkout) over cosmetic modules\n\n**Metrics:** Track CFR and lead time before/after debt sprints. Show 25% CFR drop after test coverage investment.\n\n**Architect:** ADR documents accepted debt with expiration — 'shared DB acceptable for 6 months during strangler.'",
      "Debt negotiation is executive communication — architects quantify risk.",
      "Boy scout rule? — Incremental improvement each PR — complements dedicated debt sprints.",
      "Debt register? — Visible backlog with business impact scores.",
      "Big-bang rewrite as only debt strategy",
      "Zero debt capacity — velocity illusion until outage",
      "Debt items without business impact articulation"),
    q("Developer Experience Metrics", "Platform Engineering", "Common",
      "What metrics measure Internal Developer Platform developer experience?",
      "Time-to-first-deploy, PR build time p50/p95, platform NPS survey, golden path adoption %, support ticket volume, and DORA metrics per team using platform.",
      "**Leading indicators:**\n- Template clone-to-running-hello-world < 1 day\n- % repos on golden path workflow\n- Developer satisfaction quarterly survey (5 questions)\n\n**Lagging indicators:**\n- Deployment frequency increase after IDP launch\n- MTTR decrease\n- Onboarding time new hire → first prod commit\n\n**Red flag:** Low adoption despite mandate — platform failed; interview users don't enforce harder.",
      "DX metrics prove platform ROI — architects speak product metrics for internal products.",
      "SPACE framework? — Satisfaction, Performance, Activity, Communication, Efficiency — broader than DORA.",
      "Vanity metric trap? — Pipelines created count meaningless without adoption.",
      "Platform success measured only by uptime",
      "No developer survey feedback loop",
      "Mandating platform without measuring friction"),
    q("Release Train vs Continuous Delivery", "Release Management", "Very Common",
      "When is a release train appropriate vs continuous delivery for .NET microservices?",
      "Release train for coordinated multi-service releases (shared schema, mobile app store). Continuous delivery for independently deployable microservices with contract tests.",
      "**Release train:** Fixed schedule (e.g., Thursday 2pm), all services board together, integration window, higher coordination cost.\n\n**Continuous:** Each service deploys on green main — Pact/contract tests prevent integration breaks.\n\n**Hybrid:** Most services continuous; quarterly train for major versioned API breaking changes.\n\n**Architect:** Release train often signals architectural coupling — goal is reduce train frequency by decoupling.",
      "Release model reflects architecture coupling — trains are symptom of tight coupling.",
      "SAFe release train? — Agile at scale — architect knows when overhead justified.",
      "Mobile constraint? — App store review forces train for client; server can still CD.",
      "Release train for 3 independent microservices",
      "Train as excuse to skip automated integration tests",
      "Continuous deploy without contract tests on shared APIs"),
    q("SOC 2 Compliance Automation", "Compliance", "Common",
      "How do you automate SOC 2 evidence collection in CI/CD pipelines?",
      "Pipeline generates audit artifacts: test results, security scan reports, deployment approvals, access logs, change tickets linked to commit SHA — stored immutably in blob storage.",
      "**CC8 change management automation:**\n- Branch protection rules enforced via API audit\n- Production deploy requires environment approval — logged\n- SAST/dependency scan results archived per build\n- Infrastructure changes via IaC PR with plan diff\n\n**Tools:** Vanta/Drata integrate with GitHub and Azure; custom scripts export deployment records.\n\n**Architect:** Design golden path so compliant path is default — manual prod deploy impossible.",
      "Compliance automation is architecture — auditors trust systems not screenshots.",
      "SOC 2 vs ISO 27001? — Overlapping controls; pipeline evidence serves both.",
      "Manual evidence before audit? — Automate continuous — audit is sampling not scramble.",
      "Scrambling screenshots week before audit",
      "Compliance as separate team bolt-on",
      "No linkage between deploy and change ticket"),
    q("Audit Trail in CI/CD Pipelines", "Governance", "Common",
      "What audit trail must a production CI/CD pipeline maintain for regulated .NET workloads?",
      "Immutable record: who approved, what commit SHA, what artifact digest, what tests passed, what scans ran, when deployed, to which environment — retained 7 years typical.",
      "**Audit fields:**\n- `commitSha`, `artifactDigest`, `buildId`\n- Approver identity and timestamp\n- Test and scan result artifacts\n- Environment promotion history\n- Rollback events with reason\n\n**Implementation:** GitHub deployment API, Azure DevOps deployment records, append-only blob storage. OIDC subject identifies pipeline identity.\n\n**Architect:** Segregation of duties — developer cannot approve own prod deploy.",
      "Audit trail enables forensic investigation and regulatory compliance.",
      "Mutable logs? — Ship to SIEM with WORM storage — pipeline logs tamper-evident.",
      "Artifact provenance? — Sigstore/cosign signature in audit record.",
      "Deployment with no commit SHA traceability",
      "Developer self-approves production",
      "Audit logs in ephemeral CI runner disk only"),
    q("DORA Benchmarking Cadence", "DORA Metrics", "Common",
      "How often should teams benchmark DORA metrics and against whom?",
      "Measure weekly automated, review monthly with team, benchmark quarterly against industry (DORA/Accelerate report) and own historical trend. Compare similar teams internally not across unlike contexts.",
      "**Cadence:**\n- **Weekly:** Automated dashboard — deployment frequency, lead time, CFR, MTTR\n- **Monthly:** Team retrospective — one metric improvement goal\n- **Quarterly:** Compare to DORA elite/high/medium/low tiers; present to leadership\n\n**Benchmarking pitfalls:**\n- Vanity deploy counts without CFR context\n- Comparing mobile team to API team without normalization\n\n**Architect:** Use DORA to prioritize investments — if lead time high, value stream map before buying new CI tool.",
      "Benchmarking cadence turns DORA from poster to management system.",
      "DORA vs SPACE? — Complementary — DORA delivery, SPACE developer wellbeing.",
      "Industry benchmark source? — DORA State of DevOps report annually.",
      "Annual DORA glance with no action",
      "Benchmarking against Google when 50-person fintech",
      "Improving deploy count while CFR spikes"),
]

WEEK_30_Q011_Q030 = [
    q("Pipeline as Code Principles", "CI/CD", "Very Common",
      "Why must CI/CD pipelines be defined as code in version control?",
      "Pipeline as code enables review, audit, rollback, and reproducibility. YAML in Git — not click-ops in UI — same PR process as application code.",
      "**Benefits:**\n- **Reviewability** — security team reviews pipeline changes\n- **Auditability** — git blame on who added prod approval gate\n- **Reproducibility** — branch builds use same pipeline definition\n- **DR** — pipeline definition survives portal UI changes\n\n**Implementation:** `.github/workflows/deploy.yml` or `azure-pipelines.yml` in repo. Reusable workflows in `.github/workflows/` shared org-wide.\n\n**Architect:** Platform team owns reusable workflow library; product teams consume via `uses:` reference.",
      "Pipeline as code is governance foundation for enterprise CI/CD.",
      "UI-defined pipelines? — Acceptable for spike; migrate to code before production.",
      "Pipeline versioning? — Pin reusable workflow to tag or SHA — not `@main`.",
      "Production pipeline only configurable in portal UI",
      "No PR review on pipeline YAML changes",
      "Different pipeline definition per environment ad hoc"),
    q("Reusable GitHub Actions Workflows", "GitHub Actions", "Very Common",
      "How do you design reusable workflows for .NET microservices across 20 repos?",
      "Central `org-actions` repo with `dotnet-build.yml`, `dotnet-deploy-azure.yml`. Caller passes inputs: `serviceName`, `environment`, `projectPath`. OIDC auth baked into reusable workflow.",
      "**Pattern:**\n```yaml\njobs:\n  deploy:\n    uses: org/actions/.github/workflows/dotnet-deploy.yml@v2\n    with:\n      service-name: order-api\n      environment: production\n    secrets: inherit\n```\n\n**Design rules:**\n- Inputs for variation; secrets via `secrets: inherit` or explicit mapping\n- Version reusable workflows with tags (`@v2`)\n- Document required inputs in README\n\n**Architect:** One security fix in reusable workflow patches 20 repos on version bump.",
      "Reusable workflows are IDP core — encode org standards once.",
      "Composite actions vs reusable workflows? — Composites for steps bundle; workflows for full job orchestration.",
      "Breaking change? — Major version tag + migration guide.",
      "Copy-paste 200-line workflow per repo",
      "Reusable workflow pinned to `@main`",
      "Each team invents different OIDC configuration"),
    q("Environment Promotion Gates", "CI/CD", "Very Common",
      "Design environment promotion gates from dev through production for a .NET API.",
      "Same artifact promotes: dev (auto) → staging (auto + integration tests) → prod (manual approval + smoke tests). Gates block on test failure, scan critical CVE, or missing approval.",
      "**Gate types:**\n- **Automated:** unit test pass, SAST clean, integration test pass\n- **Manual:** prod approval from on-call lead + change ticket\n- **Temporal:** no Friday prod deploy without exec approval\n\n**Azure DevOps:** `environment` resources with checks. **GitHub:** `environment: production` with required reviewers.\n\n**Architect:** Never rebuild artifact at prod gate — promote immutable `order-api:1.2.3+abc123` tag.",
      "Promotion gates encode risk management in pipeline — architect defines gate policy.",
      "Skip staging? — Only for low-risk internal tools — document exception.",
      "Gate bypass? — Break-glass role with mandatory post-incident review.",
      "Rebuild on production promotion",
      "Staging gate skipped for 'hotfix'",
      "No smoke test after prod deploy"),
    q("Immutable Artifacts in ACR", "Artifacts", "Very Common",
      "How do you manage immutable container artifacts in Azure Container Registry?",
      "Build once, push image with semver + git SHA tag. Enable ACR retention policies and content trust. Prod deploy references digest not `latest`.",
      "**Tagging strategy:**\n- `order-api:1.4.2` — semver release\n- `order-api:1.4.2+abc1234` — traceable to commit\n- `order-api:sha-abc1234` — immutable fallback\n\n**ACR practices:**\n- Geo-replication for prod pulls\n- Quarantine policy for unscanned images\n- Retention: keep last 10 semver tags per repo\n\n**Architect:** Artifact digest in deployment audit log — proves exact bits in prod.",
      "Immutable artifacts are supply chain foundation — connects to SLSA and SBOM.",
      "latest tag in prod? — Anti-pattern — impossible rollback to known version.",
      "Mutate image after push? — Violates immutability — rebuild and retag.",
      "Production deploys `latest` tag",
      "Different image built for staging vs prod",
      "No artifact-to-commit traceability"),
    q("Semantic Versioning in CI/CD", "Release Management", "Common",
      "How does semantic versioning integrate with automated CI/CD for .NET APIs?",
      "MAJOR.MINOR.PATCH: breaking change bumps major, feature bumps minor, fix bumps patch. GitVersion or MinVer calculates from conventional commits on main.",
      "**Pipeline flow:**\n1. Conventional commit on PR (`feat:`, `fix:`, `BREAKING CHANGE:`)\n2. GitVersion on main computes `1.5.0`\n3. Build tags Docker image and NuGet package `1.5.0`\n4. Git tag `v1.5.0` created automatically\n\n**Consumer impact:** NuGet clients pin major; internal APIs use contract tests for minor bumps.\n\n**Architect:** Document semver policy in ADR — when major bump required for API changes.",
      "Semver communicates breaking change risk to consumers — architect enforces on public APIs.",
      "Calendar versioning? — Acceptable for SaaS with no library consumers — document choice.",
      "0.x semver? — Unstable API — anything may break.",
      "Manual version bump forgotten in release rush",
      "Breaking API change as patch bump",
      "No conventional commit discipline"),
    q("Rollback Strategies in Production", "Deployment Strategy", "Very Common",
      "Compare rollback strategies when a .NET API deploy causes elevated 5xx errors.",
      "App Service slot swap back (instant), redeploy previous artifact digest (minutes), feature flag disable (seconds for logic), database forward-fix (slowest — avoid).",
      "**Decision tree:**\n1. **Feature flag** — if new code path flagged → disable flag first\n2. **Slot swap** — if binary regression → swap staging/previous slot\n3. **Artifact redeploy** — pin previous digest in pipeline\n4. **DB rollback** — last resort; expand-contract should make rare\n\n**Automation:** Pipeline monitors 5xx for 10 min post-deploy; auto-swap on breach.\n\n**Architect:** Rollback must be tested quarterly — untested rollback is wishful thinking.",
      "Rollback strategy is architecture requirement — design deploy for reversibility.",
      "Blue-green vs rolling rollback? — Blue-green instant; rolling must drain connections.",
      "Canary rollback? — Stop traffic shift — previous version still serving majority.",
      "Only rollback plan is restore database backup",
      "Breaking migration deployed with rolling update",
      "Rollback never tested in staging"),
    q("Smoke Tests Post-Deploy", "Testing", "Common",
      "What smoke tests run immediately after production deployment?",
      "Critical path HTTP checks: `/health` with dependency validation, `POST /auth/token`, `GET /orders/{knownId}` — 60 seconds total, fail triggers auto-rollback.",
      "**Smoke test design:**\n- Run against prod URL from pipeline (not internal only)\n- Validate DB connectivity in health endpoint\n- Use test account with synthetic data\n- Idempotent — safe to re-run\n\n**Not smoke tests:** Full regression suite (staging), load tests (separate job).\n\n**Example:**\n```bash\ncurl -f https://api.contoso.com/health\ncurl -f -X POST https://api.contoso.com/api/v1/orders/smoke-test\n```\n\n**Architect:** Smoke tests are deployment gate — define in platform reusable workflow.",
      "Smoke tests catch 'deploy succeeded but app broken' — common with config errors.",
      "Health check returns 200 without DB? — False positive — validate dependencies.",
      "Synthetic vs smoke? — Smoke is post-deploy gate; synthetic is continuous probe.",
      "No post-deploy verification",
      "Health endpoint always returns Ok()",
      "15-minute E2E suite blocking every deploy"),
    q("Integration Test Pyramid in Pipelines", "Testing", "Very Common",
      "Where do integration tests sit in the test pyramid for CI/CD pipeline design?",
      "Many unit tests (fast, PR gate), fewer integration tests (Testcontainers SQL/Redis, main branch gate), minimal E2E (staging/nightly). Integration tests validate real dependencies without full stack.",
      "**Pipeline placement:**\n- **PR:** unit + contract tests (< 10 min)\n- **Main:** + integration with Testcontainers (< 20 min)\n- **Staging:** E2E Playwright against deployed env (nightly or pre-prod gate)\n\n**.NET:** `WebApplicationFactory` + Testcontainers for SQL. Don't hit prod dependencies from CI.\n\n**Architect:** Integration test failures blocking main — not PR if slow — balance feedback speed vs coverage.",
      "Test pyramid placement affects CI duration and CFR — architects own the strategy.",
      "Integration vs E2E? — Integration tests service with real DB; E2E tests user journey across services.",
      "Flaky integration tests? — Quarantine and fix — don't disable category entirely.",
      "E2E tests on every PR blocking 45 minutes",
      "No integration tests — only unit mocks",
      "Integration tests hitting production APIs"),
    q("E2E Test Placement Strategy", "Testing", "Common",
      "When should E2E tests block deployment vs run asynchronously?",
      "E2E blocks staging promotion if < 15 min and stable. Nightly E2E for full regression. Never block PR with 30-test Playwright suite — feedback too slow.",
      "**Tiers:**\n1. **Deploy gate (staging):** 5–10 critical journey tests (login, checkout)\n2. **Nightly:** full regression 200+ scenarios\n3. **Pre-release:** manual exploratory + automated full suite\n\n**Flake management:** Retry once, quarantine chronic flakes, root cause fix required.\n\n**Architect:** E2E tests user-visible contracts — fewer but high signal. Complement with contract tests for service boundaries.",
      "E2E placement is trade-off between speed and confidence — document policy.",
      "Playwright in CI? — Containerized browsers, parallel shards, trace on failure.",
      "E2E data setup? — Seed test tenant — never prod data.",
      "200 E2E tests blocking every commit",
      "Zero E2E — prod is test environment",
      "Flaky tests ignored with `@Ignore`"),
    q("Pipeline Parallelism", "CI/CD", "Common",
      "How do you parallelize a .NET CI pipeline without wasting agent minutes?",
      "Matrix builds per project, parallel jobs for test/scan/build, fan-in before deploy. Use `needs:` DAG — don't serialize independent stages.",
      "**Patterns:**\n```yaml\njobs:\n  test:\n    strategy:\n      matrix:\n        project: [Order.Api, Payment.Api, Catalog.Api]\n  security-scan:\n    runs-on: ubuntu-latest  # parallel with test\n  deploy:\n    needs: [test, security-scan]\n```\n\n**Limits:** Agent pool concurrency caps — prioritize PR feedback over nightly jobs.\n\n**Architect:** Parallelism reduces lead time — a DORA lever — but costs compute; right-size pools.",
      "Parallelism directly attacks lead time — measure p95 pipeline duration.",
      "Over-parallelization? — NuGet restore per job — use cache or shared artifact.",
      "Self-hosted parallelism? — Scale runner pool based on queue depth.",
      "Fully serial pipeline 45 minutes",
      "Matrix 50 projects on every doc change",
      "Parallel deploys to same environment"),
    q("NuGet Cache Strategies in CI", "CI/CD", "Common",
      "How do you cache NuGet packages in GitHub Actions for faster .NET builds?",
      "Use `actions/cache` keyed on `**/packages.lock.json` or `**/*.csproj` hash. Enable lock files in SDK-style projects for deterministic restore.",
      "**GitHub Actions:**\n```yaml\n- uses: actions/cache@v4\n  with:\n    path: ~/.nuget/packages\n    key: nuget-${{ hashFiles('**/packages.lock.json') }}\n```\n\n**Azure DevOps:** Pipeline cache task with same key pattern.\n\n**Also cache:** `~/.dotnet/tool` for dotnet-ef, GitVersion.\n\n**Measure:** Restore drops from 90s to 8s — meaningful lead time improvement at scale.",
      "Caching is low-effort lead time win — platform templates should include by default.",
      "Cache poisoning? — Key on lock file hash — invalidate on dependency change.",
      "Azure Artifacts feed? — Cache + upstream proxy reduces public NuGet hits.",
      "No cache — full restore every build",
      "Cache key `nuget` never invalidated",
      "Committing packages folder to git"),
    q("Self-Hosted Runners Trade-offs", "CI/CD", "Common",
      "When do you use self-hosted GitHub Actions runners vs GitHub-hosted?",
      "Self-hosted when: VNet access to private SQL/AKS, larger machines for build, compliance data residency, or GPU builds. GitHub-hosted for default OSS-style isolation and zero maintenance.",
      "**Self-hosted requirements:**\n- Hardened VM image, auto-patching\n- Ephemeral runners preferred (one job per VM)\n- Network isolate — runners not on corp desktop\n- OIDC to Azure — no persistent SP on runner disk\n\n**Risks:** Compromised runner accesses internal network — treat as production asset.\n\n**Architect:** Platform team operates runner scale set with Terraform/Bicep — not developer laptops.",
      "Runner choice is security and networking architecture decision.",
      "Azure DevOps agents? — Same trade-offs — Microsoft-hosted vs self-hosted VMSS.",
      "Runner autoscaling? — Queue depth triggers scale out.",
      "Developer laptop as production deploy runner",
      "Long-lived secrets on self-hosted runner",
      "Self-hosted without patching cadence"),
    q("Deployment Approvals Design", "Governance", "Common",
      "Design deployment approval workflow for production with segregation of duties.",
      "PR author cannot approve prod deploy. Minimum 1 reviewer from on-call rotation + automated gate pass. Emergency break-glass with audit.",
      "**Layers:**\n1. Automated: tests, scans, smoke staging\n2. Manual: environment protection rule — 1 of 2 on-call leads\n3. Optional: change ticket ID required in deploy input\n\n**GitHub Environments:** `required_reviewers`, `wait_timer` 5 min for cancel window.\n\n**SOC 2:** Demonstrate deployer ≠ approver in audit export.",
      "Approval design satisfies compliance without weekly CAB for every deploy.",
      "Same person codes and approves prod? — Violation for regulated workloads.",
      "Approval fatigue? — Standard changes pre-approved via policy.",
      "Developer self-approves production",
      "Manual approval with no automated gates",
      "Approval required but no on-call rotation defined"),
    q("GitHub Environments Configuration", "GitHub Actions", "Common",
      "How do GitHub Environments enforce deployment policy for production?",
      "Create `production` environment with required reviewers, branch restriction (`main` only), secrets scoped to environment, deployment branch policies.",
      "**Configuration:**\n- **Protection rules:** 2 required reviewers, 5-minute wait timer\n- **Secrets:** `AZURE_CLIENT_ID` prod-only — not available on PR workflows\n- **Deployment branches:** `main` and `release/*` only\n- **OIDC:** Federated credential subject includes `environment:production`\n\n**Workflow:**\n```yaml\nenvironment: production\n```\n\n**Architect:** Environment-scoped OIDC limits blast radius of compromised workflow.",
      "GitHub Environments implement least-privilege deploy credentials.",
      "Environment vs repository secrets? — Environment secrets only exposed during protected deploy job.",
      "Preview environments? — `pull_request` environment auto-created — destroy on close.",
      "Production secrets available on PR workflows",
      "No branch restriction on production environment",
      "OIDC federated credential trusts entire org"),
    q("Azure DevOps Multi-Stage YAML", "Azure DevOps", "Common",
      "Structure a multi-stage Azure DevOps pipeline for .NET with dev, staging, and prod.",
      "Stages: Build → DeployDev → TestIntegration → DeployStaging → Approval → DeployProd. `dependsOn` chains stages; `deployment` jobs target environments.",
      "**Template:**\n```yaml\nstages:\n- stage: Build\n  jobs: [build, test, publish artifact]\n- stage: DeployStaging\n  dependsOn: Build\n  jobs:\n  - deployment: Deploy\n    environment: staging\n- stage: DeployProd\n  dependsOn: DeployStaging\n  jobs:\n  - deployment: Deploy\n    environment: production\n```\n\n**Artifacts:** `PublishPipelineArtifact` — same package all stages.\n\n**Architect:** ADO environments parallel GitHub Environments — unified policy across orgs if multi-VCS.",
      "Multi-stage YAML is Azure-native promotion model — know syntax for interviews.",
      "Stage vs job parallelism? — Stages sequential by default; parallel stages with `dependsOn: []`.",
      "Template repositories? — Extend shared pipeline template for DRY.",
      "Single stage build and deploy prod",
      "Rebuild in DeployProd stage",
      "No environment checks on production stage"),
    q("Container Image Scanning with Trivy", "DevSecOps", "Common",
      "How do you integrate Trivy container scanning into a .NET Docker build pipeline?",
      "Scan image after `docker build`, before push to ACR. Gate on CRITICAL/HIGH CVEs; export SARIF to GitHub Security tab.",
      "**Pipeline step:**\n```yaml\n- uses: aquasecurity/trivy-action@master\n  with:\n    image-ref: order-api:${{ github.sha }}\n    severity: CRITICAL,HIGH\n    exit-code: 1\n```\n\n**Policy:** Block new critical; grandfather existing with expiry ticket. Base image updates via Dependabot Dockerfile PRs.\n\n**Architect:** Scanning is shift-left — cheaper than runtime breach.",
      "Container scanning is non-negotiable gate for production images.",
      "Trivy vs Defender? — Trivy in CI; Defender for runtime — complementary.",
      "False positives? — VEX document accepted risk with expiry.",
      "Push to ACR before scan",
      "Scan disabled for 'speed'",
      "No base image update process"),
    q("SBOM Generation in CI", "Supply Chain", "Common",
      "What is an SBOM and how do you generate one for .NET container images?",
      "Software Bill of Materials lists all components and versions. Generate with Syft or `dotnet sbom`, attach to release artifact and ACR metadata for incident CVE response.",
      "**Generation:**\n```bash\nsyft order-api:1.2.3 -o spdx-json > sbom.spdx.json\n```\n\n**Storage:** Attach to GitHub release, upload to dependency track, link in deployment audit.\n\n**Incident use:** Log4Shell-style — query SBOM for affected library versions across fleet in minutes not weeks.\n\n**Architect:** SBOM mandatory for regulated customers — encode in golden path.",
      "SBOM enables fleet-wide vulnerability response — supply chain architecture.",
      "SPDX vs CycloneDX? — Both accepted — pick one org standard.",
      "NuGet SBOM? — `dotnet sbom` for managed dependencies inside image.",
      "No component inventory during CVE crisis",
      "SBOM generated but not stored with release",
      "Assuming Dockerfile alone documents all deps"),
    q("SLSA Supply Chain Levels", "Supply Chain", "Common",
      "Explain SLSA levels and what your .NET CI/CD pipeline needs for SLSA Build Level 3.",
      "SLSA (Supply-chain Levels for Software Artifacts) L3: non-falsifiable provenance, isolated build, signed provenance. GitHub OIDC + attestations + pinned actions moves toward L3.",
      "**Requirements L3:**\n- Build platform generates provenance (not modifiable by build)\n- Ephemeral isolated build environment\n- Provenance signed and verifiable\n\n**Practices:**\n- Pin GitHub Actions to commit SHA\n- OIDC federation — no long-lived secrets\n- `slsa-github-generator` for provenance attestation\n- Hermetic builds — lock files, no network in compile if possible\n\n**Architect:** Present SLSA roadmap to security — incremental not binary.",
      "SLSA frames supply chain maturity — architects speak levels not buzzwords.",
      "Sigstore cosign? — Sign container images — complements SLSA provenance.",
      "L4 realistic? — Hermetic reproducible builds — aspirational for most .NET shops.",
      "Floating action tags `@v4`",
      "No build provenance attestation",
      "Developer laptop builds production artifacts"),
    q("Pipeline Secrets Rotation", "Security", "Common",
      "How do you rotate CI/CD secrets without breaking deployments?",
      "Prefer OIDC over secrets. For remaining secrets: dual-credential overlap window, rotate in Key Vault, update GitHub secret, verify deploy, revoke old.",
      "**Rotation playbook:**\n1. Generate new secret in Key Vault\n2. Add as `SECRET_V2` in GitHub environment\n3. Update workflow to prefer V2\n4. Successful prod deploy → remove V1\n5. Audit log rotation event\n\n**OIDC migration:** Eliminate `AZURE_CREDENTIALS` JSON — federated credential only.\n\n**Schedule:** 90-day rotation for any remaining PATs; immediate on leak suspicion.",
      "Secrets rotation is operational requirement — OIDC reduces rotation burden.",
      "Key Vault reference in App Service? — Runtime secret separate from CI secret.",
      "GitGuardian alert? — Rotate immediately — assume compromise.",
      "Never rotated GitHub SP secret since 2019",
      "Rotation without dual-credential overlap",
      "Secrets in workflow YAML encoded base64"),
    q("Failed Deploy Auto-Rollback", "CI/CD", "Common",
      "Implement automatic rollback when post-deploy metrics breach SLO.",
      "Pipeline deploys → monitors App Insights 5xx rate and p99 for 10 min → if threshold breached, swap slot back or redeploy previous digest → page on-call with incident.",
      "**Implementation options:**\n- **App Service:** Swap slots via Azure CLI in pipeline\n- **AKS:** Argo Rollouts automatic promotion abort\n- **GitHub Actions:** Custom step querying metrics API\n\n**Thresholds:** 5xx > 1% for 5 min OR p99 > 2× baseline.\n\n**Architect:** Auto-rollback requires health signal quality — bad metric causes false rollback.",
      "Auto-rollback improves MTTR — DORA metric — but needs tuning.",
      "Rollback during intentional load test? — Suppress auto-rollback with pipeline flag.",
      "Metric source? — User-facing synthetic + server 5xx — not CPU alone.",
      "Manual rollback only — 45 min MTTR",
      "Auto-rollback on single failed health check",
      "No previous artifact retained for rollback"),
]

WEEK_31_Q011_Q030 = [
    q("Bicep vs Terraform Decision Framework", "IaC", "Very Common",
      "Walk through your decision framework for Bicep vs Terraform on an Azure-only .NET platform.",
      "Azure-only greenfield → Bicep (day-zero resources, ARM-backed state). Multi-cloud or existing TF investment → Terraform. Document in ADR with 5-year migration cost estimate.",
      "**Decision matrix:**\n| Factor | Bicep | Terraform |\n|--------|-------|----------|\n| Azure coverage | Day-zero | Slight lag |\n| State management | ARM tracks | Remote backend required |\n| Multi-cloud | No | Yes |\n| Team skills | ARM DSL learning curve | HCL widely known |\n| Module registry | ACR OCI | Terraform Registry |\n\n**Hybrid:** Bicep for Azure PaaS; Terraform for Cloudflare + Azure. Clear ownership boundary per resource group.\n\n**Architect:** Coexistence OK — never manage same resource in both tools.",
      "IaC choice is long-lived — interviewers want criteria not tribal preference.",
      "Pulumi/C#? — Option when team wants IaC in C# — evaluate team appetite.",
      "Switching cost? — High — pick deliberately in ADR.",
      "Terraform for 100% Azure with no multi-cloud plan",
      "Same resource in Bicep and Terraform",
      "No ADR documenting IaC choice"),
    q("Bicep Module Composition", "Bicep", "Common",
      "How do you compose Bicep modules for a .NET platform landing zone?",
      "Layer modules: `network.bicep` → `keyVault.bicep` → `appService.bicep` → `appInsights.bicep`. Parent template orchestrates; modules expose minimal params and outputs.",
      "**Structure:**\n```\nmodules/\n  networking/vnet.bicep\n  compute/appServicePlan.bicep\n  security/keyVault.bicep\nmain.bicep  # wires modules\n```\n\n**Rules:**\n- Modules 50–150 lines — not monolithic 800-line file\n- Outputs: `keyVaultUri`, `appServiceName` for pipeline consumption\n- Semantic versioning via Bicep registry OCI artifacts\n\n**Architect:** Module catalog mirrors platform service offerings.",
      "Module composition enables environment promotion with same building blocks.",
      "Nested vs registry modules? — Registry for cross-subscription reuse.",
      "Too granular? — Balance copy-paste vs 40-module dependency graph.",
      "800-line monolithic main.bicep",
      "Copy-paste module per environment",
      "Modules with hardcoded prod SKU"),
    q("Terraform State Backend on Azure Storage", "Terraform", "Common",
      "Configure Terraform remote state on Azure Storage for production workloads.",
      "Storage account with versioning, encryption, private endpoint, RBAC restricted to platform pipeline SP. Separate container per environment.",
      "**Backend config:**\n```hcl\nbackend \"azurerm\" {\n  resource_group_name  = \"rg-tfstate-prod\"\n  storage_account_name = \"sttfstateprod\"\n  container_name       = \"tfstate-order\"\n  key                  = \"prod.terraform.tfstate\"\n}\n```\n\n**Hardening:**\n- Blob versioning enabled — recover corrupted state\n- `Storage Blob Data Contributor` only for pipeline SP\n- No public network access\n\n**Architect:** State is DR-critical — backup strategy documented.",
      "Remote state is prerequisite for team IaC — local state is solo-dev only.",
      "State per env vs workspace? — Separate state files for prod isolation preferred.",
      "Sensitive values in state? — Encrypt; restrict access; use sensitive outputs carefully.",
      "Local terraform.tfstate committed to Git",
      "Single state file for dev and prod",
      "No blob versioning on state account"),
    q("Terraform State Locking", "Terraform", "Common",
      "How does state locking prevent concurrent Terraform applies and what breaks it?",
      "Azure backend uses blob lease for lock during `apply`. Concurrent apply fails with lock error — prevents state corruption.",
      "**Failure modes:**\n- CI job killed mid-apply — stale lock remains\n- Fix: `terraform force-unlock LOCK_ID` after verifying no running apply\n\n**Prevention:**\n- Timeout on pipeline jobs\n- One apply per state file at a time (`concurrency` group in GitHub Actions)\n- Never apply prod from laptop while pipeline runs\n\n**Architect:** Locking is why remote state mandatory for teams — local state has no lock.",
      "State locking incidents are common ops scenarios — know unlock procedure.",
      "DynamoDB locking on AWS? — Same concept — Azure uses blob lease.",
      "Bicep locking? — ARM deployment locking at resource group level — different mechanism.",
      "Two pipeline applies to prod simultaneously",
      "Force-unlock without checking running jobs",
      "No concurrency control in CI pipeline"),
    q("IaC Drift Detection Automation", "IaC", "Common",
      "Automate infrastructure drift detection for Bicep and Terraform managed resources.",
      "Nightly scheduled pipeline: `terraform plan -detailed-exitcode` or `az deployment group what-if` — alert on non-empty diff. Azure Policy denies unauthorized changes.",
      "**Layers:**\n1. **Prevent:** Policy denies public IP, enforces SKU whitelist\n2. **Detect:** Nightly plan/what-if in read-only mode\n3. **Remediate:** Auto-apply correct state OR backport portal hotfix to IaC within 24h\n\n**Alert:** Slack message with diff summary — assign owner.\n\n**Architect:** Black Friday manual scale-up must be backported or reverted Monday.",
      "Drift detection closes the loop on IaC governance.",
      "Intentional break-glass? — Ticket + 24h backport SLA.",
      "Drift on auto-scaled resources? — Exclude scale sets from strict drift or use target tracking in IaC.",
      "Portal changes never reconciled to IaC",
      "Drift detected but no owner assigned",
      "Auto-apply drift without human review on prod"),
    q("Bicep What-If Preview", "Bicep", "Common",
      "How do you use Bicep what-if in pull request workflows?",
      "CI runs `az deployment group what-if` with read-only SP; bot comments predicted creates/modifies/deletes on PR. Reviewers see blast radius before merge.",
      "**Pipeline:**\n```bash\naz deployment group what-if \\\n  --resource-group rg-order-staging \\\n  --template-file main.bicep \\\n  --parameters @staging.bicepparam\n```\n\n**PR comment:** Parse JSON output — highlight destructive changes (delete, SKU downgrade).\n\n**Architect:** What-if is Bicep's plan equivalent — mandatory for prod-bound PRs.",
      "What-if prevents surprise deletions — common IaC incident source.",
      "What-if vs validate? — Validate syntax only; what-if shows actual ARM changes.",
      "Scope? — Resource group deployment for most .NET workloads; subscription for landing zone.",
      "First visibility of changes at apply time",
      "What-if skipped for 'small' PRs",
      "No highlight of destructive changes in PR"),
    q("Policy as Code with Azure Policy", "Governance", "Common",
      "Design Azure Policy initiatives that complement Bicep deployments for a .NET platform.",
      "IaC deploys desired state; Policy catches portal drift and non-IaC creation paths. Initiative bundles: require tags, deny public storage, allowed regions, enforce Managed Identity.",
      "**Example policies:**\n- `Deny` — Storage account public access\n- `AuditIfNotExists` — Diagnostic settings on App Service\n- `DeployIfNotExists` — Auto-enable Defender\n\n**Mapping:** Policy initiative per compliance framework (SOC 2 CC6, CC7).\n\n**Architect:** Policy exemption process with expiry — not permanent exceptions.",
      "Policy as code is defense in depth beyond IaC discipline.",
      "Terraform Sentinel? — Plan-time policy for TF shops — Azure Policy for ARM resources.",
      "Policy vs RBAC? — Policy restricts resource config; RBAC restricts who can create.",
      "Policy so strict developers use shadow subscriptions",
      "No exemption workflow",
      "IaC-only governance without Policy"),
    q("Bicep Parameter Files Per Environment", "Bicep", "Common",
      "How do `.bicepparam` files enable safe multi-environment deployments?",
      "Same `main.bicep` module; `dev.bicepparam`, `staging.bicepparam`, `prod.bicepparam` differ SKUs, capacity, feature flags. Never fork template per environment.",
      "**Example:**\n```bicep\n// prod.bicepparam\nusing 'main.bicep'\nparam appServiceSku = 'P2v3'\nparam sqlSku = 'GP_Gen5_4'\nparam enableZoneRedundant = true\n```\n\n**CI:** PR triggers what-if for all environments. Prod apply requires approval.\n\n**Architect:** Parameter files are promotion mechanism — template unchanged across envs.",
      "Parameter files embody DRY multi-environment IaC.",
      "Secrets in bicepparam? — Reference Key Vault — never plain text.",
      "Default params? — `main.bicep` defaults for dev only — prod explicit in bicepparam.",
      "Separate main-prod.bicep fork",
      "Prod SKU hardcoded in shared module",
      "Secrets committed in bicepparam files"),
    q("Key Vault Secret References in IaC", "Security", "Common",
      "Reference Key Vault secrets from Bicep without exposing values in templates.",
      "Use `getSecret()` in Bicep with user-assigned MI granted Key Vault Secrets User. App Service `keyVaultReference` for runtime — secret never in ARM template output.",
      "**Pattern:**\n```bicep\nresource app 'Microsoft.Web/sites@2022-03-01' = {\n  properties: {\n    siteConfig: {\n      appSettings: [{\n        name: 'ConnectionStrings__Default'\n        value: '@Microsoft.KeyVault(SecretUri=${sqlConnSecretUri})'\n      }]\n    }\n  }\n}\n```\n\n**Pipeline:** Deploy MI + Key Vault access before app referencing secrets.\n\n**Architect:** No secrets in Git, state, or pipeline logs — ever.",
      "Secret references separate deployment-time from secret value exposure.",
      "Key Vault purge protection? — Enable on prod — prevent accidental secret deletion.",
      "Rotation? — Update secret version in Key Vault — app picks up new version if configured.",
      "Connection string in bicepparam plain text",
      "Key Vault secret in Terraform output",
      "Secret echoed in what-if output logged publicly"),
    q("CI Validation for Bicep Pull Requests", "IaC", "Common",
      "What Bicep validation runs on every pull request before merge?",
      "`bicep build`, `bicep lint`, what-if against staging RG, Checkov/static analysis, and optional PSRule for Azure best practices.",
      "**CI pipeline:**\n1. `az bicep build --file main.bicep` — compile check\n2. `bicep lint` — linter rules\n3. Checkov scan — security misconfigurations\n4. What-if — predicted changes\n5. Cost estimate — `az cost management` preview if available\n\n**Merge gate:** All pass + platform team review for networking changes.\n\n**Architect:** IaC PR checks as rigorous as application PR checks.",
      "CI validation catches NSG open to world before apply.",
      "Module registry publish? — Separate pipeline on tag — consumers pin version.",
      "Breaking module change? — Semver major bump in registry.",
      "Validate only on prod apply",
      "No lint rules enabled",
      "Skip what-if for time savings"),
    q("Terraform Workspaces vs Separate State", "Terraform", "Common",
      "When use Terraform workspaces vs separate state files per environment?",
      "Separate state files per environment for production isolation. Workspaces for ephemeral dev sandboxes only — workspace switching error risks prod apply.",
      "**Separate state (recommended prod):**\n```\nbackend key = \"prod/order.tfstate\"\nbackend key = \"staging/order.tfstate\"\n```\n\n**Workspaces:** Same backend, different workspace name — lighter but `-workspace=prod` typo danger.\n\n**Architect:** Prod state isolation is non-negotiable — separate backend key or storage container.",
      "Workspace vs state is common Terraform interview trap.",
      "Terragrunt? — Wrapper for DRY backend config per env.",
      "Ephemeral env? — Workspace or separate state destroyed on PR close.",
      "Prod and dev share workspace",
      "Workspace select in script without confirmation",
      "No concurrency lock per state"),
    q("Import Existing Azure Resources", "IaC", "Common",
      "Import manually created Azure resources into Bicep or Terraform management.",
      "Inventory resource → author matching template → `terraform import` or Bicep `existing` + incremental adoption → verify plan shows zero changes → enable Policy.",
      "**Terraform:**\n```bash\nterraform import azurerm_resource_group.rg /subscriptions/.../resourceGroups/rg-order\n```\n\n**Bicep:** `resource kv 'Microsoft.KeyVault/vaults@...' existing = { name: 'kv-prod' }` then expand to full definition.\n\n**Phasing:** Import prod SQL first (highest drift risk), dev storage later.\n\n**Architect:** `az bicep decompile` is starting point — never production-ready without review.",
      "Brownfield import is reality — architects phase by blast radius.",
      "Delete and recreate? — Data loss — avoid for stateful resources.",
      "Import entire subscription day one? — Phased by resource group.",
      "Decompile output deployed unreviewed",
      "Import without drift prevention Policy",
      "Managing same VM in portal and IaC"),
    q("Azure Resource Naming Conventions", "IaC", "Common",
      "Define a resource naming convention for a multi-team Azure .NET platform.",
      "`{type}-{workload}-{env}-{region}-{instance}` — e.g., `app-order-prod-eus-01`, `kv-shared-prod-eus`, `sql-order-stg-eus`. Enforce via Policy and Bicep parameters.",
      "**Components:**\n- **Type prefix:** `app`, `func`, `sql`, `st`, `kv`, `rg`\n- **Workload:** `order`, `payment`, `shared`\n- **Env:** `dev`, `stg`, `prod`\n- **Region:** `eus`, `weu`\n\n**Limits:** Storage account 3–24 lowercase alphanumeric — abbreviate.\n\n**Architect:** Naming in platform module — teams pass `workloadName` only; convention applied automatically.",
      "Naming enables automation, cost allocation, and on-call clarity.",
      "Global uniqueness? — Storage and Key Vault names global — include random suffix if needed.",
      "Rename resource? — Often recreate — get naming right at provision.",
      "Random portal-generated names",
      "Different convention per team",
      "No naming in IaC modules — manual each time"),
    q("Tagging Strategy Enforcement", "FinOps", "Common",
      "Enforce mandatory tags through IaC and Azure Policy for cost allocation.",
      "Mandatory tags: `Environment`, `CostCenter`, `Owner`, `Application`, `ManagedBy`. Policy `deny` if missing. Bicep module applies tags to all child resources.",
      "**Policy:**\n```json\n\"deny\" if tags.CostCenter is empty on resource creation\n```\n\n**IaC:**\n```bicep\nvar tags = {\n  Environment: environment\n  CostCenter: costCenter\n  Owner: ownerEmail\n}\n```\n\n**Limit:** 5–7 mandatory tags — more causes tag sprawl and deploy friction.\n\n**Architect:** Tags at provision time — retrofitting 500 resources is painful.",
      "Tagging connects IaC to FinOps showback/chargeback.",
      "Inherited tags? — Resource group tags propagate — set at RG in module.",
      "Tag audit? — Monthly report untagged resources — Policy audit mode first.",
      "15 mandatory tags blocking dev velocity",
      "Tags optional in modules",
      "Audit-only Policy never upgraded to deny"),
    q("Landing Zone Bicep Modules", "IaC", "Common",
      "What belongs in Azure landing zone Bicep modules for .NET workloads?",
      "Hub-spoke networking, Log Analytics workspace, Key Vault, ACR, App Service Plan baseline, diagnostic settings, Private DNS — product teams deploy app modules into spoke.",
      "**Module layers:**\n1. **Platform landing zone** — subscription vending, policy, networking\n2. **Workload landing zone** — RG, App Insights, app plan\n3. **Application module** — App Service, SQL, Redis per service\n\n**CAF alignment:** Microsoft Cloud Adoption Framework reference implementations.\n\n**Architect:** Product team cannot create VNet — platform provides spoke subscription.",
      "Landing zones scale governance — architects define platform vs product boundary.",
      "Terraform ALZ? — Azure Landing Zones — enterprise-scale alternative to custom Bicep.",
      "Subscription vending? — Pipeline creates spoke per team from template.",
      "Every team creates own VNet and firewall",
      "Landing zone monolith never updated",
      "No separation platform vs application modules"),
    q("Ephemeral Environments with IaC", "IaC", "Common",
      "Provision ephemeral PR preview environments with Bicep and tear down on merge.",
      "PR opened → pipeline deploys `rg-order-pr-1234` with App Service + SQL basic tier → comment preview URL → PR closed/merged → `az group delete`.",
      "**Cost controls:**\n- Auto-delete after 24h TTL tag\n- Budget alert per PR RG\n- Shared SQL server with per-PR database optional\n\n**IaC:** Same modules as staging; `pr.bicepparam` with minimal SKUs.\n\n**Architect:** Ephemeral envs need DNS wildcard `pr-1234.dev.contoso.com` and Key Vault access for test secrets.",
      "Ephemeral environments accelerate integration feedback — IDP feature.",
      "Data seeding? — Flyway/EF migrate on deploy — synthetic data only.",
      "Shared vs isolated ephemeral? — Isolated RG safer; shared cheaper.",
      "PR environments never destroyed — cost spiral",
      "Ephemeral prod SKU sizing",
      "No TTL or budget alert on preview RGs"),
    q("GitOps Argo CD vs Pipeline Deploy", "GitOps", "Common",
      "Compare Argo CD GitOps and push-based pipeline deploy for AKS vs App Service.",
      "AKS with 10+ services → Argo CD reconciles cluster to Git desired state. App Service + Bicep → push pipeline apply is simpler and equivalent desired-state pattern.",
      "**GitOps (pull):**\n- Cluster pulls manifests from Git\n- Drift auto-corrected\n- Rollback = git revert\n\n**Push pipeline:**\n- CI calls `az deployment` or `kubectl apply`\n- Simpler for PaaS\n- Drift requires what-if detection\n\n**Architect:** Match model to compute — don't mandate Argo for 3 App Service APIs.",
      "GitOps is not universal — platform-dependent architecture choice.",
      "Flux vs Argo? — Both valid GitOps — organizational preference.",
      "App Service GitOps? — Bicep in Git + pipeline is functional GitOps.",
      "kubectl apply from developer laptop to prod",
      "Argo CD without understanding reconciliation loop",
      "GitOps mandated for simple PaaS workload"),
    q("IaC Security Testing with Checkov", "IaC", "Common",
      "Integrate Checkov into IaC CI to catch misconfigurations before apply.",
      "Run `checkov -d .` on Bicep/Terraform/ARM in PR pipeline. Gate on CRITICAL; suppress false positives with documented skip comments.",
      "**Common catches:**\n- Storage account public access enabled\n- NSG allows 0.0.0.0/0 on 3389\n- Key Vault soft delete disabled\n- SQL no TLS enforcement\n\n**Integration:**\n```yaml\n- run: pip install checkov && checkov -d infra/ --framework bicep\n```\n\n**Architect:** Checkov complements what-if — security rules what-if may not evaluate.",
      "Static IaC analysis is shift-left for infrastructure security.",
      "tfsec vs Checkov? — Overlapping — pick one org standard.",
      "Suppressions? — `# checkov:skip=CKV_AZURE_33 reason=...` with ticket reference.",
      "Checkov only run manually",
      "All findings ignored",
      "No IaC scan in CI pipeline"),
    q("Blast Radius via Resource Groups", "IaC", "Common",
      "How do resource group boundaries limit IaC blast radius?",
      "Scope deployments per RG: `rg-order-prod` contains only order service resources. Failed apply or bad delete affects one workload — not entire subscription.",
      "**Patterns:**\n- One RG per microservice per environment\n- Network hub in separate RG — peering not co-deployed with app\n- State file scoped to RG deployment\n\n**Deletion:** `az group delete` on wrong RG is recoverable if soft-delete enabled — still dangerous.\n\n**Architect:** RG design in landing zone ADR — teams cannot deploy to shared networking RG.",
      "Blast radius containment is IaC architecture fundamentals.",
      "Subscription per env? — Further isolation for regulated — higher overhead.",
      "Locks? — CanNotDelete lock on prod RG — prevent accidental group delete.",
      "Entire subscription in one template apply",
      "Shared RG for 12 microservices",
      "No delete locks on production resource groups"),
    q("IaC Code Review Standards", "Governance", "Common",
      "What should platform team enforce in IaC pull request review checklist?",
      "What-if reviewed, no secrets plain text, tags present, naming convention, Checkov clean, module version pinned, destructive changes called out, rollback plan for prod.",
      "**Review checklist:**\n- [ ] What-if output attached\n- [ ] No `0.0.0.0/0` without justification\n- [ ] SKUs match environment bicepparam\n- [ ] Diagnostic settings enabled\n- [ ] Key Vault references not inline secrets\n- [ ] Cost impact noted for SKU changes\n\n**Ownership:** Platform reviews networking; product team reviews app resources.\n\n**Architect:** IaC review is security review — not rubber stamp.",
      "IaC review standards prevent prod outages from typo in NSG rule.",
      "Auto-approve bot? — Only for plan-only PRs with zero diff after apply.",
      "CODEOWNERS? — `infra/` requires platform team approval.",
      "IaC PR merged without what-if",
      "Junior dev solo approves prod networking change",
      "No checklist — ad hoc review"),
]

WEEK_32_Q011_Q030 = [
    q("Three Pillars Working Together", "Observability", "Very Common",
      "During a checkout slowdown incident, how do metrics, logs, and traces work together?",
      "Metric alert on p99 latency → distributed trace identifies slow Payment API span → logs on correlation ID show `PaymentTimeoutException`. Each pillar answers different question.",
      "**Workflow:**\n1. **Metrics** — `checkout_latency_p99` breaches SLO → page on-call\n2. **Traces** — filter traces > 3s, waterfall shows `payment-api` span 4.8s\n3. **Logs** — query `correlationId == abc` → stack trace and request payload metadata\n\n**Correlation:** W3C `traceparent` propagated to logs via `Activity.Current.TraceId`.\n\n**Architect:** Mandate all three pillars in service scaffold — not optional App Insights checkbox.",
      "Pillar integration is incident response pattern — not three disconnected tools.",
      "Fourth pillar profiling? — Continuous profiler for CPU — complements during perf incidents.",
      "Single pane? — Azure Monitor links trace to logs — configure workspace integration.",
      "Logs only shop — grep across 20 services during outage",
      "Metrics without traces — cannot localize bottleneck",
      "No correlation ID between logs and traces"),
    q("OpenTelemetry Collector Architecture", "OpenTelemetry", "Very Common",
      "Design OpenTelemetry Collector deployment for .NET microservices on Azure.",
      "Deploy collector as sidecar or centralized DaemonSet/Container App. Receivers (OTLP) → processors (batch, filter, tail sampling) → exporters (Azure Monitor, Prometheus).",
      "**Pipeline:**\n```\n.NET App → OTLP gRPC → Collector → processors → Azure Monitor exporter\n```\n\n**Processors:**\n- `batch` — reduce export chatter\n- `attributes` — add `environment`, `region`\n- `tail_sampling` — keep errors 100%, sample success 10%\n\n**Architect:** Collector centralizes sampling and PII filtering — apps stay vendor-neutral.",
      "Collector is observability control plane — architects own deployment topology.",
      "Agent vs collector? — Legacy App Insights agent vs OTel SDK + collector — migrate to OTel.",
      "HA collector? — Multiple replicas behind load balancer for OTLP ingress.",
      "Each service exports directly with different sampling rates",
      "No tail sampling — cost explosion",
      "PII filtered per service inconsistently"),
    q("Distributed Tracing Correlation", "Tracing", "Very Common",
      "How do you propagate trace context across HTTP, Service Bus, and background jobs in .NET?",
      "W3C Trace Context (`traceparent`, `tracestate`) on HTTP headers; inject into Service Bus message application properties; restore context in `IHostedService` from message.",
      "**HTTP:** `Activity` auto-instrumented on `HttpClient`.\n\n**Service Bus:**\n```csharp\nmessage.ApplicationProperties[\"traceparent\"] = Activity.Current?.Id;\n```\nConsumer links child span to parent.\n\n**Background job:** Start span from enqueued trace context — don't orphan jobs.\n\n**Architect:** Broken propagation = broken waterfall — test in integration tests.",
      "Trace propagation is cross-cutting architecture requirement for microservices.",
      "Baggage vs trace context? — Baggage propagates business metadata — use sparingly.",
      "Legacy SOAP? — Custom correlation header mapping to Activity.",
      "New trace per Service Bus message",
      "HttpClient without instrumentation",
      "Background job spans disconnected from HTTP request"),
    q("SLI Definition Examples", "SRE", "Very Common",
      "Define three SLIs for a .NET order API with measurement points.",
      "**Availability SLI:** `(successful requests / total requests)` measured at App Gateway — excludes 4xx client errors.\n\n**Latency SLI:** `% requests < 300ms` at load balancer.\n\n**Freshness SLI (async):** `% order confirmations within 60s of payment` — for queue-backed flow.",
      "**Good SLI properties:**\n- User-centric (not CPU)\n- Measurable at boundary user experiences\n- Stable definition over time\n\n**Bad SLI:** CPU < 80% — not user-facing.\n\n**Architect:** Document SLI definitions in SLO doc before building dashboards — prevents metric debates during incidents.",
      "Concrete SLI examples prove SRE literacy beyond acronym definitions.",
      "Numerator/denominator? — Define explicitly — include or exclude 4xx.",
      "Synthetic SLI? — Availability from probes complements server-side.",
      "CPU utilization as primary SLI",
      "SLI measured inside service ignoring gateway timeouts",
      "Changing SLI definition monthly"),
    q("SLO Error Budget Policy Document", "SRE", "Very Common",
      "What belongs in a written SLO error budget policy for engineering teams?",
      "SLO targets, measurement window, budget calculation, actions at 50%/20%/0% remaining, escalation path, exception process for planned maintenance.",
      "**Policy template:**\n1. **SLO:** 99.9% availability monthly\n2. **Budget:** 43.2 min downtime/month\n3. **50% remaining:** normal development\n4. **20% remaining:** reliability work prioritized in sprint\n5. **0%:** feature freeze, exec notified\n6. **Exclusions:** planned maintenance with comms (counts against budget transparently)\n\n**Architect:** Policy signed by eng director and product — not SRE dictat.",
      "Written policy makes error budgets enforceable — not theoretical.",
      "Multi-window burn? — Fast burn pages, slow burn tickets — add to policy.",
      "SLO review cadence? — Quarterly — adjust targets based on user needs.",
      "SLO in wiki never referenced",
      "No action defined when budget exhausted",
      "100% availability target"),
    q("Alerting on User Symptoms", "Alerting", "Very Common",
      "Why alert on symptoms (SLO burn, 5xx rate) instead of causes (CPU, disk)?",
      "Cause-based alerts fire before user impact (noisy) or after (late). Symptom alerts page when users suffer — CPU 90% may be fine if latency healthy.",
      "**Symptom alerts:**\n- SLO multi-window burn rate\n- `5xx / total` > 1% for 5 min\n- Synthetic checkout failure 2+ regions\n\n**Cause alerts (ticket not page):**\n- Disk 80% — scale before symptom\n- Certificate expires in 30 days\n\n**Architect:** Every page alert links to runbook answering 'what user impact?'",
      "Symptom-based alerting is SRE best practice — reduces false pages.",
      "Saturation alerting? — USE method — page when saturation affects latency.",
      "Composite alerts? — `(5xx elevated) AND (latency elevated)` reduce noise.",
      "CPU > 80% pages on-call at 3am",
      "Alert on single failed health check",
      "No distinction page vs ticket"),
    q("Alert Fatigue Reduction Program", "Alerting", "Common",
      "Run a quarterly program to reduce alert fatigue — what steps?",
      "Export all alerts fired last 90 days; classify: actionable, noisy, redundant; delete or downgrade; require runbook for every remaining page alert.",
      "**Steps:**\n1. **Inventory** — alert name, fire count, MTTA, was it actionable?\n2. **Top 10 noisy** — fix or delete\n3. **Deduplicate** — 15 alerts for same symptom → 1 SLO burn alert\n4. **Runbook audit** — no runbook = downgrade to ticket\n5. **Review meeting** — on-call rotation feedback\n\n**Target:** < 2 pages per on-call shift per week for healthy system.",
      "Alert hygiene is ongoing architecture responsibility — not one-time setup.",
      "Alert grouping? — Azure Monitor alert grouping reduces notification storm.",
      "Flapping? — Require 3 consecutive breaches before page.",
      "50 alerts fire per incident — no grouping",
      "Alerts never reviewed after creation",
      "On-call burnout ignored"),
    q("Structured Logging with Serilog", "Logging", "Common",
      "Configure Serilog for structured logging in ASP.NET Core 8 with Log Analytics.",
      "Serilog with `WriteTo.Console(new CompactJsonFormatter())` and Azure Analytics sink. Enrich with `CorrelationId`, `Environment`, `ServiceVersion`.",
      "**Setup:**\n```csharp\nLog.Logger = new LoggerConfiguration()\n  .Enrich.FromLogContext()\n  .Enrich.WithProperty(\"Service\", \"order-api\")\n  .WriteTo.ApplicationInsights(telemetryConfig, TelemetryConverter.Traces)\n  .CreateLogger();\n```\n\n**Query:** `traces | where customDimensions.OrderId == '12345'`\n\n**Never:** `Log.Information($\"Order {id} placed\")` — use `Log.Information(\"Order placed {OrderId}\", id)`.",
      "Serilog structured patterns are .NET observability baseline.",
      "Serilog vs built-in? — Serilog richer sinks; built-in ILogger sufficient with App Insights exporter.",
      "Log scopes? — `using (_logger.BeginScope(...))` for request context.",
      "String interpolation in log messages",
      "PII in structured fields",
      "Debug level enabled in production"),
    q("Log Aggregation with Log Analytics", "Logging", "Common",
      "Design log aggregation architecture for 15 .NET microservices in Azure Monitor.",
      "All services export to single Log Analytics workspace per environment. Standard schema: `serviceName`, `correlationId`, `traceId`, `severity`. Retention 90 days hot; archive to Storage.",
      "**Workspace strategy:**\n- `law-contoso-prod` — all prod services\n- Resource-specific tables or unified `AppTraces`/`AppRequests`\n\n**Cross-service query:**\n```kusto\ntraces\n| where correlationId == \"abc-123\"\n| order by timestamp asc\n```\n\n**Architect:** Workspace per env not per service — enables correlation; RBAC via table filters if needed.",
      "Centralized log aggregation enables cross-service incident queries.",
      "Multiple workspaces per service? — Fragments correlation — avoid unless regulatory isolation.",
      "Ingestion cost? — Sampling and log level discipline.",
      "15 separate workspaces — cannot correlate",
      "Unstructured logs in workspace",
      "No retention policy — unbounded cost"),
    q("Metrics Cardinality Explosion", "Metrics", "Common",
      "What causes metrics cardinality explosion and how do you prevent it?",
      "High-cardinality labels (userId, orderId) on Prometheus/custom metrics explode time series count — ingestion cost and query slowdown. Use bounded labels only.",
      "**Safe labels:** `service`, `environment`, `region`, `http_route` (templated `/orders/{id}`).\n\n**Dangerous:** `customerId`, `sessionId`, `url` full path.\n\n**Prevention:**\n- Code review metric registration\n- OTel collector drops high-cardinality attributes\n- Use logs/traces for high-cardinality debugging\n\n**Architect:** Platform lint rule banning `userId` in custom metrics.",
      "Cardinality is observability FinOps — architects set labeling standards.",
      "Histogram cardinality? — Buckets multiply series — limit custom histograms.",
      "Azure Monitor custom metrics? — Same rules — dimensions are cardinality.",
      "userId as metric dimension",
      "Unbounded HTTP path label",
      "No review of custom metric registration"),
    q("RED Method for Microservices", "Monitoring", "Common",
      "Apply the RED method to design dashboards for a .NET payment API.",
      "**Rate** — requests/sec by endpoint. **Errors** — 5xx rate, payment decline rate. **Duration** — p50/p95/p99 latency histogram.",
      "**Dashboard panels:**\n1. `sum(rate(http_requests_total[5m]))` by service\n2. `sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(...))`\n3. `histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))`\n\n**Per dependency:** RED on outbound HttpClient calls to Stripe.\n\n**Architect:** RED dashboard per service in golden path — auto-created from OTel export.",
      "RED is request-driven service monitoring standard — know the three letters.",
      "RED vs golden signals? — Golden adds saturation — use USE for resources alongside RED.",
      "gRPC RED? — Rate, gRPC status codes, duration from OTel grpc instrumentation.",
      "CPU dashboard only for API service",
      "No error rate panel",
      "Duration as average only hiding p99 outliers"),
    q("USE Method for Infrastructure", "Monitoring", "Common",
      "Apply USE method to monitor Azure SQL and Redis backing a .NET API.",
      "**Utilization** — SQL DTU %, Redis memory %. **Saturation** — SQL connection pool waits, Redis evicted keys. **Errors** — SQL deadlocks, Redis connection timeouts.",
      "**SQL USE:**\n- Utilization: DTU percentage\n- Saturation: `connection_pool_pending` metric\n- Errors: deadlock count, failed connections\n\n**Redis USE:**\n- Utilization: `used_memory / maxmemory`\n- Saturation: evicted_keys rate\n- Errors: rejected_connections\n\n**Alert:** Saturation before utilization hits 100% — pool exhaustion at 70% DTU.",
      "USE complements RED — resources vs requests.",
      "App Service Plan USE? — CPU utilization, HTTP queue length (saturation), 5xx (errors).",
      "Service Bus? — USE on active messages (saturation), dead letter count (errors).",
      "Only SQL CPU alert",
      "Ignore connection pool saturation",
      "Redis memory 100% before alert"),
    q("Observability Dashboard Design", "Monitoring", "Common",
      "Design an executive and engineering dashboard hierarchy for e-commerce platform.",
      "L1 executive: revenue-impacting SLOs, error budget remaining. L2 on-call: RED per service, dependency health. L3 deep-dive: USE per resource, trace explorer link.",
      "**Hierarchy:**\n- **Executive (1 screen):** Checkout SLO, orders/min, budget burn\n- **Service owner:** Order API RED, recent deploys, top errors\n- **Incident:** Trace search, log query templates, runbook links\n\n**Principles:** < 10 panels per dashboard; consistent color thresholds; annotation for deploys.",
      "Dashboard hierarchy serves different audiences — architects design both.",
      "Deploy annotations? — Vertical line on dashboard at deploy time — correlates regressions.",
      "Dashboard sprawl? — Catalog in Backstage — discoverable golden dashboards.",
      "Single 40-panel dashboard",
      "No SLO on executive view",
      "Different threshold colors per team"),
    q("On-Call Runbooks Linked to Alerts", "Operations", "Common",
      "What makes an effective on-call runbook linked from Azure Monitor alerts?",
      "Runbook: symptom description, impact, diagnostic steps (KQL queries), remediation commands, escalation criteria, rollback procedure — tested quarterly.",
      "**Template sections:**\n1. **Alert meaning** — what user impact\n2. **Quick checks** — 3 KQL queries copy-paste ready\n3. **Fix steps** — slot swap command, scale SQL tier\n4. **Escalate if** — unresolved 15 min → page SRE lead\n5. **Post-incident** — postmortem link\n\n**Storage:** ADO Wiki or Backstage — URL in alert description field.",
      "Runbooks reduce MTTR — DORA metric — architects provide templates.",
      "Executable runbooks? — Azure Automation hybrid runbook linked from alert.",
      "Runbook drill? — Quarterly game day executes runbook blindly.",
      "Alert with no runbook link",
      "Runbook outdated after architecture change",
      "Runbook only says 'call expert'"),
    q("Synthetic Monitoring Design", "Monitoring", "Common",
      "Design synthetic availability tests for multi-region .NET e-commerce.",
      "Availability tests from 3+ regions every 60s on critical paths: login, search, add-to-cart, checkout. Alert when 2+ locations fail consecutive 3 runs.",
      "**Configuration:**\n- Application Insights web tests or Playwright synthetic\n- `/health` insufficient — test real user journey\n- Validate SSL cert expiry in test\n\n**Post-deploy:** Synthetic runs as smoke gate — failure blocks promotion.\n\n**Architect:** Synthetic measures user-visible availability — complements server-side metrics.",
      "Synthetic catches regional DNS and CDN failures server metrics miss.",
      "Private endpoints? — Synthetic from inside VNet or use Azure Functions ping.",
      "Maintenance window? — Suppress alerts with scheduled downtime.",
      "Single-region synthetic only",
      "Health endpoint returns 200 without DB check",
      "No synthetic on checkout path"),
    q("Real User Monitoring RUM", "Monitoring", "Common",
      "How does RUM complement synthetic monitoring for a Blazor/React frontend?",
      "RUM captures actual user browser performance: Core Web Vitals (LCP, INP, CLS), JS errors, API latency from client perspective. Synthetic cannot replicate all devices and networks.",
      "**Implementation:**\n- Application Insights JavaScript SDK or OTel browser\n- Track page views, AJAX failures, client-side exceptions\n- Segment by geography, browser, device\n\n**Use cases:**\n- Synthetic green but RUM shows India users 8s LCP → CDN issue\n- JS error spike after deploy → bad frontend bundle\n\n**Architect:** SLO on client-side latency for critical flows — not just server p99.",
      "RUM is user-ground-truth — server metrics lie about client experience.",
      "PII in RUM? — Hash user IDs; GDPR consent for tracking.",
      "Blazor WASM? — Client-side error tracking essential — exceptions silent to server.",
      "Server-only monitoring for SPA",
      "No Core Web Vitals tracking",
      "RUM sample rate 0% to save cost"),
    q("PowerShell Azure Observability Automation", "Automation", "Occasional",
      "Automate observability hygiene with PowerShell for Azure estate.",
      "Scripts: enable diagnostic settings on all App Services, audit missing App Insights connection, export cost by resource group, report certificates expiring < 30 days.",
      "**Example:**\n```powershell\nGet-AzWebApp | ForEach-Object {\n  if (-not $_.SiteConfig.AppSettings['APPLICATIONINSIGHTS_CONNECTION_STRING']) {\n    Write-Warning \"Missing App Insights: $($_.Name)\"\n  }\n}\n```\n\n**Schedule:** Azure Automation runbook weekly; output to Log Analytics custom table.\n\n**Architect:** Compliance automation — no App Insights = no deploy approval.",
      "PowerShell automation scales observability governance across subscriptions.",
      "Az CLI vs PowerShell? — PowerShell for Windows-centric ops reporting; CLI on Linux agents.",
      "What not to automate? — Alert threshold tuning — requires human judgment initially.",
      "Manual portal audit of 200 App Services",
      "Non-idempotent diagnostic enable script",
      "No scheduled execution"),
    q("Hybrid Runbook Automation", "Automation", "Common",
      "Design hybrid runbook automation for incident response across Azure and on-prem.",
      "Azure Automation Hybrid Runbook Worker on-prem executes AD DNS flush, load balancer drain, while Azure runbooks scale App Service and swap slots — orchestrated from single alert.",
      "**Architecture:**\n- Alert fires → Logic App or Automation webhook\n- Parallel jobs: cloud scale-out + on-prem connection pool reset\n- Results logged to Log Analytics custom log\n- Failure path escalates to on-call\n\n**Security:** Hybrid worker uses Managed Identity; least privilege on-prem service account.",
      "Hybrid automation reflects real enterprise — not 100% cloud.",
      "Runbook vs GitHub Action? — Runbook for incident response; Action for deploy pipeline.",
      "Testing? — Monthly dry-run in staging hybrid worker.",
      "Manual on-prem steps during every Sev1",
      "Hybrid worker with domain admin — overprivileged",
      "Automation with no failure notification"),
    q("Observability Cost Control Tactics", "FinOps", "Common",
      "Application Insights bill grew 60% after OTel rollout. Optimization plan?",
      "Implement tail-based sampling at collector (100% errors, 10% success), drop health check traces, reduce verbose logging, set daily cap alert, review custom metric cardinality.",
      "**Tactics ranked:**\n1. Tail sampling at OTel collector\n2. Log level Information in prod (not Debug)\n3. Filter `/health` traces before export\n4. Drop duplicate IIS logs if App Insights captures requests\n5. 30-day retention hot; archive older to Storage\n\n**Governance:** Platform sets default sampling in scaffold — teams opt-in to higher sampling with cost approval.",
      "Observability FinOps is architect responsibility as telemetry grows.",
      "Daily cap? — Safety net only — not primary cost control.",
      "Sampling too aggressive? — Cannot debug — keep 100% error traces.",
      "100% trace sampling at 10K RPS",
      "Disable observability to cut costs",
      "No cost alert on Log Analytics workspace"),
    q("Production Debugging Workflow", "Operations", "Very Common",
      "Describe your systematic production debugging workflow for intermittent 5xx errors.",
      "1) Check SLO dashboard and recent deploys. 2) Query 5xx rate by endpoint. 3) Find exemplar trace. 4) Correlate logs on traceId. 5) Reproduce in staging with feature flag. 6) Fix with test, canary deploy.",
      "**KQL starting point:**\n```kusto\nrequests\n| where timestamp > ago(1h) and resultCode startswith \"5\"\n| summarize count() by operation_Name, resultCode\n| order by count_ desc\n```\n\nThen: `join` to `exceptions` on `operation_Id`.\n\n**Avoid:** Random log grep without hypothesis. **Do:** Time-box investigation; escalate if > 30 min without theory.",
      "Structured debugging workflow demonstrates senior operational maturity.",
      "Live debugging prod? — Last resort — use snapshot debugger or dump analysis.",
      "Chaos reproduction? — Replay production trace payload in staging.",
      "Restart service without investigation",
      "Debug logging enabled in prod as first step",
      "No deploy correlation when errors started"),
]

ALL_WEEKS_29_32_Q011_Q030 = {
    29: WEEK_29_Q011_Q030,
    30: WEEK_30_Q011_Q030,
    31: WEEK_31_Q011_Q030,
    32: WEEK_32_Q011_Q030,
}
