"""Hand-crafted premium Q011–Q030 for Weeks 23–24 — DDD and Microservices Capstone."""

from premium_qa_data import q

WEEK_23_Q011_Q030 = [
    q("Value Objects Design", "DDD", "Very Common",
      "Design value objects for Money and Address in an order domain. What rules apply?",
      "Value objects are immutable, compared by value, no identity. Money: amount + currency; operations return new instances. Address: street, city, postal — validate on construction.",
      "**Money:** Never use `decimal` alone — `new Money(10.50m, Currency.USD)`. Addition only when currencies match; otherwise convert via domain service.\n\n**Address:** `ShippingAddress.Create(...)` validates postal format; equality via all fields.\n\n**Architect:** Value objects encapsulate validation — invalid states unrepresentable. EF Core: owned types or complex type mapping.",
      "Value objects are where domain invariants hide — interviewers probe immutability and equality.",
      "Record types in C# for value objects? — Good fit if no inheritance — still validate in constructor.",
      "When value object vs entity? — Entity has lifecycle and ID; value object replaces wholesale.",
      "Mutable value object with setters",
      "Money as bare decimal without currency",
      "Reference equality on value objects"),
    q("Entities vs Value Objects", "DDD", "Very Common",
      "Order is an entity; OrderLine quantity — entity or value object? How decide?",
      "Entity: identity persists through attribute changes (OrderId). Value object: defined entirely by attributes; replace don't mutate (Quantity as int primitive OK; Money as VO).",
      "**Decision tree:**\n1. Need to track *same thing* over time with changing state? → Entity\n2. Concept defined only by current values? → Value object\n3. Child within aggregate with no external reference? → Often value object or entity inside aggregate only\n\nOrderLine may be entity *inside* Order aggregate (line ID for updates) but external world references Order only.",
      "Entity vs VO classification drives aggregate design.",
      "OrderLineId inside aggregate? — Entity within aggregate — still no direct external reference.",
      "Primitive obsession? — Wrap primitives in VOs when rules exist (Email, SKU).",
      "Every table row is entity",
      "Value object with database-generated ID",
      "External service holds reference to OrderLine entity"),
    q("Aggregate Invariants", "DDD", "Very Common",
      "Enforce 'order cannot ship until paid' inside the Order aggregate.",
      "Invariant enforced in domain methods — `order.MarkShipped()` checks `Status == Paid` and throws domain exception if violated. No setter bypass.",
      "**Pattern:**\n```csharp\npublic void MarkShipped() {\n  if (Status != OrderStatus.Paid)\n    throw new DomainException(\"Cannot ship unpaid order\");\n  Status = OrderStatus.Shipped;\n  RaiseDomainEvent(new OrderShipped(Id));\n}\n```\n\n**Architect:** Invariants live in aggregate root methods — not application service `if` chains. Unit test every illegal transition.",
      "Aggregate invariants are consistency guarantees — core DDD interview topic.",
      "Invariant vs validation? — Invariant always true in aggregate; validation at boundary may reject input.",
      "Cross-aggregate invariant? — Eventual consistency — saga or process manager.",
      "Public Status setter bypasses rules",
      "Invariant enforced only in API controller",
      "Database CHECK constraint as only guard"),
    q("Domain Services When", "DDD", "Common",
      "When use a domain service instead of entity method?",
      "Domain service when operation doesn't naturally belong to one entity — e.g. `TransferFunds(from, to, amount)` spanning two accounts, or pricing requiring external rate table owned by domain.",
      "**Use entity method when:** operation concerns single aggregate root.\n\n**Use domain service when:**\n- Multi-aggregate coordination (prefer events/saga if cross-transaction)\n- Stateless domain calculation (ShippingCostCalculator)\n- Domain concept not an entity/VO (RoutingPolicy)\n\n**Architect:** Keep domain services stateless; inject via DI in application layer — domain layer defines interface.",
      "Domain services fill gaps — not a dumping ground for god logic.",
      "Application service vs domain service? — Application orchestrates; domain service holds domain logic that isn't on one entity.",
      "Infrastructure in domain service? — Interface in domain; implementation in infrastructure.",
      "OrderService 3000-line god class",
      "Domain service with DbContext dependency",
      "Every operation through domain service bypassing entities"),
    q("Repositories in DDD", "DDD", "Very Common",
      "What belongs in a DDD repository interface? Where does querying live?",
      "Repository: load/save aggregate by ID — `GetById`, `Add`, `Remove`. Collection-like per aggregate root. Complex queries → specification or read model — not repository returning DTO lists.",
      "**Interface in domain layer:** `IOrderRepository : IRepository<Order, OrderId>`.\n\n**Implementation:** EF Core in infrastructure — maps persistence to aggregate reconstitution.\n\n**Architect:** One repository per aggregate root. `GetOrdersByCustomerForDashboard` belongs in read side (CQRS) or query service — not bloated repository.",
      "Repository abstraction protects domain from ORM leakage.",
      "Unit of Work pattern? — Single transaction boundary — EF DbContext is UoW.",
      "Generic repository anti-pattern? — `IRepository<T>` for all entities loses aggregate focus.",
      "Repository returns IQueryable to controllers",
      "27 methods on IOrderRepository",
      "Repository used from domain entities"),
    q("Factory in Domain", "DDD", "Common",
      "When use a factory to create aggregates vs constructor?",
      "Factory when creation is complex — multiple steps, optional components, or must ensure invariants before object exists. Constructor for simple aggregates.",
      "**Examples:** `OrderFactory.CreateFromCart(cart, customerId)` validates cart non-empty, applies promotions, assigns ID, raises `OrderCreated`.\n\n**Domain factory** (not GoF abstract factory): encapsulates creation rules. Static `Create` on aggregate acceptable for simple cases.\n\n**Architect:** Ban `new Order()` scattered in application layer — centralize creation.",
      "Factories hide construction complexity and enforce valid birth state.",
      "Factory vs builder? — Builder for stepwise optional assembly; factory for domain-valid complete aggregate.",
      "DI for factories? — Inject `IOrderFactory` when dependencies needed (clock, ID generator).",
      "new Order() in controller with 15 property assignments",
      "Factory in infrastructure only — domain can't create aggregates",
      "No factory tests for illegal creation paths"),
    q("Specifications Pattern", "DDD", "Common",
      "Use specification pattern for 'orders eligible for expedited shipping'.",
      "Specification encapsulates business rule as composable predicate — `ExpeditedShippingSpec.IsSatisfiedBy(order)`. Combine with AND/OR for complex rules.",
      "**Domain layer:**\n```csharp\npublic class ExpeditedShippingSpec : ISpecification<Order> {\n  public bool IsSatisfiedBy(Order o) =>\n    o.Total > Money.Usd(100) && o.ShippingAddress.IsDomestic;\n}\n```\n\n**Infrastructure:** Translate to SQL via expression visitor for EF — or use in-memory for unit tests.\n\n**Architect:** Replaces scattered LINQ `Where` duplicates — single source of truth for business rule.",
      "Specifications make business rules explicit and testable.",
      "Specification vs CQRS read query? — Spec for domain rule; read query for projection shape.",
      "Composable specs? — `AndSpec`, `OrSpec` — DRY complex eligibility.",
      "Same business rule copy-pasted in 4 queries",
      "Specification with HTTP call inside",
      "No unit tests on specification classes"),
    q("Anti-Corruption Layer Deep", "DDD", "Very Common",
      "Design ACL between legacy mainframe inventory and new order service — layers and testing.",
      "ACL modules: adapter (protocol), translator (DTO→domain command), facade (single entry to legacy). Order domain never sees COBOL copybook fields.",
      "**Layers:**\n1. **Adapter** — calls mainframe MQ/API\n2. **Translator** — `LegacyStockResponse` → `ReservationResult`\n3. **Facade** — `ILegacyInventoryGateway.Reserve(sku, qty)`\n\n**Testing:** Contract tests against mainframe stub; record/replay fixtures. Canary release ACL changes independently.\n\n**Architect:** ACL is strategic pattern — budget maintenance; plan strangler replacement.",
      "Deep ACL design shows integration maturity in DDD interviews.",
      "ACL vs adapter pattern? — ACL adds semantic translation to domain language — not just protocol.",
      "ACL versioning? — Version translators when legacy changes — parallel translators during migration.",
      "Legacy field names in domain events",
      "ACL without integration tests",
      "Direct mainframe DB access bypassing ACL"),
    q("Context Map Patterns", "DDD", "Very Common",
      "Draw context map relationships for Order, Payment, Catalog, and Legacy ERP.",
      "Document: Order downstream of Payment (conformist to PaymentCompleted event); Catalog upstream open host; Legacy ERP upstream — Order uses ACL; Shipping partnership with Order.",
      "**Patterns on map:**\n- **Partnership** — joint evolution (rare)\n- **Customer/Supplier** — negotiated upstream/downstream\n- **Conformist** — downstream accepts upstream model\n- **ACL** — downstream translates legacy\n- **OHS** — upstream published integration API\n- **Shared Kernel** — minimal shared code (dangerous)\n\n**Architect deliverable:** Context map diagram in ADR — updated when relationships change.",
      "Context maps make integration politics explicit.",
      "When conformist vs ACL? — Conformist when upstream model acceptable; ACL when legacy toxic.",
      "Distilled context map? — Subset for one initiative — don't boil ocean.",
      "No context map in microservice split",
      "Every relationship conformist — no ACL where needed",
      "Context map never updated after year one"),
    q("Published Language", "DDD", "Common",
      "Define published language for integration events across bounded contexts.",
      "Published language = stable, documented vocabulary for cross-context messages. `OrderPlacedV1` schema in schema registry — business terms, not internal entity names.",
      "**Rules:**\n- Event names past tense business facts\n- Payload fields match ubiquitous language of *consuming* contexts\n- Version in schema name or header\n- Wiki page: glossary + example JSON\n\n**Architect:** Integration team owns published language — breaking change = major version + consumer notice.",
      "Published language prevents implicit coupling via ad hoc JSON.",
      "Integration event naming convention? — `{Context}{Fact}V{n}` — e.g. `BillingPaymentCapturedV1`.",
      "Schema registry? — Confluent/Azure Schema Registry — enforce compatibility.",
      "Internal entity serialized directly to bus",
      "Renamed field without version bump",
      "No glossary for integration terms"),
    q("Open Host Service", "DDD", "Common",
      "Catalog context exposes product data to Order and Search — design as open host.",
      "Open Host Service: Catalog publishes well-defined API/events (published language) — multiple downstream consumers adapt. Catalog doesn't know each consumer's model.",
      "**Implementation:**\n- REST `GET /products/{id}` + `ProductUpdated` integration event\n- Rate limits, API keys per consumer team\n- SLA documented — 99.9% read availability\n\n**Contrast conformist:** OHS puts burden on host to maintain stable contract — host team is platform for integrators.",
      "OHS is upstream pattern for shared reference data.",
      "OHS vs shared database? — OHS replaces shared DB anti-pattern.",
      "GraphQL as OHS? — Federation supergraph can be OHS — governance critical.",
      "Catalog team custom endpoint per consumer",
      "Breaking API change without notice",
      "No SLA on integration API"),
    q("Customer Supplier Relationship", "DDD", "Common",
      "Order team needs faster changes from Payment team — customer/supplier negotiation.",
      "Downstream (Order) is customer; upstream (Payment) is supplier. Customer requests features/SLAs; supplier prioritizes roadmap. Formalize in context map + integration SLA.",
      "**Negotiation artifacts:**\n- Consumer-driven contract tests (Pact) — customer defines expectations\n- Joint planning for new event types\n- Escalation when supplier breaking change threatens customer\n\n**Architect role:** Facilitate — not let downstream hack upstream DB.",
      "Customer/supplier models real organizational dynamics in DDD.",
      "Supplier driven by downstream? — Rare inversion — supplier usually upstream.",
      "SLA for event delivery latency? — e.g. PaymentCompleted within 5s p99.",
      "Downstream reads upstream database directly",
      "No contract tests between teams",
      "Assuming unlimited supplier capacity"),
    q("Conformist vs ACL", "DDD", "Very Common",
      "Payment service uses Stripe's API model directly in domain — conformist or fix?",
      "Stripe model in domain = conformist (acceptable at boundary if Stripe is industry standard). If Stripe shapes corrupt ubiquitous language, use ACL to translate to `PaymentCapture` domain concept.",
      "**Conformist when:** upstream model is industry standard and stable (ISO codes, Stripe statuses).\n\n**ACL when:** legacy ERP, toxic nomenclature, or frequent upstream changes you must isolate.\n\n**Architect decision:** Document in ADR — cost of ACL maintenance vs conformist coupling.",
      "Conformist vs ACL is strategic trade-off — not moral choice.",
      "Two conformist hops? — Coupling accumulates — consider ACL at outer boundary.",
      "Test conformist boundary? — Contract tests against Stripe sandbox.",
      "ACL everywhere including stable standards",
      "Conformist to legacy ERP in core domain",
      "Undocumented conformist decision"),
    q("Event Storming Facilitation", "DDD", "Common",
      "You facilitate event storming for checkout redesign — agenda and outputs?",
      "Agenda: 90m — domain narrative (15m), big picture events (30m), commands/policies (20m), aggregates (15m), context boundaries (10m). Output: event flow, candidate aggregates, bounded contexts, pink hot spots.",
      "**Facilitation tips:**\n- Domain experts stick orange events — developers don't dominate\n- Timebox — park debates in hot spots\n- Read events chronologically aloud — gaps surface\n- Photo/Miro export → ADR input\n\n**Architect:** Run storming *before* service boundaries locked. Follow-up workshop resolves hot spots within 2 weeks.",
      "Facilitation skill separates architects who discover from those who dictate.",
      "Remote facilitation? — Miro + breakout pairs for commands/aggregates.",
      "Process modeling level? — Second workshop — swimlanes per actor/system.",
      "Developers-only storming",
      "No hot spot follow-up",
      "Storming output never reaches ADRs"),
    q("Process Modeling in Event Storming", "DDD", "Common",
      "After big picture storming, model 'place order' as process — steps?",
      "Process level: swimlanes per actor (Customer, Order, Payment, Inventory). Connect events → commands → policies (when X then Y). Reveals sync vs async needs and sagas.",
      "**Example flow:**\n`SubmitOrder` → `OrderSubmitted` → policy → `ReserveInventory` → `InventoryReserved` → `ChargePayment` → `PaymentFailed` → policy → `ReleaseInventory`.\n\n**Output:** Saga candidate, integration events, timeout policies.\n\n**Architect:** Process model drives orchestration vs choreography decision.",
      "Process modeling bridges discovery and technical design.",
      "Policy (lavender sticky)? — Reactive rule — 'Whenever PaymentFailed, CancelOrder'.",
      "Read model (green)? — UI projection needs from flow.",
      "Skip process level — jump to microservices",
      "All policies implemented sync HTTP",
      "No timeout policy on external steps"),
    q("Policy Pattern in Domain", "DDD", "Occasional",
      "Implement domain policy 'apply free shipping over $100' — where does it live?",
      "Policy as domain object implementing `IShippingPolicy` — `FreeShippingOverThresholdPolicy`. Order aggregate or domain service evaluates policies collection — not hardcoded in application layer.",
      "**Design:**\n```csharp\npublic interface IShippingPolicy {\n  Money AdjustShipping(Order order, Money baseShipping);\n}\n```\n\nPolicies composable — run in defined order. Configuration may load policy set per tenant.\n\n**Architect:** Distinguish domain policy (business rule) from infrastructure policy (Polly retry).",
      "Policy pattern keeps conditional business rules extensible.",
      "Strategy vs policy? — Similar — policy often event-triggered (when X then Y).",
      "Policy in event storming vs code? — Lavender sticky → `IPolicy` implementation.",
      "if (total > 100) in controller",
      "Policy with database call in domain",
      "Non-composable monolithic policy method"),
    q("Domain Events vs Integration Events", "DDD", "Very Common",
      "OrderPlaced raised in aggregate — trace path to Service Bus message.",
      "In aggregate: raise `OrderPlaced` domain event (in-memory). On `SaveChanges`: persist to outbox table same transaction. Outbox worker publishes `OrderPlacedIntegrationEventV1` to bus — translated payload, schema version.",
      "**Layers:**\n1. Domain event — internal, rich domain objects OK in handler (same process)\n2. Outbox — transactional guarantee\n3. Integration event — public contract, primitive/DTO payload\n\n**Architect:** Never publish domain entity JSON to bus. Handlers in application layer map domain → integration.",
      "Event layering is frequent senior interview question.",
      "In-process domain event handlers? — Email, metrics — keep fast; no HTTP.",
      "Eventual outbox failure? — Retry with idempotent publish key.",
      "Domain event published directly to Kafka",
      "Same class for domain and integration event",
      "Integration event includes EF navigation properties"),
    q("Snapshotting Aggregates", "DDD", "Occasional",
      "Event-sourced Order aggregate with 10K events — when and how snapshot?",
      "Snapshot every N events (e.g. 100) or on schedule — store current state blob + version. Load: latest snapshot + events since snapshot version.",
      "**Trade-offs:**\n- Faster load — O(events since snapshot) not O(all)\n- Snapshot storage cost\n- Snapshot invalidation on schema change — migration strategy needed\n\n**Architect:** Snapshot async after commit — don't block write path. Version snapshot schema.",
      "Snapshotting is event sourcing performance tool.",
      "Snapshot per aggregate type? — Order yes; small Cart maybe never.",
      "Delete events after snapshot? — No — events are audit source — archive old.",
      "Load replay 10K events every request",
      "Snapshot without version field",
      "Blocking write on snapshot creation"),
    q("CQRS in Bounded Context", "DDD", "Very Common",
      "Apply CQRS inside Ordering context — write model vs read model design.",
      "Write: Order aggregate, normalized tables, business invariants. Read: `OrderListItem` denormalized projection — customer name, line count, status badge — optimized for UI queries.",
      "**Start logical:** separate command/query handlers, same DB. **Physical split** when read RPS >> write or schemas diverge.\n\n**Projection:** OrderPlaced/OrderShipped events update read store — eventual consistency acceptable for list screen (show stale 2s).\n\n**Architect:** CQRS per bounded context — not global mandate.",
      "CQRS scope is context-local — interviewers check you don't over-apply.",
      "Read your own writes? — Synchronous projection or client polling for detail view.",
      "Separate read DB migration? — Projections versioned — rebuild from events.",
      "Global CQRS day one",
      "Write model returned for complex grid",
      "No projection lag documentation"),
    q("Modular Monolith DDD", "DDD", "Very Common",
      "Structure modular monolith with DDD bounded contexts before microservices.",
      "Solution folders: `Ordering.Domain`, `Ordering.Application`, `Ordering.Infrastructure`, `Billing.Domain`, etc. No project reference from Ordering.Domain → Billing.Domain — integration via events or ACL interface.",
      "**Rules:**\n- Domain projects reference nothing infrastructure\n- Cross-context only via integration events or explicit ACL project\n- Single deploy initially — module boundaries enforced by architecture tests (NetArchTest)\n\n**Architect:** Modular monolith is valid end state for many products — extract services when independent scale/deploy justified.",
      "Modular monolith is disciplined default — not failure to microservice.",
      "Architecture tests? — `DomainShouldNotReferenceInfrastructure` — CI enforced.",
      "Shared database modular monolith? — Schema per context minimum — table cross-join forbidden.",
      "All contexts in one Domain project",
      "Cross-context entity references",
      "Microservices without modular monolith trial"),
]

WEEK_24_Q011_Q030 = [
    q("End-to-End Order Flow Design", "Capstone", "Very Common",
      "Design end-to-end order flow across API gateway, order, payment, inventory, notification services.",
      "Sync: client → gateway → order (create). Async choreography: OrderPlaced → inventory reserve → payment capture → OrderConfirmed → notification. Idempotency keys on every step.",
      "**Flow:**\n1. `POST /orders` — validate, persist Draft, return 202 + orderId\n2. Publish `OrderSubmitted`\n3. Inventory: reserve (compensate: release)\n4. Payment: capture (compensate: refund)\n5. Order: confirm — publish `OrderConfirmed`\n6. Notification: email/SMS (best effort)\n\n**Architect diagram:** Number sync vs async hops. Trace ID from gateway. DLQ per consumer.",
      "E2E flow design is capstone centerpiece — practice 10-minute whiteboard.",
      "Orchestration vs choreography here? — Choreography for demo; orchestration if complex compensation.",
      "Duplicate submit handling? — Idempotency-Key header + unique constraint.",
      "Synchronous payment in create HTTP request",
      "No compensation on inventory failure after payment",
      "Missing correlation ID across hops"),
    q("Payment Integration Saga", "Capstone", "Very Common",
      "Design payment saga step with Stripe — success, timeout, and duplicate callback.",
      "Saga state: PendingPayment → Paid | Failed. Call Stripe with idempotency key = orderId. Webhook `payment_intent.succeeded` is source of truth — API response may race webhook.",
      "**Steps:**\n1. Saga publishes `ChargePaymentCommand`\n2. Payment service creates PaymentIntent (idempotent)\n3. Webhook handler updates saga — idempotent on event ID\n4. Timeout 30s → query Stripe → reconcile state\n\n**Compensation:** `Refund` with idempotency key `refund-{orderId}`.\n\n**Architect:** Never trust client-side payment success alone.",
      "Payment saga is where money is lost or duplicated — depth matters.",
      "Exactly-once payment? — Impossible — idempotent at-least-once achieves effectively-once.",
      "PCI scope? — Tokenize card client-side — payment service never stores PAN.",
      "Double capture on webhook retry",
      "No reconciliation job for stuck PendingPayment",
      "Saga state only in memory"),
    q("Inventory Reservation", "Capstone", "Very Common",
      "Design inventory reservation — optimistic vs pessimistic, oversell prevention.",
      "Pessimistic: `UPDATE stock SET qty = qty - @n WHERE sku = @s AND qty >= @n` — row lock. Optimistic: version column — retry on conflict. Reserve holds stock with TTL; release on payment failure.",
      "**Pattern:**\n- `ReservedQuantity` + `AvailableQuantity` columns OR reservation table\n- TTL job releases expired reservations\n- Event: `InventoryReserved`, `InventoryReleased`, `InventoryDepleted`\n\n**Architect:** Hot SKU may need shard by SKU or queue serialization — document contention plan.",
      "Inventory is classic distributed consistency challenge.",
      "Oversell acceptable? — Business question — flash sale may allow 1% oversell with apology.",
      "Read inventory from catalog cache? — Stale for display OK; never for reservation write.",
      "Check-then-act race without transaction",
      "No reservation TTL",
      "Inventory and catalog share writable table"),
    q("Notification Async Path", "Capstone", "Common",
      "Order confirmed — design async notification path that never blocks checkout.",
      "Subscribe to `OrderConfirmed` — enqueue notification job. Worker sends email via SendGrid, SMS via Twilio. Failures → retry with backoff → DLQ — order already committed.",
      "**Design:**\n- At-least-once delivery — template idempotency key `orderId-channel`\n- Preference service: opt-out, channel choice\n- Dead letter alerts ops — don't rollback order\n\n**Architect:** Notifications are side effect — saga completes without waiting for email.",
      "Async notification path teaches fire-and-forget done right.",
      "Transactional outbox to notification queue? — Yes — don't dual-write bus + DB.",
      "User notification preferences? — Filter before send — GDPR marketing opt-out.",
      "Sync SMTP in order confirm transaction",
      "Notification failure cancels order",
      "No idempotency on email send"),
    q("Observability Across Services", "Capstone", "Very Common",
      "Mandate observability standards for capstone microservices platform.",
      "Every service: OpenTelemetry SDK, W3C `traceparent`, structured JSON logs with traceId, RED metrics (rate, errors, duration), health `/health/live` + `/health/ready`.",
      "**Platform mandate:**\n- Service template ships OTel + Serilog enricher\n- Dashboard: checkout golden trace — p99 per hop\n- Alert: error rate >1% 5m window\n\n**Architect:** Observability is non-negotiable gate for production readiness review.",
      "Cross-service observability separates toy from production architecture.",
      "Service map? — App Insights Application Map or Jaeger dependency view.",
      "SLO-based alerts? — Burn rate on availability SLO — not CPU-only.",
      "Logs without trace correlation",
      "Broken trace at message broker",
      "Each team custom metrics naming"),
    q("Centralized Logging", "Capstone", "Common",
      "Design centralized logging for 12 microservices — collection, retention, PII.",
      "Agents: stdout JSON → Fluent Bit/Fluentd → OpenSearch or Log Analytics. Index by service, environment, traceId. Retention: 30d hot, 1y cold archive.",
      "**Standards:**\n- Mandatory fields: `timestamp`, `level`, `service`, `traceId`, `spanId`, `message`, `properties`\n- PII scrubbing at ingest — regex card/email\n- RBAC on log access — prod logs restricted\n\n**Architect:** Central logging is compliance and incident requirement — budget storage.",
      "Centralized logging enables cross-service incident response.",
      "Log volume cost control? — Sampling debug; structured INFO only prod.",
      "Correlation without tracing? — traceId in logs minimum.",
      "SSH to pod to tail logs",
      "Unredacted PII in centralized store",
      "No retention policy — unbounded cost"),
    q("SLO per Service", "Capstone", "Very Common",
      "Define SLOs for order, payment, and catalog services.",
      "Order API: 99.9% availability, p99 latency <300ms. Payment: 99.95% (money path). Catalog read: 99.5%, p99 <100ms. Error budget policy: freeze features if budget exhausted.",
      "**SLO template:**\n- SLI: successful requests / total (exclude 4xx client errors optionally)\n- Window: 30-day rolling\n- Alert: multi-burn-rate — 14.4x burn page immediately\n\n**Architect:** SLO per service — not one global — reflects business criticality.",
      "Per-service SLO drives prioritization and error budget culture.",
      "Dependency SLO? — Order SLO can't exceed product of critical deps — document.",
      "Synthetic probes? — Checkout canary every 1m — SLI supplement.",
      "One 99.99% SLO for everything",
      "SLO without error budget policy",
      "Latency SLO on p50 only"),
    q("Deployment Independence", "Capstone", "Very Common",
      "Prove deployment independence — order v2.3 ships while catalog stays on v1.8.",
      "Separate CI/CD per service repo. Contract tests in consumer pipeline. Backward-compatible API — v2 adds fields; catalog never calls order internal endpoints.",
      "**Proof points:**\n- GitHub Actions workflow scoped to service path\n- Blue/green or rolling deploy per K8s deployment\n- Feature flags decouple deploy from exposure\n- Shared infra (K8s cluster) OK — shared *deploy button* not OK\n\n**Architect:** Independent deploy is defining characteristic — demo in capstone.",
      "Deployment independence must be demonstrable not asserted.",
      "Database migration blocks all services? — Coupled — fix schema ownership.",
      "Monorepo deploy? — Path-filtered pipelines still independent.",
      "Single release train all services",
      "Breaking API without consumer notice",
      "Shared library forces lockstep deploy"),
    q("Database Migration per Service", "Capstone", "Common",
      "Each microservice owns its database — migration strategy without coupling.",
      "Flyway/Liquibase/EF migrations per service repo. Expand-contract for shared data elimination. No cross-service FK — use events for sync.",
      "**Expand-contract example:**\n1. Add nullable column (expand)\n2. Dual-write both old and new\n3. Backfill job\n4. Switch reads\n5. Drop old column (contract)\n\n**Architect:** Migration runs in service pipeline pre-deploy — failed migration blocks only that service.",
      "Per-service migrations enable true ownership.",
      "Shared DBA runs all migrations? — OK ops — scripts still owned by service team.",
      "Breaking schema change on event payload? — Version event — parallel consumers.",
      "Cross-service foreign keys",
      "Manual SQL in prod without version control",
      "Migration rollback untested"),
    q("API Composition vs Aggregation", "Capstone", "Common",
      "Mobile app needs order + customer + product names — composition layer or client calls three APIs?",
      "API aggregation (BFF): single `GET /mobile/orders/{id}` composes three service calls server-side — reduces chattiness, controls response shape. Not full GraphQL unless needed.",
      "**Composition (API gateway):** route + light transform — no heavy logic.\n\n**Aggregation (BFF):** fan-out parallel `Task.WhenAll`, timeout per dependency, partial response policy.\n\n**Architect:** BFF per client type (mobile, web) — not per microservice.",
      "Composition vs aggregation terminology often confused — clarify in interview.",
      "BFF god object? — Only presentation logic — no domain rules.",
      "Cache composed response? — Short TTL — invalidate on order event.",
      "Mobile calls 8 microservices directly",
      "BFF writes to multiple service DBs",
      "No timeout on fan-out composition"),
    q("GraphQL Federation", "Capstone", "Occasional",
      "Evaluate GraphQL federation for order + catalog + customer supergraph.",
      "Each service owns subgraph schema — gateway federates. Order subgraph extends `Customer` with `orders` field — resolved via reference.",
      "**Pros:** Single query mobile, typed schema, team-owned subgraphs.\n\n**Cons:** Operational complexity, N+1 at scale (dataloader), caching harder than REST CDN.\n\n**Architect:** Federation when many client-driven field combinations — not default for simple CRUD.",
      "Federation is product-facing aggregation pattern.",
      "Schema governance? — Rover checks breaking changes in CI.",
      "Federation vs BFF? — Federation client-driven; BFF server-curated payloads.",
      "Monolithic GraphQL schema one team",
      "No query depth/complexity limits",
      "Federation without performance testing"),
    q("Event Schema Governance", "Capstone", "Very Common",
      "Govern integration event schemas across 8 teams.",
      "Schema registry (Avro/JSON Schema) with BACKWARD compatibility. PR checks: additive fields only in minor. `{Event}V{n}` naming. Owning team publishes schema repo.",
      "**Process:**\n1. Propose schema change in ADR\n2. CI compatibility check\n3. Register new version\n4. Consumers regenerate stubs\n5. Deprecation window 90 days\n\n**Architect:** Schema council reviews breaking changes — platform team enforces registry.",
      "Event schema governance prevents distributed monolith breakage.",
      "Optional vs required fields? — New fields optional with default — Avro unions.",
      "Unknown producer event? — Reject at registry — no ad hoc topics.",
      "Unversioned JSON blobs on bus",
      "Breaking rename without major version",
      "No consumer contract tests"),
    q("Breaking Change Policy", "Capstone", "Common",
      "Microservice API breaking change policy — steps before removing field.",
      "1. Announce deprecation in changelog + `Sunset` header. 2. Maintain parallel v1/v2 minimum 6 months. 3. Metrics on v1 traffic — notify stragglers. 4. Remove only at zero consumers (Pact verification).",
      "**Breaking:** remove field, rename, change type, narrow enum.\n\n**Non-breaking:** add optional field, add endpoint.\n\n**Architect:** Policy in platform handbook — automated breaking change detection in CI.",
      "Breaking change discipline protects internal API consumers.",
      "Consumer-driven contracts? — Pact — provider verifies before deploy.",
      "Sunset header? — `Sunset: Sat, 01 Jan 2027` — HTTP standard.",
      "Remove field because unused (unmeasured)",
      "No version bump",
      "Break mobile app without coordination"),
    q("On-Call Ownership", "Capstone", "Common",
      "Define on-call ownership model for order and payment services.",
      "Each service has primary owning team on-call rotation. Platform team on-call for K8s/ingress. Escalation: L1 service → L2 domain architect → vendor (Stripe).",
      "**Runbook link in PagerDuty service.** SLO pages go to owning team — not centralized ops only.\n\n**Architect:** Conway's Law — team that builds runs — no throw-over-wall ops.",
      "On-call ownership is production architecture concern.",
      "Shared on-call for all microservices? — Ownership blur — slow incident response.",
      "Follow-the-sun? — For global product — handoff documented.",
      "No owning team for service",
      "Platform team pages for app bugs",
      "On-call without runbook access"),
    q("Runbook per Service", "Capstone", "Common",
      "What belongs in a microservice runbook? Example for payment service.",
      "Architecture diagram, dependencies, SLO, alert catalog, common failures (webhook delay, Stripe outage), rollback steps, escalation contacts, useful queries/dashboards.",
      "**Payment runbook sections:**\n1. **Overview** — purpose, team, repo\n2. **Dependencies** — Stripe, SQL, Service Bus\n3. **Alerts** — `PaymentErrorRateHigh` → check Stripe status page\n4. **Procedures** — replay DLQ, reconcile stuck sagas\n5. **Rollback** — Helm revision `helm rollback`\n\n**Architect:** Runbook tested in game day — not shelfware.",
      "Runbooks convert architecture knowledge to incident action.",
      "Runbook as code? — Markdown in repo — PR reviewed.",
      "Game day? — Quarterly simulate Stripe down — measure MTTR.",
      "Runbook only 'restart pod'",
      "No dependency list",
      "Outdated runbook after redesign"),
    q("Chaos Test Microservices", "Capstone", "Common",
      "Design chaos experiments for order checkout path.",
      "Hypothesis: when inventory latency +2s, checkout p99 stays <2s due to timeout + circuit breaker. Experiment: Litmus/Gremlin inject latency on inventory pod 5% traffic.",
      "**Experiments:**\n- Kill payment pod — verify retry + no double charge\n- Partition Service Bus — orders queue but recover\n- DNS failure to Stripe — fail gracefully\n\n**Architect:** Start staging — prod blast radius controlled — one service one experiment.",
      "Chaos validates resilience architecture claims.",
      "Blast radius? — Single AZ, single pod, 5% traffic — expand gradually.",
      "Steady state hypothesis? — Define measurable before experiment.",
      "Chaos only on CPU — not dependencies",
      "Prod chaos without approval",
      "No rollback on experiment failure"),
    q("Load Test Distributed", "Capstone", "Very Common",
      "Load test distributed checkout — approach and metrics.",
      "k6/Gatling scenarios: realistic think time, ramp to target RPS, run from multiple regions. Monitor per-service CPU, p99, error rate, queue depth, DB connections.",
      "**Phases:**\n1. Baseline single service\n2. Integration path 10% target\n3. Full target + soak 4h\n4. Chaos + load combined\n\n**Bottleneck service:** scale or optimize that hop — document in ADR.\n\n**Architect:** Load test proves SLO achievability — not checkbox.",
      "Distributed load test finds weakest service in chain.",
      "Coordinated omission? — k6 handles — validate tool.",
      "Test data isolation? — Dedicated load tenant — don't corrupt prod-like shared data.",
      "Load only API gateway",
      "Ignore message queue backlog",
      "Single-region test for global app"),
    q("Cost Allocation Microservices", "Capstone", "Occasional",
      "Allocate cloud cost per microservice team.",
      "Tag every resource: `service`, `team`, `environment`. Cost explorer / FinOps dashboard per team monthly. Showback before chargeback.",
      "**Tags:** AKS namespaces labeled, SQL per service account, Service Bus topics named by owner.\n\n**Architect:** Cost visibility drives right-sizing — orphan services get retired.",
      "FinOps is part of architecture governance.",
      "Untagged shared cluster cost? — Split by CPU/memory request ratio.",
      "Cost anomaly alert? — 30% week-over-week spike.",
      "No tagging standards",
      "One shared mega-SQL for all",
      "Teams blind to their cloud bill"),
    q("Team Topology Team Topologies", "Capstone", "Common",
      "Map Team Topologies to your microservices capstone teams.",
      "Stream-aligned: Order team, Payment team (own E2E features). Platform: internal developer portal, K8s, CI templates. Enabling: DDD coach/adoption. Complicated-subsystem: fraud ML if needed.",
      "**Interaction modes:** Collaboration (discovery) → X-as-a-Service (platform APIs) → Facilitating (enablement).\n\n**Architect:** Team boundaries align with service boundaries — reduce cognitive load per team (2-pizza).",
      "Team Topologies vocabulary shows organizational architecture fluency.",
      "Platform as product? — Golden paths, self-service deploy — not ticket ops.",
      "Too many stream-aligned teams? — Thinnest viable stream.",
      "One team owns 15 services",
      "Platform team does all deploys",
      "Conway ignored in service split"),
    q("Production Readiness Review Microservices", "Capstone", "Very Common",
      "Production readiness review checklist before capstone go-live.",
      "SLO defined, dashboards, alerts, runbooks, on-call rotation, security scan, pen test items closed, load test passed, chaos done, DR tested, migration rollback, feature flags, incident response drill.",
      "**PRR gate items:**\n- [ ] OTel traces E2E demo recorded\n- [ ] Secrets in Key Vault — no .env in image\n- [ ] Pact contracts green\n- [ ] Error budget policy acknowledged\n- [ ] Data backup RPO/RTO documented\n\n**Architect:** PRR is formal sign-off — not informal 'looks good'.",
      "PRR demonstrates you ship responsibly not just design.",
      "Gradual rollout? — Canary 5% → 25% → 100% with metric gates.",
      "Rollback tested? — One-click verified in staging.",
      "Skip PRR for demo",
      "No on-call before launch",
      "Load test never run at target RPS"),
]
