"""Hand-crafted premium Q001–Q010 for Weeks 3–4."""

from premium_qa_data import q

WEEK_3_Q001_Q010 = [
    q("Single Responsibility Principle", "SOLID", "Very Common",
      "Explain SRP and how you enforce it at architecture level.",
      "A module should have one reason to change. At architecture level: separate pricing, persistence, and notification — not one `OrderService` doing everything.",
      "**Code:** `OrderPricingService`, `OrderRepository`, `OrderNotificationService` — each changes for different business reasons.\n\n**Architect:** SRP drives microservice boundaries — if two teams change the same class for different reasons, split it.\n\n**Measure:** Class cohesion metrics, change-frequency heat maps in git.",
      "SRP is the most cited SOLID principle in architect interviews.",
      "SRP vs microservices? — SRP informs boundaries; not one service per class.",
      "How small is too small? — When abstraction cost exceeds benefit.",
      "God service with 40 methods",
      "Splitting every class into one method",
      "SRP only at class level ignoring module boundaries"),
    q("Open/Closed Principle", "SOLID", "Very Common",
      "Give a production OCP example in C# enterprise code.",
      "Open for extension, closed for modification. Add new discount types via `IDiscountStrategy` — don't edit `PricingService` switch.",
      "```csharp\npublic interface IDiscountStrategy { decimal Apply(Order o); }\n// New VIP discount = new class, register in DI\n```\n\n**Architect:** Plugin architectures, rule engines, strategy pattern for tax jurisdictions.\n\n**Avoid:** Abstract factory explosion for 2 variants.",
      "OCP enables safe extension without regression risk.",
      "Switch expressions vs OCP? — Closed set use switch; open set use strategy.",
      "Feature flags vs OCP? — Flags for release; OCP for permanent variants.",
      "Modify switch every new discount type",
      "Interface for single implementation",
      "OCP via copy-paste inheritance"),
    q("Liskov Substitution Principle", "SOLID", "Common",
      "What is an LSP violation in a .NET API?",
      "Subtype must honor parent contract. Override that throws `NotSupportedException` or tightens preconditions = LSP violation.",
      "**Classic:** Square/Rectangle. **Enterprise:** `ReadOnlyCollection` wrapping list but exposing Add via cast.\n\n**Architect:** Favor composition over inheritance when behavior diverges. Code review flags `throw new NotSupportedException()` in overrides.",
      "LSP protects polymorphism reliability.",
      "Bird extends Animal flies? — Ostrich LSP teaching example.",
      "Contract testing subtypes? — Consumer tests against interface.",
      "Subclass narrows input acceptance",
      "Override changes expected side effects",
      "Inheritance where composition fits"),
    q("Interface Segregation Principle", "SOLID", "Common",
      "ISP at microservice API level — example?",
      "Clients shouldn't depend on methods they don't use. Split fat `IOrderService` into `IOrderReader` and `IOrderWriter`; BFF exposes only needed endpoints.",
      "**API design:** Mobile BFF returns 5 fields; admin API returns full order — different interfaces not one bloated DTO for all.\n\n**Architect:** Segregate NuGet package interfaces — consumers reference slim abstractions.",
      "ISP reduces coupling and accidental API misuse.",
      "Role interfaces in C#? — Implicit segregation pattern.",
      "GraphQL vs ISP? — Clients select fields — different approach.",
      "IFatRepository with 30 methods",
      "Mobile client forced to reference admin API",
      "One DTO for all clients forever"),
    q("Dependency Inversion Principle", "SOLID", "Very Common",
      "How does DIP relate to DI containers in .NET?",
      "High-level modules depend on abstractions; low-level implements them. DI container wires `IOrderRepository` → `SqlOrderRepository`.",
      "**Architect mandates:** Domain/application define interfaces; infrastructure implements. No `new SqlConnection` in handlers.\n\n**Testability:** Mock abstractions in unit tests.\n\n**Composition root:** `Program.cs` or extension method registers implementations.",
      "DIP + DI is foundation of testable .NET architecture.",
      "DIP without DI container? — Manual composition root still valid.",
      "Primary constructors affect DIP? — Still inject abstractions.",
      "Application references SqlClient",
      "Concrete classes in domain layer",
      "Service locator instead of constructor injection"),
    q("Clean Architecture Layers", "Clean Arch", "Very Common",
      "Name the layers and dependency direction in Clean Architecture.",
      "Domain (center) → Application → Infrastructure/Presentation outward. Dependencies point inward only.",
      "| Layer | Contains |\n|-------|----------|\n| Domain | Entities, value objects, domain events |\n| Application | Use cases, handlers, ports |\n| Infrastructure | EF, HTTP clients, messaging |\n| Presentation | API, UI |\n\n**Architect:** Enforce with NetArchTest in CI.",
      "Layer violations are architect review red flags.",
      "Onion vs Clean vs Hexagonal? — Same dependency rule, different names.",
      "Shared kernel between layers? — Only value objects cross carefully.",
      "Domain references EF Core",
      "Controller calls DbContext directly",
      "Circular project references"),
    q("Vertical Slice Architecture", "Architecture", "Common",
      "Vertical slice vs horizontal layers — when choose vertical?",
      "Vertical: organize by feature (`Features/Orders/Create`). Horizontal: by technical concern (`Controllers/`, `Services/`).",
      "**Choose vertical when:** Feature teams ship independently, codebase large, change isolation matters.\n\n**Choose horizontal when:** Small team, simple CRUD, everyone owns all layers.\n\n**Architect:** MediatR handlers natural fit for slices.",
      "Slice architecture matches agile delivery.",
      "Shared infrastructure slice? — Cross-cutting in `/Infrastructure` folder.",
      "Slice boundaries = microservice boundaries? — Good stepping stone.",
      "500-file Services folder",
      "Duplicate validation per slice unchecked",
      "No shared kernel discipline"),
    q("CQRS — When to Introduce", "CQRS", "Common",
      "When introduce CQRS in enterprise .NET system?",
      "When read and write models diverge — complex reports, different scale, different storage optimization. Not day-one for simple CRUD.",
      "**Start logical:** Separate query handlers from commands; same DB OK.\n\n**Physical split:** When read replicas or Elasticsearch projection justified by metrics.\n\n**Architect:** Measure read:write ratio and query complexity before physical CQRS.",
      "CQRS is scaling tool not mandatory pattern.",
      "CQRS without event sourcing? — Common and valid.",
      "Read model rebuild strategy? — From events or DB snapshot.",
      "CQRS two databases for 100 users",
      "Duplicate business rules read/write",
      "Confuse CQRS with CRUD renaming"),
    q("MediatR — Pros and Cons", "Patterns", "Common",
      "MediatR in Clean Architecture — benefits and drawbacks?",
      "Pros: decoupled handlers, pipeline behaviors, one class per use case. Cons: indirection, magic for juniors, assembly scanning perf negligible.",
      "**Architect adoption:** Standard in enterprise .NET templates — document handler conventions.\n\n**Pipeline:** Validation, logging, transactions as behaviors.\n\n**Alternative:** Direct handler injection without MediatR for tiny apps.",
      "MediatR is organizational pattern as much as technical.",
      "MediatR vs custom mediator? — Roll own if 3 handlers only.",
      "Notification vs request? — Events in-process via notifications.",
      "MediatR for every GET trivial",
      "Handler calls handler bypassing mediator",
      "No pipeline behavior standards"),
    q("Anemic vs Rich Domain Model", "DDD", "Very Common",
      "Anemic domain model — problem and fix?",
      "Anemic: entities are data bags; all logic in services. Rich: entities enforce invariants (`order.Confirm()`).",
      "**Problem:** Business rules scattered, duplication, hard to test domain in isolation.\n\n**Fix:** Move behavior to aggregates; application layer orchestrates only.\n\n**Pragmatic:** Not every DTO needs behavior — DTOs anemic OK; aggregates should be rich.",
      "Domain model style is cultural architect decision.",
      "Transaction script pattern? — Valid for simple ETL — know trade-off.",
      "Rich domain with EF change tracking? — Works with careful design.",
      "OrderService 2000 lines all logic",
      "Public setters on every entity property",
      "No domain tests only integration"),
]

WEEK_4_Q001_Q010 = [
    q("Singleton vs DI Singleton", "Creational", "Very Common",
      "Static singleton vs DI-registered singleton lifetime?",
      "Static singleton: global hidden state, hard to test. DI singleton: one instance per container, mockable, explicit lifetime.",
      "```csharp\nservices.AddSingleton<ICacheService, MemoryCacheService>();\n```\n\n**Architect:** Ban static mutable singletons in coding standards. DI singleton for stateless caches and config readers.\n\n**Exception:** `IOptions` effectively singleton.",
      "DI singleton is not the Singleton pattern anti-pattern.",
      "Singleton vs Scoped for cache? — Scoped if cache must be per-tenant request.",
      "IMemoryCache thread safety? — Built-in thread-safe.",
      "static Database.Instance",
      "Singleton holding Scoped DbContext",
      "Global mutable static cache"),
    q("Factory Pattern", "Creational", "Common",
      "Factory pattern for payment gateway selection?",
      "Encapsulate creation logic — `IPaymentGatewayFactory.Create(PaymentType type)` returns Stripe or Adyen implementation.",
      "**When:** Creation complex (config, credentials, sandbox vs prod). **SimpleFactory vs FactoryMethod:** Method per product vs subclass override.\n\n**Architect:** Register factory in DI; unit test returns mocks.",
      "Factories isolate construction from business logic.",
      "DI container as factory? — `GetRequiredService` by key .NET 8.",
      "Abstract factory when? — Families of related gateways + reporting.",
      "new StripeGateway() in controller",
      "Factory with 50 case switch",
      "No interface on products"),
    q("Adapter Pattern", "Structural", "Very Common",
      "Adapter for legacy ERP integration?",
      "Wrap legacy XML/SOAP ERP API behind `IOrderPort` your application understands.",
      "**Anti-corruption layer** is architect-level adapter — translate models at boundary.\n\n**Example:** `LegacyErpOrderAdapter` maps `ErpXmlOrder` → `PlaceOrderCommand`.",
      "Adapters enable strangler fig migrations.",
      "Two-way adapter? — Rare — usually one direction inbound.",
      "Adapter vs Facade? — Adapter changes interface; Facade simplifies subsystem.",
      "Import ERP types into domain",
      "Copy-paste ERP parsing everywhere",
      "Adapter with business logic bloat"),
    q("Decorator vs Inheritance", "Structural", "Common",
      "Decorator pattern for cross-cutting without inheritance?",
      "Wrap `IOrderService` with `CachingOrderServiceDecorator` — adds behavior without subclass explosion.",
      "**vs Inheritance:** 3 cross-cutting concerns = 8 subclasses combinatorial explosion with inheritance; 3 decorators stack cleanly.\n\n**DI:** `services.Decorate<IOrderService, CachingDecorator>()` Scrutor library.",
      "Decorator is composition over inheritance exemplified.",
      "Middleware vs decorator? — HTTP pipeline similar concept different layer.",
      "Decorator order matters? — Cache outside or inside logging — document.",
      "Inheritance tree LoggingCachingOrderService",
      "Decorator changing interface contract",
      "Infinite decorator recursion"),
    q("Facade Pattern", "Structural", "Common",
      "Facade for checkout orchestration?",
      "`CheckoutFacade.PlaceOrder()` coordinates inventory, payment, notification — controller calls one method.",
      "**Not god object:** Facade delegates; doesn't implement business rules.\n\n**Architect:** BFF is facade at API boundary. Application service can be facade over domain.",
      "Facade simplifies client interaction.",
      "Facade vs MediatR? — MediatR dispatches; facade explicit API.",
      "Multiple facades per bounded context? — Yes per use case area.",
      "Controller calls 8 services directly",
      "Facade with 500 lines business logic",
      "Facade bypassing domain invariants"),
    q("Strategy Pattern", "Behavioral", "Very Common",
      "Strategy for shipping cost calculation?",
      "`IShippingStrategy` implementations: Standard, Express, International — selected by order context.",
      "**DI registration:** `services.AddTransient<IShippingStrategy, ExpressShipping>()` with factory key.\n\n**Architect:** Strategy + OCP together — add carrier without editing calculator.",
      "Strategy is most practical GoF pattern daily.",
      "Strategy vs policy pattern? — Similar intent different name.",
      "Functional strategy as lambda? — OK for simple cases.",
      "switch on string shipping type",
      "Strategy interface with 1 implementation forever",
      "Context class knowing all strategies concretely"),
    q("Observer and Domain Events", "Behavioral", "Common",
      "Observer pattern vs .NET events vs domain events?",
      "Observer: subject notifies subscribers. .NET `event` keyword. Domain events: DDD pattern — `OrderPlaced` raised from aggregate, handled in-process or outbox.",
      "**Architect:** Domain events for business facts; integration events for cross-service. MediatR `INotification` for in-process handlers.",
      "Event-driven decoupling within and across services.",
      "Event vs command? — Past tense fact vs imperative.",
      "Spaghetti event chains? — Document flow; consider orchestration.",
      "God object firing 20 events synchronously",
      "Domain event published before commit",
      "No handler idempotency cross-service"),
    q("Repository Pattern Debate", "Enterprise", "Very Common",
      "Do you still use Repository with EF Core?",
      "DbContext is already repository+UoW. Use repository per aggregate when interface adds value — custom queries, testing seam, swap storage.",
      "**Architect position:** `IOrderRepository` with meaningful methods — not generic `IRepository<T>` on 40 entities.\n\n**Skip when:** Small service, team proficient with DbContext directly.",
      "Repository debate shows architect pragmatism.",
      "Specification + repository? — Composable queries.",
      "Cosmos repository same interface? — Possible adapter.",
      "IRepository<T> everywhere",
      "Repository returns IQueryable to API",
      "Pass-through repo adding no value"),
    q("Outbox Pattern", "Enterprise", "Very Common",
      "Implement transactional outbox in .NET?",
      "Same transaction: save aggregate + insert outbox row. Background relay publishes to Service Bus and marks sent.",
      "**Libraries:** MassTransit EF outbox, custom relay worker.\n\n**Architect:** Never `SaveChanges` then `Publish` without outbox — crash between = inconsistency.\n\n**Idempotent consumers** on other side still required.",
      "Outbox is architect messaging reliability standard.",
      "Inbox pattern pairing? — Consumer dedup table.",
      "Outbox polling vs CDC? — Polling simpler; CDC lower latency.",
      "Publish before commit",
      "No poison message handling",
      "Outbox table unbounded no cleanup"),
    q("Saga Pattern Introduction", "Enterprise", "Common",
      "Orchestrated vs choreographed saga for order flow?",
      "Choreography: services react to events — loose coupling. Orchestration: central coordinator (Durable Functions) — visible flow, easier debug.",
      "**Steps:** Reserve inventory → Charge payment → Confirm order. Compensate on failure: release, refund.\n\n**Architect:** Start choreography 2-3 steps; orchestration when complexity grows.",
      "Sagas replace distributed 2PC.",
      "Saga vs 2PC? — Saga eventual consistency with compensation.",
      "Long-running saga state? — Durable Functions or MassTransit state machine.",
      "Sync HTTP chain 5 services",
      "No compensation defined",
      "Saga state lost on restart"),
]

ALL_WEEKS_3_4_Q001_Q010 = {3: WEEK_3_Q001_Q010, 4: WEEK_4_Q001_Q010}
