"""Hand-crafted premium Q011–Q030 for Week 2 — .NET Runtime."""

from premium_qa_data import q

WEEK2_Q011_Q030 = [
    q("Server GC vs Workstation GC", "GC", "Common",
      "When configure Server GC vs Workstation GC for .NET APIs?",
      "Server GC: high-throughput multi-core servers (default ASP.NET). Workstation GC: lower latency, fewer cores — client apps, some consoles.",
      "**ASP.NET Core on Linux containers:** Server GC default — optimize throughput.\n\n**When Workstation:** Interactive apps, Unity, scenarios prioritizing pause latency over total throughput.\n\n**Architect:** Measure `% Time in GC` and P99 latency before tuning. `DOTNET_gcServer` and `DOTNET_GCRetainVM` env vars for containers.",
      "GC mode affects latency SLOs at scale.",
      "DATAS GC? — Dynamic adaptation — .NET 9+ options — evaluate per workload.",
      "GC in containers limits? — Set memory limits; GC respects cgroup.",
      "Workstation GC on 16-core API server",
      "GC.Collect() in production code",
      "No GC metrics in dashboards"),
    q("Thread Pool Starvation", "Async", "Very Common",
      "Symptoms and fixes for thread pool starvation in ASP.NET Core?",
      "Symptoms: slow responses, Kestrel queue growth, `ThreadPool starvation` events. Causes: sync-over-async, blocking I/O, long-running tasks on thread pool.",
      "**Detect:** `dotnet-counters` ThreadPool queue length, App Insights dependency duration spikes.\n\n**Fix:** async all the way, `Task.Run` only for CPU offload with limits, dedicated worker for long jobs.\n\n**Architect:** Ban `.Wait()`/`.Result` in web projects via analyzer.",
      "Thread pool is shared resource — architects protect it.",
      "Min threads configuration? — Last resort — find root cause first.",
      "IOCompletionPort threads? — Separate from worker threads — know distinction.",
      "sync-over-async in library used by API",
      "Blocking HttpClient.GetStringAsync().Result",
      "Ignore ThreadPool starvation warnings"),
    q("HttpClientFactory Deep Dive", "HTTP", "Very Common",
      "Why `IHttpClientFactory` over static or injected HttpClient?",
      "Factory manages handler lifetime — avoids socket exhaustion from disposing HttpClient wrong. Named/typed clients centralize config.",
      "**Socket exhaustion:** `new HttpClient()` per request or singleton with infinite DNS cache — both fail at scale.\n\n**Pattern:**\n```csharp\nservices.AddHttpClient<IPaymentClient, PaymentClient>(c =>\n    c.BaseAddress = new Uri(...));\n```\n\n**Architect:** Polly handlers on factory pipeline; standard timeout and retry policy.",
      "HttpClient misuse is classic production outage cause.",
      "SocketsHttpHandler PooledConnectionLifetime? — Rotate connections for DNS.",
      "Primary HttpMessageHandler? — Test with mock handler.",
      "new HttpClient() per request",
      "Static HttpClient never refreshed DNS",
      "No timeout on outbound calls"),
    q("Polly Resilience Policies", "Resilience", "Common",
      "Design Polly policies for payment gateway HttpClient?",
      "Retry (transient 5xx/408), circuit breaker (cascade prevention), timeout (end-to-end bound), bulkhead (isolate dependency).",
      "**Order matters:** timeout outermost or innermost depending on semantics — document choice.\n\n**Architect:** Retry only idempotent operations or with idempotency key. Circuit breaker opens → fail fast → half-open probe.\n\n**.NET 8+:** `Microsoft.Extensions.Resilience` standardized pipelines.",
      "Resilience policies are architect-level contracts.",
      "Jitter in retry? — Prevent thundering herd on recovery.",
      "Fallback policy? — Return cached quote when pricing API down.",
      "Infinite retry on POST payment",
      "Circuit breaker never half-opens",
      "Same policy all dependencies"),
    q("OpenTelemetry in .NET", "Observability", "Common",
      "Instrument .NET microservice with OpenTelemetry?",
      "Add OTel SDK: traces (AspNetCore, HttpClient, EF), metrics (runtime, custom counters), logs correlation. Export to Azure Monitor / Jaeger / Prometheus.",
      "**Architect standard:** W3C trace context propagation across services. ActivitySource for custom spans.\n\n**Sampling:** Head-based in high traffic — adjust sample rate for cost.\n\n**Avoid:** Vendor lock-in proprietary agents only.",
      "OTel is architect's portability play for observability.",
      "Baggage vs tags? — Baggage propagates context — use sparingly.",
      "OTel logs bridge? — Correlate logs to traceId.",
      "No distributed tracing across services",
      "100% trace sampling at 50K RPS",
      "Custom metrics without SLO mapping"),
    q("Serilog Structured Logging", "Observability", "Common",
      "Structured logging standards for enterprise .NET?",
      "`LogInformation(\"Order {OrderId} placed\", orderId)` — searchable properties not string concat.",
      "**Architect mandates:** CorrelationId enricher, log levels per namespace, JSON to stdout in containers, PII redaction middleware.\n\n**Sinks:** Console for K8s, Application Insights sink, Seq for dev.\n\n**Anti-pattern:** `LogInformation($\"Order {id}\")` — loses structured property.",
      "Logs are production debugging backbone.",
      "LogContext.PushProperty? — Scoped properties in request.",
      "Sensitive data masking? — Custom destructuring policies.",
      "String concat logging only",
      "Debug logs in production always on",
      "Log PII card numbers"),
    q("EF Core DbContext Pooling", "EF Core", "Common",
      "When use `AddDbContextPool` vs `AddDbContext`?",
      "Pooling: high-throughput read-heavy APIs — reuses context instances. Non-pooling: contexts with heavy state or non-standard lifetime.",
      "**Caveat:** Reset state on return to pool — don't stash request data on context fields.\n\n**Architect:** Pool size default 1024 — validate against connection pool limits.\n\n**Measure:** Benchmark before/after on hot read endpoints.",
      "Pooling is performance tool with constraints.",
      "DbContext factory pattern? — Blazor and background jobs.",
      "Multiple DbContext types pooled? — Each registered separately.",
      "Stateful fields on pooled DbContext",
      "Pool size × instances > SQL max connections",
      "Pooling without understanding reset"),
    q("EF Core Interceptors", "EF Core", "Occasional",
      "Use cases for EF Core interceptors?",
      "Auditing (CreatedBy, UpdatedAt), soft delete global filter, slow query logging, multi-tenant connection routing.",
      "**Architect:** Cross-cutting data concerns in interceptors — not copy-paste in every repository.\n\n**Example:** `SaveChangesInterceptor` sets audit fields from `IHttpContextAccessor`.\n\n**Test:** Interceptors covered in integration tests.",
      "Interceptors centralize data policies.",
      "IDbConnectionInterceptor? — Connection-level logging.",
      "Query tagging interceptor? — Tag SQL with request ID.",
      "Audit logic duplicated per entity",
      "Interceptor throws swallows root error",
      "No test coverage on interceptors"),
    q("Minimal API Endpoint Filters", "ASP.NET", "Common",
      "Endpoint filters vs middleware — when which?",
      "Middleware: cross-cutting pipeline order (auth, exception). Endpoint filters: per-route or per-group validation, logging — closer to handler.",
      "**Architect:** Validation filter on command endpoints; middleware for correlation ID and ProblemDetails.\n\n**.NET 7+:** `IEndpointFilter` chain like middleware mini-pipeline.",
      "Right abstraction layer reduces duplication.",
      "Filter vs action filter MVC? — Parallel concepts different stacks.",
      "Antiforgery on minimal APIs? — Form posts need tokens.",
      "Duplicate validation filter and middleware",
      "Business logic in endpoint filter",
      "No filter ordering documentation"),
    q("Rate Limiting Middleware", "ASP.NET", "Common",
      "Implement rate limiting for public .NET API?",
      ".NET 7+ `AddRateLimiter` — fixed window, sliding window, token bucket, concurrency limiter.",
      "**Architect:** Per-API-key or per-IP partitioning. Return 429 with `Retry-After`. Gateway-level (APIM) + app-level defense in depth.\n\n**Distributed:** Redis-backed limiter for multi-instance consistency.",
      "Rate limiting protects availability and cost.",
      "Global vs per-endpoint limits? — Stricter on expensive endpoints.",
      "Rate limit bypass for internal callers? — IP allowlist or mTLS.",
      "No rate limit on login endpoint",
      "In-memory limiter only multi-instance",
      "429 without Retry-After header"),
    q("Output Caching ASP.NET", "Performance", "Common",
      "When use ASP.NET output caching vs Redis?",
      "Output caching: HTTP response cache for identical GETs on same instance/fleet with cache policy. Redis: shared cache across services, cache-aside pattern.",
      "**Output cache:** `[OutputCache(PolicyName = \"Catalog\")]` — VaryByQueryKeys.\n\n**Architect:** Don't output-cache personalized/authenticated responses without VaryByUser.\n\n**Invalidate:** Tag-based eviction .NET 8+.",
      "Cache layer choice affects consistency.",
      "CDN + output cache? — CDN edge for static; output cache origin.",
      "Cache stampede? — Lock or stale-while-revalidate.",
      "Cache user-specific JSON without Vary",
      "Output cache on POST",
      "No cache invalidation on update"),
    q("Native AOT Trade-offs", "Performance", "Occasional",
      "When recommend Native AOT for .NET services?",
      "Fast startup, small footprint — edge, serverless cold start, CLI tools. Constraints: no dynamic reflection, limited EF/serialization.",
      "**Architect pilot criteria:** Measure startup and size win vs feature restrictions.\n\n**Not default:** Full EF Core app with heavy reflection — validate compatibility.\n\n**.NET 8+:** Improving but architect signs off per service.",
      "AOT is strategic not default.",
      "Trimming vs AOT? — Trimming reduces size; AOT eliminates JIT.",
      "Source generators replace reflection? — Required for AOT paths.",
      "AOT entire monolith day one",
      "EF Core heavy app without AOT test",
      "Ignore trimming warnings"),
    q("System.Threading.Channels", "Concurrency", "Common",
      "When use `Channel<T>` in .NET architecture?",
      "In-process producer-consumer with backpressure — decouple stages without full message broker for single-process pipelines.",
      "**Bounded channel:** `FullMode.Wait` applies backpressure.\n\n**Architect:** Use broker (Service Bus) cross-process; Channel within single worker process pipeline.\n\n**Reader:** `await foreach` async enumeration.",
      "Channels bridge async and producer-consumer.",
      "Channel vs BlockingCollection? — Prefer Channel async-native.",
      "SingleReader optimization? — Performance flag when true.",
      "Unbounded channel hides memory leak",
      "Channel cross-service boundary",
      "No cancellation in reader loop"),
    q("IAsyncDisposable Patterns", "Resource Mgmt", "Common",
      "When implement `IAsyncDisposable` vs `IDisposable`?",
      "Async disposal when cleanup does I/O — database flush, async file write, gRPC channel shutdown.",
      "**Pattern:**\n```csharp\nawait using var conn = await OpenAsync();\n```\n\n**Architect:** `BackgroundService` dispose async resources on shutdown token.\n\n**Implement both:** `DisposeAsync` calls sync Dispose when no async work needed.",
      "Async disposal prevents thread blocking on teardown.",
      "ConfigureAwait in DisposeAsync? — Usually ConfigureAwait(false).",
      "GC.SuppressFinalize? — Still apply in hybrid dispose pattern.",
      "Block on DisposeAsync().GetAwaiter().GetResult()",
      "Only IDisposable on async resource",
      "No disposal in scoped services"),
    q("Data Protection API", "Security", "Occasional",
      "ASP.NET Data Protection for multi-instance apps?",
      "Encrypts cookies, antiforgery tokens, temp data. Keys must be shared across instances — Redis, Azure Blob, registry.",
      "**Architect:** Persist key ring to shared storage — else each instance invalidates cookies on deploy rotation.\n\n**Kubernetes:** Mount key ring secret or use Redis key ring.\n\n**Rotation:** Default 90-day — plan seamless rotation.",
      "Cookie auth breaks without shared key ring.",
      "IDataProtectionProvider scope? — Per-app purpose strings isolate.",
      "Encrypt at rest keys? — Azure Key Vault protector.",
      "Ephemeral keys per container restart",
      "Same app name different environments sharing keys",
      "No key rotation plan"),
    q("JWT Authentication Architecture", "Security", "Very Common",
      "Design JWT auth for SPA + .NET API?",
      "Entra ID / Auth0 issues JWT. API validates issuer, audience, signature, lifetime. Short access token + refresh token rotation.",
      "**Architect:** Never store JWT in localStorage if XSS risk — BFF or HttpOnly cookie pattern.\n\n**Validate:** `AddJwtBearer` with authority metadata.\n\n**Claims:** Map to policies not hardcoded role strings in controllers.",
      "Auth architecture is security foundation.",
      "Token introspection? — Opaque tokens reference — different pattern.",
      "mTLS service-to-service? — Complement JWT internal east-west.",
      "Long-lived JWT months",
      "No audience validation",
      "Custom crypto instead of standard library"),
    q("Policy-Based Authorization", "Security", "Common",
      "Policy-based authorization vs role checks in controllers?",
      "`[Authorize(Policy = \"CanRefund\")]` with requirement/handler — scales better than role strings.",
      "**Architect:** Policies encode business capabilities. Handlers check database permissions dynamically.\n\n**Test:** Authorization handler unit tests per policy.\n\n**Resource-based:** `IAuthorizationService.AuthorizeAsync(user, order, \"Owner\")`.",
      "Authorization model must evolve with product.",
      "FallbackPolicy? — Default deny — secure by default.",
      "Combine policies? — Require multiple policies on endpoint.",
      "[Authorize(Roles = \"Admin\")] everywhere",
      "Authorization logic in controller body",
      "No test on custom handlers"),
    q("ProblemDetails RFC 7807", "API Design", "Common",
      "Standardize API errors with ProblemDetails?",
      "Consistent JSON error shape: type, title, status, detail, instance, extensions for validation errors.",
      "**ASP.NET:** `AddProblemDetails()` + exception handler middleware.\n\n**Architect:** Never leak stack traces in prod. Correlation ID in `extensions`.\n\n**Client:** Predictable parsing for UI error display.",
      "Error contract is public API surface.",
      "ValidationProblemDetails? — 400 with field errors dictionary.",
      "ProblemDetails in gRPC? — Rich error model equivalent.",
      "Different error JSON per endpoint",
      "500 returns exception.Message only",
      "No correlation ID in errors"),
    q("API Versioning Strategy", "API Design", "Common",
      "URL vs header vs query API versioning for .NET?",
      "URL path (`/v2/orders`) most visible and cache-friendly. Header for strict REST purists. Query `?api-version=` acceptable.",
      "**Architect:** Version public APIs from day one. Deprecation policy: 6-12 months notice.\n\n**Package:** `Asp.Versioning.Mvc` with sunset headers.\n\n**Internal services:** May skip versioning early — document when to add.",
      "Versioning prevents breaking mobile clients.",
      "Combine versioning with OpenAPI? — Separate Swagger doc per version.",
      "Version internal gRPC? — Package proto versioning.",
      "Breaking change without version bump",
      "Three versions supported forever",
      "No deprecation communication"),
    q("BenchmarkDotNet for Architects", "Performance", "Occasional",
      "When require BenchmarkDotNet before architectural change?",
      "Before claiming Span vs string, pooling vs allocate, serialization library choice — measure with BenchmarkDotNet.",
      "**Architect:** Engineers bring benchmarks to design reviews — not opinions.\n\n**CI:** Benchmark in nightly not every PR — flaky in shared runners.\n\n**MemoryDiagnoser:** Allocation counts matter for hot paths.",
      "Data-driven performance decisions.",
      "Microbenchmark trap? — Benchmark representative workload not toy loop.",
      "Profiler vs benchmark? — Profiler finds hotspots; benchmark compares fixes.",
      "Optimize without measuring",
      "Benchmark debug build",
      "Ignore allocation in API hot path"),
]
