"""Hand-crafted premium Q001–Q010 — Weeks 7–8, 21–24, 33–36 and Week 1 advanced/expert."""

from premium_qa_data import q, WEEK_5, WEEK_6

WEEK_7 = [
    q("Clustered vs Non-Clustered Index", "Indexing", "Very Common",
      "Explain clustered vs non-clustered indexes in SQL Server. How do you decide?",
      "Clustered index defines physical row order (one per table). Non-clustered is separate structure with pointer to row. Cluster on primary access path — usually PK or most common range query column.",
      "**Clustered:** Table data IS the leaf level of the index. Range scans on clustered key are sequential I/O — fast.\n\n**Non-clustered:** Separate B-tree with row locator (RID or clustered key). Covering index includes all query columns — avoids key lookup.\n\n**Architect decisions:**\n- OLTP: clustered on PK (GUID clustered bad — random inserts fragment)\n- Wide table many queries: multiple non-clustered with careful write overhead\n- Reporting: columnstore index (different structure) for analytics\n\n**Anti-pattern:** GUID clustered PK on high-insert table — page splits, fragmentation.",
      "Index strategy drives write amplification and read latency at scale.",
      "INCLUDE columns? — Covering index avoids lookup — trade storage for read speed.",
      "Filtered index? — Index subset of rows — smaller, faster for sparse queries.",
      "Clustered index on random GUID PK",
      "Index every column — write throughput dies",
      "No index maintenance plan (rebuild/reorganize)"),
    q("Execution Plans and Query Tuning", "Performance", "Very Common",
      "How do architects approach slow queries in production SQL Server?",
      "Capture plan with Query Store or Extended Events, identify scans/seeks/hash spills, fix with indexes or rewrite. Set baseline p95 latency SLO per critical query.",
      "**Process:**\n1. Identify top CPU/duration queries (Query Store)\n2. Analyze plan — table scan, key lookup, sort, hash match warnings\n3. Fix: index, rewrite JOIN order, split query, archive old data\n4. Verify with plan regression tests\n\n**Architect:** Mandate Query Store enabled on all prod databases. Block deployments causing plan regressions.\n\nParameter sniffing: same query different plans for different parameter values — `OPTION (RECOMPILE)` or `OPTIMIZE FOR UNKNOWN` strategically.",
      "Query tuning is ongoing architecture — not one-time DBA task.",
      "Key lookup cost? — For each NC index match, fetch row from clustered — expensive at scale.",
      "When split read/write? — Read replicas for reporting queries over 500ms.",
      "Tuning without measuring production workload",
      "Hint-heavy SQL instead of proper indexes",
      "Ignoring parameter sniffing on critical SP"),
    q("Isolation Levels", "Transactions", "Very Common",
      "Compare SQL Server isolation levels. What would you use for a financial ledger?",
      "Read Committed default. Serializable strongest but deadlocks. Snapshot (RCSI) good for read-heavy with acceptable staleness. Financial ledger: Serializable or Repeatable Read for critical sections + app-level idempotency.",
      "| Level | Dirty Read | Non-repeatable | Phantom |\n|-------|------------|----------------|--------|\n| Read Uncommitted | Yes | Yes | Yes |\n| Read Committed | No | Yes | Yes |\n| Repeatable Read | No | No | Yes |\n| Serializable | No | No | No |\n| Snapshot (RCSI) | No | No* | No* |\n\n*Uses row versioning — readers don't block writers.\n\n**Ledger:** Strong consistency on balance updates — often Serializable range locks on account row + optimistic concurrency (`rowversion`).",
      "Wrong isolation causes double-spend bugs or excessive blocking.",
      "RCSI vs Snapshot isolation? — RCSI statement-level; Snapshot transaction-level consistent view.",
      "Deadlock handling? — Retry with exponential backoff; consistent lock order.",
      "Read Uncommitted in production for 'speed'",
      "Serializable everywhere — deadlock storm",
      "Ignoring rowversion for optimistic concurrency"),
    q("Partitioning Strategy", "Scale", "Common",
      "When and how do you partition large SQL Server tables?",
      "Partition when table exceeds manageable maintenance size (100M+ rows) or need sliding window archive. Range partition on date common — switch partitions in/out for archive.",
      "**Benefits:** Partition elimination in queries (scan one month not all history), fast archive via `SWITCH PARTITION`, parallel maintenance.\n\n**Keys:** Partition function on `CreatedDate` monthly; align indexes.\n\n**Architect:** Partitioning adds complexity — don't partition 10M row table prematurely. Use when backup/restore per partition or archive SLA requires it.",
      "Partitioning is operational architecture for data lifecycle.",
      "Partition alignment? — Indexes must align on same key for switch.",
      "Cross-partition queries? — Defeat elimination — design queries to filter on partition key.",
      "Partitioning without query filter on key",
      "Too many partitions — metadata overhead",
      "Partition key not in most queries"),
    q("Always On Availability Groups", "HA/DR", "Very Common",
      "Design SQL Server HA with Always On AG. RPO/RTO considerations?",
      "Synchronous replica in same region — RPO=0, automatic failover. Async cross-region — RPO>0 (seconds lag), manual or automatic failover for DR.",
      "**Architecture:**\n- Primary + sync secondary (same AZ/region) for HA\n- Async replica in DR region for geo\n- Listener for app connection string\n- Quorum: cloud witness (blob) or file share witness\n\n**RTO:** Failover ~30-120 seconds depending on recovery. **RPO:** Sync = 0; async = replication lag.\n\n.NET apps: connection string `MultiSubnetFailover=True`, retry logic for transient errors.",
      "Database HA is architect-owned NFR — apps must handle failover.",
      "Readable secondary? — Offload reporting — watch lag for stale reads.",
      "Distributed AG? — Cross-domain/geo — more complex topology.",
      "Single instance for production payment DB",
      "No app retry on failover transient errors",
      "Async replica assumed RPO=0"),
    q("TempDB Contention", "Performance", "Occasional",
      "What causes tempdb contention and how do you mitigate it?",
      "Tempdb shared by all databases — version store (RCSI), sorts, spools, temp tables. Contention on allocation pages (SGAM/PFS) at high concurrency.",
      "**Mitigations:**\n- Multiple tempdb data files (1 per CPU core up to 8)\n- Right-size memory reduce spills to tempdb\n- Reduce RCSI if version store huge\n- Trace flags for allocation contention (legacy)\n\n**Architect:** Monitor tempdb growth and latency — spikes correlate with bad queries (sort warnings in plan).",
      "Tempdb is silent bottleneck in busy SQL estates.",
      "Sort warning in plan? — Data spilling to tempdb — increase memory grant or index.",
      "Temp tables vs table variables? — Temp tables stats help optimizer — table variables often row estimate 1.",
      "Ignoring tempdb in capacity planning",
      "Single tempdb file on 32-core server",
      "RCSI without version store monitoring"),
    q("Deadlock Analysis", "Concurrency", "Common",
      "How do you diagnose and prevent deadlocks in SQL Server?",
      "Extended Events `xml_deadlock_report`, analyze cycle graph, fix lock order. App: retry transient deadlock error 1205. Design: consistent access order, shorten transactions.",
      "**Prevention:**\n1. Access tables in same order across SPs\n2. Keep transactions short — no external API calls inside txn\n3. Use snapshot isolation where appropriate\n4. Appropriate index reduces lock footprint\n\n**Architect:** Deadlocks indicate design issue — not just 'SQL problem.' Review transaction boundaries in application layer.",
      "Deadlocks bridge DBA and application architecture.",
      "Lock escalation? — Row locks → table lock — use `ROWLOCK` hints sparingly or partition.",
      "Application retry on 1205? — Standard pattern with max retries.",
      "Long transactions holding locks during HTTP calls",
      "Inconsistent table access order across services",
      "Ignoring deadlock graph in incident review"),
    q("Columnstore Indexes", "Analytics", "Common",
      "When use columnstore vs rowstore in SQL Server?",
      "Columnstore for analytical scans aggregating millions of rows (DW, reporting). Rowstore for OLTP point lookups and small range queries.",
      "**Columnstore:** Compresses columns, batch mode execution — 10x faster for aggregations. **NCCI** on OLTP for hybrid analytics.\n\n**Architect:** Separate reporting workload to read replica with columnstore vs mixing heavy analytics on OLTP primary.",
      "Right index type for workload separates OLTP from analytics architecture.",
      "CCI vs NCCI? — Clustered columnstore for DW fact tables; nonclustered on OLTP for selective analytics.",
      "Batch mode? — Vectorized execution — requires columnstore segment.",
      "Columnstore on tiny OLTP tables",
      "Heavy analytics on primary OLTP without replica",
      "No compression maintenance on columnstore"),
    q("Connection Pooling", ".NET + SQL", "Very Common",
      "How should .NET applications manage SQL Server connections?",
      "Always use connection pooling (default in SqlConnection). Pool per connection string. Set appropriate `Max Pool Size`, timeout, retry. Never open connection per row.",
      "**Architect standards:**\n- One connection string config via Key Vault\n- `Microsoft.Data.SqlClient` with AAD auth where possible\n- Polly retry for transient faults (error 40613, 40197, 40501)\n- `Min Pool Size` for warm pools on high-traffic APIs\n\n**Anti-pattern:** `Pooling=false` — exhausts SQL connections under load.",
      "Connection exhaustion takes down entire API farm.",
      "DbContext lifetime? — Scoped per request in ASP.NET — never singleton.",
      "MARS disabled why? — Multiple active result sets complicate pooling — usually off.",
      "New connection per query",
      "Singleton DbContext in web app",
      "No transient fault handling on Azure SQL"),
    q("SQL Server vs Azure SQL Decision", "Cloud", "Very Common",
      "When SQL Server on VM vs Azure SQL Database vs Managed Instance?",
      "Azure SQL DB: PaaS, single DB scale, serverless dev. Managed Instance: near 100% SQL Server compatibility, instance scope. VM: full control, licensing, legacy extensions.",
      "| Option | Best For |\n|--------|----------|\n| Azure SQL Database | New cloud-native apps, elastic scale |\n| SQL Managed Instance | Lift-and-shift needing linked server, agent |\n| SQL on VM | Legacy, custom extensions, full OS control |\n\n**Architect:** Start Azure SQL DB Hyperscale for large OLTP unless MI feature required. Document compatibility matrix in ADR.",
      "Cloud SQL choice affects ops burden and feature availability for years.",
      "Hyperscale when? — Large OLTP >4TB or fast scale requirements.",
      "DTU vs vCore? — vCore for production — predictable CPU/memory.",
      "SQL VM without HA configuration",
      "MI for simple new app — overkill",
      "Ignoring Azure SQL firewall/private endpoint"),
]

WEEK_8 = [
    q("PostgreSQL vs SQL Server", "Polyglot Persistence", "Very Common",
      "When would you choose PostgreSQL over SQL Server for a new .NET workload?",
      "PostgreSQL: open source, strong JSON (JSONB), extensions (PostGIS), cost on cloud. SQL Server: Windows ecosystem integration, enterprise tooling, team skill. Both excellent — decide on team, licensing, features.",
      "**PostgreSQL strengths:** JSONB for document hybrid, extensibility, lower cloud cost (RDS/Azure Flexible Server), strong standards compliance.\n\n**SQL Server strengths:** EF Core first-class, enterprise support, Always On maturity, SSIS/SSRS ecosystem.\n\n**Architect:** Polyglot persistence OK — use Postgres for new microservice if team skilled and JSON-heavy; don't force one DB for ideology.",
      "Polyglot choice is team + workload — not religion.",
      "JSONB indexing? — GIN index on JSONB path — flexible schema evolution.",
      "Npgsql with .NET? — Excellent provider; enable retry and pooling.",
      "Choosing DB without workload analysis",
      "Ignoring operational skill on team",
      "Two databases without clear bounded context ownership"),
    q("PostgreSQL Index Types", "Indexing", "Common",
      "What index types does PostgreSQL offer beyond B-tree?",
      "B-tree default. GIN/GiST for full-text and JSONB. BRIN for very large append-only tables. Hash for equality only (rare).",
      "**GIN:** JSONB containment, full-text search arrays.\n**BRIN:** Block Range INdex — tiny index for timestamp-ordered logs — 'find logs between T1 and T2.'\n**Partial index:** `WHERE status = 'active'` — smaller, faster.\n\nArchitect maps query pattern to index type — not all indexes are B-tree.",
      "Postgres index variety solves problems SQL Server uses different features for.",
      "EXPLAIN ANALYZE? — Always verify plan after index — Postgres optimizer differs from SQL Server.",
      "Index-only scan? — Covering index with INCLUDE equivalent via index all columns needed.",
      "B-tree only mentality",
      "No EXPLAIN on production-like data volumes",
      "Over-indexing write-heavy tables"),
    q("MVCC in PostgreSQL", "Concurrency", "Common",
      "How does PostgreSQL MVCC affect architecture and vacuum?",
      "Postgres uses MVCC — updates create new row versions; old dead tuples need VACUUM. Architects plan autovacuum tuning, connection pooling (PgBouncer), and monitor bloat.",
      "**Implications:**\n- Long transactions block vacuum — cause bloat and ID wraparound risk\n- `UPDATE`-heavy tables need vacuum monitoring\n- PgBouncer for connection pooling — Postgres doesn't pool like SQL Server internally\n\n**Architect:** Set `idle_in_transaction_session_timeout` on prod. Monitor `pg_stat_user_tables` n_dead_tup.",
      "MVCC maintenance is operational requirement — not optional DBA trivia.",
      "VACUUM FULL vs autovacuum? — FULL locks table — rare; autovacuum continuous.",
      "Table bloat symptoms? — Queries slow, disk grows — reindex or vacuum.",
      "Long open transactions in app servers",
      "No PgBouncer at hundreds of connections",
      "Ignoring autovacuum tuning on busy tables"),
    q("Read Replicas and Lag", "Scale", "Common",
      "Design read scaling with PostgreSQL replicas. How handle replication lag?",
      "Streaming replicas for read offload. App routes read-only queries to replica with lag tolerance. Critical reads hit primary. Monitor `replay_lag`.",
      "**Patterns:**\n- **CQRS:** write primary, read replica — accept seconds lag on catalog\n- **Sticky session:** user sees own writes on primary briefly\n- **Lag-aware routing:** if lag > 5s, route to primary\n\nAzure Database for PostgreSQL Flexible Server: up to 5 read replicas.",
      "Read replica lag is consistency architecture decision.",
      "Synchronous replica in Postgres? — Possible — impacts write latency — rare cross-region.",
      "Logical replication? — Selective table replication — upgrades, migrations.",
      "Assuming replica has zero lag",
      "Financial balance read from stale replica",
      "No lag monitoring alert"),
    q("JSONB for Schema Flexibility", "Document Store", "Common",
      "When use JSONB columns vs normalized tables in PostgreSQL?",
      "JSONB for evolving attributes, metadata, tenant-specific fields, event payloads. Normalize core entities with stable schema. GIN index on hot JSON paths.",
      "**Good JSONB:** product attributes varying by category, audit log details, config blobs.\n**Bad JSONB:** core relational data needing joins and constraints — use tables.\n\n**Architect:** Hybrid model — stable columns + `metadata JSONB` — avoids schema migration for every new attribute.",
      "Hybrid relational + JSON is modern Postgres sweet spot.",
      "Schema validation on JSONB? — `CHECK (jsonb_typeof)` or app-layer validation.",
      "JSONB vs separate NoSQL? — Postgres JSONB avoids second database if queries simple.",
      "Everything in JSONB — lose constraints",
      "No index on queried JSON paths",
      "Large JSONB blobs in hot rows"),
    q("Redis with PostgreSQL", "Caching", "Very Common",
      "Design caching layer in front of PostgreSQL.",
      "Cache-aside with Redis: read cache → miss → Postgres → populate. Invalidate on write. TTL for eventual consistency. Session cache separate from entity cache.",
      "**Keys:** `product:{id}`, `user:{id}:profile`. **TTL:** 5-60 min based on change frequency.\n\n**Stampede:** lock per key on miss. **Invalidation:** publish/subscribe on update or explicit delete.\n\nArchitect: Redis is not durable primary store — Postgres remains source of truth.",
      "Cache + RDBMS is standard architect pattern.",
      "Cache aside vs write-through? — Aside simpler; write-through for strict consistency needs.",
      "Redis Cluster for HA? — Shard when single node memory exceeded.",
      "Cache without invalidation strategy",
      "Redis as only copy of critical data",
      "Same TTL for all entity types"),
    q("Database Migration Strategy", "Migrations", "Common",
      "How do you run zero-downtime schema migrations with PostgreSQL?",
      "Expand-contract: add nullable column → dual write → backfill → add constraint → remove old. Tools: Flyway, Liquibase, EF migrations with review.",
      "**Never:** rename column in one deploy without compatibility layer.\n**Always:** backward-compatible migrations — old app version must work during rolling deploy.\n\n**Architect:** Migration pipeline in CI with review for locking operations (`ADD COLUMN DEFAULT` on huge table locks — use no-default add, backfill, then default).",
      "Schema migration strategy enables continuous deployment.",
      "Concurrent index create? — `CREATE INDEX CONCURRENTLY` — no write lock.",
      "EF migrations in prod? — OK with SQL review — auto migrations risky at scale.",
      "Breaking schema change in single release",
      "Migration locks table during Black Friday",
      "No rollback plan for failed migration"),
    q("Connection Pooling with PgBouncer", "Operations", "Common",
      "Why PgBouncer for PostgreSQL in production?",
      "Postgres uses process-per-connection — 500 connections expensive. PgBouncer multiplexes many client connections to fewer server connections.",
      "**Modes:** transaction pooling most common for web apps — connection returned after transaction.\n\n**Architect:** Place PgBouncer between app tier and Postgres (or use managed pooler). Size `max_connections` on Postgres conservatively.",
      "Connection pooling is mandatory at scale — not optional.",
      "Transaction vs session pooling? — Session breaks prepared statements sometimes — test.",
      "ORM prepared statements? — May conflict with transaction pooling — disable or use session mode.",
      "Thousands of connections direct to Postgres",
      "No pooler on serverless burst workloads",
      "Connection leak in application code"),
    q("Polyglot Persistence Pattern", "Architecture", "Very Common",
      "Design data layer with SQL Server, PostgreSQL, and Redis for e-commerce.",
      "SQL Server: orders/transactions (team skill + ACID). PostgreSQL: product catalog (JSONB attributes). Redis: cart, sessions, hot product cache. Each store owns its bounded context.",
      "**Integration:** Events sync catalog changes to cache. Order service never JOINs product DB — API or cached snapshot.\n\n**Architect:** Document data ownership per service. Avoid shared database antipattern.",
      "Polyglot is about bounded context — not collecting databases.",
      "Eventual consistency between stores? — Accept lag on catalog display vs order snapshot at checkout.",
      "Saga across SQL and Redis? — Compensate carefully — Redis not transactional with SQL.",
      "Shared database across microservices",
      "JOIN across Postgres and SQL Server",
      "No cache invalidation on product update"),
    q("CAP and Postgres HA", "Distributed", "Common",
      "How does PostgreSQL HA relate to CAP theorem?",
      "Primary-replica async replication — partition or failover gives AP with potential data loss (RPO>0). Sync replica gives CP within cluster at latency cost.",
      "**Patroni / cloud HA:** Automatic failover promotes replica. **Split brain:** use etcd consensus for leader election.\n\nArchitect documents RPO/RTO per tier — payments sync replica; analytics async OK.",
      "HA mode is CAP trade-off made concrete.",
      "Quorum requirement? — Odd number of nodes for etcd/Patroni.",
      "Manual failover runbook? — Even with auto failover — document verification steps.",
      "Assuming auto failover means zero data loss",
      "No split-brain protection",
      "Single AZ Postgres for production payments"),
]

# Import continues - WEEK_21 through WEEK_36 in same file for apply script

WEEK_21 = [
    q("CAP Theorem in Practice", "Fundamentals", "Very Common",
      "Explain CAP and how it applies to choosing between SQL, Redis, and Cassandra.",
      "During partition, choose C or A. All distributed systems need P. SQL with sync replica: CP. Redis cluster with async: AP. Cassandra tunable — often AP with eventual consistency.",
      "CAP is not 'pick two of three always' — it's 'during partition, C or A.'\n\n**Examples:**\n- Bank transfer: CP — reject if cannot verify consistency\n- Product view count: AP — approximate OK\n- Shopping cart in Redis: AP — merge on reconnect\n\nArchitect maps each datastore in design to CAP stance and documents business acceptance of inconsistency.",
      "CAP literacy separates architects from developers who treat all DBs as equal.",
      "PACELC extension? — Else Latency vs Consistency — even without partition.",
      "Does Cosmos DB beat CAP? — Tunable consistency — still trade-offs exist.",
      "Claiming 'we are CA' for distributed system",
      "Same consistency model for ledger and analytics",
      "Ignoring partition in multi-region design"),
    q("Idempotency Keys", "Reliability", "Very Common",
      "Design idempotent payment API. What can go wrong without it?",
      "Client sends `Idempotency-Key` UUID. Server stores key → response mapping 24h. Retry returns cached response without double charge. Without it: network timeout → client retry → double payment.",
      "**Implementation:**\n```\nPOST /payments\nIdempotency-Key: 550e8400-e29b-41d4-a716-446655440000\n```\nStore in Redis or SQL with unique constraint on key. Process payment in transaction with key insert — duplicate key returns original result.\n\n**Architect:** Mandate for all non-idempotent POST from mobile clients (unreliable networks).",
      "Idempotency is financial-system hygiene — interview favorite.",
      "Same key different body? — Return 422 conflict — key reused incorrectly.",
      "Stripe idempotency window? — 24 hours — industry standard reference.",
      "Only client-side dedup without server store",
      "GET requests with side effects",
      "Idempotency key in URL logged in access logs"),
    q("Saga Pattern", "Transactions", "Very Common",
      "Design order checkout saga across inventory, payment, shipping.",
      "Choreography: OrderPlaced event → Inventory reserves → Payment charges → Shipping schedules. Compensation: PaymentFailed → release inventory. Orchestration: central coordinator if logic complex.",
      "**Steps:**\n1. Reserve inventory (TTL 15 min)\n2. Charge payment (idempotent)\n3. Confirm order\n4. On failure: compensate in reverse order\n\n**Orchestration (Durable Functions):** visible state, easier debug. **Choreography:** looser coupling, harder trace.\n\nNever 2PC across microservices — sagas with compensation instead.",
      "Distributed transactions without XA is core microservices architecture.",
      "Saga vs 2PC? — 2PC blocks on failure; saga compensates — eventual consistency.",
      "Orchestration when? — 6+ steps or complex compensation logic.",
      "Sync chain without compensation plan",
      "Distributed 2PC across three services",
      "No idempotency on saga steps"),
    q("Outbox Pattern", "Messaging", "Very Common",
      "Why transactional outbox instead of publish after SaveChanges?",
      "Dual-write problem: DB commits, message publish fails (or reverse) — inconsistent state. Outbox writes event in same transaction; relay publishes asynchronously.",
      "**Flow:**\n1. BEGIN TRANSACTION\n2. INSERT order + INSERT outbox_event\n3. COMMIT\n4. Relay polls outbox → publishes to Service Bus → marks processed\n\nDebezium CDC alternative for high volume. Architect chooses polling outbox for simplicity or log-based for scale.",
      "Outbox is the correct answer for reliable event publishing from OLTP DB.",
      "At-least-once delivery? — Consumers must be idempotent — pair outbox with idempotent handlers.",
      "Inbox pattern? — Dedup incoming messages — complement outbox.",
      "Fire-and-forget after SaveChangesAsync",
      "No duplicate detection on consumer",
      "Outbox relay single point without HA"),
    q("Eventual Consistency UX", "Consistency", "Common",
      "User complains 'I paid but order still shows pending.' How design for this?",
      "Async pipeline causes visible lag. UX: optimistic UI with rollback, status polling, email confirmation as source of truth, 'processing' state not 'failed.'",
      "**Technical:** Read-your-writes via sticky session to primary or short TTL cache invalidation after write.\n\n**Product:** Set expectation — 'Payment processing, refresh in 30 seconds.'\n\nArchitect aligns consistency model with user mental model — don't promise instant if pipeline is async.",
      "Consistency is UX problem as much as technical.",
      "Strong consistency when needed? — Sync read from primary for order status page only.",
      "WebSocket for status? — Push update when saga completes — better UX than polling.",
      "Showing failed before saga timeout",
      "Reading stale replica for own transaction",
      "No correlation ID for support lookup"),
    q("Quorum and Leader Election", "Consensus", "Occasional",
      "Why do distributed systems need odd-numbered quorum nodes?",
      "Quorum (n/2+1) prevents split brain — two partitions cannot both elect leader. Even nodes risk tie; odd (3, 5) ensures majority on one side.",
      "**Examples:** etcd for K8s, Redis Sentinel, ZooKeeper, Patroni for Postgres.\n\n**Architect:** When evaluating HA product, ask 'how does it prevent split brain?' — not just 'is it HA?'",
      "Consensus underpins every HA claim.",
      "Split brain consequence? — Dual writes corrupt data — worse than downtime.",
      "Witness node? — Cloud blob witness for 2-node SQL AG quorum.",
      "Two-node cluster without witness",
      "Ignoring fencing during failover",
      "Assuming automatic HA means no split brain risk"),
    q("Clock Skew and Ordering", "Time", "Occasional",
      "Why can't you rely on wall-clock timestamps for event ordering?",
      "NTP skew between servers — events appear out of order. Use logical clocks (Lamport), vector clocks, or database-assigned monotonic sequence.",
      "**Solutions:**\n- Database `rowversion`/sequence for ordering\n- Kafka partition ordering per key\n- Hybrid logical clocks (CockroachDB)\n\n**Architect:** Never sort distributed events by `DateTime.UtcNow` from different machines for correctness.",
      "Time is unreliable in distributed systems — plan ordering explicitly.",
      "Lamport timestamp? — causal ordering without synchronized clocks.",
      "TTL based on local clock? — Skew causes early expiry — use server authority.",
      "Cross-machine timestamp sort for audit trail",
      "No monotonic ID generator",
      "Assuming NTP perfect in cloud"),
    q("Backpressure", "Resilience", "Common",
      "Consumer cannot keep up with producer — architectural responses?",
      "Backpressure: slow producer, buffer with bounds, scale consumers, drop/dead-letter low priority, circuit break upstream.",
      "**Patterns:**\n- Reactive Streams `request(n)` flow control\n- KEDA scale consumers on queue depth\n- Bounded channel — block producer when full\n\n**Architect:** Unbounded queue = memory bomb — always bound buffers and alert on lag.",
      "Backpressure prevents cascade overload.",
      "Kafka consumer lag alert? — Primary scaling signal.",
      "Drop vs delay? — Business decision — payments delay, metrics may drop.",
      "Unbounded in-memory queue",
      "Scale producer without consumer",
      "No DLQ for poison messages"),
    q("Exactly-Once Semantics", "Messaging", "Common",
      "Is exactly-once delivery possible in distributed systems?",
      "True exactly-once end-to-end is impossible — achieve effectively-once via idempotent consumers + dedup + transactional outbox. Kafka EOS within stream processing scope.",
      "**Practical:** At-least-once delivery + idempotent handler + business key dedup = effectively once.\n\n**Architect:** Design for at-least-once; make handlers idempotent. Don't pay complexity cost of EOS unless Kafka streams with specific semantics needed.",
      "Honest semantics answer impresses principals.",
      "Kafka exactly-once? — Producer idempotence + transactions within Kafka — not across DB without outbox.",
      "Distributed transaction across Kafka and DB? — Outbox pattern — not XA.",
      "Claiming exactly-once without idempotent consumers",
      "No dedup store",
      "Ignoring duplicate in financial handlers"),
    q("Failure Detection and Heartbeats", "Reliability", "Common",
      "How do systems detect failed nodes? Gossip vs heartbeat?",
      "Heartbeat: central coordinator or health checks at interval. Gossip: nodes exchange state probabilistically (Cassandra, Consul). Missed heartbeats → suspect → failed → failover.",
      "**Architect settings:**\n- Health check interval vs failover time trade-off\n- False positive failover worse than slow detection sometimes\n- Synthetic monitoring from user perspective\n\nK8s: liveness vs readiness probes — different purposes.",
      "Failure detection tuning affects availability and false failover.",
      "Phi accrual failure detector? — Adaptive timeout — used in Akka.",
      "Flapping node? — Hysteresis — require N failed checks before failover.",
      "No health checks on dependencies",
      "Liveness probe includes DB — kills pod on DB blip",
      "Too aggressive failover causes oscillation"),
]

# WEEK_22-24, 33-36 - I'll add condensed but still premium quality

WEEK_22 = [
    q("Service Decomposition", "Decomposition", "Very Common",
      "How do you decompose a monolith into microservices?",
      "Identify bounded contexts via domain events and team structure. Extract highest-value, lowest-coupling module first. Strangler fig routing. Avoid big-bang.",
      "Use Event Storming or domain workshops. Score candidates: deployment frequency pain, scale mismatch, team boundary alignment.\n\nFirst extraction often: notification, catalog, or payment — clear boundaries.\n\nKeep monolith data accessible via API during transition — don't big-bang database split.",
      "Decomposition strategy is top microservices interview question.",
      "Monolith first? — Modular monolith validates domain before distributed ops complexity.",
      "Shared library vs service? — Share domain types cautiously — prefer API contracts.",
      "Split by technical layer (API service, DB service)",
      "Microservices day one for 3 developers",
      "No strangler — big bang rewrite"),
    q("API Gateway Pattern", "Gateway", "Very Common",
      "What belongs in API gateway vs microservices?",
      "Gateway: TLS, auth, rate limit, routing, request ID, CORS. Services: domain logic, validation, data access.",
      "Azure APIM policies: validate JWT, throttle, cache GET responses, route `/api/orders/*`.\n\nDon't put business rules in gateway — drifts from services, untestable domain logic at edge.",
      "Gateway is cross-cutting edge — not second business layer.",
      "Gateway aggregation? — GraphQL or BFF sometimes better than fat gateway.",
      "mTLS at gateway? — Terminate TLS at gateway or pass-through — compliance decision.",
      "Business validation in APIM policy",
      "Gateway becomes god object",
      "No rate limiting on public endpoints"),
    q("Database Per Service", "Data", "Very Common",
      "Explain database-per-service and reporting challenge.",
      "Each service owns schema — no cross-DB FK. Reporting via data warehouse fed by events or CDC.",
      "Order service: Order DB. Inventory: Inventory DB. Join in application via API or denormalized read model.\n\nAnalytics: Azure Synapse / Snowflake ingests domain events nightly.",
      "Data ownership enables independent deploy.",
      "Shared database antipattern? — Hidden monolith — coupling at schema level.",
      "CDC for reporting? — Debezium streams changes to warehouse.",
      "Distributed JOIN across service DBs",
      "Reporting queries on OLTP primary",
      "Shared tables between teams"),
    q("Sync vs Async Communication", "Communication", "Very Common",
      "When HTTP sync vs message async between services?",
      "Sync when user waits (get order total). Async for side effects (email, analytics). Max 2-3 sync hops.",
      "Checkout: sync payment authorization. Post-order: async notification, inventory sync, search index update.\n\nCircuit breaker + timeout on every sync call.",
      "Communication choice defines latency and resilience.",
      "Request-response over Kafka? — Anti-pattern — use HTTP or true async events.",
      "Timeout values? — Shorter than client timeout — fail fast with fallback.",
      "6-service sync chain for page load",
      "Async without dead letter queue",
      "No timeout on HttpClient"),
    q("Circuit Breaker", "Resilience", "Very Common",
      "Implement circuit breaker for inventory service calls.",
      "After failure threshold, open circuit — fail fast. Half-open test request. Polly in .NET HttpClient factory.",
      "Configure per dependency — payment stricter than recommendations.\n\nPair with fallback: cached catalog, degraded mode banner.\n\nMonitor circuit state metric — alert when open.",
      "Resilience patterns are architect checklist items.",
      "Bulkhead with circuit breaker? — Isolate thread pools per downstream.",
      "Retry with circuit open? — Don't retry when open — wastes resources.",
      "Circuit breaker without monitoring",
      "Infinite retry on 500 errors",
      "Same policy for all dependencies"),
    q("BFF Pattern", "API Design", "Common",
      "Mobile app needs aggregated homepage. BFF or generic API?",
      "BFF per client type — MobileBFF aggregates 3 calls into one payload shaped for mobile screens.",
      "Web BFF and Mobile BFF separate — different data needs. BFF calls microservices server-side — reduces client chattiness.\n\nDon't let BFF become monolith — thin orchestration only.",
      "BFF solves client-specific API shape problem.",
      "GraphQL vs BFF? — GraphQL flexible queries; BFF explicit endpoints — team skill trade-off.",
      "BFF auth? — BFF holds service-to-service tokens — not exposed to mobile.",
      "One API for web and mobile forever",
      "Mobile calls 15 microservices directly",
      "Fat BFF with domain logic"),
    q("Contract Testing", "Testing", "Common",
      "How ensure payment service change doesn't break order service?",
      "Consumer-driven contracts (Pact): order service defines expected payment API contract; CI verifies payment provider satisfies it.",
      "Complement with smoke E2E — don't rely on E2E alone — slow and flaky at scale.\n\nVersion APIs — breaking changes require contract major version bump.",
      "Contract tests enable independent deploy.",
      "Pact broker? — Central contract repository — CI gate on publish.",
      "Backward compatibility rule? — Additive changes only in minor version.",
      "E2E only integration testing",
      "Breaking API without version bump",
      "No consumer notification on contract change"),
    q("Service Mesh When", "Infrastructure", "Occasional",
      "When adopt Istio/Linkerd service mesh?",
      "15+ services needing uniform mTLS, traffic splitting, observability without library instrumentation in every app.",
      "Cost: sidecar memory, operational complexity. Start with Polly + centralized logging for <10 services.\n\nMesh wins: polyglot services, canary by percentage, zero-trust east-west.",
      "Mesh is infrastructure decision with ops cost.",
      "Sidecar latency? — ~1-2ms per hop — measure at your scale.",
      "Mesh without observability backend? — Telemetry needs destination.",
      "Mesh for 3-service system",
      "No team to operate Istio",
      "Ignoring sidecar resource cost"),
    q("Strangler Fig Migration", "Migration", "Very Common",
      "Migrate order module from .NET monolith to microservice.",
      "Proxy routes `/api/orders/*` to new service; monolith handles rest. Gradually move endpoints. Shared DB initially OK — then split schema.",
      "Phase 1: new service wraps same DB tables (pragmatic). Phase 2: split schema. Phase 3: retire monolith path.\n\nFeature flags control traffic percentage to new service.",
      "Strangler reduces migration risk.",
      "Anti-corruption layer? — Translate monolith models to new domain model at boundary.",
      "Rollback plan? — Route 100% back to monolith via proxy config.",
      "Big bang cutover on Friday",
      "No traffic shadowing before cutover",
      "Delete monolith before parity verified"),
    q("Microservices Anti-Patterns", "Anti-Patterns", "Common",
      "Name three microservices anti-patterns you've seen.",
      "Distributed monolith (deploy together, shared DB). Chatty microservices (20 calls per page). Nano-services (network overhead dominates).",
      "**Detection:** Cannot deploy service alone; integration tests need all services; p99 dominated by network not work.\n\n**Fix:** Merge services, add BFF aggregation, or consolidate boundaries.",
      "Naming anti-patterns shows production experience.",
      "Gold plating? — Kubernetes for team of 3.",
      "Smart endpoints dumb pipes? — Domain logic in services not ESB.",
      "Microservices for resume",
      "No correlation ID across calls",
      "Shared ORM models across services"),
]

# Continue WEEK_23, 24, 33-36 in compact premium form - still hand crafted

WEEK_23 = [
    q("Bounded Context", "DDD", "Very Common",
      "What is a bounded context? Example in e-commerce.",
      "'Customer' differs in Sales (buyer), Support (ticket submitter), Shipping (recipient). Separate models, integrate via events or ACL.",
      "Bounded context = linguistic boundary where domain terms have precise meaning. Map to microservice or module boundary.\n\nContext map documents relationships: upstream/downstream, conformist, anti-corruption layer.",
      "DDD vocabulary is architect interview language.",
      "Ubiquitous language? — Same terms in code, docs, and conversation with domain experts.",
      "Shared kernel? — Small shared model between contexts — use sparingly.",
      "One enterprise data model for everything",
      "Anemic domain — logic in services not entities",
      "Context boundaries follow org chart only"),
    q("Aggregate and Consistency Boundary", "DDD", "Very Common",
      "What is an aggregate root? Why one transaction per aggregate?",
      "Cluster of entities updated atomically — Order + OrderLines. Root (Order) is only entry point. One transaction per aggregate — cross-aggregate eventual consistency.",
      "Order aggregate: add line, recalculate total, raise OrderLineAdded domain event — all in one transaction.\n\nReference other aggregates by ID only — not object reference across boundaries.",
      "Aggregate rules prevent distributed lock nightmares.",
      "Aggregate size? — Small — large aggregates cause contention — split if needed.",
      "Domain events from aggregate? — Raise on state change — persist in same transaction (outbox).",
      "Transaction spanning Order and Customer aggregates",
      "Direct entity references across aggregates",
      "God aggregate with 50 child entities"),
    q("Ubiquitous Language", "DDD", "Common",
      "How do architects enforce ubiquitous language?",
      "Code names match business terms. Glossary in wiki. PR reviews reject technical jargon replacing domain terms. Event names = business language.",
      "`PlaceOrder` not `ProcessOrderDto`. `Money` not `decimal amount`.\n\nWorkshop with domain experts quarterly — refine language.",
      "Language alignment reduces bugs between business and engineering.",
      "Anti-corruption layer naming? — Translate external terms at boundary only.",
      "Bounded context glossary? — Per-context wiki page linked from repo.",
      "Database column `fld_amt_1`",
      "Different terms in UI vs API vs database",
      "Developers never talk to domain experts"),
    q("Domain Events", "DDD", "Very Common",
      "Domain event vs integration event?",
      "Domain event: something happened in model (OrderPlaced) — in-process first. Integration event: cross-service message on bus — published after commit via outbox.",
      "OrderPlaced → handler sends email (in-process). Same event → outbox → Service Bus → Inventory service (integration).\n\nDon't leak integration concerns into domain layer.",
      "Event distinction keeps domain pure.",
      "Event sourcing? — Store events as source of truth — different pattern — high complexity.",
      "Event version evolution? — Additive schema — `version` field.",
      "Synchronous email in same transaction as order",
      "Domain event with HTTP call inside handler",
      "No distinction domain vs integration events"),
    q("Anti-Corruption Layer", "DDD", "Common",
      "Integrate legacy ERP with new order service using ACL.",
      "ACL translates ERP XML/API to domain commands. New service never imports ERP models.",
      "Adapter module: `ErpOrderAdapter` maps `ERP_SALES_ORDER_42` → `PlaceOrderCommand`.\n\nIsolate legacy ugliness — replace ERP without rewriting domain.",
      "ACL is migration pattern architects specify.",
      "When skip ACL? — Greenfield with no legacy — direct API.",
      "ACL testing? — Contract tests against ERP sandbox responses.",
      "ERP DTOs in domain layer",
      "Direct SQL to legacy DB from new service",
      "No translation layer documented"),
    q("CQRS in DDD", "DDD", "Common",
      "When apply CQRS in bounded context?",
      "Read model differs from write model — different scale, shape, or optimization. Commands mutate aggregates; queries hit read DB or projection.",
      "Write: Order aggregate in SQL. Read: denormalized OrderSummary in Redis or read replica optimized for list screens.\n\nStart logical CQRS (separate handlers) before separate databases.",
      "CQRS solves read/write mismatch — not default pattern.",
      "Eventual consistency on read model? — Accept lag — show 'updating' in UI.",
      "Projection rebuild? — Replay events from event store — disaster recovery.",
      "CQRS on day one for CRUD admin",
      "Separate DB without migration plan",
      "Write model returned on complex read query"),
    q("Context Mapping", "DDD", "Common",
      "Explain upstream/downstream and conformist in context map.",
      "Downstream conforms to upstream model or uses ACL. Upstream has power — downstream adapts.",
      "Payment (upstream) publishes PaymentCompleted — Order (downstream) conforms or translates via ACL.\n\nDocument on context map diagram — prevents implicit coupling.",
      "Context maps are architect deliverables in DDD initiatives.",
      "Partnership? — Two contexts evolve together — rare — needs coordination.",
      "Open host service? — Published language for integrators — API as product.",
      "No documented context relationships",
      "Downstream forces upstream model change",
      "Shared database between contexts"),
    q("Event Storming", "DDD", "Common",
      "What is event storming and what artifacts does it produce?",
      "Workshop: domain experts + engineers stick orange (events), blue (commands), yellow (aggregates) on wall. Produces bounded contexts, process flows, hot spots.",
      "Run before microservice split. Output: candidate services, integration events, unresolved policy questions.\n\nArchitect facilitates — not passive attendee.",
      "Event storming is discovery — not design silver bullet.",
      "Remote event storming? — Miro boards — works with facilitation discipline.",
      "Hot spot (pink)? — Unclear policy or contention — resolve before coding.",
      "Skip discovery — code first",
      "Only developers in room",
      "No follow-up ADR from storming"),
    q("Anemic Domain Model", "Anti-Pattern", "Common",
      "Detect and fix anemic domain model.",
      "Entities are data bags; all logic in `OrderService` 2000 lines. Fix: move behavior to entities/value objects; application layer orchestrates.",
      "`order.Confirm()` not `orderService.SetStatus(order, Confirmed)`. Rich domain catches invalid transitions inside aggregate.",
      "Anemic model leads to god services — architect review red flag.",
      "When anemic OK? — Integration DTOs and read models — not core domain.",
      "DDD tactical patterns effort? — Worth it in core domain only — not CRUD edges.",
      "Public setters on all entity properties",
      "Validation only in API controller",
      "OrderService knows all other domains"),
    q("DDD and Microservices Alignment", "Strategy", "Very Common",
      "Does every bounded context become a microservice?",
      "No — modular monolith with clear boundaries first. Microservice when independent deploy, scale, or team need justifies ops cost.",
      "Start: bounded contexts as .NET projects in one solution. Extract when pain real.\n\nConway's Law: service boundaries should align with team boundaries.",
      "Pragmatic DDD — not distributed everything.",
      "Monolith modular structure? — `Ordering.Domain`, `Billing.Domain` projects.",
      "Team topologies? — Stream-aligned team per core context.",
      "10 microservices for 4 developers",
      "Bounded context = database table",
      "No integration strategy between contexts"),
]

WEEK_24 = [
    q("Capstone Architecture Review", "Capstone", "Very Common",
      "Present your microservices e-commerce capstone in 10 minutes.",
      "Structure: problem (2m), context diagram (3m), key ADRs — decomposition, saga, data (3m), failure modes (2m).",
      "Cover: bounded context map, sync vs async choices, idempotency, observability (trace ID), deployment independence proof.",
      "Capstone presentation is interview simulation.",
      "What if interviewer challenges service count? — Defend with scale and team drivers or concede merge.",
      "Cost estimate? — Order of magnitude monthly cloud cost.",
      "No failure scenarios",
      "Diagram without legend",
      "Cannot explain why 8 services not 3"),
    q("Saga Compensation Design", "Sagas", "Very Common",
      "Payment succeeds, shipping fails — compensate?",
      "Compensating transaction: refund payment (idempotent refund API), release inventory, mark order cancelled. Log compensation steps for audit.",
      "Each saga step has defined compensator. Compensators must be idempotent too — retry safe.\n\nManual intervention queue for compensation failure — human workflow.",
      "Compensation design is where sagas succeed or fail.",
      "Poison saga state? — Persist saga state machine — Durable Functions or custom table.",
      "Timeout on saga step? — Trigger compensation automatically.",
      "No compensation for payment step",
      "Hope shipping never fails",
      "Non-idempotent refund handler"),
    q("Observability Across Services", "Observability", "Very Common",
      "Trace order request across 5 microservices.",
      "W3C trace context propagation on HTTP and messages. Single trace ID in logs. OpenTelemetry → App Insights/Jaeger.",
      "Every service adds span: order-api, payment, inventory. Dashboard: p99 per hop — find slow service.\n\nArchitect mandates OTel SDK in service template.",
      "Distributed tracing is non-negotiable for microservices.",
      "Baggage attributes? — Pass tenantId on trace for filtering.",
      "Log correlation without tracing? — Insufficient at scale — use traces.",
      "No trace ID in logs",
      "Broken trace at message bus boundary",
      "Each service different logging format"),
    q("Independent Deployment Proof", "DevOps", "Common",
      "How prove services deploy independently?",
      "Separate CI/CD pipeline per repo/service. Deploy order v2 without touching catalog. Contract tests gate breaking changes.",
      "Versioned API — consumers pin compatibility. Feature flags decouple deploy from release.\n\nDemonstrate in capstone: GitHub Actions workflow per service.",
      "Independent deploy is defining microservices characteristic.",
      "Shared pipeline monolith? — Red flag for distributed monolith.",
      "Database migration blocks all services? — Coupled deploy — fix boundaries.",
      "Monorepo single deploy button for all",
      "Shared DB migration coupling",
      "No contract tests"),
    q("Data Consistency Across Services", "Data", "Very Common",
      "Customer updates address — order history shows old address?",
      "Snapshot address on order at placement time — don't JOIN live customer for historical orders. Eventual sync for display-only views.",
      "Order aggregate stores `ShippingAddress` value object at confirm — immutable history.\n\nCustomer service owns current address — orders own snapshot.",
      "Temporal consistency is business rule — architect clarifies with stakeholders.",
      "Event-carried state transfer? — Include needed fields in event payload.",
      "Read model projection lag? — Accept for catalog; not for financial snapshot.",
      "Live JOIN customer address on old orders",
      "No snapshot on transactional records",
      "Assuming strong consistency everywhere"),
    q("API Versioning Strategy", "API Design", "Common",
      "Version microservices APIs without breaking consumers.",
      "URL `/v1/` or header `Api-Version`. Deprecation policy: 6 months notice. Additive changes in minor; breaking in major.",
      "Document in consumer portal. Automated breaking change detection in CI against Pact contracts.",
      "API lifecycle governance prevents consumer breakage.",
      "GraphQL schema deprecation? — `@deprecated` directive — similar lifecycle.",
      "Parallel run v1 and v2? — Route traffic gradually — strangler for APIs.",
      "Breaking change without version bump",
      "Unlimited backward compatibility burden",
      "No deprecation timeline"),
    q("Security East-West Traffic", "Security", "Common",
      "Secure service-to-service communication.",
      "mTLS via service mesh OR managed identity + private network. Never basic auth over HTTP internal.",
      "Azure: Managed Identity service A calls service B with token. Private Link — no public endpoints.\n\nValidate JWT or mTLS on every internal call — zero trust.",
      "Internal network not trusted — architect assumes breach.",
      "Service principal per service? — Least privilege — not shared SP.",
      "Network policy K8s? — Deny all default — allowlist per namespace.",
      "HTTP internal without TLS",
      "Shared API key all services",
      "Public endpoints for internal APIs"),
    q("Load Test Microservices Platform", "Performance", "Common",
      "How load test microservices vs monolith?",
      "Test each service SLO independently plus critical user journeys E2E. Chaos inject downstream failure during load.",
      "k6 scenarios: checkout journey 5K RPS. Monitor per-service CPU, p99, error rate, queue depth.\n\nFind bottleneck service — scale or optimize that hop.",
      "Load test proves architecture claims.",
      "Soak test? — 24h run — memory leak detection.",
      "Chaos during load? — Validate circuit breakers under real traffic shape.",
      "Only test monolith entry point",
      "No downstream failure injection",
      "Ignore queue backlog metric"),
    q("When to Merge Services Back", "Pragmatism", "Occasional",
      "Signs microservices should be merged?",
      "Always deployed together, chatty sync calls, shared DB, team same standup, network latency > compute time.",
      "Merge into modular monolith or single service — reduce ops overhead.\n\nArchitect ego must not prevent re-merge when boundaries wrong.",
      "Pragmatism impresses senior interviewers.",
      "Reverse strangler? — Route back to monolith module — valid.",
      "Metrics to decide? — Deploy coupling score, call ratio, cost per transaction.",
      "Never merge — ideology",
      "Ignore ops cost of tiny services",
      "Nano-service per endpoint"),
    q("Month 6 Readiness Checklist", "Career", "Common",
      "What proves readiness after microservices month?",
      "Bounded context map, saga diagram, 3 ADRs, capstone presented, Microservices Top 50 ≥75%, lab 21-24 complete, trace demo recorded.",
      "Self-assess: can whiteboard checkout saga with compensation in 15 minutes? Can defend service boundaries to skeptical principal?",
      "Readiness is demonstrable artifacts — not videos watched.",
      "Weakest area? — Log in progress tracker — revisit week.",
      "Mock interview? — mock-05 checkout design.",
      "No hands-on lab completed",
      "Cannot draw context map from memory",
      "Only theoretical microservices knowledge"),
]

# Weeks 33-36 - System Design focus

WEEK_33 = [
    q("RESHADED Framework", "Methodology", "Very Common",
      "Walk through RESHADED for system design interviews.",
      "Requirements, Estimation, Storage, High-level design, API, Deep dive, Edge cases, Deployment. Never skip requirements — interviewers withhold info to test clarification.",
      "Spend 5 min on functional + NFR: scale, latency, durability, consistency, geographic distribution.\n\nWrite assumptions on board. State what you defer (e.g., 'security detail in deep dive if time').",
      "Framework discipline prevents premature diagramming.",
      "RESHADED vs C4? — RESHADED for timed interview; C4 for documentation.",
      "Time check at 20 min? — Must enter deep dive — don't over-detail early components.",
      "Jumping to microservices diagram in minute 2",
      "No numbers in estimation",
      "Silent design without thinking aloud"),
    q("Requirements Clarification", "Requirements", "Very Common",
      "What questions ask before designing Twitter feed?",
      "Read/write ratio, fan-out model, celebrity users, latency SLA, consistency, media support, delete/edit, follower count limits.",
      "Miss celebrity user problem → naive fan-out-on-write fails. Ask: 'Max followers per user? Read timeline latency target? Consistent global ordering needed?'",
      "Requirements questions differentiate senior candidates.",
      "MVP scope? — Explicitly defer analytics, ads — focus core feed.",
      "DAU vs MAU? — Drives estimation — clarify.",
      "Assume requirements without asking",
      "Over-engineer features not requested",
      "Ignore read/write asymmetry"),
    q("Back-of-Envelope Estimation", "Estimation", "Very Common",
      "Estimate storage for 100M users, 2 tweets/day, 280 chars, 5 years.",
      "100M × 2 × 365 × 5 = 365B tweets. ~300 bytes/tweet with metadata ≈ 110TB raw before replication and indexes. 3x replication ≈ 330TB.",
      "Show math on board. Round aggressively. State assumptions: average text length, metadata overhead, media excluded.\n\nQPS: 100M DAU × 2 / 86400 ≈ 2300 write QPS average, peak 5×.",
      "Estimation proves engineering judgment.",
      "Bandwidth estimate? — Write QPS × payload size — CDN for media separate.",
      "Index overhead? — 2-3x storage — mention.",
      "No assumptions stated",
      "Exact precision false confidence",
      "Forget replication factor"),
    q("API Design in System Design", "API", "Common",
      "Design REST API for URL shortener.",
      "`POST /v1/urls` {longUrl, customAlias?} → {shortCode}. `GET /{shortCode}` → 301 redirect. `DELETE /v1/urls/{code}` auth. Rate limit headers.",
      "Idempotent POST with Idempotency-Key for create. Version in path. ProblemDetails errors.\n\nConsider internal vs public API separation.",
      "API sketch shows you can ship not just diagram boxes.",
      "302 vs 301 redirect? — 301 permanent — analytics implications.",
      "Custom alias collision? — 409 Conflict — unique constraint.",
      "RPC-style random verbs",
      "No error response design",
      "Missing rate limit discussion"),
    q("High-Level Diagram Discipline", "Communication", "Common",
      "How draw effective whiteboard architecture diagram?",
      "Left: clients. Center: LB, API, cache, DB. Right: async workers. Label protocols. Legend for symbols. One box per logical component first — refine in deep dive.",
      "Avoid 20 boxes minute one. Show data flow arrows with read vs write path different colors if possible.\n\nName technologies after logical design approved: 'cache' then 'Redis'.",
      "Clear diagrams communicate faster than words in interview.",
      "Single diagram overload? — High-level first — zoom deep dive second diagram.",
      "Bidirectional arrows everywhere? — Label read vs write paths.",
      "Technology logos before logical design",
      "Unreadable tiny boxes",
      "No legend"),
    q("Deep Dive Selection", "Strategy", "Common",
      "Interviewer says 'deep dive any component.' Which pick?",
      "Pick bottleneck or most interesting: usually cache, database shard, or messaging. Show trade-offs you considered and rejected.",
      "Prepare 2 deep dives in mind while drawing high-level — likely ask about data store and hot path.\n\nGo deep on: schema, sharding key, cache invalidation, consistency.",
      "Strategic deep dive choice shows experience.",
      "Database deep dive template? — Schema, indexes, shard key, replication.",
      "Cache deep dive? — Pattern, TTL, invalidation, stampede.",
      "Shallow overview of all components",
      "Deep dive load balancer only — boring unless asked",
      "No trade-offs mentioned"),
    q("Failure Mode Analysis", "Reliability", "Very Common",
      "What failures discuss before interview ends?",
      "Single server down, DB primary failure, cache down, network partition, hot key, cascade failure. Mitigation: replication, circuit breaker, degrade gracefully.",
      "Template: 'If Redis fails, fall through to DB — higher latency but available.' 'If DB primary down, failover to replica — 30s RTO.'",
      "Failure discussion mandatory for pass score.",
      "Cascading failure? — Timeout + circuit breaker — stop retry storm.",
      "Data center loss? — Multi-region — RPO/RTO numbers.",
      "Happy path only design",
      "No monitoring mention",
      "Infinite retry on failure"),
    q("Monitoring and SLIs", "Observability", "Common",
      "Define SLIs for URL shortener.",
      "Availability: successful redirects / total. Latency: p99 redirect < 100ms. Correctness: wrong redirect rate ~ 0.",
      "SLI → SLO → error budget. Alert on burn rate. Dashboard: QPS, cache hit ratio, DB replication lag.",
      "SLO literacy expected at architect level.",
      "Synthetic monitoring? — Probe redirect from multiple regions.",
      "Business metric SLI? — Links created per minute — capacity planning.",
      "No metrics defined",
      "Alert on CPU only",
      "100% availability SLO"),
    q("Scope Management in 45 Minutes", "Interview Skill", "Common",
      "Running out of time in system design interview?",
      "Explicitly prioritize: 'I'll cover data model and skip CDN unless time.' Ask interviewer preference.",
      "Better to deep dive one area well than shallow everything.\n\nLeave 3 min for failures — reserve time early.",
      "Time management is scored implicitly.",
      "Checkpoint at 15 min? — 'High-level complete — proceed to deep dive?'",
      "Rabbit hole? — 'I'll note open question and continue.'",
      "Panic and rush diagram",
      "Ignore interviewer hint to move on",
      "No time reserved for failures"),
    q("Post-Design Evolution", "Evolution", "Common",
      "Interviewer: 'How does design change at 100x scale?'",
      "Identify first bottleneck from estimation. 100x QPS → shard DB, regional caches, separate write/read path, async preprocessing.",
      "Show evolution path — not redesign from scratch. 'Phase 1 monolith OK; at 10M users add read replicas; at 100M shard by userId.'",
      "Evolution thinking shows production experience.",
      "When rewrite? — When operational cost of patch exceeds rewrite — rare — justify.",
      "Cost at 100x? — Mention linear vs superlinear cost drivers.",
      "Same design regardless of scale",
      "Shard day one for 1000 users",
      "Cannot identify bottleneck"),
]

WEEK_34 = [
    q("Cache-Aside Pattern", "Caching", "Very Common",
      "Explain cache-aside. Cache miss flow?",
      "App checks cache → miss → read DB → populate cache → return. On write: update DB → invalidate or update cache.",
      "Standard for Redis + SQL. TTL prevents stale forever. Stampede protection on hot keys.\n\nRead-through/write-through alternatives when cache layer owns load logic.",
      "Cache-aside is default architect pattern.",
      "Cache penetration? — Bloom filter for non-existent keys.",
      "Cache avalanche? — Stagger TTLs — random jitter.",
      "Cache without TTL",
      "Write DB without cache invalidation",
      "Thundering herd on hot key expiry"),
    q("CDN Architecture", "CDN", "Very Common",
      "When CDN vs origin-only?",
      "CDN for static assets, video, global users, DDoS absorption. Origin for dynamic personalized API unless edge compute.",
      "CloudFront/Front Door: cache static `/assets/*`, pass-through `/api/*`. Geo routing for latency.\n\nCache invalidation on deploy — versioned filenames `app.v123.js`.",
      "CDN is edge architecture decision.",
      "Edge compute? — Lambda@Edge, CloudFront Functions — auth geo block.",
      "Cache key design? — Vary by `Accept-Language` if needed.",
      "CDN for personalized JSON API",
      "No cache bust on deploy",
      "Origin exposed without CDN DDoS protection"),
    q("Horizontal Scaling", "Scale", "Very Common",
      "Scale web tier from 1K to 100K RPS.",
      "Stateless app servers behind L7 LB. Session in Redis not sticky server memory. Auto-scale on CPU/RPS. DB becomes bottleneck next — read replicas then shard.",
      "Remove server affinity. Externalize sessions. Connection pool to DB per instance — watch total DB connections = instances × pool size.",
      "Horizontal scale requires stateless design.",
      "Sticky sessions when needed? — Prefer Redis session store over LB stickiness.",
      "Auto-scale signal? — RPS or queue depth — not CPU alone.",
      "In-memory session on scaled servers",
      "DB connection exhaustion",
      "Stateful app servers behind LB"),
    q("Database Sharding Key", "Sharding", "Very Common",
      "Choose shard key for multi-tenant SaaS orders.",
      "`tenantId` — co-locate tenant data — efficient tenant queries. Hot large tenant risk — salting or dedicated shard for enterprise tier.",
      "Avoid shard key with poor cardinality. Queries must include shard key or scatter-gather expensive.\n\nRe-sharding plan: consistent hashing, dual-write migration.",
      "Shard key is hardest to change — get right early.",
      "Cross-shard query? — Fan-out to all shards — avoid in hot path.",
      "Tenant dedicated shard? — Enterprise SLA — isolate noisy neighbor.",
      "UserId shard for tenant-scoped queries",
      "Shard key not in queries",
      "No plan for resharding"),
    q("Read Replica Lag", "Replication", "Common",
      "Product catalog read replica 30s lag — acceptable?",
      "Often yes for browse — not for inventory count at checkout. Route critical reads to primary or use sync replication for stock.",
      "Display 'prices may update' vs hard correctness on payment amount from primary snapshot.",
      "Lag tolerance is business decision documented in ADR.",
      "Read-your-writes? — Route user's reads to primary briefly after write.",
      "Global replicas? — Cross-region lag higher — geo routing aware.",
      "All reads to lagging replica",
      "Inventory oversell from stale read",
      "No lag monitoring"),
    q("Rate Limiting Algorithms", "Rate Limiting", "Common",
      "Token bucket vs sliding window for API rate limit?",
      "Token bucket: smooth burst allowance. Sliding window: precise requests per minute. Fixed window: simple but boundary burst.",
      "Implement in Redis with Lua script atomicity. Return `429` + `Retry-After`.\n\nPer-user and global limits — global protects platform.",
      "Rate limiting protects availability — architect specifies at gateway.",
      "Distributed rate limit? — Redis central — not per-node counters.",
      "Whitelist internal services? — Carefully — mTLS identity based.",
      "No rate limit on public API",
      "Per-server limit only — uneven",
      "Rate limit without client feedback headers"),
    q("Hot Partition Problem", "Sharding", "Common",
      "Celebrity user breaks shard — mitigation?",
      "Separate handling: dedicated shard, cache layer, async fan-out, read replicas for that key. Detect hot keys via metrics.",
      "Twitter fan-out on read for celebrities instead of write to all followers.\n\nGeneral: monitor shard QPS variance — rebalance.",
      "Hot key is common failure at scale — anticipate in design.",
      "Key salting? — `userId#random` spread writes — complicates reads.",
      "Local cache on app for hot key? — Short TTL — reduce shard load.",
      "Uniform sharding assumption",
      "No hot key monitoring",
      "Same path for celebrity and normal user"),
    q("Autoscaling Signals", "Cloud Scale", "Common",
      "What metrics trigger autoscale for API tier?",
      "RPS, CPU, request queue depth, p95 latency. Scale out cooldown prevents flapping. Pre-warm before known events.",
      "K8s HPA: CPU + custom metrics from Prometheus. App Service: CPU + schedule rules.\n\nScale-in slowly — drain connections.",
      "Autoscale policy is architecture not ops afterthought.",
      "Predictive scaling? — Schedule before Black Friday — historical pattern.",
      "KEDA on queue depth? — Scale consumers with backlog.",
      "CPU-only autoscale misses I/O bound",
      "Aggressive scale-in kills requests",
      "No max instance cap — cost runaway"),
    q("Multi-Region Active-Passive", "Availability", "Common",
      "Design active-passive multi-region for 99.99% SLA.",
      "Active region serves traffic; passive warm standby. DNS/Traffic Manager failover on health check failure. Async replication — RPO > 0.",
      "Document failover runbook: detection, decision, DNS flip, validation, comms.\n\nPassive region: smaller footprint — scale on failover (cold/warm).",
      "Multi-region is cost + complexity — justify with SLA revenue.",
      "Active-active when? — 99.99%+ and global users — conflict resolution harder.",
      "Split brain during failover? — Ensure single writer — fencing.",
      "Sync replication cross-region latency",
      "No failover tested annually",
      "DNS TTL 3600 slows failover"),
    q("Cost at Scale", "FinOps", "Common",
      "Estimate cost drivers at 100K RPS.",
      "Compute instances, DB (largest often), cache, egress bandwidth, CDN. Egress often surprise — keep traffic in-region.",
      "Order of magnitude with pricing calculator. Unit economics: $/million requests.\n\nArchitect proposes tiered architecture — cache reduces DB cost 10x.",
      "Cost awareness completes scalability answer.",
      "Reserved capacity? — Baseline RIs + burst on-demand.",
      "Egress optimization? — CDN, compress responses, regional data.",
      "Ignore egress in estimate",
      "Over-provision 'just in case' forever",
      "No cache — DB scales linearly expensive"),
]

WEEK_35 = [
    q("Message Queue vs Event Stream", "Messaging", "Very Common",
      "SQS vs Kafka — when each?",
      "SQS: simple queue, consumer deletes message, lower ops. Kafka: log, replay, high throughput, stream processing, ordering per partition.",
      "Order processing: SQS fine. Clickstream analytics: Kafka. Azure: Service Bus vs Event Hubs mirrors this split.",
      "Right messaging tech avoids re-architecture later.",
      "Ordering guarantee? — Kafka partition key; Service Bus sessions.",
      "Poison message? — DLQ after maxReceiveCount.",
      "Kafka for 10 messages/day",
      "SQS when need replay history",
      "No DLQ configured"),
    q("At-Least-Once Delivery", "Semantics", "Very Common",
      "Design consumer for at-least-once messaging.",
      "Idempotent handler + business key dedup store. Ack message only after successful processing. Store processed message IDs.",
      "Duplicate delivery normal — not exceptional. `ProcessedEvents` table with unique `messageId`.\n\nOutbox publisher also at-least-once — consumers must cope.",
      "Semantic understanding separates architect from beginner.",
      "Exactly-once illusion? — Say effectively-once via idempotency.",
      "Ordering + duplicates? — Handle out-of-order with version numbers.",
      "Assume one delivery only",
      "Ack before processing completes",
      "No dedup on consumer"),
    q("Event Choreography", "Events", "Common",
      "OrderPlaced event — who listens?",
      "Inventory, Payment, Notification services subscribe independently. No central orchestrator. Risk: hard to see global flow — use distributed tracing.",
      "Choreography: loose coupling. Add process manager view in observability dashboard documenting event flow.\n\nCompensation via compensating events — PaymentFailed → ReleaseInventory.",
      "Choreography suits simple flows — document event catalog.",
      "Event schema registry? — Confluent/Azure Schema Registry — evolution governance.",
      "Circular events? — Design dead letter — detect cycles.",
      "God orchestrator in monolith ESB",
      "No event documentation",
      "Synchronous chain disguised as events"),
    q("Outbox and Inbox", "Patterns", "Very Common",
      "Pair outbox with inbox pattern?",
      "Outbox: reliable publish from producer. Inbox: consumer deduplicates incoming `messageId` before processing — together effectively-once.",
      "Producer TX → outbox. Consumer: insert inbox record → process → mark done — same messageId unique constraint prevents duplicate processing.",
      "Inbox completes reliability story.",
      "Shared inbox table per service? — Yes — local to consumer DB.",
      "Outbox relay failure? — Retry with backoff — monitor lag.",
      "Consumer without dedup",
      "Outbox without transactional insert",
      "At-most-once ack too early"),
    q("Service Bus Sessions", "Azure Messaging", "Common",
      "When use Service Bus sessions?",
      "Ordered processing per session key — e.g., all events for `orderId` processed in sequence by one consumer at a time.",
      "SessionId = orderId. One consumer holds session lock — sequential processing.\n\nTrade-off: less parallelism per session — hot session bottleneck.",
      "Sessions solve ordering without Kafka.",
      "Max concurrent sessions? — Tune for throughput vs ordering strictness.",
      "Session lock lost? — Message redelivered — handler idempotent.",
      "Sessions for all messages unnecessarily",
      "Hot session single consumer bottleneck unmitigated",
      "No session timeout handling"),
    q("Event Schema Evolution", "Governance", "Common",
      "Add field to OrderPlaced event — safe rollout?",
      "Additive changes only in v1 — new optional field. Consumers ignore unknown fields. Breaking change → new event type or version `OrderPlacedV2`.",
      "Schema registry compatibility: backward compatible readers. Deploy consumers before producers or vice versa per compatibility rule.",
      "Event contracts are API contracts — version them.",
      "Envelope pattern? — `{ metadata, payload }` — version in metadata.",
      "JSON vs Avro/Protobuf? — Binary schemas enforce compatibility better.",
      "Breaking rename without version",
      "No schema registry",
      "Deploy producer breaking consumers"),
    q("Dead Letter Queue", "Reliability", "Very Common",
      "Message fails 5 times — what happens?",
      "Moves to DLQ. Alert on DLQ depth. Manual or automated replay after fix. Root cause: poison schema, bug, or bad data.",
      "DLQ dashboard + runbook. Never infinite retry — blocks queue.\n\nSample DLQ messages to staging for debug.",
      "DLQ is operational necessity — architect specifies in design.",
      "DLQ replay tool? — Script re-publish with same idempotency keys.",
      "Alert threshold? — Any DLQ message > 0 for payment queue.",
      "Infinite retry loop",
      "DLQ messages auto-deleted",
      "No alert on DLQ growth"),
    q("Pub/Sub vs Point-to-Point", "Patterns", "Common",
      "Notification to email SMS push — pattern?",
      "Pub/sub topic — each channel subscriber independent. Point-to-point queue if exactly one worker must process job.",
      "Topic: OrderPlaced → [EmailSub, SmsSub, PushSub]. Competing consumers on queue for work distribution.",
      "Pattern choice affects scaling and semantics.",
      "Fan-out cost? — N subscribers × message size — budget.",
      "Filtering? — Subscription filters on attributes — avoid wrong delivery.",
      "Queue when need broadcast",
      "Topic when need single consumer",
      "No subscription error handling"),
    q("Event-Driven Microservices Integration", "Architecture", "Very Common",
      "Sync API vs event between order and inventory?",
      "Reserve inventory: sync if user waits at checkout. Low stock alert: async event. Replenish warehouse: async.",
      "User-facing latency dictates sync. Everything else event-driven for resilience.\n\nNever 30s sync HTTP chain — use async + polling/WebSocket for status.",
      "Integration style follows user wait time.",
      "Eventual notification UX? — WebSocket push when async completes.",
      "Saga via events? — Choreographed saga — document compensation events.",
      "All sync between all services",
      "All async for user-blocking path",
      "No correlation ID on events"),
    q("Messaging Cost and Ops", "FinOps", "Common",
      "Service Bus premium vs Kafka self-hosted TCO?",
      "Service Bus: low ops, per-message cost. Kafka: high ops (cluster management), lower marginal message cost at huge volume.",
      "Break-even depends on volume and team skills. Architect includes engineer time in TCO.\n\nStart managed — migrate to Kafka if message volume forces it.",
      "Build vs buy applies to messaging infrastructure.",
      "Serverless consumption plan? — Azure Service Bus premium for predictable latency.",
      "Message size limit? — Large payloads → blob storage + event reference.",
      "Kafka for low volume — ops waste",
      "Ignore ops cost in TCO",
      "Large payload in message body"),
]

WEEK_36 = [
    q("Capstone System Design Presentation", "Capstone", "Very Common",
      "Present e-commerce platform design — structure?",
      "Requirements recap, estimation, diagram, catalog/cart/checkout deep dives, failure modes, evolution roadmap, cost order of magnitude.",
      "10-minute version for exec; 45-minute whiteboard for technical. Have ADRs for SQL vs NoSQL, cache, saga.",
      "Capstone simulates senior interview.",
      "Challenge defense? — Acknowledge trade-off — don't be defensive.",
      "What cut if 6 months not 12? — Prioritize checkout path MVP.",
      "No failure scenarios",
      "Cannot estimate QPS",
      "Single diagram only"),
    q("Checkout Saga End-to-End", "Saga", "Very Common",
      "Whiteboard checkout in 15 minutes.",
      "Cart (Redis) → reserve inventory (sync, TTL) → payment (idempotent) → confirm order → async notify. Compensate on payment fail.",
      "Draw numbered steps. Label sync vs async arrows. Idempotency-Key on payment. Inventory release compensation.",
      "Checkout is #1 system design + microservices crossover.",
      "Double-click pay? — Idempotency key — same result.",
      "Inventory TTL? — 15 min — release on timeout job.",
      "No compensation path",
      "Sync email in checkout path",
      "Missing idempotency"),
    q("Notification Platform Design", "System Design", "Common",
      "Design multi-channel notification system.",
      "Event bus → router → priority queues per channel → workers → provider adapters (SendGrid, Twilio). Template service. Retry + DLQ.",
      "Rate limit per user — don't spam. Preference center — opt out per channel.\n\nIdempotent send — `notificationId` dedup.",
      "Notification is common whiteboard — prepare template.",
      "Priority queue? — OTP before marketing email.",
      "Batching? — Digest emails — separate scheduler.",
      "Single thread sends all email",
      "No provider abstraction",
      "No user preference store"),
    q("Search and Catalog at Scale", "Search", "Common",
      "10M products — search architecture?",
      "Elasticsearch/Azure AI Search index fed by product change events. Primary DB source of truth. Cache hot searches.",
      "CDC or domain events update index. Search replica lag acceptable for browse.\n\nFaceted search — denormalize attributes in index document.",
      "Search is separate read optimized store.",
      "Index rebuild? — Blue-green index alias swap.",
      "Typo tolerance? — Fuzzy match — product decision.",
      "SQL LIKE for search at 10M products",
      "No index update pipeline",
      "Search and DB strong consistency"),
    q("Multi-Tenant E-Commerce", "Multi-Tenancy", "Common",
      "B2B marketplace — tenant isolation?",
      "Pool: `tenantId` on all rows + RLS. Silo: DB per enterprise tenant. Bridge: pool default, silo for premium.",
      "Auth resolves tenant — every query scoped. Cache keys include tenantId.\n\nNoisy neighbor: rate limit per tenant.",
      "Multi-tenancy permeates data and cache design.",
      "Cross-tenant leak test? — Security test suite mandatory.",
      "Tenant-specific config? — Feature flags per tenant tier.",
      "Missing tenantId in cache key",
      "Shared admin API without tenant scope",
      "One rate limit global"),
    q("Disaster Recovery for Platform", "DR", "Common",
      "Region loss — RPO/RTO for e-commerce capstone?",
      "RPO 1h, RTO 4h example: async cross-region DB replica, Traffic Manager failover, runbook tested quarterly.",
      "Payment during DR: pause or read-only mode decision — document.business choice.\n\nBackup restore test — untested backup is fiction.",
      "DR numbers make design concrete.",
      "Chaos engineering? — Game day regional failover drill.",
      "Data residency? — EU tenants stay EU region — affects DR.",
      "No DR for 'we'll rebuild'",
      "RPO=0 claim with async replication",
      "Untested failover runbook"),
    q("Performance Budget", "Performance", "Common",
      "Set performance budget for checkout page.",
      "p99 checkout API < 500ms. CDN static < 50ms. Max 3 sync service calls. Database queries < 50ms each.",
      "Budget drives architecture — exceed budget → add cache or async.\n\nMeasure in CI with load test gate on PR for critical paths.",
      "Performance budgets connect NFR to design.",
      "Real user monitoring? — Compare lab load test to production RUM.",
      "Budget owner? — Architect proposes — product approves trade-offs.",
      "No latency targets",
      "Budget only on homepage",
      "Ignore mobile network latency"),
    q("Security in Platform Design", "Security", "Common",
      "Security layers for e-commerce capstone?",
      "WAF at edge, auth at gateway, PCI scope reduction (tokenized payments), encryption at rest, audit logs, rate limiting, input validation.",
      "Card data never touches your servers — Stripe/Adyen tokenization.\n\nOWASP top 10 addressed in threat model document.",
      "Security woven in — not bolted on at end.",
      "PCI DSS scope? — Minimize — SAQ A if iframe checkout.",
      "Secrets? — Key Vault — rotation policy.",
      "Store PAN in database",
      "No WAF on public API",
      "Security only in week 14"),
    q("Evolution from Monolith to Platform", "Evolution", "Common",
      "Year 1 monolith → Year 3 platform — phases?",
      "Y1: modular monolith. Y2: extract checkout + catalog. Y3: event bus + search + notifications. Document triggers for each phase.",
      "Triggers: team size, deploy pain, scale metrics — not calendar alone.\n\nStrangler fig throughout — never big bang.",
      "Evolution roadmap shows strategic thinking.",
      "Team topology per phase? — Align stream-aligned teams to services.",
      "Technical debt budget? — 20% capacity for platform improvements.",
      "Microservices day 1",
      "No phase criteria",
      "Rewrite instead of strangler"),
    q("Month 9 Graduation Criteria", "Readiness", "Common",
      "Prove system design month mastery?",
      "5 whiteboards ≥75/100, System Design Top 50 ≥75%, capstone doc complete, mock-02 and mock-05 passed, RESHADED under 45 min.",
      "Record yourself whiteboarding — painful but effective. Weak area log updated.",
      "Demonstrable skill — not content consumed.",
      "Peer review capstone? — Another student challenges design.",
      "Schedule mock-06 panel when ready.",
      "Theory only no whiteboard practice",
      "Cannot do estimation under pressure",
      "Skip failure mode section every time"),
]

ALL_WEEKS = {
    5: WEEK_5, 6: WEEK_6, 7: WEEK_7, 8: WEEK_8,
    21: WEEK_21, 22: WEEK_22, 23: WEEK_23, 24: WEEK_24,
    33: WEEK_33, 34: WEEK_34, 35: WEEK_35, 36: WEEK_36,
}
