"""Hand-crafted premium Q081–Q100 for Week 1 Advanced — C# / .NET architect topics."""

from premium_qa_data import q

WEEK1_ADVANCED_Q081_Q100 = [
    q("Reflection Cost and Alternatives", "Runtime", "Common",
      "When is reflection acceptable in production .NET, and what alternatives should architects mandate?",
      "Reflection is fine at startup (DI registration, mapping config) but costly in hot paths — metadata lookup, Activator.CreateInstance, and property iteration allocate and bypass JIT inlining. Prefer compile-time solutions: source generators, delegates, or expression trees compiled once.",
      "**Cost profile:**\n- `typeof(T).GetProperties()` — cache results statically\n- `Activator.CreateInstance` — 10–100× slower than `new T()`\n- JSON serializers using reflection — switch to `System.Text.Json` source generators\n\n**Alternatives:**\n| Pattern | Use Case |\n|---------|----------|\n| Source generators | DTO mapping, serializers, DI registration |\n| Compiled delegates | Dynamic property access after one-time compile |\n| `IServiceProvider` keyed services | Plugin resolution without reflection scan |\n| Interface + factory registry | Known types at compile time |\n\n**Architect rule:** Reflection allowed in composition root and one-time startup; banned in request path without benchmark proof.\n\n**Native AOT note:** Reflection trimmed — plan alternatives before AOT migration.",
      "Reflection is a platform tax — architects distinguish bootstrap vs hot-path usage.",
      "Reflection.Emit vs expression trees? — Emit for dynamic assemblies; expressions for single-delegate compile.",
      "HybridCache reflection? — .NET 9 caches reflection metadata internally — still avoid per-request.",
      "GetProperties() in every request handler",
      "Reflection-based ORM mapping in microsecond SLA path",
      "No static cache for reflection metadata"),
    q("Expression Trees Use Cases", "Advanced C#", "Occasional",
      "What are expression trees in .NET and when should architects use them?",
      "Expression trees represent code as data (`Expression<Func<T,bool>>`) — compiled once to delegates or translated to SQL (EF Core), OData filters, or dynamic rules engines. Use when you need inspectable, composable predicates — not for simple lambdas.",
      "**Use cases:**\n1. **EF Core** — `Where(x => x.Age > 18)` translated to SQL via expression visitor\n2. **Dynamic filtering** — API `?sort=name&filter=status eq active` → composable `IQueryable`\n3. **Rule engines** — business rules stored as expressions, compiled at load\n4. **Specification pattern** — `ISpecification<T>.Criteria` as expression\n\n```csharp\nExpression<Func<Order, bool>> pred = o => o.Total > 100;\nvar compiled = pred.Compile(); // once\n```\n\n**Avoid:** Compiling same expression per request — cache `Func<T,bool>`. Don't build expression trees manually unless framework requires it — use `PredicateBuilder` libraries.\n\n**Architect:** Expression trees bridge type-safe C# and external DSLs — document who owns translation (EF vs custom).",
      "Expression trees power IQueryable — architects know when compile-once pays off.",
      "Expression vs delegate? — Delegate executes; expression describes — EF needs description.",
      "Visitor pattern complexity? — Custom translators need test suite — EF does heavy lifting.",
      "Compile() inside request loop",
      "Manual expression building for simple if/else",
      "Expression tree for logging only"),
    q("Channels vs BlockingCollection", "Concurrency", "Common",
      "Compare `System.Threading.Channels` and `BlockingCollection<T>` for producer-consumer in .NET.",
      "`Channels` (async-first, backpressure, bounded/unbounded, `IAsyncEnumerable`) is the modern choice. `BlockingCollection` blocks thread pool threads — legacy, avoid in ASP.NET request paths.",
      "| Feature | Channels | BlockingCollection |\n|---------|----------|-------------------|\n| Async | `await reader.ReadAsync()` | Blocking `Take()` |\n| Backpressure | Bounded capacity + `Wait`/`Drop` | Bounded with locks |\n| Thread use | Non-blocking async | Blocks threads |\n| Integration | `BackgroundService`, pipelines | TPL Dataflow predecessor |\n\n**Architect pattern:**\n```csharp\nvar channel = Channel.CreateBounded<WorkItem>(100);\n// Producer: await channel.Writer.WriteAsync(item)\n// Consumer: await foreach (var item in channel.Reader.ReadAllAsync(ct))\n```\n\n**Use BlockingCollection only:** Legacy integration, existing TPL code not yet migrated.\n\n**Production:** Bounded channel with `FullMode.Wait` prevents OOM when consumer slower than producer. Multiple readers via `Channel.CreateUnbounded` + single consumer `BackgroundService`.",
      "Channels align with async ASP.NET — BlockingCollection starves thread pool under load.",
      "Channel vs ConcurrentQueue? — Channel adds backpressure and async wait — queue alone spins.",
      "System.Threading.Channels unbounded risk? — Memory growth if consumer dies — prefer bounded.",
      "BlockingCollection.Take() in async API",
      "Unbounded channel without monitoring",
      "Multiple writers without TryWrite handling"),
    q("Immutable Collections Architecture", "Collections", "Occasional",
      "When architect `System.Collections.Immutable` in enterprise .NET services?",
      "Immutable collections (`ImmutableList<T>`, `ImmutableDictionary<K,V>`) provide thread-safe snapshots without locks — ideal for shared config, lookup tables, and functional pipelines. Mutations return new instances — pay copy cost.",
      "**Architect use cases:**\n- **Cached reference data** — product catalog snapshot refreshed hourly — readers never see partial update\n- **Options/config snapshots** — `IOptionsMonitor` callback builds new immutable graph\n- **Domain value objects** — internal immutable state, exposed as `IReadOnlyList`\n- **Concurrent read-heavy maps** — `ImmutableDictionary` + atomic `Interlocked.Exchange` reference swap\n\n**Pattern:**\n```csharp\nprivate volatile ImmutableDictionary<string, Sku> _catalog = ImmutableDictionary<string, Sku>.Empty;\nvoid Refresh(IEnumerable<Sku> skus) =>\n    Interlocked.Exchange(ref _catalog, skus.ToImmutableDictionary(s => s.Code));\n```\n\n**Avoid:** Per-request mutations — use mutable collections in local scope. Large frequent updates — copy cost dominates.\n\n**NuGet:** `System.Collections.Immutable` — also used by Roslyn, MSBuild.",
      "Immutable snapshots eliminate reader locks — architects use for shared read-mostly state.",
      "Frozen collections .NET 8? — `FrozenDictionary` faster read — immutable after build.",
      "Persistent immutable vs deep copy? — Structural sharing — not full copy on every Add.",
      "ImmutableList per-request Add in loop",
      "Mutable static dictionary without sync",
      "Immutable for write-heavy cache"),
    q("ConcurrentDictionary Patterns", "Concurrency", "Common",
      "Production patterns for `ConcurrentDictionary` beyond basic Get/Add?",
      "`GetOrAdd`, `AddOrUpdate`, and `GetOrAdd` with lazy factory prevent duplicate expensive initialization. Avoid locking entire dictionary — use per-key patterns and `ConcurrentDictionary` for cache, not primary data store.",
      "**Patterns:**\n1. **Lazy singleton per key** — `GetOrAdd(key, _ => ExpensiveCreate(key))` — factory may run twice rarely; OK for idempotent\n2. **Atomic counter** — `AddOrUpdate(key, 1, (_, count) => count + 1)`\n3. **Striped locking** — combine with `SemaphoreSlim` per key for non-atomic multi-step updates\n4. **Cache with TTL** — store `(Value, Expiry)` tuple; background sweep or lazy expiry check\n\n**Anti-patterns:**\n- `TryGetValue` then `TryAdd` race — use `GetOrAdd` atomic\n- Holding lock while awaiting — blocks other keys\n- Million keys unbounded — memory leak; use IMemoryCache with size limits\n\n**Architect:** In-memory `ConcurrentDictionary` cache is process-local — document cache invalidation across instances (Redis pub/sub, message).",
      "ConcurrentDictionary is in-process concurrent map — not distributed cache.",
      "GetOrAdd factory runs twice? — Documented race — use Lazy<T> inside value if costly.",
      "ConcurrentDictionary vs IMemoryCache? — IMemoryCache adds eviction, size limits, DI integration.",
      "TryGetValue + TryAdd race condition",
      "Unbounded cache keys in long-running service",
      "Async work inside GetOrAdd factory blocking threads"),
    q("Thread Safety and Lock-Free Patterns", "Concurrency", "Occasional",
      "Explain lock-free patterns available in .NET and when architects choose them over locks?",
      "Lock-free uses atomic operations (`Interlocked`, `Volatile`, `MemoryBarrier`) to avoid mutex contention. Use for simple counters, reference swaps, and lock-free queues at high contention — not replacement for all synchronization.",
      "**Building blocks:**\n- `Interlocked.Increment`, `CompareExchange` — atomic counter, CAS loops\n- `volatile` / `Volatile.Read/Write` — visibility guarantees\n- `ImmutableInterlocked` — atomic immutable collection swap\n- `System.Threading.Channels` — internally efficient queues\n\n**When lock-free:**\n- Metrics counters at millions ops/sec\n- Single-writer reference swap (config reload)\n- `ConcurrentQueue` / Channels for producer-consumer\n\n**When locks (`lock`, `SemaphoreSlim`):**\n- Multi-step invariants across fields\n- Complex business rules\n- Async code — `SemaphoreSlim`, not `lock` with await\n\n**Architect caution:** Lock-free CAS retry loops can starve under extreme contention — benchmark. Prefer `ConcurrentDictionary` and BCL abstractions over hand-rolled lock-free.",
      "Lock-free trades complexity for latency — architects default to BCL concurrent types first.",
      "SpinLock vs lock? — SpinLock for micro-short critical sections only — can waste CPU.",
      "Memory model on ARM? — Volatile/Interlocked required — don't rely on accidental ordering.",
      "Hand-rolled lock-free linked list",
      "lock {} around await",
      "False sharing on hot counters — pad cache lines in extreme HPC"),
    q("Parallel.For Pitfalls", "Parallelism", "Common",
      "What are production pitfalls of `Parallel.For` and `Parallel.ForEach` in .NET?",
      "Parallel.For uses thread pool threads — wrong for I/O-bound work, dangerous with thread-affine APIs (DbContext, HttpContext), and can cause oversubscription when combined with async. Use for CPU-bound, partitionable, thread-safe workloads only.",
      "**Pitfalls:**\n1. **I/O inside loop** — blocks thread pool → starvation — use `Task.WhenAll` + async\n2. **Non-thread-safe collections** — `List<T>.Add` races — use `ConcurrentBag` or lock\n3. **DbContext per iteration** — not thread-safe — one context per thread via `Parallel.For` local init\n4. **ASP.NET request** — Parallel.For in controller doubles thread pressure with Kestrel\n5. **Small collections** — parallel overhead exceeds benefit — threshold ~1000+ CPU-heavy items\n6. **Exception handling** — `AggregateException` — handle `LoopResult`\n\n**Better alternatives:**\n- CPU batch: `Parallel.For` with `MaxDegreeOfParallelism`\n- I/O batch: `await Task.WhenAll(items.Select(ProcessAsync))`\n- Data pipeline: `Channel` + `BackgroundService`\n\n**Architect:** Ban Parallel.For in web request path by analyzer; restrict to batch jobs, image processing, compute workers.",
      "Parallel.For is for CPU parallelism — not async I/O replacement.",
      "Partitioner.Create? — Custom chunk sizing for uneven work per item.",
      "PLINQ vs Parallel.For? — PLINQ declarative; similar thread pool — same pitfalls.",
      "Parallel.For with async lambda — doesn't exist — common mistake with .Result",
      "Shared DbContext across parallel iterations",
      "Parallel.For on 10-item collection"),
    q("PLINQ When to Use", "Parallelism", "Occasional",
      "When should architects recommend PLINQ (`AsParallel()`) in production .NET?",
      "PLINQ parallelizes LINQ to Objects in-memory queries — use for CPU-bound filtering/aggregation on large in-memory collections, offline batch processing. Avoid on IQueryable (not EF-translatable), small collections, or order-dependent operations without `AsOrdered()`.",
      "**Good fits:**\n- In-memory analytics on 100K+ records loaded once\n- Image/file batch transformation\n- Complex CPU aggregation where `Parallel.For` less readable\n\n**Bad fits:**\n- `dbContext.Orders.AsParallel()` — doesn't parallelize SQL — pulls all to memory\n- Latency-sensitive API request path\n- Side-effecting `Select` (DB writes per item)\n- Collections < few thousand simple ops\n\n```csharp\nvar result = records.AsParallel()\n    .WithDegreeOfParallelism(Environment.ProcessorCount)\n    .Where(r => ExpensiveCpuCheck(r))\n    .ToList();\n```\n\n**Architect:** PLINQ is batch/offline tool — document in platform guidance. Prefer explicit `Parallel.For` when degree of parallelism must be tightly controlled.",
      "PLINQ parallelizes in-memory LINQ — architects block EF + AsParallel anti-pattern.",
      "AsOrdered cost? — Preserves order with coordination overhead — only when required.",
      "WithExecutionMode ForceParallelism? — Debug only — not production.",
      "AsParallel on IQueryable EF query",
      "PLINQ with non-thread-safe side effects",
      "Default parallelism on machine with 64 cores — cap for shared hosts"),
    q("MemoryPool and ArrayPool", "Performance", "Very Common",
      "Architect guidance for `MemoryPool<T>` and `ArrayPool<T>` in high-throughput .NET APIs?",
      "ArrayPool rents/returns byte buffers — eliminates LOH allocation for transient buffers. MemoryPool rents `IMemoryOwner<T>` — structured memory for pipelines (Kestrel, Pipelines). Always return buffers; clear sensitive data; never return buffer still in use.",
      "**ArrayPool<byte>.Shared:**\n```csharp\nvar buffer = ArrayPool<byte>.Shared.Rent(minSize);\ntry { /* use buffer.AsSpan(0, actualLength) */ }\nfinally { ArrayPool<byte>.Shared.Return(buffer, clearArray: true); }\n```\n\n**MemoryPool:** Used internally by `PipeReader`/`PipeWriter` — custom protocol parsers rent from `MemoryPool<byte>.Shared`.\n\n**Architect rules:**\n- Pool buffers >1KB used frequently in hot path\n- `clearArray: true` for security-sensitive data\n- Don't pool tiny arrays — overhead exceeds benefit\n- Document max rent size — unbounded rent breaks pool buckets\n\n**LOH connection:** Arrays >85KB go to LOH — pooling prevents Gen2 pressure.\n\n**System.Text.Json:** `JsonSerializer.SerializeToUtf8Bytes` allocates — use `IBufferWriter<byte>` + ArrayPool for zero-copy paths.",
      "Pooling is architect-level GC strategy — mandatory review for serialization-heavy APIs.",
      "ArrayPool vs stackalloc? — stackalloc for small fixed spans <1KB sync-only.",
      "LOH threshold 85KB? — Rent size may exceed needed — use exact length slice.",
      "Forget Return() — pool exhaustion",
      "Return buffer while async IO still reading",
      "Pool every 32-byte allocation"),
    q("Utf8JsonReader Streaming", "Serialization", "Common",
      "How architect high-performance JSON parsing with `Utf8JsonReader`?",
      "`Utf8JsonReader` is forward-only, low-allocation UTF-8 JSON reader — parse streams without deserializing entire document to `JsonDocument` or string. Use for large payloads, selective field extraction, and hot paths.",
      "**Patterns:**\n```csharp\nvar reader = new Utf8JsonReader(utf8Bytes);\nwhile (reader.Read())\n{\n    if (reader.TokenType == JsonTokenType.PropertyName &&\n        reader.ValueTextEquals(\"orderId\"))\n    {\n        reader.Read();\n        var id = reader.GetInt64();\n    }\n}\n```\n\n**Architect use cases:**\n- Webhook ingestion — extract 3 fields from 5MB JSON\n- Log/event pipeline — stream from `PipeReader`\n- API gateway — validate structure without full model bind\n\n**vs alternatives:**\n| Approach | When |\n|----------|------|\n| `JsonSerializer.Deserialize<T>` | Full object mapping, moderate size |\n| `JsonDocument` | Random access, moderate memory |\n| `Utf8JsonReader` | Streaming, selective, max perf |\n| Source generator | Known schema, compile-time |\n\n**Caveat:** Manual parsing brittle — wrap in tested extractor class; use source generator for known DTOs when possible.",
      "Utf8JsonReader is architect tool for allocation-sensitive JSON pipelines.",
      "JsonReaderException handling? — Partial reads from stream — buffer incomplete JSON.",
      "PipeReader integration? — Kestrel request body — avoid ToArray() materialize.",
      "ReadAsStringAsync entire 50MB body",
      "Hand-rolled parser without tests per schema version",
      "Utf8JsonReader on UTF-16 string — convert allocates"),
    q("HttpContext Accessor Anti-Pattern", "ASP.NET Core", "Very Common",
      "Why is `IHttpContextAccessor` considered an anti-pattern in domain and application layers?",
      "`IHttpContextAccessor` hides implicit dependency on HTTP request — untestable domain logic, service locator smell, breaks in background workers, and thread-unsafe if cached in singleton. Pass `UserId`, `CorrelationId`, `CancellationToken` explicitly.",
      "**Problems:**\n- Domain service calls `httpContextAccessor.HttpContext.User` — can't unit test without mock HTTP\n- Singleton caching accessor — stale/wrong context\n- MediatR handler uses accessor — obscures real dependencies in signature\n\n**Architect-approved pattern:**\n```csharp\n// Middleware extracts context → scoped IRequestContext\npublic interface IRequestContext\n{\n    string UserId { get; }\n    string CorrelationId { get; }\n}\n// Handler: CreateOrderHandler(IRequestContext ctx) — explicit\n```\n\n**Legitimate accessor use:** Infrastructure only — logging enrichers, legacy library bridge, framework middleware.\n\n**Enforcement:** ArchUnitNet test — domain project must not reference `Microsoft.AspNetCore.Http`.",
      "Explicit context injection preserves clean architecture boundaries.",
      "AsyncLocal for context? — Same hidden dependency problem — prefer explicit scoped service.",
      "Minimal APIs access HttpContext param? — OK at edge — map to command before domain.",
      "IHttpContextAccessor in domain entity",
      "Singleton service storing HttpContext field",
      "Accessor in MediatR behavior without interface abstraction"),
    q("Options Validation IValidateOptions", "Configuration", "Common",
      "How implement robust options validation with `IValidateOptions<T>` and `ValidateOnStart`?",
      "Bind configuration to `IOptions<T>`, validate with `IValidateOptions<T>` or data annotations, call `ValidateOnStart()` so misconfiguration fails at boot — not first request.",
      "**Implementation:**\n```csharp\nservices.AddOptions<PaymentOptions>()\n    .BindConfiguration(\"Payment\")\n    .ValidateDataAnnotations()\n    .Validate(o => o.TimeoutSeconds > 0, \"Timeout must be positive\")\n    .ValidateOnStart();\n\npublic class PaymentOptionsValidator : IValidateOptions<PaymentOptions>\n{\n    public ValidateOptionsResult Validate(string name, PaymentOptions options)\n    {\n        if (string.IsNullOrEmpty(options.ApiKey))\n            return ValidateOptionsResult.Fail(\"ApiKey required\");\n        if (!Uri.TryCreate(options.BaseUrl, UriKind.Absolute, out _))\n            return ValidateOptionsResult.Fail(\"Invalid BaseUrl\");\n        return ValidateOptionsResult.Success;\n    }\n}\n```\n\n**Architect:**\n- Cross-field validation in `IValidateOptions` — URL + API key consistency\n- Secrets validated present (not empty) — actual values from Key Vault\n- Separate options per bounded context — not one `AppSettings` god object\n- Health check can re-validate critical options if using `IOptionsMonitor`",
      "Fail-fast configuration prevents production runtime exceptions on missing settings.",
      "IValidateOptions vs ValidateDataAnnotations? — Combine — annotations for simple, custom for cross-field.",
      "Options in library vs app? — Library registers `AddOptions<T>` extension with validator.",
      "No ValidateOnStart — first request crashes",
      "Catch validation errors and use defaults",
      "500-line monolithic Options class"),
    q("Health Check UI Production", "Observability", "Common",
      "Should architects expose Health Checks UI in production ASP.NET Core?",
      "Expose `/health/live` and `/health/ready` for orchestrators (K8s probes) — minimal JSON, no dependency details publicly. Health Checks UI (`/health-ui`) is dev/staging only — production leaks dependency topology and aids attackers.",
      "**Production pattern:**\n```csharp\napp.MapHealthChecks(\"/health/live\", new() { Predicate = _ => false }); // process up\napp.MapHealthChecks(\"/health/ready\", new() { Predicate = check => check.Tags.Contains(\"ready\") });\n```\n\n**Security:**\n- Public ready endpoint returns `Healthy`/`Unhealthy` only — not SQL connection strings in response\n- Detailed checks (`/health/detail`) — internal network + auth or metrics backend only\n- AspNetCore.HealthChecks.UI — disable in prod or protect with OAuth + IP allowlist\n\n**Architect:** Align probes — liveness (restart pod) vs readiness (remove from LB). Dependency checks (SQL, Redis) on readiness only.\n\n**Azure:** App Service health check path = `/health/ready`. Front Door origin probe same.",
      "Health endpoints are attack surface — architects separate public minimal vs internal detailed.",
      "Health check caching? — `Microsoft.Extensions.Diagnostics.HealthChecks` timeout per check — tune.",
      "Tag-based filtering? — `ready` vs `live` tags — K8s best practice.",
      "Health Checks UI public on internet",
      "Return exception stack in health response",
      "Liveness probe checks SQL — kills pod on DB blip"),
    q("API Versioning Header vs URL", "API Design", "Very Common",
      "Compare URL path, header, and query string API versioning for enterprise .NET APIs.",
      "URL path (`/v2/orders`) — most visible, cache-friendly, easy routing. Header (`api-version: 2.0`) — clean URLs, harder to test in browser. Query (`?api-version=2.0`) — optional versioning, poor caching. Architects pick one standard per platform.",
      "| Strategy | Pros | Cons |\n|----------|------|------|\n| URL path | Explicit, gateway routing, docs clarity | URL proliferation |\n| Header | Clean URLs, REST purist | Proxy config, curl friction |\n| Media type | Hypermedia purist | Complex, rare in practice |\n| Query string | Easy opt-in | CDN cache key mess |\n\n**ASP.NET Core:** `Asp.Versioning.Http` supports all — configure default version + sunset headers.\n\n**Architect policy:**\n- Public mobile/ partner APIs — URL versioning + deprecation `Sunset` header\n- Internal east-west — header or no versioning with simultaneous deploy\n- Document minimum supported version — 2 major versions max\n\n**Gateway:** APIM/YARP route `/v1/*` vs `/v2/*` to different backends during strangler.",
      "Versioning strategy is long-term consumer contract — architects document deprecation timeline.",
      "Sunset header RFC? — Communicate version retirement date to API consumers.",
      "Default version assume 1.0? — Unversioned calls route to oldest — explicit policy needed.",
      "Three versioning strategies in same org",
      "Breaking change without version bump",
      "Version in body JSON — hardest to route"),
    q("ProblemDetails Exception Mapping", "API Design", "Very Common",
      "How architect consistent exception-to-`ProblemDetails` mapping in ASP.NET Core APIs?",
      "Use `IExceptionHandler` (.NET 8+) or middleware with typed exception hierarchy — map `NotFoundException` → 404, `ValidationException` → 400, unknown → 500 without leaking internals. Include `traceId`, `type` URI, RFC 7807 fields.",
      "**Architecture:**\n```csharp\npublic class GlobalExceptionHandler : IExceptionHandler\n{\n    public async ValueTask<bool> TryHandleAsync(\n        HttpContext ctx, Exception ex, CancellationToken ct)\n    {\n        var (status, title) = ex switch\n        {\n            NotFoundException => (404, \"Not Found\"),\n            FluentValidation.ValidationException => (400, \"Validation Error\"),\n            ConflictException => (409, \"Conflict\"),\n            _ => (500, \"Internal Server Error\")\n        };\n        var problem = new ProblemDetails\n        {\n            Status = status, Title = title,\n            Type = $\"https://api.example.com/errors/{status}\",\n            Extensions = { [\"traceId\"] = Activity.Current?.Id }\n        };\n        if (ex is ValidationException ve)\n            problem.Extensions[\"errors\"] = ve.Errors;\n        await Results.Problem(problem).ExecuteAsync(ctx);\n        return true;\n    }\n}\n```\n\n**Rules:**\n- 500 responses — generic message; log full exception server-side\n- Domain exceptions carry error codes — not SQL messages\n- Consistent across all services — shared `ProblemDetails` library",
      "ProblemDetails is enterprise API error contract — architects enforce via shared middleware package.",
      "ValidationProblemDetails? — ModelState + FluentValidation unified shape.",
      "Exception middleware order? — Before endpoints — catch handler exceptions too.",
      "return ex.Message on 500",
      "Different error JSON shape per service",
      "Stack trace in ProblemDetails extensions public"),
    q("MediatR Pipeline Behaviors", "Patterns", "Common",
      "Design MediatR pipeline behaviors for cross-cutting concerns in Clean Architecture.",
      "Pipeline behaviors wrap handlers — order: logging → validation → authorization → transaction → handler. Register open generic `IPipelineBehavior<TRequest,TResponse>` in DI.",
      "**Standard behaviors:**\n1. **ValidationBehavior** — FluentValidation all `IValidator<TRequest>`\n2. **LoggingBehavior** — request name, duration, user\n3. **TransactionBehavior** — `IUnitOfWork.Commit` for commands only\n4. **AuthorizationBehavior** — policy check on request attributes\n5. **CachingBehavior** — queries with `ICacheableQuery` marker\n\n```csharp\npublic class ValidationBehavior<TReq, TRes> : IPipelineBehavior<TReq, TRes>\n    where TReq : IRequest<TRes>\n{\n    public async Task<TRes> Handle(TReq req, RequestHandlerDelegate<TRes> next, CancellationToken ct)\n    {\n        await _validator.ValidateAndThrowAsync(req, ct);\n        return await next();\n    }\n}\n```\n\n**Architect:** Behavior order documented in platform README. Avoid 10 behaviors — performance and debuggability suffer. Queries skip transaction behavior via marker interface.",
      "MediatR pipeline is enterprise cross-cutting backbone — architects standardize behavior set.",
      "Behavior ordering? — Registration order in DI — first registered outermost.",
      "MediatR vs decorator? — Behaviors are chain; decorators per handler — choose consistency.",
      "Transaction on query handler",
      "Authorization only in controller — bypassed by internal Send()",
      "Behavior with sync blocking I/O"),
    q("EF Core Interceptors", "Data Access", "Common",
      "When use EF Core interceptors and what cross-cutting concerns do they solve?",
      "Interceptors hook `DbCommand`, `SaveChanges`, connection events — implement auditing, soft delete, multi-tenancy filters, slow query logging, and command tagging without repository boilerplate.",
      "**Common interceptors:**\n- **Auditing** — `SaveChangesInterceptor` sets `CreatedAt`, `ModifiedBy` on `EntityState.Added/Modified`\n- **Soft delete** — rewrite `Delete` to `Update` with `IsDeleted` flag\n- **Tenant filter** — `QueryExpressionInterceptor` adds `Where(e => e.TenantId == current)` globally\n- **Tagging** — `CommandInterceptor` appends `-- Tag: OrderService.GetById` for SQL insights\n- **Retry** — connection resiliency (built-in) + custom for transient detection\n\n```csharp\noptions.AddInterceptors(new AuditingInterceptor(currentUser));\n```\n\n**Architect cautions:**\n- Global query filters + multi-tenancy — test bypass for admin reports\n- Interceptor order matters — document registration\n- Don't hide business rules that belong in domain — auditing OK, pricing rules not",
      "Interceptors centralize persistence cross-cutting — architects govern tenant and audit policies.",
      "IDbCommandInterceptor vs SaveChangesInterceptor? — Command for SQL; SaveChanges for entity state.",
      "EF Plus vs interceptor? — Third-party bulk — evaluate vendor lock-in.",
      "Soft delete interceptor without unique index on filtered column",
      "Tenant filter missing on new entity type",
      "Interceptor throws — opaque transaction failure"),
    q("Compiled Queries EF Core", "Data Access", "Occasional",
      "When do compiled queries in EF Core justify the complexity?",
      "Compiled queries cache query expression translation and delegate — shave microseconds on hot paths executed millions of times. Worth for tight loops; unnecessary for typical CRUD called once per request.",
      "**Syntax:**\n```csharp\nprivate static readonly Func<AppDbContext, int, Order?> GetOrderById =\n    EF.CompileQuery((AppDbContext ctx, int id) =>\n        ctx.Orders.AsNoTracking().FirstOrDefault(o => o.Id == id));\n\n// Usage\nvar order = GetOrderById(dbContext, orderId);\n```\n\n**When to use:**\n- High-frequency lookup (product catalog by SKU every request)\n- Minimal API hot endpoints after profiling proves EF compile cost significant\n- .NET multi-tenant same query shape different context instance\n\n**When to skip:**\n- Dynamic LINQ with varying shapes — can't compile one delegate\n- Already using `AsNoTracking` projection — optimize N+1 first\n\n**Architect:** Measure with BenchmarkDotNet — compiled query saves ~10–30% EF overhead, not magic fix for bad SQL.",
      "Compiled queries micro-optimize hot EF paths — architects apply after N+1 and index fixes.",
      "EF.CompileAsyncQuery? — Async hot paths — same pattern.",
      "Query splitting interaction? — Compiled query includes AsSplitQuery in expression.",
      "Compiled query for admin report run once daily",
      "Dynamic filter breaks compiled query cache",
      "Skip indexes because compiled query added"),
    q("Bulk Insert Strategies EF Core", "Data Access", "Very Common",
      "Compare bulk insert strategies for high-volume .NET data ingestion.",
      "EF `SaveChanges` row-by-row is too slow for 100K+ rows. Strategies: `AddRange` + batched SaveChanges, `ExecuteSqlRaw` COPY/BULK INSERT, `SqlBulkCopy`, third-party EFExtensions, or bypass EF with Dapper.",
      "| Strategy | Throughput | Trade-off |\n|----------|------------|----------|\n| AddRange + batch SaveChanges | Moderate | Change tracking overhead |\n| ExecuteUpdate/Insert (.NET 7+) | Good | SQL generation limits |\n| SqlBulkCopy | Very high | SQL Server specific, no EF tracking |\n| PostgreSQL COPY | Very high | Npgsql binary import |\n| EF Extensions BulkInsert | High | License, extension dep |\n\n**Architect pattern:**\n- **OLTP path** — normal EF for business transactions\n- **Ingestion pipeline** — separate worker, `SqlBulkCopy` or CSV `BULK INSERT`, no DbContext\n- **Batch size** — 1000–5000 per SaveChanges batch; tune memory\n\n**Pitfalls:** Identity column handling, trigger firing, audit interceptor bypass on raw bulk, transaction log growth — coordinate with DBA.",
      "Bulk insert is separate architectural path from OLTP EF — don't force SaveChanges at scale.",
      "Change tracking off? — `context.ChangeTracker.AutoDetectChangesEnabled = false` for large AddRange.",
      "Outbox pattern bulk? — Insert outbox in same transaction — order matters.",
      "SaveChanges 1M rows in single request",
      "Bulk insert without transaction boundary plan",
      "Ignore audit requirements on bulk path"),
    q("Architect Code Review Checklist", "Leadership", "Very Common",
      "What does a .NET architect code review checklist cover beyond syntax?",
      "Architect review verifies boundaries, NFRs, operability, and systemic risk — not formatting. Checklist: layering violations, security authZ gaps, data access patterns, async discipline, observability, configuration, API contract, and failure modes.",
      "**Checklist categories:**\n1. **Architecture** — Domain doesn't reference Infrastructure; no circular deps; appropriate pattern (not gold-plated CQRS)\n2. **Security** — AuthZ on every mutating endpoint; input validation; secrets not in code; IDOR check\n3. **Data** — N+1 risk; transaction scope; migration included; index for new filters\n4. **Async** — No `.Result`/`.Wait()`; CancellationToken propagated; DbContext not in singleton\n5. **Observability** — Structured logging with correlation ID; metrics on critical path; health checks\n6. **API** — Versioning; ProblemDetails; breaking change assessment; pagination on lists\n7. **Resilience** — Timeouts on HttpClient; retry only idempotent; circuit breaker on externals\n8. **Performance** — Allocation in hot path; caching stampede risk; pool usage\n\n**Process:** Automate with analyzers, ArchUnitNet, and CI — human review for trade-offs and ADR alignment.\n\n**Architect role:** Teach via review comments — link to standards doc, not rewrite PR.",
      "Architect code review gates systemic risk — checklist scales team quality.",
      "Automate what? — StyleCop, Roslyn analyzers, NetArchTest, EF query count test.",
      "Review size limit? — 400 LOC PR guideline — architect splits large changes.",
      "Review only naming conventions",
      "Approve without running app or tests",
      "No security review on public endpoints"),
]
