"""Hand-crafted premium Q011–Q030 for Weeks 21–22 — Distributed Systems & Microservices."""

from premium_qa_data import q

WEEK_21_Q011_Q030 = [
    q("Two-Phase Commit Limits", "Transactions", "Very Common",
      "Why do architects avoid 2PC across microservices? What breaks at scale?",
      "2PC blocks all participants until coordinator commits — locks held, latency spikes, single coordinator failure stalls all. Not suitable for WAN or long-running business logic.",
      "**Phase 1 (prepare):** participants vote ready, hold locks. **Phase 2 (commit/abort):** coordinator decides.\n\n**Problems:**\n- Blocking: if coordinator dies after prepare, participants stuck until timeout\n- Availability hit during partition — CP behavior\n- Locks on inventory/payment rows block other orders\n\n**Architect stance:** Use sagas with compensation, outbox, or single-service transactions. Reserve XA/2PC for legacy same-DC, same-team databases only.",
      "Rejecting 2PC shows you understand distributed transaction reality.",
      "When is 2PC acceptable? — Same database cluster, short transactions, ops team owns coordinator HA.",
      "3PC improvement? — Reduces blocking but adds complexity — rarely used in practice.",
      "Distributed 2PC across payment and inventory microservices",
      "Long-running prepare phase holding row locks",
      "No coordinator HA plan"),
    q("Saga Compensation Design", "Transactions", "Very Common",
      "Payment succeeded but shipping failed — design compensation steps and ordering.",
      "Compensate in reverse order of forward steps. Payment → refund (idempotent). Inventory → release reservation. Each compensating action must be safe to retry and semantically undo the forward step.",
      "**Forward:** Reserve inventory → Charge payment → Create shipment.\n**Compensate:** Cancel shipment (if created) → Refund payment → Release inventory.\n\n**Design rules:**\n- Compensating transactions are business operations (`RefundPayment`), not DB rollbacks\n- Use saga log with state machine — `Compensating`, `Completed`, `Failed`\n- TTL on reservations prevents orphan holds\n\n**Architect:** Document which steps are compensatable vs require manual intervention (shipment already picked).",
      "Compensation design is where saga interviews go deep.",
      "Pivot vs compensate? — If forward step not yet committed, pivot to alternate path instead of compensate.",
      "Poison saga step? — Escalate to human workflow after N automated compensation failures.",
      "Compensation as DELETE without audit trail",
      "Compensate out of order releasing inventory before refund",
      "No idempotency on refund API"),
    q("Outbox Pattern Deep Dive", "Messaging", "Very Common",
      "Compare polling outbox, transactional messaging, and CDC relay. When each?",
      "Polling outbox: simple, slight lag. Transactional messaging (Kafka EOS): limited cross-store. CDC (Debezium): scales, captures all row changes, ops overhead.",
      "**Polling relay:**\n```sql\nSELECT * FROM outbox WHERE processed_at IS NULL ORDER BY id LIMIT 100 FOR UPDATE SKIP LOCKED\n```\nPublish → mark processed in same worker transaction.\n\n**CDC:** Reads DB WAL — no polling load on OLTP, delivers all changes, requires Kafka Connect ops.\n\n**Architect decision matrix:**\n- <1K events/sec, team small → polling outbox\n- High volume, existing Kafka → Debezium\n- Azure SQL + Service Bus → polling or Azure SQL trigger relay",
      "Deep outbox knowledge separates textbook from production architects.",
      "Outbox ordering guarantees? — Per aggregate ID partition key preserves order.",
      "Relay failure mid-batch? — At-least-once relay — consumer dedup required.",
      "Dual write without outbox",
      "Outbox table without index on unprocessed rows",
      "Relay single instance without SKIP LOCKED"),
    q("Inbox Deduplication", "Messaging", "Common",
      "Partner sends duplicate webhooks. Design inbox pattern for exactly-once processing.",
      "Store `message_id` in inbox table with unique constraint. Process in same transaction as business update. Duplicate insert fails → skip processing, return 200.",
      "**Flow:**\n1. BEGIN TRANSACTION\n2. INSERT inbox (message_id) — conflict → rollback, ack duplicate\n3. Apply business logic\n4. COMMIT\n\n**TTL:** Purge processed inbox rows after 7–30 days.\n\n**Architect:** Pair with outbox on publisher side — end-to-end effectively-once. Redis SET NX for speed with SQL inbox for durability audit.",
      "Inbox is the consumer-side mirror of outbox.",
      "At-least-once broker + inbox = effectively once? — Yes if business logic idempotent on replay.",
      "Inbox vs idempotency key table? — Inbox for inbound events; idempotency keys for client API retries.",
      "Dedup only in memory — lost on restart",
      "Process business logic before inbox insert",
      "No unique constraint on message_id"),
    q("Quorum and Raft Basics", "Consensus", "Common",
      "Explain Raft leader election and why quorum is n/2+1.",
      "Raft: one leader handles writes, replicates log to followers. Election on leader timeout — candidate needs majority votes. Quorum n/2+1 ensures at most one leader per term.",
      "**Raft terms:**\n1. Follower misses heartbeat → becomes candidate\n2. Candidate requests votes — needs majority\n3. Winner becomes leader — append entries to followers\n4. Commit when majority replicated\n\n**Examples:** etcd (K8s), CockroachDB, Consul.\n\n**Architect:** Ask vendors 'Raft or custom?' — understand failover time = election timeout + replication lag.",
      "Raft literacy explains modern distributed DB behavior.",
      "Raft vs Paxos? — Raft designed for understandability — same safety guarantees.",
      "Read from follower? — Possible with linearizability trade-off — stale reads risk.",
      "Even number of Raft nodes without witness",
      "Sub-quorum writes during partition",
      "Ignoring election timeout tuning"),
    q("Clock Skew and Ordering", "Time", "Common",
      "Design event ordering for audit trail across three data centers without synchronized clocks.",
      "Never sort by `DateTime.UtcNow` from different hosts. Use database sequence, Snowflake IDs, or Lamport/vector clocks for causal ordering.",
      "**Patterns:**\n- **DB authority:** `BIGSERIAL` or `rowversion` assigned at write primary\n- **Kafka:** partition by `orderId` — order within partition guaranteed\n- **Hybrid logical clocks:** CockroachDB `hlc` — wall time + logical counter\n\n**Audit requirement:** Display events sorted by authoritative sequence, show originating DC as metadata not sort key.\n\n**Architect:** NTP drift in cloud is real (milliseconds to seconds) — design for logical order.",
      "Time ordering mistakes cause compliance and debugging nightmares.",
      "TrueTime (Spanner)? — GPS + atomic clocks bound clock uncertainty — expensive.",
      "Lamport vs vector clocks? — Vector tracks concurrent events — Lamport only causal.",
      "Cross-DC sort by client timestamp",
      "Assuming NTP perfect in containers",
      "No monotonic ID for financial audit"),
    q("Split Brain Prevention", "Consensus", "Common",
      "Two-node SQL Always On AG lost quorum witness — what is split brain and how prevent?",
      "Split brain: two nodes both believe they are primary, accept writes — data diverges irreconcilably. Prevent with quorum, fencing/STONITH, and witness.",
      "**Prevention:**\n- Odd quorum or witness for 2-node\n- Fencing: losing node forcibly stopped from I/O\n- `required_synched_secondaries_to_commit` tuning\n\n**Cloud:** Blob witness in Azure, file share witness on-prem.\n\n**Architect:** During partition, **availability vs consistency** — quorum chooses consistency (one side stops). Document RTO/RPO for witness failure.",
      "Split brain is worse than brief outage — architects prioritize prevention.",
      "STONITH? — Shoot The Other Node In The Head — isolate before promote.",
      "Last man standing? — Dangerous without quorum — can promote stale replica.",
      "Two-node cluster no witness",
      "Manual failover without fencing",
      "Both sides accepting writes during partition"),
    q("Backpressure Strategies", "Resilience", "Common",
      "Queue depth growing 10x — architect backpressure response beyond 'scale consumers'.",
      "Layered response: bound buffers, slow producers, shed load, scale consumers, dead-letter poison, alert on lag SLO.",
      "**Strategies:**\n1. **Bounded channel** — block or drop producer when full\n2. **Adaptive publish rate** — reduce batch size when lag > threshold\n3. **Priority queues** — drop analytics, preserve payments\n4. **KEDA** — scale consumers on lag metric\n5. **Circuit break upstream** — stop accepting work user can't complete\n\n**Architect:** Unbounded queue = OOM. Define max lag SLO and escalation runbook before incident.",
      "Backpressure is load management not just autoscaling.",
      "Reactive Streams request(n)? — Pull-based flow control in streaming APIs.",
      "Shed load vs delay? — Payments delay with 503; telemetry sample/drop.",
      "Unbounded in-memory queue",
      "Scale producer without consumer capacity plan",
      "No DLQ for poison messages"),
    q("Circuit Breaker Tuning", "Resilience", "Very Common",
      "How tune circuit breaker thresholds for payment vs recommendation services?",
      "Payment: low failure threshold, short sampling window, no retry when open. Recommendations: higher threshold, fallback to cached defaults, longer half-open probe interval.",
      "**Polly / resilience pipeline parameters:**\n- `FailureRatio` / `MinimumThroughput` — avoid opening on 1/2 requests\n- `BreakDuration` — 30s payment, 5s recommendations\n- `SamplingDuration` — window for failure rate calculation\n\n**Monitor:** `circuit_state` metric — alert when open > 1 min.\n\n**Architect:** Per-dependency policy — never one global breaker. Document fallback behavior in ADR.",
      "Tuning shows production resilience experience.",
      "Half-open probe? — Single test request — success closes, failure reopens.",
      "Circuit breaker vs retry interaction? — Don't retry when circuit open.",
      "Same breaker settings all dependencies",
      "Circuit open with no fallback UX",
      "No metrics on breaker state transitions"),
    q("Bulkhead Isolation", "Resilience", "Common",
      "Design bulkhead isolation for API calling payment, inventory, and email services.",
      "Separate thread pools / semaphores / HttpClient pipelines per downstream — email slowness cannot exhaust threads for payment.",
      "**Implementation:**\n```csharp\n// Polly bulkhead: max 10 parallel, 20 queue\n.AddBulkhead(maxParallelization: 10, maxQueuingActions: 20)\n```\n\n**K8s:** Separate deployments for critical vs batch paths.\n\n**Architect:** Bulkhead + circuit breaker + timeout = defense in depth. Size pools from load test — payment pool sized for peak checkout.",
      "Bulkhead prevents one slow dependency from sinking the ship.",
      "Bulkhead vs timeout? — Timeout limits wait; bulkhead limits concurrency — use both.",
      "Thread pool starvation signal? — Growing queue length with flat throughput.",
      "Single shared HttpClient pool all dependencies",
      "Bulkhead queue unbounded",
      "No bulkhead on background email worker affecting API"),
    q("Retry with Jitter", "Resilience", "Very Common",
      "Design retry policy for transient 503 from inventory API. Why jitter?",
      "Exponential backoff with full jitter: `delay = random(0, min(cap, base * 2^attempt))`. Prevents thundering herd when service recovers — clients don't retry simultaneously.",
      "**Rules:**\n- Retry only idempotent operations (GET, PUT with idempotency key)\n- Max 3–5 attempts with cap (30s)\n- Retry 408, 429, 502, 503, 504 — not 400, 401, 404\n\n**Polly:** `WaitAndRetryAsync` with decorrelated jitter.\n\n**Architect:** Mandate jitter in org resilience standards — without it, recovery causes second outage.",
      "Jitter is small detail with large production impact.",
      "Retry-After header? — Honor server hint on 429/503.",
      "Retry on POST payment without idempotency key? — Never.",
      "Fixed 1s retry interval on all clients",
      "Infinite retry on 500 errors",
      "Retry storm after regional recovery"),
    q("Timeout Budgets", "Resilience", "Very Common",
      "Page load budget 800ms — allocate timeout budget across gateway and three sync services.",
      "Subtract network overhead; allocate remaining budget top-down. Client 800ms → gateway 750ms → service A 400ms → B 200ms → C 100ms. Child timeout < parent.",
      "**Pattern:**\n- Propagate `X-Timeout-Deadline` or use `CancellationToken` linked to remaining budget\n- Fail fast when budget exhausted — don't start call with 50ms left\n\n**Architect:** Document timeout tree in service catalog. Alert when p95 approaches budget — scaling signal before timeouts cascade.",
      "Timeout budgets connect SLOs to implementation.",
      "Timeout vs deadline? — Deadline is absolute wall clock; timeout is relative duration.",
      "Default HttpClient 100s timeout? — Change — kills thread pool under load.",
      "Same 30s timeout every hop",
      "Child timeout exceeds parent",
      "No timeout on outbound calls"),
    q("Graceful Degradation", "Resilience", "Common",
      "Recommendations service down during Black Friday — design graceful degradation for product page.",
      "Serve cached popular products, hide personalization block, show 'recommendations temporarily unavailable' — core catalog and checkout unaffected.",
      "**Tiers:**\n1. **Full:** live recommendations\n2. **Degraded:** 1-hour stale cache\n3. **Minimal:** bestsellers static list\n4. **Off:** section hidden — page loads\n\n**Architect:** Define degradation levels in ADR. Feature flags toggle tiers. Never block checkout on non-critical dependency.",
      "Graceful degradation protects revenue during partial outages.",
      "Fallback cache warming? — Pre-populate top 100 SKUs before event.",
      "Health check drives degradation? — Auto-fallback when dependency unhealthy.",
      "Entire page 500 when recommendations fail",
      "No cached fallback path",
      "Degradation not tested in game day"),
    q("CAP in Practice Examples", "Fundamentals", "Very Common",
      "Map five production components to CAP stance during network partition.",
      "During partition: SQL sync replica CP (reject writes), Redis async replica AP (stale reads), Cassandra AP (tunable), ZooKeeper CP, CDN AP.",
      "**Scenario walkthrough — partition between AZs:**\n- **Order DB (CP):** reject write if quorum lost — user sees error, no double charge\n- **Session cart (AP):** accept writes both sides, merge on heal — acceptable conflict rules\n- **Search index (AP):** stale results OK briefly\n\n**Architect:** Document per-component CAP choice and business sign-off on inconsistency windows.",
      "Concrete CAP mapping beats abstract theorem recitation.",
      "Bank transfer during partition? — CP — reject rather than risk duplicate.",
      "Social like count? — AP — approximate acceptable.",
      "Claiming distributed system is CA",
      "Same CAP stance for ledger and analytics",
      "No partition scenario in DR design review"),
    q("PACELC Theorem", "Fundamentals", "Common",
      "Explain PACELC and how it guides database selection beyond CAP.",
      "If Partition → choose A or C. Else (normal operation) → choose Latency or Consistency. DynamoDB/Cassandra favor EL; Spanner/Cockroach favor EC.",
      "**Examples:**\n- **DynamoDB (PA/EL):** fast writes, eventual consistency default\n- **Cosmos strong session (PC/EC):** higher latency for consistency even without partition\n- **CockroachDB (PC/EC):** distributed SQL with tunable isolation\n\n**Architect:** CAP only describes partition — PACELC captures everyday latency vs consistency trade-off that dominates most designs.",
      "PACELC shows mature distributed systems thinking.",
      "Cosmos consistency levels? — Five levels map to LC spectrum.",
      "Read-your-writes without strong? — Session consistency — practical middle ground.",
      "Only discussing CAP in interviews",
      "Ignoring latency cost of strong consistency",
      "Strong consistency globally for all reads"),
    q("Gossip Protocols", "Consensus", "Occasional",
      "How do gossip protocols work in Cassandra and Consul? Trade-offs?",
      "Nodes periodically exchange state with random peers — epidemic spread. Eventually all nodes converge. O(log n) rounds for cluster-wide awareness.",
      "**Uses:**\n- **Cassandra:** failure detection, ring membership\n- **Consul:** cluster membership, health state\n- **Redis Cluster:** slot map propagation\n\n**Trade-offs:** Eventually consistent membership view — brief window of stale routing. Low overhead vs centralized coordinator.\n\n**Architect:** Understand gossip ≠ consensus — use for membership, not financial ledger writes.",
      "Gossip explains how decentralized clusters self-organize.",
      "SWIM protocol? — Improved failure detection — used in Consul.",
      "Gossip vs heartbeat? — Gossip scales better; heartbeat simpler for small clusters.",
      "Assuming gossip gives strong consistency",
      "No handling of stale membership during failover",
      "Central coordinator without HA for membership"),
    q("Leader Election", "Consensus", "Common",
      "Kubernetes controller needs single leader — compare etcd election vs database advisory lock.",
      "etcd/K8s lease: built-in, TTL, watch-based — standard for K8s operators. DB advisory lock: simpler if already on Postgres, risk if DB slow.",
      "**K8s pattern:**\n```yaml\nleaderElection:\n  leaseDuration: 15s\n  renewDeadline: 10s\n```\n\n**Postgres:** `pg_advisory_lock(id)` — released on connection drop.\n\n**Redis:** `SET key NX EX ttl` — fencing token required for safety.\n\n**Architect:** Leader election for background jobs only — not user-facing request routing without load balancer coordination.",
      "Leader election prevents duplicate cron side effects.",
      "Split brain in leader election? — TTL + fencing — stale leader must stop.",
      "ZooKeeper ephemeral nodes? — Classic pattern — etcd replaced in cloud-native.",
      "Two leaders processing same payment batch",
      "No TTL on Redis leader key",
      "Leader election on every API request"),
    q("Distributed Locks Redis", "Coordination", "Common",
      "Implement safe distributed lock with Redis for invoice generation job.",
      "Redlock or single-instance `SET lock_key token NX PX 30000`. Verify token before unlock (Lua script). Always set TTL — prevent deadlock on crash.",
      "**Safety requirements:**\n- Unique token per acquirer\n- TTL > max job duration + clock skew buffer\n- Extend lock (heartbeat) for long jobs\n- Fencing token passed to downstream (DB write rejects stale leader)\n\n**Architect:** Redis lock OK for efficiency jobs; use DB or etcd for financial correctness. Martin Kleppmann critique — understand limitations.",
      "Redis locks are common — knowing limits is architect duty.",
      "Redlock algorithm? — Multi-master quorum — debated safety.",
      "Lock without TTL? — Crashed holder blocks forever.",
      "DEL lock_key without token check",
      "Single Redis instance claimed 'fully safe'",
      "Lock duration shorter than job runtime"),
    q("Consensus vs Coordination", "Consensus", "Occasional",
      "Distinguish consensus and coordination. Which does etcd provide?",
      "Consensus: nodes agree on single value/ordering (Raft log). Coordination: broader — locks, leader election, config — may use consensus underneath.",
      "**etcd provides both:**\n- Consensus via Raft replicated log\n- Coordination primitives: leases, watches, elections\n\n**Examples:**\n- **Consensus needed:** distributed config version, schema migration leader\n- **Coordination only:** job scheduling lock, feature flag propagation\n\n**Architect:** Don't build custom consensus — use etcd, Consul, or cloud leader election. Use consensus layer for correctness-critical state.",
      "Precise vocabulary shows distributed systems depth.",
      "ZooKeeper znode? — Coordination primitive on top of ZAB consensus.",
      "Why not roll your own Raft? — Subtle bugs — use battle-tested library.",
      "Using database row lock as cluster consensus",
      "Confusing service discovery with consensus",
      "Custom leader election without fencing"),
    q("Phi Accrual Failure Detection", "Reliability", "Occasional",
      "How does phi accrual failure detector differ from fixed heartbeat timeout?",
      "Phi accrual adapts to network jitter — computes suspicion level (phi) from heartbeat arrival distribution. Fixed timeout false-positives on slow networks or false-negatives on fast failures.",
      "**Concept:** Model heartbeat inter-arrival times; phi rises as time since last heartbeat exceeds expected distribution. Threshold triggers suspect → failed.\n\n**Used in:** Akka, Cassandra (phi accrual influenced failure detection).\n\n**Architect:** Tune suspicion thresholds — aggressive = flapping failover; lenient = slow detection. Pair with hysteresis (N consecutive failures).",
      "Adaptive failure detection reduces false failover.",
      "Fixed 5s heartbeat timeout problems? — Jitter causes false positives at scale.",
      "Suspect vs failed state? — Suspect: probe more; failed: trigger failover.",
      "Single missed heartbeat triggers failover",
      "No hysteresis on flapping node",
      "Failure detection without considering GC pauses"),
]

WEEK_22_Q011_Q030 = [
    q("Service Boundary Discovery", "Decomposition", "Very Common",
      "How do you discover microservice boundaries in a brownfield e-commerce monolith?",
      "Event Storming workshops, dependency graph analysis, change coupling metrics, and team Conway alignment. Extract where business capability, data, and deployment pain intersect.",
      "**Workshop output:** Domain events on timeline — `OrderPlaced`, `PaymentCaptured`, `ShipmentDispatched`. Cluster events into bounded contexts.\n\n**Metrics:** Services that change together (git co-change) shouldn't split yet.\n\n**First candidate:** Notification or catalog — clear API, low cross-context transactions.\n\n**Architect:** Validate boundary with 'can this team deploy independently without coordinating schema migration?'",
      "Boundary discovery is collaborative domain work not just drawing boxes.",
      "Transaction boundary test? — If two modules need same DB transaction often — maybe same service.",
      "Conway's Law? — Service boundaries should align with team communication structure.",
      "Split by technical layer (API service, DB service)",
      "Boundaries from org chart without domain analysis",
      "Ignore data coupling in dependency graph"),
    q("API Gateway Patterns", "Gateway", "Very Common",
      "Compare single gateway, per-domain gateway, and mesh ingress. When each?",
      "Single gateway: small fleet, one team. Per-domain: multiple gateways by business area. Mesh ingress: K8s with Istio/Contour per cluster — gateway at platform layer.",
      "**Single (APIM):** `/api/*` routes to services — good <15 services.\n\n**Per-domain:** `orders-api.company.com`, `catalog-api.company.com` — separate rate limits, WAF rules, teams own routing.\n\n**Patterns in gateway:** TLS termination, JWT validation, rate limit, request ID, routing — not business rules.\n\n**Architect:** Gateway sprawl risk — platform team owns standards; domain teams own route config via GitOps.",
      "Gateway topology scales with org structure.",
      "Gateway aggregation vs BFF? — BFF when client-specific shaping; gateway stays thin.",
      "mTLS passthrough? — Compliance may require end-to-end encryption past gateway.",
      "Business validation in gateway policies",
      "God gateway with 200 routes one team",
      "No rate limiting on public endpoints"),
    q("BFF Per Client", "API Design", "Common",
      "Web and mobile need different order payloads. Design BFF layer.",
      "MobileBFF: compact JSON, fewer round trips, image URLs sized for device. WebBFF: richer data, SEO metadata. Each BFF orchestrates microservice calls server-side.",
      "**Structure:**\n- `MobileBff` → OrderService + CatalogService → single `/mobile/home`\n- `WebBff` → same services → `/web/home` with more fields\n\n**Auth:** BFF holds service-to-service tokens; mobile never calls 5 microservices directly.\n\n**Architect:** Keep BFF thin — orchestration and shaping only. Domain logic stays in services.",
      "BFF solves client-specific API ergonomics.",
      "GraphQL vs BFF? — GraphQL flexible queries; BFF explicit endpoints — team skill trade-off.",
      "One BFF forever? — Add new BFF per major client type (partner API, admin portal).",
      "Mobile app calls 12 microservices directly",
      "Fat BFF with business rules and EF Core",
      "Shared BFF for web and mobile with compromise payload"),
    q("Database Per Service Migration", "Data", "Very Common",
      "Extract order service from monolith DB — phased migration plan?",
      "Phase 1: service owns API, reads/writes monolith tables (pragmatic). Phase 2: dual-write or CDC sync to new schema. Phase 3: cut read traffic. Phase 4: retire monolith writes.",
      "**Patterns:**\n- **Strangler on schema:** views and triggers bridge during transition\n- **CDC:** Debezium captures monolith changes → new Order DB\n- **Anti-corruption layer:** translate legacy row shape to domain model\n\n**Reporting:** Warehouse ingests events — no cross-DB JOINs in prod.\n\n**Architect:** Never big-bang schema split on Friday. Rollback = route traffic back, not reverse migration.",
      "DB migration is highest-risk microservices step.",
      "Shared tables interim OK? — Time-boxed with explicit exit criteria.",
      "Saga for cross-service data? — Eventual consistency during split.",
      "Big-bang schema cutover",
      "Distributed JOIN across service DBs in prod",
      "No CDC validation before cutover"),
    q("Sync vs Async Communication", "Communication", "Very Common",
      "Checkout flow — classify each step as sync HTTP or async messaging.",
      "Sync (user waits): validate cart, authorize payment, return confirmation. Async: send email, update search index, analytics, loyalty points.",
      "**Rules:**\n- User-facing path: max 2–3 sync hops with timeout budgets\n- Side effects: always async with outbox\n- Sync failure blocks UX; async failure retries with DLQ\n\n**Example:** `POST /checkout` syncs payment; publishes `OrderPlaced` → inventory, email, warehouse consume async.\n\n**Architect:** Document communication matrix in service catalog — prevents ad-hoc HTTP chains.",
      "Sync/async choice defines latency and resilience.",
      "Request-reply over Kafka? — Anti-pattern — use HTTP or true fire-and-forget events.",
      "Choreography default? — Prefer events for side effects; sync only when user needs answer now.",
      "6-service sync chain for page load",
      "Email send blocks checkout response",
      "Async without dead letter queue"),
    q("Circuit Breaker Polly", "Resilience", "Very Common",
      "Configure Polly circuit breaker in .NET HttpClientFactory for inventory client.",
      "```csharp\nservices.AddHttpClient<IInventoryClient, InventoryClient>()\n    .AddStandardResilienceHandler(options => {\n        options.CircuitBreaker.SamplingDuration = TimeSpan.FromSeconds(30);\n        options.CircuitBreaker.FailureRatio = 0.5;\n        options.CircuitBreaker.MinimumThroughput = 10;\n        options.CircuitBreaker.BreakDuration = TimeSpan.FromSeconds(30);\n    });\n```\nOpen after 50% failures in 30s window (min 10 requests). Break 30s then half-open.",
      "**Architect standards:**\n- Named client per dependency\n- Fallback policy returns cached stock or 'availability unknown'\n- Log circuit state transitions\n\n**.NET 8+:** `Microsoft.Extensions.Http.Resilience` replaces ad-hoc Polly wiring.",
      "Polly configuration is hands-on architect skill for .NET shops.",
      "Half-open behavior? — Trial request — success closes circuit.",
      "Combine with retry? — Retry transient before breaker counts failure — configure pipeline order.",
      "Circuit breaker without HttpClientFactory",
      "Same resilience pipeline all dependencies",
      "No fallback when circuit open"),
    q("Bulkhead Thread Pools", "Resilience", "Common",
      "Isolate thread pools for payment and analytics HTTP calls in ASP.NET Core.",
      "Separate `IHttpClientFactory` named clients with Polly bulkhead — payment max 20 parallel, analytics max 5. Analytics backlog cannot starve payment threads.",
      "**Implementation:**\n```csharp\n.AddResilienceHandler(\"payment-bulkhead\", b =>\n    b.AddBulkhead(new BulkheadStrategyOptions {\n        MaxParallelization = 20,\n        MaxQueuedActions = 40\n    }));\n```\n\n**K8s complement:** Separate deployments for batch vs API if bulkhead insufficient.\n\n**Architect:** Size from load test — payment pool = peak concurrent checkouts × downstream calls.",
      "Thread pool bulkhead protects critical path.",
      "Bulkhead rejection? — Return 503 fast — better than slow timeout.",
      "Sync-over-async breaks bulkhead? — Fix root cause — async all the way.",
      "Single pool for all outbound HTTP",
      "Unbounded bulkhead queue",
      "No monitoring on bulkhead rejections"),
    q("Strangler Fig Migration", "Migration", "Very Common",
      "Strangler fig routing for `/api/orders` — design proxy rules and validation gates.",
      "Reverse proxy (YARP, APIM, nginx) routes by path prefix. Start 0% new service, shadow traffic, then 10% → 50% → 100% with feature flag.",
      "**Phases:**\n1. Proxy all `/api/orders/*` to monolith (baseline)\n2. Implement new service — route `GET /orders/{id}` only\n3. Shadow: duplicate requests, compare responses\n4. Canary: route percentage by header or flag\n5. Retire monolith handler\n\n**Architect:** Parity checklist — response schema, error codes, latency SLO before each traffic shift.",
      "Strangler fig is standard brownfield microservices pattern.",
      "Anti-corruption layer at boundary? — Translate monolith DTOs to new domain model.",
      "Rollback? — Single config change routes 100% back to monolith.",
      "Big bang cutover without shadow",
      "No automated response diff in shadow phase",
      "Delete monolith code before parity verified"),
    q("Service Mesh Istio When", "Infrastructure", "Occasional",
      "15 microservices, mixed .NET and Python — when justify Istio adoption?",
      "Justify when: uniform mTLS east-west, canary by percentage, observability without per-language SDK, 15+ services with platform team to operate mesh.",
      "**Cost:** Sidecar ~50–100MB RAM per pod, ~1–2ms latency per hop, Istio control plane ops.\n\n**Start without mesh:** Polly + centralized OTel + APIM for <10 services.\n\n**Mesh wins:** Polyglot, zero-trust network, traffic shifting without app changes.\n\n**Architect:** Pilot on non-critical service; measure p99 overhead before fleet-wide.",
      "Mesh is infrastructure bet with real ops cost.",
      "Sidecar vs ambient mesh? — Istio ambient reduces per-pod sidecar — evaluate maturity.",
      "Mesh without observability backend? — Telemetry needs Jaeger/Prometheus destination.",
      "Istio for 3-service team",
      "No platform team for mesh upgrades",
      "Ignore sidecar memory in node sizing"),
    q("Contract Testing Pact", "Testing", "Common",
      "Set up Pact between order service (consumer) and payment service (provider).",
      "Consumer writes pact defining expected `POST /payments` request/response. Provider CI verifies against published pacts. Pact Broker gates deploy.",
      "**Flow:**\n1. Order service tests define interaction expectations\n2. Pact file published to broker\n3. Payment service `verify-pacts` job in CI\n4. `can-i-deploy` checks compatibility before prod\n\n**Architect:** Consumer-driven — order team defines what they need; payment must not break contract without negotiation.",
      "Pact enables independent deploy with confidence.",
      "Pact vs OpenAPI? — OpenAPI is provider schema; Pact is consumer expectations verified.",
      "Breaking change process? — Major pact version bump + consumer update before provider deploy.",
      "E2E only integration testing",
      "Provider changes API without pact verification",
      "No broker — pacts lost on developer laptops"),
    q("Consumer-Driven Contracts", "Testing", "Common",
      "Why consumer-driven contracts vs provider-published OpenAPI only?",
      "Provider OpenAPI documents what exists; consumer-driven captures what is actually used — prevents unused breaking changes and catches provider drift on consumed fields.",
      "**Scenario:** Payment adds required field — OpenAPI updated — but order service didn't need it. Consumer-driven pact only tests order's subset.\n\n**Org process:** Consumer PRs publish pacts; provider CI blocks on verification failure.\n\n**Architect:** Complement with contract tests + smoke E2E — not replace all integration tests.",
      "CDC puts consumers in the contract driver's seat.",
      "Provider states? — Pact supports staging pacts per environment.",
      "Bi-directional contracts? — Emerging pattern — both sides verify.",
      "Provider dictates API without consumer input",
      "Breaking field removal without consumer notification",
      "Contract tests skipped in CI"),
    q("API Versioning Microservices", "API Design", "Common",
      "Version `/orders` API across three microservices consumed by mobile app.",
      "URL path versioning (`/v1/orders`, `/v2/orders`) for public APIs. Deprecation headers (`Sunset`, `Link`). Support N-1 version minimum 6–12 months.",
      "**Rules:**\n- Additive changes in minor — new optional fields OK\n- Breaking: new major version, parallel deploy\n- Mobile: force upgrade policy for ancient versions\n\n**Internal gRPC:** package versioning in proto (`v1`, `v2` services).\n\n**Architect:** API gateway routes version to correct service deployment — v1 and v2 may run simultaneously during migration.",
      "Versioning prevents mobile client breakage.",
      "Header vs URL versioning? — URL more visible for support and caching.",
      "GraphQL versioning? — Avoid — evolve schema additively with deprecation.",
      "Breaking change without version bump",
      "Three versions supported forever",
      "No Sunset header communication"),
    q("Choreography vs Orchestration", "Integration", "Very Common",
      "Order saga — when event choreography vs orchestrator (Durable Functions)?",
      "Choreography: few steps, clear events, teams own services — `OrderPlaced` → inventory reacts. Orchestration: 6+ steps, complex compensation, visibility needed — central coordinator.",
      "**Choreography pros:** loose coupling, no single point. **Cons:** hard to trace, implicit flow.\n\n**Orchestration pros:** visible state machine, easier debug. **Cons:** coordinator HA, coupling to orchestrator.\n\n**Hybrid:** Orchestrate checkout; choreograph post-order side effects.\n\n**Architect:** Choose orchestration when support asks 'where is my order in the pipeline?' daily.",
      "Saga style choice affects operability.",
      "Event notification vs event-carried state? — Carried state reduces chattiness.",
      "Orchestration language? — Durable Functions, Temporal, Camunda — team skill matters.",
      "Choreography with 12 events nobody documents",
      "Orchestrator for simple two-step flow",
      "No correlation ID across choreography"),
    q("Domain Events Integration", "Integration", "Common",
      "Publish `OrderPlaced` domain event — design schema, versioning, and consumers.",
      "CloudEvents envelope: `type`, `source`, `id`, `time`, `data`. Schema registry (Avro/JSON Schema). Version in `type` suffix or `dataschema` URI.",
      "**Event payload:** orderId, customerId, line items, total — not full entity graph.\n\n**Consumers:** inventory, email, analytics, warehouse — each idempotent on `event.id`.\n\n**Outbox:** publish from same transaction as order insert.\n\n**Architect:** Event contract is public API — review like REST breaking changes.",
      "Domain events are integration backbone.",
      "Event versioning? — Add optional fields; never remove — upcast old events in consumers.",
      "Integration event vs domain event? — Domain is business language; integration may translate at boundary.",
      "Fat events with entire database row",
      "No schema registry",
      "Consumers mutate event payload"),
    q("Shared Database Anti-Pattern", "Anti-Patterns", "Very Common",
      "Two microservices share Orders table — why anti-pattern and remediation?",
      "Hidden distributed monolith — schema changes require coordinated deploy, no true service ownership, coupling at data layer defeats independent scaling.",
      "**Symptoms:** Both services run migrations on same DB; integration tests need both schemas; neither team can deploy alone.\n\n**Remediation:**\n1. Assign table ownership to one service\n2. Other service accesses via API or replicated read model\n3. Events for state changes\n\n**Architect:** Shared DB acceptable as time-boxed migration phase — not end state.",
      "Shared DB is #1 microservices anti-pattern.",
      "View-based sharing? — Still coupling — views break on schema change.",
      "Reporting on shared DB? — CDC to warehouse instead of cross-service queries.",
      "Distributed JOIN in application layer",
      "Both services write same table",
      "No exit plan from shared schema"),
    q("Distributed Tracing Correlation", "Observability", "Common",
      "Standardize trace correlation across gateway, BFF, and five microservices.",
      "W3C `traceparent` header propagated on every hop. Structured logs include `traceId`, `spanId`. Business `correlationId` in baggage for support tickets.",
      "**Implementation:**\n- OpenTelemetry auto-instrument ASP.NET, HttpClient\n- APIM injects trace context if missing\n- Service Bus messages carry trace context in application properties\n\n**Architect:** 100% sampling in dev; head-based 1–10% in prod with tail sampling for errors.\n\n**Support:** User provides order ID → lookup trace → see full waterfall.",
      "Correlation is debugging microservices at scale.",
      "Baggage vs span attributes? — Baggage propagates; keep small — no PII.",
      "Trace ID in ProblemDetails? — Return correlation ID to client for support.",
      "No trace propagation on async messages",
      "Different trace format per service",
      "100% sampling at 50K RPS"),
    q("Health Check Aggregation", "Operations", "Common",
      "Design `/health` for Kubernetes — liveness vs readiness vs dependency checks.",
      "Liveness: process alive — restart if fails. Readiness: can accept traffic — exclude from LB. Dependency checks in readiness only for critical path — not every downstream.",
      "**ASP.NET Core:**\n```csharp\nbuilder.Services.AddHealthChecks()\n    .AddSqlServer(conn, name: \"db\", tags: [\"ready\"])\n    .AddCheck(\"self\", () => Healthy(), tags: [\"live\"]);\n```\n\n**Anti-pattern:** Liveness includes DB — DB blip kills all pods.\n\n**Architect:** Aggregate health at deploy gate — `can-i-deploy` + smoke, not deep checks on liveness.",
      "Health check design prevents cascading pod restarts.",
      "Startup probe? — Slow-init containers — prevent kill during warmup.",
      "Health check aggregation API? — Gateway polls services — circuit on unhealthy dependency.",
      "Liveness probe calls database",
      "Readiness always healthy — route to broken pods",
      "No differentiation live vs ready"),
    q("Config Externalization", "Operations", "Common",
      "Move microservice config from appsettings.json to external store — design approach.",
      "Azure App Configuration + Key Vault references. Feature flags, connection strings, tuning params. Refresh without redeploy via `IOptionsMonitor`.",
      "**Layers:**\n- **Static:** appsettings baseline defaults\n- **Environment:** App Config label `Production`\n- **Secrets:** Key Vault — never in App Config plaintext\n\n**Architect:** Config change audit trail, RBAC on keys, staged rollout per service. GitOps for infra; App Config for runtime tuning.",
      "External config enables safe runtime changes.",
      "Refresh interval? — Balance propagation speed vs API throttling.",
      "Config vs secrets boundary? — Secrets always Key Vault; config may reference vault URI.",
      "Secrets in appsettings committed to git",
      "No refresh — redeploy for timeout change",
      "Shared config key across services — coupling"),
    q("Feature Flags Per Service", "Operations", "Common",
      "Canary new inventory service with 10% traffic — feature flag architecture.",
      "LaunchDarkly / App Configuration feature flag `inventory-v2-routing`. Gateway or BFF evaluates flag by user ID percentage. Metrics compare error rate and latency v1 vs v2.",
      "**Patterns:**\n- **Percentage rollout:** hash(userId) % 100 < 10\n- **Allowlist:** internal testers first\n- **Kill switch:** instant 100% back to v1\n\n**Architect:** Flag per service not global monolith flag. Automate flag cleanup after full rollout — tech debt otherwise.",
      "Feature flags are microservices migration safety net.",
      "Flag evaluation at edge vs service? — Edge for routing; service for behavior toggles.",
      "Long-lived flags? — Review quarterly — remove stale.",
      "Hardcoded if-debug routing",
      "No metrics on flag cohorts",
      "Kill switch untested until incident"),
    q("Microservices Testing Pyramid", "Testing", "Common",
      "Define testing pyramid for microservices order domain.",
      "Many unit tests (domain logic), contract tests (Pact), integration tests (Testcontainers per service), few E2E smoke (critical paths only).",
      "**Layers:**\n1. **Unit:** aggregate rules, pricing — fast, no IO\n2. **Contract:** order ↔ payment, order ↔ inventory\n3. **Integration:** API + real DB in container — one service boundary\n4. **E2E:** checkout happy path staging — 5–10 scenarios max\n\n**Architect:** E2E suite >30 min blocks CI — invest in contracts and integration. Service virtualization for rare third parties.",
      "Right pyramid keeps microservices CI fast and reliable.",
      "Testcontainers? — Real Postgres/Redis in Docker for integration tests.",
      "E2E environment parity? — Staging mirrors prod topology scaled down.",
      "E2E only — 2 hour CI pipeline",
      "No contract tests between services",
      "Shared test database across parallel CI jobs"),
]
