"""Hand-crafted premium Q011–Q050 for Azure weeks 13–14 (networking & security)."""

from premium_qa_data import q

WEEK_13_Q011_Q050 = [
    q("VNet Peering", "Networking", "Very Common",
      "Design VNet peering for two workloads in the same region — what must you validate before peering?",
      "Non-overlapping address spaces, no transitive routing, peering is not gateway transit by default. Validate DNS resolution and effective routes after peering.",
      "**Pre-peering checklist:**\n- CIDR ranges must not overlap (10.0.0.0/16 vs 10.0.1.0/24 fails)\n- Decide `allowForwardedTraffic` and `allowGatewayTransit` / `useRemoteGateways`\n- Plan DNS — linked private zones or custom DNS forwarders\n\n**Architect:** Peering is non-transitive — if VNet A peers to Hub and Hub to VNet B, A cannot reach B without UDR or hub routing.\n\n**Cost:** Same-region peering data transfer is low cost but not free at scale — model chatty cross-VNet traffic.",
      "Peering mistakes cause day-one connectivity failures in landing zones.",
      "Can you peer overlapping VNets? — No — must redesign IP plan or use NAT/proxy.",
      "Global VNet peering? — Cross-region peering with higher latency and transfer cost.",
      "Assuming peering enables transitive routing",
      "Overlapping IP ranges discovered after deploy",
      "No post-peering effective route validation"),
    q("Hub-Spoke Design", "Networking", "Very Common",
      "Compare hub-spoke vs mesh for 15 application teams on Azure.",
      "Hub-spoke: centralized firewall, VPN/ER gateway, DNS, Bastion in hub; spokes peer to hub only. Mesh does not scale — 15 teams = 105 peering pairs and no central egress control.",
      "**Hub contains:** Azure Firewall or NVA, ExpressRoute/VPN gateway, Private DNS resolver, optional DDoS-protected public IPs.\n\n**Spoke rules:** Default route 0.0.0.0/0 → firewall private IP via UDR. No direct spoke-to-spoke peering.\n\n**Architect:** Hub-spoke is the enterprise default for policy enforcement, logging, and hybrid connectivity. Virtual WAN is the managed evolution at 50+ sites.",
      "Hub-spoke demonstrates centralized governance thinking.",
      "When mesh is acceptable? — Small estates (<5 VNets) with low security requirements.",
      "Shared hub across subscriptions? — Yes — peering and RBAC at subscription scope.",
      "Full mesh peering between all team VNets",
      "Spoke internet egress bypassing hub firewall",
      "Hub without redundant gateway for production hybrid"),
    q("Azure Firewall", "Networking", "Very Common",
      "When choose Azure Firewall vs NSG for egress control?",
      "Azure Firewall: centralized FQDN filtering, threat intel, TLS inspection (Premium), DNAT, forced tunneling — hub appliance. NSG: subnet/NIC stateful L3-L4 rules — micro-segmentation.",
      "**Azure Firewall use cases:**\n- Central egress allow-list by FQDN (`*.microsoft.com`)\n- SNAT for spoke outbound with logging to Log Analytics\n- Application rules for HTTP/HTTPS without opening all ports\n\n**Architect:** Firewall Policy (hierarchical) for enterprise — parent policy in platform team, child policies per environment. Premium SKU for IDPS and TLS inspection when compliance requires.",
      "Firewall vs NSG is a classic Azure architect layering question.",
      "Firewall vs third-party NVA? — Azure Firewall is fully managed; NVA when deep packet inspection vendor required.",
      "Firewall in forced tunneling mode? — All internet via on-prem — UDR + BGP configuration.",
      "Replacing NSG entirely with firewall only",
      "Basic SKU when FQDN filtering required",
      "No diagnostic logs to Log Analytics"),
    q("NSG vs ASG", "Networking", "Very Common",
      "Explain NSG vs Application Security Group — how combine for 3-tier app?",
      "NSG: L3-L4 rules on subnet or NIC. ASG: logical grouping of NICs — rules reference ASG not IP. Combine: `WebServers` ASG → `AppServers` ASG port 443.",
      "**Example rules:**\n- Inbound 443 to `WebServers` ASG from App Gateway subnet\n- Inbound 443 to `AppServers` ASG from `WebServers` ASG\n- Inbound 1433 to `SqlServers` ASG from `AppServers` ASG only\n\n**Architect:** ASG rules survive VM reprovisioning — no IP churn in rule sets. Implicit deny remains — last rule is not explicit allow-all.",
      "ASG shows micro-segmentation maturity beyond IP-based NSG.",
      "NSG on subnet vs NIC? — Both possible — avoid conflicting rules; prefer subnet for consistency.",
      "ASG across VNets? — ASG is VNet-scoped only.",
      "Hardcoded VM IPs in NSG rules",
      "Allow all VNet inbound for convenience",
      "NSG on subnet and NIC with contradictory rules"),
    q("Route Tables UDR", "Networking", "Very Common",
      "Spoke VMs reach internet without going through hub firewall — diagnose with UDR.",
      "Check effective routes on NIC: `0.0.0.0/0` may point to Internet via system route overriding intent. Associate UDR on subnet, disable BGP route propagation if needed, verify firewall as next hop.",
      "**Common causes:**\n- UDR not associated to subnet\n- System route preferred over custom (wrong next hop type)\n- `0.0.0.0/0` on firewall but asymmetric return path\n\n**Architect:** Use Network Watcher 'Effective routes' before and after UDR changes. Document route table per spoke tier (web, app, data).",
      "UDR debugging separates senior network architects from beginners.",
      "Service endpoint routes and UDR? — May need `Microsoft.Storage` routes — test PaaS after UDR.",
      "Route Server for BGP? — Hub firewall advertises routes via BGP to spokes.",
      "UDR on wrong subnet (app tier not web tier)",
      "Forgot to disable BGP propagation when required",
      "Asymmetric routing without firewall SNAT"),
    q("VPN Gateway", "Hybrid", "Very Common",
      "Design site-to-site VPN for hybrid Azure — SKU and redundancy?",
      "VpnGw2+ for production throughput. Active-active dual tunnels from on-prem to Azure VPN gateway in hub VNet. Use route-based (BGP optional) VPN.",
      "**Design:**\n- Gateway subnet `/27` minimum in hub VNet\n- Local network gateway represents on-prem CIDR\n- Connection with shared key or IKEv2\n\n**Architect:** VPN for dev/pilot or backup to ExpressRoute. Plan bandwidth — VpnGw3 ~1.25 Gbps aggregate. Always second tunnel or second on-prem device for HA.",
      "VPN is the fast path to hybrid — architects know limits.",
      "Policy-based vs route-based VPN? — Route-based only for most Azure scenarios.",
      "Point-to-site VPN? — Developer remote access — separate from site-to-site.",
      "Gateway subnet too small (/28)",
      "Single tunnel production with no failover",
      "VPN as primary without bandwidth planning"),
    q("ExpressRoute", "Hybrid", "Very Common",
      "ExpressRoute architecture for production hybrid — what components required?",
      "ExpressRoute circuit (provider), ExpressRoute gateway in hub VNet, routing via BGP, optional ExpressRoute FastPath for data plane performance.",
      "**Redundancy:** Dual circuits from diverse peering locations or providers — Microsoft requires diverse for SLA.\n\n**Architect:** ExpressRoute for predictable latency, high bandwidth, and private connectivity (not over public internet). Pair with VPN as Microsoft → 'ExpressRoute with VPN failover' pattern.\n\n**Peering types:** Private (to VNet), Microsoft (to M365/Azure PaaS public endpoints), Public (legacy).",
      "ExpressRoute is enterprise hybrid default for critical workloads.",
      "ExpressRoute Direct? — 100 Gbps dedicated port at peering location.",
      "Circuit provider vs Microsoft peering? — You buy circuit from Equinix/AT&T etc.; Microsoft provides ER gateway.",
      "Single circuit production",
      "Wrong peering type for workload (Public vs Private)",
      "No VPN backup for circuit maintenance window"),
    q("ExpressRoute Global Reach", "Hybrid", "Common",
      "When use ExpressRoute Global Reach?",
      "Connect two on-prem datacenters via Azure backbone using ExpressRoute circuits — traffic hairpins through Microsoft global network without traversing corporate WAN.",
      "**Use case:** Merger integration — Datacenter A and B each have ER to Azure; Global Reach links them via Azure.\n\n**Architect:** Requires premium circuit SKUs at both ends. Alternative: VPN between on-prem sites + Azure as hub.\n\n**Not for:** General Azure VNet-to-VNet — use peering or Virtual WAN.",
      "Global Reach shows advanced hybrid routing knowledge.",
      "Global Reach vs VNet peering? — Global Reach is on-prem to on-prem via Azure ER; peering is Azure VNet to VNet.",
      "Bandwidth limits? — Depends on circuit SKU — validate with provider.",
      "Using Global Reach for Azure VNet connectivity",
      "Single region ER without Global Reach planning",
      "No route filtering between on-prem sites"),
    q("Virtual WAN", "Networking", "Common",
      "Virtual WAN vs manual hub-spoke — when migrate to vWAN?",
      "vWAN when 20+ branch sites, SD-WAN integration, automated spoke onboarding, or global transit hub needed. Manual hub-spoke fine for centralized Azure-only estate.",
      "**vWAN components:** Virtual hub (managed), VPN/ExpressRoute gateways, Azure Firewall in hub, branch connections.\n\n**Architect:** vWAN reduces operational toil — spokes connect via `Virtual network connection` not manual peering matrix. Hub routing intent policies control inter-spoke traffic.\n\n**Trade-off:** Less granular control than DIY NVA; cost model differs from manual hub.",
      "vWAN is the scale answer for multi-site Azure networking.",
      "vWAN secure hub? — Built-in Azure Firewall deployment in vWAN hub.",
      "SD-WAN CPE integration? — Partner devices connect as branch to vWAN.",
      "vWAN for 3 VNets only — over-engineering",
      "Manual peering alongside vWAN without plan",
      "Ignoring vWAN routing policy for spoke isolation"),
    q("Azure DNS Private Zones", "DNS", "Very Common",
      "Design private DNS zones for private endpoints across hub-spoke.",
      "Central private DNS zones in hub (`privatelink.database.windows.net`, `privatelink.blob.core.windows.net`). Link zones to all spoke VNets or use Private DNS Resolver.",
      "**Split-horizon:** Same FQDN resolves to private IP inside VNet, public IP outside.\n\n**Architect:** Auto-registration optional for VMs; private endpoints require A record (manual or via Terraform/Bicep). Document zone ownership — platform team manages all privatelink zones.",
      "Private DNS is mandatory for private endpoint success.",
      "Multiple zones same name linked to VNets? — One zone linked to many VNets — central model.",
      "Fallback to public DNS? — Conditional forwarder from on-prem for hybrid resolution.",
      "Private endpoint without DNS zone link",
      "Per-team duplicate private zones",
      "Hardcoding private IPs in connection strings"),
    q("DNS Forwarding", "DNS", "Common",
      "Hybrid DNS — on-prem resolves Azure private endpoints. Architecture?",
      "Azure Private DNS Resolver inbound endpoint in hub; on-prem DNS conditional forwarders send `database.windows.net` to resolver IP. Outbound endpoint forwards to on-prem for internal names.",
      "**Flow:** VM in Azure → Azure DNS → private zone. On-prem client → forward to Resolver inbound → Azure private zone.\n\n**Architect:** Avoid split-brain — document which zones live where. Test resolution from both sides before cutover.",
      "Hybrid DNS breaks more migrations than compute.",
      "Resolver vs custom DNS VM? — Managed Resolver preferred over IaaS DNS servers.",
      "DNS private resolver rulesets? — Forward specific domains to on-prem or internet.",
      "No conditional forwarding from on-prem",
      "Public DNS cache serving stale records after private link",
      "Single DNS server with no redundancy"),
    q("Traffic Manager", "Networking", "Common",
      "Traffic Manager vs Front Door for global routing?",
      "Traffic Manager: DNS-based load balancing, any endpoint (on-prem, Azure, external). Front Door: HTTP(S) reverse proxy at edge with WAF, caching, TLS.",
      "**Traffic Manager profiles:** Priority (active-passive DR), Weighted (canary), Performance (lowest latency), Geographic (compliance routing).\n\n**Architect:** Traffic Manager for non-HTTP (custom ports, legacy) or multi-cloud endpoints. Front Door for modern web APIs with WAF requirement.",
      "DNS vs anycast routing — know when each applies.",
      "Traffic Manager health probes? — HTTP/TCP probes remove unhealthy endpoints from DNS.",
      "Nested profiles? — Combine geographic + priority for complex DR.",
      "Traffic Manager for single-region app only",
      "TTL too high during failover (600s+)",
      "No health probe — stale DNS to dead endpoint"),
    q("Front Door vs CDN", "Networking", "Very Common",
      "Azure Front Door vs Azure CDN — when use each?",
      "Front Door: global L7 load balancer + WAF + routing to origins (App Service, AKS, on-prem). CDN (Standard/Premium): cache static assets at edge — often behind Front Door.",
      "**Pattern:** Front Door → CDN endpoint for static (`/assets/*`) → App Service for dynamic API.\n\n**Architect:** Front Door Premium for Private Link origins, advanced WAF, bot protection. CDN alone when only static content acceleration needed without origin load balancing.",
      "Edge architecture layers CDN caching on Front Door routing.",
      "Front Door vs App Gateway? — Front Door global; App Gateway regional — often combined.",
      "Caching rules? — CDN cache TTL vs dynamic API no-cache.",
      "CDN for dynamic API responses incorrectly cached",
      "Front Door without WAF on public endpoints",
      "Origin exposed publicly when Private Link available"),
    q("Private Link Service", "Networking", "Very Common",
      "Expose internal PaaS or IaaS service to consumers via Private Link Service?",
      "Provider creates Private Link Service on Standard ILB fronting your service; consumers create private endpoints in their VNets. Cross-tenant and cross-subscription supported.",
      "**Use case:** SaaS platform on Azure offering private connectivity to enterprise customers without public IPs.\n\n**Architect:** Approve connection requests manually or via automation. NAT IP mapping for SNAT. Document DNS — consumers need private DNS for your service FQDN.",
      "Private Link Service is the B2B private connectivity pattern.",
      "Private Link Service vs Private Endpoint? — Service is provider side; endpoint is consumer side.",
      "On-premises access? — ExpressRoute/VPN + private endpoint in connected VNet.",
      "Auto-approve all connection requests",
      "No ILB health probes on backend pool",
      "Consumer DNS not documented"),
    q("Private Endpoint DNS", "DNS", "Very Common",
      "Private endpoint created but app still connects to public SQL IP — fix?",
      "Create A record in `privatelink.database.windows.net` zone linked to VNet, or use `zoneGroup` on private endpoint for auto DNS. Verify `nslookup` from VM returns 10.x private IP.",
      "**Common gaps:**\n- Zone exists but not linked to VM's VNet\n- `hostNameInCertificate` mismatch when using custom DNS\n- App caches connection string resolved at startup\n\n**Architect:** Integrate private endpoint + private DNS in IaC template — never manual post-deploy.",
      "DNS is the #1 private endpoint failure mode.",
      "Integrate with on-prem DNS? — Conditional forward via Private DNS Resolver.",
      "Multiple endpoints same service? — Separate A records or CNAME chain.",
      "Private endpoint without private DNS zone",
      "Testing DNS from laptop not from VNet VM",
      "Disabling public endpoint while DNS still public"),
    q("NAT Gateway", "Networking", "Common",
      "When NAT Gateway vs Azure Firewall SNAT for outbound internet?",
      "NAT Gateway: scalable outbound SNAT for subnet — no FQDN filtering, simple, high SNAT ports. Firewall: filtered egress with logging and threat intel.",
      "**Architect:** NAT Gateway on spoke subnet when outbound-only internet needed (Windows updates, package repos) and hub firewall handles filtered traffic separately. Avoid mixing default routes — one SNAT path per subnet.\n\n**SNAT exhaustion:** NAT Gateway scales ports automatically; LB SNAT limited to 1024 ports per IP.",
      "SNAT architecture prevents mysterious outbound failures.",
      "NAT Gateway vs LB outbound rule? — NAT Gateway preferred for subnet-level outbound; LB SNAT for load-balanced VMs.",
      "IPv4 only? — NAT Gateway is IPv4 outbound.",
      "LB SNAT exhaustion at scale",
      "NAT Gateway and firewall both as 0.0.0.0/0 next hop",
      "No monitoring of SNAT failed connections"),
    q("Bastion Host", "Operations", "Very Common",
      "Secure VM admin access without public RDP/SSH?",
      "Deploy Azure Bastion in hub VNet — admin connects via portal/CLI over HTTPS. VMs have no public IPs. Standard SKU for session recording.",
      "**Alternatives:** JIT access via Defender for Cloud, private jump box with PIM.\n\n**Architect:** Bastion subnet `AzureBastionSubnet` /26 minimum. NSG rules per Microsoft requirements. Integrate with Entra ID for conditional access on portal access.",
      "Bastion eliminates public management plane exposure.",
      "Bastion vs VPN jump box? — Bastion zero inbound ports; jump box needs VNet connectivity design.",
      "Native client support? — Bastion Standard supports native RDP/SSH clients.",
      "Public RDP 'temporarily' for troubleshooting",
      "Bastion in spoke without hub connectivity to VMs",
      "Shared local admin credentials"),
    q("DDoS Protection", "Security", "Common",
      "DDoS Network Protection vs IP Protection — when enable?",
      "Network Protection: protects all public IPs in VNet. IP Protection: per protected IP. Enable for revenue-critical public endpoints with DDoS telemetry to SOC.",
      "**Layers:** DDoS (volumetric L3-L4) + WAF (L7) + rate limiting at APIM.\n\n**Architect:** DDoS Protection Plan associated to VNet. Alert thresholds in Monitor. Runbook for attack — Microsoft scrubs traffic automatically on protected resources.",
      "DDoS is availability architecture not optional for public commerce.",
      "DDoS vs WAF overlap? — Complementary — volumetric vs application attacks.",
      "Simulation testing? — Contact Microsoft for DDoS simulation prior to go-live.",
      "Public ecommerce without DDoS plan",
      "Assume Front Door alone stops all attacks",
      "No runbook for DDoS alert escalation"),
    q("Network Watcher", "Operations", "Common",
      "Key Network Watcher capabilities for architects?",
      "Topology view, NSG flow logs, connection monitor, packet capture, VPN troubleshoot, next hop analysis, IP flow verify.",
      "**Architect workflow:**\n1. IP flow verify — is traffic allowed?\n2. Next hop — where does packet route?\n3. Connection troubleshoot — end-to-end latency and path\n\nEnable flow logs to Storage or Log Analytics for traffic analytics and anomaly detection.",
      "Network Watcher is first-line hybrid connectivity debug tool.",
      "Flow logs vs NSG diagnostics? — Flow logs are long-term traffic records; diagnostic settings for audit.",
      "Traffic analytics? — Log Analytics solution on flow logs.",
      "Debugging routing without effective routes check",
      "Flow logs disabled to save cost on prod",
      "Packet capture left running indefinitely"),
    q("Packet Capture", "Operations", "Occasional",
      "When use Network Watcher packet capture vs NSG flow logs?",
      "Packet capture: deep debug specific VM NIC — short duration, high detail. Flow logs: continuous metadata (5-tuple, allow/deny) for all NSG-associated traffic.",
      "**Capture limits:** Storage account for `.cap` files — analyze in Wireshark. Stop capture after issue reproduced — storage and performance impact.\n\n**Architect:** Packet capture for 'connection reset' mysteries; flow logs for baseline and compliance. Require change ticket for production capture.",
      "Right diagnostic tool for network triage.",
      "Filters on packet capture? — Filter by IP/port to reduce capture size.",
      "Mirror vs capture? — Azure does local NIC capture not SPAN port.",
      "Permanent packet capture on production NIC",
      "Capture without storage account lifecycle policy",
      "Confusing flow logs with full packet capture"),
    q("Connection Troubleshoot", "Operations", "Common",
      "Connection troubleshoot reports 'Unreachable' between VM and SQL private endpoint — steps?",
      "Verify NSG/ASG allow path, UDR next hop, private DNS resolution to 10.x, private endpoint NIC in correct subnet, SQL firewall disabled (private link only).",
      "**Network Watcher connection troubleshoot** tests TCP from VM to destination — reports hop failures.\n\n**Architect:** Document connectivity matrix (source subnet → destination → port → rule). Automate validation in deployment pipeline with test VM.",
      "Systematic connectivity debug impresses in incident scenarios.",
      "User-defined route blocking? — Effective routes show blackhole.",
      "Private endpoint in wrong subnet? — Must be dedicated subnet recommended.",
      "Testing from developer laptop not VNet",
      "Public SQL firewall rule left enabled masking DNS issue",
      "Skip DNS verification step"),
    q("IP Groups", "Networking", "Common",
      "Azure Firewall IP Groups — use case?",
      "Named collections of IP ranges/CIDRs referenced in firewall rules — simplify management of on-prem datacenter ranges, partner networks, banned IPs.",
      "**Example:** `OnPrem-Datacenters` IP Group in allow rules instead of 20 individual CIDR entries.\n\n**Architect:** Central platform team maintains IP Groups; application teams reference in child Firewall Policies. Update group once — all rules inherit.",
      "IP Groups reduce firewall rule sprawl.",
      "IP Groups vs ASG? — IP Groups for firewall/NVA external CIDRs; ASG for Azure NIC grouping.",
      "Cross-policy reference? — IP Groups are regional resource referenced by policies.",
      "Hardcoded CIDRs in every firewall rule",
      "Stale IP Group after datacenter migration",
      "No ownership for IP Group updates"),
    q("Service Tags", "Networking", "Very Common",
      "Use service tags in NSG and Firewall rules — example?",
      "Service tags represent Azure service IP prefixes — `Sql`, `Storage`, `AzureKeyVault`, `AzureActiveDirectory`. Rule: allow outbound to `Sql` from app subnet without maintaining Microsoft IP list.",
      "**Architect:** Prefer service tags over `0.0.0.0/0` for PaaS access. Combine with Private Link — service tag rules become fallback or unnecessary when all traffic is private.\n\n**Regional tags:** `Sql.WestEurope` when scoping to region.",
      "Service tags show Azure-native rule authoring.",
      "Service tag updates? — Microsoft maintains — rules auto-update unlike manual IP lists.",
      "Service tags on-prem? — Available for hybrid allow rules to Azure services.",
      "Allow all internet because PaaS IPs change",
      "Service tag when Private Link should be used",
      "Wrong regional service tag scope"),
    q("Forced Tunneling", "Hybrid", "Common",
      "Force all Azure internet egress through on-prem firewall — design?",
      "UDR default route to NVA/firewall OR ExpressRoute with forced tunneling — internet breakout via on-prem inspection before exiting.",
      "**Azure Firewall forced tunneling:** Firewall learns default route via BGP from on-prem; SNAT on-prem or on firewall per design.\n\n**Architect:** Watch asymmetric routing and hairpin latency. Document exception paths for Azure PaaS service tags that must not tunnel.",
      "Forced tunneling satisfies 'all egress inspected' compliance.",
      "Split tunnel exceptions? — Route Azure service tag prefixes direct to Azure backbone.",
      "Performance impact? — All internet RTT adds on-prem hop — model latency.",
      "Forced tunnel without bandwidth sizing",
      "Asymmetric routing breaking TCP sessions",
      "No break-glass direct egress path"),
    q("Active-Active VPN", "Hybrid", "Common",
      "Active-active VPN gateway configuration benefits?",
      "Two public IPs on Azure VPN gateway, two tunnels from on-prem — aggregate throughput and redundancy. On-prem requires dual VPN devices or dual tunnels.",
      "**Architect:** Active-active for production hybrid backup to ExpressRoute or primary VPN at scale. BGP over VPN for dynamic route exchange.\n\n**Failover:** One tunnel down — traffic flows remaining tunnel; monitor both.",
      "Active-active shows HA hybrid design.",
      "Active-active vs active-passive? — Active-active uses both paths simultaneously.",
      "Policy-based with active-active? — Route-based required.",
      "Single tunnel labeled 'active-active'",
      "No monitoring per tunnel status",
      "Asymmetric routing with dual paths unplanned"),
    q("BGP with ExpressRoute", "Hybrid", "Common",
      "How BGP works with ExpressRoute gateway?",
      "Microsoft and customer exchange routes via BGP sessions over private peering — Azure advertises VNet prefixes; customer advertises on-prem prefixes. Enables dynamic routing without static UDRs.",
      "**Architect:** Set connection weight for primary/backup paths. Route filters limit prefixes advertised. AS path prepending for traffic engineering.\n\n**Warning:** Overlapping prefixes between on-prem and Azure cause blackholes — IP plan governance critical.",
      "BGP is how hybrid routing scales beyond static routes.",
      "BGP vs static UDR? — BGP for dynamic failover; UDR for forced default route to firewall.",
      "ExpressRoute Microsoft peering BGP? — Separate session for Office 365/Azure public prefixes.",
      "Overlapping BGP advertised prefixes",
      "No route filter on large prefix advertisements",
      "Static routes conflicting with BGP learned routes"),
    q("VNet Encryption", "Security", "Occasional",
      "Azure VNet encryption — what does it protect?",
      "Encrypts VNet traffic between VMs within a VNet (and peered VNets with encryption enabled) using MACsec-like capability on Azure infrastructure — defense against physical layer interception within Azure datacenter.",
      "**Architect:** Enable at VNet creation (cannot enable later on existing in some cases — verify current docs). Performance overhead minimal for most workloads. Complements TLS in transit at app layer — not replacement.",
      "VNet encryption is defense-in-depth for regulated workloads.",
      "VNet encryption vs TLS? — VNet encryption is network fabric; TLS is application payload.",
      "Peering with encryption? — Both VNets must enable for encrypted peering traffic.",
      "VNet encryption replaces application TLS",
      "Enable on existing VNet without validation",
      "Assume encryption covers internet egress"),
    q("MACsec", "Security", "Occasional",
      "MACsec on ExpressRoute Direct — when required?",
      "Layer 2 encryption between customer router and Microsoft edge on ExpressRoute Direct — financial/regulated workloads requiring link-layer encryption beyond IPsec.",
      "**Architect:** MACsec on ER Direct physical port — complementary to IPsec/Private Peering BGP routes. Plan key exchange and cipher suites with network team.\n\n**Not available:** Standard provider-based ExpressRoute shared ports — Direct only.",
      "MACsec shows deep compliance networking knowledge.",
      "MACsec vs IPsec VPN? — MACsec is L2 on dedicated link; IPsec is L3 tunnel.",
      "Key rotation MACsec? — Follow Microsoft ER Direct MACsec key lifecycle.",
      "MACsec on standard ExpressRoute circuit",
      "MACsec as only encryption layer for data at rest",
      "No network team coordination for Direct"),
    q("Load Balancer Outbound SNAT", "Networking", "Common",
      "Standard LB outbound SNAT exhaustion — symptoms and fixes?",
      "Symptoms: intermittent outbound TCP failures, 'Cannot assign requested address'. Cause: 1024 ports per frontend IP shared across backend pool VMs.",
      "**Fixes:**\n1. Add backend VMs to reduce ports-per-VM (counterintuitive — more VMs share pool)\n2. Dedicated outbound rule with extra public IPs\n3. NAT Gateway on subnet (recommended for new designs)\n\n**Architect:** Allocate min 40 ports per VM guideline — calculate `ports = 1024 / VM count` for planning.",
      "SNAT exhaustion is classic Azure VM outbound mystery.",
      "Outbound rules vs default SNAT? — Explicit outbound rule with multiple IPs scales ports.",
      "Connection idle timeout? — Reduce long-lived idle connections consuming ports.",
      "Ignore SNAT in architecture review",
      "Single public IP large VM scale set",
      "No alert on SNAT failed metric"),
    q("Cross-Subscription Peering", "Networking", "Common",
      "VNet peering across subscriptions — permissions and design?",
      "User needs Network Contributor on both VNets. Peering created in both directions (initiator + accepter). Use for platform hub in connectivity subscription, spokes in app subscriptions.",
      "**Architect:** RBAC at subscription — platform team owns hub subscription. Automate peering via pipeline with managed identity. Document subscription ID mapping in landing zone.",
      "Cross-subscription peering is standard landing zone pattern.",
      "Cross-tenant peering? — Possible with B2B guest access and peering request.",
      "Global peering cross-subscription? — Supported — watch data transfer billing.",
      "Insufficient RBAC on one subscription side",
      "Peering only one direction",
      "Assuming policy inherits across subscription boundary"),
    q("IPv6 Dual Stack", "Networking", "Occasional",
      "Dual-stack IPv4/IPv6 on Azure VNet — considerations?",
      "Azure supports IPv6 on VNets, LB, App Service (limited), Public IP dual stack. Not all PaaS services IPv6-native — verify per service.",
      "**Architect:** IPv6 for internet-facing apps where mobile/carrier IPv6 required. Internal east-west often IPv4-only sufficient. DNS AAAA records required. NSG rules must include IPv6 address space.",
      "Dual-stack when business requires IPv6 client reachability.",
      "IPv6 only VNet? — Rare — dual stack is typical migration path.",
      "ExpressRoute IPv6? — Supported on private peering — verify provider.",
      "IPv6 public without NSG hardening",
      "Forgot AAAA DNS records",
      "Assumed all Azure PaaS supports IPv6"),
    q("Network Segmentation Zero Trust", "Security", "Very Common",
      "Implement Zero Trust network segmentation on Azure?",
      "Assume breach — verify explicitly. Micro-segment with NSG/ASG, Private Link for PaaS, Conditional Access, no flat VNet trust, JIT admin access, continuous monitoring.",
      "**Principles:**\n- Never trust VNet membership alone for authorization\n- Identity + network + app layer checks\n- Least privilege east-west traffic\n\n**Architect:** Segment by data classification — PCI subnet isolated with separate firewall policy.",
      "Zero Trust is identity + network + data — not product name only.",
      "Zero Trust vs traditional perimeter? — Perimeter still exists but not sole control.",
      "Microsoft Zero Trust deployment guide? — Map to CA, Defender, Purview pillars.",
      "Flat VNet — all subnets talk freely",
      "Network location as sole trust signal",
      "Zero Trust without identity verification"),
    q("Micro-Segmentation", "Security", "Very Common",
      "Micro-segmentation strategy for microservices on AKS?",
      "Azure CNI with network policies (Calico/Cilium), NSG on node subnet, service mesh mTLS optional, Private Link to backing stores.",
      "**Layers:**\n- Deny all between namespaces by default\n- Allow explicit namespace-to-namespace on ports\n- Ingress controller WAF for north-south\n\n**Architect:** Start with Kubernetes NetworkPolicy — add service mesh when mTLS and L7 policy required.",
      "Micro-segmentation beyond coarse subnet NSG.",
      "Service mesh vs network policy? — Policy is L3-L4 K8s; mesh adds L7 and mTLS.",
      "AKS Azure CNI required? — Network policies need Azure CNI (not kubenet).",
      "All pods in cluster flat network",
      "NSG allow all within VNet",
      "Micro-segmentation without observability on denied flows"),
    q("Application Security Groups Deep Dive", "Networking", "Common",
      "Refactor 200 IP-based NSG rules to ASGs — approach?",
      "Inventory VMs by tier role, create ASGs (`WebTier`, `AppTier`, `DataTier`), assign NICs to ASGs, replace IP rules with ASG-to-ASG rules, decommission IP rules.",
      "**Migration:** Enable in audit mode with flow logs — verify traffic patterns before removing old rules.\n\n**Architect:** ASG naming standard in landing zone policy. Automate ASG assignment in VM deployment template.",
      "ASG migration reduces operational toil at scale.",
      "Multiple ASGs per NIC? — Yes — NIC can belong to multiple ASGs.",
      "ASG with scale sets? — Apply ASG to scale set NIC configuration.",
      "Big-bang rule cutover without flow log validation",
      "ASG per VM instead of per tier",
      "Forgetting to assign new VMs to ASG"),
    q("Firewall Policy DNAT", "Networking", "Common",
      "Publish internal web server via Azure Firewall DNAT?",
      "Firewall public IP + DNAT rule: external 443 → internal 10.0.1.4:443. Source filter restrict to known IPs if possible.",
      "**Architect:** Prefer Front Door/App Gateway for web publishing with WAF — use Firewall DNAT for non-HTTP or hub-centric designs. Log all DNAT hits to Log Analytics.\n\n**SNAT return path:** Firewall performs SNAT for return — internal server sees firewall IP as source.",
      "DNAT is hub ingress pattern — know alternatives.",
      "DNAT vs ILB? — DNAT through firewall for inspected ingress.",
      "Multiple DNAT rules same IP different ports? — Supported — map ports to different internals.",
      "DNAT without WAF for public HTTP",
      "Any source on DNAT rule",
      "Internal server default gateway wrong for asymmetric"),
    q("TLS Inspection", "Security", "Occasional",
      "Azure Firewall Premium TLS inspection — trade-offs?",
      "Decrypt HTTPS for IDPS and URL filtering — requires corporate CA cert deployed to clients/servers. Privacy and compliance implications.",
      "**Architect:** Enable only where policy mandates — exclude banking/health categories. Document exception list. Performance overhead on firewall SKU.\n\n**Alternative:** East-west mTLS within app layer without central TLS break.",
      "TLS inspection is compliance decision not default enable.",
      "Certificate pinning apps? — Break with inspection — maintain bypass list.",
      "Outbound vs inbound inspection? — Both configurable in Premium policy.",
      "Enable TLS inspection without legal/compliance review",
      "Default CA not deployed to all clients",
      "Inspect all traffic including Azure service tags unnecessarily"),
    q("Proxy Architecture", "Networking", "Common",
      "Design explicit proxy for outbound internet from Azure workloads?",
      "Squid/NVA or Azure Firewall as forward proxy — apps configured with `HTTP_PROXY` env var. UDR forces traffic to proxy; direct internet blocked.",
      "**Architect:** Central proxy enables URL categorization, authentication, logging. Container egress via proxy sidecar or cluster-wide policy.\n\n**PaaS exception:** App Service regional VNet integration may need service endpoints/Private Link instead of proxy for Azure services.",
      "Explicit proxy for regulated egress filtering.",
      "Transparent vs explicit proxy? — Explicit requires app config; transparent uses UDR redirect.",
      "Proxy HA? — Scale proxy VMSS behind ILB in hub.",
      "Proxy as single VM SPOF",
      "Apps not configured for proxy — bypass fails open",
      "No proxy logging to SIEM"),
    q("Egress Filtering", "Security", "Very Common",
      "Egress filtering strategy for PCI subnet on Azure?",
      "Default deny outbound from PCI subnet UDR — allow explicit FQDN via Azure Firewall application rules, deny direct internet, Private Link to required PaaS only.",
      "**Allow list:** Package repos (nuget.org via mirror), Microsoft Update service tags, specific API partners.\n\n**Architect:** Log all denied egress — tune rules monthly. Break-glass rule with approval workflow for emergency domains.",
      "Egress control prevents data exfiltration architecture.",
      "Egress vs ingress focus? — Architects often neglect outbound — attackers use egress.",
      "FQDN tag AzureBackup? — Allow required service tag rules for backup agents.",
      "Allow all outbound from app subnet",
      "Egress filter without logging",
      "Block Azure service tags breaking PATCH operations"),
    q("Hybrid DNS", "DNS", "Very Common",
      "End-to-end hybrid DNS for Active Directory integrated zones?",
      "Domain controllers on-prem authoritative for `corp.contoso.com`; Azure VMs join domain via VPN/ER. Azure Private DNS Resolver bridges Azure-specific privatelink zones.",
      "**Architect:** Avoid split-brain AD DNS — single authoritative source. Azure DCs in hub if Azure-native DR for AD required.\n\n**Test:** `nslookup` internal names from Azure VM and from on-prem client.",
      "Hybrid DNS + AD is common enterprise migration path.",
      "Azure AD DS vs AD DS DNS? — Managed domain has own DNS — different pattern.",
      "DNS forwarder on Azure VM? — Prefer Private DNS Resolver managed.",
      "Duplicate AD DNS zones Azure and on-prem",
      "Dynamic DNS updates blocked by firewall",
      "No DNS monitoring on resolution failures"),
    q("Network Monitoring", "Observability", "Very Common",
      "Network monitoring architecture for Azure landing zone?",
      "NSG flow logs → Log Analytics Traffic Analytics, Connection Monitor synthetic probes, Azure Monitor alerts on VPN/ER gateway metrics, Firewall diagnostic logs, DDoS alerts.",
      "**Dashboards:** Cross-region latency, top talkers, denied flow trends, VPN tunnel status.\n\n**Architect:** Define SLO for hub connectivity — alert ER BGP session down within 1 minute. Integrate Sentinel for correlation with security events.",
      "Network observability prevents long MTTR on hybrid incidents.",
      "SNMP on Azure? — Limited — use platform metrics and flow logs.",
      "Packet capture automation? — Logic App triggered on alert for brief capture.",
      "No flow logs in production",
      "Alerts without runbook links",
      "Monitoring only Azure not on-prem path"),
]

WEEK_14_Q011_Q050 = [
    q("Microsoft Defender for Cloud", "Security", "Very Common",
      "How integrate Defender for Cloud into architecture governance?",
      "Enable Defender CSPM + workload plans (Servers, SQL, Storage, App Service). Secure score tracks posture. Critical recommendations block deploy via policy/CI gate.",
      "**Architect workflow:**\n- Weekly secure score review in platform team\n- Regulatory compliance dashboard mapped to SOC2/ISO\n- Agentless and agent-based scanning per workload\n\n**Integration:** Export to Sentinel for correlation; assign recommendation owners in workload teams.",
      "Defender for Cloud is continuous compliance not point-in-time audit.",
      "Defender CSPM vs CWP? — CSPM posture; CWP runtime threat protection per plan.",
      "Defender for DevOps? — Scan IaC and secrets in GitHub/Azure DevOps repos.",
      "Defender disabled in prod to save cost",
      "Critical findings with no owner",
      "Secure score ignored in architecture review"),
    q("Defender for App Service", "Security", "Common",
      "Defender for App Service detects what threats?",
      "Cryptomining, suspicious IP access, MITM indicators, environment variable theft, communication with malicious IPs — runtime anomaly on App Service.",
      "**Architect:** Enable on all internet-facing App Services. Pair with WAF and Private Link. Alerts to Sentinel playbook for auto-disable site on critical.",
      "Runtime PaaS protection beyond network perimeter.",
      "Defender App Service vs WAF? — Defender runtime anomalies; WAF request inspection.",
      "Enable on Functions? — Separate Defender plan for App Service covers Functions on same plan tier.",
      "App Service public with Defender only defense",
      "Ignore Defender alerts as false positives",
      "No integration with incident response"),
    q("Defender for SQL", "Security", "Very Common",
      "Defender for SQL vulnerability assessment workflow?",
      "Weekly scan for misconfigurations ( excessive permissions, TDE off), surface results in Defender portal, remediate via baseline template, track in secure score.",
      "**Architect:** Enable Advanced Threat Protection alerts (SQL injection, anomalous access). VA results feed CI/CD — fail deploy if critical on prod.\n\n**Managed Instance + SQL DB:** Same Defender SQL plan.",
      "Database security is layered — TDE + Defender + network.",
      "ATP vs VA? — ATP real-time threats; VA configuration baseline.",
      "Azure SQL vs SQL on VM? — Defender for SQL covers PaaS; Servers plan for IaaS.",
      "Public SQL endpoint with VA only",
      "VA critical findings unremediated months",
      "No alert routing for SQL injection attempt"),
    q("Defender for Storage", "Security", "Common",
      "Defender for Storage — key detections?",
      "Unusual access patterns, malware upload, anonymous access enabled, suspicious IP geographies accessing blobs.",
      "**Architect:** Enable on storage with sensitive data. Malware scanning on upload for user content buckets. Restrict to Private Link + disable public blob access via policy.",
      "Storage is exfiltration target — Defender adds anomaly layer.",
      "Malware scanning vs Defender? — On-upload scan feature complement detections.",
      "Storage analytics logs? — Enable for forensic correlation.",
      "Public containers with sensitive data",
      "Defender Storage disabled for cost",
      "No alert on anonymous access detection"),
    q("Security Score Improvement", "Governance", "Common",
      "Raise secure score from 45% to 80% — prioritized approach?",
      "Fix critical/high recommendations affecting score weight first: MFA, external exposure, unpatched CVEs, missing encryption. Assign owners per subscription.",
      "**Architect:**\n1. Export recommendations to spreadsheet/work item tracker\n2. Quick wins: disable public access, enable MFA, diagnostic logs\n3. Policy DeployIfNotExists for recurring gaps\n\nTrack weekly score trend — not one-time project.",
      "Secure score prioritization shows operational security leadership.",
      "Score vs compliance? — Score is Microsoft best practices; compliance adds regulatory controls.",
      "Exemptions? — Document risk acceptance for impossible fixes.",
      "Chasing 100% score ignoring business risk",
      "Fix low-impact items first for vanity score",
      "No score tracking over time"),
    q("Regulatory Compliance Dashboard", "Compliance", "Common",
      "Use Defender regulatory compliance dashboard for SOC 2?",
      "Maps Azure Security Benchmark and regulatory standards to control pass/fail. Drill into failing controls → linked recommendations → remediation.",
      "**Architect:** Export compliance PDF for auditors quarterly. Custom initiative for org-specific controls. Not replacement for formal audit — evidence accelerator.",
      "Compliance dashboard bridges engineering and audit conversations.",
      "SOC2 vs ISO27001 in dashboard? — Select standard — overlapping controls deduplicated.",
      "Custom compliance standard? — Import custom policy initiative mapped to controls.",
      "Assume green dashboard equals audit pass",
      "No evidence collection for control",
      "Compliance only checked before audit season"),
    q("Key Vault Architecture", "Security", "Very Common",
      "Design Key Vault topology for 10 microservices?",
      "Separate vault per environment (prod/nonprod) or per data classification — not one vault all secrets. RBAC not access policies. Private Link + diagnostic logs.",
      "**Patterns:**\n- Platform vault: infra secrets\n- App vault per bounded context: app-specific connection strings\n- Purge protection + soft delete on prod\n\n**Architect:** Managed identity access only — no secrets in pipeline variables.",
      "Key Vault topology prevents blast radius on compromise.",
      "Vault per app vs per env? — Trade isolation vs operational overhead — document standard.",
      "HSM-backed keys? — Premium/Managed HSM for CMK requiring FIPS 140-2 Level 3.",
      "Single vault all environments",
      "Access policies with broad secrets get/list",
      "Key Vault public endpoint production"),
    q("HSM vs Software Keys", "Security", "Common",
      "When HSM-backed keys vs software keys in Key Vault?",
      "HSM (Premium vault or Managed HSM): regulatory FIPS 140-2 Level 3, CMK for SQL/Storage with hardware protection. Software keys: dev, lower classification, cost sensitive.",
      "**Architect:** PCI/HIPAA workloads → HSM CMK. Rotation and access audit identical — key material non-exportable for HSM.\n\n**Cost:** HSM premium — justify per data classification policy.",
      "Key backing choice is compliance architecture decision.",
      "Managed HSM vs Key Vault Premium HSM? — Managed HSM dedicated HSM pool; Premium shared.",
      "BYOK? — Bring your own key to HSM — key never leaves your control.",
      "Software keys for PCI CMK requirement",
      "Exportable private keys in production",
      "No key access audit logging"),
    q("Managed HSM", "Security", "Occasional",
      "Azure Managed HSM vs Key Vault Premium — selection?",
      "Managed HSM: single-tenant HSM pool, FIPS 140-2 Level 3, PKCS#11, higher isolation for strict regulatory. Key Vault Premium: shared HSM, simpler integration with Azure PaaS CMK.",
      "**Architect:** Managed HSM when auditor requires dedicated HSM or PKCS#11. Key Vault Premium sufficient for most Azure CMK scenarios.\n\n**Integration:** Managed HSM supports fewer native PaaS integrations — validate service compatibility.",
      "Managed HSM for top-tier key isolation requirements.",
      "MHSM clustering? — Multi-region MHSM for DR — plan key replication.",
      "Cost model? — Managed HSM higher base cost — capacity planning required.",
      "Managed HSM without PKCS#11 need — overkill",
      "Assume all PaaS supports MHSM CMK",
      "No HSM access logging to SIEM"),
    q("Key Rotation Automation", "Security", "Very Common",
      "Automate Key Vault secret and certificate rotation?",
      "Event Grid notification on near-expiry; Azure Automation or Functions rotation function; dual-secret pattern for zero-downtime app refresh.",
      "**Certificates:** Auto-renew via App Service managed cert or Key Vault integration.\n\n**Architect:** Prefer Entra ID auth over SQL passwords — eliminates rotation. Test rotation game day quarterly.",
      "Automated rotation beats manual ticket-driven expiry incidents.",
      "Rotation function template? — Microsoft sample rotation function for Storage/SQL.",
      "CMK rotation? — Create new key version; re-encrypt or use latest automatically.",
      "Secrets with no expiry date",
      "Rotation breaks prod without staging test",
      "Manual rotation only documented in wiki"),
    q("Azure Sentinel SIEM", "Security", "Very Common",
      "Design Sentinel deployment for multi-subscription Azure estate?",
      "Central Log Analytics workspace in security subscription, Sentinel enabled, data connectors per source, RBAC for SOC analysts, watchlists and bookmarks.",
      "**Architect:** Data ingestion cost model — filter verbose logs at source. Retention tiering: hot 90 days, archive longer for compliance.\n\n**Workbooks:** Executive dashboard + tier-1 analyst triage view.",
      "Sentinel is cloud-native SIEM for Azure-first estates.",
      "Sentinel vs Defender portal alerts? — Sentinel correlates cross-source; Defender is workload-centric.",
      "Multi-workspace? — Single primary SOC workspace with LA agent — avoid sprawl.",
      "Every subscription separate workspace",
      "No ingestion cost monitoring",
      "Sentinel enabled without use cases defined"),
    q("Data Connectors Sentinel", "Security", "Common",
      "Essential Sentinel data connectors for Azure landing zone?",
      "Azure Activity, Azure AD (Entra ID), Defender for Cloud, DNS, Firewall, NSG flow (via LA), Key Vault diagnostics, Office 365 if applicable.",
      "**Architect:** Prioritize connectors mapping to MITRE tactics — identity, network, endpoint. Custom logs via AMA for third-party apps.\n\n**Validate:** Connector health blade — stale data equals blind SOC.",
      "Connector strategy defines detection coverage.",
      "AMA vs Log Analytics agent? — Azure Monitor Agent is current standard.",
      "CEF/Syslog connectors? — On-prem firewall and network gear.",
      "Sentinel with only Activity Log",
      "Connectors enabled without parsing rules",
      "No connector failure alerting"),
    q("KQL Detection Rules", "Security", "Very Common",
      "Write Sentinel detection strategy beyond built-in analytics?",
      "Custom scheduled query rules for org-specific TTPs: impossible travel, mass Key Vault access, new external forwarding rule, spike in failed auth.",
      "**Example KQL pattern:**\n```kql\nSigninLogs | where ResultType != 0 | summarize Failed=count() by UserPrincipalName, bin(TimeGenerated, 5m) | where Failed > 20\n```\n\n**Architect:** Tune false positives in staging rule mode. Map each rule to MITRE technique and incident severity.",
      "Custom KQL shows hands-on SOC architecture skill.",
      "NRT vs scheduled rules? — Near-real-time for high-severity; scheduled for batch patterns.",
      "Fusion ML? — Built-in multi-stage attack detection — enable.",
      "Copy generic KQL without tuning",
      "No suppression for known maintenance windows",
      "Rules without entity mapping for investigation"),
    q("SOAR Playbooks", "Security", "Common",
      "Sentinel automation playbook — disable compromised user scenario?",
      "Trigger: Sentinel incident with high-confidence identity compromise. Actions: Entra disable user, revoke sessions, reset password, notify SOC, create ServiceNow ticket.",
      "**Architect:** Human-in-the-loop approval for destructive actions in prod. Managed identity for playbook RBAC — least privilege.\n\n**Test:** Simulation in nonprod tenant before auto-containment prod.",
      "SOAR reduces MTTR when designed with guardrails.",
      "Logic Apps vs Automation? — Sentinel playbooks are Logic Apps ARM templates.",
      "Webhook vs native connector? — Prefer native Entra connector over custom API.",
      "Auto-disable user without approval on medium confidence",
      "Playbook service principal Contributor scope",
      "No playbook run history retention"),
    q("Microsoft Purview Compliance", "Compliance", "Common",
      "Microsoft Purview for data governance architecture?",
      "Purview scans Azure SQL, Storage, Synapse — classifies sensitive data, lineage maps ETL flows, compliance manager tracks control assessment.",
      "**Architect:** Register data sources in Purview account per environment. Auto-labeling policies push classifications to M365 and Azure.\n\n**Integration:** DLP policies use Purview sensitivity labels.",
      "Purview connects data discovery to compliance posture.",
      "Purview vs Defender? — Purview data governance; Defender threat protection.",
      "Lineage for ADF? — Purview captures copy activity lineage automatically.",
      "Scan prod without sampling strategy — cost",
      "Classifications without owner remediation workflow",
      "Purview deployed without label policy adoption"),
    q("Information Protection", "Security", "Common",
      "Sensitivity labels architecture for hybrid organization?",
      "Labels defined in Purview/Compliance center — encrypt, mark headers, control sharing. Auto-labeling rules on SQL/Storage scanned data.",
      "**Architect:** Label taxonomy aligned to data classification policy (Public, Internal, Confidential, Restricted). Mandatory labeling for email/docs via policy.",
      "Information protection extends beyond network perimeter.",
      "Labels vs DLP? — Labels classify; DLP enforces actions on classified content.",
      "Double key encryption? — Hold your own key for highest confidentiality.",
      "Too many labels — user confusion",
      "Labels optional not enforced",
      "No training on label application"),
    q("DLP Policies", "Security", "Common",
      "DLP policy for preventing credit card exfiltration?",
      "Purview DLP detects PCI patterns in Exchange, SharePoint, Teams, endpoints — block external share, alert SOC, require justification.",
      "**Architect:** Start in audit mode, tune false positives, enforce block. Endpoint DLP covers USB/upload paths.\n\n**Scope reduction:** Tokenize payments — no PAN in email/files to begin with.",
      "DLP is detective and preventive control for data exfil.",
      "Azure DLP vs M365 DLP? — Unified Purview DLP across services.",
      "Custom sensitive info types? — Org-specific regex patterns.",
      "DLP block day one without tuning",
      "DLP only on email not endpoints",
      "No exception workflow for false positives"),
    q("Insider Risk", "Security", "Occasional",
      "Defender Insider Risk Management use cases?",
      "Detect data hoarding before departure, risky browser usage, anomaly volume download, policy violations on sensitive files.",
      "**Architect:** Privacy/legal review before enable — scope policies to high-risk roles. Integrate with HR offboarding triggers.\n\n**Not surveillance:** Transparent policy communication to employees.",
      "Insider risk complements external threat detection.",
      "Insider risk vs DLP? — Insider risk behavioral analytics; DLP content pattern match.",
      "Case triage workflow? — Analyst review before punitive action.",
      "Enable broad monitoring without legal review",
      "No HR integration for termination triggers",
      "Treat all alerts as termination events"),
    q("Attack Surface Reduction", "Security", "Common",
      "Reduce attack surface for Azure-hosted .NET API?",
      "Private Link only, no public IP, WAF+Front Door, Defender enabled, JIT admin, minimal RBAC, disable unused endpoints, API Management authZ.",
      "**Architect:** ASR rules on VMs (block Office macros, child process create). Regular exposure scan — Defender CSPM 'attack path' analysis.",
      "Attack surface reduction is continuous architecture discipline.",
      "Defender attack path analysis? — Graph shows lateral movement chains — remediate critical paths.",
      "External scanning? — Authorized pen test + Defender EASM if licensed.",
      "Public management ports open",
      "Unused legacy public endpoints",
      "Over-permissive NSG 'allow all'"),
    q("Just Enough Access", "Identity", "Very Common",
      "Implement Just Enough Access (JEA) on Azure?",
      "PIM eligible assignments — no standing admin. Time-bound elevation with approval. Custom roles scoped to resource group not subscription.",
      "**Architect:** Break-glass accounts sealed in vault — audited quarterly use only. CI/CD SP gets deploy role not Owner.\n\n**Measure:** % admin actions via PIM vs permanent.",
      "JEA is Zero Trust identity pillar on Azure.",
      "JEA vs JIT VM access? — JEA is RBAC elevation; JIT is NSG port opening.",
      "Access reviews? — Quarterly Entra access review on privileged roles.",
      "Permanent Owner on production subscription",
      "PIM without approval workflow",
      "Shared break-glass password"),
    q("Zero Trust Architecture Azure", "Security", "Very Common",
      "Map Microsoft Zero Trust pillars to Azure services?",
      "Verify explicitly (Entra CA, MFA), Least privilege (RBAC, PIM), Assume breach (Defender, Sentinel), Secure data (Purview, encryption), Secure infrastructure (Policy, Private Link).",
      "**Architect:** Zero Trust assessment tool in Defender scores maturity per pillar. Roadmap by gap — identity first, then network, then data.",
      "Zero Trust is framework — map to concrete Azure controls.",
      "Zero Trust vs perimeter? — Perimeter supports but identity is primary gate.",
      "Micro-segmentation role? — Network leg of Zero Trust.",
      "Zero Trust as single product purchase",
      "Network location trust only",
      "No measurement of Zero Trust maturity"),
    q("Secure Score vs Compliance", "Governance", "Common",
      "Explain secure score vs regulatory compliance in Defender?",
      "Secure score: weighted Microsoft security recommendations best practice. Compliance: mapped controls (SOC2, PCI) pass/fail — overlapping but not identical.",
      "**Architect:** Use both — compliance for audit evidence, secure score for continuous improvement. Custom initiative for org controls not in defaults.",
      "Distinguishing score and compliance avoids audit surprises.",
      "100% secure score means compliant? — Not necessarily — regulatory controls may exceed recommendations.",
      "Compliance only Azure policies? — Includes identity and data controls beyond ARM.",
      "Ignore compliance dashboard if score high",
      "Compliance pass without evidence artifacts",
      "No custom initiative for internal standards"),
    q("Vulnerability Scanning", "Security", "Very Common",
      "Vulnerability management architecture on Azure?",
      "Defender for Cloud VA on SQL/VM/containers, Qualys extension optional on VMs, container registry scan on push, CI/CD Trivy on images.",
      "**Architect:** Severity SLA — Critical patch 7 days. Integrate findings to Azure DevOps work items. Block deploy on critical unmitigated in prod pipeline.",
      "Vulnerability scanning spans runtime and build-time.",
      "Agentless VM scanning? — Defender agentless scanner — no agent install.",
      "ACR vulnerability scan? — Microsoft Defender for Containers on registry.",
      "Scan only quarterly",
      "Critical CVE no SLA",
      "Scanner findings not routed to owners"),
    q("Container Security Defender", "Security", "Common",
      "Defender for Containers on AKS — what is protected?",
      "Runtime threat detection on nodes, K8s audit log analysis, registry image scan, misconfiguration (privileged pods, hostPath mounts).",
      "**Architect:** Enable Defender plan, deploy DaemonSet agent, restrict privileged containers via Azure Policy for Kubernetes. Network policy default deny.",
      "Container security is orchestrator + image + runtime.",
      "Defender vs admission controller? — Defender detects runtime; Gatekeeper prevents bad deploys.",
      "AKS free tier Defender? — Per-node licensing — budget accordingly.",
      "Privileged pods allowed in prod",
      "No image scan on CI push",
      "Defender enabled without K8s audit logs"),
    q("DevSecOps Pipeline Gates", "DevSecOps", "Very Common",
      "Security gates in Azure DevOps pipeline for Bicep deploy?",
      "1. Secret scan (CredScan) 2. Bicep linter + what-if 3. Defender for IaC / Checkov 4. Policy compliance scan 5. Deploy staging 6. VA scan post-deploy.",
      "**Architect:** Golden pipeline template — teams inherit gates. Fail on Critical; warn on Medium with ticket.\n\n**Break glass:** Document override with CAB approval.",
      "Pipeline gates encode security architecture at scale.",
      "What-if vs deploy? — What-if catches policy deny before ARM submission.",
      "Progressive deployment? — Canary with Defender continuous assessment post-deploy.",
      "Deploy direct to prod no gates",
      "Secret in repo undetected",
      "Policy violations ignored in what-if"),
    q("Secret Scanning GitHub", "DevSecOps", "Very Common",
      "Prevent secrets in Git — GitHub and Azure DevOps?",
      "GitHub secret scanning + push protection; Azure DevOps CredScan in pipeline; pre-commit hooks locally; rotate if leaked.",
      "**Architect:** Block merge on detected secret. Use Key Vault references in appsettings — never commit connection strings.\n\n**If leaked:** Rotate immediately — secret in git history forever even if deleted.",
      "Secret scanning is minimum DevSecOps bar.",
      "Push protection? — Prevent commit containing known secret patterns.",
      "GitHub Advanced Security? — Required org-wide for private repos policy.",
      "Secrets in Bicep parameters committed",
      "Scan only on main branch",
      "Leaked key not rotated — assume compromised"),
    q("SAST DAST Integration", "DevSecOps", "Common",
      "Integrate SAST and DAST in release pipeline?",
      "SAST: CodeQL/SonarQube on PR — block Critical. DAST: OWASP ZAP against staging URL post-deploy — auth-aware scan.",
      "**Architect:** SAST in PR fast feedback; DAST nightly on staging. Separate dev noise from prod gate rules.\n\n**Limitation:** DAST misses authZ logic bugs — complement with threat modeling.",
      "SAST+DAST shift-left and validate running app.",
      "CodeQL vs Sonar? — CodeQL deep semantic; Sonar broad language support.",
      "Authenticated DAST? — Script login flow in ZAP context.",
      "SAST only on release branch",
      "DAST against production",
      "Ignore SAST findings as false positive always"),
    q("Threat Modeling STRIDE", "Security", "Very Common",
      "Apply STRIDE to Azure order API architecture?",
      "Spoofing: Entra JWT validation. Tampering: HTTPS, signed payloads. Repudiation: audit logs. Info disclosure: minimize response fields. DoS: rate limits, autoscale. Elevation: object-level authZ on orderId.",
      "**Architect:** Threat model per major feature at design phase. Document mitigations in ADR. Revisit on architecture change.\n\n**Tool:** Microsoft Threat Modeling Tool or OWASP.",
      "STRIDE connects threats to concrete Azure controls.",
      "STRIDE vs PASTA? — STRIDE categorization; PASTA risk-centric process.",
      "Trust boundaries? — Draw API, DB, queue as boundaries.",
      "Threat model after prod launch only",
      "Generic threats not mapped to mitigations",
      "Skip repudiation/logging threats"),
    q("Security Review Checklist", "Governance", "Common",
      "Architecture security review checklist items?",
      "Identity model, data classification, encryption transit/rest, network diagram, secrets management, logging/monitoring, DR, compliance controls, threat model reference.",
      "**Architect:** Review gate before prod deploy — signed checklist in ADO work item. Red team findings tracked to closure.",
      "Checklist institutionalizes security in design process.",
      "Review cadence? — Major release + annual per system.",
      "Who attends? — Architect, security, ops, product owner.",
      "Checklist checkbox exercise no depth",
      "No threat model attached",
      "Findings not tracked post-review"),
    q("Incident Response Azure", "Security", "Very Common",
      "Azure security incident response phases for Key Vault breach?",
      "1. Detect (Sentinel alert) 2. Contain (disable SP, rotate secrets) 3. Eradicate (remove persistence) 4. Recover (restore from backup) 5. Lessons learned.",
      "**Architect:** Pre-document runbooks in Sentinel playbooks. Preserve Key Vault diagnostic logs before rotation. Legal notification timeline per regulation.",
      "IR runbooks show operational security maturity.",
      "Forensic subscription? — Isolated subscription for snapshot analysis.",
      "Communication plan? — Exec, legal, customer notification templates.",
      "Delete logs during incident cleanup",
      "No secret rotation runbook",
      "Incident without postmortem"),
    q("Forensics Blob Immutability", "Security", "Common",
      "Immutable blob storage for forensic evidence retention?",
      "Time-based immutability policy on evidence container — WORM compliance. Legal hold for litigation. Separate storage account air-gapped RBAC.",
      "**Architect:** Sentinel incident exports, VM disk snapshots, packet captures land in immutable container. Retention matches regulatory minimum (e.g., 7 years finance).",
      "Immutability prevents attacker or admin tampering evidence chain.",
      "Immutability vs soft delete? — Immutability cannot delete until retention expires.",
      "Version-level immutability? — Finer control per blob version.",
      "Mutable forensic storage",
      "Same account as operational logs — attacker deletes",
      "Retention shorter than legal requirement"),
    q("Ransomware Protection", "Security", "Very Common",
      "Azure ransomware resilience architecture?",
      "Backup with immutability, MFA on backup admin, Private Link backups, Defender alerts, least privilege, tested restore, multi-region backup copies.",
      "**Architect:** 3-2-1 rule — 3 copies, 2 media, 1 offsite. Azure Backup soft delete + immutability. Regular restore drills — untested backup is hope not strategy.",
      "Ransomware architecture is backup + identity + detection.",
      "Azure Backup immutability? — Vault immutability prevents backup deletion.",
      "Multi-user authorization on backup? — Critical operations require second approver.",
      "Single backup copy same region",
      "Backup admin same as prod admin",
      "Never tested restore"),
    q("Backup Encryption", "Security", "Common",
      "Backup encryption on Azure — keys and scope?",
      "Azure Backup encrypts at rest by default with Microsoft-managed keys. CMK optional via Key Vault for regulatory custody.",
      "**Architect:** CMK for finance/health backups. Encrypt backup traffic in transit TLS. Separate backup RG RBAC from workload admins.",
      "Backup encryption is often assumed not verified.",
      "CMK rotation impact? — New backups use new key version.",
      "On-prem MARS agent? — Passphrase + Azure encryption.",
      "Assume backup unencrypted acceptable",
      "CMK without key recovery plan",
      "Backup operators can delete backups"),
    q("Customer-Managed Keys PaaS", "Security", "Very Common",
      "Enable CMK for Azure SQL and Storage — architecture steps?",
      "Create HSM or software key in Key Vault, grant SQL/Storage service identity unwrap permissions, configure CMK on resource, verify encryption status.",
      "**Architect:** Key in same region as data. Document key revocation procedure — revocation makes data inaccessible immediately.",
      "CMK is customer custody vs Microsoft-managed default.",
      "Double encryption? — CMK plus platform encryption layer.",
      "Key revocation drill? — Test annually — understand data lockout.",
      "CMK key in wrong region",
      "No wrap/unwrap permission for service",
      "Revoke key without DR plan"),
    q("Double Encryption", "Security", "Occasional",
      "Double encryption on Azure — when required?",
      "Platform encryption + customer-managed key on Storage/SQL/Disks — defense in depth for highest classification data.",
      "**Architect:** Evaluate performance and cost. Required by some government contracts. Managed HSM for key material isolation.",
      "Double encryption for regulatory maximum assurance.",
      "Which services support? — Storage, SQL, managed disks — verify current list.",
      "Performance impact? — Minimal for most — benchmark write-heavy workloads.",
      "Double encryption without CMK need",
      "Ignore Microsoft-managed layer in threat model",
      "Key and data different compliance zones"),
    q("Confidential Computing", "Security", "Occasional",
      "Azure confidential computing use cases?",
      "Encrypt data in use — SGX enclaves or AMD SEV-SNP on DCsv3/DCasv5 VMs for multi-party compute, encrypted SQL Always Encrypted with enclave.",
      "**Architect:** When threat model includes malicious admin or host compromise — enclave protects data during processing. Higher cost SKUs.\n\n**SGX enclaves:** Intel SGX trusted execution for small memory enclaves — attestation proves code integrity.",
      "Confidential computing protects data in use — third encryption state.",
      "SGX vs SEV-SNP? — SGX enclave app model; SEV encrypts entire VM memory.",
      "Attestation? — Verify enclave identity before secrets release.",
      "Confidential VM for all workloads — cost",
      "SGX without understanding memory limits",
      "No attestation in secret release flow"),
    q("Trusted Launch VMs", "Security", "Common",
      "Trusted Launch for Azure VMs — benefits?",
      "Secure Boot, vTPM, boot integrity attestation — prevents rootkits and boot-level malware. Required baseline for many compliance frameworks.",
      "**Architect:** Enable Trusted Launch on new VM templates. Boot diagnostics to Azure Storage encrypted. Pair with Defender for Servers.",
      "Trusted Launch is firmware/boot integrity layer.",
      "Trusted Launch vs Confidential VM? — Trusted Launch boot integrity; Confidential VM memory encryption.",
      "Gen2 VMs required? — Trusted Launch requires Gen2 images.",
      "Gen1 VMs in new deployments",
      "Secure Boot disabled",
      "No boot integrity monitoring alerts"),
    q("Firmware Integrity", "Security", "Occasional",
      "How Azure addresses firmware-level threats?",
      "Project Cerberus-inspired platform integrity, Trusted Launch attestation, Defender alerts on boot anomalies, Azure-hosted hardware root of trust.",
      "**Architect:** Specify Trusted Launch in VMSS and AKS node pools. Monitor Defender recommendations for firmware-related findings.",
      "Firmware integrity is emerging architect concern for regulated VMs.",
      "Measured boot? — vTPM records boot measurements for attestation.",
      "On-prem comparison? — Azure manages hardware integrity customer enables VM features.",
      "Ignore boot-level threats as hypothetical",
      "Custom images without integrity verification",
      "No attestation in compliance evidence"),
    q("Security Baselines AKS", "Security", "Common",
      "AKS security baseline — top controls?",
      "Private cluster, Azure CNI network policy, Defender for Containers, Azure Policy add-on (no privileged pods), managed identity, API server authorized IP ranges or private.",
      "**Architect:** CIS Azure benchmark mapping for AKS — enable policy initiative 'Kubernetes cluster pod security baseline standards for Azure Kubernetes Service'. Regular kube-bench assessment.",
      "AKS baseline combines K8s and Azure platform controls.",
      "Private cluster? — API server private endpoint — no public kube-apiserver.",
      "Pod Security Standards? — Replace deprecated PSP with built-in PSS labels.",
      "Public AKS API with wide IP allow list",
      "kubenet without network policy",
      "No CIS assessment in CI"),
    q("CIS Benchmark Azure", "Compliance", "Common",
      "Implement CIS Microsoft Azure Foundations Benchmark?",
      "Assign CIS Azure Policy initiative in audit then deny mode. Defender regulatory dashboard tracks CIS controls. Remediate identity and logging gaps first.",
      "**Architect:** Not every CIS control applies — document exceptions. Automate DeployIfNotExists for diagnostic settings and MFA requirements.\n\n**Evidence:** Export compliance reports for auditors quarterly.",
      "CIS benchmark is practical hardening standard for Azure estates.",
      "CIS vs Azure Security Benchmark? — Overlap — ASB is Microsoft superset mapping.",
      "Level 1 vs Level 2 CIS? — Level 2 stricter — phased adoption.",
      "CIS audit-only forever",
      "No exception documentation process",
      "CIS compliance without technical remediation owners"),
]

ALL_AZURE_Q011_Q050 = {
    13: WEEK_13_Q011_Q050,
    14: WEEK_14_Q011_Q050,
}
