"""Hand-crafted premium Q011–Q030 for Weeks 5–6 — Data Structures & Algorithms."""

from premium_qa_data import q

WEEK_5_Q011_Q030 = [
    q("Trie for Prefix Search", "Tries", "Common",
      "When would you choose a trie over a hash table for search in system design?",
      "Trie (prefix tree) supports O(key length) prefix lookup — autocomplete, IP routing, spell check. Hash tables only do exact key match in O(1) average.",
      "**Trie structure:** Each node represents a character; paths from root spell keys. Shared prefixes compress storage.\n\n**Production use cases:**\n1. **Autocomplete** — type 'arch' → suggest 'architecture', 'archive'\n2. **IP routing (CIDR)** — longest prefix match in routers\n3. **Search suggestions** — Elasticsearch completion suggester uses FST (finite state transducer), trie variant\n\n**Trade-offs:** Memory-heavy for sparse alphabets; use compressed trie (radix tree) or FST for disk efficiency.\n\nFor a typeahead API at 50K QPS, trie in Redis or dedicated suggest service beats scanning hash keys.",
      "Architects match prefix vs exact-match access patterns to the right structure.",
      "Trie vs Elasticsearch for autocomplete? — ES FST at scale; in-memory trie for small catalogs.",
      "Radix tree vs standard trie? — Radix compresses single-child chains — less memory.",
      "Using hash map and scanning all keys for prefix",
      "Not compressing trie for large sparse keyspaces",
      "Ignoring case-folding and Unicode normalization in prefix keys"),
    q("Skip List", "Probabilistic Structures", "Occasional",
      "What is a skip list and where does it appear in production systems?",
      "Skip list: probabilistic layered linked list giving O(log n) search/insert — simpler than balanced trees. Used in Redis sorted sets (ZSET) internals and LevelDB/RocksDB memtables.",
      "**How it works:** Base level is sorted linked list; upper levels 'skip' forward with probability p (often 0.5). Search starts at top, drops down — like express lanes.\n\n**Why production cares:**\n- **Redis ZSET** — scores + member ordering via skip list + hash map combo\n- **LevelDB** — memtable before flush to SSTable\n\n**vs Red-black tree:** Skip list easier to implement concurrently (lock-free variants); similar O(log n) bounds probabilistically.\n\nArchitect: when you need ordered in-memory structure with concurrent inserts, skip list (or managed ZSET) beats hand-rolled BST.",
      "Skip lists bridge interview DS trivia and Redis internals.",
      "Skip list vs B+ tree on disk? — B+ tree wins for disk; skip list for in-memory ordered sets.",
      "Concurrent skip list? — Redis uses dual structure; research papers on lock-free skip lists.",
      "Implementing BST when Redis ZSET exists",
      "Assuming skip list is deterministic O(log n) worst case",
      "Not knowing Redis ZSET is skip list + hash"),
    q("Inverted Index", "Search", "Very Common",
      "Explain inverted indexes. Why are they fundamental to search systems?",
      "Inverted index maps term → list of document IDs (postings list). Enables O(1) term lookup instead of O(n) full-text scan. Core of Elasticsearch, Lucene, SQL full-text indexes.",
      "**Structure:**\n- **Dictionary:** term → pointer to postings\n- **Postings list:** sorted doc IDs + positions/frequencies for ranking\n\n**Query:** AND/OR postings lists (merge sorted lists) — 'architecture AND azure' intersects two lists.\n\n**Production:** Elasticsearch shard = Lucene index = inverted index segments. Azure AI Search same pattern.\n\n**Architect decision:** Inverted index for full-text; B-tree for structured filters; combine in hybrid query planner.\n\nAt 100M documents, scanning text is impossible — inverted index is non-negotiable for search.",
      "Search architecture starts with inverted index — not SQL LIKE.",
      "Inverted vs forward index? — Forward: doc → terms (for highlighting); inverted: term → docs (for search).",
      "BM25 ranking? — Scoring function using term frequency and doc frequency from postings.",
      "SQL LIKE '%term%' on billion-row table",
      "No stemming/normalization in index pipeline",
      "Ignoring index rebuild cost on schema change"),
    q("Count-Min Sketch", "Probabilistic Structures", "Occasional",
      "What is a count-min sketch and when would an architect use it?",
      "Count-min sketch: probabilistic frequency estimator — O(1) update, fixed memory. Overestimates counts (never underestimates). Used for heavy hitter detection, CDN traffic, streaming analytics.",
      "**How it works:** d hash functions × w buckets matrix. Increment all d buckets on add; query returns min across d buckets.\n\n**Use cases:**\n- **Heavy hitters** — find top talkers in network traffic without storing every flow\n- **Streaming dashboards** — approximate request counts per endpoint\n- **DDoS detection** — flag IPs exceeding threshold in sliding window\n\n**Trade-off:** Approximate counts with tunable error ε. Exact counts need hash map — memory explodes at billions of keys.\n\nArchitect: pair count-min sketch with exact store for candidates that sketch flags as heavy hitters.",
      "Streaming systems need approximate DS — count-min sketch is the architect's tool.",
      "Count-min vs HyperLogLog? — Count-min estimates frequency; HyperLogLog estimates distinct count.",
      "Error bound tuning? — Width w and depth d trade memory vs accuracy.",
      "Storing every event in memory for frequency",
      "Treating sketch count as exact for billing",
      "No second-stage exact verification for flagged keys"),
    q("Union-Find Disjoint Set", "Graphs", "Common",
      "How does union-find apply to system design beyond coding interviews?",
      "Union-find (disjoint set) tracks connected components with near O(1) union/find via path compression + rank. Used for network connectivity, Kruskal MST, dynamic cluster merging, permission group equivalence.",
      "**Production mappings:**\n1. **Network connectivity** — are two nodes in same partition after link failures?\n2. **Kubernetes** — union-find variants in cluster federation grouping\n3. **Social 'mutual group'** — transitive closure queries with periodic rebuild\n4. **Image processing pipelines** — connected component labeling\n\n**Architect note:** For static graphs, precompute components offline. Union-find shines when edges arrive dynamically (streaming merges).\n\nWith path compression, amortized α(n) — effectively constant for practical n.",
      "Union-find models 'are these things in the same group?' at scale.",
      "Union-find vs graph DB traversal? — Union-find for dynamic connectivity; BFS for path queries.",
      "When rebuild vs incremental? — If queries are batch, rebuild nightly; streaming needs union-find.",
      "BFS on every connectivity check at high QPS",
      "Not applying path compression in hand-rolled implementation",
      "Using union-find when you need shortest path"),
    q("Sliding Window Deque", "Deque", "Common",
      "How does a deque enable O(n) sliding window maximum algorithms and rate limiting?",
      "Deque (double-ended queue) maintains monotonic candidate indices — O(1) push/pop each end. Enables sliding window max/min in O(n) and implements sliding window rate limiters.",
      "**Sliding window maximum:** Deque stores indices of decreasing values — front always current max. Each element enters and exits once — O(n) total.\n\n**Rate limiting:** Sliding window log stores timestamps in deque — drop expired from front, reject if count exceeds limit.\n\n**Production:** NGINX rate limiting, API gateways (Kong, APIM), custom middleware using deque or Redis sorted set for distributed windows.\n\n**Architect:** Specify window type in NFR — fixed vs sliding vs token bucket. Deque backs precise sliding window; approximate counters save memory at scale.",
      "Deque connects algorithm pattern to gateway rate-limit design.",
      "Deque vs circular buffer for window? — Deque for variable-size eviction; ring buffer for fixed slots.",
      "Distributed sliding window? — Redis ZSET with timestamp scores; trim expired range.",
      "Re-sorting entire window on every request O(n log n)",
      "Fixed window when sliding required — boundary burst abuse",
      "Unbounded deque growth without expiry"),
    q("B+ Tree Deep Dive", "Trees", "Very Common",
      "Explain B+ tree internals. Why is it the default database index?",
      "B+ tree: high fanout balanced tree; keys only in internal nodes, all data in linked leaf nodes. Optimized for disk block reads — minimizes I/O per lookup.",
      "**Key properties:**\n- **Fanout 100–500** — one disk read covers hundreds of keys\n- **Leaf linked list** — efficient range scans (`WHERE price BETWEEN 10 AND 50`)\n- **Height log_{fanout}(n)** — billion rows ≈ 3–4 levels\n\n**vs B-tree:** B+ tree doesn't store values in internal nodes — more keys per page, shallower tree.\n\n**Production:** PostgreSQL, SQL Server, MySQL InnoDB clustered index IS a B+ tree. Page size (8KB default) drives fanout.\n\n**Architect:** Every `WHERE` on unindexed column = leaf-to-leaf scan. Index design = choosing B+ tree columns and order.",
      "B+ tree is the bridge between SQL performance and disk physics.",
      "Clustered vs non-clustered index? — Clustered = table sorted by B+ tree key (one per table).",
      "Index column order? — Leftmost prefix rule — (a,b) index helps `WHERE a=?` not `WHERE b=?` alone.",
      "Assuming hash index for range queries",
      "Too many indexes — write amplification on every insert",
      "Ignoring fill factor and page splits under heavy insert"),
    q("Ring Buffer", "Arrays", "Common",
      "When do architects use ring buffers (circular buffers) in production?",
      "Ring buffer: fixed-size array with head/tail pointers — O(1) enqueue/dequeue, cache-friendly, no allocation. Used in logging, IPC, streaming, kernel drivers, LMAX Disruptor.",
      "**Properties:**\n- **Bounded memory** — backpressure when full (block or drop)\n- **Sequential access** — CPU cache friendly\n- **Lock-free variants** — single producer/single consumer without mutex\n\n**Production:**\n- **LMAX Disruptor** — financial exchange inter-thread messaging\n- **Kernel pipe buffers, NIC ring descriptors**\n- **Embedded telemetry** — bounded log before flush to disk\n\n**Architect:** Choose ring buffer when throughput > latency variance tolerance and memory must be bounded. Use queue (Kafka) when you need durability and replay.",
      "Ring buffer is the high-performance bounded queue pattern.",
      "Ring buffer vs Kafka? — Ring buffer in-process; Kafka cross-process durable log.",
      "Power-of-two size? — Enables bitmask instead of modulo for index wrap.",
      "Unbounded in-memory queue in latency-critical path",
      "Multi-producer without lock-free design — contention",
      "No strategy when buffer full — silent drop vs block"),
    q("Hash Collision Strategies", "Hash Tables", "Common",
      "What hash collision strategies exist and when does each matter at scale?",
      "Collisions inevitable (pigeonhole). Strategies: chaining (linked list per bucket), open addressing (probe sequence), cuckoo hashing (relocate), robin hood (reduce variance). Choice affects cache behavior and worst-case under attack.",
      "**Chaining:** Simple, handles high load factor; pointer chasing hurts cache.\n\n**Open addressing:** Linear probing (cache friendly, clustering), quadratic, double hashing. Better memory locality; clustering risk.\n\n**Cuckoo hashing:** O(1) worst-case lookup with two tables — used in some network switches and high-performance maps.\n\n**Attack surface:** Adversarial keys hashing to same bucket → O(n) — use SipHash or randomized seed per process.\n\n**Architect:** .NET Dictionary uses chaining; Python 3.7+ dict is open addressing. Know your runtime; for custom sharding, test distribution with production key samples.",
      "Collision handling affects tail latency and security — not just Big-O average.",
      "Load factor tuning? — 0.75 typical; resize when exceeded — amortized cost.",
      "Consistent hashing collision? — Virtual nodes reduce imbalance; separate from bucket collision.",
      "Ignoring adversarial hash attack on public API",
      "Assuming uniform distribution without measuring key skew",
      "Quoting O(1) without mentioning resize/rehash cost"),
    q("Open Addressing vs Chaining", "Hash Tables", "Common",
      "Compare open addressing and chaining for in-memory hash maps at scale.",
      "Chaining: bucket → linked list/tree of entries. Open addressing: all entries in array, probe on collision. Open addressing better cache locality; chaining simpler deletion and high load factors.",
      "**Open addressing:**\n- Probing: linear, quadratic, double hashing\n- **Pros:** No pointer overhead, cache-friendly sequential probe\n- **Cons:** Clustering, sensitive to load factor (>0.7 degrades)\n\n**Chaining:**\n- **Pros:** Tolerates load factor >1, simple delete, worst-case bucket → tree (Java HashMap)\n- **Cons:** Pointer chasing, allocator pressure\n\n**At scale:** Redis dict uses chaining. Many language runtimes moved to open addressing for memory density.\n\n**Architect:** For embedded/edge with tight memory, open addressing. For unknown key distribution with deletes, chaining. Profile — don't assume.",
      "Implementation choice affects memory per key and p99 lookup.",
      "Robin Hood hashing? — Reduces probe length variance — better tail latency.",
      "When treeify bucket? — Java HashMap treeifies bucket at 8+ collisions — O(log n) bucket.",
      "Choosing without measuring memory per entry",
      "Open addressing with load factor 0.95",
      "Not considering deletion tombstone buildup in open addressing"),
    q("Red-Black Tree Overview", "Trees", "Occasional",
      "What is a red-black tree and where does it appear in production systems?",
      "Red-black tree: self-balancing BST with color invariants — O(log n) insert/delete/search. Used in Linux kernel rbtree, Java TreeMap, C++ std::map, epoll timer management, some memory allocators.",
      "**Invariants (simplified):** Black height equal on all paths; no consecutive reds. Rotations restore balance on insert/delete.\n\n**vs AVL:** Red-black allows slightly looser balance — fewer rotations on insert (better write-heavy). AVL stricter — faster reads.\n\n**Production:**\n- **Linux CFQ scheduler, VMA management** — kernel rbtree\n- **Java TreeMap** — sorted map when you need in-order traversal\n- **Timer wheels vs rbtree** — rbtree for many arbitrary timeouts\n\n**Architect:** You rarely implement rbtree — use sorted structures from runtime or Redis ZSET. Know it when ordered in-memory map with range queries is needed and hash won't work.",
      "Red-black tree is the default ordered map behind many standard libraries.",
      "Red-black vs B+ tree? — In-memory ordered map vs disk-backed index — different layers.",
      "Skip list vs red-black? — Similar use case; skip list easier concurrent; rbtree in standard libs.",
      "Hand-rolling rbtree in application code",
      "Using TreeMap for equality-only lookups",
      "Not knowing ordered map needed for range queries"),
    q("Adjacency List vs Matrix", "Graphs", "Common",
      "When use adjacency list vs adjacency matrix for graph storage in architecture?",
      "Adjacency list: O(V+E) space, iterate neighbors fast — sparse graphs. Adjacency matrix: O(V²) space, O(1) edge lookup — dense graphs or small V.",
      "**Adjacency list (default):**\n- Social graphs, service dependencies, road networks\n- Storage: array of neighbor lists, or edge table in SQL\n- **Neo4j, graph DBs** — optimized adjacency traversal\n\n**Adjacency matrix:**\n- Small fixed node sets (10–100), need O(1) `isConnected(i,j)`\n- Network topology among known datacenter nodes\n- Floyd-Warshall all-pairs shortest path preprocessing\n\n**Architect at scale:** Billion-node social graph cannot use matrix — adjacency list / graph partition / adjacency compression. Service mesh with 200 services — adjacency list in config or service catalog.",
      "Graph storage choice determines memory and query feasibility at scale.",
      "Edge table in SQL? — `from_id, to_id` — adjacency list in relational form.",
      "Graph partitioning? — Shard adjacency list by node ID range for distributed graph.",
      "Adjacency matrix for million-node graph",
      "Storing full graph in single machine memory",
      "No index on edge table for neighbor lookups"),
    q("Topological Sort Applications", "Graphs", "Common",
      "Where does topological sort appear in system architecture?",
      "Topological sort orders DAG nodes so dependencies come first. Used in build pipelines, task schedulers, schema migrations, infrastructure-as-code dependency graphs, package managers.",
      "**Production examples:**\n1. **CI/CD** — build service B before A if A depends on B's API contract\n2. **Terraform/Pulumi** — resource dependency graph → apply order\n3. **Database migrations** — migration scripts with FK dependencies\n4. **npm/Docker layer builds** — Dockerfile instruction order\n\n**Algorithm:** Kahn's (BFS in-degree) or DFS post-order. O(V+E).\n\n**Architect:** Circular dependency = no topological order = design bug. Detect cycles before deploy pipeline runs.",
      "Deploy and build systems are topological sorts in production.",
      "Kahn vs DFS topo sort? — Kahn detects cycles explicitly; DFS with coloring.",
      "Parallel topo levels? — All nodes with in-degree 0 at same level can run parallel.",
      "Manual deploy order for 50 microservices",
      "Circular IaC dependency undetected until apply fails",
      "Running migrations out of dependency order"),
    q("Dijkstra Structure Needs", "Graphs", "Common",
      "What data structures does Dijkstra's algorithm require and where is it used in architecture?",
      "Dijkstra needs: weighted graph (adjacency list), min-priority queue (heap), distance array. O((V+E) log V). Used in CDN routing, network path selection, service mesh weighted routing.",
      "**Structures:**\n- **Adjacency list** — sparse graph storage\n- **Min-heap / priority queue** — extract minimum distance node\n- **Distance map** — best known cost to each node\n- **Predecessor map** — reconstruct path\n\n**Production:**\n- **OSPF/BGP** — link-state routing (variants of shortest path)\n- **Maps APIs** — road network shortest path (often A* with heuristics)\n- **Service mesh** — weighted latency routing between nodes\n\n**Limitation:** Non-negative weights only — negative weights need Bellman-Ford.\n\n**Architect:** At internet scale, precompute or use hierarchical routing — full Dijkstra on billion-node graph is offline batch, not per-request.",
      "Dijkstra maps to weighted dependency and routing problems.",
      "Dijkstra vs A*? — A* adds heuristic — faster when goal-directed (maps).",
      "Bidirectional Dijkstra? — Search from both ends — cuts search space.",
      "Running Dijkstra per request on full internet graph",
      "Using Dijkstra with negative edge weights",
      "Array-based priority queue instead of heap — slower"),
    q("Memory Locality and Cache-Friendly Design", "Performance", "Common",
      "How does memory locality affect architectural choices for data structures?",
      "CPU cache lines (~64 bytes) favor sequential access. Arrays and struct-of-arrays beat linked lists and array-of-structs for hot paths. False sharing and pointer chasing cause cache misses.",
      "**Cache-friendly patterns:**\n- **Columnar storage** — scan one column (array) — analytics\n- **Ring buffer** — sequential access\n- **Open addressing hash** — probe in contiguous memory\n- **Struct of arrays (SoA)** — process one field across all entities in SIMD-friendly loops\n\n**Cache-unfriendly:**\n- Linked list traversal — random memory jumps\n- Object graphs with pointers everywhere\n\n**Architect impact:** ORM materializing object graphs vs DTO projection — projection reduces allocations and improves locality. Data-oriented design in game engines and HFT applies same principle to services processing batches.",
      "Locality explains why arrays beat linked lists at scale beyond Big-O.",
      "False sharing? — Two threads write adjacent fields — same cache line invalidated.",
      "NUMA awareness? — On multi-socket servers, memory affinity matters for hot structures.",
      "Linked list for hot-path iteration over millions of items",
      "Array of objects when SoA would vectorize",
      "Ignoring allocation pressure from small object churn"),
    q("Probabilistic Structures Tradeoffs", "Probabilistic Structures", "Common",
      "Compare bloom filter, HyperLogLog, and count-min sketch for architects.",
      "Bloom: set membership (maybe yes, definitely no). HyperLogLog: distinct count estimate. Count-min: frequency estimate. All trade exactness for fixed memory at scale.",
      "| Structure | Answers | Error | Delete? |\n|-----------|---------|-------|--------|\n| Bloom filter | Is x in set? | False positives | No (standard) |\n| HyperLogLog | How many unique? | ~0.81% std error | N/A |\n| Count-min sketch | How many x? | Overestimate | N/A |\n\n**Combined pattern:** Bloom in front of DB → HyperLogLog for UV metrics → count-min for heavy hitter detection → exact store for flagged items.\n\n**Architect:** Document acceptable error rate in ADR. Billing needs exact; CDN cache negative lookup can tolerate bloom FP.",
      "Probabilistic DS suite covers membership, cardinality, frequency.",
      "Redis HyperLogLog? — `PFADD`/`PFCOUNT` — built-in UV counting.",
      "Counting bloom filter? — Supports delete via counter per bit.",
      "Using bloom filter for billing exact counts",
      "Not sizing structures for expected cardinality",
      "Single probabilistic structure for all query types"),
    q("Data Structure Selection ADR", "Framework", "Common",
      "How do you document data structure choices in an Architecture Decision Record?",
      "ADR captures: access pattern, scale, consistency, rejected alternatives, consequences. Template: Context → Decision → Hash/B-tree/Trie/Redis → Rejected options with why.",
      "**Example ADR snippet:**\n- **Context:** Product search 10M SKUs, prefix + full-text\n- **Decision:** Elasticsearch inverted index + Redis cache for hot SKUs\n- **Rejected:** SQL LIKE (O(n) scan); in-memory trie (memory bound)\n- **Consequences:** Ops overhead, index rebuild pipeline, eventual consistency on index lag\n\n**Architect:** DS selection is not permanent — ADR revision when scale crosses threshold (10M → 1B).",
      "ADR makes DS choice auditable and teachable to team.",
      "When revisit ADR? — 10x scale, new access pattern, cost threshold.",
      "Who approves DS ADR? — Tech lead + DBA/search owner for managed services.",
      "Verbal decision with no rejected alternatives documented",
      "Choosing technology before access pattern analysis",
      "No migration path when DS choice hits limit"),
    q("Immutable Persistent Structures", "Functional DS", "Occasional",
      "What are immutable persistent data structures and where do they help in distributed systems?",
      "Persistent DS preserve previous versions on update — structural sharing, not full copy. Immutable structures simplify concurrency, event sourcing, and Git-like versioning.",
      "**Benefits:**\n- **Thread safety** — no locks on read path\n- **Event sourcing** — each event produces new version; old state queryable\n- **Copy-on-write** — B-tree, persistent vector (Clojure, Immutable.js)\n\n**Production:**\n- **Git** — Merkle DAG of commits (immutable tree objects)\n- **Kafka log** — append-only immutable segments\n- **Cosmos DB / CRDT** — conflict-free replicated data types build on immutable merge\n\n**Trade-off:** Updates allocate new nodes — GC pressure. Use when read >> write and history matters.",
      "Immutability enables safe sharing and audit trails in distributed design.",
      "Persistent vs ephemeral? — Persistent keeps old versions; ephemeral discards.",
      "Structural sharing? — New version shares unchanged subtrees — O(log n) copy.",
      "Deep-cloning entire state on every event",
      "Mutable shared state across threads without synchronization",
      "Ignoring storage growth from retained versions"),
    q("HyperLogLog Cardinality", "Probabilistic Structures", "Common",
      "Explain HyperLogLog. When estimate unique visitors instead of exact count?",
      "HyperLogLog estimates distinct count in O(1) memory (~12KB for 64K buckets, ~0.81% error). Redis `PFADD`/`PFCOUNT`, BigQuery `APPROX_COUNT_DISTINCT`, Datadog UV metrics.",
      "**How it works:** Hash each element; track maximum leading zeros in registers; more unique elements → more varied hashes → higher max zeros statistically.\n\n**Use when:**\n- Unique visitors at billions of events/day\n- Network flow distinct IP counting\n- Database `COUNT(DISTINCT)` too expensive\n\n**Don't use when:** Exact count required (billing, compliance), small cardinality (just use set).\n\n**Architect:** Pipeline: HyperLogLog for real-time dashboard → nightly exact batch for reconciliation if needed.",
      "Cardinality estimation is standard infra — not exotic.",
      "HLL merge? — Union of sketches from shards — `PFMERGE` in Redis.",
      "HLL++ improvements? — Google bias correction — better small cardinalities.",
      "Exact distinct on 10B row table per dashboard load",
      "Not merging per-shard HLL at query time",
      "HyperLogLog for 'top 10 products by count' — wrong tool"),
    q("Merkle Tree Integrity", "Trees", "Common",
      "What is a Merkle tree and how is it used for data integrity in distributed systems?",
      "Merkle tree: hash tree where leaf = data hash, parent = hash(children). Root hash commits to entire dataset — O(log n) proof of inclusion. Used in Git, blockchain, Cassandra repair, certificate transparency.",
      "**Production:**\n1. **Git** — commit tree objects; root identifies snapshot\n2. **Cassandra** — Merkle trees compare replica data for anti-entropy repair\n3. **Certificate Transparency** — log inclusion proofs\n4. **IPFS** — content-addressed DAG\n\n**Verification:** To prove block D in tree: provide O(log n) sibling hashes — verifier recomputes root.\n\n**Architect:** Merkle proofs enable light clients and efficient sync — 'prove this record existed at this root' without downloading full dataset.",
      "Merkle trees are integrity and sync primitives for distributed data.",
      "Merkle vs plain checksum? — Merkle localizes corruption and enables partial verification.",
      "Blockchain relevance? — Block header includes Merkle root of transactions.",
      "Full dataset compare for replica sync on TB data",
      "SHA1 for new integrity systems — use SHA-256",
      "Not versioning root hash when data mutates"),
]

WEEK_6_Q011_Q030 = [
    q("Merge Sort vs Quicksort", "Sorting", "Common",
      "When choose merge sort over quicksort in production systems?",
      "Merge sort: stable O(n log n) worst case, good for external sort and linked lists. Quicksort: faster in practice in-memory, O(n²) worst case, often unstable — typical library default with optimizations.",
      "**Merge sort wins:**\n- **External sort** — merge sorted chunks from disk\n- **Stability required** — multi-key sort preserving order\n- **Linked list sort** — O(1) space merge on lists\n- **Parallel sort** — predictable divide for fork-join\n\n**Quicksort wins:**\n- **In-memory general sort** — cache-friendly, in-place variants\n- **.NET/Java default** — Timsort (hybrid merge+insertion) not pure quicksort\n\n**Architect:** Don't pick algorithm per API request — push ordering to index. Batch ETL: external merge sort. Know tradeoffs for pipeline design.",
      "Sort choice matters in batch pipelines, not typical CRUD.",
      "Timsort? — Real-world hybrid — merge + insertion for runs — Python/Java default.",
      "Introsort? — C++ std::sort — quicksort + heap sort fallback for O(n log n) worst.",
      "In-memory quicksort on dataset larger than RAM",
      "Unstable sort breaking secondary key order",
      "Full sort when partial top-K suffices"),
    q("Heap Sort Use Cases", "Sorting", "Occasional",
      "When is heap sort the right choice in system design?",
      "Heap sort: O(n log n) in-place, not stable. Best when memory is tight and you need guaranteed O(n log n) without merge sort's extra space. Introsort uses heap sort as quicksort worst-case fallback.",
      "**Use cases:**\n- **Priority-driven processing** — heap more natural than heap sort on full array\n- **Top-K extraction** — min-heap of size K is O(n log k), better than heap sorting entire array\n- **Real-time systems** — bounded worst case matters\n\n**Rarely:** Full array heap sort in application code — libraries handle it.\n\n**Architect:** Think heap data structure for scheduling and top-K, not heap sort algorithm for reporting queries. SQL `ORDER BY` with limit uses heap internally in some engines.",
      "Heap sort matters as worst-case guard; heap structure matters for operations.",
      "Heap sort vs merge for in-place? — Heap in-place O(1) extra; merge needs O(n).",
      "Why introsort uses heap? — Guarantees O(n log n) when quicksort pivots degrade.",
      "Heap sorting 1B rows in app memory",
      "Using full sort for top-10 leaderboard",
      "Not knowing library already uses introsort/timsort"),
    q("Radix and Counting Sort", "Sorting", "Occasional",
      "When do radix sort or counting sort beat comparison sorts?",
      "Non-comparison sorts: O(n) when key range is bounded. Counting sort for small integer range; radix sort for fixed-width keys (IDs, IPs). Used in suffix arrays, GPU sorts, specialized indexes.",
      "**Counting sort:** O(n + k) where k = max value — fine when k is small (e.g., ages 0–120).\n\n**Radix sort:** Process digit by digit — O(n × d) for d digits. LSD radix for 32-bit integers, fixed-length strings.\n\n**Production:**\n- **IP routing tables** — prefix/suffix sorting patterns\n- **GPU batch sorts** — radix on parallel hardware\n- **Bucket sort by hash prefix** — shuffle in MapReduce\n\n**Architect:** When user IDs are numeric and range bounded, bucket by radix digit for sharding — related concept. Don't radix sort arbitrary strings in API layer.",
      "Linear-time sorts exploit key structure — not general purpose.",
      "Radix vs hash partition? — Radix for ordered buckets; hash for uniform distribution.",
      "When counting sort fails? — k larger than n — memory explodes.",
      "Comparison sort on million duplicate small integers",
      "Radix sort on variable-length UTF-8 without care",
      "O(n) claim without bounded key assumption"),
    q("Binary Search Variants", "Search", "Common",
      "What binary search variants matter beyond sorted array lookup?",
      "Variants: lower_bound (first ≥ target), upper_bound (first > target), search rotated array, binary search on answer (parametric search). B-tree index lookup is multi-way binary search.",
      "**Parametric search:** 'Minimum cache size so p99 < 100ms' — monotonic predicate, binary search on configuration space.\n\n**Production:**\n- **Capacity planning** — binary search replica count in load test\n- **Feature flags rollout** — bisect percentage until error rate threshold\n- **Git bisect** — find introducing commit — operational binary search\n\n**Invariant:** Monotonicity — if predicate true at x, true at all x' > x (or < x).\n\n**Architect:** Binary search on answer is underused — applies to tuning, not just arrays.",
      "Binary search generalizes to any monotonic decision problem.",
      "Lower bound vs upper bound? — Range query boundaries; equal_range for duplicates.",
      "Binary search on floating point? — Careful with precision and iteration limit.",
      "Linear scan configuration space for tuning",
      "Binary search without proving monotonic invariant",
      "Off-by-one in lower_bound implementation"),
    q("Master Theorem Intuition", "Complexity", "Occasional",
      "Explain the master theorem intuition for divide-and-conquer recurrences.",
      "Master theorem solves T(n) = aT(n/b) + O(n^d). Compare log_b(a) vs d: more subproblems → leaves dominate; equal → balanced; fewer → root work dominates.",
      "**Intuition:**\n- **Case 1 (log_b a > d):** Leaf work dominates — O(n^{log_b a}) — merge sort T(n)=2T(n/2)+O(n) → O(n log n)\n- **Case 2 (equal):** Balanced — O(n^d log n)\n- **Case 3 (log_b a < d):** Root dominates — O(n^d)\n\n**Architect use:** Estimate MapReduce cost — a mappers, b reduction factor, O(n^d) merge cost. Predict when distributed merge becomes bottleneck.\n\nDon't memorize — communicate: 'Recursive halving with linear merge → n log n.'",
      "Master theorem quantifies distributed divide-and-conquer pipelines.",
      "Akra-Bazzi? — Generalization when subproblem sizes vary — more accurate for real systems.",
      "When master theorem fails? — Non-polynomial f(n) or uneven splits — use recursion tree.",
      "Quoting master theorem without relating to pipeline cost",
      "Ignoring communication cost in distributed recurrence",
      "Assuming perfect halving in skewed data partitions"),
    q("Topological Sort Algorithm", "Graph Algorithms", "Common",
      "Compare Kahn's algorithm and DFS for topological sort. When prefer each?",
      "Kahn's: BFS by in-degree — peel nodes with in-degree 0, detect cycles if nodes remain. DFS: post-order finish times — reverse for topo order. Both O(V+E).",
      "**Kahn's advantages:**\n- Natural parallelization — all in-degree-0 nodes at same level\n- Explicit cycle detection (queue stalls)\n- Intuitive for build pipelines\n\n**DFS advantages:**\n- Compact recursive code\n- Combined with cycle detection (back edge)\n- Single pass for connected components + topo\n\n**Production:** Terraform plan uses DFS-style dependency walk. CI systems often Kahn for parallel stage execution.\n\n**Architect:** Expose parallel levels in pipeline UI — Kahn's level structure maps directly.",
      "Algorithm choice affects parallelization of deploy graphs.",
      "Lexicographic topo sort? — Priority queue for in-degree-0 — deterministic order.",
      "Topo sort on cyclic graph? — Impossible — return cycle for engineer fix.",
      "DFS topo without cycle check on dependency graph",
      "Serial deploy when parallel levels exist",
      "O(V²) in-degree scan each iteration instead of queue"),
    q("Cycle Detection Algorithms", "Graph Algorithms", "Common",
      "How detect cycles in directed vs undirected graphs in architecture contexts?",
      "Directed: DFS with three colors (white/gray/black) — back edge to gray node = cycle. Or Kahn's — nodes left after processing. Undirected: DFS tracking parent — edge to visited non-parent = cycle.",
      "**Architecture mappings:**\n- **Microservice sync calls** — directed cycle = deadlock risk\n- **Circular FK dependencies** — migration graph cycle\n- **Deadlock detection** — wait-for graph cycles\n- **Terraform** — cycle prevents apply\n\n**Union-find:** Undirected cycle detection during MST build — adding edge connecting same component.\n\n**Architect:** Run cycle detection in CI on service dependency manifest — fail build before production deadlock.",
      "Cycle detection prevents class of production failures in dependency graphs.",
      "Directed vs undirected cycle? — Mutual A↔B sync calls — directed 2-cycle.",
      "Self-loop? — Trivial cycle — validate in schema.",
      "No dependency graph validation in CI",
      "Confusing undirected and directed cycle algorithms",
      "Ignoring indirect cycles A→B→C→A"),
    q("Bellman-Ford vs Dijkstra", "Graph Algorithms", "Common",
      "When use Bellman-Ford over Dijkstra for shortest path problems?",
      "Dijkstra: non-negative weights, O((V+E) log V) with heap. Bellman-Ford: handles negative weights, detects negative cycles, O(VE) — slower but more general.",
      "**Bellman-Ford when:**\n- Negative edge weights (currency arbitrage detection)\n- Need negative cycle detection\n- Small sparse graphs where VE acceptable\n- Distributed Bellman-Ford variants in distance-vector routing (RIP)\n\n**Dijkstra when:**\n- Non-negative weights (latency, distance, cost)\n- Large graphs — need efficiency\n- Production routing, CDN path selection\n\n**Architect:** Service latency routing = non-negative → Dijkstra or A*. Financial netting with credits/debits — validate sign convention before algorithm choice.",
      "Shortest path algorithm follows edge weight semantics.",
      "Floyd-Warshall? — All-pairs O(V³) — small V only (network topology matrix).",
      "Johnson's algorithm? — All-pairs sparse with reweighting — rare in interviews.",
      "Dijkstra on graph with negative latency 'boosts'",
      "Bellman-Ford on million-node graph per request",
      "Not detecting negative cycle in arbitrage scenario"),
    q("Rabin-Karp String Search", "String Algorithms", "Occasional",
      "How does Rabin-Karp apply beyond string matching in interviews?",
      "Rabin-Karp: rolling hash compares pattern in O(n) average — hash match then verify. Used for plagiarism detection, duplicate file finding, multi-pattern search, DNA sequence matching.",
      "**Rolling hash:** Update hash in O(1) when window slides — remove left char, add right char.\n\n**Production:**\n- **Duplicate detection** — hash file chunks, compare hashes before byte compare\n- **Git blob identification** — content hash (SHA, not Rabin-Karp, but same rolling concept for diff)\n- **IDS signature matching** — multiple patterns via hash buckets\n\n**Collision handling:** Hash match → verify characters — avoid false positive.\n\n**Architect:** Content-defined chunking (rsync, backup dedup) uses rolling hash for boundary detection.",
      "Rolling hash enables streaming pattern and duplicate detection.",
      "Rabin-Karp vs KMP? — KMP O(n) worst case single pattern; Rabin-Karp better multiple patterns.",
      "Polynomial hash modulo prime? — Base and mod chosen to reduce collisions.",
      "Byte-by-byte compare on GB files for duplicate find",
      "Ignoring hash collision verification step",
      "Wrong modulus causing excessive collisions"),
    q("Backtracking with Pruning", "Backtracking", "Occasional",
      "Explain backtracking with pruning. Where does it appear in system design?",
      "Backtracking explores decision tree, abandons branches when constraints fail (prune). Used in constraint solvers, scheduling, config validation, test case generation — not brute force enumeration.",
      "**Pruning examples:**\n- **Resource allocation** — stop branch when budget exceeded\n- **Scheduling** — skip assignment violating hard constraints\n- **Feature flag matrix** — invalid combinations pruned early\n\n**Production:** OR-Tools, SAT solvers, SQL query optimizer prunes plan search space.\n\n**Architect:** Offline optimization (shift scheduling, capacity planning) uses backtracking/branch-and-bound with time limit — return best-so-far if timeout.",
      "Pruning is how systems make NP-hard search tractable.",
      "Branch and bound? — Prune when lower bound exceeds best known solution.",
      "Time-boxed solver? — Architect specifies max solve time for config generation.",
      "Brute force all combinations for 40-flag config",
      "No pruning in custom allocation engine",
      "Infinite backtracking without memoization on overlapping subproblems"),
    q("NP-Hard Recognition", "NP-Hard", "Occasional",
      "How recognize NP-hard problems in architecture and respond appropriately?",
      "NP-hard: no known polynomial exact solution. Recognize: scheduling, routing, bin packing, graph coloring, optimal shard placement. Response: heuristics, approximation, limits, or offline solver.",
      "**Recognition signals:**\n- 'Optimal' assignment of N items to M containers minimizing cost\n- Traveling salesman / vehicle routing\n- Boolean satisfiability for complex rule sets\n\n**Architect playbook:**\n1. **Simplify** — reduce constraints\n2. **Heuristic** — greedy 90% solution\n3. **Approximation algorithm** — proven bound (e.g., 2-approx bin packing)\n4. **Offline + cache** — solve nightly, serve lookup\n5. **Human override** — edge cases\n\nDon't promise real-time optimal at scale.",
      "Recognizing NP-hard prevents impossible SLA commitments.",
      "NP-hard vs NP-complete? — Interview precision; both mean 'don't expect polynomial exact.'",
      "APX-hard? — Even constant approximation may be hard — set expectations lower.",
      "Promising optimal real-time routing for 10K vehicles",
      "Exact solver with no timeout in API path",
      "Not identifying problem as NP-hard before estimating"),
    q("Parallel Algorithm Patterns", "Parallelism", "Common",
      "What parallel algorithm patterns matter for architects designing scalable systems?",
      "Patterns: map-reduce, fork-join divide-conquer, pipeline parallelism, data parallelism, scatter-gather. Amdahl's law limits speedup — sequential bottleneck dominates.",
      "**MapReduce:** Map shards process in parallel; shuffle; reduce aggregates. Spark, Hadoop.\n\n**Fork-join:** Parallel merge sort, parallel graph traversal with careful synchronization.\n\n**Pipeline:** Assembly line stages — Kafka consumers per stage.\n\n**Data parallel:** Same operation on array shards — SIMD, GPU batch inference.\n\n**Architect:** Identify sequential fraction — if 5% serial, max 20× speedup regardless of cores. Partition data to minimize shuffle (expensive network).",
      "Parallel patterns map to Spark, K8s jobs, and stream pipelines.",
      "Amdahl's law example? — 10% serial → max 10× speedup on infinite cores.",
      "Straggler problem? — Slowest map task delays reduce — speculative execution.",
      "Parallelize without measuring sequential bottleneck",
      "Massive shuffle in every Spark job",
      "Shared mutable state across parallel workers"),
    q("External Merge Sort", "Sorting", "Common",
      "Explain external merge sort for datasets larger than memory.",
      "Phase 1: sort chunks in memory, write sorted runs to disk. Phase 2: k-way merge runs using min-heap. O(n log n) comparisons, O(n/B) I/O passes with buffer size B.",
      "**When needed:**\n- ETL sorting billion-row warehouse table\n- Database ORDER BY spilling to disk\n- Log file merge across time partitions\n\n**Optimization:**\n- **Larger run size** — match RAM budget\n- **k-way merge** — heap of size k, not pairwise merge\n- **SSD vs HDD** — I/O dominates; sequential read matters\n\n**Architect:** Design batch jobs with known memory ceiling — external sort built into Spark, SQL Server, not hand-rolled. Hand-roll only embedded/edge constraints.",
      "External sort is how 'sort everything' works at warehouse scale.",
      "Replacement selection? — Generate longer initial runs — fewer merge passes.",
      "Polyphase merge? — Optimize tape/disk drive utilization — classic DB technique.",
      "Load entire billion-row file into API memory",
      "Pairwise merge of 1000 runs — inefficient",
      "Random disk access during merge — kill performance"),
    q("Reservoir Sampling", "Sampling", "Common",
      "What is reservoir sampling and where is it used in streaming systems?",
      "Reservoir sampling: uniform random sample of size k from stream of unknown length in O(n) time, O(k) memory. Each element seen has k/i probability of entering reservoir at step i.",
      "**Use cases:**\n- **Log sampling** — retain representative 0.1% for debugging without bias\n- **A/B test analysis** — uniform subsample for expensive computation\n- **Stream QA** — continuous quality sample from Kafka topic\n\n**Variants:** Weighted reservoir sampling for non-uniform probabilities.\n\n**Architect:** Prefer reservoir over 'every Nth' — Nth is biased if stream has patterns. Document sampling rate in observability ADR.",
      "Unbiased streaming sample under memory constraints.",
      "Reservoir size k choice? — Balance storage vs statistical confidence.",
      "Distributed reservoir? — Per-shard sample then merge — approximate global uniform.",
      "Take first k events as sample — biased",
      "Every-1000th event sample on periodic traffic — aliasing",
      "Reservoir per thread without merge strategy"),
    q("Fisher-Yates Shuffle", "Randomization", "Occasional",
      "Why is Fisher-Yates the correct shuffle algorithm for fair randomization?",
      "Fisher-Yates (Knuth shuffle): O(n) unbiased permutation. For each i from n-1 down to 1, swap i with random j in [0,i]. Every permutation equally likely.",
      "**Production:**\n- **Load balancer** — shuffle backend list for fairness\n- **A/B experiment** — randomize cohort assignment\n- **Game/matchmaking** — fair random ordering\n- **ML training** — shuffle training data each epoch\n\n**Wrong approach:** Sort by random() — biased due to duplicate random keys and sort stability issues.\n\n**Architect:** Use crypto RNG (`RandomNumberGenerator` in .NET) for security-sensitive shuffle; `System.Random` for load distribution.",
      "Fair shuffle matters for experiments and load distribution integrity.",
      "Shuffle vs sample? — Shuffle permutes all; reservoir samples subset.",
      "Seed for reproducibility? — Fixed seed in ML; not for security.",
      "Sort by Math.random() for shuffle",
      "Modulo bias when mapping random to index",
      "Predictable PRNG for lottery or security shuffle"),
    q("Reservoir for Streaming Analytics", "Sampling", "Common",
      "How combine reservoir sampling with streaming analytics pipelines?",
      "Reservoir provides unbiased fixed-size sample stream; downstream aggregates (percentiles, histograms) run on sample with known confidence bounds.",
      "**Pipeline:**\n1. Kafka consumer → reservoir buffer size 10K\n2. On flush interval → compute metrics on sample\n3. Extrapolate with confidence interval to full population\n\n**vs Count-min/HLL:** Reservoir keeps actual events for debugging; sketches aggregate without retention.\n\n**Architect:** Dual path — sketches for real-time dashboard (HLL, count-min), reservoir for drill-down and incident investigation.",
      "Sampling strategy is observability architecture decision.",
      "Sample and hold vs reservoir? — Reservoir uniform; sample-and-hold may bias recent.",
      "Confidence intervals on sample metrics? — Document error bars for stakeholders.",
      "Store all events for 'just in case' at 1M/sec",
      "Metrics on biased every-Nth sample",
      "No sample retention policy — compliance risk"),
    q("Meet-in-the-Middle", "Algorithm Patterns", "Occasional",
      "Explain meet-in-the-middle. When does it apply to architecture-scale problems?",
      "Meet-in-the-middle: split problem in half, solve each half, combine via hash lookup — reduces O(2^n) to O(2^{n/2}). Applies to subset sum, password cracking partitions, pairing search spaces.",
      "**Architectural analogy:**\n- **Distributed join** — partition both sides, hash join on key — same intersection idea\n- **Security** — key search space halved per node in distributed crack (ethical pentest)\n- **Feature combination testing** — test half-configs on each environment, intersect failures\n\n**Coding:** Subset sum for budget allocation with 40 items — brute force 2^40 impossible; meet-in-the-middle 2^20 + 2^20 feasible.\n\n**Architect:** When exponential search seems needed, ask if problem splits for hash-based intersection.",
      "Meet-in-the-middle is exponential search made feasible via hashing.",
      "Hash join similarity? — Build hash on smaller half; probe with larger — SQL optimizer.",
      "Space-time tradeoff? — Store half results in memory/disk for lookup.",
      "Brute force exponential without split attempt",
      "Meet-in-the-middle without hash — O(n²) intersection",
      "Applying to problem without separable halves"),
    q("Bit Manipulation Tricks", "Bit Manipulation", "Occasional",
      "What bit manipulation techniques are useful for architects and performance engineers?",
      "Techniques: power-of-two sizing (mask instead of mod), feature flags in bitmask, bloom filter bit array, permission sets, cardinality in bitmap indexes.",
      "**Production:**\n- **Feature flags** — `flags & FEATURE_X` — compact permission storage\n- **Roaring bitmap** — compressed bitmap indexes in analytics DBs (Druid, Pinot)\n- **Bloom filter** — bit array with k hashes\n- **Connection pooling bitmap** — track free slots\n\n**Useful ops:** `x & (x-1)` clears lowest set bit (count bits); `x & -x` isolates lowest bit.\n\n**Architect:** Bitmap index for low-cardinality columns (status, country) in OLAP — 100× compression vs naive storage.",
      "Bits pack state efficiently at scale — flags, indexes, filters.",
      "Roaring bitmap? — Hybrid array/container — better compression than naive bitmap.",
      "Bit field in API versioning? — Compact capability negotiation.",
      "String column index for boolean-like status",
      "Modulo instead of bitmask on power-of-two ring buffer",
      "Assuming bit ops are always faster — measure"),
    q("Algorithm Interview Communication", "Communication", "Very Common",
      "How should architects communicate algorithm thinking in system design interviews?",
      "Structure: clarify constraints → state brute force → optimize with DS/algorithm → analyze complexity → discuss scale limits → map to production service.",
      "**Template:**\n1. **Constraints** — n, QPS, memory, latency SLO\n2. **Brute force** — 'Scan all rows O(n)' — honest baseline\n3. **Optimization** — 'B-tree index → O(log n)' or 'cache → O(1)'\n4. **Bottleneck** — 'At 10M QPS, single shard fails — shard by userId'\n5. **Production** — 'Redis sorted set, not custom heap'\n\n**Stakeholder version:** Skip Big-O symbols — 'Index cuts query from 30s to 50ms, costs 20% more write I/O.'\n\n**Architect signal:** You connect algorithm to managed service and operational cost.",
      "Communication separates senior architects from silent coders.",
      "When to whiteboard code vs boxes? — System design: boxes; coding round: implement.",
      "Trade-off articulation? — 'We chose eventual consistency for 10× read throughput.'",
      "Jump to Redis without stating access pattern",
      "Only Big-O without scale numbers",
      "Cannot explain why brute force fails at scale"),
    q("Complexity Proof Sketch", "Complexity", "Occasional",
      "How sketch a complexity argument in an interview without formal proofs?",
      "Use recursion tree, aggregate analysis, or loop invariants. State dominant term; ignore lower-order constants. Show you understand structure, not graduate-level proof.",
      "**Recursion tree:** Merge sort — n levels, n work per level → O(n log n).\n\n**Aggregate:** n inserts into heap of size n → each O(log n) → O(n log n) total.\n\n**Amortized:** n appends to dynamic array — n × O(1) + log(n) resizes × O(n) → O(n) total → O(1) amortized.\n\n**Architect version:** 'Each of n requests does hash lookup O(1) average; worst case O(n) if attacker crafts collisions — we use SipHash.'\n\nInterviewers want structured reasoning, not LaTeX.",
      "Proof sketch shows depth without academic overhead.",
      "Loop invariant example? — Binary search — subarray always contains answer.",
      "When amortized vs worst case? — Present both for production systems.",
      "Hand-wave 'it's O(n log n)' without justification",
      "Only average case for security-sensitive hash table",
      "Confuse best, average, and worst case"),
]
