"""Hand-crafted premium Q011–Q050 for Azure Week 12 — Identity."""

from premium_qa_data import q

WEEK_12_Q011_Q050 = [
    q("Entra ID vs AD DS Deep Comparison", "Identity", "Very Common",
      "When deploy AD Domain Services vs Entra ID for a hybrid enterprise?",
      "Entra ID: cloud-native identity for SaaS, OAuth/OIDC apps, Conditional Access. AD DS on VM/IaaS: full LDAP/Kerberos domain control you manage. Entra Domain Services: managed AD-compatible for legacy LDAP lift.",
      "**Decision tree:**\n- **New cloud apps:** Entra ID only\n- **Legacy LDAP/Kerberos app:** Entra DS or AD DS VM\n- **Hybrid users:** Entra Connect sync from on-prem AD\n\n**Architect:** Minimize new AD DS deployments — operational burden (patching, DC HA). Entra DS for GPO/LDAP without VM DCs.",
      "Hybrid identity architecture balances legacy and modern auth.",
      "Entra DS limitations? — No domain admin, fixed schema — verify app compatibility.",
      "Cloud-only org? — Entra ID only — no AD DS needed.",
      "New SaaS app authenticating Kerberos to AD DS",
      "Entra DS without understanding schema limits",
      "No exit plan from on-prem AD"),
    q("Managed Identity Types in Depth", "Identity", "Very Common",
      "Design managed identity strategy for App Service, Functions, and AKS.",
      "System-assigned MI per app resource. User-assigned MI shared across slot swap, multiple Functions, AKS pod identity. Prefer user-assigned for production multi-resource scenarios.",
      "**AKS:** Workload Identity (OIDC) replaces deprecated pod identity. Federate K8s SA to user-assigned MI.\n\n**Architect RBAC:** Grant MI least privilege at resource group scope — `Storage Blob Data Contributor` on one account not subscription.\n\n**Dev:** DefaultAzureCredential chain — local VS login, MI in Azure.",
      "MI strategy prevents secret sprawl across compute types.",
      "MI across tenants? — Not supported — per-tenant MI.",
      "Rotate MI? — No secret to rotate — advantage over SP.",
      "Shared SP credential across 20 microservices",
      "Subscription Contributor on every MI",
      "Pod identity on new AKS clusters without migration plan"),
    q("Conditional Access Policy Design", "Security", "Very Common",
      "Layer Conditional Access policies without lockout risk.",
      "Start report-only. Baseline: all users MFA, block legacy auth. Layer: admin policies (compliant device + MFA), guest restrictions, sign-in risk policies.",
      "**Policy order matters:** Named locations, filter groups, exclusions documented.\n\n**Architect:** Break-glass accounts excluded with Sentinel alert on sign-in. Separate policies per risk persona — don't one-size-fits-all.\n\n**Test:** What If tool before enforcement.",
      "CA is Zero Trust enforcement — design carefully to avoid outages.",
      "Service principal CA? — Conditional Access for workload identities (preview) — know trend.",
      "Session controls? — App enforced restrictions, sign-in frequency.",
      "Enforce all policies day one without report-only",
      "Break-glass in same CA scope as admins",
      "No exclusion documentation"),
    q("PIM Just-in-Time Access", "Security", "Very Common",
      "Configure PIM for Azure subscription Owner role.",
      "Eligible assignment not permanent. Activation requires MFA, justification, ticket ID, max duration 8 hours. Approval workflow for prod subscription.",
      "**Architect:**\n- No standing Owner in prod\n- Audit activation logs to Log Analytics\n- Notification to security on activation\n\n**Emergency access:** Break-glass bypasses PIM — monitored separately.",
      "PIM converts privileged access from standing to just-in-time.",
      "PIM for groups? — PIM-enabled Entra groups — scale RBAC management.",
      "Permanent assignment audit? — Defender Identity recommendations flag.",
      "Standing Global Administrator prod",
      "PIM activation without approval prod",
      "No alert on break-glass usage"),
    q("Service Principal vs Managed Identity", "Identity", "Very Common",
      "Service principal vs managed identity for Azure resource access?",
      "Managed identity: Azure-managed, no credential rotation, tied to Azure resource. Service principal: app registration with secret/cert, needed for external systems, CI/CD (prefer federated over secret).",
      "**Use SP when:** GitHub Actions OIDC (federated), third-party SaaS, non-Azure caller.\n\n**Use MI when:** Azure-hosted app accessing Azure APIs.\n\n**Architect:** Eliminate SP secrets — federated workload identity for pipelines.",
      "Credential type selection is fundamental security architecture.",
      "SP secret expiry? — App registration credential lifetime policies.",
      "Multi-tenant SP? — SaaS vendor pattern — careful consent model.",
      "MI for GitHub Actions (wrong — use federated SP)",
      "SP secret in ARM template plaintext",
      "Same SP Owner on all subscriptions"),
    q("App Registration vs Enterprise Application", "Identity", "Common",
      "Multi-tenant SaaS app registration architecture?",
      "One multi-tenant app registration (definition). Each customer tenant creates enterprise application instance on admin consent. Per-tenant service principal for API access.",
      "**Architect documents:**\n- Redirect URIs per environment\n- API exposed scopes and app roles\n- Admin consent URL for customer onboarding\n\n**Enterprise app:** SSO blade, user assignment, conditional access targeting.",
      "SaaS identity model separates definition from tenant instances.",
      "Publisher verification? — Required for customer trust — MPN ID.",
      "App roles vs scopes? — App roles for RBAC in API; scopes for delegated permissions.",
      "Confuse registration object ID with enterprise app ID",
      "Customer admin consent not documented",
      "Over-permissioned Graph API scopes"),
    q("Entra B2B Guest Access", "Identity", "Common",
      "Design B2B collaboration for external consultants.",
      "Invite guest users to home tenant. CA policies for guests (MFA, device compliance if enrolled). Restrict guest visibility in directory.",
      "**Architect:**\n- Guest access reviews quarterly\n- Limit guest to specific apps via assignment\n- Cross-tenant sync for partner org auto-provisioning (advanced)\n\n**vs B2C:** B2B for workforce collaboration; B2C for consumer apps.",
      "B2B extends workforce identity to partners securely.",
      "Redeem invitation flow? — One-time link — expiry policy.",
      "Guest can enumerate users? — Restrict in external collaboration settings.",
      "Guest with same CA as employees without assessment",
      "Never review guest access",
      "B2B for customer ecommerce login"),
    q("Entra External ID for B2C", "Identity", "Common",
      "Entra External ID (CIAM) vs legacy Azure AD B2C?",
      "External ID is converged CIAM platform — custom sign-up, social IdPs, branded flows. B2C tenants continue; new projects evaluate External ID.",
      "**Architect consumer app:**\n- Separate tenant from workforce Entra\n- User flows or custom policies (legacy B2C) / native sign-up (External ID)\n- Token customization for app claims\n\n**Scale:** Millions of users — no directory object limit concerns with proper architecture.",
      "Know B2C → External ID evolution for architect roadmap.",
      "Social identity providers? — Google, Facebook, Apple — configure per app.",
      "MFA for consumers? — Risk-based — balance UX.",
      "Workforce and consumer same tenant",
      "Store consumer PII in workforce directory",
      "Custom policy complexity without docs"),
    q("Passwordless Authentication", "Identity", "Very Common",
      "Roll out passwordless for enterprise Entra ID users.",
      "Windows Hello for Business, FIDO2 security keys, Microsoft Authenticator phone sign-in. Combined registration in Entra — start with security-key pilots.",
      "**Architect rollout:**\n1. Enable Combined Registration\n2. CA requires MFA → upgrade to passwordless-capable MFA\n3. Disable password legacy auth\n4. Helpdesk process for lost key\n\n**Phishing-resistant:** FIDO2 and WHfB resist credential theft.",
      "Passwordless is Microsoft strong auth direction.",
      "Temporary Access Pass? — Bootstrap passwordless registration.",
      "Passkeys? — FIDO2 aligned — watch Entra roadmap.",
      "SMS as only MFA calling it passwordless",
      "No backup auth method",
      "Passwordless without CA policy update"),
    q("Certificate-Based Authentication", "Identity", "Common",
      "Certificate-based auth for service-to-service on Azure?",
      "App registration upload cert (public key) — app uses private cert for client assertion JWT. No client secret.",
      "**vs Federated credential:** CBA for traditional cert PKI; federation for OIDC trust (GitHub, K8s).\n\n**Architect:** Cert expiry monitoring 60 days ahead. Store private cert in Key Vault HSM. Auto-renew with ACME/internal CA integration.",
      "Certs beat secrets for long-lived service auth when managed properly.",
      "Mutual TLS? — APIM/API Management client cert validation at gateway.",
      "Self-signed prod? — Enterprise CA or Key Vault issued preferred.",
      "Expired cert no monitoring",
      "Private key in repo",
      "Cert auth without rotation runbook"),
    q("Entra Connect Sync Architecture", "Hybrid", "Very Common",
      "Design Entra Connect sync for hybrid identity.",
      "Entra Connect on hardened VM syncs on-prem AD to Entra ID. Password hash sync (PHS) default; PTA or federation for advanced.",
      "**Architect:**\n- Staging mode second server for DR\n- OU filtering sync scope\n- Group writeback if needed\n- Monitor sync errors in Entra Connect Health\n\n**Cloud sync:** Lightweight agent alternative for simple scenarios.",
      "Hybrid sync is critical path — HA and monitoring mandatory.",
      "PHS vs PTA? — PHS simpler; PTA keeps password on-prem.",
      "Soft match vs hard match? — UPN alignment prevents duplicate objects.",
      "Single Connect server no staging",
      "Sync all OUs including service accounts",
      "Ignore sync error emails"),
    q("Pass-Through Authentication", "Hybrid", "Common",
      "Pass-through authentication vs password hash sync?",
      "PTA: Entra sign-in validated against on-prem AD in real time — password never in cloud. Requires PTA agents on-prem. PHS: hash synced — cloud auth without on-prem dependency.",
      "**Choose PTA when:** policy forbids password hash in cloud, real-time account disable needed.\n\n**Architect:** PTA agents HA (minimum 3). Fallback to PHS documented if agents down.\n\n**Limitation:** PTA agent outage blocks cloud sign-in.",
      "Auth method affects availability and compliance posture.",
      "PTA vs Federation AD FS? — PTA simpler; federation for custom auth flows.",
      "Seamless SSO? — Kerberos ticket for domain-joined devices.",
      "PTA single agent",
      "PTA without PHS break-glass fallback plan",
      "PTA for internet-only users"),
    q("Federated Identity AD FS", "Hybrid", "Common",
      "When use AD FS federation instead of PHS/PTA?",
      "Federation when: custom auth (smart card step-up), third-party IdP integration legacy, claim rules complex. AD FS farm on-prem — higher ops burden.",
      "**Architect:** Microsoft recommends PHS/PTA for new hybrids unless federation requirement clear.\n\n**Modern:** Move to Entra federation with custom IdP via OIDC where possible — retire AD FS long-term.",
      "Federation is legacy-heavy — justify before designing.",
      "AD FS WAP? — Web Application Proxy DMZ — don't expose AD FS direct.",
      "Certificate management AD FS? — Token signing cert rotation critical.",
      "AD FS for greenfield hybrid",
      "AD FS without HA farm",
      "No token signing cert expiry monitoring"),
    q("MFA Methods Comparison", "Security", "Very Common",
      "Rank MFA methods for security and usability.",
      "Most secure: FIDO2/WHfB (phishing-resistant). Strong: Microsoft Authenticator push with number matching. Weaker: SMS/voice (SIM swap risk).",
      "**Architect CA policy:** Authentication strength — require phishing-resistant for admins.\n\n**Registration:** Combined registration campaign; block weak methods for privileged roles via Authentication methods policy.",
      "MFA method choice is measurable security difference.",
      "OATH hardware tokens? — Supported for air-gapped scenarios.",
      "MFA fatigue attacks? — Number matching + additional context.",
      "SMS-only MFA for Global Admin",
      "Allow MFA bypass codes routinely",
      "No method upgrade path for users"),
    q("Entra ID Protection", "Security", "Common",
      "Use Identity Protection risk signals in architecture.",
      "Detects leaked credentials, anonymous IP, atypical travel, malware-linked IP. Risk levels feed Conditional Access (sign-in risk, user risk).",
      "**Architect workflows:**\n- Medium sign-in risk → MFA\n- High sign-in risk → block or password change\n- User risk high → force password reset or block\n\n**License:** Entra ID P2 for full Identity Protection.",
      "Risk-based auth automates threat response.",
      "Risk detections export? — Sentinel integration for SOC.",
      "Disable risk policy on break-glass? — Yes — separate monitoring.",
      "Ignore Identity Protection alerts",
      "Risk policy without user communication",
      "P1 license expecting full risk features"),
    q("Risk-Based Conditional Access", "Security", "Common",
      "Design risk-based CA policies for remote workforce.",
      "Sign-in risk: require MFA medium+, block high. User risk: require password change for high user risk. Combine with named locations — trusted office IPs lower friction.",
      "**Architect balance:** Productivity vs security — start report-only on new detections.\n\n**Integration:** Defender for Cloud Apps session policies for risky OAuth apps.",
      "Risk policies adapt to threat without static IP reliance alone.",
      "Insider risk? — Different product — don't conflate with sign-in risk.",
      "Continuous Access Evaluation? — Real-time revocation on risk change.",
      "Block all foreign sign-ins without business justification",
      "Risk policy no exception for traveling execs",
      "Never tune false positives"),
    q("Workload Identity Federation", "Identity", "Very Common",
      "Explain workload identity federation without secrets.",
      "App registration federated credential trusts external OIDC issuer (GitHub, K8s, other cloud). External workload exchanges OIDC token for Entra access token — no client secret.",
      "**Setup:** Issuer, subject, audience on federated credential. GitHub: `repo:org/repo:ref:refs/heads/main`.\n\n**Architect:** Standard pattern for all CI/CD and K8s — ban secret-based SP auth in platform guardrails.",
      "Federation is modern SP replacement.",
      "Multiple federated credentials? — Per repo/environment subject.",
      "Audit federated sign-ins? — Entra sign-in logs show workload identity.",
      "Long-lived SP secret for GitHub Actions",
      "Over-broad subject `repo:org/*:*`",
      "No branch protection on federated repos"),
    q("GitHub OIDC to Azure", "DevOps", "Very Common",
      "Configure GitHub Actions OIDC deploy to Azure without secrets.",
      "App registration federated credential for GitHub OIDC. Workflow `permissions: id-token: write`. `azure/login@v2` with client-id, tenant-id, subscription-id.",
      "**Architect RBAC:** Grant federated SP `Contributor` on resource group not subscription Owner.\n\n**Environments:** Separate federated credential subject per GitHub environment (prod vs dev).",
      "OIDC pipeline auth is platform security baseline.",
      "Azure DevOps equivalent? — Service connection workload identity federation.",
      "Token theft? — Subject binding prevents other repos using credential.",
      "AZURE_CREDENTIALS JSON secret",
      "Owner role for deploy pipeline",
      "Same credential prod and dev"),
    q("Kubernetes SA Token Volume Projection", "Identity", "Common",
      "AKS workload identity with service account token projection?",
      "Kubernetes ServiceAccount annotated with Entra app client ID. Token projected into pod via OIDC — app uses DefaultAzureCredential or SDK token credential.",
      "**Migration:** AKS workload identity replaces legacy pod identity. Enable OIDC issuer on cluster.\n\n**Architect:** One user-assigned MI per workload class; federate via SA annotation. Avoid mounting Azure SP secrets as K8s secrets.",
      "K8s-native identity is Azure best practice on AKS.",
      "Token expiration? — Projected token rotates — handle refresh in SDK.",
      "Multi-tenant K8s? — Namespace isolation + separate MI per namespace.",
      "Legacy aad-pod-identity on new clusters",
      "Cluster admin kubeconfig shared",
      "SP secret in K8s Secret manifest"),
    q("Microsoft Entra External ID", "Identity", "Common",
      "Architect consumer identity with Microsoft Entra External ID.",
      "Dedicated workforce vs external tenant separation. External ID provides branded authentication experiences, social and local accounts, MFA for consumers.",
      "**Architect:**\n- Custom domains for auth (`login.contoso.com`)\n- API connectors for custom logic at sign-up\n- Rate limiting and fraud signals\n\n**Integration:** OIDC standard — any mobile/web app.",
      "External ID is strategic CIAM direction.",
      "User migration B2C? — Bulk import and gradual cutover patterns.",
      "Custom extensions? — API connectors call REST endpoints.",
      "Consumer users in workforce tenant",
      "No separate CA policy for external users",
      "Shared app registration workforce and consumer"),
    q("Custom Domain in Entra", "Identity", "Common",
      "Configure custom domain for Entra ID sign-in branding?",
      "Verify domain DNS TXT record. Set primary domain for UPN suffix. Custom branding on login page — logo, background, terms link.",
      "**Architect:** Users sign in with `@company.com` not `@tenant.onmicrosoft.com`. Required for federation alignment.\n\n**Email-verified domains for B2C/External ID:** separate DNS verification flow.",
      "Custom domain is professional identity hygiene.",
      "Federated domain? — Cannot convert cloud-only managed domain easily.",
      "Multiple domains? — One primary; aliases supported.",
      "Permanent onmicrosoft.com UPNs prod",
      "DNS verification lapsed",
      "Brand assets not updated phishing risk"),
    q("Tenant Isolation Strategy", "Identity", "Common",
      "Isolate production from non-production Entra tenants?",
      "Separate Entra tenants for prod vs dev/test — prevents misconfigured CA/policy blast radius. Cross-tenant B2B for admin access if needed.",
      "**Architect:**\n- Prod tenant: strict CA, PIM, no experimental apps\n- Dev tenant: developer freedom, synthetic data\n- No prod data in dev tenant apps\n\n**Alternative:** Single tenant with strict app/CA scoping — harder at scale.",
      "Tenant boundary is strongest identity isolation.",
      "Cross-tenant sync? — Partner provisioning — not prod/dev substitute.",
      "Management group vs tenant? — Azure RBAC vs identity boundary — both needed.",
      "Prod and dev same tenant same CA",
      "Prod API app registration in dev tenant",
      "Global admin shared across tenants same person no PIM"),
    q("Cross-Tenant Synchronization", "Identity", "Occasional",
      "Use cross-tenant sync for partner user provisioning?",
      "Automated provisioning of member users from source tenant to target tenant — B2B alternative for trusted partners needing member (not guest) experience.",
      "**Architect:** Source tenant controls. target tenant one-way sync. Define scope groups. Monitor provisioning logs.\n\n**vs B2B guest:** Member users in target — different CA and licensing implications.",
      "Cross-tenant sync automates partner onboarding at scale.",
      "Provisioning conflicts? — Attribute mapping and quarantine review.",
      "Reverse sync? — Not supported — design one authoritative source.",
      "Bidirectional sync expectation",
      "Sync all users not scoped group",
      "No offboarding sync disable"),
    q("Directory Roles vs App Roles", "Identity", "Very Common",
      "Directory roles vs app roles in API authorization?",
      "Directory roles: Entra admin (Global Reader, User Admin) — manage tenant. App roles: defined on app registration, assigned to users/groups/SPs — authorize in your API.",
      "**Architect API:** Validate `roles` claim in JWT — map to permissions. Don't overload directory roles for app RBAC.\n\n**Example app roles:** `Order.Read`, `Order.Admin` assigned via enterprise app.",
      "Clear role separation prevents authorization model confusion.",
      "Group vs app role? — Assign group to app role for scale.",
      "Claims mapping? — Optional claims emit roles in token.",
      "Global Admin check in application code",
      "App roles not defined on registration",
      "Directory role for business permission"),
    q("OAuth 2.0 Flows Selection", "Identity", "Very Common",
      "Select OAuth 2.0 flow per application type on Azure.",
      "Auth code + PKCE: SPA, mobile, native. Client credentials: daemon/service. Auth code (confidential): web server apps with secret/cert. OBO: API calling API with user context. Device code: CLI/IoT constrained input.",
      "**Deprecated:** Implicit flow, ROPC — never new apps.\n\n**Architect:** APIM validates token at edge; backend validates audience, issuer, scopes.",
      "OAuth flow literacy is identity architecture core.",
      "Hybrid flow? — Deprecated — use auth code.",
      "Native redirect URI? — Mobile platform-specific URIs registered.",
      "Implicit flow new SPA 2024",
      "ROPC for mobile login",
      "No PKCE public client"),
    q("PKCE for Mobile Apps", "Security", "Very Common",
      "Why PKCE mandatory for mobile and SPA on Entra ID?",
      "Public clients cannot store client secret. PKCE sends code_challenge with authorize request, code_verifier with token exchange — prevents authorization code interception.",
      "**Architect mobile:** Use MSAL — PKCE automatic. Register redirect URI `msauth://` or app link. Broker auth via Authenticator/Company Portal for SSO.\n\n**No secret in mobile binary — ever.",
      "PKCE is non-negotiable for public clients.",
      "S256 vs plain? — S256 required — plain rejected.",
      "Dynamic client registration? — Not typical Entra — manual app reg.",
      "Embed client secret in Xamarin app",
      "Custom OAuth without PKCE",
      "Token cache unencrypted on device"),
    q("Token Lifetime Policies", "Identity", "Common",
      "Configure refresh and access token lifetime policies.",
      "Configurable token lifetime policies (legacy) and continuous access evaluation for session. Default access token ~1 hour; refresh token sliding window.",
      "**Architect:** Short access token + refresh for security. CA sign-in frequency enforces re-auth for sensitive apps.\n\n**Session revocation:** CAE enables near-real-time token invalidation on user disable/risk.",
      "Token lifetime balances UX and security.",
      "Refresh token max inactive? — 90 days default single tenant — document.",
      "Configurable token lifetime retirement? — Moving to CA sign-in frequency.",
      "Access token 24 hours for convenience",
      "No sign-in frequency on financial app",
      "Ignore token lifetime when user disabled"),
    q("Refresh Token Rotation", "Security", "Common",
      "Refresh token rotation and reuse detection in Entra?",
      "Single-page apps and native clients get rotating refresh tokens — each use issues new refresh token. Reuse of old token signals theft — revoke family.",
      "**Architect:** MSAL handles rotation. Monitor `invalid_grant` spikes.\n\n**Compromise response:** Revoke all refresh tokens for user + force password reset.",
      "Rotation limits refresh token theft window.",
      "Family refresh tokens? — Entire chain invalidated on reuse detection.",
      "Long-lived refresh without rotation awareness?",
      "Custom token cache ignoring rotation",
      "No monitoring anomalous refresh patterns",
      "Store refresh token in secure storage not localStorage — XSS risk"),
    q("Secret vs Certificate Credentials", "Security", "Very Common",
      "App registration credential strategy — secret or certificate?",
      "Certificates preferred for prod SP — longer life, no plaintext secret. Secrets: max 2 years, rotate regularly, store Key Vault only.",
      "**Architect policy:**\n- Block secret creation via CA/App governance\n- Federated credentials over cert where possible (CI/CD)\n- Expiry alerts 30/60/90 days\n\n**HSM:** Premium Key Vault for private key protection.",
      "Credential type and storage define breach blast radius.",
      "Secret expiry notification? — App registration owners + automation.",
      "Multiple active secrets? — Overlap during rotation only.",
      "Never-rotated 5-year secret",
      "Secret in terraform state unencrypted",
      "Cert private key exportable to dev laptop"),
    q("Entra Permissions Management", "Governance", "Occasional",
      "Use Entra Permissions Management for cloud access governance?",
      "Discovers permissions across AWS/Azure/GCP (where integrated), right-sizing recommendations, access requests, segregation of duties policies.",
      "**Architect:** Complements PIM — focuses permission analytics and least privilege at scale.\n\n**Workflow:** Over-privileged identity alert → review → downgrade or PIM eligible.",
      "Permissions Management extends governance beyond Azure RBAC alone.",
      "SoD policies? — Block toxic combinations (e.g., create VM + reset password).",
      "Integration Sentinel? — Permission anomaly alerts.",
      "Ignore over-permissioned SP reports",
      "No SoD for finance systems",
      "Manual access reviews only spreadsheets"),
    q("LDAP over TLS Hybrid", "Hybrid", "Common",
      "Secure LDAP (LDAPS) for apps connecting to Entra Domain Services.",
      "Entra DS exposes LDAPS on port 636. Apps must trust Entra DS CA chain. Prefer LDAPS over plain LDAP — credentials encrypted.",
      "**Architect:** Private Link to Entra DS VNet. No LDAP over internet. Certificate validation enforced in app config.\n\n**Alternative:** Modernize app to OAuth instead of LDAP bind.",
      "LDAPS is minimum for legacy directory auth.",
      "LDAPS vs StartTLS? — Entra DS documents 636 LDAPS.",
      "Service account LDAP? — Dedicated account least privilege OU.",
      "Plain LDAP port 389 prod",
      "LDAP bind account password never rotated",
      "LDAP app not in VNet with Entra DS"),
    q("Hybrid Azure AD Join", "Devices", "Common",
      "Hybrid Azure AD join vs Entra join for corporate devices?",
      "Hybrid join: domain-joined PC synced to Entra via Connect — SSO to cloud apps. Entra join: cloud-first devices registered directly in Entra.",
      "**Architect:**\n- Hybrid: existing AD GPO investment, on-prem apps\n- Entra join + Autopilot: modern provisioning\n\n**CA:** Require hybrid OR Entra join for resource access.",
      "Device identity enables device-based CA.",
      "Co-management Intune? — Hybrid join path to MDM.",
      "Registration vs join? — Registration alone weaker — join preferred.",
      "CA device compliance without join",
      "Hybrid join without Connect health monitoring",
      "Personal devices hybrid joined"),
    q("Continuous Access Evaluation", "Security", "Common",
      "Implement Continuous Access Evaluation (CAE) in app architecture.",
      "CAE-capable apps receive critical event notifications — user disabled, password changed, location change — revoke access in minutes not token TTL.",
      "**Requirements:** MS Graph, Exchange, SharePoint support CAE; custom APIs must implement token validation + CAE protocol.\n\n**Architect:** Enable CAE in MSAL apps. Pair with strict token lifetime and sign-in frequency for custom APIs.",
      "CAE closes token revocation gap.",
      "CAE IP address validation? — Critical events on IP mismatch.",
      "Fallback without CAE? — Standard token lifetime until expiry.",
      "Assume disable user instant without CAE",
      "Custom API ignores token revocation events",
      "CAE not tested in DR user lockout"),
    q("Global Secure Access Overview", "Networking", "Common",
      "What is Microsoft Global Secure Access (GSA)?",
      "Converged SASE offering: Entra Internet Access (SWG) + Entra Private Access (ZTNA) replacing legacy Global Secure Access preview branding.",
      "**Architect:** Entra ID-centric secure access — identity drives access not VPN perimeter.\n\n**Components:** Quick Access apps, forwarding profile on devices, Conditional Access integration.",
      "GSA is Microsoft's SSE/SASE identity story.",
      "GSA vs Azure VPN? — VPN perimeter vs identity-based ZTNA.",
      "Client required? — Global Secure Access client on managed devices.",
      "VPN only remote access strategy",
      "Ignore GSA for Zero Trust roadmap",
      "No CA integration with private access"),
    q("Entra Internet Access", "Networking", "Common",
      "Entra Internet Access for secure web gateway?",
      "Cloud SWG — traffic forwarded from device through Microsoft edge, URL filtering, TLS inspection policies, threat intelligence, integrated with Entra sign-in.",
      "**Architect use cases:**\n- Replace legacy proxy for remote workers\n- Enforce web policy by Entra group\n- Log internet access to Sentinel\n\n**Deploy:** Client forwarding profile + CA requiring compliant device.",
      "Internet Access is SWG leg of GSA.",
      "Breakout Office 365? — Bypass rules for optimized paths.",
      "Third-party SWG coexistence? — Migration period dual stack.",
      "No web filtering remote users",
      "TLS inspect without privacy review",
      "Policy not tied to identity groups"),
    q("Entra Private Access", "Networking", "Common",
      "Entra Private Access vs traditional VPN for internal apps?",
      "Private Access publishes internal apps via Quick Access — users connect through Microsoft ZTNA edge, no full network tunnel. Per-app authorization with Entra ID.",
      "**Architect:** Replace VPN for SaaS-like internal web apps. Connector on-prem or Azure publishes app.\n\n**Benefits:** No lateral movement on full tunnel, CA enforced per session.",
      "Private Access is ZTNA for private apps.",
      "Connector HA? — Multiple connectors for resilience.",
      "On-prem Active Directory apps? — Publish specific URLs not entire VLAN.",
      "Full VPN for one internal dashboard",
      "Publish RDP to entire subnet",
      "No connector monitoring"),
    q("Identity Governance Lifecycle", "Governance", "Common",
      "Design identity lifecycle from joiner to leaver.",
      "Automated provisioning (HR-driven), access packages, access reviews, entitlement management, deprovisioning disables account + revokes tokens.",
      "**Architect workflow:**\n1. Joiner: Entra ID + group + app assignments via SCIM/Logic Apps\n2. Mover: access review trigger role change\n3. Leaver: disable account, revoke sessions, transfer ownership\n\n**Target:** <4 hours leaver SLA for prod access removal.",
      "Lifecycle automation prevents orphaned access.",
      "Guest leaver? — Same disable — often forgotten.",
      "SCIM provisioning? — SaaS apps auto user sync.",
      "Manual ticket for every new hire app access",
      "Disabled AD user still active Entra",
      "No leaver checklist"),
    q("Access Reviews Configuration", "Governance", "Common",
      "Configure Entra access reviews for group and app assignments.",
      "Quarterly review of group membership, app role assignments, PIM activations. Self-review + manager or designated reviewer. Auto-apply remove if no response.",
      "**Architect:**\n- Reviews for privileged groups monthly\n- Exclude break-glass with separate process\n- Export results for audit\n\n**Integration:** Defender Identity access review recommendations.",
      "Access reviews prove least privilege over time.",
      "Recurring vs one-time? — Recurring for SOX cadence.",
      "If reviewer absent? — Fallback reviewer configured.",
      "Access reviews never auto-apply",
      "Privileged groups excluded from review",
      "Annual review only for admins"),
    q("Entitlement Management", "Governance", "Common",
      "Use entitlement management access packages for project access.",
      "Access package bundles groups, apps, SharePoint sites. Request workflow, approval, time-bound assignment, automatic expiration.",
      "**Architect:** Catalog per department. External users via connected org B2B. Policies: max duration 90 days project access.\n\n**vs PIM:** PIM for admin roles; entitlement management for business resource bundles.",
      "Entitlement management is self-service governance with guardrails.",
      "Approval workflows? — Single or multi-stage + escalation.",
      "Assignment customization? — Questions at request time.",
      "Permanent project group membership",
      "Manual SharePoint permission grants",
      "No expiration on vendor package"),
    q("PIM Workflow and Audit", "Security", "Very Common",
      "End-to-end PIM activation workflow for production support?",
      "Engineer eligible for `Contributor` on prod RG. Activation: MFA, ticket number, 4-hour window, optional approver. Work performed. Activation expires auto. Audit log to Log Analytics + Sentinel rule for after-hours activation.",
      "**Architect:**\n- No permanent active assignments prod\n- Weekly PIM audit report\n- Integration ServiceNow webhook for ticket validation (custom)\n\n**Emergency:** Break-glass outside PIM with C-level approval path.",
      "PIM workflow demonstrates operational maturity in interviews.",
      "PIM alerts Sentinel? — KQL on `Add member to role` PIM logs.",
      "Audit export retention? — Align 7 years compliance.",
      "PIM activated role never expires bug ignored",
      "Same person requester and approver",
      "PIM logs not monitored"),
]
