"""Hand-crafted premium Q011–Q050 for Azure Week 11 — Data Platform."""

from premium_qa_data import q

WEEK_11_Q011_Q050 = [
    q("Azure SQL Tier Selection", "SQL", "Very Common",
      "How do you select the right Azure SQL tier for a new production OLTP workload?",
      "Start with vCore General Purpose for most OLTP. Move to Business Critical for low-latency IO and built-in read scale-out. Hyperscale when database exceeds ~4 TB or needs rapid storage growth.",
      "**Decision matrix:**\n- **General Purpose (GP):** cost-effective, remote storage, 99.99% SLA with zone redundancy\n- **Business Critical (BC):** local SSD, read replicas on same instance, 99.995% SLA — finance/trading latency\n- **Hyperscale:** auto-growing storage to 100 TB+, fast backup/restore, read replicas\n\n**Architect process:** Baseline DTU/vCore from load test, right-size compute, use reserved capacity for steady baseline. Serverless vCore for intermittent dev/test only.\n\n**SaaS pattern:** Many small DBs → elastic pool on GP vCore rather than individual tiers.",
      "Tier selection ties directly to SLA, cost, and scale ceiling.",
      "When GP vs BC read scale? — BC has free readable secondaries on same node; GP needs active geo-replication for read scale.",
      "Serverless for production? — Rarely — auto-pause and cold start unacceptable for steady OLTP.",
      "Choosing DTU prod without vCore analysis",
      "Hyperscale for 50 GB database — overkill",
      "No reserved capacity on predictable baseline"),
    q("Cosmos DB Consistency Levels", "Cosmos DB", "Very Common",
      "Explain Cosmos DB consistency levels and when to use each.",
      "Five levels from strong to eventual: Strong, Bounded Staleness, Session, Consistent Prefix, Eventual. Session is default — best balance for most apps.",
      "**Strong:** linearizability — single region only, highest RU cost. Use financial ledger within region.\n\n**Bounded Staleness:** max lag in K versions or T seconds — global reads with predictable staleness.\n\n**Session:** reads see own writes — ideal for user-scoped data (cart, profile).\n\n**Consistent Prefix / Eventual:** lowest RU, highest throughput — analytics counters, social feeds.\n\n**Architect:** Default Session; document per-container consistency in ADR. Multi-region writes require Session or weaker — Strong only single-region writer.",
      "Consistency level is a cost, latency, and correctness trade-off.",
      "Can you mix consistency per request? — Yes — override at request level within account default.",
      "Strong multi-region? — Not supported for multi-writer — use Session + conflict resolution.",
      "Strong everywhere for cost savings",
      "Eventual for inventory without business acceptance",
      "No consistency documented in API contracts"),
    q("Blob Storage Access Tiers", "Storage", "Very Common",
      "Compare Hot, Cool, Cold, and Archive blob tiers for a document archive platform.",
      "Hot: frequent access, highest storage cost, lowest access cost. Cool: 30+ day retention, infrequent access. Cold: 90+ days, cheaper storage. Archive: 180+ days, lowest storage, highest retrieval latency (hours).",
      "**Minimum retention:** Cool 30 days, Cold 90 days, Archive 180 days — early deletion penalty.\n\n**Architect design:** Lifecycle policy automates tier transitions. Archive for compliance docs accessed once a year.\n\n**Example:** Invoices Hot 7 days → Cool 1 year → Archive 7 years.\n\n**Premium block blobs:** sub-ms latency for Hot tier hot paths — separate from tier choice.",
      "Tier selection is FinOps architecture — wrong tier doubles storage bill.",
      "Archive rehydrate priority? — High (minutes-hours) vs Standard ( hours) — cost vs urgency.",
      "Cool vs Cold break-even? — Model access frequency — Cold wins below ~1 read/month per blob.",
      "All blobs Hot forever",
      "Archive for monthly payroll reports",
      "No lifecycle policy in IaC"),
    q("Azure Data Factory Pipelines", "Data Integration", "Common",
      "Design an ADF pipeline for nightly SQL-to-Data-Lake ETL.",
      "Linked services for SQL and ADLS Gen2. Copy activity with incremental watermark column. Trigger schedule or tumbling window. Staging in ADLS as Parquet partitioned by date.",
      "**Pattern:**\n1. Lookup last watermark from metadata table\n2. Copy activity `query` with `WHERE modified > @{watermark}`\n3. Update watermark on success\n4. Failure alert via Logic App / Azure Monitor\n\n**Architect:** Use managed VNet integration + private endpoints for SQL. Git integration for ARM/Bicep-deployed ADF. Self-hosted IR only for on-prem sources.",
      "ADF is orchestration — not transformation engine for complex logic.",
      "Mapping data flows vs Copy? — Data flows for transforms; Copy for bulk movement.",
      "Parameterize environments? — ARM template parameters or Bicep — separate dev/prod linked services.",
      "Full load nightly on 500 GB table",
      "No watermark — duplicates or missed rows",
      "Credentials in pipeline not Key Vault"),
    q("Synapse Analytics Architecture", "Analytics", "Very Common",
      "When use Synapse dedicated SQL pool vs serverless vs Spark pool?",
      "Dedicated pool: provisioned DW, predictable performance, large aggregations. Serverless: ad-hoc queries on Data Lake files, pay per TB scanned. Spark pool: ETL, ML, complex transforms on big data.",
      "**Modern lakehouse:** Ingest to ADLS (Parquet/Delta) → Spark for curation → Serverless SQL for analysts → Dedicated pool for heavy BI if needed.\n\n**Architect:** Don't duplicate data — medallion layers in ADLS, Synapse workspaces query in place.\n\n**Cost:** Pause dedicated pool off-hours. Serverless — partition Parquet and use column pruning to reduce scan cost.",
      "Synapse is a workspace orchestrating multiple compute engines on shared storage.",
      "Synapse Link for Cosmos? — Near real-time analytics without ETL batch.",
      "Dedicated vs Fabric warehouse? — Fabric convergence — know both for interviews.",
      "Dedicated pool for 10 GB monthly report",
      "Serverless full table scan on CSV",
      "No pause schedule on dedicated pool"),
    q("PostgreSQL Flexible Server", "Databases", "Common",
      "Azure Database for PostgreSQL Flexible Server vs Single Server — why Flexible?",
      "Flexible Server is current platform: zone redundancy, better VNet integration, custom maintenance window, burstable and general-purpose compute. Single Server is retired — migrate to Flexible.",
      "**Architect choices:**\n- **Burstable:** dev/test, low CPU average\n- **General Purpose:** production OLTP\n- **Memory Optimized:** analytics on Postgres, large cache\n\n**HA:** zone-redundant HA with automatic failover. Read replicas for read scale.\n\n**Extensions:** pgvector, PostGIS — verify allowlist for AI/search workloads.",
      "Flexible Server is default Postgres choice on Azure.",
      "Private access? — Private endpoint or VNet injection — no public endpoint prod.",
      "Migration from Single Server? — Azure migration tooling — plan downtime or DMS.",
      "New projects on Single Server",
      "Public endpoint production",
      "No HA on business-critical Postgres"),
    q("Azure Cache for Redis Tiers", "Caching", "Common",
      "Compare Basic, Standard, Premium Redis tiers for session cache.",
      "Basic: single node, no SLA — dev only. Standard: two-node replica, 99.9% SLA. Premium: clustering, persistence, VNet injection, geo-replication.",
      "**Production session cache:** Standard C1 minimum. **Premium when:** >53 GB data, shard cluster, persistence (AOF/RDB), private VNet, active geo-replication for DR.\n\n**Architect:** Cache-aside pattern, TTL on sessions, handle Redis failure gracefully (re-login acceptable vs data loss).\n\n**Enterprise:** Azure Managed Redis (new) vs legacy Cache for Redis — know rebranding direction.",
      "Redis tier maps to HA, scale, and network isolation needs.",
      "Clustering when? — Memory exceeds single node max or need horizontal shard.",
      "Redis vs SQL session state? — Redis for scale and speed; SQL when durability mandatory.",
      "Basic tier production",
      "No TTL — memory eviction surprises",
      "Cache as source of truth for orders"),
    q("Table Storage vs Cosmos DB Table API", "Storage", "Common",
      "Table Storage vs Cosmos DB Table API — when each?",
      "Table Storage: legacy, cheap, single region, Key/Value within partition. Cosmos Table API: global distribution, SLA, throughput control, same SDK surface.",
      "**Choose Table Storage:** simple internal tooling, single region, lowest cost, no SLA requirement.\n\n**Choose Cosmos Table API:** need multi-region, RU scaling, consistency options, enterprise SLA.\n\n**Architect:** Greenfield tabular NoSQL → prefer Cosmos native API (SQL/NoSQL) over Table API unless SDK compatibility required.",
      "Table API is migration path — not default for new global apps.",
      "Partition key Table Storage? — `PartitionKey` + `RowKey` — same hot partition rules as Cosmos.",
      "Azure Tables SDK? — New `Azure.Data.Tables` works with both — connection string differs.",
      "Table Storage for global user-facing app",
      "Cosmos Table API without RU planning",
      "Cross-partition scan on large table"),
    q("Data Lake Storage Gen2 Design", "Storage", "Very Common",
      "Design ADLS Gen2 folder structure for enterprise analytics.",
      "Hierarchical namespace enabled on storage account. Zones: raw/bronze, curated/silver, analytics/gold. Partition by `year/month/day/`. RBAC at container/folder level.",
      "**Features:** ACLs + RBAC, atomic directory operations, POSIX-like semantics for Spark/Hadoop.\n\n**Architect:**\n- Separate storage accounts per environment (dev/prod)\n- Managed identity for Synapse/Databricks access\n- Lifecycle to Cool/Archive on raw after N days\n\n**Security:** No public access, private endpoints, Entra ID only — avoid shared keys.",
      "ADLS Gen2 is analytics landing zone foundation.",
      "ABFS driver? — `abfss://` URI — always use OAuth not key.",
      "One account vs many? — Domain-separated accounts (finance, marketing) for blast radius.",
      "Flat blob storage without hierarchical namespace",
      "Shared key in Spark config",
      "No partition strategy — full scans"),
    q("Private Endpoint for Azure SQL", "Networking", "Very Common",
      "Configure Azure SQL with Private Endpoint — what breaks if misconfigured?",
      "SQL gets private IP in subnet. Requires private DNS zone `privatelink.database.windows.net` linked to VNet. Without DNS, apps still resolve public IP — connection fails or bypasses private path.",
      "**Checklist:**\n1. Disable public network access (prod)\n2. Create private endpoint in app subnet\n3. Private DNS zone group on endpoint\n4. Link DNS zone to all VNets that need access (hub-spoke)\n\n**Architect:** Test with `nslookup sqlserver.database.windows.net` from VM — must return 10.x private IP.\n\n**Cross-region:** Private endpoint same region as SQL; consumers in other regions via peered VNet.",
      "Private Link for SQL is production security baseline.",
      "Dual endpoint public+private? — Transitional only — disable public after validation.",
      "Managed identity through PE? — Yes — `Authentication=Active Directory Default`.",
      "Private endpoint without DNS zone",
      "Public access still enabled prod",
      "Hardcode private IP in connection string"),
    q("Azure SQL Active Geo-Replication", "SQL", "Very Common",
      "Design active geo-replication for read scale and DR.",
      "Up to four readable secondaries in any region. Async replication — typical RPO ~5 seconds. Manual failover for DR; secondaries for read offload.",
      "**Read routing:** `ApplicationIntent=ReadOnly` in connection string with `Server=tcp:secondary.database.windows.net`.\n\n**Architect:** Secondary in paired region for DR; additional secondaries near users for read scale.\n\n**Limitations:** Same service tier family, no cross-tier. User tables replicate — some system objects differ.",
      "Geo-replication is async — plan for seconds of data loss on failover.",
      "Auto-failover groups vs geo-replication? — Failover groups add automatic endpoint management.",
      "Hyperscale geo? — Different model — named replicas.",
      "Assume RPO zero with geo-replication",
      "Write to secondary",
      "No read connection string separation"),
    q("Azure SQL Backup Retention", "SQL", "Common",
      "Backup retention strategy for compliance-heavy Azure SQL?",
      "PITR: 7–35 days default configurable. LTR (Long-Term Retention): weekly/monthly/yearly up to 10 years in blob storage.",
      "**Architect documents:**\n- PITR window for operational recovery (35 days typical prod)\n- LTR for regulatory (SOX 7 years)\n- Test restore quarterly to verify LTR\n\n**Geo-redundant backup storage:** ON for DR — backups survive region loss.\n\n**Hyperscale:** Continuous backup model — different restore semantics.",
      "Backup retention is compliance architecture not DBA checkbox.",
      "Restore time PITR? — Depends on size — communicate RTO in DR plan.",
      "Deleted database retention? — 7 days recoverable — extend awareness.",
      "Minimum 7-day PITR for prod financial",
      "LTR never tested restore",
      "Geo-redundant backup disabled"),
    q("Elastic Pool Sizing Strategy", "SQL", "Common",
      "Size an elastic pool for 500 tenant databases with variable load.",
      "Monitor aggregate DTU/vCore and per-DB peaks. Pool eDTU must exceed sum of average usage with headroom for uncorrelated peaks.",
      "**Signals:**\n- `elastic_pool_resource_stats` — pool utilization\n- Per-DB `avg_cpu_percent` — identify noisy neighbors\n\n**Architect:** Set per-database min/max eDTU caps — prevent one tenant consuming entire pool. Move hot tenant to standalone DB.\n\n**Alternative:** Hyperscale per tenant if one tenant exceeds pool economics.",
      "Elastic pools assume load diversity — correlated peaks breakupsize pool.",
      "Pool vs many singles cost? — Break-even ~20–30 small DBs — model with calculator.",
      "Zone redundancy pool? — Supported — add HA at pool level.",
      "Max eDTU per DB unlimited — one tenant starves others",
      "No per-DB cap configuration",
      "Never eject hot tenant from pool"),
    q("Cosmos DB Partition Key Deep Dive", "Cosmos DB", "Very Common",
      "A tenant has 10× traffic of others — partition key strategy?",
      "Synthetic partition key: `tenantId + bucket` where bucket = hash(userId) % N. Distributes mega-tenant across N logical partitions while keeping queries scoped.",
      "**Physical limit:** 20 GB and 10K RU/s per physical partition — hot tenant hits ceiling with `tenantId` alone.\n\n**Architect:** Monitor `PartitionKeyRangeId` metrics for skew. Dedicated container for mega-tenant if isolation required.\n\n**Hierarchical keys:** `/tenantId/orders` — preview feature for multi-level — know conceptually.",
      "Partition key mistakes are expensive to fix — requires container rebuild.",
      "Change partition key? — Live container migration feature — plan downtime/cost.",
      "GUID as partition key? — High cardinality but random — cross-partition queries on every read.",
      "Low cardinality status field as key",
      "Ignore 429 throttling on single partition",
      "No tenant size monitoring"),
    q("Cosmos DB Change Feed", "Cosmos DB", "Common",
      "Use Cosmos DB change feed for event-driven sync to Azure Search.",
      "Change feed processor reads ordered changes per partition. Push product updates to Azure AI Search indexer or custom worker.",
      "**Pattern:**\n1. Container with change feed enabled (default)\n2. Azure Function or Container Apps processor with lease container\n3. Idempotent upsert to Search index\n\n**Architect:** At-least-once delivery — handle duplicates. Lease container manages processor scale-out.\n\n**Alternative:** Synapse Link for analytics path; change feed for operational sync.",
      "Change feed is CDC for Cosmos — foundation for event-driven architecture.",
      "All versions and deletes? — Configure feed mode — know delete handling.",
      "Multiple processors? — Partition lease distribution — scale horizontally.",
      "Poll container manually for changes",
      "No idempotent downstream writes",
      "Single processor no lease container"),
    q("Azure AI Search Indexing Pipeline", "Search", "Common",
      "Design Azure AI Search index refresh from SQL and blob documents.",
      "Indexer pulls from SQL with high-watermark column or Cosmos change feed. Skillset for OCR (blob), language detection, enrichment. Schedule or push model.",
      "**Architect:**\n- Separate index per environment\n- Semantic ranker for relevance\n- Private endpoint for Search service prod\n\n**Scale:** Replicas for query QPS, partitions for index size >25 GB.",
      "Search indexing is part of polyglot persistence reference architecture.",
      "Push vs pull? — Indexer scheduled pull; push API for real-time from app events.",
      "Skillset cost? — Cognitive Services billing per document — batch wisely.",
      "Search without index partitioning plan",
      "Indexer full scan hourly on large table",
      "No soft delete handling in index"),
    q("Event Hubs Capture to Data Lake", "Streaming", "Common",
      "Configure Event Hubs Capture for raw event archival.",
      "Enable Capture on Event Hub — writes Avro files to Storage account or ADLS on time/size window (e.g., 5 min / 300 MB).",
      "**Downstream:** Spark/Synapse reads Avro for batch analytics. Stream Analytics separate path for real-time.\n\n**Architect:** Capture is fire-and-forget archive — consumers use separate consumer groups for live processing.\n\n**Retention:** Event Hubs retention (1–7 days) vs Capture ( indefinite cheap storage ).",
      "Capture decouples long-term storage from stream retention limits.",
      "Avro vs Parquet capture? — Event Hubs Capture is Avro; convert in Spark to Parquet.",
      "Capture storage account security? — Private endpoint, MI access from Synapse.",
      "Only 1-day retention no Capture — data loss for replay",
      "Same consumer group for analytics and live",
      "Capture to Hot tier forever without lifecycle"),
    q("Schema Migration Strategy Cloud", "DevOps", "Very Common",
      "Zero-downtime schema migration for Azure SQL in CI/CD?",
      "Expand-contract pattern: add nullable column (expand) → dual-write or backfill → switch reads → remove old (contract). Flyway/Liquibase/DbUp in pipeline with review gate.",
      "**Tools:** Flyway in Azure DevOps/GitHub Actions against staging slot DB. Use `-outOfOrder` carefully.\n\n**Architect:** Backward-compatible migrations only in release N; breaking changes in N+1 after code deployed.\n\n**Lock avoidance:** Online index rebuild, avoid table rewrites in peak hours.",
      "Cloud DB migrations require expand-contract not big-bang ALTER.",
      "Blue-green database? — Copy failover group secondary as test — advanced.",
      "Rollback? — Forward-only migrations with feature flags safer than down scripts prod.",
      "Breaking schema change same release as code",
      "Manual SSMS prod without script review",
      "Long-running migration without online option"),
    q("Connection Pooling in Cloud", "Performance", "Very Common",
      "Connection pooling best practices for Azure SQL with App Service?",
      "Enable pooling in ADO.NET (default). Right-size pool `Max Pool Size` — too high exhausts SQL `max_connections`. Use gateway/proxy (PgBouncer pattern) for serverless functions with many instances.",
      "**Azure specifics:**\n- **App Service:** pooling per instance — 10 instances × 100 pool = 1000 SQL connections\n- **Functions:** use `Microsoft.Data.SqlClient` pooling; consider Azure SQL serverless min vCores to avoid cold start + connection storm\n\n**Architect:** Monitor `connection_failed` and `blocked_process` metrics. Elastic pool many apps — aggregate connection math.",
      "Connection storms are common cloud outage cause.",
      "Disable pooling? — Almost never — latency and resource waste.",
      "SqlClient vs ODBC pool? — Per-process separate pools.",
      "Max Pool Size 500 on 20 App Service instances",
      "New connection per request in Functions",
      "No connection count monitoring"),
    q("Read Replica Routing Pattern", "SQL", "Common",
      "Implement read replica routing in .NET microservices.",
      "Primary connection string for writes. Secondary with `ApplicationIntent=ReadOnly` for reports. Or separate `IReadDbConnection` injected via DI.",
      "**Architect:**\n- Eventual consistency on replica — UI labels 'near real-time'\n- Retry on replica lag for critical read-after-write — read primary\n\n**Cosmos:** Session consistency gives read-your-writes without routing complexity.\n\n**Postgres Flexible:** Read replica FQDN separate — reader endpoint load balances.",
      "Explicit read/write split protects OLTP primary.",
      "EF Core read replica? — Interceptor or dual DbContext — no built-in auto routing.",
      "Replica for all reads including just-written order? — Bug — use primary or wait.",
      "Random round-robin to replica for writes",
      "Ignore replication lag in UX",
      "Single connection string for everything"),
    q("Azure SQL Geo-Restore", "DR", "Common",
      "Geo-restore vs failover group — when geo-restore?",
      "Geo-restore: restore DB from geo-redundant backup to any region — RPO up to 1 hour, RTO hours. Use region-wide outage when failover group not configured or full region loss.",
      "**Failover group:** Managed DR with seconds RPO. **Geo-restore:** Backup-based recovery last resort.\n\n**Architect DR runbook:**\n1. Attempt failover group automatic/manual\n2. If backup region intact, geo-restore to target region\n3. Update DNS/connection strings\n4. Communicate data loss window",
      "Geo-restore is safety net not primary DR strategy.",
      "Geo-restore Hyperscale? — Different — point-in-time restore within region first.",
      "Test geo-restore annually? — Required for compliance evidence.",
      "Geo-restore as only DR plan",
      "No runbook for connection string update",
      "Assume zero data loss geo-restore"),
    q("Transparent Data Encryption SQL", "Security", "Very Common",
      "Explain TDE for Azure SQL and customer-managed keys.",
      "TDE encrypts data at rest automatically — data files, backups, tempdb. Microsoft-managed keys default. CMK via Azure Key Vault for customer control and audit.",
      "**Architect:** Enable TDE on all prod databases (default on new). CMK when compliance mandates key ownership.\n\n**Ops:** Key Vault soft delete + purge protection mandatory with CMK. Key unavailable = database offline.\n\n**Double encryption:** Infrastructure encryption + TDE for defense in depth.",
      "TDE is baseline — interviewers want CMK trade-offs too.",
      "TDE performance impact? — Minimal on Azure SQL — hardware accelerated.",
      "Bring your own key (BYOK)? — CMK from HSM-backed Key Vault.",
      "CMK without Key Vault HA",
      "Assume TDE covers in-transit — need TLS too",
      "Disable TDE for performance myth"),
    q("Dynamic Data Masking", "Security", "Common",
      "Implement Dynamic Data Masking for support staff SQL access.",
      "DDM masks column values in query results — email shows `aXXX@XXXX.com`. Does not encrypt — users with UNMASK privilege see plain text.",
      "**Architect:** Layer defense — DDM for casual access, Always Encrypted for true protection, audit UNMASK grants.\n\n**Limitations:** Deterministic masking for joins; random for display-only. Not replacement for encryption.",
      "DDM reduces accidental exposure — not cryptographic control.",
      "Mask admin accounts? — Exclude with UNMASK only break-glass audited.",
      "DDM on API layer? — Database-level — apps using same DB user still masked.",
      "DDM instead of Always Encrypted for PCI",
      "Grant UNMASK broadly",
      "Masking without auditing privileged access"),
    q("Always Encrypted SQL", "Security", "Common",
      "When use Always Encrypted vs TDE?",
      "Always Encrypted: client-side encryption — DBA and cloud admin cannot read column values. TDE: at-rest only — DBAs see plain text in memory.",
      "**Use Always Encrypted for:** SSN, PCI PAN, highly sensitive PII.\n\n**Modes:** Deterministic (equality search) vs Randomized (max security, no search).\n\n**Architect:** Key in Key Vault or Windows Certificate Store. Column Master Key rotation plan. Performance overhead on encrypted columns.",
      "Always Encrypted protects against privileged insider and cloud operator.",
      "Enclave enabled? — Secure enclaves allow range queries on encrypted data — complexity trade-off.",
      ".NET integration? — `Column Encryption Setting=Enabled` in connection string.",
      "Always Encrypted for all columns — unnecessary overhead",
      "Store CMK in app config",
      "Randomized encryption then filter WHERE — fails"),
    q("Azure SQL Failover Groups", "SQL", "Very Common",
      "Design failover group for multi-region Azure SQL.",
      "Failover group: one primary, one secondary (or more readable), shared `failover-group-name.database.windows.net` listener. Automatic or manual failover, RPO ~5s.",
      "**Architect checklist:**\n- Same subscription recommended\n- App uses listener connection string\n- `MultipleActiveResultSets` and retry logic for transient faults\n- Graceful failover: planned maintenance\n\n**Readable secondaries:** Include in failover group — DR + read scale unified.",
      "Failover group simplifies DR connection management.",
      "Failover group elastic pool? — Pools must match region pairing strategy.",
      "Split-brain? — Azure prevents dual primary — listener follows primary.",
      "Hardcode regional server name not listener",
      "No application retry on 40613 errors",
      "Failover untested in production"),
    q("Cosmos DB RU Autoscale", "Cosmos DB", "Common",
      "Provisioned RU vs autoscale vs serverless for Cosmos?",
      "Provisioned: steady predictable load, cost at max RU. Autoscale: 10–100% of max RU, scales to zero floor at 10% max — variable workloads. Serverless: dev/test, sporadic traffic, no minimum.",
      "**Architect:** Start autoscale for unknown patterns — max RU = peak × 1.5. Move to provisioned when baseline stable for cost.\n\n**Monitor:** 429 rate, normalized RU consumption. Partition max 10K RU/s — autoscale per partition.",
      "RU model choice is primary Cosmos cost lever.",
      "Autoscale max RU change? — Can adjust — billing on highest max in hour.",
      "Serverless limits? — 1M RU/month free tier; not for sustained prod load.",
      "Provisioned 50K RU on idle dev database",
      "Ignore 429 throttling alerts",
      "Autoscale max set to peak without headroom"),
    q("Blob Immutability WORM", "Compliance", "Common",
      "Configure immutable blob storage for SEC 17a-4 compliance.",
      "Time-based retention policy on container — blobs cannot be deleted or overwritten until period expires. Legal hold for litigation.",
      "**Governance mode:** admins can extend retention. **Compliance mode:** no one shortens — including subscription owner.\n\n**Architect:** Separate storage account for audit logs. Versioning + immutability together. Document retention in compliance register.",
      "Immutability is regulatory architecture for WORM requirements.",
      "Immutable vs soft delete? — Complementary — immutability prevents overwrite; soft delete recovery window.",
      "Lifecycle delete conflict? — Lifecycle cannot delete before immutability expiry.",
      "Compliance mode without legal review",
      "Mutable audit log container",
      "No versioning with immutability"),
    q("ADLS ACLs vs RBAC", "Security", "Common",
      "When use POSIX ACLs vs RBAC on ADLS Gen2?",
      "RBAC: Entra ID groups, coarse-grained container/folder via `Storage Blob Data Contributor`. ACLs: fine-grained file/folder POSIX permissions, execute bit for folders.",
      "**Architect pattern:** RBAC for service principals and broad team access. ACLs when fine folder-level control needed (multi-tenant lake folders).\n\n**Best practice:** Enable `storage blob owner` RBAC + ACLs for default ACL inheritance on new files.\n\n**Avoid:** Shared keys — always OAuth/RBAC.",
      "ADLS security combines RBAC and ACLs — not either/or.",
      "Default ACL? — New files inherit — critical for Spark jobs.",
      "Access checker tool? — Validate effective permissions before prod cutover.",
      "RBAC alone on deeply nested multi-tenant paths",
      "Shared key in Databricks cluster",
      "ACL changes not in IaC"),
    q("Azure Data Share", "Governance", "Occasional",
      "Share dataset with partner without copying to their subscription?",
      "Azure Data Share: provider shares snapshot or in-place from Storage, SQL, Synapse. Consumer maps to their subscription — governed, monitored transfers.",
      "**Architect:** Prefer in-place share (provider pays egress rules apply) vs copy for freshness. Entra B2B guest for consumer access.\n\n**Alternative:** Event-driven export to their storage with SAS — less governance.",
      "Data Share is B2B data exchange pattern on Azure.",
      "Snapshot vs in-place? — Snapshot for point-in-time; in-place for live read with refresh triggers.",
      "Purview integration? — Register shared assets in catalog.",
      "Email CSV export to partner",
      "Full storage account key shared",
      "No data sharing agreement documented"),
    q("Microsoft Purview Data Map", "Governance", "Common",
      "Use Purview for data governance across Azure and on-prem.",
      "Purview scans sources (SQL, ADLS, Power BI), builds data map, classifies sensitive data, lineage graph. Unified catalog for discovery.",
      "**Architect:** Register collections per domain. Auto-classification for PII. Integrate with ADF/Synapse for lineage capture.\n\n**Ops:** Scheduled scans, glossary for business terms, access policies (preview features evolving).",
      "Purview is enterprise data catalog — not optional at scale.",
      "Scan scope? — Sample vs full — cost and time trade-off.",
      "On-prem SQL scan? — Self-hosted integration runtime.",
      "No catalog — analysts query unknown datasets",
      "Classification without owner assignment",
      "Scan prod without change window"),
    q("Lakehouse Medallion Architecture", "Analytics", "Very Common",
      "Explain bronze/silver/gold medallion layers on ADLS.",
      "Bronze: raw ingest, schema-on-read, append-only. Silver: cleansed, deduplicated, conformed. Gold: business aggregates, star schema, BI-ready.",
      "**Architect:**\n- Delta/Iceberg on ADLS for ACID silver/gold\n- Separate Spark jobs per layer\n- Data quality checks at bronze→silver gate\n\n**Ownership:** Domain teams own gold; platform team owns bronze ingestion standards.",
      "Medallion is standard lakehouse pattern interviewers expect.",
      "One big folder? — Anti-pattern — layer separation enables reprocessing.",
      "Real-time gold? — Streaming silver → materialized gold via Spark Structured Streaming.",
      "Skip silver — dirty data in reports",
      "No idempotent bronze ingestion",
      "Gold tables writable by analysts"),
    q("Synapse Spark Pool Configuration", "Analytics", "Common",
      "Size and configure Synapse Spark pool for daily ETL.",
      "Node size (Small to XXLarge), auto-scale min/max nodes, auto-pause idle minutes. Spark 3.x with Delta Lake libraries.",
      "**Architect:**\n- Separate pools dev (small, short pause) vs prod (right-sized, longer pause delay)\n- Managed VNet for private data access\n- Pool packages for dependency consistency\n\n**Cost:** Auto-pause after 15 min idle. Spot/Low priority nodes where fault-tolerant.",
      "Spark pool sizing affects ETL window and bill directly.",
      "Dynamic allocation? — Enable for variable partition workloads.",
      "Synapse vs Databricks? — Know both — Synapse unified workspace; Databricks broader ecosystem.",
      "XXLarge pool for 1 GB daily job",
      "No auto-pause — pool runs 24/7",
      "Libraries installed ad hoc not pool package"),
    q("PolyBase in Synapse", "Analytics", "Occasional",
      "Use PolyBase to query external data in Synapse dedicated pool.",
      "PolyBase creates external tables over ADLS/Blob/SQL ODBC sources. Query Data Lake with T-SQL without loading into warehouse.",
      "**Architect:** External tables for exploratory queries; CETAS to materialize hot paths into internal tables.\n\n**Serverless SQL:** Preferred for ad-hoc external queries — dedicated pool PolyBase for integrated DW workloads.\n\n**Format:** Parquet/ORC/Delta supported — CSV for small only.",
      "PolyBase bridges relational SQL and data lake.",
      "Statistics on external tables? — Create for cardinality estimates — performance.",
      "Credential security? — DATABASE SCOPED CREDENTIAL with MI or SAS in Key Vault.",
      "Load entire lake into DW unnecessarily",
      "External table on tiny CSV forever",
      "SAS key in credential plaintext"),
    q("Azure Stream Analytics", "Streaming", "Common",
      "Design Stream Analytics job from Event Hubs to Power BI.",
      "Input Event Hub, query with SQL-like language (windowing, JOIN reference data), output Power BI push dataset or ADLS for archive.",
      "**Patterns:**\n- Tumbling window aggregations (5-min counts)\n- Reference data blob for dimension enrichment\n- Multiple outputs — alert stream + archive\n\n**Architect:** Scale SU for throughput. Handle late events with watermark policy.",
      "Stream Analytics is managed stream processing without Spark ops.",
      "ASA vs Spark Streaming? — ASA simpler SQL; Spark for complex ML/transform.",
      "Exactly-once? — At-least-once default — idempotent sinks.",
      "Unbounded window on high volume",
      "No reference data version strategy",
      "Single SU production peak traffic"),
    q("Azure Time Series Insights", "IoT", "Occasional",
      "Time Series Insights vs storing IoT telemetry in Cosmos/SQL?",
      "TSI (legacy/evolving to Data Explorer): optimized time-series storage, downsampling, trend analysis. Cosmos/SQL: operational state, alerts, not long-term analytics at scale.",
      "**Modern path:** IoT Hub → Event Hubs → ADX (Azure Data Explorer) for time-series analytics; TSI Gen2 migrated toward ADX.\n\n**Architect:** Hot path operational in SQL/Cosmos; warm/cold analytics in ADX with retention policies.",
      "Know TSI evolution to ADX for interviews.",
      "ADX vs Synapse? — ADX sub-second analytics on append-only telemetry; Synapse batch/BI.",
      "Retention tiering ADX? — Cache vs extend vs archive.",
      "SQL for billion-row telemetry",
      "No downsampling on 1-second sensor data",
      "Ignore TSI migration guidance"),
    q("Azure Database for MySQL Flexible", "Databases", "Common",
      "Choose Azure Database for MySQL Flexible Server for WordPress scale-out.",
      "Flexible Server: zone HA, read replicas, burstable/GP/MO tiers, VNet integration. Better than Single Server (retired).",
      "**Architect:** Read replicas for read-heavy WordPress; Premium storage IO for plugin-heavy DB. Connection pooling via ProxySQL sidecar if needed.\n\n**Migration:** Azure Database Migration Service from on-prem or Single Server.",
      "MySQL Flexible is standard Azure MySQL offering.",
      "MariaDB vs MySQL? — Separate Azure service — see selection criteria.",
      "Private Link MySQL? — Supported Flexible — disable public.",
      "Single Server new deployment",
      "No read replica for viral traffic",
      "max_connections default without pooling"),
    q("MariaDB vs MySQL on Azure", "Databases", "Occasional",
      "Azure Database for MariaDB vs MySQL — selection?",
      "MariaDB Flexible Server mirrors MySQL Flexible capabilities. Choose based on app compatibility (MariaDB fork features vs Oracle MySQL 8).",
      "**MySQL when:** Oracle MySQL 8 features, InnoDB cluster compatibility. **MariaDB when:** existing MariaDB app, specific MariaDB extensions.\n\n**Architect:** Standardize one engine org-wide unless legacy requires MariaDB. Both support HA, replicas, VNet.",
      "Engine choice is compatibility not performance religion.",
      "Cross-migrate? — Dump/restore or DMS — test charset/collation.",
      "Azure MariaDB Single Server? — Retired — Flexible only.",
      "Pick MariaDB without app requirement",
      "Ignore version EOL schedule",
      "Wrong collation migration failure"),
    q("Data Encryption at Rest Azure", "Security", "Very Common",
      "Map encryption at rest across Azure data services.",
      "Storage: SSE with Microsoft or CMK. SQL: TDE. Cosmos: service-managed keys or CMK. ADLS: same as storage. Disks: SSE.",
      "**Architect defense in depth:**\n1. Platform encryption (default on)\n2. CMK for regulated workloads\n3. Client-side (Always Encrypted, app-level) for highest sensitivity\n\n**Compliance:** Document key hierarchy in security architecture.",
      "Encryption at rest is table stakes — CMK is the architect decision.",
      "Infrastructure encryption storage? — Extra AES layer on hardware.",
      "Cosmos CMK? — Account level Key Vault key.",
      "Assume default encryption satisfies all regulators without CMK review",
      "Keys and data same Key Vault no separation",
      "No encryption in transit complement"),
    q("SQL Key Rotation with CMK", "Security", "Common",
      "Rotate customer-managed TDE key without database outage?",
      "Add new Key Vault key version; alter database encryption key to rewrap with new version. Azure SQL online reencryption — minimal impact.",
      "**Architect runbook:**\n1. Create new KV key version (or rotation policy auto)\n2. `ALTER DATABASE ENCRYPTION KEY` or portal rotate\n3. Verify `sys.dm_database_encryption_keys`\n4. Audit Key Vault logs\n\n**Avoid:** Disabling purge protection; deleting old key version before rewrap complete.",
      "Key rotation proves crypto governance maturity.",
      "Automatic rotation Key Vault? — 90-day policy + SQL manual rewrap or automation runbook.",
      "TDE protector vs column CMK? — Separate rotation schedules.",
      "Delete old key version immediately",
      "CMK rotation untested in staging",
      "No alert on Key Vault access failure"),
    q("SQL Data Classification", "Governance", "Common",
      "Implement data discovery and classification in Azure SQL.",
      "Built-in SQL Data Discovery & Classification scans columns, recommends labels (PII, financial). Integrates with Purview for enterprise catalog.",
      "**Architect workflow:**\n1. Enable classification scan\n2. Review recommendations, apply labels\n3. Export report for compliance\n4. Feed Purview for lineage + policies\n\n**Combine with:** DDM, Always Encrypted, audit sensitive column access.",
      "Classification drives protection tier decisions.",
      "Auto-labeling sensitivity? — Information Protection integration for MIP labels.",
      "Classification in CI? — Fail build if unlabeled columns in prod schema — advanced governance.",
      "Manual spreadsheet of PII columns",
      "Classification without remediation plan",
      "Ignore recommendations quarterly"),
]
