"""Hand-crafted premium Q001–Q010 for Week 2 — .NET Runtime & Ecosystem."""

from premium_qa_data import q

WEEK_2 = [
    q("CLR and Managed Runtime", ".NET Runtime", "Very Common",
      "What is the CLR's role in a .NET architecture?",
      "CLR loads assemblies, JIT-compiles IL to native code, manages GC, enforces type safety, handles exceptions. Architects care about GC behavior, assembly loading, and runtime version pinning.",
      "**Hosting:** .NET 8 unified runtime — LTS for production APIs.\n\n**Architect decisions:** Pin runtime in container images; test GC settings for high-RPS services; understand assembly load contexts for plugin architectures.\n\n**Production:** `DOTNET_gcServer=1` default on ASP.NET — verify workstation GC not forced.",
      "Runtime knowledge separates senior .NET architects.",
      "ReadyToRun vs JIT? — Faster startup; larger binaries — containers benefit.",
      "Native AOT? — No JIT; constraints on reflection — microservices edge cases.",
      "Mixing .NET Framework and .NET 8 without boundary",
      "Ignore runtime patch cadence in LTS planning",
      "Plugin load without AssemblyLoadContext isolation"),
    q("Hosting Models Compared", "Hosting", "Very Common",
      "Compare Kestrel+IIS, Kestrel-only, and container hosting for .NET APIs.",
      "Kestrel is the actual server. IIS acts as reverse proxy on Windows. Containers: Kestrel behind ingress/ALB — preferred for cloud-native.",
      "**Cloud default:** Linux container + Kestrel + Kubernetes/App Service/ECS.\n\n**IIS:** Legacy Windows deployments, Windows Auth integration.\n\n**Architect:** Kestrel at edge only behind reverse proxy in production — not exposed directly without hardening.",
      "Hosting choice affects deploy pipeline and scaling.",
      "YARP reverse proxy? — Replace IIS ARR for .NET-native proxy.",
      "HTTP.sys vs Kestrel? — HTTP.sys Windows-specific niche.",
      "Expose Kestrel directly to internet without proxy",
      "Windows containers without cost analysis",
      "IIS and Kestrel misconfigured request limits"),
    q("Dependency Injection Lifetimes", "DI", "Very Common",
      "Explain Singleton, Scoped, Transient — and the captive dependency bug.",
      "Singleton: one instance app lifetime. Scoped: per request/scope. Transient: new each resolve. Never inject Scoped into Singleton.",
      "**Captive dependency:** `Singleton<Cache>` holding `Scoped<DbContext>` — DbContext never disposed per request.\n\n**Fix:** Make cache Scoped, or use `IServiceScopeFactory` in singleton.\n\n**Architect:** Document lifetime rules in coding standards; Roslyn analyzer or review checklist.",
      "DI lifetime bugs cause production data corruption.",
      "ValidateOnBuild / ValidateScopes? — Enable in Development to catch early.",
      "Keyed services .NET 8? — Multiple implementations same interface.",
      "Singleton wrapping DbContext",
      "Transient for heavy objects in tight loop",
      "No scope in background service"),
    q("Configuration and Options Pattern", "Configuration", "Common",
      "How structure configuration in 12-factor .NET apps?",
      "Hierarchy: appsettings.json → environment override → environment variables → Key Vault/secrets. `IOptions<T>` with validation at startup.",
      "```csharp\nservices.AddOptions<PaymentOptions>()\n    .BindConfiguration(\"Payment\")\n    .ValidateDataAnnotations()\n    .ValidateOnStart();\n```\n\n**Architect:** Fail fast on misconfiguration; no secret files in repo; reload carefully for non-secret options only.",
      "Configuration errors should crash at startup not runtime.",
      "IOptions vs IOptionsSnapshot vs IOptionsMonitor? — Scoped vs singleton reload needs.",
      "Azure App Configuration? — Feature flags + centralized config.",
      "Secrets in appsettings.Production.json committed",
      "No validation on connection strings",
      "Hot reload secrets unsafely"),
    q("Minimal APIs vs Controllers", "API Design", "Common",
      "When Minimal APIs vs MVC Controllers in enterprise?",
      "Minimal APIs: microservices, simple endpoints, AOT-friendly. Controllers: complex conventions, filters, large teams familiar with MVC patterns.",
      "**Enterprise:** Controllers still common in large codebases — consistency matters.\n\n**Minimal:** Gateway BFFs, internal tools, serverless functions style.\n\n**Architect:** Pick per service; don't mix arbitrarily within one bounded context.",
      "API style is team consistency decision.",
      "Endpoint filters vs action filters? — Minimal API has endpoint filters .NET 7+.",
      "OpenAPI generation both? — Swashbuckle works with both.",
      "Minimal APIs everywhere without structure",
      "Controllers for 2-line health check only",
      "No versioning strategy either style"),
    q("gRPC vs REST", "API Design", "Common",
      "When gRPC vs REST for internal service communication?",
      "gRPC: internal east-west, high performance, streaming, contract-first protobuf. REST: public APIs, browser clients, human debugging with curl.",
      "**.NET:** First-class gRPC with HTTP/2. Needs load balancer HTTP/2 support.\n\n**Architect:** REST/JSON at edge (BFF); gRPC inside mesh between services.\n\n**Tooling:** Contract versioning critical — backward compatible field adds.",
      "Protocol choice affects gateway and observability.",
      "gRPC-Web? — Browser clients through proxy.",
      "Json transcoding? — gRPC exposed as REST for transition.",
      "gRPC public without gateway hardening",
      "Breaking proto changes without versioning",
      "REST between every internal hop at scale"),
    q(".NET Versioning and LTS Strategy", "Strategy", "Common",
      "Enterprise policy for .NET version adoption?",
      "Adopt LTS (even years) for production within 6 months of release. STS for tooling only. Pin SDK in global.json; container base images on LTS.",
      "**.NET 8 LTS** until Nov 2026 — standard for new services.\n\n**Architect:** Central template repo; automated Dependabot for patch; major upgrade wave planned quarterly.",
      "Version strategy prevents security and support debt.",
      ".NET Framework 4.8 extended support? — Legacy isolation plan required.",
      "Central Package Management? — Consistent versions across solution.",
      "STS in production without upgrade plan",
      "Mixed .NET versions uncontrolled per repo",
      "No global.json — SDK drift in CI"),
    q("Assembly Versioning and Breaking Changes", "Packaging", "Occasional",
      "SemVer for internal NuGet packages — architect rules?",
      "Major: breaking API. Minor: backward compatible features. Patch: fixes. Consumers pin major; CI detects breaking changes.",
      "**Architect:**\n- API compatibility checks (Microsoft.CodeAnalysis.PublicApiAnalyzers)\n- Single internal feed\n- Document deprecation cycle (2 minors before remove)\n\n**Avoid:** Shared kernel NuGet becoming god package.",
      "Package graph affects build and deploy coupling.",
      "Source linking vs NuGet for shared code? — Prefer project reference in monorepo.",
      "MinVer vs Nerdbank.GitVersioning? — Automate semver from git.",
      "Breaking change without major bump",
      "Shared library with domain logic for all teams",
      "No deprecation notices"),
    q("Health Checks Architecture", "Observability", "Common",
      "Design health endpoints for Kubernetes/App Service?",
      "Liveness: process up. Readiness: can serve traffic (DB reachable). Startup: slow initialization. Don't include external deps in liveness.",
      "```csharp\nbuilder.Services.AddHealthChecks()\n    .AddSqlServer(conn)\n    .AddRedis(redis);\n```\n\n**Architect:** Readiness fails remove from load balancer; liveness fail restarts pod — wrong check causes restart storm.",
      "Health check design prevents cascading failures.",
      "Health Checks UI? — Dev only — not expose prod details publicly.",
      "Tags for checks? — `ready` vs `live` endpoints separate.",
      "HTTP call to payment provider in liveness",
      "Single /health does everything",
      "Detailed exception stack in health response"),
    q("Worker Services vs Web Apps", "Hosting", "Common",
      "When `Worker Service` template vs ASP.NET Core for background work?",
      "Worker Service: queue consumers, scheduled jobs, long-running hosts without HTTP. Web + hosted service: light background in same process as API — caution scaling.",
      "**Architect:** Separate worker deployment when CPU/memory profile differs from API — independent scale.\n\n**Patterns:** Generic Host, `BackgroundService`, cancellation on shutdown.\n\n**Avoid:** Heavy processing in API process — competes with request threads.",
      "Process boundary is scaling boundary.",
      "IHostedService vs Worker template? — Worker is template with DI defaults.",
      "Azure WebJobs vs separate Worker? — WebJobs coupled to App Service.",
      "Scale API replicas to process queue backlog",
      "No graceful shutdown on worker",
      "Ignore duplicate message processing"),
]
