"""Hand-crafted premium Q011–Q030 for Week 1 fundamentals."""

from premium_qa_data import q

WEEK1_FUNDAMENTALS_Q011_Q030 = [
    q("is vs as vs Pattern Matching", "C# Type System", "Common",
      "Compare `is`, `as`, and pattern matching. When use each?",
      "`is` checks type; modern `is` with pattern declares variable. `as` safe cast returns null. Pattern matching (`is Order o`) preferred for clarity and exhaustiveness.",
      "**Modern style:**\n```csharp\nif (payment is CardPayment card) { ... }\n```\n\n**`as`:** legacy nullable cast — `var o = obj as Order; if (o != null)` — more verbose.\n\n**Switch expressions:** exhaustiveness checking with compiler warnings on missing cases — architect mandates for status/state machines in domain.\n\n**Architect:** Prefer pattern matching in code review standards — reduces null reference bugs and improves readability in complex business rules.",
      "Language feature choice affects maintainability at scale.",
      "Can pattern matching replace Visitor? — Simple hierarchies yes; double-dispatch Visitor still valid for complex open hierarchies.",
      "Switch expression exhaustiveness? — Compiler warns on missing enum cases — enable warnings as errors.",
      "Using `as` when `is` pattern is clearer",
      "No exhaustiveness on business state switches",
      "Cast without null check after `as`"),
    q("Covariance and Contravariance", "C# Generics", "Common",
      "Explain covariance and contravariance with examples.",
      "Covariance (`out`): return more derived — `IEnumerable<string>` → `IEnumerable<object>`. Contravariance (`in`): accept more base — `Action<object>` → `Action<string>`.",
      "**Design interfaces:** `IProducer<out T>`, `IConsumer<in T>`. Critical when designing shared libraries and LINQ-style APIs.\n\n**IEnumerable<T> covariant** — enables passing `List<string>` where `IEnumerable<object>` expected (read-only producer).\n\n**Action/Func contravariance** — callback parameters.\n\n**Architect:** Misuse causes compile errors in generic APIs — document variance on shared abstractions.",
      "Generics variance matters for framework design.",
      "Why not covariant List<T>? — List allows Add — would break type safety.",
      "Immutable collections variance? — IReadOnlyList covariant for reads.",
      "Mutable covariant interfaces",
      "Confusing in/out keywords meaning",
      "Variance bugs in public SDK design"),
    q("delegate vs Func vs Action", "C# Delegates", "Common",
      "Difference between delegate, Func, and Action?",
      "Delegate is the type concept. `Func<T, TResult>` returns value. `Action<T>` returns void. Both are built-in generic delegate types.",
      "**When custom delegate:** semantic name matters (`EventHandler`, domain-specific).\n\n**Architect preference:** inject interfaces (`IPaymentProcessor`) not `Func<Payment, bool>` in public APIs — clearer contracts, easier testing, stable surface.\n\n**Func acceptable:** internal LINQ-style utilities, local lambdas, fluent configuration.",
      "API design clarity over delegate brevity.",
      "Multicast delegates? — `+=` combines — events use this — know removal with `-=`.",
      "Expression trees vs delegates? — LINQ to SQL uses expressions — different runtime.",
      "Public API exposes Func everywhere",
      "Custom delegate for every one-liner",
      "Confuse delegate with interface role"),
    q("Properties vs Fields", "C# OOP", "Common",
      "When use auto-properties vs fields?",
      "Public API: always properties — fields should be private. Auto-properties for simple data; full properties when validation/side effects needed.",
      "**Encapsulation:** fields don't version well — adding logic later breaks binary compatibility if public field.\n\n**Performance:** properties compile to methods — negligible; don't use public fields for micro-optimization.\n\n**Architect:** `init` accessors for immutable DTOs; private set for controlled mutation on entities.",
      "Encapsulation standard enforced in coding guidelines.",
      "Field-like properties C#? — `{ get; field; }` — rare explicit backing field access.",
      "Required properties C# 11? — Constructor must set — API contract enforcement.",
      "Public fields on domain entities",
      "Property logic in getter with DB call",
      "Mutable static public fields"),
    q("static Classes and Members", "C# OOP", "Common",
      "When are static members appropriate in enterprise .NET?",
      "Stateless utilities (`Guid.NewGuid` wrappers), extension method containers, factory registries, well-known singletons (careful).",
      "**Avoid:** static mutable state — untestable, hidden dependencies, thread-safety bugs.\n\n**Architect red flag:** `static HttpClient` or `static DbContext` — use DI singleton lifetime correctly instead.\n\n**Good:** `static` extension methods in `Microsoft.Extensions` style.",
      "Static state is hidden coupling architects eliminate.",
      "Static local functions? — Encapsulate helper in method — good practice.",
      "Generic static classes? — `static class Cache<T>` — per-T static state — thread-safe?",
      "Static mutable Dictionary cache unbounded",
      "Static service locator anti-pattern",
      "Test impossible due to static state"),
    q("GC Generations Deep Dive", "GC", "Very Common",
      "Explain Gen 0, 1, 2, and LOH. Architect impact?",
      "Gen 0: short-lived (temp objects). Gen 1: buffer. Gen 2: long-lived. LOH: ≥85KB objects, collected with Gen 2, compaction limited historically.",
      "**Architect monitors:** `% Time in GC`, Gen 2 collection frequency, LOH size.\n\n**High RPS APIs:** reduce allocations in hot path — pooling, structs, `ArrayPool<byte>`, avoid string concat in loops.\n\n**Server GC:** default for ASP.NET — throughput optimized.",
      "GC behavior drives latency SLOs.",
      "POH pinned heap? — Long-lived pinned objects — separate heap .NET 5+.",
      "GC.TryStartNoGCRegion? — Ultra-low latency short windows — expert use.",
      "Ignore GC metrics in production",
      "LOH allocations per request in hot path",
      "Assume workstation GC for server API"),
    q("Finalizers and Why to Avoid", "GC", "Common",
      "Why avoid finalizers in .NET application code?",
      "Finalizers run on finalizer thread unpredictably, delay GC, promote objects to Gen 2, non-deterministic cleanup.",
      "**Use `IDisposable`/`IAsyncDisposable`/`using`** explicitly.\n\n**SafeDisposable pattern** with `GC.SuppressFinalize` if finalizer exists for native handle safety net.\n\n**Architect:** Code analyzers flag finalizers — ban in application code except interop wrappers.",
      "Deterministic disposal is architect standard.",
      "SafeHandle? — Preferred for native resources — finalizer on SafeHandle only.",
      "Using statement async? — `await using` for IAsyncDisposable.",
      "Rely on finalizer for SqlConnection cleanup",
      "Empty finalizer adding GC pressure",
      "No Dispose pattern on unmanaged wrapper"),
    q("Weak References", "Memory", "Occasional",
      "Use case for WeakReference in application architecture?",
      "Large object caches where GC can reclaim under memory pressure — image cache, metadata cache. `ConditionalWeakTable` for attaching data without preventing collection.",
      "**Not** for primary business logic storage — unpredictable disappearance.\n\n**Architect:** prefer explicit cache eviction (LRU, TTL) over weak refs unless memory-sensitive client app.",
      "Weak refs are specialized — know when not to use.",
      "WeakReference<T> vs GCHandle? — GCHandle pinned — different purpose.",
      "MemoryCache with size limit vs weak ref? — Prefer MemoryCache with policies in server apps.",
      "Business data only in weak reference",
      "Expect weak ref object always available",
      "No fallback when weak ref collected"),
    q("stackalloc and When to Use", "Performance", "Common",
      "When is `stackalloc` appropriate?",
      "Small buffers on stack avoiding heap allocation — parsing, crypto, short-lived span operations. Keep size small (typically <1KB) to avoid stack overflow.",
      "```csharp\nSpan<byte> buffer = stackalloc byte[256];\n```\n\n**With `Span<T>`:** safe scoped lifetime.\n\n**Architect:** profile before micro-optimizing — clarity first unless hot path proven.",
      "stackalloc is performance tool with bounds.",
      "stackalloc in loop? — Dangerous — large total stack — allocate outside loop.",
      "ArrayPool vs stackalloc? — Larger buffers — ArrayPool shared heap.",
      "Large stackalloc per request",
      "stackalloc without Span safety",
      "Premature stackalloc without profiling"),
    q("Memory<T> vs Span<T>", "Performance", "Common",
      "Difference between Memory<T> and Span<T>?",
      "`Span<T>` stack-only ref struct — cannot be field on async class. `Memory<T>` heap-friendly — use in async methods and instance fields.",
      "**Rule:** `Span` in synchronous hot path; `Memory` when stored or crossed `await`.\n\n**Architect:** enable `Span` usage in parsing libraries; team training required — ref struct constraints.",
      "Memory/Span literacy for high-performance .NET.",
      "ReadOnlySpan<char> for strings? — Zero-copy slicing without Substring allocation.",
      "MemoryMarshal? — Advanced interop — architect review required.",
      "Span as class field",
      "async method using Span parameter incorrectly",
      "Substring in tight loop instead of span slice"),
    q("ConfigureAwait(false) — Still Needed?", "Async", "Common",
      "Is ConfigureAwait(false) still needed in ASP.NET Core?",
      "ASP.NET Core has no `SynchronizationContext` capture issue — `ConfigureAwait(false)` rarely needed in app code. Still recommended in library code for reuse outside ASP.NET.",
      "**Library authors:** use `ConfigureAwait(false)` always.\n\n**Application code:** optional in ASP.NET Core; still valid in UI (WPF/WinForms) and legacy ASP.NET.\n\n**Architect:** coding standard per project type — document in guidelines.",
      "Async context knowledge shows .NET depth.",
      "SynchronizationContext what? — Posts continuation to UI thread — ASP.NET Core removed this.",
      "Library used in UI and ASP.NET? — ConfigureAwait(false) in library mandatory.",
      "ConfigureAwait(false) everywhere blindly in ASP.NET",
      "Missing ConfigureAwait in shared library",
      "async void event handlers without care"),
    q("Task vs ValueTask", "Async", "Common",
      "When use ValueTask instead of Task?",
      "ValueTask when operation often completes synchronously — cache hit, buffered read. Reduces Task allocation on hot paths.",
      "**Caution:** ValueTask can only be awaited once — don't cache and reuse multiple times unless converted to Task.\n\n**Architect:** EF Core and ASP.NET internals use ValueTask — application code only after profiling shows Task allocation cost.",
      "ValueTask is optimization — not default.",
      "ValueTask.FromResult? — Sync completion path.",
      "IValueTaskSource? — Advanced pooling — framework level.",
      "ValueTask everywhere by default",
      "Double-await ValueTask",
      "ValueTask without understanding constraints"),
    q("CancellationToken Patterns", "Async", "Common",
      "How propagate and honor cancellation in ASP.NET APIs?",
      "Accept `CancellationToken` on all async endpoints — ASP.NET passes aborted request token. Pass to EF, HttpClient, `Task.Delay`.",
      "**Cooperative cancellation** — check `token.ThrowIfCancellationRequested()` in long loops.\n\n**Architect:** global timeout policies via middleware; linked tokens for shutdown + request cancel.\n\n**Graceful shutdown:** `IHostApplicationLifetime` linked token stops background work.",
      "Cancellation is production reliability requirement.",
      "CancellationToken.None? — Explicit when intentionally ignoring — document why.",
      "LinkedTokenSource? — Combine shutdown + user cancel.",
      "Ignore CancellationToken parameter",
      "Long loop without cancellation check",
      "Kill thread instead of cooperative cancel"),
    q("IAsyncEnumerable Use Cases", "Async", "Common",
      "When use IAsyncEnumerable<T>?",
      "Stream large datasets without loading all into memory — CSV export, DB forward-only read, SignalR streaming, gRPC streaming.",
      "```csharp\nawait foreach (var row in QueryAsync(token)) { ... }\n```\n\n**Architect:** API returns `IAsyncEnumerable` for million-row exports instead of `List<T>`.",
      "Streaming patterns prevent OOM on large data.",
      "EF Core AsAsyncEnumerable? — Stream query results.",
      "Channel vs IAsyncEnumerable? — Producer-consumer — different patterns.",
      "ToListAsync on million rows",
      "No cancellation in async enumeration",
      "Buffer entire export in memory"),
    q("Deadlock Scenarios in Async", "Async", "Very Common",
      "Classic async deadlock in .NET — cause and fix?",
      "`.Result` or `.Wait()` on async method blocks thread while async continuation needs same thread (UI/legacy ASP.NET context). Fix: async all the way.",
      "**ASP.NET Core:** less common but thread pool starvation similar symptom from sync-over-async.\n\n**Architect:** analyzers ban `.Result`/`.Wait()` in web projects. Code review gate.",
      "Deadlock prevention is architect coding standard.",
      "GetAwaiter().GetResult()? — Same problem — don't.",
      "Task.Run wrap sync-over-async? — Extra thread — band-aid not fix.",
      ".Result in controller action",
      "Blocking async database call",
      "sync-over-async in library consumed by web app"),
    q("Source Generators", "Modern C#", "Occasional",
      "When adopt source generators in enterprise?",
      "Repeatable boilerplate: mapping, DI registration, regex, serialization context. Worth at platform scale with team to maintain generators.",
      "**Examples:** Mapperly, System.Text.Json source gen, compile-time DI scanners.\n\n**Trade-off:** build time, debugging complexity.\n\n**Architect:** approve generator use in platform templates — not one-off per developer.",
      "Generators are platform decision.",
      "Incremental generators? — Faster builds large solutions.",
      "Analyzer vs generator? — Analyzer reports; generator emits code.",
      "Generator for one mapping class",
      "No team knowledge to maintain generator",
      "Build time regression ignored"),
    q("required Members (C# 11)", "Modern C#", "Common",
      "What do `required` properties provide?",
      "Compiler enforces object initializer or constructor sets required members — compile-time guarantee non-null initialization.",
      "```csharp\npublic required string OrderId { get; init; }\n```\n\n**With NRT:** stronger API contracts without runtime validation only.\n\n**Architect:** adopt on DTOs and commands in new projects.",
      "Compile-time contracts reduce runtime validation gaps.",
      "required vs constructor? — required works with init and object initializers.",
      "JSON deserialization required? — System.Text.Json respects required.",
      "Constructor validation only without required",
      "required on optional fields incorrectly",
      "Mixing required with nullable confusion"),
    q("Primary Constructors Trade-offs", "Modern C#", "Common",
      "C# 12 primary constructors — benefits and risks?",
      "Less boilerplate capturing constructor parameters as fields. Good for small services, records, DI-injected dependencies.",
      "**Risk:** too much logic in primary constructor; entity classes become unclear.\n\n**Architect:** allow for services/DTOs; discourage for rich domain entities with behavior.",
      "Modern syntax with discipline.",
      "Primary constructors on records? — Natural fit.",
      "Validation in primary constructor? — Keep minimal — use factory or validator.",
      "God constructor logic",
      "Primary constructor on EF entity with complex rules",
      "Every class uses primary constructor without review"),
    q("Global Usings", "Modern C#", "Common",
      "Project-wide global usings — architect guidance?",
      "`GlobalUsings.cs` for common namespaces (`System`, `Microsoft.Extensions.Logging`) — reduces noise. Don't global-using domain-specific namespaces — hides dependencies.",
      "**Architect:** shared `Directory.Build.props` global usings for org-wide consistency.\n\n**Review:** implicit usings enabled on new SDK projects — understand what's imported.",
      "Usings affect code clarity and dependency visibility.",
      "Implicit usings disable? — Explicit control legacy migration.",
      "Global using alias? — Rare — document if used.",
      "Global using hides ambiguous types",
      "Every namespace global — unclear file dependencies",
      "Conflict between global usings unresolved"),
    q("File-Scoped Namespaces", "Modern C#", "Common",
      "Benefit of file-scoped namespaces?",
      "One less indentation level — entire file in namespace. C# 10+ standard for new code.",
      "```csharp\nnamespace MyApp.Orders;\n\npublic class Order { }\n```\n\n**Architect:** mandate in `.editorconfig` for new files — consistent style across 50 developers.",
      "Small syntax improvement compounds at scale.",
      "Block namespace migration? — Mechanical find-replace safe.",
      "File-scoped and top-level statements? — Program.cs patterns.",
      "Mixed styles in same solution",
      "Block namespace in new files only",
      "Nested namespace file-scoped incorrectly"),
]
