"""Hand-crafted premium Q011–Q050 for Azure weeks 15–16 (messaging + capstone)."""

from premium_qa_data import q

WEEK_15_Q011_Q050 = [
    q("Service Bus Queues", "Service Bus", "Very Common",
      "When do you choose a Service Bus queue over a topic, and how do you design for competing consumers?",
      "Use a queue for point-to-point work distribution — one logical consumer pool processes each message once. Topics fan out to multiple independent subscribers.",
      "**Queue pattern:** order-fulfillment queue with 5 worker instances using peek-lock receive — each message handled by exactly one consumer.\n\n**Design:** Enable duplicate detection on business key, set max delivery count (e.g. 10) before DLQ, use sessions only when ordering per entity is required.\n\n**Architect:** Queue = command/work item. Topic = domain event broadcast. Don't use queue when inventory, billing, and analytics all need the same event.",
      "Queue vs topic is the first Service Bus design fork — interviewers probe whether you understand competing consumers vs pub/sub.",
      "Queue vs Storage Queue? — Service Bus for enterprise messaging (sessions, transactions, DLQ); Storage Queue for simple high-volume at lowest cost.",
      "How scale consumers? — Add competing receivers on same queue; partition with sessions if order per key matters.",
      "Using queue when multiple services need same event",
      "Receive-delete without idempotent handler",
      "No max delivery count configured"),
    q("Service Bus Topics and Subscriptions", "Service Bus", "Very Common",
      "Design a Service Bus topic for OrderPlaced with three subscribers — what subscription filters and rules apply?",
      "One topic `order-events`; subscriptions: `inventory-svc` (filter: eventType=OrderPlaced), `notification-svc`, `analytics-svc`. Each subscription is independent with own DLQ.",
      "**Topic:** publisher sends once; N subscriptions receive independently.\n\n**Filters:** SQL filters or correlation filters on `eventType`, `tenantId`. Avoid catch-all subscription without filter — costs and noise.\n\n**Architect:** Subscription = bounded context consumer. Document event catalog: schema, version, subscribers. Use separate subscriptions per service, not shared subscription with in-app routing.",
      "Topic/subscription is Azure event-driven microservices backbone.",
      "Forward to another topic? — Subscription forward rules for routing without custom code.",
      "Subscription auto-delete on idle? — Useful for ephemeral dev; dangerous in prod without review.",
      "Single subscription shared by three services",
      "No subscription-level DLQ monitoring",
      "Publisher knows subscriber implementation details"),
    q("Service Bus Sessions", "Service Bus", "Very Common",
      "Order line items must process in sequence per orderId — implement with Service Bus sessions?",
      "Set `SessionId = orderId` on send. Consumer accepts session, processes all messages for that order sequentially, then completes session.",
      "**Sessions:** FIFO guarantee per session ID — not global FIFO.\n\n**Pattern:** payment events for order-123 always processed in order; different orders parallel across consumers.\n\n**Architect:** Sessions reduce throughput per session — don't session-key entire platform on low-cardinality key (e.g. `country=US`). Session lock timeout and renewal required for long handlers.",
      "Sessions solve per-entity ordering — common follow-up to queue design.",
      "Session lock lost? — Handler must be idempotent; renew lock during long processing.",
      "Sessions on Premium only? — Available Standard and Premium; Premium for higher throughput.",
      "Sessions for all messages regardless of ordering need",
      "Low-cardinality session key causing hot partition",
      "No lock renewal on 5-minute handler"),
    q("Service Bus Partitioning", "Service Bus", "Common",
      "When enable partitioning on Service Bus entity and what changes?",
      "Partitioning spreads entity across multiple message brokers for throughput. Enable at creation — cannot add later. Trade: ordering only within partition via sessions.",
      "**Use when:** sustained high ingress/egress on single queue/topic exceeds non-partitioned limits.\n\n**Architect:** Plan partition strategy upfront. Partitioned entities still need session ID for per-key order. Geo-DR pairing differs — document MS docs for paired regions.",
      "Partitioning is capacity planning decision — not toggle-on in crisis.",
      "Partition key vs session ID? — Related concepts; session routes to partition bucket.",
      "Migrate non-partitioned to partitioned? — Recreate entity; plan dual-write cutover.",
      "Enable partitioning after production launch",
      "Assume global FIFO on partitioned queue",
      "No throughput measurement before partitioning"),
    q("Service Bus Premium Tier", "Service Bus", "Common",
      "Justify Service Bus Premium over Standard for a payment platform?",
      "Premium: dedicated capacity, predictable latency, larger message size (100 MB vs 256 KB Standard with claim check), VNet integration, geo-disaster recovery pairing.",
      "**When Standard enough:** moderate volume, cost-sensitive, no VNet requirement.\n\n**When Premium:** noisy-neighbor isolation, compliance requires private endpoint, sustained >1000 msg/sec per messaging unit, mission-critical latency SLA.\n\n**Architect:** Model messaging units (MUs) and cost vs SLA risk. Premium Messaging SKU bundles with isolated hardware.",
      "Tier selection ties messaging to enterprise SLA and network design.",
      "Premium geo-DR? — Alias-based pairing between namespaces in paired regions.",
      "Auto-scaling MUs? — Premium supports messaging unit scale within namespace.",
      "Premium for dev/test environments",
      "Standard with 10 MB messages without claim check pattern",
      "No VNet requirement cited but Premium chosen for hype"),
    q("Event Grid System Topics", "Event Grid", "Very Common",
      "React to BlobCreated in Storage without polling — Event Grid system topic design?",
      "Enable system topic on storage account; Event Subscription filters event type `Microsoft.Storage.BlobCreated` → Function or Logic App webhook endpoint.",
      "**System topics:** Azure resource publishes automatically — no custom publisher code.\n\n**Flow:** upload to `incoming/` container → Event Grid → virus scan Function → move to `clean/`.\n\n**Architect:** Prefer Event Grid over Storage polling for reactive automation. RBAC: Event Grid needs permission to deliver to destination (e.g. Function with RBAC trigger).",
      "System topics are default Azure-native event routing.",
      "Event delivery schema? — Event Grid envelope with `data` payload per resource provider.",
      "Dead letter for failed delivery? — Configure storage blob DLQ destination on subscription.",
      "Polling blob container every minute",
      "No filter — all storage events to one handler",
      "Missing managed identity on Event Grid subscription"),
    q("Event Grid Custom Topics", "Event Grid", "Very Common",
      "Publish domain events from order microservice via Event Grid custom topic?",
      "Create custom topic; order service publishes CloudEvents/EG schema via REST or SDK with SAS key or MI. Subscribers create event subscriptions with filters.",
      "**Custom topic:** your application is publisher — decouples subscribers from order API.\n\n**Security:** prefer managed identity + RBAC (`EventGrid Data Sender`) over long-lived keys.\n\n**Architect:** Custom topic for external/partner fan-out; Service Bus often better for ordered transactional workflows with DLQ semantics.",
      "Custom topics bridge application events to Azure serverless consumers.",
      "CloudEvents on custom topic? — Supported — improves portability.",
      "Input schema validation? — Event Grid advanced filtering and partner topics.",
      "Direct HTTP calls from publisher to every subscriber",
      "Shared SAS key in all microservices",
      "Custom topic for payment command with strict ordering"),
    q("Event Grid Domains", "Event Grid", "Common",
      "When use Event Grid domain vs multiple custom topics?",
      "Domain: single endpoint managing thousands of topics (multi-tenant SaaS). Each tenant gets topic within domain. Centralized auth and quota.",
      "**SaaS pattern:** domain `contoso-events.azure.net` → topic per tenant `tenant-abc` → their subscriptions.\n\n**Architect:** Domain reduces management overhead at scale (10K tenants). Custom topic per bounded context for simpler estates (<50 topics).",
      "Domains are multi-tenant event routing control plane.",
      "Domain RBAC? — Assign at domain or topic level per tenant isolation.",
      "Domain throughput limits? — Plan partition across domains if exceeding quotas.",
      "Separate custom topic per tenant at 5000 tenants",
      "No tenant isolation on domain RBAC",
      "Domain for single-app three events only"),
    q("Event Hubs Partitions", "Event Hubs", "Very Common",
      "Size Event Hubs partition count for 50K events/sec clickstream?",
      "Throughput scales with partitions — plan partition count at creation (increase limited). Partition key (userId) ensures related events land same partition for ordered consumer read.",
      "**Rule of thumb:** 1 MB/s ingress per throughput unit; partitions distribute load. Consumer groups read the read load — one consumer instance per partition max for balanced read.\n\n**Architect:** Cannot easily shrink partitions — over-provision with growth plan. Hot partition if poor key choice (e.g. constant key).",
      "Partition planning is irreversible Event Hubs decision.",
      "Partition vs consumer group? — Partitions = write scale; consumer groups = independent readers.",
      "Auto-inflate TUs? — Scale throughput units; partitions fixed at create.",
      "Single partition for high-volume stream",
      "Random partition key when per-user order needed",
      "More consumers than partitions expecting scale"),
    q("Event Hubs Capture", "Event Hubs", "Common",
      "Enable Capture on Event Hubs for analytics replay — configuration?",
      "Capture writes Avro files to ADLS/Blob on time (e.g. 5 min) or size window. Downstream Synapse/Spark reads lake; stream processor handles real-time path.",
      "**Benefits:** cheap long-term retention vs keeping in Event Hubs; replay for ML retraining.\n\n**Architect:** Capture + Stream Analytics = lambda architecture on Azure. Set lifecycle policy on capture container to cool/archive tiers.",
      "Capture is batch archive complement to real-time stream.",
      "Capture vs Consumer reading to lake? — Capture automatic, no consumer code maintenance.",
      "Avro schema evolution? — Plan compatibility in downstream Spark jobs.",
      "Retain all events in Event Hubs 365 days",
      "No capture for compliance audit trail",
      "Capture container public access enabled"),
    q("Event Hubs Kafka Endpoint", "Event Hubs", "Common",
      "Migrate on-prem Kafka producers to Azure without code change?",
      "Event Hubs Kafka surface — same bootstrap `*.servicebus.windows.net:9093` with connection string or OAuth. Existing Kafka clients connect with minimal config change.",
      "**Limits:** not 100% Kafka API parity — verify admin operations and exact protocol features.\n\n**Architect:** Accelerates migration lift-and-shift. Long-term evaluate native Event Hubs SDK for Azure optimizations. Enable Kafka on existing namespace.",
      "Kafka endpoint is migration bridge not eternal architecture.",
      "Kafka vs native AMQP? — Kafka for existing clients; AMQP for Azure-native greenfield.",
      "Schema Registry with Kafka endpoint? — Azure Schema Registry integrates.",
      "Assume full Kafka broker feature parity",
      "No TLS/SASL config update in clients",
      "Kafka endpoint without monitoring partition lag"),
    q("Azure Relay Hybrid Connections", "Hybrid", "Common",
      "Expose on-prem SQL to Azure Function without VPN — Relay Hybrid Connection?",
      "Install Hybrid Connection Manager on-prem; Relay namespace hybrid connection maps TCP endpoint. Azure Function/App connects outbound through Relay — no inbound firewall hole.",
      "**vs VPN/ExpressRoute:** Relay for single endpoint quick connect; VPN for full network mesh.\n\n**Architect:** Hybrid Connections for legacy SOAP/SQL during migration. Not replacement for Private Link long-term — latency and ops overhead higher.",
      "Relay solves hybrid reach without site-to-site VPN for one service.",
      "Hybrid vs Private Link? — Private Link for Azure PaaS; Relay for on-prem TCP.",
      "HCM high availability? — Multiple HCM instances for redundancy.",
      "Open inbound SQL port to Azure IP range",
      "Relay for all microservice traffic instead of VPN",
      "Single HCM node no HA"),
    q("Logic Apps Consumption vs Standard", "Logic Apps", "Very Common",
      "Choose Logic Apps Consumption vs Standard for B2B EDI workflow?",
      "Standard: VNet integration, fixed predictable cost, Integration Account, long-running workflows, single-tenant isolation. Consumption: serverless pay-per-action, quick integrations, no VNet.",
      "**EDI high volume:** Standard in ASE or dedicated plan — action cost at scale breaks Consumption economics.\n\n**Architect:** Consumption for webhooks and simple connectors; Standard for enterprise integration with on-prem gateways and private APIs.",
      "Plan selection drives integration cost and network posture.",
      "Consumption limits? — Run duration, connector throttling, no VNet.",
      "Stateful workflows Standard? — Better for long B2B processes with human approval.",
      "Consumption for high-volume EDI 500K actions/day",
      "Standard without VNet when calling private API",
      "Logic App for core synchronous OLTP path"),
    q("API Management Policies", "APIM", "Very Common",
      "Implement JWT validation, header injection, and backend routing in APIM policy pipeline?",
      "Inbound: `validate-jwt` → `set-header` correlation ID → `set-backend-service` based on `/v2/` path. Outbound: strip internal headers. On-error: return JSON problem details.",
      "**Policy scopes:** global → product → API → operation — narrowest wins.\n\n**Architect:** Keep business logic out of policies — gateway concerns only (auth, rate limit, routing, transformation). Version policies in Git with APIM DevOps.",
      "Policy pipeline is APIM architect core skill.",
      "Policy expressions vs fragments? — Fragments reuse across APIs.",
      "Trace policy for debug? — Enable in dev; disable prod verbose trace.",
      "500 lines business rules in XML policy",
      "No validate-jwt on external API",
      "Policies edited only in portal not IaC"),
    q("APIM Rate Limiting", "APIM", "Very Common",
      "Design tiered rate limits: 100 req/min free, 10K partner?",
      "Products per tier with `rate-limit` or `quota` policies keyed by subscription. `rate-limit-by-key` on `context.Subscription.Id` or JWT claim `partnerId`.",
      "**429 response:** include `Retry-After`. Combine with Azure Front Door rate limiting for DDoS edge layer.\n\n**Architect:** Rate limit at gateway — protect backends uniformly. Document limits in developer portal. Monitor 429 metrics per product.",
      "Rate limiting protects platform and enables monetization tiers.",
      "Rate limit vs quota? — Rate = per window burst; quota = total over period.",
      "Bypass for internal callers? — Separate product or IP filter policy.",
      "Rate limit in each microservice differently",
      "No 429 or Retry-After header",
      "Unlimited public API on launch"),
    q("APIM OAuth and OIDC", "APIM", "Very Common",
      "Secure APIM API with Entra ID OAuth 2.0 client credentials and user delegation?",
      "Register API in Entra; APIM `validate-jwt` with tenant issuer and audience. Client credentials for service-to-service; auth code + PKCE for user-facing apps via developer portal OAuth config.",
      "**Pattern:** mobile app → auth code → bearer token → APIM validates → forwards to backend with optional `Authorization` or managed identity to backend.\n\n**Architect:** Never pass client secret to mobile. APIM caches JWKS. Separate app registrations per environment.",
      "OAuth at gateway is standard Azure API security pattern.",
      "OAuth 2.0 vs Easy Auth? — APIM for external API; Easy Auth for App Service direct.",
      "Certificate-bound tokens? — CAE and continuous access evaluation with CA policies.",
      "API key only for partner integration",
      "validate-jwt without audience check",
      "Same app registration prod and dev"),
    q("APIM Self-Hosted Gateway", "APIM", "Common",
      "Deploy APIM self-hosted gateway for on-prem API consumers?",
      "Self-hosted gateway container in on-prem K8s/VM connects outbound to APIM control plane in cloud. Local traffic stays local; policies sync from cloud.",
      "**Use cases:** hybrid latency-sensitive, data residency requires local gateway termination, air-gapped edge sites.\n\n**Architect:** Premium APIM feature. Control plane cloud; data plane local. HA: multiple gateway replicas.",
      "Self-hosted gateway extends APIM to hybrid edge.",
      "vs Azure API gateway on AKS? — APIM policy consistency across cloud and edge.",
      "Gateway upgrade? — Container image updates from APIM; plan rolling update.",
      "Self-hosted without HA replicas",
      "Developer SKU expecting self-hosted",
      "All traffic through cloud APIM adding latency unnecessarily"),
    q("Integration Account B2B", "Integration", "Common",
      "Configure Integration Account for partner onboarding and EDI X12?",
      "Integration Account stores schemas, maps, partners, agreements. Logic Apps uses account for encode/decode AS2/X12, validate against schema, transform to canonical JSON.",
      "**Partner record:** AS2 identifier, certificate, MDN settings. **Agreement:** links partners with protocol settings.\n\n**Architect:** Anti-corruption layer — EDI → canonical Order domain event → Service Bus. Rotate partner certs before expiry with monitoring.",
      "Integration Account is Azure iPaaS B2B anchor.",
      "Integration Account tier? — Basic vs Standard for HL7/X12 features.",
      "Maps vs Liquid transforms? — Liquid in Logic Apps for JSON/XML mapping.",
      "Custom EDI parser in monolith",
      "Partner cert expiry not monitored",
      "No error handling on decode failure"),
    q("AS2 EDI Integration", "Integration", "Occasional",
      "Design AS2 receive flow for retail partner PO files on Azure?",
      "Logic App AS2 receive trigger → Integration Account agreement validates signature/decrypt → parse X12 850 → map to JSON → Service Bus `PurchaseOrderReceived`.",
      "**AS2:** HTTPS + signing/encryption + MDN async/sync acknowledgment.\n\n**Architect:** Store raw EDI in Blob for audit 7 years. DLQ failed parses. Idempotent on PO number. Compare with managed SFTP + Function for simpler partners.",
      "AS2 shows legacy integration competence.",
      "AS2 vs SFTP? — AS2 real-time HTTP push; SFTP batch file drop.",
      "MDN failure handling? — Retry and partner alert; poison quarantine.",
      "Skip MDN acknowledgment",
      "No raw archive for compliance",
      "Process PO before signature validation"),
    q("Azure Functions Durable Orchestration", "Serverless", "Very Common",
      "Implement order saga with Durable Functions vs Service Bus choreography?",
      "Durable orchestrator: call inventory (activity) → payment → shipping with compensating transactions on failure. State persisted in storage table — visible workflow.",
      "**When Durable:** complex branching, human approval timers, need orchestration visibility.\n\n**When Service Bus:** loose coupling, many subscribers, event-native teams.\n\n**Architect:** Durable = orchestration; Service Bus topics = choreography. Sub-orchestrations for nested flows.",
      "Orchestration choice is integration architecture classic.",
      "Durable vs Logic Apps? — Code-heavy logic Durable; connector-rich low-code Logic Apps.",
      "Fan-out fan-in pattern? — Durable Task API parallel activities with timeout.",
      "Choreography for 12-step order with compensation",
      "Durable for simple fire-and-forget notification",
      "No idempotent activities in orchestration"),
    q("Messaging Idempotency", "Reliability", "Very Common",
      "Design idempotent Service Bus consumer for payment capture?",
      "Store processed `messageId` or business key `paymentId` in SQL with unique constraint. Handler checks before side effect; complete message only after commit.",
      "**At-least-once delivery:** assume duplicates. **Effectively-once:** idempotent write + dedup table.\n\n**Architect:** Idempotency key propagated from API through outbox to message properties. TTL dedup table to bound storage.",
      "Idempotency is non-negotiable for messaging consumers.",
      "Idempotency vs duplicate detection? — Broker window vs app-level permanent dedup.",
      "Outbox + idempotent consumer together? — Yes — standard production pattern.",
      "Complete message before DB commit",
      "Assume exactly-once Service Bus delivery",
      "No dedup for financial side effects"),
    q("Dead Letter Handling", "Operations", "Very Common",
      "Operational playbook when Service Bus DLQ depth exceeds threshold?",
      "Alert → triage sample messages → classify poison vs transient → fix consumer → replay via script to main queue after deploy → postmortem root cause.",
      "**Tools:** Service Bus Explorer, `ServiceBusReceiver` on sub-queue `$deadletterqueue`. **Never** auto-replay all without fix.\n\n**Architect:** DLQ metrics per subscription in dashboard. Runbook linked in alert. Separate DLQ for manual review vs automated retry queue.",
      "DLQ operations separate mature integration teams.",
      "DLQ retention? — Messages persist until explicitly removed — capacity plan.",
      "Move to Blob for analysis? — Export poison payload for dev reproduction.",
      "Delete DLQ messages without analysis",
      "No alert on DLQ growth",
      "Auto-replay before fix deployed"),
    q("Message Size Limits", "Service Bus", "Common",
      "Service Bus 256 KB limit blocks large order payload — pattern?",
      "Claim check: upload document to Blob; message carries URL + SAS token or MI-accessible path + metadata. Consumer fetches payload from storage.",
      "**Standard limit:** 256 KB message; Premium up to 100 MB but claim check still best practice.\n\n**Architect:** Keep messages lean for throughput and cost. Compress small JSON if near limit. Event Grid + Blob pattern same principle.",
      "Claim check is universal large-payload messaging pattern.",
      "Batch send for small messages? — `ServiceBusMessageBatch` reduces round trips.",
      "Event Hubs 1 MB event limit? — Same claim check applies.",
      "Embed 2 MB PDF in message body",
      "Public SAS on blob in message forever",
      "Ignore size in load test design"),
    q("Schema Registry for Event Hubs", "Schema", "Common",
      "Enforce Avro schema evolution for Event Hubs producers and consumers?",
      "Azure Schema Registry in Event Hubs namespace; producers register schema; serialize with schema ID; consumers deserialize with compatibility mode (backward/forward).",
      "**Benefits:** contract enforcement, fewer deserialization failures, documentation.\n\n**Architect:** CI validates schema compatibility before deploy. Version bump strategy: add optional fields backward compatible. Link to event catalog in repo.",
      "Schema registry prevents silent contract breaks in streaming.",
      "Schema Registry vs Protobuf? — Azure SR supports Avro primary; JSON Schema emerging.",
      "Incompatible schema deploy? — Block in pipeline with compatibility check API.",
      "Undocumented JSON blobs in stream",
      "Breaking rename field without version",
      "No schema in code repo"),
    q("CloudEvents Format", "Standards", "Common",
      "Standardize cross-service events with CloudEvents 1.0 on Azure?",
      "Wrap payload: `specversion`, `type`, `source`, `id`, `time`, `datacontenttype`. Publish to Event Grid or Service Bus application properties + JSON body.",
      "**Interoperability:** Knative, AWS EventBridge, on-prem tools understand CloudEvents.\n\n**Architect:** Map domain event names to `type` (`com.contoso.order.placed.v1`). `id` for dedup. Event Grid natively supports CloudEvents schema.",
      "CloudEvents is portable event envelope standard.",
      "CloudEvents vs custom envelope? — Standard wins multi-cloud and tooling.",
      "Binary vs structured mode? — Structured JSON common on HTTP; binary for AMQP.",
      "Inconsistent event headers per team",
      "No version in event type string",
      "Duplicate id across publishers"),
    q("Saga with Service Bus", "Patterns", "Very Common",
      "Implement compensating saga for travel booking with Service Bus?",
      "Choreography: `BookingStarted` → reserve flight/hotel/car via subscriptions; failures publish `BookingFailed` triggering compensating `Release*` events. Correlation ID ties saga.",
      "**Orchestration alternative:** Durable Functions central coordinator.\n\n**Architect:** Document saga state transitions. Timeout events for stuck steps. Idempotent compensation — `ReleaseFlight` safe if already released.",
      "Saga pattern is distributed transaction interview staple.",
      "Saga vs 2PC? — No distributed locks — eventual consistency accepted.",
      "Monitoring saga? — App Insights with correlation across messages.",
      "Synchronous chain of 6 REST calls",
      "Missing compensation on partial failure",
      "No saga timeout handling"),
    q("Outbox with Azure SQL", "Patterns", "Very Common",
      "Transactional outbox: SQL order insert + Service Bus publish atomically?",
      "Same transaction inserts order row and outbox row (`status=pending`). Background worker polls or SQL trigger → Function sends to Service Bus → marks `processed`.",
      "**Alternatives:** Debezium CDC, SQL Server Change Tracking to Event Hubs.\n\n**Architect:** Polling interval vs latency trade-off. Index outbox on status+created. Horizontal scale workers with lease pattern to avoid double-send.",
      "Outbox solves dual-write problem correctly.",
      "Outbox vs dual write? — Dual write loses consistency on partial failure.",
      "At-least-once outbox relay? — Idempotent consumer handles duplicate send.",
      "Publish to Service Bus before SQL commit",
      "No outbox cleanup/archival",
      "Single worker SPOF without lease"),
    q("Inbox Pattern", "Patterns", "Common",
      "Implement inbox pattern alongside outbox for incoming Service Bus messages?",
      "Consumer transaction: insert inbox record with messageId (unique) → process business logic → mark processed. Duplicate delivery hits unique constraint — skip safely.",
      "**Pairs with outbox** for end-to-end reliability in integration service.\n\n**Architect:** Inbox table per consumer service. Same DB as business write for single transaction. Cleanup processed inbox rows on schedule.",
      "Inbox completes consumer-side idempotency story.",
      "Inbox vs dedup cache? — Inbox durable audit trail; Redis dedup faster but volatile.",
      "Process then insert inbox? — Wrong order — insert first in same TX as handler.",
      "Handler side effects before inbox insert",
      "No unique constraint on messageId",
      "Inbox table unbounded growth"),
    q("Event-Driven Microservices on Azure", "Architecture", "Very Common",
      "Draw Azure event-driven reference for e-commerce microservices?",
      "Sync: APIM → order API. Async: OrderPlaced/OrderShipped on Service Bus topic → inventory, notification, analytics subscriptions. Outbox from writers. Event Grid for infra events.",
      "**Principles:** choreograph by default; orchestrate when needed; schema registry; DLQ everywhere; correlation IDs.\n\n**Architect:** Bounded context owns its events. No shared database — events are contract.",
      "Event-driven is week 15 synthesis architecture.",
      "Event notification vs event-carried state? — Prefer slim events + query API for large state.",
      "Azure Service Bus vs Event Hubs for domain events? — Service Bus for business messaging; Event Hubs for telemetry firehose.",
      "Distributed monolith via shared DB",
      "Synchronous mesh between all services",
      "No event versioning strategy"),
    q("CQRS with Service Bus", "Patterns", "Common",
      "Separate read model updates using Service Bus after command side write?",
      "Command API writes to SQL → outbox → `OrderUpdated` event → projection handler updates Cosmos/read store or Elasticsearch.",
      "**Benefits:** scale reads independently, optimized query models.\n\n**Architect:** Accept eventual consistency lag (seconds). Version projections for schema change. Separate consumer group/subscription for read model updater.",
      "CQRS on Azure commonly uses messaging for projection pipeline.",
      "CQRS vs CRUD? — CQRS when read/write shapes diverge significantly.",
      "Replay projections? — Rebuild read model from event log or replay topic.",
      "Same table for command and complex read joins",
      "No lag monitoring on projection",
      "Projection update synchronous in command API"),
    q("Webhooks vs Polling", "Integration", "Very Common",
      "Partner asks webhook vs your polling their API — decision criteria?",
      "Webhooks: real-time, efficient, requires public endpoint or Event Grid partner topic, signature verification, retry logic. Polling: simpler firewall, higher latency, rate limit risk.",
      "**Azure:** expose webhook via APIM with HMAC validation; or Logic App recurrence poll with delta token.\n\n**Architect:** Prefer webhooks at scale; polling for legacy partners without push capability. Idempotent webhook handler — partners retry.",
      "Push vs pull integration is common partner discussion.",
      "Webhook security? — HMAC-SHA256 signature, timestamp anti-replay, IP allowlist.",
      "Event Grid webhook delivery? — Built-in retry and DLQ.",
      "Poll every 10 seconds at 1000 partners",
      "Webhook without signature verification",
      "No idempotency on webhook retries"),
    q("Async API Design", "API Design", "Very Common",
      "Design async REST API: submit job returns 202 with status URL?",
      "POST `/reports` → 202 Accepted + `Location: /reports/{id}/status` + optional `Retry-After`. Client polls status or registers webhook callback URL. Result in Blob when complete.",
      "**Headers:** `Operation-Location`, correlation ID. **Storage:** job state in Table/Cosmos.\n\n**Architect:** Never block HTTP 30s for long work — Service Bus + Functions backend. Document async pattern in OpenAPI.",
      "Async API pattern prevents gateway timeouts and improves UX at scale.",
      "vs gRPC streaming? — Async REST for broad client compatibility.",
      "Cancel async operation? — DELETE on operation ID signals cancellation token to worker.",
      "HTTP 200 after 45 second report generation",
      "No status endpoint for 202",
      "Lost jobs without durable state store"),
    q("Backpressure in Messaging", "Performance", "Common",
      "Consumers fall behind producers — apply backpressure on Azure?",
      "Monitor queue depth lag; scale out consumers (KEDA); throttle producers via 429 from API; max queue size policy; pause non-critical publishers.",
      "**KEDA:** scale Function/ACA on Service Bus queue length. **Architect:** Define SLA max lag (e.g. 5 min). Alert on age of oldest message. Premium Service Bus for headroom.",
      "Backpressure protects downstream from overload collapse.",
      "Prefetch count tuning? — Higher prefetch throughput but uneven if consumer slow.",
      "Dead letter old messages? — Only if business allows — usually the scale out.",
      "Unbounded queue with no lag alerts",
      "Single consumer on growing queue",
      "Producer ignores 503 backpressure signal"),
    q("KEDA Service Bus Scaler", "Kubernetes", "Common",
      "Configure KEDA to scale AKS deployment on Service Bus queue depth?",
      "Install KEDA; ScaledObject references deployment; trigger `azure-servicebus` with connection string or frontend length threshold (e.g. scale at 100 messages per pod).",
      "**Auth:** workload identity preferred over connection string in ScaledObject.\n\n**Architect:** minReplicas > 0 for latency-sensitive; maxReplicas cap cost. Cooldown prevents flapping.",
      "KEDA connects messaging metrics to compute scale.",
      "KEDA vs HPA CPU? — KEDA event-driven; HPA for CPU-bound sync APIs.",
      "Multiple triggers? — Combine Service Bus + CPU in ScaledObject.",
      "CPU-only HPA on queue worker",
      "maxReplicas unlimited cost surprise",
      "Connection string in ScaledObject YAML in git"),
    q("Functions Service Bus Trigger", "Serverless", "Very Common",
      "Configure Azure Function Service Bus trigger with peek-lock and retry?",
      "Trigger on queue/subscription; `autoCompleteMessages: false` for manual complete after success; `maxAutoLockRenewalDuration` for long handlers; poison → DLQ after max deliveries.",
      "**Settings:** batch size, prefetch, session handler for session-enabled entity.\n\n**Architect:** Function Premium or dedicated plan for VNet + always-ready instances on critical queues.",
      "Functions trigger is default Azure message consumer.",
      "Trigger vs Runbook? — Function for code; Logic App for connector workflows.",
      "Managed identity trigger auth? — RBAC `Azure Service Bus Data Receiver`.",
      "autoComplete true before DB commit",
      "Consumption plan cold start on critical queue",
      "No DLQ configured on subscription"),
    q("Ordering Guarantees", "Reliability", "Very Common",
      "What ordering guarantees exist across Azure messaging services?",
      "Service Bus sessions: FIFO per session ID. Event Hubs: order within partition. Event Grid: no ordering guarantee. Standard queues: no global order.",
      "**Design:** assign session/partition key deliberately. Don't assume cross-partition order.\n\n**Architect:** Sequence numbers for gap detection. Reorder buffer in consumer if minor disorder acceptable.",
      "Ordering guarantees vary — architects match service to requirement.",
      "Global order requirement? — Single session/partition bottleneck — often wrong design.",
      "Out-of-order handling? — Version field + discard stale updates.",
      "Assume Event Grid ordered delivery",
      "Random partition key needing order",
      "No sequence number in event schema"),
    q("Duplicate Detection", "Service Bus", "Common",
      "Enable Service Bus duplicate detection for idempotent publishes?",
      "Set `MessageId` or duplicate detection history window on queue/topic; broker drops duplicate within window (default 10 min, max 7 days).",
      "**Complements** application idempotency — not replacement.\n\n**Architect:** Use business key as MessageId for natural dedup (`order-123-placed`). Enable at entity creation. Document window for ops.",
      "Broker duplicate detection reduces consumer load.",
      "Duplicate detection vs sessions? — Orthogonal features both can enable.",
      "Window expired duplicate? — App-level dedup still required.",
      "Random GUID MessageId every retry",
      "Duplicate detection disabled on payment queue",
      "Assume broker dedup replaces inbox pattern"),
    q("TTL on Messages", "Service Bus", "Common",
      "Set message TTL for time-sensitive fraud check events?",
      "Set `TimeToLive` on message or default on entity — expired messages dropped or dead-lettered depending on config.",
      "**Use case:** price quote valid 15 minutes — TTL 15m on quote events; consumer ignores stale anyway.\n\n**Architect:** Align TTL with business validity. Monitor expired counts. Don't TTL audit events prematurely.",
      "TTL prevents processing stale business events.",
      "TTL vs scheduled enqueue? — TTL expires; scheduled delays delivery.",
      "Default TTL on entity? — Applies when message TTL not set.",
      "Process expired payment authorization",
      "No TTL on time-bound offers",
      "TTL 7 days on fraud hold needing 24h max"),
    q("Scheduled Messages", "Service Bus", "Common",
      "Schedule payment capture 24 hours after order shipment?",
      "Send message with `ScheduledEnqueueTimeUtc` — broker holds until time, then delivers to queue for capture worker.",
      "**vs Durable timer:** Service Bus schedule simpler for single delay; Durable for complex workflow timers.\n\n**Architect:** Cancel scheduled message by sequence number if order cancelled before capture.",
      "Scheduled messages replace hacky sleep in workers.",
      "Schedule limit? — Large backlog of scheduled messages — monitor namespace metrics.",
      "Cancel scheduled message? — CancelScheduledMessageAsync with sequence number.",
      "Sleep 24h in Function execution",
      "Cron poll DB for ready captures",
      "No cancel path on order cancellation"),
    q("Geo-Disaster Recovery for Messaging", "DR", "Common",
      "Design Service Bus geo-disaster recovery for critical namespace?",
      "Premium: pair primary/secondary namespaces with alias; metadata sync; failover breaks pairing until re-pair. Apps use connection string alias for transparent failover.",
      "**Failover:** manual or scripted; in-flight messages primary may lost — document RPO. **Re-pair** after primary healthy.\n\n**Architect:** DR drill includes messaging failover + consumer reconnect test. Event Hubs geo-disaster recovery similar with alias.",
      "Messaging DR is often overlooked in DR plans.",
      "Active-active messaging? — Complex conflict resolution — prefer active-passive for Service Bus.",
      "Event Grid DR? — Multi-region publish endpoints; custom topic redundancy patterns.",
      "No DR on messaging tier Standard mission-critical",
      "Failover never tested in game day",
      "Hardcoded primary namespace connection only"),
]

WEEK_16_Q011_Q050 = [
    q("Production Architecture Review", "Capstone", "Very Common",
      "Lead production architecture review for Azure SaaS — scope and deliverables?",
      "Review WAF five pillars, threat model, data flows, HA/DR, identity, network, observability, FinOps, IaC maturity. Deliverable: ranked findings with owners, dates, and accepted risks.",
      "**Process:** pre-read architecture docs → 2-hour session with app + platform + security → written report within 5 days.\n\n**Architect:** Collaborative not gatekeeping — every Critical finding needs mitigation option or explicit risk acceptance by product owner.",
      "Production review synthesizes entire architect curriculum.",
      "Review cadence? — Major release + annual prod health check.",
      "Sign-off blockers? — Open Critical; High must have dated plan.",
      "Checklist without workload context",
      "Verbal findings only no traceability",
      "Security-only lens ignoring cost and ops"),
    q("Multi-Region SLA Math", "Reliability", "Very Common",
      "Calculate end-to-end SLA: Front Door 99.99%, App Service 99.95%, SQL geo 99.99%?",
      "Series dependencies multiply: 0.9999 × 0.9995 × 0.9999 ≈ 99.93%. Parallel redundant paths improve composite — document weakest link.",
      "**Presentation:** show math to executives; propose mitigation (cache, fallback read-only mode) if below target.\n\n**Architect:** Don't contract SLA below calculated composite without architectural change.",
      "SLA math is executive-facing architect deliverable.",
      "Independent vs dependent failures? — Model realistically — shared region outage hits all.",
      "Error budget at 99.9%? — ~43 minutes downtime/month allowed.",
      "Add SLAs instead of multiply",
      "Promise 99.99% without chain analysis",
      "Ignore third-party SaaS in chain"),
    q("DR Drill Execution", "DR", "Very Common",
      "Execute quarterly DR drill for Azure SQL failover group — steps?",
      "Announce window → simulate primary failure → trigger failover → validate app connectivity synthetic tests → measure RTO → document gaps → failback in lower environment next sprint.",
      "**Success criteria:** RTO < target, RPO within business tolerance, runbook steps complete without improvisation.\n\n**Architect:** Rotate drill scenarios — region down, corruption, key compromise.",
      "Untested DR is wishful thinking — drills prove RTO.",
      "Tabletop vs full drill? — Tabletop quarterly; full failover semi-annual.",
      "Blast radius containment? — Drill in isolated subscription first.",
      "DR plan never exercised",
      "Failover first time during real outage",
      "No failback procedure documented"),
    q("RTO RPO Validation", "DR", "Very Common",
      "Business requires RPO 15 min, RTO 1 hour — validate Azure design delivers?",
      "RPO: SQL geo-replica/async replication lag monitoring < 15m. RTO: automated failover group + runbook + App Service multi-instance warm secondary — drill measured time.",
      "**Evidence:** drill logs, replication lag dashboards, written attestation for auditors.\n\n**Architect:** RPO/RTO are business terms — map to technical controls and test results, not SKU names alone.",
      "RTO/RPO validation closes gap between design and proof.",
      "RPO zero requirement? — Sync replication latency/cost trade-off — geographic limits.",
      "RTO vs MTTR? — RTO business-facing; MTTR ops metric — align both.",
      "Claim RPO 0 with async replication",
      "No lag monitoring on replica",
      "RTO estimate never measured in drill"),
    q("FinOps Production Budget", "FinOps", "Very Common",
      "Set production Azure budget with alerts and escalation?",
      "Budget at subscription/MG scoped to prod; alerts 50/80/100/120% to FinOps + engineering lead; Cost Management action group; monthly review with tag-based chargeback.",
      "**Architect:** Budget tied to unit economics ($/order) not just total — anomaly when unit cost spikes.\n\n**Include:** Log Analytics ingestion, Service Bus ops, egress — hidden drivers.",
      "Production FinOps is ongoing not launch-only.",
      "Budget vs reservation? — Budget alerts spend; RI/SP reduces rate — separate tracking.",
      "Chargeback tags? — Required tags policy `CostCenter`, `Product`.",
      "No budget on prod subscription",
      "Alert only at 100% — too late",
      "Untagged 30% spend unallocated"),
    q("Cost Anomaly Response", "FinOps", "Common",
      "Production spend jumped 40% overnight — triage process?",
      "Cost Management anomaly detection alert → identify resource/service spike in Cost Analysis → check recent deploys, autoscale runaway, Log Analytics ingestion, DDoS egress → contain (scale down, cap) → postmortem.",
      "**Common culprits:** verbose logging, forgotten load test, misconfigured autoscale max, public blob egress abuse.\n\n**Architect:** FinOps runbook parallel to incident runbook.",
      "Cost incidents deserve same urgency as availability.",
      "Azure Advisor cost alerts? — Supplement anomaly detection.",
      "Prevent recurrence? — Policy max SKUs; budget hard actions.",
      "Ignore cost alert until month end",
      "No owner for cost anomalies",
      "Load test in prod without budget guardrails"),
    q("Incident Command in Production", "Operations", "Very Common",
      "You are incident commander for Sev1 Azure outage — first 15 minutes?",
      "Declare Sev1, open bridge, assign roles (IC, comms, ops, scribe), confirm customer impact, stop risky changes, gather timeline, engage Azure support if platform, 15-min status cadence.",
      "**Azure-specific:** check Service Health, Resource Health, recent deployments, Front Door backend health.\n\n**Architect:** IC coordinates — doesn't solo-debug. Single source of truth doc.",
      "Incident command proves operational maturity.",
      "Sev1 vs Sev2? — Pre-defined severity matrix by revenue/users affected.",
      "When engage Microsoft? — Platform SLA impact — support ticket priority.",
      "Everyone debugs without coordination",
      "No scribe — lost timeline",
      "Deploy fix during unclear root cause"),
    q("Blameless Post-Incident Review", "Operations", "Very Common",
      "Facilitate blameless PIR after prod outage — structure?",
      "Timeline facts → impact metrics → root cause (5 whys) → contributing factors → action items (detect, prevent, mitigate) with owners — no individual blame.",
      "**Output:** published internally, linked from ADR if architectural gap. Track action item closure in sprint.\n\n**Architect:** System fixes over person fixes — missing runbook, bad alert, no canary.",
      "PIR culture distinguishes senior organizations.",
      "PIR within 48 hours? — Fresh memory; before narrative solidifies wrong.",
      "Customer-facing summary? — Separate comms doc without internal jargon.",
      "Name engineer who caused outage",
      "PIR with no action items",
      "Same root cause third time no systemic fix"),
    q("SLO Error Budget Policy", "Reliability", "Very Common",
      "Define error budget policy when SLO burn exceeds 50% mid-month?",
      "At 50% burn: freeze non-critical releases, focus reliability. At 100%: halt feature work until budget reset; exec notification. Burn rate alerts multi-window.",
      "**SLO example:** 99.9% availability = 43m/month budget. **Tooling:** App Insights + alert on burn rate.\n\n**Architect:** Error budget connects reliability to product velocity — engineering decision not ops alone.",
      "SLO policy is modern production governance.",
      "SLI selection? — User-facing success rate latency tail not CPU.",
      "Partial SLO? — Critical paths stricter SLO than admin UI.",
      "SLO defined but no enforcement",
      "100% availability target impossible",
      "Alert on mean only ignoring p99 latency SLO"),
    q("Canary Production Deploy", "Deployment", "Very Common",
      "Canary deploy new order API on App Service with 5% traffic?",
      "Front Door or APIM weighted routing 5% canary / 95% stable; compare error rate latency 30 min; auto-rollback on SLO breach; gradual 25/50/100.",
      "**Metrics:** golden signals canary vs baseline; business KPI checkout success.\n\n**Architect:** Canary needs representative traffic — feature flags for internal-only canary first if needed.",
      "Canary reduces blast radius of bad deploys.",
      "App Service slot vs Front Door canary? — Slots swap binary; Front Door % gradual.",
      "Automated rollback? — Pipeline gate on App Insights alert.",
      "Big bang deploy Friday 4pm",
      "Canary without comparable traffic volume",
      "No rollback runbook"),
    q("Blue-Green App Service Production", "Deployment", "Very Common",
      "Blue-green deployment on App Service production with minimal downtime?",
      "Production slot (blue) live; deploy to staging (green); warm-up `/health/ready`; slot swap with preview; validate; complete swap; keep previous slot for instant rollback swap back.",
      "**Database:** backward-compatible schema only — expand-contract. **Sessions:** sticky issues — prefer stateless or shared Redis.\n\n**Architect:** Auto-swap only after integration tests pass on staging slot.",
      "Blue-green is App Service native strength.",
      "Swap with VIP? — Instant DNS swap within App Service plan.",
      "Green never receives prod traffic before swap? — Use slot setting sticky for preview test.",
      "Deploy directly to production slot",
      "Breaking DB migration with swap",
      "Delete old slot immediately after swap"),
    q("Feature Flags in Production", "Deployment", "Common",
      "Roll out risky checkout feature to 10% tenants with Azure App Configuration?",
      "Feature flag `checkout-v2` with percentage filter + tenant allowlist; telemetry compares conversion; kill switch instant off without redeploy.",
      "**Architect:** Flags for release control not long-term config — retire flags. Audit flag changes. Combine with canary routing.",
      "Feature flags decouple deploy from release.",
      "App Configuration vs LaunchDarkly? — App Config native Azure; LD advanced targeting.",
      "Flag debt? — Quarterly flag cleanup sprint.",
      "Long-lived branch instead of flag",
      "No kill switch during holiday peak",
      "Flag change without audit trail"),
    q("Chaos Engineering on Azure", "Reliability", "Common",
      "Introduce chaos experiments safely in Azure production?",
      "Start in staging prod-like; then controlled prod (business hours low traffic): kill one pod, simulate Service Bus lag, deny Key Vault access — hypothesize steady state, abort if SLO breach.",
      "**Tools:** Azure Chaos Studio faults (VM, AKS, Network). **Governance:** game day approval, blast radius limits, automated stop.\n\n**Architect:** Chaos proves resilience claims — not chaos monkey random in prod day one.",
      "Chaos validates architecture under failure.",
      "First experiment? — Verify monitoring detects injected failure.",
      "Frequency? — Monthly game day after maturity.",
      "Chaos in prod without hypothesis",
      "No abort criteria during experiment",
      "Chaos before basic monitoring exists"),
    q("Load Test Production-Like", "Performance", "Very Common",
      "Design load test mirroring production before Black Friday?",
      "Azure Load Testing or JMeter against staging prod-parity environment; realistic mix, think time, auth; ramp to 2× peak; monitor App Insights, SQL DTU, Service Bus depth.",
      "**Never** surprise prod unless dedicated load sub with isolation. **Architect:** Define pass criteria (p99 < 500ms, error < 0.1%) before test.",
      "Load test validates capacity plans with evidence.",
      "Production synthetic load? — Only isolated scale test with approval.",
      "Soak test duration? — 4-24h catches memory leaks.",
      "Load test dev SKU expecting prod numbers",
      "No pass/fail criteria defined",
      "Ignore messaging tier in load model"),
    q("Capacity Planning Production", "Operations", "Common",
      "Annual capacity review for Azure production estate?",
      "Trend CPU, memory, DTU, queue depth, TU consumption 12 months; forecast growth; quota checks; reservation renewals; scale ceiling documentation per service.",
      "**Deliverable:** capacity plan spreadsheet + quota increase requests 90 days before need.\n\n**Architect:** Connect business growth forecast (users, orders) to infrastructure headroom.",
      "Capacity planning prevents emergency scale failures.",
      "Azure quota limits? — Pre-request vCPU Service Bus TU before launch.",
      "Headroom target? — 30-40% below max autoscale under peak.",
      "Wait until throttling to plan",
      "No forecast from business growth",
      "Ignore messaging partition limits"),
    q("On-Call Runbook Quality", "Operations", "Very Common",
      "Evaluate runbook quality for Service Bus DLQ alert?",
      "Good runbook: symptom, severity, prerequisites, step-by-step diagnosis, rollback, escalation contact, last-tested date. Linked directly from alert.",
      "**Quality bar:** new engineer resolves 80% incidents without tribal knowledge. **Review:** quarterly runbook drill.\n\n**Architect:** Runbook lives in wiki/Git near IaC — version controlled.",
      "Runbook quality defines on-call experience.",
      "Runbook vs playbook? — Runbook technical steps; playbook incident process.",
      "Stale runbook? — Auto-ticket if last-tested > 6 months.",
      "Alert says page someone",
      "Runbook references retired portal blades",
      "No escalation section"),
    q("Escalation Paths", "Operations", "Common",
      "Define escalation path for unresolved Sev1 after 30 minutes?",
      "L1 on-call → L2 platform engineer (15m) → engineering manager (30m) → director + Azure support Sev A (45m) → exec comms if customer-facing > 1h.",
      "**Document:** phone tree, backup on-call, timezone coverage, vendor contacts (Microsoft, Datadog).\n\n**Architect:** Escalation is pre-negotiated — not invented during outage.",
      "Clear escalation prevents incident stagnation.",
      "Azure support severity? — Sev A for production down platform suspected.",
      "Customer escalation parallel? — Support lead owns external while IC owns technical.",
      "Single on-call no backup",
      "Escalation path unknown to team",
      "Wait 4 hours before manager engaged"),
    q("Customer Communication During Outage", "Operations", "Very Common",
      "Draft customer communication approach for multi-tenant SaaS outage?",
      "Status page update within 15m: impact scope, workaround if any, next update time. Post-resolution: summary, root cause high-level, prevention steps — no sensitive internals.",
      "**Templates:** pre-written status.io/Azure status integration. **Roles:** comms lead separate from IC.\n\n**Architect:** B2B SLA may mandate notification windows — contract drives timeline.",
      "Customer comms is architect awareness for SaaS.",
      "When notify? — When customer-visible impact confirmed — not every internal blip.",
      "Regulatory notification? — GDPR breach diff from availability outage.",
      "Silence until outage over",
      "Blame Azure publicly without verification",
      "Share internal postmortem draft externally"),
    q("Regulatory Audit Production", "Compliance", "Common",
      "Prepare Azure production environment for SOC 2 Type II audit?",
      "Evidence: IAM access reviews, change management tickets, encryption configs, backup logs, vulnerability scans, incident PIRs, policy assignments, penetration test remediation.",
      "**Architect:** Traceability matrix control → Azure implementation → evidence artifact location.\n\n**Tools:** Microsoft Purview compliance manager, Defender for Cloud regulatory dashboard.",
      "Audit readiness is continuous not scramble.",
      "Auditor Azure access? — Read-only scoped RBAC not Owner.",
      "Gap remediation timeline? — Prioritize Critical before audit window.",
      "Scramble evidence week before audit",
      "No change management for prod",
      "Controls documented but not implemented"),
    q("Pen Test Remediation", "Security", "Common",
      "Prioritize penetration test findings for production Azure workload?",
      "Critical (exploit RCE/data breach) fix 7 days; High 30 days; Medium next quarter; Low backlog. Retest after Critical/High fix.",
      "**Common findings:** misconfigured storage public, excessive RBAC, missing WAF rules, SQL injection in custom code.\n\n**Architect:** Track in same system as prod defects — visible to leadership.",
      "Pen test without remediation is theater.",
      "Azure penetration testing rules? — Notify Microsoft for certain services — follow policy.",
      "Third-party vs internal? — External annual + internal continuous.",
      "Ignore Medium findings forever",
      "No retest verification",
      "Findings in PDF only not ticketed"),
    q("Backup Restore Drill", "DR", "Very Common",
      "Validate Azure Backup restore quarterly — procedure?",
      "Select random VM/SQL/file backup → restore to isolated network → verify data integrity app login → document RTO actual → delete restore resources.",
      "**SQL:** point-in-time restore to alternate server. **Architect:** Immutable backup vault protects against ransomware.",
      "Restore drill proves backup not just backup job success.",
      "Backup vault immutability? — Enable for prod vaults.",
      "Cross-region backup? — GRS vault for regional disaster.",
      "Backup succeeds restore never tested",
      "Restore over production database",
      "No isolated network for restore test"),
    q("Key Compromise Response", "Security", "Very Common",
      "Azure Storage account key leaked in GitHub — response?",
      "Rotate keys immediately (regenerate key2 then key1), audit access logs for abuse, migrate to managed identity, enable Key Vault references, scan repos for secrets, incident PIR.",
      "**Contain:** deny public access review; Defender alert. **Prevent:** GitHub secret scanning, no keys in appsettings in prod.\n\n**Architect:** Eliminate long-lived keys — RBAC + MI default pattern.",
      "Key compromise runbook is security architect must-know.",
      "Key Vault soft delete? — Protects against accidental/malicious delete during incident.",
      "Customer impact communication? — If data exfil suspected — legal/comms engaged.",
      "Only delete Git commit without rotation",
      "Shared key across environments",
      "No access log review after leak"),
    q("Certificate Expiry Monitoring", "Security", "Common",
      "Monitor TLS certificate expiry across App Service APIM Front Door?",
      "Key Vault cert lifetime alerts 30/14/7 days; App Service managed cert auto-renew track failures; Azure Monitor metric alerts; external synthetic check TLS handshake.",
      "**Architect:** Central inventory of all certs — custom domains easy to orphan. Automate renewal via ACME or Key Vault integration.",
      "Cert expiry outages are preventable — embarrassing prod incidents.",
      "Managed cert failure? — Alert on renewal failed state.",
      "Wildcard vs single? — Wildcard convenience vs blast radius if compromised.",
      "Calendar reminder only no automation",
      "Expired cert takes down checkout silently undetected",
      "Manual cert install on 40 App Services"),
    q("Dependency Mapping CMDB", "Operations", "Common",
      "Maintain service dependency map for Azure production CMDB?",
      "Map: app → APIM → backends → SQL/Cosmos/Service Bus/Key Vault/third-party SaaS. Tag resources in Azure Resource Graph; link to Service Map/App Insights application map.",
      "**Use:** impact analysis for changes and outages. **Architect:** Update on every architecture review — stale CMDB useless.",
      "Dependency map accelerates incident triage.",
      "App Insights app map? — Auto-discovered if instrumentation consistent.",
      "Third-party dependencies? — Include Stripe, SendGrid SLA in composite.",
      "No dependency map during change review",
      "CMDB spreadsheet never updated",
      "Missing messaging dependencies in map"),
    q("Architecture Decision Log Production", "Governance", "Very Common",
      "Maintain ADR log for production system — what belongs?",
      "ADRs for significant prod decisions: database choice, messaging product, auth model, multi-region strategy. Status: proposed/accepted/deprecated/superseded with date and consequences.",
      "**Location:** git `/docs/adr/` next to Bicep. **Review:** new ADR in PR template for architectural changes.\n\n**Architect:** ADR explains why — diagram shows what.",
      "Production ADRs prevent re-litigating settled decisions.",
      "ADR vs design doc? — ADR single decision; design doc full system.",
      "Supersede example? — App Service → AKS when scale threshold hit.",
      "Verbal decisions only",
      "ADR never updated when reversed",
      "No consequences section"),
    q("Technical Debt Budget", "Governance", "Common",
      "Allocate 20% sprint capacity to production technical debt — enforce how?",
      "Platform roadmap includes debt epics: upgrade .NET, retire flags, fix DLQ root causes, IaC drift. Track debt ratio in quarterly review; block all-feature sprints after outage from debt.",
      "**Architect:** Quantify debt impact — 'missing index costs $2K/month and 200ms p99'. Makes prioritization objective.",
      "Debt budget prevents slow production rot.",
      "Debt register? — Shared backlog tagged `tech-debt` visible to product.",
      "When defer debt? — Never entirely — minimum 10% even in crunch.",
      "Zero debt sprints until emergency rewrite",
      "Debt invisible to product owner",
      "No link debt to incidents"),
    q("Platform Team SLA", "Organization", "Common",
      "Define internal SLA platform team provides app teams?",
      "Examples: new subscription provisioned 2 business days; AKS cluster upgrade communicated 30 days ahead; break-fix P1 platform 1h response; golden path template updates monthly.",
      "**Measure:** ticket metrics, deployment frequency of platform modules.\n\n**Architect:** Platform SLA enables-label enables app team planning — not ad hoc Slack requests.",
      "Platform SLAs professionalize internal cloud enablement.",
      "X-as-a-service maturity? — Platform evolves from ticket to self-service portal.",
      "SLA breach escalation? — App team VP to platform lead.",
      "Platform team no published SLA",
      "Unlimited custom requests no queue",
      "Breaking change without notice window"),
    q("App Team Autonomy Guardrails", "Governance", "Common",
      "Balance app team autonomy with Azure guardrails?",
      "Autonomy: choose app architecture within approved services; deploy via pipeline. Guardrails: Azure Policy deny public IP, required tags, allowed SKUs, network hub-spoke, security baseline.",
      "**Exception process:** RFC to architecture board with time-bound exemption.\n\n**Architect:** Guardrails enable speed — teams don't fear breaking prod security.",
      "Autonomy + guardrails is enterprise platform pattern.",
      "Policy vs RBAC? — Policy restricts resource config; RBAC who can deploy.",
      "Self-service subscription vending? — Automated with policy inheritance.",
      "Central team approves every deploy",
      "No guardrails full Owner on prod sub",
      "Guardrails without exception path"),
    q("Golden Path Templates", "Platform", "Very Common",
      "Ship golden path Bicep template for standard .NET API on Azure?",
      "Template: App Service P1v3 + MI + Key Vault + App Insights + Service Bus queue + SQL private endpoint + CI/CD pipeline stub + monitoring dashboard + runbook links.",
      "**Documentation:** 'happy path' README — deviations need ADR. **Version:** semver template releases.\n\n**Architect:** Golden path covers 80% teams — not every edge case.",
      "Golden paths scale architect standards.",
      "Template vs module library? — Composable modules; golden path opinionated bundle.",
      "Adoption metric? — % new apps from template vs snowflake.",
      "Every team custom architecture snowflake",
      "Template outdated .NET 6 in 2026",
      "Golden path without security defaults"),
    q("Production Readiness Checklist", "Operations", "Very Common",
      "Production readiness review (PRR) checklist before go-live?",
      "HA validated, DR drill scheduled, monitoring/alerting complete, runbooks written, security scan passed, load test passed, FinOps budget set, on-call rotation staffed, rollback tested, docs updated.",
      "**Gate:** no go-live with open Critical PRR items. **Sign-off:** engineering + ops + security + product.\n\n**Architect:** PRR is quality gate — not checkbox theater if items verified.",
      "PRR prevents preventable launch disasters.",
      "PRR vs go/no-go? — PRR input to business go/no-go meeting.",
      "Hypercare planned? — Extended support post-launch in checklist.",
      "Go-live without load test",
      "Monitoring added after launch",
      "PRR signed without evidence"),
    q("Go-Live Criteria", "Operations", "Very Common",
      "Define objective go-live criteria for Azure platform migration?",
      "Cutover when: parallel run 2 weeks <0.1% variance, rollback tested <30m, all integrations verified, training complete, support staffed, exec sign-off, maintenance window communicated.",
      "**Rollback trigger:** error rate 2× baseline within 2h post-cutover.\n\n**Architect:** Criteria documented before project starts — prevents moving goalposts.",
      "Go-live criteria align business and technical readiness.",
      "Big bang vs phased? — Phased lower risk — criteria per phase.",
      "Data validation? — Reconciliation counts financial parity.",
      "Go-live on hope",
      "Rollback never tested",
      "Criteria changed day of cutover"),
    q("Hypercare Period", "Operations", "Common",
      "Plan 2-week hypercare after major Azure production launch?",
      "War room daily standup, extended on-call (24/7), senior engineers embedded, heightened monitoring dashboards, fast-track bug fixes, daily status to stakeholders, hypercare exit criteria defined.",
      "**Exit:** error rate normal 7 days, no Sev1/2, runbooks handed to BAU ops.\n\n**Architect:** Hypercare budgeted upfront — not volunteer overtime surprise.",
      "Hypercare bridges launch to steady-state ops.",
      "Hypercare team composition? — Build team + ops + product analyst.",
      "Deferred enhancements? — Log but don't destabilize during hypercare.",
      "Launch Friday no hypercare",
      "Same on-call intensity forever post-launch",
      "No exit criteria from hypercare"),
    q("Handoff to Operations", "Operations", "Very Common",
      "Hand off new Azure service from project team to BAU operations?",
      "Deliver: runbooks, architecture diagrams, IaC repo access, monitoring dashboards, alert routing verified, on-call trained shadow shift, known issues list, SLAs documented, KT sessions recorded.",
      "**Acceptance:** ops sign-off checklist — won't accept without runbooks.\n\n**Architect:** Design for operability during build — not documentation scramble at end.",
      "Clean handoff defines project success beyond go-live.",
      "Shadow on-call? — Project engineer pairs one week before solo.",
      "Ops feedback loop? — Retro on handoff quality improve golden path.",
      "Throw over wall Friday evening",
      "No ops in PRR",
      "Runbooks written by dev who never ops"),
    q("Monitoring Coverage Review", "Observability", "Very Common",
      "Audit monitoring coverage for production Azure app?",
      "Checklist: golden signals all services, synthetic availability, dependency failures, business KPIs, Service Bus DLQ depth, SQL replica lag, cert expiry, quota usage — gaps prioritized.",
      "**Tooling:** Azure Monitor workbook inventory; alert rules tagged `prod`.\n\n**Architect:** Monitoring debt is technical debt — schedule quarterly coverage review.",
      "Coverage review finds blind spots before customers do.",
      "Service Level Indicators? — Map each SLI to metric source.",
      "Third-party SaaS monitoring? — Synthetic or webhook status integration.",
      "Monitor VM CPU only",
      "No alert on dependency failure",
      "Business KPIs absent from dashboards"),
    q("Alert Fatigue Reduction", "Observability", "Very Common",
      "Reduce alert fatigue — 200 alerts/week down to actionable set?",
      "Audit alerts: delete noisy, tune thresholds, composite alerts, SLO burn rate only pages, route info to ticket not page, dedupe, weekly alert review meeting.",
      "**Principle:** page human only when immediate action required.\n\n**Architect:** Every alert links runbook — if no runbook, maybe shouldn't alert.",
      "Alert hygiene is operational excellence pillar.",
      "Action groups? — Separate email vs SMS vs PagerDuty severity.",
      "Alert on missing data? — Critical metrics treat no-data as breach.",
      "Page on CPU 60%",
      "200 alerts nobody reads",
      "Same alert fires every 5 min all night"),
    q("Executive Dashboards", "Observability", "Common",
      "Build executive Azure dashboard for CTO — what metrics?",
      "Availability SLO trend, error budget remaining, monthly Azure spend vs budget, deployment frequency, open Critical vulnerabilities, major incident count, customer-facing latency p95.",
      "**Avoid:** raw CPU graphs — executives need business-aligned KPIs.\n\n**Architect:** Workbook shared read-only; auto-refresh weekly email snapshot.",
      "Executive dashboards translate ops to business language.",
      "Power BI vs Monitor workbook? — Power BI for cross-cloud finance merge.",
      "Drill-down path? — Exec dashboard links to ops detail.",
      "Executive dashboard 50 technical graphs",
      "No financial view",
      "Stale manual PowerPoint monthly"),
    q("Tenant Isolation Production SaaS", "Architecture", "Very Common",
      "Multi-tenant SaaS isolation strategies on Azure?",
      "Pool: shared DB tenantId column + RLS. Silo: database per tenant Premium tier. Hybrid: pool default, silo enterprise. Network: separate subscriptions for largest tenants.",
      "**Security:** always filter by tenantId in code + DB RLS defense in depth. **Compliance:** silo for data residency requirements.\n\n**Architect:** Isolation model drives cost model — document in ADR.",
      "Tenant isolation is SaaS architect core decision.",
      "Cosmos partition key tenantId? — Natural isolation boundary.",
      "Cross-tenant leak test? — Automated security test in CI.",
      "TenantId optional query filter",
      "Shared Key Vault secrets all tenants",
      "No isolation testing"),
    q("Multi-Tenant Noisy Neighbor", "Performance", "Very Common",
      "Large tenant batch job degrades others — mitigation?",
      "Rate limit per tenant APIM; separate Service Bus queue for bulk vs interactive; compute quota per tenant; autoscale dedicated workers for premium tier; circuit breaker on shared SQL pool DTU exhaustion.",
      "**Detection:** per-tenant metrics dashboards; anomaly on one tenant CPU/queue depth.\n\n**Architect:** Fair scheduling — premium tenants get silo or reserved capacity.",
      "Noisy neighbor handling separates SaaS maturity levels.",
      "Elastic pool vs single DB? — Pool shares DTU — noisy neighbor risk.",
      "Bulkhead pattern? — Separate thread pools/queues per tenant class.",
      "Unlimited batch for any tenant",
      "No per-tenant rate limits",
      "Single shared queue all priorities"),
    q("Performance Baseline", "Performance", "Common",
      "Establish production performance baseline post-launch?",
      "Capture 30 days normal traffic: p50/p95/p99 latency per endpoint, SQL query durations, Service Bus processing time, error rates — store in workbook; alert when 2× baseline deviation.",
      "**Use:** capacity planning, regression detection after releases.\n\n**Architect:** Baseline during representative load — not holiday peak as normal.",
      "Baseline enables meaningful regression alerts.",
      "Continuous baseline update? — Rolling 30-day window adapts seasonality.",
      "Load test baseline vs prod? — Prod baseline authoritative; load test validates headroom.",
      "No baseline alert on 3× latency",
      "Baseline from dev environment",
      "One-time baseline never updated"),
    q("Continuous Improvement WAF", "Process", "Very Common",
      "Institutionalize WAF continuous improvement for production?",
      "Quarterly WAF assessment per workload pillar score 1-5; improvement backlog; link incidents to pillar gaps; Azure Advisor + WAF review; annual compare scores trend.",
      "**Architect:** WAF not one-time launch review — living discipline tied to OKRs.",
      "Continuous WAF closes architect learning loop.",
      "WAF assessment tool? — Microsoft WAF self-assessment checklist.",
      "Pillar trade-off example? — Cost vs reliability reserved capacity decision.",
      "WAF review once at launch only",
      "Scores without improvement plan",
      "Ignore Advisor recommendations systematically"),
]

ALL_AZURE_Q011_Q050_W15_W16 = {
    15: WEEK_15_Q011_Q050,
    16: WEEK_16_Q011_Q050,
}
