"""Hand-crafted premium Q011–Q050 for Azure weeks 9–10."""

from premium_qa_data import q

WEEK_9_Q011_Q050 = [
    q("Azure Resource Manager", "Governance", "Very Common",
      "What is Azure Resource Manager and why is it central to Azure architecture?",
      "ARM is the deployment and management layer for Azure — every resource lives in a resource group, is deployed via ARM templates/Bicep, and is governed through RBAC, Policy, and tags at defined scopes.",
      "Azure Resource Manager (ARM) is the **control plane API** behind every Azure portal click, CLI command, and IaC deployment. It provides:\n\n1. **Consistent resource model** — resources belong to resource groups, subscriptions, and management groups\n2. **Declarative deployment** — Bicep/ARM templates define desired state; ARM reconciles\n3. **RBAC and Policy enforcement** at scope hierarchy\n4. **Idempotent operations** — redeploy same template safely\n\n**Architect workflow:** Design landing zones as ARM/Bicep modules. Never create production resources manually in portal — drift and audit gaps follow.\n\n**Example:** A `Microsoft.Web/sites` resource deploys through ARM with dependencies on App Service Plan and Log Analytics diagnostic settings defined in template.",
      "ARM literacy separates architects who govern estates from those who click-deploy single apps.",
      "ARM vs classic Azure Service Manager? — ASM is legacy; all new workloads use ARM.",
      "Resource provider registration? — Some services require `Microsoft.*` provider registered per subscription before deploy.",
      "Confusing resource group with subscription boundary",
      "Manual portal changes without IaC backfill",
      "Ignoring ARM deployment dependencies and ordering"),
    q("Resource Locks", "Governance", "Very Common",
      "When and how do you use Azure resource locks in production?",
      "CanNotDelete locks on production resource groups and critical shared resources; ReadOnly for audit-only assets. Locks override RBAC — even Owner cannot delete without removing lock.",
      "**Lock types:**\n- **CanNotDelete** — modify allowed, delete blocked — default for prod RGs\n- **ReadOnly** — no modifications — compliance archives, golden images\n\n**Architect patterns:**\n- Lock hub VNet, firewall, Log Analytics workspace at platform subscription\n- Lock production SQL server (not individual DB if team needs schema deploy)\n- Document lock removal in change management\n\n**Gotcha:** Locks don't prevent data operations inside resources (SQL DELETE rows still works). Combine with RBAC and Policy.\n\n**Break-glass:** Platform admin role can remove locks — audit Activity Log for lock changes.",
      "Locks are cheap insurance against accidental deletion during incidents or mis-clicks.",
      "Lock at MG vs RG scope? — RG-level typical; subscription lock rare and heavy-handed.",
      "Locks vs Policy deny delete? — Lock is simpler; Policy can enforce org-wide deny delete on tagged prod.",
      "No locks on shared platform resources",
      "ReadOnly lock blocking legitimate deployments",
      "Assuming lock prevents data deletion inside SQL"),
    q("Deployment Stacks", "IaC", "Common",
      "What are Azure deployment stacks and when use them over standard deployments?",
      "Deployment stacks manage a set of resources as a unit with deny-delete/modify actions on managed resources — ideal for platform team baseline deployments that must not be drifted.",
      "**Standard Bicep deploy:** Resources created but users can modify/delete outside template.\n\n**Deployment stack:** ARM tracks managed resources; optional **denyDelete** or **denyModify** actions prevent drift. Deleting stack can delete all managed resources (configurable).\n\n**Use cases:**\n- Platform baseline (diagnostic settings, Defender plans)\n- Shared monitoring agents\n- Landing zone components owned by central team\n\n**Architect:** Stacks complement Policy — stacks protect specific deployments; Policy governs entire subscription. Not replacement for full IaC pipeline.",
      "Stacks solve 'someone deleted our monitoring config' drift problem.",
      "Stack vs Blueprint? — Blueprints deprecated; stacks + template specs + ALZ are current pattern.",
      "Stack delete behavior? — Configure deleteResources: detach vs delete — critical for prod.",
      "Using stacks for every app deploy — overkill",
      "denyModify blocking app team legitimate changes",
      "No stack versioning in pipeline"),
    q("Activity Log vs Diagnostic Logs", "Observability", "Very Common",
      "Difference between Azure Activity Log and Diagnostic logs?",
      "Activity Log = control plane operations (who created VM, changed NSG). Diagnostic logs = data plane telemetry from resources (App Service HTTP logs, SQL audit).",
      "**Activity Log (Subscription level):**\n- Administrative operations: create, update, delete resources\n- Service health notifications\n- Retention ~90 days default — export to Log Analytics for longer\n\n**Diagnostic Settings (Resource level):**\n- Resource-specific metrics and logs\n- App Service: AppServiceHTTPLogs, ConsoleLogs\n- SQL: SQLSecurityAuditEvents\n- Sent to Log Analytics, Storage, or Event Hub\n\n**Architect:** SOC 2 requires both — Activity Log for change audit; Diagnostic for workload forensics. Centralize in shared Log Analytics with RBAC separation.",
      "Confusing the two is a common observability interview failure.",
      "Azure Monitor Activity Log vs Entra sign-in logs? — Entra logs are identity plane — separate diagnostic setting on Entra.",
      "Retention strategy? — Activity Log 90 days insufficient — export day one.",
      "Only Activity Log, no resource diagnostics",
      "Diagnostic logs without Log Analytics centralization",
      "No alert on Activity Log delete operations"),
    q("Azure Advisor", "Operations", "Very Common",
      "How do architects use Azure Advisor at enterprise scale?",
      "Advisor aggregates recommendations across cost, security, reliability, performance, and operational excellence — review weekly at platform level, monthly with app owners for remediation prioritization.",
      "**Recommendation categories map to WAF pillars.**\n\n**Enterprise workflow:**\n1. Export Advisor score to Power BI / Azure Workbooks\n2. Assign recommendations to owners via tagging\n3. Policy can auto-remediate some (e.g., enable MFA)\n4. Track suppression with documented justification\n\n**Architect:** Don't treat Advisor as optional — it's free continuous review. Integrate high-severity security recs into architecture review gate.",
      "Advisor demonstrates operational maturity beyond initial design.",
      "Advisor vs Defender for Cloud recommendations? — Overlap on security; Defender deeper CSPM; dedupe in reporting.",
      "Suppress vs fix? — Suppress with expiry and reason — not permanent ignore.",
      "Never reviewing Advisor recommendations",
      "Fixing cost recs before security recs without prioritization",
      "No ownership assignment for recommendations"),
    q("Service Health vs Resource Health", "Reliability", "Common",
      "Explain Azure Service Health vs Resource Health for incident response.",
      "Service Health = Azure platform events affecting regions/services (outages, maintenance). Resource Health = health of YOUR specific resource instance and remediation steps.",
      "**Service Health:**\n- Azure-wide or region-specific incidents\n- Planned maintenance notifications\n- Health history and root cause summaries\n- Configure Action Groups for alerts\n\n**Resource Health:**\n- Per-resource availability status\n- 'Unavailable — platform issue' vs 'user configuration issue'\n- Suggested remediation (restart, redeploy)\n\n**Architect runbook:** On alert, check Service Health first — if platform incident, don't fail over unnecessarily. Resource Health for single-resource degradation.",
      "Distinguishing platform vs workload issues speeds incident triage.",
      "Service Health API for automation? — Yes — integrate with status page and ITSM.",
      "Resource Health for App Service? — Shows if instance unhealthy — triggers autoscale/restart.",
      "Debugging app code when Service Health shows region outage",
      "No Service Health alert subscriptions",
      "Ignoring planned maintenance windows"),
    q("Azure Monitor Metrics vs Logs", "Observability", "Very Common",
      "When use Azure Monitor metrics vs logs for alerting and dashboards?",
      "Metrics: numeric time-series, low latency, cheap — CPU, request count, queue depth. Logs: rich text/structured events — queries, joins, forensics. Alert on metrics for SLOs; investigate with logs.",
      "**Metrics:**\n- Pre-aggregated, 90-day retention (extendable)\n- Near real-time alerting\n- Metric alerts, autoscale triggers\n\n**Logs (Log Analytics):**\n- KQL queries across tables\n- Cross-resource correlation\n- Long retention for compliance\n\n**Architect pattern:** Metric alert fires → runbook queries logs for root cause. Example: CPU metric alert → AppTraces KQL for slow dependency.\n\n**Cost:** Log ingestion expensive at volume — sample verbose logs; use metrics for high-cardinality counters.",
      "Metrics vs logs trade-off is foundational observability design.",
      "Platform metrics vs guest OS metrics? — Enable Diagnostic Settings for guest metrics on VMs.",
      "Logs to metrics? — Log-based metrics for custom KPIs from KQL.",
      "Alerting only on log queries for high-frequency signals",
      "No metric baseline before setting thresholds",
      "Ingesting all verbose logs unfiltered"),
    q("Log Analytics Workspace Design", "Observability", "Very Common",
      "Design Log Analytics workspace strategy for 20 subscriptions.",
      "Central workspace per environment (prod/nonprod) in platform subscription; regional workspaces only if data residency requires; use Azure Monitor Agent; RBAC at workspace level.",
      "**Patterns:**\n1. **Single prod workspace** — simplest queries, cross-subscription dashboards\n2. **Workspace per region** — data residency (EU vs US)\n3. **Dedicated security workspace** — SOC access only\n\n**Architect decisions:**\n- Daily cap and alert on ingestion spike\n- Retention: 90 default, 365+ for compliance tables\n- Data collection rules (DCR) for AMA filtering\n\n**Anti-pattern:** Workspace per app — query fragmentation and cost duplication.",
      "Workspace topology affects query, cost, and compliance for years.",
      "Commitment tier pricing? — Reserve ingestion capacity for predictable volume.",
      "Cross-workspace queries? — `union` in KQL or Azure Monitor multi-workspace.",
      "One workspace per microservice",
      "No ingestion cap on nonprod",
      "Classic Log Analytics agents on new deployments"),
    q("Naming Conventions", "Governance", "Very Common",
      "Define Azure naming convention for resources across landing zone.",
      "Pattern: `{resource-type}-{workload}-{environment}-{region}-{instance}` e.g. `app-orders-prod-eus-01`. Document in CAF naming guide; enforce via Policy where possible.",
      "**Components:**\n- **Resource type abbreviation** — `vnet`, `kv`, `asp`, `sql` (from CAF abbreviations)\n- **Workload/application** — business identifier\n- **Environment** — prod, stg, dev, sbx\n- **Region** — eus, weu (short code)\n- **Instance** — 01, 02 for scale-out\n\n**Architect:** Naming enables automation, cost allocation, and on-call routing. Global uniqueness required for some types (Storage, Key Vault).\n\n**Policy:** Audit naming with regex; deny for critical types (Key Vault, Storage).",
      "Naming conventions are day-one decisions — renaming Key Vault is painful.",
      "Azure naming tool? — Microsoft CAF naming convention reference.",
      "Tags vs naming? — Naming for uniqueness and automation; tags for metadata.",
      "Random portal-generated names in production",
      "No documented standard across teams",
      "Names exceeding length limits for Storage accounts"),
    q("Capacity Reservations", "FinOps", "Common",
      "When use Azure capacity reservations vs savings plans vs reserved instances?",
      "Capacity reservations guarantee compute capacity in a region/AZ without payment discount — use when SLA requires capacity during shortages. RIs/Savings Plans for cost discount on usage.",
      "**Capacity Reservation:**\n- Reserve VM or AKS node capacity in advance\n- No cost discount — pay for reserved capacity whether used or not\n- Combine with RI for discount + capacity guarantee\n\n**Use when:** Large VM SKUs scarce in region, critical workloads during peak provisioning, AKS node pool scale events.\n\n**Architect:** Capacity reservation is reliability play; Savings Plan/RI is FinOps play. Document in DR plan if reserved capacity is region-specific.",
      "Capacity reservation vs reservation discount confuses many candidates.",
      "On-demand capacity reservation? — Azure Capacity Reservation for VMs — check current SKU support.",
      "Zonal vs regional reservation? — Zonal ties to specific AZ for HA clusters.",
      "Buying capacity reservation expecting cost savings",
      "No monitoring of unused reserved capacity",
      "Capacity reservation in wrong region for DR failover"),
    q("Azure Compliance Offerings", "Compliance", "Very Common",
      "Map Azure compliance offerings to SOC 2 and ISO 27001 customer requirements.",
      "Azure maintains certifications (SOC 1/2/3, ISO 27001, PCI DSS) at platform level — customers inherit for IaaS/PaaS controls; must implement workload controls (access, encryption, logging) for shared responsibility.",
      "**Inherited from Microsoft:** Physical datacenter security, hypervisor, platform patching for PaaS.\n\n**Customer responsibility:** Data classification, RBAC, network rules, application security, backup testing.\n\n**Tools:**\n- **Microsoft Purview Compliance Manager** — track control implementation\n- **Azure Policy** regulatory compliance dashboard\n- **Defender for Cloud** regulatory standards\n\n**Architect deliverable:** Compliance matrix mapping each control to Azure service + evidence source (Policy compliance, Activity Log, Defender score).",
      "Compliance interviews require shared responsibility clarity — not 'Azure is certified so we are.'",
      "SOC 2 Type I vs II? — Type II over period — customer audit often requires Type II evidence.",
      "Azure Government for FedRAMP? — Separate cloud for US government workloads.",
      "Claiming Azure cert covers application code vulnerabilities",
      "No customer control evidence collection",
      "Compliance as one-time checkbox not continuous Policy monitoring"),
    q("Data Residency", "Compliance", "Very Common",
      "Design Azure architecture for EU data residency requirements.",
      "Deploy workloads in EU regions only; Policy deny non-EU regions; use EU Data Boundary where applicable; Private Link keeps traffic in-region; document subprocessors and replication paths.",
      "**Controls:**\n1. **Allowed locations Policy** — deny deploy outside `westeurope`, `northeurope`\n2. **Geo-redundant storage** — GRS replicates to paired region (still EU pair)\n3. **SQL geo-replication** — verify secondary region acceptable\n4. **Log Analytics** — workspace in EU;  \n5. **Microsoft 365 / Entra** — EU Data Boundary for tenant data\n\n**Architect:** Data residency ≠ data sovereignty. Sovereign clouds (e.g., Azure Government) for stricter requirements.\n\n**Contract review:** AI services may process data in other regions — disclose Copilot/OpenAI routing.",
      "Data residency is legal + technical — architects document data flows.",
      "Multi-region CDN impact? — Static assets may cache globally — use CDN rules or avoid for strict residency.",
      "Backup vault region? — Backup data stays in chosen region — verify cross-region backup settings.",
      "Using US-only regions for EU customer data",
      "GRS without legal review of paired region",
      "No Policy enforcement on region selection"),
    q("Shared Responsibility Model", "Security", "Very Common",
      "Explain shared responsibility model for Azure App Service vs IaaS VM.",
      "App Service: Microsoft manages OS, runtime patching, physical security; customer manages app code, auth, connection strings, network integration config. IaaS VM: customer manages OS patching, antivirus, app — more control, more burden.",
      "**Responsibility spectrum:**\n```\nSaaS ──► PaaS ──► IaaS ──► On-prem\n(Microsoft owns more)     (Customer owns more)\n```\n\n**App Service customer owns:**\n- Application vulnerabilities (SQL injection, auth bugs)\n- Managed identity and Key Vault integration\n- VNet integration and private endpoints\n- Deployment pipeline security\n\n**VM customer additionally owns:**\n- OS patching, firewall on VM, disk encryption config\n\n**Architect:** Choose PaaS to shift ops burden; document residual responsibilities in security architecture.",
      "Shared responsibility is table stakes for cloud architect credibility.",
      "PaaS means no security work? — Common fatal interview mistake.",
      "Container Apps shared model? — Similar PaaS — customer secures container image and config.",
      "Assuming Microsoft patches application code",
      "IaaS without patch management process",
      "No distinction between models in security docs"),
    q("SLA Aggregation Math", "Reliability", "Common",
      "Calculate composite SLA for API depending on App Service and SQL Database.",
      "Composite SLA = product of component SLAs. App Service 99.95% × SQL 99.99% ≈ 99.94%. Add Front Door, Redis, etc. — chain weakest links.",
      "**Formula:** `SLA_composite = SLA1 × SLA2 × ... × SLAn`\n\n**Example:**\n- App Service Standard: 99.95% (21.9 min/month max downtime)\n- Azure SQL: 99.99% (4.3 min/month)\n- Combined: 0.9995 × 0.9999 = 0.9994 → **99.94%**\n\n**Architect:** Multi-region active-active improves beyond single-region SLA math. Document SLA budget per dependency — third-party SaaS often 99.9% drags composite down.\n\n**N+1:** SLA math is theoretical — design for failure with retries, circuit breakers, caching.",
      "SLA multiplication surprises stakeholders — architects quantify uptime honestly.",
      "SLA credits vs architecture? — Credits don't replace revenue loss — design for HA.",
      "Zone redundancy SLA impact? — Zone-redundant SKUs often higher SLA — use published figures.",
      "Adding SLAs instead of multiplying",
      "Ignoring dependencies in SLA calculation",
      "Promising 99.99% on single-region single-instance design"),
    q("Platform vs Workload RACI", "Governance", "Common",
      "Define RACI between platform team and application team in landing zone model.",
      "Platform **Accountable** for hub network, firewall, identity baseline, Policy, central monitoring. Application team **Accountable** for app architecture, data, deployments within guardrails. Both **Consulted** on security exceptions.",
      "**RACI example:**\n| Activity | Platform | App Team |\n|----------|----------|----------|\n| Hub VNet / Firewall | A/R | C |\n| Spoke subscription | R | A |\n| App Service deploy | C | A/R |\n| Azure Policy baseline | A/R | I |\n| Incident P1 platform | A/R | C |\n| App bug fix | I | A/R |\n\n**Architect:** Publish RACI in Cloud Center of Excellence docs — reduces turf wars during incidents.",
      "RACI clarity prevents 'not my job' during outages.",
      "RACI vs operating model? — RACI is who; operating model is how (ticket queues, SLAs).",
      "Third-party MSP in RACI? — Define R for managed services explicitly.",
      "Platform team deploying application code",
      "App team opening NSG rules on hub firewall without process",
      "No documented RACI — verbal agreements only"),
    q("Cloud Center of Excellence", "Governance", "Common",
      "What is a Cloud Center of Excellence (CCoE) and what should it deliver?",
      "CCoE is a cross-functional team (architecture, security, FinOps, ops) establishing standards, guardrails, training, and self-service enablement — not a bottleneck approval committee.",
      "**Deliverables:**\n- Landing zone and IaC templates\n- Approved service catalog and architecture patterns\n- FinOps reporting and tagging standards\n- Office hours and migration playbooks\n- Architecture review board with SLAs\n\n**Architect role:** Often leads or sits in CCoE — balances innovation vs risk.\n\n**Anti-pattern:** CCoE as gatekeeper with 6-week ticket queues — drives shadow IT.",
      "CCoE shows enterprise cloud maturity beyond individual projects.",
      "CCoE vs platform engineering? — Overlap; platform eng builds; CCoE governs and enables.",
      "Measure CCoE success? — Time-to-production, policy compliance %, cloud spend variance.",
      "CCoE blocks all deploys centrally",
      "No self-service templates — every request custom",
      "CCoE without business stakeholder representation"),
    q("Sandbox Subscriptions", "Governance", "Common",
      "Design sandbox subscription strategy for developer experimentation.",
      "Dedicated sandbox MG with Policy (allowed SKUs, deny prod regions, cost caps), auto-expiring resources, no production data, separate from prod billing — developers Contributor on their sandbox sub only.",
      "**Controls:**\n- Budget alert at $100/month per sandbox\n- Policy: deny creation of ExpressRoute, expensive GPU VMs\n- Mandatory `Environment=sandbox` tag\n- Monthly cleanup automation (delete untagged resources)\n\n**Architect:** Sandboxes accelerate learning without risking prod Policy inheritance mistakes. Separate Entra group `Azure-Sandbox-Users`.",
      "Sandbox strategy prevents 'experiment in prod subscription' anti-pattern.",
      "Sandbox vs dev subscription? — Dev is for integrated team workloads; sandbox is individual throwaway.",
      "Azure Lab Services vs sandbox sub? — Lab Services for training classes; sandbox for architect/engineer R&D.",
      "Developers Contributor on production subscription",
      "Sandbox without budget alerts",
      "Production secrets copied to sandbox"),
    q("DevTest Pricing", "FinOps", "Common",
      "How does Azure DevTest subscription pricing benefit architecture planning?",
      "Visual Studio/DevTest subscriptions offer reduced rates on Windows VMs and select services for non-production — architect routes dev/test workloads to eligible subscriptions saving 15-40% on compute.",
      "**Eligible:** Development and test workloads only — not production. Windows client VMs for testing, reduced compute rates.\n\n**Architect planning:**\n- Map environments: prod (full price), staging (DevTest if no SLA need), dev (DevTest)\n- Combine with auto-shutdown schedules\n- Policy deny prod tags in DevTest subscriptions\n\n**Compliance:** Microsoft audits misuse — production traffic on DevTest violates terms.",
      "FinOps-aware architects route nonprod to DevTest automatically.",
      "DevTest vs CSP dev/test offer? — Different programs — verify eligibility with EA/MCA.",
      "Hybrid Benefit in DevTest? — Can stack with AHUB for Windows Server licensing savings.",
      "Production APIs on DevTest subscription",
      "No separation between DevTest and prod subscriptions",
      "Assuming all Azure services discounted in DevTest"),
    q("Azure Lighthouse", "Governance", "Common",
      "Explain Azure Lighthouse for MSP and enterprise central management.",
      "Lighthouse enables cross-tenant management — MSP or central IT manages customer/child tenant subscriptions with delegated RBAC without guest accounts, maintaining audit trail in managing tenant.",
      "**Use cases:**\n- MSP monitoring and patching customer estates\n- Enterprise managing acquired company tenants\n- Central SOC viewing Defender alerts across tenants\n\n**Architect:** Define least-privilege delegated roles (e.g., Reader + specific Defender roles). Customer retains Owner; can remove delegation anytime.\n\n**vs Guest users:** Lighthouse scales better — no B2B guest sprawl, unified automation from managing tenant.",
      "Lighthouse is standard for multi-tenant Azure management architecture.",
      "Lighthouse vs Azure Arc? — Lighthouse for Azure tenant delegation; Arc for hybrid/on-prem resources.",
      "Policy via Lighthouse? — Deploy policies from managing tenant to delegated subscriptions.",
      "Guest Owner accounts in every customer tenant",
      "Over-privileged MSP Contributor delegation",
      "No customer audit of delegated actions"),
    q("Enterprise Agreement Hierarchy", "FinOps", "Common",
      "Describe Enterprise Agreement (EA) billing hierarchy impact on subscription design.",
      "EA: Enrollment → Departments → Accounts → Subscriptions. Billing rolls up to enrollment; architects align subscription boundaries with department chargeback and quota allocation.",
      "**Hierarchy:**\n```\nEnrollment (company)\n└── Department (cost center / division)\n    └── Account (owner / invoice section)\n        └── Subscription (technical boundary)\n```\n\n**Architect considerations:**\n- Subscription quota and ARM limits per subscription\n- Chargeback reports map Department → tags/CostCenter\n- MCA migration changing hierarchy — plan transition\n\n**Not technical but drives:** How many subscriptions, who approves new subs, budget ownership.",
      "Billing hierarchy influences subscription vending and FinOps reporting.",
      "EA vs MCA? — Modern Commerce Agreement replacing EA — similar concepts, different portal.",
      "Enterprise dev/test offer? — Separate enrollment pricing for nonprod.",
      "One subscription for entire enterprise",
      "Ignoring department chargeback in subscription layout",
      "No quota planning per enrollment"),
    q("Management Group Inheritance", "Governance", "Very Common",
      "How do Policy and RBAC inherit through management group hierarchy?",
      "Assignments at parent MG flow to all child MGs and subscriptions — explicit deny at child doesn't override parent allow unless using exemption. Design hierarchy top-down: root policies for baseline, child overrides sparingly.",
      "**Inheritance rules:**\n- Policy assignment at `Application-Prod` MG applies to all prod subscriptions beneath\n- RBAC at MG grants access to all contained subscriptions\n- **Deny assignments** block even Owner — separate from Policy\n\n**Architect pattern:**\n```\nRoot: Require tags, allowed locations\n├── Platform MG: network policies\n└── Application MG\n    ├── Prod: deny public IP, require encryption\n    └── NonProd: relaxed SKUs\n```\n\nDocument exceptions with Policy exemption TTL and approval workflow.",
      "MG inheritance is core landing zone governance — wrong hierarchy is expensive to fix.",
      "MG depth limits? — Up to 6 levels — keep shallow for clarity.",
      "Subscription move between MGs? — Policies re-evaluate — test before move.",
      "Policies assigned only at subscription level at scale",
      "Conflicting policies at sibling MGs without documentation",
      "No exemption workflow — permanent Policy overrides"),
    q("Deny Assignments", "Security", "Very Common",
      "What are Azure deny assignments and when use them?",
      "Deny assignments block actions even for Owner — used by Azure Blueprints (legacy), managed apps, and platform teams to protect critical resources from any deletion or modification.",
      "**Unlike Policy Deny:** Deny assignment is RBAC-layer block — applies regardless of role including Owner (except break-glass with specific exclusion).\n\n**Use cases:**\n- Protect management group structure\n- Managed application resources\n- Recovery Services vault immutability scenarios\n\n**Architect:** Rare for app teams to create — platform team applies to hub resources. Combine with CanNotDelete locks for defense in depth.\n\n**Audit:** Activity Log shows denied operations with deny assignment ID.",
      "Deny assignments are strongest Azure control short of subscription lock.",
      "Deny assignment vs Policy deny? — Deny assignment overrides RBAC; Policy evaluates at deploy/config time.",
      "Who can create deny assignments? — Only specific roles like User Access Administrator with constraints.",
      "Relying on Owner discipline alone for critical resources",
      "Deny assignment blocking legitimate emergency changes without process",
      "No break-glass exclusion documented"),
    q("Resource Graph", "Governance", "Very Common",
      "Use Azure Resource Graph for governance at scale — example queries?",
      "Resource Graph indexes ARM resources cross-subscription — query with KQL-like language for inventory, compliance drift, untagged resources, public endpoints.",
      "**Example queries:**\n```kusto\nResources\n| where type == 'microsoft.web/sites'\n| where properties.publicNetworkAccess == 'Enabled'\n\nResources\n| where tags['Environment'] == '' or isnull(tags['Environment'])\n```\n\n**Architect use cases:**\n- Weekly compliance report (public storage accounts)\n- Pre-migration inventory\n- Cost anomaly investigation (count VMs by SKU)\n\nIntegrate with Azure Automation, Logic Apps, or GitHub Actions for scheduled governance scans.",
      "Resource Graph is architect's SQL for entire Azure estate.",
      "Resource Graph vs Log Analytics? — Resource Graph = current state inventory; Log Analytics = time-series events.",
      "ARG API pagination? — Use `skipToken` for large estates in automation.",
      "Manual portal inventory per subscription",
      "No scheduled compliance queries",
      "Ignoring ARG for pre-Policy audit baseline"),
    q("KQL for Governance", "Observability", "Common",
      "Write KQL patterns for governance monitoring in Log Analytics.",
      "Query Activity Log tables for unauthorized changes, Policy non-compliance, sign-in anomalies — centralize governance signals in workbooks.",
      "**Patterns:**\n```kusto\nAzureActivity\n| where OperationNameValue has 'delete'\n| where ActivityStatusValue == 'Success'\n| summarize count() by Caller, ResourceGroup\n\nPolicyState\n| where ComplianceState == 'NonCompliant'\n| summarize by PolicyAssignmentName\n```\n\n**Architect:** Build governance workbook: failed deployments, Policy drift, RBAC changes, Key Vault access anomalies. Alert on `Add Member to Owner` role assignments.",
      "KQL connects audit logs to actionable governance alerts.",
      "KQL vs Resource Graph query language? — Different syntax and data sources — both needed.",
      "Retention for AzureActivity table? — Match compliance — archive to Storage if >2 years.",
      "No alerts on privileged role assignments",
      "Governance queries never scheduled",
      "Copy-paste KQL without understanding table schema"),
    q("Microsoft Purview", "Data Governance", "Common",
      "Role of Microsoft Purview in Azure data architecture?",
      "Purview provides data catalog, lineage, classification, and compliance mapping across Azure, on-prem, and multi-cloud — architects use it for sensitive data discovery and policy enforcement integration.",
      "**Capabilities:**\n- Automated scanning (SQL, Storage, Synapse, Power BI)\n- Classification labels (PII, financial)\n- Data lineage for impact analysis\n- Compliance Manager integration\n\n**Architect workflow:** Register data sources → scan → apply sensitivity labels → integrate with Defender for Cloud and DLP policies.\n\n**Not a database** — metadata layer; plan scan schedules to avoid production load impact.",
      "Purview answers 'where is our customer PII across Azure?'",
      "Purview vs Azure Policy? — Purview data governance; Policy infrastructure compliance.",
      "Purview governance vs catalog? — Unified platform — catalog is consumer-facing discovery.",
      "No data classification in regulated workloads",
      "Scanning prod without performance window",
      "Purview deployed without owner stewardship model"),
    q("Carbon Optimization", "Sustainability", "Common",
      "How do architects incorporate carbon optimization in Azure design?",
      "Use Carbon Optimization in Emissions Impact Dashboard, prefer region with lower carbon intensity when latency allows, right-size compute, serverless/scale-to-zero, schedule dev shutdown, and track emissions KPI alongside cost.",
      "**Tactics:**\n- **Region selection** — Nordic regions often lower carbon grid\n- **Right-sizing** — Advisor + idle resource elimination\n- **PaaS over IaaS** — shared infrastructure efficiency\n- **Reserved capacity** — higher utilization of physical hardware\n\n**Architect:** Sustainability pillar in WAF reviews — document trade-offs when lowest-carbon region conflicts with latency SLA.\n\n**Reporting:** Export Azure emissions data for ESG reporting.",
      "Carbon awareness is increasingly asked in enterprise architect interviews.",
      "Carbon proxy metric? — vCore-hours and storage GB-months correlate with emissions.",
      "Azure sustainability calculator? — Estimate before migrate.",
      "Ignoring region carbon when latency SLA allows flexibility",
      "Oversized always-on dev environments",
      "Sustainability never mentioned in architecture review"),
    q("Architecture Review Cadence", "Governance", "Common",
      "Establish architecture review cadence for growing Azure estate.",
      "Tiered reviews: lightweight ADR for team decisions; formal review board for new services, cross-subscription changes, and security exceptions; quarterly estate health review.",
      "**Cadence:**\n| Trigger | Review type | SLA |\n|---------|-------------|-----|\n| New Azure service adoption | Full board | 2 weeks |\n| Standard pattern deploy | Self-service + ADR | Async |\n| Policy exception | Security + architect | 1 week |\n| Quarterly | Estate WAF assessment | Scheduled |\n\n**Architect:** Publish decision log — searchable ADRs prevent re-litigating same choices.\n\n**Inputs:** Threat model, cost estimate, SLA impact, operational runbook draft.",
      "Review cadence balances agility with governance at scale.",
      "ADR format? — Context, decision, consequences, status — store in repo.",
      "Review board size? — 5-7 voting members — avoid too large for decisions.",
      "No review for new Azure service adoption",
      "Reviews as rubber stamp without threat modeling",
      "Decisions verbal only — no ADR trail"),
    q("Azure Migrate", "Migration", "Very Common",
      "Azure Migrate assessment workflow for datacenter to Azure migration?",
      "Discover on-prem with appliance → assess readiness/ sizing/ cost/ dependencies → migrate in waves via server replication or modernize to PaaS.",
      "**Phases:**\n1. **Discover** — Azure Migrate appliance, agentless VMware/Hyper-V\n2. **Assess** — Azure readiness, right-size SKU, monthly cost estimate, dependency mapping\n3. **Migrate** — Agent-based replication for lift-shift; refactor path documented separately\n\n**Architect:** Use dependency data for wave planning — migrate leaf apps before core databases.\n\n**Modernize decision:** IIS app → assess for App Service compatibility before defaulting to VM.",
      "Azure Migrate is standard enterprise migration entry point.",
      "Migrate vs Modernize? — 6R framework: Rehost, Refactor, Rearchitect, etc.",
      "Database Migration Service? — Pair with Migrate for SQL/PostgreSQL cutover.",
      "Lift-shift all VMs without assessment",
      "Ignore dependency map — migrate database before consumers",
      "No post-migrate right-sizing review"),
    q("Backup Vault Strategy", "Reliability", "Common",
      "Design Azure Backup vault strategy across subscriptions and regions.",
      "Central backup vault per environment/region in platform subscription; Backup Policies by workload type; immutability for ransomware protection; cross-region restore for DR.",
      "**Design:**\n- **Recovery Services vault** per region (backup data locality)\n- **Soft delete + immutability** enabled on vault\n- **Backup policies:** Daily app-consistent SQL; weekly VM; retention 30/90/365 tiers\n- **RBAC:** Backup Operator for ops; no delete permission for app teams\n\n**Architect:** Backup ≠ DR — define RPO/RTO per tier. Test restore quarterly — untested backup is wishful thinking.",
      "Backup vault architecture protects against ransomware and operator error.",
      "Backup vault vs Backup center? — Backup center is management UI across vaults.",
      "Azure Backup for AKS? — Backup via Azure Backup for AKS or Velero — evaluate workload.",
      "App teams can delete backup vault",
      "No immutability on prod vault",
      "Backup never restored in testing"),
    q("Defender for Cloud Tiers", "Security", "Very Common",
      "Compare Defender for Cloud plans and architect enrollment strategy.",
      "Foundational (free): secure score, basic recommendations. CSPM: posture management. Workload protection plans (Servers, App Service, SQL, Storage, etc.) add threat detection — enable per workload class in prod.",
      "**Plans:**\n- **CSPM** — misconfiguration detection, regulatory compliance\n- **Defender for Servers** — EDR integration, vulnerability management\n- **Defender for App Service** — threat detection on PaaS\n- **Defender for SQL** — anomaly detection\n\n**Architect:** Enable CSPM org-wide via Policy. Add workload plans based on data classification — not one-size-all or none.\n\n**Cost:** Per-resource pricing — budget Defender like any production service.",
      "Defender tier selection maps to workload criticality and compliance.",
      "Defender vs Sentinel? — Defender detects; Sentinel SIEM aggregates — often paired.",
      "Auto-provisioning agents? — Policy deploy AMA + Defender agents consistently.",
      "Defender disabled to save cost on prod PII systems",
      "All plans enabled everywhere — FinOps waste",
      "Secure score treated as compliance certification"),
    q("Entra ID Tenant Design", "Identity", "Very Common",
      "Design Entra ID tenant strategy for multi-brand enterprise.",
      "Single tenant with B2B guests for partners OR separate tenants per brand with Entra ID B2B sync — single tenant simplifies licensing; multi-tenant for strict isolation (M&A, regulatory).",
      "**Single tenant pattern:**\n- Conditional Access policies by app sensitivity\n- Dynamic groups for brand/department\n- Separate app registrations per brand\n\n**Multi-tenant pattern:**\n- Post-M&A hold separate tenants until integration\n- Azure Lighthouse or B2B for cross-tenant access\n\n**Architect:** Tenant boundary is hard to merge — decide early. DNS custom domains (`brand1.com`, `brand2.com`) map to one tenant cleanly.",
      "Tenant design is identity architecture foundation — expensive to reverse.",
      "B2B vs B2C? — B2B for partner employees; External ID (CIAM) for customer identities.",
      "Hybrid identity? — Entra Connect sync on-prem AD — plan UPN suffixes.",
      "New tenant per small project",
      "No Conditional Access on admin roles",
      "Guest users with excessive privileges"),
    q("Azure Firewall vs NSG", "Networking", "Very Common",
      "When Azure Firewall vs NSG for traffic control?",
      "NSG: L3/L4 stateful filter on subnet/NIC — micro-segmentation. Azure Firewall: centralized L3-L7 inspection, FQDN filtering, threat intel, IDPS — hub network security.",
      "**NSG use:**\n- Allow SQL 1433 from App Service subnet only\n- Deny inbound RDP from internet on subnet\n\n**Azure Firewall use:**\n- Egress FQDN filtering (allow `*.microsoft.com` only)\n- Centralized logging and forced tunneling\n- Application rules for outbound HTTP/S\n\n**Architect:** Hub-spoke — Firewall in hub, NSGs in spokes for defense in depth. Don't duplicate same rules in both without documentation.",
      "Firewall vs NSG layering is classic Azure network interview question.",
      "Firewall Premium vs Standard? — Premium adds IDPS and TLS inspection — compliance driver.",
      "NSG vs Application Security Group? — ASGs simplify NSG rules by grouping NICs logically.",
      "Replacing all NSGs with Firewall only — cost and complexity",
      "No egress filtering on prod subnets",
      "Firewall rules without naming and documentation"),
    q("Hub-Spoke Topology", "Networking", "Very Common",
      "Design hub-spoke network topology for enterprise Azure landing zone.",
      "Hub VNet: firewall, VPN/ExpressRoute gateway, DNS, Bastion. Spoke VNets: workloads peer to hub; no spoke-to-spoke without hub inspection (or AVNM).",
      "**Components:**\n```\nHub (10.0.0.0/16)\n├── Azure Firewall\n├── ExpressRoute GW\n├── DNS Private Resolver\nSpoke A (10.1.0.0/16) ──peering──► Hub\nSpoke B (10.2.0.0/16) ──peering──► Hub\n```\n\n**Architect decisions:**\n- Use Virtual WAN hub at scale (100+ spokes)\n- UDR default route `0.0.0.0/0` → Firewall private IP\n- IP plan avoids overlap with on-prem\n\n**CAF reference:** Implement via ALZ or Terraform/Bicep modules.",
      "Hub-spoke is default enterprise Azure network pattern.",
      "VWAN vs classic hub? — VWAN simplifies large-scale routing and S2S VPN.",
      "Spoke-to-spoke traffic? — Route through firewall or enable direct peering with governance.",
      "Flat VNet per app with no central egress control",
      "Overlapping IP ranges with on-prem",
      "Peering without UDR to firewall"),
    q("Private Link Overview", "Networking", "Very Common",
      "Explain Azure Private Link and architect use cases.",
      "Private Link exposes PaaS services via private IP in your VNet — traffic stays on Microsoft backbone, no public endpoint needed.",
      "**Components:**\n- **Private Endpoint** — NIC in your subnet with private IP\n- **Private DNS Zone** — `privatelink.database.windows.net` resolves to private IP\n\n**Use cases:**\n- SQL, Storage, Key Vault, App Service inbound private access\n- Consumer connects without service public IP\n\n**Architect:** Default deny public network access on PaaS + Private Endpoint. DNS is critical — broken DNS causes 'can't connect' incidents.",
      "Private Link is standard zero-trust PaaS connectivity pattern.",
      "Private Link vs Service Endpoints? — Private Link gives private IP; service endpoints route over backbone but public IP target.",
      "Private Link for App Service? — Inbound private endpoint on Premium v2+.",
      "Public endpoints on prod databases",
      "Private endpoint without private DNS zone",
      "On-prem DNS not forwarding privatelink zones"),
    q("Bicep vs Terraform", "IaC", "Very Common",
      "Choose Bicep vs Terraform for Azure-only landing zone.",
      "Bicep: native Azure, no state file, day-zero support, ARM integration. Terraform: multi-cloud, mature module ecosystem, state management — choose by team skills and multi-cloud requirement.",
      "**Bicep advantages:**\n- Transpiles to ARM — no state drift file\n- `what-if` and deployment stacks native\n- Azure Quickstart modules\n\n**Terraform advantages:**\n- AWS/GCP same tooling\n- Terragrunt for multi-env\n- Large community modules\n\n**Architect:** Azure-only shop → Bicep default. Multi-cloud mandate → Terraform with Azure provider. Don't maintain both for same resources.",
      "IaC tool choice is organizational — architects standardize one.",
      "Bicep vs ARM JSON? — Bicep is authoring layer — always compiles to ARM.",
      "Terraform state in Azure? — Store in Storage account with locking.",
      "Portal-only deploys in production",
      "Both Bicep and Terraform managing same RG",
      "No PR review on IaC changes"),
    q("Template Specs", "IaC", "Common",
      "What are Azure Template Specs and when use them?",
      "Template Specs are versioned Bicep/ARM templates stored as Azure resources — share approved patterns across subscriptions with RBAC control.",
      "**Workflow:**\n1. Platform team publishes `Template Spec` to shared resource group\n2. App teams deploy via `Microsoft.Resources/deployments` referencing spec version\n3. Version pinning ensures consistent landing patterns\n\n**Architect use cases:**\n- Approved App Service + SQL pattern\n- Spoke VNet subscription provisioning\n- Compliance baseline resources\n\n**vs Git repo:** Template Spec is Azure-native artifact with RBAC; Git remains source of truth in CI/CD pipeline.",
      "Template Specs enable self-service within guardrails.",
      "Template Spec vs Deployment stack? — Spec is template artifact; stack manages deployed resource lifecycle.",
      "Version strategy? — Semantic versioning; deprecate old versions with sunset date.",
      "Emailing Bicep files between teams",
      "No version pinning — always latest",
      "Template Spec without testing in CI"),
    q("What-If Deployment", "IaC", "Common",
      "How use ARM/Bicep what-if before production deployment?",
      "`az deployment group what-if` or Bicep what-if in CI pipeline previews creates/modifies/deletes without applying — mandatory gate before prod deploy.",
      "**What-if output:**\n- **Create** — new resources\n- **Modify** — property changes (highlight destructive)\n- **Delete** — resources removed from template scope\n\n**Architect CI/CD:**\n```bash\naz deployment group what-if \\\n  --resource-group rg-orders-prod \\\n  --template-file main.bicep\n```\n\nBlock pipeline on unexpected deletes. Pair with `canNotDelete` locks and Policy.",
      "What-if prevents 'template deleted our SQL server' disasters.",
      "What-if vs validate? — Validate syntax; what-if shows actual delta against live state.",
      "Incremental vs complete mode? — Complete mode deletes resources not in template — dangerous.",
      "Deploy to prod without what-if",
      "Complete deployment mode by default",
      "Ignoring what-if delete warnings"),
    q("Role Assignment Best Practices", "Security", "Very Common",
      "Azure RBAC role assignment best practices for production?",
      "Least privilege, narrowest scope, group-based assignments not individuals, PIM for admin roles, managed identities for apps, periodic access reviews.",
      "**Patterns:**\n- `Contributor` on resource group, not subscription\n- Use built-in roles before custom\n- Assign to Entra groups (`Azure-Orders-Prod-Contributors`)\n- PIM eligible Owner on prod subscription — max 8 hour activation\n- CI/CD: federated credential OIDC, custom deploy role\n\n**Architect:** Quarterly access review via Entra ID Access Reviews. Deny `Owner` standing assignment via Policy audit.",
      "RBAC hygiene is continuous — not one-time setup.",
      "ABAC vs RBAC? — Azure ABAC conditions on roles (e.g., tag match) — advanced least privilege.",
      "Role assignment propagation delay? — Up to 30 minutes — plan deployment pipeline retries.",
      "Owner assigned to developers permanently",
      "Individual user assignments not groups",
      "Service principal with Contributor on subscription"),
    q("Break-Glass Accounts", "Security", "Very Common",
      "Design break-glass accounts for Azure subscription emergency access.",
      "Two cloud-only global admin accounts, excluded from Conditional Access, credentials in physical safe, monitored with alerts on any sign-in, tested quarterly, separate from daily admin accounts.",
      "**Requirements:**\n- `@company.onmicrosoft.com` — no MFA device dependency that could fail\n- Excluded from CA policies that could lock everyone out\n- Alert Sentinel/Defender on ANY login\n- Document usage approval (two executives)\n\n**Architect:** Break-glass is last resort — daily ops use PIM. Never use break-glass for routine deploys.",
      "Break-glass design shows mature identity architecture.",
      "Break-glass vs emergency access in PIM? — PIM for normal elevation; break-glass when Entra/CA broken.",
      "How many break-glass accounts? — Microsoft recommends at least 2 cloud-only emergency accounts.",
      "Break-glass account used daily by admins",
      "Break-glass subject to same CA as everyone — locks out during CA misconfig",
      "No alerting on break-glass sign-in"),
    q("Subscription Vending", "Governance", "Common",
      "Implement subscription vending in Azure landing zone.",
      "Automated pipeline creates subscription via EA/MCA API, assigns to MG, applies Policy, RBAC, network peering, and tags — self-service request via ServiceNow/Portal.",
      "**Pipeline steps:**\n1. Validate request (owner, cost center, environment)\n2. Create subscription (Billing API / Account Factory)\n3. Move to target MG\n4. Deploy spoke via Template Spec (VNet, UDR, peering)\n5. Assign RBAC to owner group\n6. Register in CMDB\n\n**Architect:** Subscription vending scales cloud adoption — manual sub creation doesn't past 20 teams.\n\n**Tools:** Azure Landing Zone Accelerator, Terraform Cloud, custom Bicep + Azure DevOps.",
      "Subscription vending is platform engineering deliverable for scale.",
      "Alias vs subscription? — Create subscription alias for programmatic repeatability.",
      "Quota in vending? — Check regional vCPU quotas during vending workflow.",
      "Manual subscription creation per request",
      "New subscriptions land in root MG ungoverned",
      "No RBAC template in vending pipeline"),
]

WEEK_10_Q011_Q050 = [
    q("App Service Plans SKUs", "Compute", "Very Common",
      "Compare App Service Plan SKUs and select for production .NET API.",
      "Free/Shared dev only. Basic: no slots. Standard: slots, autoscale. Premium v3: zone balance, better CPU, VNet. Isolated v2: dedicated hardware for compliance isolation.",
      "**SKU tiers:**\n| Tier | Slots | Autoscale | Zone | Use |\n|------|-------|-----------|------|-----|\n| B1+ | No | Manual | No | Dev/test |\n| S1+ | Yes | Yes | No | Small prod |\n| P1v3+ | Yes | Yes | Yes | Production |\n| I1v2 | Yes | Yes | Yes | Isolated compliance |\n\n**Architect:** Start P1v3 × 2 instances for HA. Load test before P2v3 vs scale-out. Linux plans often better price/perf for .NET 8.\n\n**Reserved instances:** 1-3 year commit on ASP for FinOps savings.",
      "SKU choice affects SLA, features, and cost — not just vCPU count.",
      "P0v3 tier? — Entry Premium v3 — evaluate for lighter prod workloads.",
      "ASE required when? — VNet isolation at plan level, legacy compliance — often replaced by Private Link.",
      "Premium v3 for dev sandboxes — wasted cost",
      "Single B1 instance in production",
      "Choosing SKU without load test data"),
    q("Deployment Slots", "DevOps", "Very Common",
      "Deep dive: deployment slot configuration for zero-downtime .NET releases.",
      "Use staging slot for pre-swap validation; configure sticky settings; warm up with health check; auto-swap on CI success; database changes must be backward compatible.",
      "**Sticky settings (slot-specific):**\n- Connection strings (staging DB vs prod)\n- `ASPNETCORE_ENVIRONMENT`\n- Application Insights instrumentation key\n\n**Swap flow:**\n1. Deploy to staging\n2. Warm-up requests / smoke tests\n3. Swap (instant DNS/traffic flip)\n4. Monitor App Insights for 15 min\n5. Rollback = swap back if needed\n\n**Architect:** Slots share ASP compute — cost-effective blue/green. Pair with feature flags for decoupled releases.",
      "Slot mastery is expected for Azure PaaS architect interviews.",
      "Traffic routing before swap? — Route 5% production traffic to staging for canary testing.",
      "Slot density limits? — Standard allows 5 slots; Premium 20 — plan accordingly.",
      "Deploy directly to production slot",
      "Non-sticky connection string breaks swap",
      "Breaking DB migration during slot swap"),
    q("Always On", "Compute", "Common",
      "Why enable Always On for App Service and when can you disable it?",
      "Always On keeps worker process loaded — prevents idle shutdown that causes cold starts on first request. Required for WebJobs, timer triggers on same plan, and consistent API latency.",
      "**Without Always On (Basic+ can enable):**\n- App unloaded after ~20 min idle\n- First request slow (5-30+ seconds .NET startup)\n- WebJobs continuous mode fails\n\n**Can disable when:** Dev/test apps tolerating cold start, Consumption Functions (different service), aggressive cost savings on nonprod with scheduled access.\n\n**Architect:** Mandate Always On for production APIs. Monitor with availability test hitting `/health` every 5 minutes.",
      "Always On is free setting with major latency impact — often overlooked.",
      "Always On on Free tier? — Not available — another reason Free is dev-only.",
      "Always On vs availability test? — Availability test pings app; Always On prevents unload — use both.",
      "Production API without Always On",
      "WebJobs on plan without Always On",
      "Confusing with 'Keep Alive' custom hack instead of native setting"),
    q("App Service Environment", "Networking", "Common",
      "When deploy App Service Environment (ASE) vs standard multi-tenant App Service?",
      "ASE for legacy VNet-isolated dedicated App Service, fine-grained scale unit control, and ILB internal-only access. Most new designs use Premium v3 + Private Link instead of ASE v3 cost/complexity.",
      "**ASE v3 characteristics:**\n- Dedicated compute isolated in your VNet\n- Internal or external deployment\n- Higher cost and operational overhead\n- Longer deploy time (hours)\n\n**Modern alternative:**\n- App Service Premium v3\n- Regional VNet Integration + Private Endpoint inbound\n- Front Door for WAF\n\n**Architect:** ASE when regulatory mandate requires dedicated infrastructure boundary or existing ASE investment.",
      "ASE vs Private Link App Service is common modernization decision.",
      "ASE scaling? — Front-end and worker scale independently — plan IP space.",
      "ASE deprecation concerns? — Evaluate Microsoft guidance — many migrate to standard + Private Link.",
      "ASE for small internal CRUD app — massive overkill",
      "ASE without IP planning for subnet",
      "Choosing ASE without cost analysis vs Premium + PE"),
    q("Azure Functions Bindings", "Serverless", "Very Common",
      "Explain Azure Functions bindings and triggers for event-driven architecture.",
      "Triggers start execution (HTTP, Queue, Timer, Blob). Bindings connect to data sources read/write without boilerplate SDK code — input bindings inject data, output bindings persist results.",
      "**Example pattern:**\n- **Trigger:** Service Bus queue message\n- **Input binding:** Blob `{orderId}.json`\n- **Output binding:** Cosmos DB document + Service Bus reply queue\n\n**Architect:** Bindings accelerate development but hide complexity — understand retry, poison queue, and idempotency. Extension bundles version-lock dependencies.\n\n**Isolated worker (.NET):** Preferred for .NET 8 — align binding extensions with host version.",
      "Bindings show Functions depth beyond 'small HTTP method'.",
      "Binding vs SDK manual? — Bindings for standard paths; SDK when fine control needed.",
      "Durable Functions bindings? — Orchestrator uses async calls — different programming model.",
      "Non-idempotent output binding on retry",
      "Wrong extension bundle version in host.json",
      "HTTP trigger for long batch — wrong trigger choice"),
    q("Durable Functions", "Serverless", "Common",
      "When use Durable Functions vs standard Functions or Logic Apps?",
      "Durable Functions for stateful workflows in code — fan-out/fan-in, human approval, sagas with compensation. Logic Apps for visual integration; standard Functions for stateless event handlers.",
      "**Patterns:**\n- **Function chaining** — sequential steps\n- **Fan-out/fan-in** — parallel processing aggregate\n- **Human interaction** — wait for external event (approval webhook)\n- **Eternal orchestrator** — periodic polling\n\n**Storage:** Requires Azure Storage (task hub) for state. Premium plan recommended for production orchestrations.\n\n**Architect:** Order fulfillment saga — reserve inventory → charge payment → ship — with compensation on failure — ideal Durable Functions case.",
      "Durable Functions fills gap between stateless Functions and BPM engines.",
      "Durable vs Step Functions? — AWS equivalent — similar orchestration concept.",
      "Sub-orchestrations? — Compose large workflows from smaller orchestrators.",
      "Long workflow on Consumption plan — timeout and cold start issues",
      "No idempotency in activity functions",
      "Durable for simple 2-step flow — over-engineering"),
    q("Container Apps", "Containers", "Very Common",
      "Architect Azure Container Apps for microservices with scale-to-zero.",
      "Container Apps provides serverless Kubernetes abstraction — KEDA autoscale, Dapr sidecars, revisions, internal/external ingress — ideal for event-driven microservices without full AKS ops.",
      "**Architecture:**\n- One Container App per microservice\n- Environment shared VNet integration\n- KEDA scale on HTTP, queue depth, custom metrics\n- Secrets from Key Vault references\n\n**vs AKS:** Container Apps when team lacks K8s platform engineers. AKS when need full K8s API, service mesh, GPU node pools.\n\n**Architect:** Start Container Apps for 3-10 microservices; revisit AKS at scale/complexity threshold.",
      "Container Apps is the modern answer between App Service and AKS.",
      "Consumption vs dedicated environment? — Dedicated for workload isolation and predictable perf.",
      "Jobs in Container Apps? — Event-driven jobs with scale-to-zero — batch processing.",
      "AKS for two simple containers",
      "No revision management — deploy over production",
      "Public ingress without WAF/Front Door"),
    q("AKS Node Pools", "Kubernetes", "Very Common",
      "Design AKS node pool strategy for mixed workload cluster.",
      "System node pool (critical addons only) + user node pools by workload profile — general compute, memory-optimized, GPU — with cluster autoscaler and availability zones.",
      "**Best practices:**\n- **System pool:** 3 nodes min, zone spread, taints prevent app scheduling\n- **User pools:** Separate pools for windows/linux, spot for batch, on-demand for API\n- **Node size:** Standard_D4s_v5 general; E-series for memory\n\n**Architect:** One cluster per environment (nonprod/prod). Namespace isolation + RBAC for teams — not cluster per team unless strong isolation need.\n\n**Upgrade strategy:** Surge node pool upgrade with maxUnavailable tuning.",
      "Node pool design affects cost, availability, and upgrade safety.",
      "Spot node pool for API? — Batch/CI only — use on-demand for user-facing.",
      "Cluster autoscaler vs HPA? — CA adds nodes; HPA adds pods — both needed.",
      "Single node pool for everything including system pods",
      "No zone spread on production pool",
      "System pool running application workloads"),
    q("KEDA Autoscaling", "Scale", "Common",
      "Explain KEDA autoscaling on Azure Container Apps and AKS.",
      "KEDA scales workloads based on event sources (queue length, HTTP rate, Prometheus metrics) including scale-to-zero — Event-driven autoscaling beyond CPU-only HPA.",
      "**ScaledObject examples:**\n- Azure Service Bus queue > 10 messages → scale out\n- HTTP concurrent requests > 100\n- Cron scaler for business hours\n\n**On Container Apps:** Built-in KEDA integration — configure scale rules in Bicep/portal.\n\n**On AKS:** Install KEDA addon — ScaledObject CRD references Deployment.\n\n**Architect:** CPU-only autoscale misses queue backlog signals — KEDA for event-driven services.",
      "KEDA is essential for serverless container and Functions Premium patterns.",
      "KEDA vs HPA? — KEDA extends HPA with external metrics and scale-to-zero.",
      "Cooldown period? — Set scale-in stabilization to prevent flapping.",
      "CPU autoscale only on queue processor",
      "Scale to zero on latency-critical sync API",
      "No max replica limit — runaway scale cost"),
    q("Azure Container Registry", "Containers", "Very Common",
      "Design Azure Container Registry strategy for enterprise CI/CD.",
      "Premium ACR for geo-replication, private link, content trust; separate registry per environment or single with repo naming; managed identity pull from AKS/App Service; retention policies for untagged images.",
      "**Tiers:**\n- **Basic:** Dev only\n- **Standard:** Prod single region\n- **Premium:** Geo-rep, private link, higher throughput\n\n**Architect patterns:**\n- `acme.azurecr.io/orders-api:1.2.3` semver tags\n- ACR tasks for image build in cloud\n- Defender for Containers scan on push\n- Retention: keep last 10 tags, delete untagged >30 days",
      "ACR is supply chain security chokepoint — architect it deliberately.",
      "ACR vs Docker Hub? — ACR private, integrated RBAC, geo-rep — no rate limits.",
      "Anonymous pull? — Disable in prod — MI authentication only.",
      "Latest tag in production deploys",
      "Basic ACR for prod without geo-rep",
      "No image scanning in pipeline"),
    q("Web App for Containers", "Containers", "Common",
      "When use Web App for Containers vs Container Apps or AKS?",
      "Web App for Containers runs custom Docker on App Service — best when team knows App Service ops model and needs slots/VNet integration without Kubernetes.",
      "**Choose Web App for Containers when:**\n- Existing App Service expertise\n- Need deployment slots with container\n- Simple single-container web app\n- Built-in CI/CD from ACR webhook\n\n**Choose Container Apps/AKS when:**\n- Multi-container sidecars\n- KEDA scale-to-zero\n- Full K8s APIs\n\n**Architect:** Middle ground — containerize without K8s tax. Set `WEBSITES_PORT` and health check path in Dockerfile.",
      "Web App for Containers is underrated migration path from VM IIS.",
      "Multi-container App Service? — Compose supported limited — sidecars better on Container Apps.",
      "Pull from ACR? — Managed identity AcrPull role on App Service.",
      "AKS for single container blog app",
      "Wrong WEBSITES_PORT — app unreachable",
      "Huge container image — slow deploy and cold start"),
    q("App Service VNet Integration", "Networking", "Very Common",
      "Regional VNet Integration vs Private Endpoint for App Service — architect both.",
      "VNet Integration: outbound from App Service to private resources (SQL PE, internal API). Private Endpoint: inbound to App Service on private IP. Production private backends need both.",
      "**Outbound (Regional VNet Integration):**\n- App → private SQL, Storage, on-prem via ExpressRoute\n- Requires delegated subnet `Microsoft.Web/serverFarms`\n- Route all outbound through VNet optional\n\n**Inbound (Private Endpoint):**\n- Users/internal clients → App Service via private IP\n- DNS: `privatelink.azurewebsites.net`\n\n**Architect checklist:** NSG on integration subnet, private DNS zones linked to VNet, disable public network access when PE enabled.",
      "Bidirectional private App Service is production baseline for enterprise.",
      "Gateway-required VNet Integration? — Legacy — use regional integration.",
      "DNS private resolver? — On-prem resolves privatelink zones via hybrid DNS.",
      "Public SQL from App Service in prod",
      "Integration subnet without NSG rules",
      "Private endpoint without disabling public access"),
    q("Custom Domains and TLS", "Networking", "Very Common",
      "Configure custom domain and TLS for production App Service API.",
      "Map CNAME/A record to App Service; enable managed certificate (free) or import Key Vault cert; enforce HTTPS only; TLS 1.2 minimum; consider Front Door for apex domain and WAF.",
      "**Steps:**\n1. Verify domain ownership (TXT/CNAME)\n2. Bind `api.company.com` to App Service\n3. App Service Managed Certificate or Key Vault reference\n4. `minimumTlsVersion`: 1.2\n5. HSTS header in app or Front Door\n\n**Architect:** Apex domain (`company.com`) often needs Front Door or DNS ALIAS — App Service alone prefers subdomain CNAME.\n\n**Renewal:** Managed certs auto-renew; Key Vault certs need renewal automation.",
      "TLS and domain architecture affects SEO, security scanners, and mobile apps.",
      "Wildcard cert? — Key Vault or purchase — managed cert is per-domain.",
      "Cert on slot? — Bind cert before swap — or use Front Door single endpoint.",
      "HTTP allowed in production",
      "Expired cert without monitoring",
      "Self-signed cert in prod mobile app API"),
    q("Autoscale Rules App Service", "Scale", "Very Common",
      "Design autoscale profile for App Service handling daily traffic spikes.",
      "Combine metric rules (CPU, HTTP queue length, memory) with schedule rules (pre-scale before 9 AM); min 2 instances prod; cooldown 5-10 min; validate with load test.",
      "**Example profile:**\n```\nMin: 2, Max: 12, Default: 2\nRule 1: CPU > 70% avg 5 min → +2 instances\nRule 2: HTTP queue > 100 → +1 instance\nSchedule: Mon-Fri 8 AM → min 4 instances\nScale-in: CPU < 30% for 10 min → -1 (slow scale-in)\n```\n\n**Architect:** HTTP queue catches I/O bound before CPU spikes. Custom metric from App Insights (requests/sec) often best signal.",
      "Autoscale tuning separates architect from checkbox configurator.",
      "Per-app vs plan autoscale? — Scale App Service Plan instance count — all apps on plan scale together.",
      "Predictive autoscale? — ML-based pre-scale — evaluate for predictable patterns.",
      "Min 1 instance in production",
      "Scale-in immediately on CPU dip — flapping",
      "Autoscale without load test baseline"),
    q("Local Cache App Service", "Performance", "Common",
      "When enable App Service local cache for .NET deployments?",
      "Local cache copies site content to worker local SSD — faster cold start after scale-out and reduces storage latency — enable for large deployments or frequent scale events.",
      "**How it works:**\n- `WEBSITE_LOCAL_CACHE_OPTION` = Always\n- Content synced from `/home` to local disk on startup\n- Survives scale-out instance boot faster\n\n**Use when:**\n- Large wwwroot (many static files)\n- Frequent autoscale events\n- Read-heavy content (not write-heavy local files)\n\n**Architect:** Pair with Run From Package — package read-only; local cache accelerates reads. Don't rely on local disk for persistent writes.",
      "Local cache optimizes scale-out performance on App Service.",
      "Local cache vs CDN? — CDN for static public assets; local cache for app file system perf.",
      "Write to local cache disk? — Ephemeral — lost on restart — use Blob Storage.",
      "Persistent file uploads to App Service local disk",
      "Local cache without understanding read-only semantics",
      "Huge mutable log files on local cache volume"),
    q("ARR Affinity", "Performance", "Common",
      "Explain ARR affinity (session affinity) on App Service — enable or disable?",
      "ARR affinity routes returning clients to same instance via cookie — enable only for legacy in-memory session state; disable for stateless APIs and enable proper load distribution.",
      "**When ON:**\n- Legacy app stores session in memory\n- WebSocket sticky connections (sometimes)\n\n**When OFF (default for modern apps):**\n- Stateless REST APIs\n- Session in Redis/SQL/Cosmos\n- Better load balance across instances\n\n**Architect:** Default OFF. If enabling, document instance failure impact — users lose session. Migration path: externalize session then disable affinity.",
      "ARR affinity is technical debt indicator in modern architectures.",
      "Affinity and deployment slots? — Affinity cookie may route to specific instance after swap — test carefully.",
      "Affinity vs Front Door session affinity? — Layer on layer — avoid double affinity.",
      "Affinity on with in-memory session — instance failure logout",
      "Affinity enabled 'just in case' on stateless API",
      "No plan to externalize session before scaling"),
    q("Health Check App Service", "Reliability", "Very Common",
      "Configure App Service health check for autoscale and load balancer integration.",
      "Health check path (e.g., `/health`) — unhealthy instances removed from load balancer rotation; enables automatic instance replacement during platform issues.",
      "**Configuration:**\n- Path returns 200 with quick DB ping optional\n- Unhealthy threshold removes instance from rotation\n- Works with autoscale — unhealthy instances don't receive traffic\n\n**Architect:** Health endpoint checks critical dependencies (SQL, Redis) with timeout budget < 5 seconds. Don't check every downstream — cascading false unhealthy.\n\n**Pair with:** App Insights availability tests for external monitoring.",
      "Health checks connect app readiness to platform routing decisions.",
      "Liveness vs readiness? — Single App Service health check — design combined endpoint.",
      "Health check during deployment slot swap? — Ensure staging healthy before swap.",
      "Health check returns 200 without checking dependencies",
      "Slow health check causing timeout removals",
      "No health check configured on production"),
    q("Run From Package", "DevOps", "Common",
      "Benefits of Run From Package (WEBSITE_RUN_FROM_PACKAGE) on App Service?",
      "Deploys app as read-only zip/blob mount — faster deployments, fewer file lock issues, atomic updates, reduced storage corruption risk.",
      "**Settings:**\n- `WEBSITE_RUN_FROM_PACKAGE=1` (local package)\n- `WEBSITE_RUN_FROM_PACKAGE=URL` (Blob SAS or MI to Storage)\n\n**Benefits:**\n- Atomic deploy — all files updated simultaneously\n- No Kudu file copy slow sync\n- Read-only filesystem reduces tampering\n\n**Architect:** Standard for CI/CD — pipeline uploads zip to Blob, sets URL with MI auth. Pair with deployment slots.",
      "Run From Package is CI/CD best practice for App Service.",
      "Run From Package vs ZIP deploy? — Run From Package mounts zip; traditional deploy extracts to wwwroot.",
      "Package size limits? — Large packages slow cold start — trim dependencies.",
      "Kudu manual file edits in production",
      "SAS URL expiring without rotation",
      "Writable app expecting local file persistence"),
    q("Function Premium Plan", "Serverless", "Very Common",
      "When choose Azure Functions Premium plan over Consumption?",
      "Premium plan for pre-warmed instances (no cold start), VNet integration, unlimited duration, higher memory — production HTTP APIs and Durable Functions orchestrations.",
      "**Premium features:**\n- **Always Ready instances** — min 1+ warm workers\n- **Elastic Premium (EP1-EP3)** — scale 0 to N with pre-warm\n- VNet integration for private resources\n- Max 60 min execution (vs 5-10 min consumption)\n\n**Architect decision matrix:**\n| Requirement | Plan |\n|-------------|------|\n| Spiky batch, cold OK | Consumption |\n| Sync API <500ms | Premium |\n| VNet + private SQL | Premium |\n| Durable production | Premium |",
      "Premium plan is the architect answer to Consumption cold start limitations.",
      "Premium vs App Service? — Premium Functions when event-driven + scale-to-zero; App Service for always-on API.",
      "EP1 sizing? — Start EP1 with 1 pre-warmed; load test before EP2.",
      "Consumption for customer-facing checkout API",
      "Premium with 0 always-ready instances — defeats purpose",
      "Durable Functions on Consumption in production"),
    q("Logic Apps Standard", "Integration", "Common",
      "Logic Apps Standard vs Consumption — architect integration platform choice.",
      "Standard (single-tenant, App Service plan hosted) for VNet integration, predictable performance, higher throughput. Consumption for low-volume, pay-per-action, no VNet requirement.",
      "**Logic Apps Standard:**\n- Hosted in App Service Environment or dedicated plan\n- VNet integration for private connectors\n- Fixed pricing via WS1/WS2/WS3 workflow service plan\n- Stateful workflows with better isolation\n\n**Consumption:**\n- Serverless pricing per action\n- Public connectors default\n- Quick prototypes and low-volume B2B\n\n**Architect:** Enterprise integrations touching SAP/on-prem via hybrid connector → Standard. Simple SaaS webhook fan-out → Consumption.",
      "Logic Apps tier choice affects networking, cost, and compliance.",
      "Logic Apps vs Functions for integration? — Logic Apps visual, connectors; Functions code-first complex logic.",
      "Durable Functions vs Logic Apps? — Durable for dev team in C#; Logic Apps for integration specialists.",
      "Consumption Logic Apps for private SAP integration",
      "Standard without VNet when connectors need private access",
      "No error handling / dead letter on critical workflows"),
    q("API Management Integration", "Integration", "Very Common",
      "Place Azure API Management in front of App Service and Functions — why and how?",
      "APIM provides API gateway: authentication, rate limiting, versioning, caching, analytics, WAF integration — decouples public API contract from backend implementation.",
      "**Architecture:**\n```\nClient → APIM (api.company.com) → App Service / Functions (private)\n```\n\n**Features:**\n- OAuth/JWT validation at gateway\n- Rate limit per subscription key\n- Revision-based API versioning\n- Request/response transformation\n\n**Architect:** Backends use Private Endpoint; APIM in VNet or External with IP restrictions. Don't expose App Service public URL when APIM is front door.",
      "APIM is standard API façade pattern for enterprise Azure.",
      "APIM vs Front Door? — APIM API management; Front Door global L7 load balance + WAF — often combined.",
      "Consumption vs Premium APIM? — Premium for VNet injection and multi-region.",
      "Public App Service URL bypassing APIM",
      "No rate limiting on public API",
      "API keys as only auth for sensitive data"),
    q("Windows vs Linux App Service", "Compute", "Common",
      "Choose Windows vs Linux App Service for .NET 8 workload?",
      "Linux App Service preferred for .NET 8+ — better performance, lower cost, smaller footprint. Windows when needing full Framework 4.x, COM components, or legacy IIS modules.",
      "**Linux advantages (.NET 8):**\n- Lower ASP cost for same tier\n- Faster container-like isolation\n- Better CI/CD with Oryx build\n\n**Windows required when:**\n- .NET Framework 4.8 legacy\n- Windows-specific dependencies (COM, GAC)\n- Team only has IIS expertise short-term\n\n**Architect:** Default Linux for new .NET Core/8. Document migration path for Framework apps (Azure Migrate App Service assessment).",
      "OS choice affects cost, performance, and migration strategy.",
      "Mixed plan? — One ASP is Windows OR Linux — not mixed on same plan.",
      ".NET on Linux containers? — Web App for Containers alternative on Linux plan.",
      "Windows plan for new .NET 8 API without reason",
      "Linux plan with Windows-only dependency discovered late",
      "No load test comparing OS options"),
    q("App Service Certificates", "Security", "Common",
      "Manage TLS certificates for App Service at enterprise scale.",
      "App Service Managed Certificate for public apps; Key Vault integration for wildcard and internal certs; automate renewal; Front Door for centralized cert management multi-app.",
      "**Options:**\n1. **Free managed cert** — single domain, auto-renew, public apps only\n2. **Key Vault reference** — import PFX, RBAC to App Service MI\n3. **Front Door managed cert** — apex + subdomains at edge\n\n**Architect:** Central team owns Key Vault `prod-tls-certs`. Pipeline imports renewed cert. Alert 30 days before expiry on non-auto-renew certs.",
      "Certificate lifecycle failures cause production outages — automate.",
      "Managed cert limitations? — No wildcard, no internal/private App Service.",
      "Cert per slot? — Each hostname binding needs cert — automate in swap pipeline.",
      "Manual cert upload every year",
      "Expired cert without Azure Monitor alert",
      "Wildcard cert private key in app settings"),
    q("Diagnostic Settings App Service", "Observability", "Very Common",
      "Configure diagnostic settings for App Service production monitoring.",
      "Send AppServiceHTTPLogs, AppServiceConsoleLogs, AppServiceAppLogs to Log Analytics; enable AllMetrics; configure retention and daily cap; alert on HTTP 5xx spike.",
      "**Enable via Bicep:**\n```bicep\nresource diag 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {\n  // AppServiceHTTPLogs, AppServicePlatformLogs → Log Analytics\n}\n```\n\n**Architect:** Platform team deploys diagnostic settings via Policy DeployIfNotExists — app teams don't opt-in manually.\n\n**Tables:** `AppServiceHTTPLogs` for W3C request analytics; `AppServiceConsoleLogs` for startup failures.",
      "Diagnostic settings are prerequisite for troubleshooting App Service incidents.",
      "App Insights vs diagnostic logs? — App Insights APM; diagnostics platform and HTTP raw logs.",
      "Log scrubbing? — Don't log PII/card data — configure sampling and app log levels.",
      "No HTTP logs in production",
      "Verbose logging without daily cap",
      "Diagnostics only to Storage — slow query in incidents"),
    q("CPU Profiling App Service", "Performance", "Common",
      "Diagnose high CPU on App Service using profiling tools.",
      "Use App Service Profiler (App Insights) for production CPU flame graphs; Kudu `dotnet-trace` for deeper analysis; correlate with autoscale metrics and slow dependencies.",
      "**Workflow:**\n1. Enable Profiler on App Insights\n2. Capture during high CPU window\n3. Identify hot methods (JSON serialization, regex, sync-over-async)\n4. Fix code path or scale out temporarily\n\n**Architect:** Profiler overhead minimal — leave enabled prod. Pair with `ServerException` and dependency tracking in App Insights.\n\n**Common .NET causes:** Sync `HttpClient`, missing `AsNoTracking`, large object heap pressure.",
      "Profiling connects performance architecture to code reality.",
      "Profiler vs snapshot debugger? — Profiler for CPU; Snapshot for exception moment variables.",
      "Load test before profiling? — Reproduce under known load for clearer flame graph.",
      "Scale out indefinitely without profiling root cause",
      "Profiler never enabled — flying blind",
      "Profiling only in dev — issue doesn't reproduce locally"),
    q("Zone Redundancy App Service", "Reliability", "Common",
      "Enable zone redundancy for App Service Premium v3 — requirements and benefits.",
      "Premium v3 plan with minimum 3 instances spread across availability zones — protects against datacenter failure within region — improves SLA beyond single-datacenter deployment.",
      "**Requirements:**\n- Premium v3 App Service Plan\n- `zoneRedundant: true` in Bicep\n- Min 3 instances for zone spread\n- Supported regions with AZ\n\n**Architect:** Zone-redundant ASP + zone-redundant SQL + Front Door health probes = strong single-region HA. Not substitute for multi-region DR.\n\n**Cost:** ~3 instances minimum — budget accordingly vs 2-instance non-zonal HA.",
      "Zone redundancy is within-region HA — architects distinguish from geo-DR.",
      "Zonal vs zone-redundant storage for app? — App state external — zone-redundant ASP handles compute.",
      "Deploy zone-redundant in region without AZ? — Fails — verify region capability.",
      "Two instances claiming zone redundancy",
      "Zone-redundant without multi-instance minimum",
      "Assuming zone-redundant replaces backup region"),
    q("App Service Backup", "Reliability", "Common",
      "App Service backup strategy — what is backed up and what is not?",
      "App Service backup captures app content, config, connection strings — NOT the database. Schedule daily backup to Storage account; include slot settings; test restore to staging slot.",
      "**Backed up:**\n- wwwroot files\n- App settings and connection strings\n- Custom domains bindings (partial)\n\n**NOT backed up:**\n- Azure SQL data — use SQL backup\n- External Blob content\n- DNS records outside Azure\n\n**Architect:** Backup is DR for app config/code — pair with IaC (Bicep) as primary source of truth; backup as safety net.",
      "App Service backup scope limits catch teams in disaster recovery drills.",
      "Backup vs snapshot slot? — Backup scheduled; slot is deployment strategy — complementary.",
      "Geo-redundant backup storage? — Store backups in paired region for regional disaster.",
      "Assuming App Service backup includes SQL database",
      "Never tested restore procedure",
      "No backup on production because 'we have Git'"),
    q("Easy Auth", "Security", "Very Common",
      "Implement App Service Authentication (Easy Auth) vs app-level auth?",
      "Easy Auth handles OAuth/OIDC at platform layer before request hits app — quick Entra ID, Google, Facebook integration — app receives authenticated headers (`X-MS-CLIENT-PRINCIPAL`).",
      "**When Easy Auth:**\n- Internal tools with Entra ID only\n- Quick protection without code changes\n- Multi-tenant SaaS with platform SSO\n\n**When app-level:**\n- Complex authorization (ABAC, custom claims)\n- Multi-idp with unified token format\n- API returning JWT to mobile clients\n\n**Architect:** Easy Auth for internal admin sites; ASP.NET Core Identity + Entra for product APIs with fine-grained RBAC.",
      "Easy Auth vs DIY auth is common App Service security question.",
      "Easy Auth v2? — Current version — configure via app settings or portal Authentication blade.",
      "Easy Auth on API + APIM? — APIM validates JWT; Easy Auth may duplicate — choose one layer.",
      "Easy Auth for complex custom RBAC without evaluation",
      "Authentication disabled on staging slot publicly exposed",
      "Trusting client-sent user headers without Easy Auth"),
    q("Managed Identity App Service", "Identity", "Very Common",
      "Implement managed identity patterns for App Service accessing Azure services.",
      "Enable system-assigned or user-assigned MI; grant least-privilege RBAC (Key Vault Secrets User, Storage Blob Data Reader); use Key Vault references; DefaultAzureCredential in .NET.",
      "**Pattern:**\n```csharp\n// .NET — no secrets in config\nvar credential = new DefaultAzureCredential();\nvar client = new SecretClient(vaultUri, credential);\n```\n\n**Slot consideration:** User-assigned MI can stay constant across slot swap; system-assigned differs per slot — plan Key Vault access accordingly.\n\n**Architect:** Ban connection strings with passwords in app settings — Policy audit non-compliant apps.",
      "Managed identity is mandatory pattern for production Azure apps.",
      "System vs user-assigned MI? — User-assigned for shared identity across slots/regions.",
      "Federated credential CI/CD? — GitHub Actions OIDC to Entra — no SP secret.",
      "SQL connection string password in app settings",
      "Contributor MI on subscription",
      "System-assigned MI breaks after slot swap without planning"),
    q("Sidecar Pattern Containers", "Containers", "Common",
      "Explain sidecar pattern in Azure Container Apps and AKS.",
      "Sidecar containers share pod/network namespace with main app — handle logging, proxy, mesh, secrets — without modifying application container.",
      "**Examples:**\n- **Dapr sidecar** — service invocation, pub/sub, state store\n- **Envoy/Istio** — service mesh mTLS, traffic split\n- **Log forwarder** — Fluent Bit shipping to Log Analytics\n\n**Container Apps:** Dapr enabled per app — sidecar injected automatically.\n\n**Architect:** Sidecars add resource overhead — size CPU/memory accordingly. Prefer Dapr over custom sidecar glue when patterns match.",
      "Sidecar pattern shows container architecture maturity beyond single-container apps.",
      "Sidecar vs init container? — Init runs before app starts (migration); sidecar runs alongside.",
      "Multiple sidecars? — Supported in K8s — watch total pod resource limits.",
      "Monolithic container doing app + proxy + logging",
      "Sidecar without resource limits starving main app",
      "Custom sidecar reinventing Dapr features"),
    q("Batch vs Real-Time Compute", "Architecture", "Common",
      "Choose batch vs real-time compute on Azure for order processing.",
      "Real-time (App Service, Functions, Container Apps HTTP) for user-facing order submission. Batch (Azure Batch, Functions queue trigger, Container Apps Jobs) for end-of-day settlement, reporting, ETL.",
      "**Decision matrix:**\n| Pattern | Azure service | Latency |\n|---------|---------------|--------|\n| Sync API | App Service | <500ms |\n| Event async | Functions + SB Queue | Seconds |\n| Large parallel batch | Azure Batch / ACA Jobs | Minutes-hours |\n| Stream | Event Hubs + Stream Analytics | Sub-second ingest |\n\n**Architect:** Hybrid — API accepts order (real-time), publishes event, batch processor settles payments overnight.",
      "Batch vs real-time split is fundamental compute architecture decision.",
      "Batch on Consumption Functions? — 10 min timeout limit — use Batch service for HPC.",
      "Spark on Synapse for batch? — Big data analytics batch — different scale tier.",
      "Batch job in synchronous HTTP request",
      "Real-time Functions for 6-hour ETL",
      "No queue between API and batch processor"),
    q("SignalR Service", "Real-Time", "Common",
      "When use Azure SignalR Service vs self-hosted SignalR on App Service?",
      "Azure SignalR Service offloads connection management — scales to 100K+ concurrent connections — App Service hosts hub logic only — required for large fan-out real-time apps.",
      "**Tiers:**\n- **Free:** Dev only (20 connections)\n- **Standard:** Production scale\n- **Premium:** Large enterprise, geo-scale, SLA\n\n**Architecture:**\n```\nBrowser ←→ Azure SignalR Service ←→ App Service (hub code)\n```\n\n**Architect:** Live dashboards, collaborative editing, notification push — SignalR Service prevents connection exhaustion on App Service.",
      "SignalR Service solves WebSocket scale limits on App Service.",
      "SignalR vs Web PubSub? — Web PubSub general pub/sub; SignalR .NET hub model.",
      "Serverless mode? — SignalR Service serverless with Functions triggers.",
      "Self-hosted SignalR at 10K concurrent users on small ASP",
      "Sticky sessions instead of SignalR Service at scale",
      "Free tier in production"),
    q("Static Web Apps", "Compute", "Common",
      "Azure Static Web Apps vs App Service for React front-end and API?",
      "Static Web Apps for Jamstack — static front-end from GitHub, serverless API via Functions, global CDN, free SSL — ideal SPA + API. App Service when need full .NET server, WebSockets, long-running API.",
      "**Static Web Apps strengths:**\n- CI/CD from GitHub Actions built-in\n- Staging environments per PR\n- Azure Functions integrated API routes\n- Custom domain + managed cert free tier\n\n**App Service when:**\n- Full ASP.NET Core MVC/server rendering\n- Deployment slots with complex backend\n- VNet integration to private SQL\n\n**Architect:** SWA for marketing site + lightweight API; App Service for core enterprise API.",
      "SWA vs App Service is common front-end architecture fork.",
      "SWA Standard vs Free? — Standard for custom domains without SWA subdomain limits in enterprise.",
      "SWA + APIM? — API behind APIM while static on SWA CDN.",
      "App Service for static-only React site — overpaying",
      "SWA API for heavy VNet-private SQL without networking plan",
      "No PR preview environments for front-end"),
    q("App Service Hybrid Connections", "Networking", "Common",
      "Use App Service Hybrid Connections to reach on-premises resources.",
      "Hybrid Connection Manager agent on-prem relays TCP traffic to App Service — reach legacy SQL, SOAP APIs without VPN/ExpressRoute — good for dev/test or small integrations.",
      "**Limits:**\n- TCP only — not UDP\n- Not for production high-throughput (use ExpressRoute/VPN)\n- Requires Hybrid Connection Manager installed on-prem\n\n**Architect:** Migration bridge — cloud App Service calls on-prem DB during phased migration. Plan cutover to VPN/ExpressRoute + private connectivity for prod.",
      "Hybrid Connections are stepping stone — not enterprise production networking.",
      "Hybrid vs VNet Integration? — Hybrid reaches on-prem TCP by name; VNet Integration routes through Azure VNet.",
      "Relay vs Hybrid Connection? — Azure Relay underpins Hybrid Connections feature.",
      "Hybrid Connection as permanent prod path for high traffic",
      "No HA on Hybrid Connection Manager agent",
      "Confusing with Site-to-Site VPN architecture"),
    q("Compute Quota Planning", "Operations", "Common",
      "Plan Azure compute quota before large migration or product launch.",
      "Request vCPU quota increases per region/SKU family early; use Azure Capacity Reservation for scarce SKUs; distribute across regions; monitor `Microsoft.Compute/locations/usages`.",
      "**Process:**\n1. Inventory target VM/SKU needs from Migrate assessment\n2. Check current quota vs required in target region\n3. Submit quota increase ticket 2-4 weeks before deploy\n4. Consider alternate SKU or region if quota delayed\n\n**Architect:** Quota is deployment blocker equal to architecture approval — include in migration timeline. AKS node pools consume multiple VM family quotas.",
      "Quota planning prevents launch-day 'InsufficientQuota' failures.",
      "Quota vs capacity reservation? — Quota is ceiling; reservation guarantees availability within quota.",
      "Subscription vs region quota? — Regional vCPU limits per subscription — request per sub/region.",
      "Assume unlimited Azure capacity in any region",
      "Quota increase request day before go-live",
      "Wrong SKU family in quota request"),
    q("Image Hardening Containers", "Security", "Very Common",
      "Container image hardening checklist for ACR and AKS production.",
      "Non-root user, minimal base image (distroless/alpine), no secrets in layers, scan with Defender for Containers, pin digests not tags, sign with Notation/Cosign.",
      "**Checklist:**\n- Multi-stage Dockerfile — build vs runtime separation\n- `USER nonroot` in final stage\n- Patch base image weekly in CI\n- ACR retention + quarantine policy on CVE critical\n- Admission controller deny `:latest` and unscanned images\n\n**Architect:** Supply chain security — only deploy images passing scan gate in CI/CD.",
      "Image hardening is container security foundation — expected in architect interviews.",
      "Distroless vs Alpine? — Distroless smaller attack surface; Alpine musl compatibility issues for .NET.",
      "ACR Tasks scan on build? — Integrate Trivy/Defender in pipeline.",
      "Root container in production K8s",
      "Latest tag deploys from public Docker Hub",
      "Secrets baked into image layers in Git history"),
    q("Startup Probes Kubernetes", "Kubernetes", "Common",
      "Configure startup, liveness, and readiness probes for AKS workloads.",
      "Startup probe allows slow-starting containers before liveness kills them. Readiness removes pod from Service until ready. Liveness restarts hung containers.",
      "**Example:**\n```yaml\nstartupProbe:\n  httpGet: { path: /health/startup, port: 8080 }\n  failureThreshold: 30\n  periodSeconds: 10\nreadinessProbe:\n  httpGet: { path: /health/ready, port: 8080 }\nlivenessProbe:\n  httpGet: { path: /health/live, port: 8080 }\n```\n\n**Architect:** .NET apps need generous startupProbe — JIT and EF migrations slow boot. Readiness checks DB connection; liveness only checks process responsive.",
      "Probe design prevents cascading pod restart death spirals.",
      "Probe and App Service health check? — Same concept — K8s native on AKS.",
      "exec vs httpGet probe? — Prefer httpGet; exec adds shell dependency.",
      "Liveness probe hits database — restart loops on DB blip",
      "No startup probe on 60-second .NET boot",
      "Readiness same as liveness — wrong semantics"),
    q("Resource Limits Containers", "Kubernetes", "Very Common",
      "Set CPU and memory requests/limits for AKS pod resource management.",
      "Requests guarantee scheduling capacity; limits cap usage — set requests ≈ average usage, limits ≈ peak — prevents noisy neighbor and OOM kills.",
      "**Guidelines:**\n```yaml\nresources:\n  requests: { cpu: 250m, memory: 512Mi }\n  limits:   { cpu: 1000m, memory: 1Gi }\n```\n\n**Architect:** Start from load test metrics. .NET apps: watch LOH — memory limit too low causes GC thrashing/OOMKill. Use Vertical Pod Autoscaler recommendation mode before enforcing.\n\n**Namespace quotas:** Prevent one team consuming entire cluster.",
      "Resource limits translate performance architecture to K8s scheduling.",
      "Limit without request? — Bad practice — request required for scheduling.",
      "CPU limit throttling? — .NET can throttle under low CPU limit — tune carefully.",
      "No limits — pod consumes node memory crash neighbors",
      "Limits equal requests with no burst room",
      "Copy-paste limits without load test validation"),
    q("Multi-Region App Service", "Reliability", "Very Common",
      "Design multi-region App Service for 99.99% API availability.",
      "Front Door Premium routes to regional App Services; externalize session state (Redis); SQL geo-replication or Cosmos multi-write; coordinated deployment pipeline; health probes per origin.",
      "**Active-active challenges:**\n- Data consistency across regions\n- Deployment synchronization\n- Config drift between regions\n\n**Architect patterns:**\n- **Active-passive:** Simpler data — secondary warm standby\n- **Active-active:** Stateless API + Cosmos/SQL read replicas\n\n**Runbook:** Failover = Front Door origin priority change + DNS if needed.",
      "Multi-region App Service requires data architecture not just duplicate deploy.",
      "Traffic Manager vs Front Door? — Front Door L7 + WAF; TM DNS-level weighted routing.",
      "Regional ASP scaling? — Each region independent autoscale profile.",
      "Active-active without shared session store",
      "Manual deploy causing region config drift",
      "No Front Door health probe per region origin"),
    q("Cost Optimize Idle Compute", "FinOps", "Very Common",
      "Reduce Azure compute cost for idle and non-production workloads.",
      "Auto-shutdown dev VMs/App Service nights/weekends; scale Functions/Container Apps to zero; right-size SKUs; DevTest subscriptions; Azure Advisor recommendations; reserved instances for stable prod baseline only.",
      "**Tactics:**\n| Workload | Optimization |\n|----------|-------------|\n| Dev VMs | Auto-shutdown 7 PM |\n| Nonprod ASP | Scale to 1 off-hours |\n| Batch | Spot instances / ACA Jobs scale-to-zero |\n| Prod | RI/Savings Plan on baseline |\n\n**Architect:** Tag `AutoShutdown=true` + Automation account. FinOps dashboard shows idle CPU <5% for 7 days — right-size ticket.\n\n**Balance:** Cost vs developer experience — don't shutdown shared staging during release week.",
      "Idle compute optimization is recurring FinOps architect responsibility.",
      "Azure Automation vs Logic Apps shutdown? — Automation runbooks common for VM schedule.",
      "Start/Stop v2? — Managed feature for VM schedules without custom scripts.",
      "Production Premium ASP 3 instances overnight for dev traffic",
      "No budget alerts on nonprod subscriptions",
      "Reserved instances on workloads planned to decommission"),
]

ALL_AZURE_Q011_Q050_W09_W10 = {
    9: WEEK_9_Q011_Q050,
    10: WEEK_10_Q011_Q050,
}
