"""Week 1 advanced (Q071-Q080 premium) and expert scenarios (Q101-Q120)."""

from premium_qa_data import q

# Advanced Q071-Q080 — premium; script will generate Q081-Q100 as solid standard
WEEK1_ADVANCED_PREMIUM = [
    q("Native AOT vs JIT for .NET APIs", "Performance", "Occasional",
      "When recommend Native AOT compilation for .NET 8 services?",
      "Native AOT for cold-start sensitive (Functions, edge), constrained memory, or security (no JIT). JIT default for most ASP.NET APIs with reflection-heavy frameworks.",
      "**Native AOT:** faster startup, smaller footprint, no dynamic codegen — limitations: reflection, some EF features, longer compile.\n\n**JIT:** full runtime flexibility, tiered compilation optimizes hot paths.\n\n**Architect:** Profile first — team wanted Go rewrite at 500 RPS — Native AOT + optimization often sufficient without language change.",
      "Technology choice requires workload-specific evidence.",
      "Trimming vs AOT? — Trimming reduces size; AOT eliminates JIT — different trade-offs.",
      "EF Core AOT? — Improving but verify — may need Dapper for hot path.",
      "AOT everywhere mandate",
      "Ignore reflection dependency break",
      "Rewrite language before profiling"),
    q("LOH Fragmentation", "GC", "Common",
      "Large Object Heap issues in .NET service — diagnosis and fix?",
      "Objects ≥85KB go to LOH, collected with Gen2, not compacted by default (pre-.NET 4.5.1 limitations improved). Large byte arrays, JSON strings cause LOH pressure and fragmentation.",
      "**Diagnose:** `% Time in GC`, LOH size in dotMemory, Gen2 frequency.\n\n**Fix:** pool large buffers (`ArrayPool<byte>`), stream JSON instead of materialize, `POH` pinned object heap for specific scenarios, upgrade runtime for compaction settings.\n\nPayment API serializing 500KB JSON per request — switch to streaming or chunk.",
      "LOH is common production GC issue architects recognize.",
      "ArrayPool return? — Don't return arrays still in use — clear sensitive data.",
      "Gen2 full blocking? — Indicates LOH or long-lived object pressure.",
      "ToString on huge collections in logs",
      "Deserialize entire blob to string",
      "Ignore Gen2 GC alerts"),
    q("ConfigureAwait and Library Code", "Async", "Occasional",
      "Should library authors use ConfigureAwait(false)?",
      "Library code: yes — avoid capturing caller sync context unnecessarily. Application code (ASP.NET): generally no — needs HttpContext on continuation after await.",
      "ASP.NET Core doesn't have legacy sync context capture issue like old ASP.NET — but library code still benefits from `ConfigureAwait(false)` for reuse in UI, legacy contexts.\n\nArchitect coding standard: analyzers enforce in shared libraries.",
      "Async context rules differ library vs app — architects document standards.",
      "Task.Run to offload CPU? — Extra thread pool hop — only for CPU-bound blocking code.",
      "async void? — Only event handlers — never in services.",
      "ConfigureAwait(false) in every ASP.NET line blindly",
      "async void service methods",
      "Blocking .Result in library"),
    q("Assembly Load Context and Plugins", "Runtime", "Rare",
      "Design plugin architecture in .NET without memory leaks?",
      "`AssemblyLoadContext` collectible contexts unload plugin assemblies. Default ALC loads permanently — plugin reload leaks.",
      "Create collectible `PluginLoadContext`, load plugin DLL, execute, unload context when done.\n\n**Architect:** Plugin systems need isolation — also security sandbox — run untrusted plugins out-of-process.",
      "Plugin architecture is advanced .NET architect topic.",
      "Unload limitations? — References from default context prevent unload — strict boundary.",
      "Roslyn scripting? — Separate ALC per script execution.",
      "Load plugins in default context",
      "No isolation for third-party code",
      "Assume unload always works"),
    q("Distributed Caching Stampede", "Caching", "Common",
      "Cache expires on hot product — 10K requests miss simultaneously?",
      "Cache stampede — use lock per key (mutex), early probabilistic refresh, request coalescing (`HybridCache` in .NET 9), never expire all keys same second.",
      "**Pattern:** first miss acquires lock, others wait or serve stale briefly (`stale-while-revalidate`).\n\n**Redis:** `SETNX` lock key, single flight rebuild.",
      "Stampede prevention is architect-level caching knowledge.",
      "Thundering herd vs stampede? — Same problem — coordinated miss.",
      "Negative caching? — Cache 'not found' briefly — prevent DB hammer.",
      "Identical TTL on all keys",
      "No lock on cache miss",
      "Cache bypass floods DB"),
    q("Source Generator Architecture", "Modern C#", "Occasional",
      "When adopt C# source generators in enterprise platform?",
      "Boilerplate reduction: mapping, DI registration, API clients, validators. Worth when pattern repeats 50+ times and team can maintain generator.",
      "Examples: Mapperly for DTO mapping, compile-time regex, System.Text.Json source context.\n\n**Risk:** debugging harder, build time increase, team skill requirement.\n\nArchitect approves generator use in platform template — not ad-hoc per project.",
      "Generators are platform decision — consistency vs complexity.",
      "Analyzer vs generator? — Analyzer flags issues; generator emits code.",
      "Incremental generator? — Faster builds in large solutions.",
      "Generator for one-off mapping",
      "No documentation for generated code consumers",
      "Build time regression ignored"),
    q("Microservices vs Modular Monolith ADR", "Architecture", "Very Common",
      "Write ADR: stay modular monolith or split to microservices?",
      "Document context: team size 8, 2 deploys/week pain, no K8s ops. Recommendation: modular monolith + strangler for one hot module. Revisit when team >15 or deploy daily required.",
      "**ADR sections:** Status, context, decision, consequences, alternatives rejected.\n\nRejected: full microservices — ops cost exceeds benefit at current scale.",
      "ADR articulation is architect core skill.",
      "When revisit ADR? — Quarterly or on trigger metrics.",
      "Who approves? — Architecture review board or tech lead + EM.",
      "ADR without rejected alternatives",
      "Decision without measurable triggers",
      "ADRs never updated"),
    q("Performance Culture and Budgets", "Performance", "Common",
      "Establish performance culture in .NET organization?",
      "Performance budgets in CI (k6/Gatling gate), mandatory profiling for P0 features, `% Time in GC` and p99 dashboards, blameless postmortems on regressions.",
      "Architect defines non-negotiables: no PR merging if critical path +20% latency in benchmark.\n\nBudget example: search API p99 < 200ms at 1K RPS.",
      "Performance is ongoing architecture governance.",
      "Regression test data? — Record baseline on main branch.",
      "Production profiling? — dotTrace continuous profiler sampling — low overhead.",
      "Optimize without measurement",
      "Performance testing only before release",
      "No production latency SLO"),
    q("Security in .NET API Design", "Security", "Very Common",
      "Architect security checklist for new ASP.NET Core API?",
      "AuthN at edge, authZ policies, input validation, rate limiting, secrets in Key Vault, HTTPS only, security headers, dependency scanning, audit logs.",
      "OWASP API Top 10 mapped to controls. Pen test before public launch.\n\nNever expose internal exception details — ProblemDetails with trace ID only.",
      "Security architecture is part of API design — not separate phase.",
      "BOLA/IDOR? — Authorize every resource access by owner — `{userId}/orders/{id}`.",
      "CORS misconfiguration? — Explicit origins — not `*` with credentials.",
      "JWT in localStorage",
      "Missing authZ on object access",
      "Secrets in appsettings.json"),
    q("Technical Debt Prioritization", "Leadership", "Common",
      "Prioritize technical debt vs features — framework?",
      "Classify debt: interest rate (cost of delay), principal (fix cost), blast radius. High interest + small principal → next sprint. Low interest → backlog.",
      "Quantify: 'missing index costs $4K/month compute' beats 'code smells.'\n\n20% capacity rule for platform/debt — negotiate with product.",
      "Architects quantify debt in business terms.",
      "Strangler reduces debt incrementally? — Preferred over rewrite.",
      "Debt register? — Visible to leadership — not hidden shame.",
      "All debt equal priority",
      "Rewrite without business case",
      "No metrics on debt impact"),
]

WEEK1_EXPERT = [
    q("Go Rewrite Decision", "Architecture", "Common",
      "Team wants Go rewrite for performance. 500 RPS .NET API, p99 80ms.",
      "Profile first — likely DB or network. FARCS: rewrite 6-12 months, retraining, dual maintenance. Optimize .NET: indexes, caching, async I/O, Native AOT if startup. Rewrite only if proven insufficient.",
      "**Response structure:** Acknowledge concern → propose 2-week profiling sprint → decision gate with metrics.\n\n**Stakeholder:** 'Rewrite delays features 2 quarters — data will tell us if runtime is bottleneck.'",
      "Shows judgment under pressure to chase trends.",
      "What metrics prove runtime bottleneck? — CPU <30% but high latency → not CPU language issue.",
      "When Go makes sense? — Small binary edge workers, team already expert.",
      "Blind rewrite approval",
      "No profiling data",
      "Ignoring organizational cost"),
    q("GC Pause Trading System", "Performance", "Common",
      "p99 latency spikes correlate with Gen2 GC in trading-adjacent system.",
      "Reduce allocations in hot path, `ArrayPool`, struct-based tick data, object pooling for orders, consider LOH compaction settings, isolate critical path to dedicated hardware if needed.",
      "**Investigation:** dotMemory during spike, allocation stack traces, LOH size.\n\n**Extreme:** separate process for matching engine with tuned GC settings (`DOTNET_GCName` workstation vs server).",
      "Latency-sensitive .NET requires GC-aware architecture.",
      "Server vs workstation GC? — Server default for ASP.NET — throughput vs latency trade-off.",
      "Native AOT for matching? — Evaluate if reflection-free feasible.",
      "Ignore GC in latency SLA",
      "Allocate per tick in hot loop",
      "Full GC during market hours untuned"),
    q("Monolith Extraction Deadline", "Scenario", "Common",
      "CEO mandates microservices in 6 months. 500K LOC monolith, 30 developers.",
      "Push back with phased strangler plan: Month 1-2 observability + CI, 3-4 extract one bounded context, 5-6 second context. Full decomposition 18-24 months realistic.",
      "Deliver: context map, risk register, what 'microservices' achieves by month 6 (2 services + platform foundations).\n\n**Executive comms:** Tie to business outcomes — deploy frequency, not buzzword.",
      "Architect must negotiate scope with leadership.",
      "What ship in 6 months? — Extracted payment service + API gateway + tracing.",
      "Risk if big bang? — Production outage, team burnout.",
      "Promise full decomposition in 6 months",
      "No incremental value milestones",
      "Skip platform prerequisites"),
    q("Null Reference Production Outage", "Scenario", "Common",
      "NullReferenceException top crash in mobile API after release. Architect response?",
      "Immediate: rollback or hotfix. Week: enable NRT on service, warnings as errors in CI, add null checks at API boundaries, review crash telemetry top stacks.",
      "Root cause: nullable disabled + new DTO field. Prevention: NRT + contract tests + staged rollout with feature flag.",
      "Shows incident + systemic fix thinking.",
      "Blame developer? — Focus on system gates missing.",
      "Feature flag rollback? — Faster than redeploy if integrated.",
      "Fix null check only — no systemic gate",
      "Disable nullable to ship faster",
      "No staged rollout"),
    q("EF Core N+1 Production", "Scenario", "Very Common",
      "Order API p99 2s after feature launch. dotTrace shows 200 SQL queries per request.",
      "N+1 from lazy loading or loop with `Include` missing. Fix: projection query, `AsNoTracking` for reads, split query, or explicit batch load.",
      "**Immediate:** hotfix with `.Include()` or DTO projection. **Long-term:** ban lazy loading in API layer, arch test, query review in PR for data access.",
      "Classic production issue architects must diagnose fast.",
      "Split query EF? — `.AsSplitQuery()` — multiple SQL vs cartesian explosion.",
      "Compiled queries? — Hot path micro-optimization after N+1 fixed.",
      "Lazy loading enabled in web API",
      "No query logging in staging",
      "Ignore SQL count in PR review"),
    q("Memory Leak in Production", "Scenario", "Common",
      "App Service memory grows 8GB over 48 hours until restart.",
      "Capture dump, analyze with dotMemory — static event handlers, undisposed `HttpClient` (pre-IHttpClientFactory), cache without eviction, DI singleton holding scoped services.",
      "**Common .NET leak:** singleton capturing scoped `DbContext`. Fix lifetimes, `IDisposable` audit, memory alert at 70%.",
      "Memory leak triage is operational architect skill.",
      "Dump capture in Azure? — Diagnostic settings memory dump on threshold.",
      "HttpClient anti-pattern? — `new HttpClient()` per request — socket exhaustion.",
      "Ignore slow memory growth",
      "Restart without root cause",
      "Singleton DbContext"),
    q("Breaking API Change Crisis", "Scenario", "Common",
      "Mobile team broken by API field rename — 2M users affected.",
      "Immediate: revert or dual-field compatibility period. Process: API versioning policy, contract tests in CI, deprecation timeline, consumer notification.",
      "Add `Obsolete` field period — return both `customerId` and `clientId` for 2 releases.\n\nArchitect owns API governance policy.",
      "API compatibility is architecture governance.",
      "Consumer-driven contracts? — Pact would catch before prod.",
      "Breaking change in patch version? — Semantic versioning violation.",
      "Rename without version bump",
      "No mobile app lag consideration",
      "No contract tests"),
    q("Thread Pool Starvation", "Scenario", "Common",
      "ASP.NET API hangs under load — thread pool starvation from sync-over-async.",
      "`Task.Result`, `.Wait()`, blocking I/O on thread pool threads. Fix: async all the way, `Task.Run` only for CPU offload with care, diagnose with thread pool starvation events.",
      ".NET 6+ detects starvation — logs warning. Audit codebase for `.Result` in request path.\n\n**Architect:** CI analyzer bans sync-over-async in API projects.",
      "Async discipline prevents mysterious outages.",
      "Min threads config? — Emergency relief — not root fix.",
      "Dedicated thread for CPU work? — `BackgroundService` queue.",
      "Task.Result in controller",
      "sync I/O in async method",
      "Ignore thread pool starvation warnings"),
    q("Choose SQL vs Cosmos for New Service", "Scenario", "Very Common",
      "Product wants global low-latency reads, flexible schema, 50K writes/sec. SQL or Cosmos?",
      "Cosmos if partition key clear, global distribution needed, document model fits. SQL if strong transactions, complex joins, team skill, cost at moderate scale.",
      "Decision matrix presentation to stakeholders with cost estimate. Hybrid: SQL for orders, Cosmos for product catalog.\n\n**Document:** partition key design before Cosmos commitment.",
      "Data store decision is architect signature moment.",
      "Cosmos hot partition? — Validate key cardinality with load test.",
      "SQL scale limits? — Hyperscale or sharding path.",
      "Cosmos because 'NoSQL faster'",
      "SQL without index plan at scale",
      "No partition key design for Cosmos"),
    q("Regulatory Audit Data Residency", "Scenario", "Common",
      "EU regulator audits — customer data stored in US region.",
      "Document data flows, migrate EU tenants to EU region, encryption in transit/at rest, DPA compliance, access logs for cross-border access.",
      "Architecture: geo-routing by tenant residency, separate DB per region, no replication across border without legal basis.\n\n**Remediation plan** with timeline to auditor.",
      "Compliance architecture is increasingly common.",
      "Schrems II implications? — Legal + architect collaboration.",
      "Pseudonymization? — Reduce PII scope — architect enables.",
      "Ignore tenant residency at design",
      "Global single DB for simplicity",
      "No audit trail for data access"),
    q("Black Friday Scale Plan", "Scenario", "Common",
      "10x traffic in 2 weeks — architect checklist?",
      "Load test 12x, scale out app tier, pre-warm cache, CDN, DB connection pool review, rate limit non-critical endpoints, freeze deploys 48h before, war room runbook.",
      "Identify bottleneck from load test — scale that tier. Queue non-critical work. Feature flag disable heavy features if needed.\n\n**Rollback:** one-click scale down + feature flags.",
      "Seasonal scale is planning not improvisation.",
      "Synthetic load shape? — Match previous year traffic curve.",
      "Cost ceiling? — Pre-approve auto-scale max instances.",
      "First load test on Black Friday",
      "Scale DB without app tier",
      "Deploy new feature week before"),
    q("Developer Wants Microservices", "Scenario", "Common",
      "Junior architect proposes 12 microservices for 5-person startup MVP.",
      "Coach: modular monolith, single deploy, extract when pain real. Document Conway's Law — 5 people can't operate 12 services.",
      "Offer compromise: solution structure with clear modules, one database, API boundaries internal — prepare for future extraction.\n\n**Mentoring** not dictating — explain ops cost.",
      "Shows leadership without ego.",
      "Resume-driven architecture? — Name it gently — focus on outcomes.",
      "When agree? — If 5 teams already assigned — different story.",
      "Approve 12 services for MVP",
      "Dismiss without alternative",
      "No mentoring documentation"),
    q("Legacy .NET Framework Migration", "Scenario", "Very Common",
      "400K LOC .NET Framework 4.8 — migrate to .NET 8 strategy?",
      "Assessment: Windows dependencies, ASP.NET WebForms/MVC version, third-party libs. Strangler: new features on .NET 8, bridge via API, migrate module by module. 2-3 year plan typical.",
      "Use .NET Upgrade Assistant for analysis. Not big bang unless small app.\n\n**Interop:** host .NET Framework and .NET 8 side by side during transition.",
      "Migration strategy is bread-and-butter architect work.",
      "Containerize Framework? — Windows containers — ops cost — bridge only.",
      "Entity Framework version jump? — Major effort — plan per module.",
      "Big bang rewrite",
      "Ignore third-party lib blockers",
      "No parallel run period"),
    q("Observability Gap Post-Incident", "Scenario", "Common",
      "4-hour outage — cannot trace request across services. Post-incident architect actions?",
      "Mandate OpenTelemetry, correlation ID middleware, structured logging, distributed tracing dashboard, SLO alerts. Blameless postmortem with action items.",
      "Week 1: trace ID in all logs. Month 1: OTel rollout. Quarter: SLO dashboards per service.\n\n**Prevent:** synthetic monitoring on critical journeys.",
      "Incidents drive observability investment — architect leads.",
      "Log aggregation? — Central ELK/App Insights — query by traceId.",
      "MTTR improvement metric? — Track post-OTel deployment.",
      "Add println debugging only",
      "No postmortem action tracking",
      "Same blind spot next incident"),
    q("Cost Overrun Azure Bill", "Scenario", "Common",
      "Azure bill 3x forecast — CTO escalation.",
      "Cost Explorer: top resources, untagged sprawl, over-provisioned SKUs, verbose logging to Log Analytics, egress, forgotten dev environments.",
      "Quick wins: shutdown dev nights, right-size VMs, log sampling, reserved instances for baseline, budget alerts.\n\n**Architect:** FinOps review in every design going forward.",
      "Cost crisis requires immediate + preventive response.",
      "Log Analytics cost? — Often surprise — retention and ingestion volume.",
      "Zombie resources? — Unattached disks, old snapshots.",
      "Ignore until bill arrives",
      "Cut prod capacity blindly",
      "No tagging — cannot attribute"),
    q("AI Feature in Core Product", "Scenario", "Common",
      "PM wants ChatGPT in checkout flow by next sprint.",
      "Clarify: latency budget, PII handling, cost per request, fallback when API down, prompt injection risks. Propose RAG or API behind feature flag — not inline blocking call.",
      "Architecture: async suggestion service, cache common responses, content safety filter, no card data in prompts.\n\n**ADR:** build vs Azure OpenAI vs third-party.",
      "AI integration requires architect guardrails.",
      "Prompt injection? — Sanitize user input — separate system prompt.",
      "Cost cap? — Token budget per session.",
      "Sync OpenAI in payment path",
      "Send PII to model",
      "No fallback when AI unavailable"),
    q("Team Split Across Timezones", "Scenario", "Occasional",
      "US and India teams — async communication breaking architecture decisions?",
      "ADR documents decisions, architecture decision records in Confluence, recorded design reviews, clear ownership per bounded context, overlap hours for sync decisions only.",
      "Reduce synchronous design meetings — written RFC with comment period. Escalation path for blocking disagreements.",
      "Distributed team process is architect facilitation.",
      "RFC template? — Problem, options, recommendation, deadline.",
      "Decision log? — Single source of truth — avoid Slack-only decisions.",
      "Verbal decisions not documented",
      "No overlap for contentious choices",
      "Architecture by committee without owner"),
    q("Acquire Startup Integrate Stack", "Scenario", "Common",
      "Acquired startup on Node.js + Mongo — integrate with .NET Azure estate?",
      "Assess: retain at boundary via API, strangler migrate high-value modules, or rewrite if tiny. Anti-corruption layer between stacks. Don't force immediate rewrite.",
      "6-month: API gateway routing, SSO integration, observability unified, security policy aligned.\n\n18-month: migrate if business justifies — not ideology.",
      "M&A integration is architect scenario.",
      "Team skill? — Retain Node team for their service initially.",
      "Data sync? — Events between Mongo and SQL — eventual consistency.",
      "Immediate full rewrite",
      "Two security models forever",
      "No ACL at boundary"),
    q("Principal Engineer Disagrees", "Scenario", "Common",
      "Principal proposes event sourcing everywhere. You disagree for CRUD admin module.",
      "Engage with respect: document trade-offs, complexity cost, team skill, propose event sourcing for order aggregate only — CRUD stays simple EF.",
      "Written ADR with both options scored. Escalate to architecture review if stalemate. Data wins — pilot both if needed.",
      "Conflict resolution without ego — architect soft skill.",
      "When principal right? — If audit replay legally required — reconsider.",
      "Pilot scope? — One bounded context — measure complexity.",
      "Acquiesce without discussion",
      "Public undermining",
      "No written trade-off analysis"),
    q("Graduation Readiness Self-Assessment", "Scenario", "Common",
      "Are you ready for Solution Architect interviews after Week 1?",
      "Honest checklist: explain GC/async/value types with production examples, 5 ADRs written, week 1 assessment ≥70%, expert scenarios practiced aloud, identified 3 weak areas with plan.",
      "Week 1 is foundation — revisit weak topics in weeks 45-47 intensive. Record mock answers — compare to premium samples.",
      "Self-assessment honesty expected.",
      "Weak area plan? — Log in progress tracker.",
      "Next practice? — Month 1 Top 50 Q001-Q010.",
      "Overconfidence without practice",
      "Skip expert scenarios",
      "No production examples in answers"),
]
