"""Hand-crafted premium Q011–Q030 for AWS weeks 17–20."""

from premium_qa_data import q

WEEK_17_Q011_Q030 = [
    q("CloudTrail Organization Trail", "Security", "Very Common",
      "Design organization-wide CloudTrail for SOC 2?",
      "Org trail in all regions, log file validation, centralized S3 bucket in log-archive account, SSE-KMS, Object Lock for immutability.",
      "**Architect:** Separate account for logs — developers can't delete audit trail.\n\n**Integration:** CloudTrail → EventBridge → Security Hub for alerts on root login, IAM changes.\n\n**Retention:** Match compliance — 1 year minimum many frameworks.",
      "Audit logging is non-negotiable for enterprise AWS.",
      "Data events vs management events? — S3 object-level optional extra cost.",
      "CloudTrail Lake? — SQL analytics on trails.",
      "Trail only in one region",
      "Logs in same account as workloads",
      "No alerting on root usage"),
    q("AWS Config Rules", "Compliance", "Common",
      "AWS Config for continuous compliance — key rules?",
      "Managed rules: encrypted-volumes, rds-storage-encrypted, s3-bucket-public-read-prohibited, required-tags.",
      "**Architect:** Conformance packs bundle SOC2/PCI rules. Remediation via SSM automation or Lambda.\n\n**Cost:** Config per resource recording — enable where compliance requires.",
      "Config catches drift not just deploy-time policy.",
      "Config aggregator? — Multi-account multi-region view.",
      "Remediation action? — Auto-fix noncompliant SG rule.",
      "Config enabled no rules",
      "Ignore noncompliant report",
      "Manual compliance quarterly only"),
    q("KMS Key Management Strategy", "Security", "Very Common",
      "CMK strategy for RDS, S3, and EBS?",
      "Customer managed CMK per data classification — separate keys prod vs nonprod. Key policy least privilege. Automatic annual rotation.",
      "**Architect:** Grant IAM roles `kms:Decrypt` not `*` on key. CloudTrail logs KMS API calls.\n\n**Multi-account:** CMK in security account with cross-account grant.",
      "Key management is shared responsibility core.",
      "AWS managed vs CMK? — CMK for control and audit.",
      "KMS multi-Region keys? — DR for encrypted data.",
      "One CMK wildcard principal *",
      "No key rotation",
      "Secrets in plaintext beside encrypted data"),
    q("Secrets Manager Rotation", "Security", "Common",
      "Rotate RDS credentials with Secrets Manager?",
      "Secret stores connection string; Lambda rotation function updates DB password and secret version; apps fetch latest via SDK.",
      "**Architect:** No passwords in Parameter Store plaintext for DB. Rotation schedule 30-90 days.\n\n**Apps:** Cache secret with TTL; handle rotation gracefully on auth failure retry.",
      "Automated rotation beats manual password tickets.",
      "Rotation vs manual? — Lambda single-user rotation for RDS.",
      "Cross-account secrets? — Resource policy on secret.",
      "Password in environment variable forever",
      "No rotation on prod DB",
      "App never refreshes cached secret"),
    q("CloudWatch Alarms for SLOs", "Observability", "Very Common",
      "CloudWatch alarms aligned to SLO error budget?",
      "Alarm on ALB 5xx rate, Lambda errors, RDS CPU, custom business metric. Composite alarm reduces noise.",
      "**Architect:** Multi-stage — warning at 50% budget burn, page at 90%. Runbooks linked in alarm description.\n\n**Metric math:** `(errors/requests)*100` over 5 minutes.",
      "Alarms connect metrics to human response.",
      "Anomaly detection alarms? — ML baseline for variable traffic.",
      "Alarm on insufficient data? — Treat missing data as breach for critical.",
      "Alarm every metric no prioritization",
      "No runbook in alarm",
      "PagerDuty on dev environment alarm"),
    q("X-Ray Distributed Tracing", "Observability", "Common",
      "Enable X-Ray across API Gateway, Lambda, ECS?",
      "Active tracing on API GW, Lambda pass-through, ECS daemon or sidecar. Service map shows latency bottlenecks.",
      "**Architect:** Sample rate tune for cost. Correlate with CloudWatch Logs via trace ID.\n\n**OpenTelemetry:** ADOT collector export to X-Ray — portable instrumentation.",
      "Tracing is architect debugging superpower.",
      "X-Ray groups? — Filter traces by service version.",
      "Service lens? — Health dashboard per service.",
      "No tracing production",
      "100% trace always on",
      "Trace without log correlation"),
    q("Service Control Policy Examples", "Governance", "Very Common",
      "Three SCPs every enterprise AWS org needs?",
      "Deny root user actions, deny unencrypted S3 upload, restrict regions to approved list.",
      "**Architect:** SCPs don't grant — only filter max permissions. Test in sandbox OU before prod MG.\n\n**Exemption:** Break-glass OU without region deny but heavily monitored.",
      "SCPs are guardrails not IAM replacement.",
      "SCP inheritance? — All OUs below inherit.",
      "FullAWSAccess SCP? — Still need explicit attach.",
      "SCP on root without testing",
      "Think SCP grants permissions",
      "No exemption process"),
    q("IAM Access Analyzer", "Security", "Common",
      "Use IAM Access Analyzer in CI/CD?",
      "Identifies resources shared externally — S3 public, KMS keys, IAM roles trust external accounts.",
      "**Architect:** Run in pipeline on Terraform plan — fail PR if unintended public access.\n\n**Unused access analyzer:** Right-size IAM policies — remove stale permissions.",
      "External access findings prevent breaches.",
      "Archive rules? — Suppress known intentional findings.",
      "Zone of trust? — Organization as trust boundary.",
      "Ignore Access Analyzer findings",
      "Public S3 discovered at audit",
      "Overly broad resource * in policy"),
    q("AWS Systems Manager", "Operations", "Common",
      "Systems Manager for patch and session management?",
      "SSM Patch Manager baselines for EC2, Session Manager replaces SSH with audited access, Parameter Store for config hierarchy.",
      "**Architect:** No SSH keys on instances — Session Manager IAM-based. Patch windows with maintenance windows.\n\n**Hybrid:** SSM agent on-prem via activation.",
      "SSM is modern EC2 operations default.",
      "Run command vs State Manager? — Ad hoc vs desired state.",
      "Parameter Store vs Secrets Manager? — Secrets for credentials; Param for config.",
      "SSH port 22 open world",
      "Manual patching prod fleet",
      "Secrets in Parameter Store String"),
    q("AWS Trusted Advisor", "Operations", "Occasional",
      "Trusted Advisor vs Cost Explorer vs Compute Optimizer?",
      "Trusted Advisor: high-level checks (support tier). Cost Explorer: spend analysis. Compute Optimizer: ML rightsizing.",
      "**Architect:** Monthly review all three dashboards. Trusted Advisor security checks on Business+ support.\n\n**Automate:** Export recommendations to ticketing.",
      "Operational excellence uses AWS advisory tools.",
      "Trusted Advisor API? — Automate report to S3.",
      "Priority support benefit? — TA full checks.",
      "Never review recommendations",
      "Ignore security TA checks",
      "Rightsizing once never again"),
    q("Cost Explorer and CUR", "FinOps", "Common",
      "Cost and Usage Report vs Cost Explorer?",
      "Cost Explorer: interactive dashboards. CUR: detailed line-item export to Athena/S3 for custom analysis.",
      "**Architect:** CUR with hourly granularity for chargeback. Athena queries by tag CostCenter.\n\n**Unit economics:** Join CUR with application metrics table.",
      "FinOps needs granular data export.",
      "CUR parquet? — Efficient Athena queries.",
      "Data exports new? — Simpler than legacy CUR setup.",
      "Invoice surprise no CUR",
      "Untagged resources 40% spend",
      "No monthly cost review"),
    q("Savings Plans vs Reserved Instances", "FinOps", "Common",
      "Savings Plans vs RI for steady .NET on EC2?",
      "Compute Savings Plans flexible across instance family/region. Standard RI cheapest for fixed size. Convertible RI for migration flexibility.",
      "**Architect:** 1-year SP baseline after 3 months stable usage. Analyze in Cost Explorer recommendations.\n\n**Don't:** Buy 3-year RI day one of new product.",
      "Commitment discounts need usage stability proof.",
      "SP EC2 Instance SP vs Compute SP? — Compute SP broader.",
      "RI marketplace? — Sell unused RI.",
      "On-Demand only at scale always",
      "RI wrong instance family locked",
      "No utilization monitoring"),
    q("AWS Support Tiers", "Operations", "Occasional",
      "When upgrade to Business or Enterprise Support?",
      "Business: production workloads needing <1hr response on urgent. Enterprise: mission-critical, TAM, concierge routing.",
      "**Architect:** Business minimum for prod accounts with Trusted Advisor full. Enterprise for regulated/large estate.\n\n**Cost:** % of monthly spend — model in TCO.",
      "Support tier is insurance policy.",
      "AWS Health Dashboard? — All tiers — personalized events.",
      "Support case severity? — Know when Sev1 justified.",
      "Basic support prod outage",
      "Enterprise without TAM engagement",
      "No runbook before opening case"),
    q("Shared Responsibility Model Depth", "Security", "Very Common",
      "Explain shared responsibility for EC2 vs Lambda vs RDS?",
      "EC2: you patch OS, AWS patches hypervisor. Lambda: AWS manages runtime, you manage code/IAM. RDS: AWS manages DB engine patch, you manage schema/access.",
      "**Interview:** Map each service to who patches, encrypts, configures network.\n\n**Architect:** Misunderstanding causes compliance gaps — 'AWS is secure' without customer duties.",
      "Shared responsibility is AWS interview foundation.",
      "Customer responsibility matrix? — Download per service.",
      "Compliance inheritance? — You still certify workload config.",
      "Assume AWS handles all security",
      "Unpatched EC2 AMI in prod",
      "Lambda with wild IAM role"),
    q("Multi-Account Strategy Pitfalls", "Governance", "Common",
      "Common mistakes in AWS multi-account design?",
      "Too many accounts unmanageable, no centralized logging, inconsistent SCPs, VPC per account without TGW plan, manual account creation.",
      "**Architect:** Landing zone with Control Tower, account vending automation, guardrails at OU level.\n\n**Balance:** Isolation vs operational overhead.",
      "Account strategy errors are expensive to fix.",
      "Account per developer? — Usually excessive.",
      "Consolidated billing? — Required for org benefits.",
      "50 accounts no org structure",
      "Duplicate VPC CIDRs",
      "No log archive account"),
    q("Control Tower Guardrails", "Landing Zone", "Common",
      "AWS Control Tower guardrails — mandatory vs elective?",
      "Mandatory: disallow public RDS, require encryption. Elective: allowed regions, approved instance types.",
      "**Architect:** Enable mandatory set on prod OU; elective customized per workload OU.\n\n**Drift:** Control Tower detects drift from baseline — remediate or document exception.",
      "Guardrails operationalize governance at scale.",
      "Custom guardrails? — Lambda-based proactive controls.",
      "Account Factory baseline? — VPC config per new account.",
      "Control Tower without guardrail review",
      "Disable guardrail for convenience",
      "No drift detection process"),
    q("Account Vending Automation", "Platform", "Common",
      "Automate new AWS account provisioning?",
      "Control Tower Account Factory, AFT (Account Factory for Terraform), or Service Catalog — pipeline creates account, applies SCPs, VPC baseline.",
      "**Architect:** Self-service portal for teams with guardrails — not ticket to cloud team for 2 weeks.\n\n**Inputs:** Account email, OU placement, tags, network CIDR from IPAM.",
      "Vending scales cloud adoption.",
      "AFT vs CFCT? — Terraform vs Control Tower native customization.",
      "IPAM integration? — Avoid CIDR collisions.",
      "Manual console account create",
      "No baseline applied new account",
      "Account sprawl untracked"),
    q("Break-Glass Account Procedure", "Security", "Common",
      "Design break-glass emergency access?",
      "Separate account or root MFA hardware keys in physical safe; CloudTrail alert on any use; post-incident review mandatory; time-limited credentials.",
      "**Architect:** Break-glass excluded from SCP deny root only with dual control. Runbook documents when authorized.",
      "Emergency access without procedure is liability.",
      "PIM equivalent AWS? — No exact — process + monitoring.",
      "Disable break-glass creds after? — Rotate and audit.",
      "Daily admin uses break-glass",
      "No alert on break-glass use",
      "Shared break-glass password"),
    q("AWS Outage Communication", "Operations", "Common",
      "During AWS regional outage — architect actions?",
      "Check Service Health Dashboard, communicate ETA unknown honestly, fail over if DR ready, disable non-critical jobs, post-mortem after.",
      "**Architect:** Pre-written status comms template. DR drill proves failover works — not first attempt during outage.\n\n**Don't:** Promise recovery time without data.",
      "Calm communication is leadership skill.",
      "Personal Health Dashboard? — Subscribe RSS per service.",
      "Multi-region failover test frequency? — Quarterly minimum critical.",
      "No DR plan documented",
      "First failover attempt during outage",
      "Blame AWS publicly without internal review"),
    q("AWS Health Dashboard Subscriptions", "Operations", "Common",
      "Personal Health Dashboard and EventBridge integration?",
      "Subscribe to service events affecting your account; EventBridge rules trigger SNS/Slack on `AWS Health API` events.",
      "**Architect:** Automated comms to status page internal channel. Runbooks per critical service (RDS, ECS, DynamoDB).\n\n**Proactive:** Plan maintenance windows from scheduled events.",
      "Health events should drive automated response.",
      "Organization view health? — Aggregated across accounts.",
      "Affected entities API? — Identify impacted resources.",
      "Learn outage from customers first",
      "No EventBridge health rules",
      "Ignore scheduled maintenance events"),
]

WEEK_18_Q011_Q030 = [
    q("EC2 Instance Type Selection", "Compute", "Very Common",
      "Choose EC2 family for .NET API workload?",
      "General purpose m7g/m7i for APIs. Compute optimized c7 for CPU-heavy. Memory r7 for large in-memory cache. Graviton if ARM-validated.",
      "**Architect:** Start m-family right-sized; benchmark before jumping to xlarge. Burst T-family dev only.\n\n**Rightsizing:** Compute Optimizer recommendations monthly.",
      "Instance selection drives cost and performance.",
      "Metal instances? — Bare metal niche compliance.",
      "Dedicated hosts? — License compliance Oracle/SQL legacy.",
      "largest instance without profiling",
      "T3 unlimited prod API surprise bill",
      "Wrong architecture ARM incompatible"),
    q("Launch Templates and AMIs", "Compute", "Common",
      "Golden AMI vs launch template user data?",
      "Golden AMI: baked dependencies fast boot. Launch template: cloud-init installs latest on boot — more flexible.",
      "**Architect:** Packer builds golden AMI in CI; ASG uses launch template version. Immutable infrastructure pattern.",
      "Image strategy affects deploy speed and drift.",
      "EC2 Image Builder? — Managed pipeline for AMIs.",
      "Launch template versioning? — Rollback ASG to prior version.",
      "Manual SSH install packages",
      "No AMI refresh patching",
      "Mutable servers pet model"),
    q("ECS Task Definitions", "Containers", "Common",
      "Design ECS task definition for .NET container?",
      "CPU/memory limits, awsvpc networking, secrets from Secrets Manager, health check, logging to awslogs driver.",
      "**Architect:** Task role vs execution role — execution pulls image/secrets; task role app AWS API access.\n\n**Sidecar:** ADOT collector for traces.",
      "Task definition is container deploy contract.",
      "Fargate vs EC2 launch type? — Fargate serverless; EC2 more control.",
      "Task placement constraints? — GPU instance type.",
      "Secrets in task definition plaintext",
      "No health check container",
      "Task role AdministratorAccess"),
    q("EKS Cluster Autoscaler", "Kubernetes", "Common",
      "EKS cluster autoscaler vs Karpenter?",
      "Cluster Autoscaler scales ASG node groups. Karpenter provisions nodes dynamically per pod requirements — faster scale.",
      "**Architect:** Karpenter preferred greenfield EKS .NET workloads. Define NodePool limits for cost cap.\n\n**Watch:** Pod disruption budgets during scale-in.",
      "Node autoscaling prevents pending pods stuck.",
      "Karpenter consolidation? — Remove empty nodes.",
      "Multiple node groups? — Spot + on-demand split.",
      "Fixed 10 nodes always",
      "No PDB on critical deployment",
      "Autoscaler without resource requests"),
    q("Lambda Layers", "Serverless", "Common",
      "When use Lambda layers for .NET?",
      "Share dependencies across functions — common libraries, native deps, ADOT layer — reduce deployment package size.",
      "**Limit:** 5 layers per function, 250MB unzipped total.\n\n**Architect:** Layer for approved internal SDK version — central update.",
      "Layers manage shared dependency versions.",
      "Layer versioning? — Pin function to layer version.",
      ".NET layer custom runtime? — Native deps packaging.",
      "Duplicate 50MB lib per function",
      "Unversioned layer breaking change",
      "Layer exceeds size limit"),
    q("Lambda Destinations on Failure", "Serverless", "Common",
      "Lambda failure handling with destinations and DLQ?",
      "Async invoke: on-failure destination to SQS/SNS/Lambda. Sync: return error to client. DLQ for event source mapping.",
      "**Architect:** Destinations for observability routing — not silent drop. Idempotent failure handler.\n\n**Retry:** Event source mapping retry policy vs function async retry.",
      "Failure paths must be designed not accidental.",
      "On-success destination? — Chain async workflows.",
      "Bisect batch on failure? — Partial batch response SQS.",
      "No DLQ on SQS trigger",
      "Infinite retry poison message",
      "Lost failed events silent"),
    q("Step Functions Orchestration", "Serverless", "Common",
      "Step Functions for order saga vs Lambda chain?",
      "Step Functions: visual state machine, built-in retry/catch, long-running, human approval steps.",
      "**Architect:** Express workflows high volume short; Standard workflows sagas minutes-days.\n\n**.NET:** Lambda tasks or ECS run task integration.",
      "Orchestration visibility beats hidden Lambda chains.",
      "Callback pattern? — Wait for external token.",
      "Map state parallel? — Bulk processing.",
      "15 Lambda sync chain",
      "Saga state in Lambda memory",
      "No compensation path defined"),
    q("EventBridge vs SNS vs SQS", "Messaging", "Very Common",
      "Choose EventBridge, SNS, or SQS?",
      "SQS: point-to-point queue, pull, ordering option. SNS: fan-out pub/sub push. EventBridge: event bus routing rules, schema registry, SaaS integration.",
      "**Architect:** EventBridge default enterprise event backbone. SNS+SQS fan-out pattern classic. SQS worker queues.",
      "Wrong messaging choice hurts coupling and scale.",
      "FIFO vs standard SQS? — FIFO ordering cost.",
      "EventBridge archive replay? — Debug and reprocess.",
      "SNS email for critical path",
      "No DLQ on queue consumer",
      "EventBridge no schema governance"),
    q("Elastic Beanstalk Environments", "Compute", "Occasional",
      "Beanstalk environment tiers and deployment policies?",
      "WebServer vs Worker environment. Rolling, rolling with batch, immutable, traffic splitting deployments.",
      "**Architect:** Immutable deploy for zero-downtime config safety. Worker tier for SQS-driven background.",
      "Beanstalk still valid for simple .NET hosting.",
      "Platform branch .NET? — Windows vs Linux platform.",
      "EB CLI vs console? — IaC prefer CloudFormation generated.",
      "Single instance prod Beanstalk",
      "AllAtOnce deploy prod",
      "Ignore health check red"),
    q("AWS App Runner", "Compute", "Occasional",
      "App Runner vs ECS Fargate for container API?",
      "App Runner: simplest — connect repo/ECR, auto scale, built-in load balancer. ECS: more control, VPC, service mesh.",
      "**Architect:** App Runner internal tools and MVPs. ECS/EKS enterprise microservices.",
      "Simplicity vs control trade-off.",
      "App Runner VPC connector? — Reach private RDS.",
      "Custom domain TLS? — App Runner managed cert.",
      "App Runner for complex mesh",
      "ECS for hello-world only",
      "No VPC connector to private DB"),
    q("Fargate Task Networking", "Networking", "Common",
      "Fargate awsvpc networking and security groups?",
      "Each task gets ENI — security group per task/service. Private subnets + NAT for outbound internet.",
      "**Architect:** Security group least privilege — ALB SG → task SG only on app port.\n\n**Cost:** NAT Gateway per AZ — use VPC endpoints.",
      "Fargate networking affects security and cost.",
      "Service Connect vs Cloud Map? — ECS service discovery.",
      "Public IP on task? — Avoid — use ALB ingress.",
      "0.0.0.0/0 egress task SG",
      "Tasks in public subnet unnecessary",
      "No endpoint S3 through NAT"),
    q("SSM Session Manager Access", "Operations", "Common",
      "Replace SSH with Session Manager?",
      "IAM-based shell access, logged to S3/CloudWatch, no bastion host, port 22 closed.",
      "**Architect:** Require MFA for Session Manager IAM policy. Session logs retained for audit.\n\n**Port forwarding:** Tunnel to RDS through instance.",
      "Bastion elimination reduces attack surface.",
      "Session Manager preferences? — Log encryption KMS.",
      "Hybrid activations? — On-prem servers.",
      "SSH keys on all EC2",
      "Bastion no patching",
      "Session logs not retained"),
    q("Parameter Store Hierarchy", "Config", "Common",
      "SSM Parameter Store hierarchy design?",
      "/app/prod/database/host — path convention per env and service. Standard vs advanced parameters.",
      "**Architect:** Advanced for secrets with policies; Secrets Manager for rotation. IaC references parameters not hardcode.",
      "Hierarchy prevents config chaos.",
      "StringList parameters? — Multiple values.",
      "Policy on parameter? — IAM resource-level.",
      "Flat parameter names",
      "Secrets in String not SecureString",
      "Prod param in dev path typo"),
    q("CloudWatch Logs Insights", "Observability", "Common",
      "Query patterns in Logs Insights for incident?",
      "Filter `@message like /Exception/`, stats count by bin(5m), parse JSON fields, correlate traceId.",
      "**Architect:** Structured JSON logging mandatory. Saved queries for common incidents.\n\n**Cost:** Log retention 30-90d hot; archive S3 Glacier.",
      "Log query skill speeds MTTR.",
      "Contributor Insights? — Find noisy log sources.",
      "Metric filters on logs? — Custom metrics from log pattern.",
      "Unstructured grep only",
      "Infinite log retention",
      "No saved queries runbook"),
    q("ECR Image Scanning", "Security", "Common",
      "ECR vulnerability scanning in CI/CD?",
      "Scan on push, fail pipeline on critical CVE, enhance scanning for OS and language deps.",
      "**Architect:** Pin base image digest not `:latest`. Renovate base image updates weekly.\n\n**Lambda:** Container image same scanning discipline.",
      "Supply chain security includes images.",
      "Inspector vs basic scan? — Enhanced deeper.",
      "Private ECR replication? — DR images region.",
      "latest tag prod deploy",
      "Ignore critical CVE",
      "Public Docker Hub prod"),
    q("CodeDeploy Blue/Green", "Deployment", "Common",
      "CodeDeploy blue/green for ECS/ASG?",
      "Parallel green environment, traffic shift via ALB, automatic rollback on CloudWatch alarm, terminate blue after success.",
      "**Architect:** Hook scripts run integration tests on green before shift. Deployment configuration minimum healthy hosts.",
      "Blue/green reduces deploy risk.",
      "Canary traffic shift? — Linear 10% increments.",
      "CodeDeploy vs Argo? — AWS-native vs K8s GitOps.",
      "In-place deploy prod only",
      "No rollback alarm",
      "Skip validation hook"),
    q("CodePipeline Architecture", "CI/CD", "Common",
      "Multi-account CodePipeline with OIDC?",
      "Source GitHub → build CodeBuild → deploy cross-account via OIDC role assumption — no long-lived keys.",
      "**Architect:** Separate tooling account pipelines; deploy role trust GitHub OIDC subject repo:branch.\n\n**Artifacts:** S3 encrypted between stages.",
      "Pipeline security is architect CI/CD topic.",
      "Manual approval stage? — Prod gate.",
      "Parallel actions? — Build and test split.",
      "Access keys in CodeBuild env",
      "Deploy role * on *",
      "No approval prod deploy"),
    q("SAM vs CDK vs Terraform", "IaC", "Common",
      "Choose SAM, CDK, or Terraform for AWS .NET serverless?",
      "SAM: Lambda/API GW focused simple. CDK: .NET constructs, L2 abstractions, good for mixed AWS. Terraform: multi-cloud, large community.",
      "**Architect:** Team skill matters. CDK if all .NET shop on AWS. Terraform if multi-cloud standard.\n\n**Testing:** cdk synth in CI; tf plan review.",
      "IaC choice affects velocity and portability.",
      "CloudFormation raw? — Verbose — CDK generates.",
      "SAM local invoke? — Dev Lambda test.",
      "Console deploy prod",
      "No plan review CI",
      "Mixed IaC tools per resource random"),
    q(".NET on Lambda Packaging", "Serverless", "Common",
      "Package .NET 8 Lambda — best practices?",
      "Trimmed publish, ReadyToRun optional, native deps for arm64 Graviton, container image if package >50MB.",
      "**Architect:** Provisioned concurrency for API Lambda after measuring cold start.\n\n**Logging:** Structured JSON to CloudWatch.",
      "Packaging affects cold start and cost.",
      "Lambda Annotations framework? — Simplified attribute model.",
      "AOT Lambda? — Experimental constraints check.",
      "Full framework self-contained always huge",
      "Ignore cold start metrics",
      "x86 only without ARM test"),
    q("Compute Selection ADR Framework", "Process", "Very Common",
      "ADR framework: EC2 vs ECS vs EKS vs Lambda?",
      "Forces: team skill, traffic pattern, scale-to-zero need, VPC integration, ops overhead, cost model.",
      "**Decision matrix:** Score 1-5; weight by business priority. Document rejected options.\n\n**Review:** Revisit ADR when traffic 10x or team doubles.",
      "Structured compute choice impresses interviewers.",
      "Reversibility? — Note migration cost if wrong.",
      "PoC spike timebox? — 1 week validate Lambda cold start.",
      "EKS because trendy",
      "Lambda for 10K RPS steady",
      "No documented decision"),
]

# Weeks 19-20 continue in same file - split for manageability
WEEK_19_Q011_Q030 = [
    q("VPC Flow Logs", "Networking", "Common",
      "VPC Flow Logs for security and debugging?",
      "Capture accepted/rejected traffic to S3 or CloudWatch. Analyze rejected flows for SG misconfiguration.",
      "**Architect:** Enable on all prod VPCs. Athena queries on S3 parquet flow logs.\n\n**Cost:** Log volume — sample or filter if needed.",
      "Flow logs prove network debugging skill.",
      "Custom format fields? — pkt-srcaddr,pkt-dstaddr,action.",
      "Traffic Mirroring? — Deep packet inspection niche.",
      "No flow logs prod",
      "Ignore REJECT patterns",
      "Overly broad 0.0.0.0/0 undetected"),
    q("PrivateLink Interface Endpoints", "Networking", "Common",
      "Interface endpoint for SaaS and AWS services?",
      "Private connectivity without internet — other AWS accounts publish endpoint service; consumers create interface endpoint in VPC.",
      "**Architect:** Cost per AZ endpoint + data processing — model in TCO.\n\n**Security:** Endpoint policy restricts principals.",
      "PrivateLink is enterprise connectivity pattern.",
      "Gateway vs Interface? — S3/Dynamo gateway; most others interface.",
      "Cross-region endpoint? — PrivateLink limitations apply.",
      "All traffic over internet to SaaS",
      "No endpoint policy",
      "Forget endpoint per-AZ cost"),
    q("AWS WAF on ALB", "Security", "Common",
      "AWS WAF rules for public API?",
      "Managed rule groups (Core, KnownBadInputs), rate-based rule, geo block if needed, custom SQLi/XSS.",
      "**Architect:** WAF in front of ALB/API GW. Log to S3/CloudWatch. Tune false positives in count mode first.",
      "WAF is edge defense layer.",
      "WAF vs Shield? — WAF app layer; Shield DDoS.",
      "Bot Control rule? — Extra cost bot management.",
      "WAF disabled cost saving",
      "Block mode day one no tune",
      "No WAF logs"),
    q("Shield Standard vs Advanced", "Security", "Occasional",
      "Shield Advanced when justify cost?",
      "Standard free DDoS protection all customers. Advanced: cost protection, DRT access, detailed metrics — high revenue sites.",
      "**Architect:** Advanced for DDoS risk business case — ecommerce, fintech. Standard sufficient many B2B APIs.",
      "DDoS protection is availability topic.",
      "Route 53 Shield? — DNS layer protection.",
      "CloudFront + Shield? — Edge combined.",
      "Assume impossible to DDoS",
      "Advanced without DRT runbook",
      "No game day DDoS sim"),
    q("S3 Pre-Signed URLs", "Storage", "Very Common",
      "Secure large file upload/download with pre-signed URLs?",
      "Client requests URL from API; API generates PUT/GET pre-signed with expiry; client uploads direct to S3 — offloads API bandwidth.",
      "**Architect:** Short expiry (15 min). Limit content-type and size. Virus scan on S3 event post-upload.",
      "Pre-signed pattern is scalable file transfer.",
      "SSE-KMS pre-signed? — KMS permissions on signer role.",
      "POST policy alternative? — Browser form upload.",
      "Public bucket upload",
      "Long expiry 7 days",
      "No malware scan user upload"),
    q("S3 Cross-Region Replication", "DR", "Common",
      "CRR for compliance and DR?",
      "Async replicate objects to second region bucket. Requires versioning both sides. RTC option for tighter RPO.",
      "**Architect:** Replicate encrypted with KMS multi-Region keys plan. Lifecycle on replica bucket.\n\n**Cost:** Replication + storage + egress.",
      "CRR is DR building block not full failover alone.",
      "Bidirectional replication? — Conflict handling needed.",
      "S3 RTC? — 15 min RPO guarantee extra cost.",
      "Single region prod no backup",
      "CRR without failover runbook",
      "Ignore replication lag RPO"),
    q("RDS Proxy Connection Pooling", "Database", "Very Common",
      "RDS Proxy for Lambda → RDS connection storm?",
      "Proxy pools DB connections; Lambda scales without exhausting max_connections on RDS.",
      "**Architect:** IAM auth through proxy optional. Pin proxy in same VPC private subnets.\n\n**Not for:** All apps — adds latency slight — use when connection count problem proven.",
      "Connection pooling is serverless + RDS pattern.",
      "Proxy vs PgBouncer? — AWS managed vs self.",
      "Read/write splitting proxy? — RDS Proxy targets single cluster.",
      "1000 Lambda max connections RDS",
      "No proxy IAM auth",
      "Proxy public subnet"),
    q("Aurora Global Database", "Database", "Common",
      "Aurora Global for cross-region DR?",
      "Primary region read/write; secondary regions read replica <1s lag typical; promote secondary for DR.",
      "**Architect:** RPO sub-second typical; RTO minutes for promoted cluster. Application DNS failover required.\n\n**Cost:** Secondary cluster running always.",
      "Global database is premium DR option.",
      "Write forwarding? — Secondary can forward writes to primary.",
      "Backtrack? — Rewind cluster mistake — not global.",
      "Cross-region async only manual",
      "No promote drill",
      "App hardcoded primary endpoint"),
    q("DynamoDB DAX", "NoSQL", "Occasional",
      "When DynamoDB Accelerator (DAX)?",
      "Microsecond read cache for DynamoDB hot keys — session store, read-heavy leaderboard.",
      "**Architect:** App must use DAX SDK cluster endpoint. Eventually consistent reads from cache.\n\n**Skip:** If ElastiCache Redis already standard team skill.",
      "DAX is specialized performance tool.",
      "DAX vs CloudFront? — Different layers.",
      "Item cache TTL? — DAX manages invalidation on write.",
      "DAX for write-heavy workload",
      "Cache stale reads surprise",
      "DAX without TLS"),
    q("DynamoDB Streams", "Integration", "Common",
      "DynamoDB Streams use cases?",
      "CDC from table — Lambda consumer updates search index, triggers audit, materialized view sync.",
      "**Architect:** Exactly-once processing with idempotent Lambda. Parallelization factor tune.\n\n**Ordering:** Per partition key sequence preserved.",
      "Streams enable event-driven on NoSQL.",
      "Stream vs Kinesis? — DynamoDB native vs custom stream.",
      "TTL deletes in stream? — Yes records appear.",
      "Poll table scan instead stream",
      "Non-idempotent consumer",
      "Ignore iterator age alarm"),
    q("ElastiCache Redis Cluster", "Caching", "Common",
      "ElastiCache Redis cluster mode vs single node?",
      "Cluster mode: horizontal scale, sharding. Single node: simple session cache small scale.",
      "**Architect:** Multi-AZ with automatic failover production. Auth token enabled. Encryption in transit and at rest.",
      "Redis architecture affects HA and scale.",
      "Redis vs Memcached ElastiCache? — Redis data structures richer.",
      "Global datastore? — Cross-region Redis DR.",
      "Single node prod cache",
      "No AUTH token",
      "Cache as primary database"),
    q("Amazon MQ vs MSK", "Messaging", "Common",
      "ActiveMQ/RabbitMQ (Amazon MQ) vs MSK (Kafka)?",
      "Amazon MQ: traditional brokers, JMS, small teams migrating on-prem. MSK: Kafka ecosystem, high throughput event streaming.",
      "**Architect:** MSK for event backbone scale. MQ for legacy JMS integration short term.",
      "Broker choice is long-term commitment.",
      "MSK Serverless? — Simpler ops Kafka.",
      "MQ maintenance? — AWS patches broker.",
      "Kafka for 10 msgs/day",
      "MQ for greenfield streaming",
      "No topic governance MSK"),
    q("Direct Connect vs Site-to-Site VPN", "Hybrid", "Very Common",
      "Direct Connect vs VPN for hybrid cloud?",
      "DX: dedicated private link, predictable latency, higher setup time/cost. VPN: IPsec over internet, quick, backup path.",
      "**Architect:** DX primary + VPN backup standard enterprise. VIF virtual interfaces routing BGP.",
      "Hybrid connectivity is architect interview staple.",
      "DX Gateway? — Connect DX to multi-VPC.",
      "MACsec encryption? — Line encryption DX.",
      "VPN only production no redundancy",
      "DX single location",
      "No BGP failover test"),
    q("Route 53 Health Checks Deep", "DNS", "Common",
      "Route 53 health check types and failover?",
      "HTTP/HTTPS, TCP, CloudWatch alarm, calculated health checks combine children.",
      "**Architect:** Health check every 30s; insufficient data handling define. Latency charts for routing decisions.",
      "DNS health drives failover automation.",
      "Private health checks? — Internal resources VPC.",
      "Health check regions? — Multiple probe locations.",
      "Health check wrong path /",
      "Failover untested 6 months",
      "TTL 86400 during migration"),
    q("AWS Network Firewall", "Security", "Common",
      "Network Firewall vs NACL vs SG?",
      "SG: stateful instance level. NACL: stateless subnet edge. Network Firewall: deep inspection, IDS/IPS, domain filtering centralized.",
      "**Architect:** Network Firewall in centralized egress VPC — domain allowlist outbound.",
      "Layered network security model.",
      "Suricata rules? — Custom IDS signatures.",
      "TLS inspection? — Complex compliance need.",
      "Only SG no defense in depth",
      "0.0.0.0/0 egress all",
      "Firewall misrule blocks prod"),
    q("Gateway Load Balancer", "Networking", "Occasional",
      "GWLB for inline security appliances?",
      "Transparent bump-in-wire scaling third-party firewalls/IDS across VPC.",
      "**Architect:** Niche — regulated industries. Consumer endpoint routes to GWLB endpoint ENI.",
      "Know GWLB exists for security architecture interviews.",
      "Endpoint fail open? — Risk if appliance down.",
      "Vendor appliance AMI? — Partner integrations.",
      "GWLB for simple API",
      "Single appliance SPOF",
      "No health check appliance"),
    q("AWS Backup Centralized", "DR", "Common",
      "AWS Backup for cross-service policy?",
      "Central backup plans: EBS, RDS, DynamoDB, EFS, S3 — vault lock immutability, cross-region copy.",
      "**Architect:** Tag-based backup selection `Backup=daily`. Separate vault prod/nonprod.\n\n**Restore drill:** Quarterly restore test documented.",
      "Unified backup beats per-service scripts.",
      "Backup Audit Manager? — Compliance reporting.",
      "Legal hold? — WORM vault lock.",
      "Manual snapshots only",
      "Never tested restore",
      "Backup vault same account delete risk"),
    q("EFS vs FSx", "Storage", "Occasional",
      "EFS vs FSx for Windows/Lustre?",
      "EFS: NFS Linux shared files. FSx Windows: SMB .NET legacy shared files. FSx Lustre: HPC ML high throughput.",
      "**Architect:** EFS for container shared config rare cases. FSx when Windows file share required.",
      "File storage choice by protocol and performance.",
      "EFS Infrequent Access? — Cost tier lifecycle.",
      "FSx backup? — AWS Backup support.",
      "EFS for database files",
      "FSx overkill static assets",
      "No performance mode plan"),
    q("Data Transfer Pricing Traps", "FinOps", "Very Common",
      "Hidden AWS data transfer costs?",
      "Cross-AZ traffic, NAT Gateway processing, cross-region replication, internet egress, inter-AZ ELB to targets.",
      "**Architect:** Model in architecture review — same-AZ placement where possible; endpoints reduce NAT.\n\n**Calculator:** Pricing calculator before design sign-off.",
      "Egress ignorance kills cloud budget.",
      "CloudFront reduce origin egress? — Cache hit ratio.",
      "PrivateLink data processing? — Still charged.",
      "Chatty cross-AZ microservices",
      "No cost allocation tags",
      "Surprise NAT GB bill"),
    q("Network Architecture Review Checklist", "Process", "Common",
      "Network architecture review checklist?",
      "CIDR plan, subnet tiers, SG least privilege, NACL defense, endpoints vs NAT, flow logs, WAF, hybrid connectivity, DR DNS.",
      "**Architect deliverable:** Diagram + table of every ingress/egress path with justification.\n\n**Security:** No 0.0.0.0/0 on admin ports.",
      "Checklist shows thorough senior review.",
      "IPAM integration? — Prevent overlap multi-VPC.",
      "Network segmentation test? — Pen test validation.",
      "Flat network all public",
      "Diagram outdated",
      "Review once never again"),
]

WEEK_20_Q011_Q030 = [
    q("Terraform Multi-Cloud Modules", "IaC", "Common",
      "Structure Terraform for Azure and AWS modules?",
      "Root modules `env/prod/azure`, `env/prod/aws`; shared `modules/networking` with provider-specific submodules; remote state per env.",
      "**Architect:** DRY where safe — don't force identical module interface where clouds differ.\n\n**CI:** `terraform plan` on PR both providers.",
      "IaC structure enables multi-cloud ops.",
      "Terragrunt wrappers? — DRY backend config.",
      "State locking? — DynamoDB AWS; blob Azure.",
      "One state file all clouds",
      "No plan review",
      "Copy-paste modules diverge"),
    q("Pulumi vs Terraform Team Choice", "IaC", "Common",
      "Pulumi (.NET) vs Terraform (HCL) for dual-cloud team?",
      "Pulumi: C# infrastructure, IDE support, unit test IaC. Terraform: HCL standard, larger module ecosystem.",
      "**Architect:** All-.NET platform team may prefer Pulumi. Multi-team org often standardizes Terraform.",
      "Team skill drives IaC language choice.",
      "CDKTF? — Terraform from TypeScript/C#.",
      "Import existing resources? — Both support.",
      "Two IaC languages no standard",
      "IaC not in CI",
      "Manual hotfix drift"),
    q("Kubernetes Portability EKS/AKS", "Containers", "Common",
      "Portable Kubernetes between EKS and AKS?",
      "Standard K8s APIs portable; ingress, storage class, IAM differ — abstract with Helm values per cloud.",
      "**Architect:** Avoid cloud-specific operators in portable core. GitOps (Argo CD) same workflow both.",
      "K8s portability is partial not absolute.",
      "CSI drivers? — Per-cloud storage plugin.",
      "Cluster autoscaling differs? — Karpenter vs CA.",
      "Cloud lock-in CRDs everywhere",
      "No Helm values per env",
      "kubectl prod from laptop"),
    q("PostgreSQL Portable Across Clouds", "Data", "Common",
      "Run PostgreSQL portable on RDS and Azure Flexible Server?",
      "Stick to portable SQL features; avoid vendor extensions; use standard connection pooling; migration via pg_dump/logical replication.",
      "**Architect:** ORM and migrations tool (Flyway) cloud-agnostic. Test on both before claiming portable.",
      "Database portability limits ORM features used.",
      "Citus/Azure-specific? — Breaks portability.",
      "Connection string abstraction? — Config per cloud.",
      "PL/pgSQL cloud-specific functions",
      "No compatibility test CI",
      "Assume identical performance"),
    q("Object Storage Abstraction SDK", "Integration", "Common",
      "Abstract S3 and Blob storage in application?",
      "Interface `IObjectStorage` with put/get/presign; implementations AWSS3, AzureBlob; or MinIO API compatible.",
      "**Architect:** Don't leak provider SDK types to domain. Test with local MinIO container.\n\n**Cost:** Egress when moving between clouds — model carefully.",
      "Abstraction trade-off worth for true multi-cloud storage.",
      "S3 API compatibility? — Many tools S3-compatible.",
      "Multipart upload abstracted? — Large file API design.",
      "Provider SDK in domain layer",
      "Abstraction without integration test",
      "Ignore egress on migration"),
    q("Message Bus Abstraction", "Integration", "Common",
      "Abstract SQS and Service Bus?",
      "Port interface publish/subscribe; adapters per cloud; accept lowest common denominator or feature flags per provider.",
      "**Architect:** Map semantics — visibility timeout vs lock duration. DLQ both sides.\n\n**Alternative:** Kafka/MSK self-managed portable layer.",
      "Messaging abstraction is hard — document gaps.",
      "CloudEvents standard? — Payload envelope portable.",
      "Outbox still recommended? — Yes per cloud DB.",
      "Lowest common denominator kills features",
      "No DLQ abstracted",
      "Sync HTTP instead async both"),
    q("OpenTelemetry Portable Observability", "Observability", "Common",
      "Single OTel instrumentation both clouds?",
      "OTel SDK in app → exporter per env (X-Ray, Azure Monitor, vendor-neutral collector → Grafana).",
      "**Architect:** One dashboard tool (Grafana/Datadog) aggregates both clouds — unified SLO view.",
      "OTel is multi-cloud observability win.",
      "Collector agent per node? — DaemonSet pattern.",
      "Trace correlation cross-cloud? — Propagate trace context.",
      "Two proprietary agents",
      "Different metric names unnormalized",
      "No unified on-call"),
    q("CI/CD Multi-Cloud Pipelines", "DevOps", "Common",
      "GitHub Actions deploy to Azure and AWS?",
      "OIDC federation both clouds — no secrets. Reusable workflows; environment protection rules prod.",
      "**Architect:** Separate jobs parallel; shared build artifact container image; cloud-specific deploy job assumes role.",
      "Pipeline design prevents credential sprawl.",
      "Matrix strategy? — Test both clouds PR.",
      "Deployment environments? — Approval gates.",
      "Long-lived keys GitHub secrets",
      "Deploy both one job tangled",
      "No rollback workflow"),
    q("Secret Management Both Clouds", "Security", "Common",
      "Unified secrets strategy Azure Key Vault + AWS Secrets Manager?",
      "External Secrets Operator syncs to K8s; or HashiCorp Vault central; or duplicate secrets with rotation automation each cloud.",
      "**Architect:** Prefer single Vault for multi-cloud central; accept operational cost. Document rotation ownership.",
      "Secrets multiply in multi-cloud — plan early.",
      "Vault on K8s? — HA cluster required.",
      "Never replicate secrets manual",
      "Secrets in git encrypted sloppy",
      "Different secret names chaos",
      "No rotation schedule"),
    q("Compliance Mapping Azure/AWS", "Compliance", "Common",
      "Map SOC 2 controls across Azure and AWS?",
      "Control matrix: logging (CloudTrail/Activity Log), encryption (KMS/Key Vault), access (IAM/Entra), network (FW/NSG).",
      "**Architect:** Unified compliance dashboard both providers. Gap analysis per control not per checkbox vendor doc.",
      "Compliance is mapped controls not logos.",
      "ISO 27001 similar mapping? — Same approach.",
      "Shared audit evidence? — Central SIEM.",
      "Separate compliance silos",
      "Assume certified so compliant",
      "No unified control matrix"),
    q("Acquisition Cloud Consolidation", "Strategy", "Common",
      "Acquired company on different cloud — architect plan?",
      "Assess workloads, contract commitments, skills, data gravity, regulatory, integration timeline — migrate vs federate vs leave.",
      "**Architect:** 12-month consolidation roadmap with waves; don't force day-one unless M&A requires.",
      "M&A cloud strategy is common principal scenario.",
      "Data export legal? — Contract and privacy review.",
      "Retain both 2 years? — Often realistic interim.",
      "Big-bang migration weekend",
      "Ignore acquired team's expertise",
      "No TCO comparison"),
    q("Negotiating Cloud Contracts", "FinOps", "Occasional",
      "Enterprise Agreement vs EDP negotiation tips?",
      "Commit based on steady baseline not peak; volume discounts; MAP migration funding; BYOL options; support tier included.",
      "**Architect:** Provide engineering usage forecast to finance for negotiation — credible data.",
      "Commercial awareness complements technical depth.",
      "CSP vs direct? — Partner discounts vs enterprise direct.",
      "True-up risk? — Overcommit penalty.",
      "Sign 3-year day one startup",
      "No engineering input commit",
      "Ignore support tier value"),
    q("Reserved Capacity Both Providers", "FinOps", "Common",
      "RI/SP on AWS and Reservations on Azure together?",
      "Separate commitment per cloud — no cross-cloud credit. Track utilization dashboards each.",
      "**Architect:** Commit only after 6+ months stable usage per cloud. Finance consolidated view both.",
      "Dual cloud doubles commitment complexity.",
      "Flexibility exchange? — Provider-specific policies.",
      "Savings plan unused? — Waste both sides.",
      "Max commit both clouds speculative",
      "No utilization alerts",
      "Forgot Azure reservation expiry"),
    q("Carbon and Sustainability Compare", "Sustainability", "Occasional",
      "Compare cloud sustainability for workload placement?",
      "AWS Customer Carbon Footprint Tool; Azure Emissions Impact Dashboard; region grid carbon intensity varies.",
      "**Architect:** Sustainability pillar in WAF — batch jobs schedule low-carbon hours; Graviton/ARM efficiency.",
      "Sustainability increasingly in RFPs.",
      "Carbon aware scheduling? — Emerging practice.",
      "Marketing green without metrics",
      "Ignore region carbon data",
      "Over-provisioned resources waste",
      "No sustainability review"),
    q("SaaS Multi-Tenant Multi-Cloud", "Architecture", "Common",
      "Offer SaaS on customer-choice cloud?",
      "Single codebase, config per cloud deployment; tenant isolation; data residency per customer region/cloud.",
      "**Architect:** Massive ops burden — justify premium pricing. Shared control plane; isolated data plane per cloud option.",
      "Customer-choice cloud is hardest SaaS model.",
      "Terraform modules per cloud tenant? — Automation required.",
      "Support SLA per cloud? — Different capabilities.",
      "Underestimate ops 3x",
      "Same SLA all clouds unrealistic",
      "No automated tenant provisioning"),
    q("Edge Computing Both Clouds", "Edge", "Occasional",
      "Azure IoT Edge vs AWS Greengrass — architect view?",
      "Edge run modules/lambda offline sync cloud — factory, retail, CDN PoP scenarios.",
      "**Architect:** Edge when latency/regulations require local processing; manage fleet updates OTA securely.",
      "Edge extends hybrid architecture.",
      "Azure Stack HCI? — On-prem Azure services.",
      "Wavelength 5G edge? — Ultra-low latency mobile.",
      "Edge without update strategy",
      "Same security model cloud assumed",
      "No offline mode design"),
    q("AI/ML Services Portability", "AI", "Occasional",
      "Portable AI architecture across Azure OpenAI and Bedrock?",
      "Abstract LLM provider interface; prompt templates versioned; evaluate vendor lock on fine-tuning and embeddings.",
      "**Architect:** Open models on portable K8s GPU if lock-in concern high. Cost per token compare both.",
      "AI portability is emerging architect concern.",
      "LangChain multi-provider? — Abstraction layer example.",
      "Embedding model lock-in? — Re-index cost high.",
      "Single vendor prompts hardcoded",
      "No fallback model outage",
      "PII to cloud AI no review"),
    q("Data Gravity Decision", "Strategy", "Very Common",
      "How does data gravity affect multi-cloud?",
      "Large datasets expensive/slow to move — analytics stay near data; apps migrate to data not reverse.",
      "**Architect:** Place compute in cloud holding primary data lake. Egress costs dominate TCO.",
      "Data gravity is physics of cloud architecture.",
      "Snowball/Device transfer? — Bulk migration.",
      "Replication not migration? — Hybrid access both.",
      "Move 5PB monthly over internet",
      "Ignore egress in business case",
      "Analytics cloud different no plan"),
    q("Exit Strategy Documentation", "Strategy", "Common",
      "Document cloud exit strategy without paranoia?",
      "Export procedures, data formats, contract terms, alternative providers, transition timeline, acceptable lock-in list.",
      "**Architect:** Exit doesn't mean leave — means negotiable posture and risk management.",
      "Exit strategy is mature governance.",
      "Escrow for SaaS vendor? — Different but related.",
      "Open formats mandate? — Parquet, Postgres dumps.",
      "No data export tested",
      "100% proprietary formats",
      "Exit strategy never reviewed"),
    q("Architecture Board Multi-Cloud Governance", "Governance", "Very Common",
      "Architecture review board for multi-cloud estate?",
      "Standards: tagging, IaC, security baseline, approved services list per cloud, exception process, quarterly landscape review.",
      "**Architect:** Board approves new cloud services and cross-cloud patterns — not every deploy.\n\n**Output:** Decision log ADRs searchable.",
      "Governance enables speed with guardrails.",
      "RFC process? — Lightweight proposal before adopt.",
      "Tech radar? — Assess/Hold/Trial/Adopt per service.",
      "No standards each team freestyle",
      "Board blocks without alternatives",
      "ADRs written never read"),
]

ALL_AWS_Q011_Q030 = {
    17: WEEK_17_Q011_Q030,
    18: WEEK_18_Q011_Q030,
    19: WEEK_19_Q011_Q030,
    20: WEEK_20_Q011_Q030,
}
