"""Hand-crafted premium Q001–Q005 for Weeks 49–52 — Whiteboard Mock 2, Leadership, STAR, Graduation fundamentals."""

from premium_qa_data import q

WEEK_49_Q001_Q005 = [
    q("Multi-tenant SaaS Mock Intro", "Whiteboard Mock", "Very Common",
      "How do you open and structure a whiteboard mock for multi-tenant SaaS architecture?",
      "Clarify tenant count, isolation tier, compliance, and scale first. Narrate a three-layer diagram (edge → app → data), state tenant model options, and reserve deep dive for one isolation path. Time-box: 5 min clarify, 10 min high-level, 20 min deep dive, 5 min trade-offs.",
      "**Opening script (first 2 minutes):**\n'Before I draw, I want to confirm: B2B or B2C tenants? Rough tenant count and whether any enterprise customers need dedicated isolation? Any compliance tier — SOC2, HIPAA? Peak RPS and data residency constraints?'\n\n**Structure template:**\n```\nMinute 0–5   Requirements + assumptions on board\nMinute 5–15  High-level: Tenant → APIM → App tier → Data tier\nMinute 15–30 Deep dive: tenant model + auth + noisy-neighbor controls\nMinute 30–40 NFRs: backup, DR, audit, observability by tenantId\nMinute 40–45 Trade-offs + migration path for enterprise upsell\n```\n\n**Tenant model options to present:**\n| Model | Isolation | Ops cost | When |\n|-------|-----------|----------|------|\n| Shared DB + tenantId + RLS | Logical | Low | Standard tier |\n| Schema per tenant | Medium | Medium | Mid-market |\n| DB/silo per tenant | Strong | High | Enterprise/HIPAA |\n\n**Must mention:** JWT `tenant_id` claim, row-level security, per-tenant rate limits, tenant dimension in logs/metrics.\n\n**Intro goal:** Show structured thinking before drawing boxes — interviewers score process, not perfect diagram.",
      "Multi-tenant mock intro proves you clarify before designing — the #1 whiteboard failure mode is premature drawing.",
      "When default to RLS vs silo? — RLS for <100 enterprise; silo when contract or audit mandates physical separation.",
      "Noisy neighbor on intro? — Name per-tenant rate limits and fair queue scheduling — even in opening.",
      "Drawing microservices before stating tenant model",
      "Skipping compliance question in B2B SaaS mock",
      "No tenantId in observability discussion"),
    q("Acquisition Integration Mock Intro", "Whiteboard Mock", "Very Common",
      "How introduce an acquisition integration whiteboard mock before diving into integration patterns?",
      "Start with discovery framing: systems of record, timeline, risk appetite, and governance. Present phased target state — never big-bang. Draw current vs target with integration hub as explicit boundary.",
      "**Opening clarifiers:**\n- What does acquired company own today (OMS, CRM, billing)?\n- 12-month deadline hard or aspirational?\n- Customer overlap — migrate all or new customers only?\n- Team retention and skill mix on acquired side?\n\n**Intro narrative structure:**\n```\nPhase 0: Discovery (inventory, data quality, SLAs)\nPhase 1: Identity + read-only mirror\nPhase 2: Event-driven sync + strangler for new traffic\nPhase 3: Write path migration + decommission\n```\n\n**First diagram (simple):**\n```\nAcquired Stack ←→ Integration Hub ←→ Your Platform\n                      ↓\n               Customer ID Golden Record\n```\n\n**Name risks early:** Duplicate orders, currency/tax rules, dual ops cost, cultural resistance.\n\n**Governance:** Joint integration squad with sunset date; executive milestone map at month 3, 6, 12.\n\n**Intro goal:** Signal program thinking — acquisition mocks test integration strategy and stakeholder awareness, not API syntax.",
      "Acquisition mock intro separates architects who plan phased integration from those who draw point-to-point REST.",
      "Strangler vs big-bang intro? — State strangler as default; big-bang only if EOL imminent — shows judgment.",
      "Who owns integration hub? — Name platform/integration team — avoid orphan middleware.",
      "Jumping to API design without systems-of-record map",
      "Ignoring data quality in legacy inventory",
      "No rollback or feature-flag cohort strategy mentioned"),
    q("Migration Strategy Mock Intro", "Whiteboard Mock", "Very Common",
      "How frame a large-scale migration whiteboard mock before detailing waves and landing zone?",
      "Open with assess → plan → pilot → scale. State dependency mapping, wave criteria, landing zone prerequisites, and per-wave rollback. Quantify scope (service count, stateful vs stateless) before drawing Azure boxes.",
      "**Opening clarifiers:**\n- Source environment (on-prem K8s, VMs, mainframe)?\n- Timeline and blackout windows?\n- Stateful services count and data gravity?\n- Team K8s/cloud maturity?\n- Compliance constraints on data movement?\n\n**Intro framework (write on board):**\n```\n1. ASSESS  — CMDB, dependency graph, risk scoring\n2. LANDING ZONE — network, identity, policy guardrails\n3. PILOT    — 5–10 low-risk services, learn run rate\n4. WAVES    — dependency-ordered batches\n5. VALIDATE — metrics per wave; rollback window\n```\n\n**Wave criteria to name upfront:**\n| Wave | Selection rule |\n|------|----------------|\n| Pilot | Stateless, low revenue risk |\n| Platform | Shared services others depend on |\n| Core | Revenue path |\n| Long tail | Legacy deps, manual steps |\n\n**Per-service pattern:** Containerize → deploy target → traffic shift (DNS/APIM) → decommission source → 30-day rollback warm.\n\n**Parallel track:** Data migration often separate program — call it out in intro.\n\n**Intro goal:** Interviewers want wave planning discipline — not 'lift-and-shift everything weekend 1.'",
      "Migration mock intro rewards sequencing language — assess and waves before technology choices.",
      "Replatform vs refactor intro? — Replatform containers first; refactor in cloud incrementally — set expectation early.",
      "Landing zone before pilot? — Yes — identity and network policy before first production workload.",
      "Big-bang cutover as opening recommendation",
      "No dependency-ordered wave criteria",
      "Ignoring team training and runbook updates"),
    q("Risk Register Mock Intro", "Whiteboard Mock", "Very Common",
      "How open a risk register whiteboard mock for a major architecture program?",
      "State risk categories, scoring model (likelihood × impact), owner assignment, and review cadence before listing risks. Link risks to ADRs and executive escalation path.",
      "**Opening clarifiers:**\n- Program scope (greenfield, migration, launch)?\n- Risk appetite — regulated vs startup tolerance?\n- Audience — arch guild or risk committee?\n- Time horizon — 90-day launch or 3-year program?\n\n**Intro template (draw table header first):**\n```\n| Risk | Category | L | I | Score | Mitigation | Owner | Residual |\n```\n\n**Categories to announce:**\n- Technical (performance, integration failure)\n- Security (key compromise, data breach)\n- Operational (skill gap, runbook gaps)\n- Compliance (residency, audit)\n- Vendor (PSP outage, cloud dependency)\n\n**Scoring:** L/M/H × L/M/H → heat map; top-right items get steering committee visibility.\n\n**Process:** Biweekly arch guild review; red items escalated with mitigation options not just alerts.\n\n**Link to design:** Each high risk maps to ADR, spike, or accepted residual with exec sign-off.\n\n**Intro goal:** Show governance maturity — risk register is living artifact, not one-time slide.",
      "Risk register mock intro tests whether you quantify and assign — 'we'll monitor it' is not mitigation.",
      "Risk vs issue? — Risk = may happen; issue = occurred — separate logs in intro.",
      "Heat map for exec? — Mention 5×5 grid translation for non-technical audience.",
      "Generic risks without domain specificity",
      "No owners or review cadence on register",
      "Mitigation column says 'monitor' without action"),
    q("Executive Communication Mock Intro", "Whiteboard Mock", "Very Common",
      "How structure the opening of an executive communication mock for a non-technical audience?",
      "Lead with business outcome (BLUF), not technology. One diagram, three milestones, cost/benefit, clear ask. Practice hard time limit — 5 minutes means 5 minutes.",
      "**Opening clarifiers (even in mock):**\n- Who is audience — CEO, CFO, board?\n- Decision needed today or informational?\n- Prior context — first briefing or progress update?\n\n**5-minute structure (write outline first):**\n```\n1. Why now     — Business pain in dollars or risk\n2. What        — Scope in plain language (not 'Kubernetes')\n3. How         — Phased; customer impact = none/minimal\n4. When        — 3 milestones with dates\n5. Cost/benefit — Invest vs save; break-even\n6. Ask         — Budget, headcount, or decision\n```\n\n**Language rules:**\n- No acronyms without expansion\n- 'Faster checkout' not 'microservices decomposition'\n- '$2M annual savings by year 2' not 'improved scalability'\n\n**One diagram:** Old brittle chain → new resilient flow — max 5 boxes.\n\n**Anticipate one objection:** Prepare 'Why not buy SaaS?' or 'Why now vs next year?'\n\n**Intro goal:** Executive comms mock tests translation — architects who cannot speak business fail regardless of technical depth.",
      "Executive comms intro is BLUF discipline — headline outcome before any architecture vocabulary.",
      "CEO vs board depth? — CEO: outcomes and ask; board: risk, audit, material cost.",
      "Yellow status in exec update? — Early yellow preferred over surprise red — mention in intro.",
      "Opening with technology stack names",
      "No dollar figures or timeline in first minute",
      "Ending without explicit ask"),
]

WEEK_50_Q001_Q005 = [
    q("Stakeholder Management Fundamentals", "Leadership", "Very Common",
      "What are stakeholder management fundamentals every architect must master?",
      "Identify all stakeholders, map power and interest, align work to business OKRs, communicate proactively, document decisions, and escalate with data when deadlocked. Architecture ships through people — not diagrams alone.",
      "**Core fundamentals:**\n1. **Discovery** — Who wins/loses from this change? Interview sponsors early\n2. **Map** — Power/interest grid: manage closely, keep satisfied, consult, monitor\n3. **Align** — Tie initiatives to company OKRs — not architecture preferences\n4. **Engage** — Cadence per stakeholder type (weekly tech leads, biweekly sponsors)\n5. **Decide transparently** — RACI + decision log; no back-channel surprises\n6. **Escalate** — Present options with cost/risk when priorities conflict\n\n**Stakeholder map example:**\n| Stakeholder | Power | Interest | Strategy |\n|-------------|-------|----------|----------|\n| CTO | High | High | Manage closely |\n| CFO | High | Low | Cost dashboard, brief updates |\n| Team leads | Low | High | Consult on contracts |\n| Legacy team | Medium | Low | Co-opt as migration leads |\n\n**Artifacts:** Stakeholder map, RACI, decision log, steering deck.\n\n**Architect trap:** Designing perfect solution that key sponsor never bought into.",
      "Stakeholder fundamentals are prerequisite to every leadership scenario — neglect them and perfect architecture stalls.",
      "Sponsor vs champion? — Sponsor has budget authority; champion drives daily adoption.",
      "Silent stakeholder risk? — Proactively engage neutrals — silence becomes veto at steering.",
      "Designing without sponsor alignment",
      "Treating all stakeholders with same cadence",
      "No written decision record after conflict"),
    q("Conflict Resolution for Architects", "Leadership", "Very Common",
      "What conflict resolution approaches should architects use when teams disagree on technical direction?",
      "Separate people from problem, agree on decision criteria, timebox debate, use POC when needed, record ADR, escalate by deadline. Focus on requirements and data — not rank or volume of opinions.",
      "**Resolution process:**\n1. **Restate problem** — Shared understanding of business need and NFRs\n2. **Criteria** — Latency, coupling, team skills, ops burden, cost — written list both sides accept\n3. **Options** — At least two viable paths with honest trade-offs\n4. **Evidence** — POC with success metrics (1 week max) or reference architecture precedent\n5. **Decision** — ADR with rejected alternative and revisit trigger\n6. **Commit** — Disagree and commit; assign ownership on chosen path\n\n**Facilitation techniques:**\n- Round-robin input before debate\n- 'What would change your mind?' question\n- Architecture board as tie-breaker with strategic lens\n\n**People dimension:** Acknowledge contributions from both sides; 1:1 repair after heated sessions.\n\n**When to escalate:** Deadline missed, compliance risk, or deadlock on criteria themselves.",
      "Conflict resolution is core architect leadership — process beats charisma or seniority.",
      "Consensus vs consent? — Consent = no principled objection — faster at scale than full consensus.",
      "Relationship repair? — Brief 1:1 after resolution — 'disagree and commit' ritual.",
      "Defaulting to senior engineer's preference",
      "Endless debate without timebox or POC",
      "No ADR — same conflict repeats next quarter"),
    q("Influencing Without Authority", "Leadership", "Very Common",
      "How do architects influence autonomous teams without direct management authority?",
      "Make the right path the easy path: golden paths, templates, pilot wins, champions, data on adoption, and executive air cover. Respect team autonomy — influence through value, not mandates.",
      "**Influence levers:**\n| Lever | Tactic |\n|-------|--------|\n| Ease | Secure CI template faster than rolling your own |\n| Proof | Pilot team shows 80% CVE reduction — tell story |\n| Data | Adoption % correlated with incident rate |\n| Champions | Tech lead per tribe advocates standard |\n| Air cover | CTO: 'expected default for new services' |\n\n**Gradual adoption curve:**\n```\nOpt-in → Recommended → Required for new services only\n```\n\n**Avoid:** Email mandates from ivory tower; standards as PDF without tooling; shaming holdouts.\n\n**Listen to resistance:** Often edge case reveals gap in standard — adapt before enforcing.\n\n**When mandate is OK:** Regulatory audit finding, security incident, contractual obligation — pair with tooling enforcement.",
      "Influence without authority defines architect role — platforms and proof beat policies.",
      "When escalate to mandate? — After opt-in fails and compliance risk is material.",
      "Holdout team? — 1:1 to understand friction — fix template before forcing.",
      "Standards email without golden path tooling",
      "Architecture team disconnected from stream pain",
      "Treating resistance as ignorance not signal"),
    q("Executive Communication Skills", "Leadership", "Very Common",
      "What executive communication skills must architects develop beyond technical depth?",
      "BLUF, business metrics first, one visual, risk honesty, clear ask, no jargon, rehearsed timing. Executives decide on outcomes, dollars, and dates — not container orchestration details.",
      "**Skill checklist:**\n1. **BLUF** — Bottom line up front in first 30 seconds\n2. **Business language** — Revenue, risk, cost, time-to-market — not tech stack\n3. **One diagram** — Simplified current → target; appendix for depth\n4. **Status discipline** — Green/yellow/red with early yellow preferred\n5. **Risks** — Top 2 with mitigations; no surprise bad news in Q&A\n6. **Ask** — Specific decision, budget, or resource — every meeting\n7. **Timing** — 10-minute slot means 8 minutes content + 2 buffer\n\n**10-minute template:**\n```\nHeadline → Progress (3 bullets) → Business impact → One diagram → Risks → Ask\n```\n\n**Preparation:** Rehearse aloud; anticipate cost, timeline, competitive questions.\n\n**Common failure:** Technical deep dive unprompted — loses executive attention in 90 seconds.",
      "Executive communication is a distinct skill — senior architects practice it deliberately.",
      "Managing up to technical CTO? — Lead with metrics and code-level credibility — still BLUF.",
      "Board vs exec committee? — Board wants risk, audit, materiality — less operational detail.",
      "Opening with acronyms and architecture patterns",
      "No ask at end of presentation",
      "Surprise bad news first time in exec forum"),
    q("Prioritization Frameworks", "Leadership", "Very Common",
      "What prioritization frameworks help architects rank competing initiatives with limited capacity?",
      "WSJF, RICE, value/effort matrix, and OKR alignment — applied transparently with steering ratification. Architect owns the 'no' — document deferred items with reason.",
      "**Framework comparison:**\n| Framework | Formula / method | Best for |\n|-----------|------------------|----------|\n| WSJF | (BV + TC + RR) / Job size | SAFe / portfolio |\n| RICE | Reach × Impact × Confidence / Effort | Product-style ranking |\n| Value/Effort 2×2 | Plot initiatives | Quick visual triage |\n| OKR tie-break | Align to company objectives | Executive deadlock |\n\n**WSJF components:**\n- **Business value** — Revenue, cost save, risk reduction\n- **Time criticality** — Regulatory deadline, competitive window\n- **Risk reduction** — Unblocks other work, reduces outage risk\n- **Job size** — Engineering estimate in person-weeks\n\n**Process:**\n1. Inventory initiatives with one-line outcome\n2. Collaborative scoring — avoid architect solo ranking\n3. Fit top N into squad capacity\n4. Publish ranked backlog; dissent documented\n5. Revisit quarterly or when OKRs shift\n\n**Say no explicitly:** Bottom items deferred with reason — prevents zombie priorities.",
      "Prioritization frameworks show strategic discipline — transparent criteria beat HIPPO (highest paid person's opinion).",
      "Local vs global optimum? — Platform work ranks low locally — exec override may be needed.",
      "Cost of delay? — WSJF time criticality captures regulatory deadlines.",
      "40 items all marked P0",
      "Architect scores alone without stakeholder input",
      "No re-prioritization cadence when context shifts"),
]

WEEK_51_Q001_Q005 = [
    q("Technical Leadership STAR Format", "STAR Behavioral", "Very Common",
      "How structure a technical leadership answer using the STAR format in architect interviews?",
      "STAR = Situation, Task, Action, Result. Lead with 90-second summary; emphasize your facilitation, criteria, and measurable outcome. Show trade-off thinking and cross-team impact — not solo heroics.",
      "**STAR anatomy for technical leadership:**\n- **Situation (15 sec)** — Business context, ambiguity, scale (teams, services, deadline)\n- **Task (10 sec)** — Your role explicitly: 'As lead architect, I was accountable for...'\n- **Action (45 sec)** — What YOU did: facilitated RFC, defined NFRs, ran POC, wrote ADR, aligned stakeholders\n- **Result (20 sec)** — Quantified: defects down 55%, adoption 100%, delivered in 90 days\n\n**Sample skeleton:**\n```\nS: 8 teams, no integration standard, release delays\nT: Deliver API standards adopted in 90 days\nA: RFC process, working group, 2 pilots, phased CI lint\nR: 100% new services compliant; integration defects −55%\n```\n\n**Delivery tips:**\n- Use 'I facilitated' not 'we decided' without your role clarity\n- Name trade-offs considered\n- Prepare probes: 'What resistance?' 'What would you change?'\n\n**Avoid:** Decision with no alternatives; result without metrics; only technical actions with no people leadership.",
      "Technical leadership STAR proves you drive outcomes — interviewers probe whether you led or observed.",
      "Ambiguity in Situation? — Strong stories start with unclear NFRs you helped define.",
      "Team credit balance? — 'I facilitated; Team X built lint rules' — shows multiplier leadership.",
      "90-second STAR runs 5 minutes unprompted",
      "Result not quantified",
      "Only technical work — no facilitation or alignment"),
    q("Failure Story STAR Format", "STAR Behavioral", "Very Common",
      "How deliver an authentic failure story in STAR format for senior architect interviews?",
      "Pick real mistake you owned, show humility, explain systemic lesson, and process change applied. No blaming; no humble brag ('I work too hard').",
      "**STAR for failure:**\n- **Situation** — Context where you made recommendation\n- **Task** — What you were accountable for\n- **Action** — What you decided; what went wrong; how you detected it\n- **Result** — Recovery action + lesson that changed your process\n\n**Strong failure elements:**\n1. **Ownership** — 'I recommended Cassandra based on hype, not team fit'\n2. **Impact** — Ops complexity, timeline slip — honest scope\n3. **Recovery** — Migrated to Redis in 6 weeks; transparent comms\n4. **Lesson** — Added ops maturity criteria to ADR template; skills matrix check\n\n**Weak patterns to avoid:**\n- Fake failure ('I'm perfectionist')\n- Blame vendor or former employer\n- Failure too recent without resolution\n\n**Probe prep:** 'What signals did you miss?' 'How do you prevent recurrence?'",
      "Failure STAR tests psychological safety and growth mindset — senior interviews expect one polished failure story.",
      "Too recent? — Pick resolved failure with lesson already applied in later work.",
      "Blame external? — Own your recommendation even if vendor or market shifted.",
      "Humble brag disguised as failure",
      "No systemic process change after lesson",
      "Villain narrative about former team"),
    q("Mentoring STAR Format", "STAR Behavioral", "Very Common",
      "How structure a mentoring STAR answer that demonstrates architect-level multiplier leadership?",
      "Show intentional investment: specific coaching actions, opportunities you created, and measurable mentee growth. Mentoring is more than answering Slack — it's accelerating someone's trajectory.",
      "**STAR for mentoring:**\n- **Situation** — Person's starting point and aspiration (e.g., senior dev → architect path)\n- **Task** — Your commitment as mentor\n- **Action** — Paired on ADRs, delegated facilitation, feedback on exec comms, recommended resources, sponsored visibility\n- **Result** — Promoted in 14 months; led review solo; still mentors others\n\n**Actions that score well:**\n- Created opportunities (guild facilitation, steering presentation)\n- Specific feedback loops (weekly 1:1, written comms critique)\n- Advocated for promotion with evidence\n- Taught framework (ADR, C4) through doing, not lecturing\n\n**Balance:** Credit mentee's work — you enabled, not did their job.\n\n**Probe prep:** 'Mentee struggled — how adapted?' 'Formal vs informal structure?'",
      "Mentoring STAR shows multiplier leadership — critical for principal and staff architect tracks.",
      "Mentoring = Slack answers? — Weak — show structured development plan.",
      "No mentee outcome? — Interviewers want promotion, scope growth, or skill proof.",
      "Taking credit for mentee's delivery",
      "Generic advice without specific coaching actions",
      "No opportunity created — only reactive Q&A"),
    q("Cross-team Collaboration STAR", "STAR Behavioral", "Very Common",
      "How format a cross-team collaboration STAR answer when you had no direct authority?",
      "Emphasize coalition building, shared metrics, RACI, cadence, conflict navigation, and on-time outcome across 4+ teams. Program leadership plus technical depth.",
      "**STAR skeleton:**\n- **Situation** — Initiative requiring app, data, security, legal (or similar)\n- **Task** — Your DRI role with deadline (e.g., 30-day GDPR compliance)\n- **Action** — RACI, weekly sync, shared dashboard, early escalation of blockers, technical spikes per team\n- **Result** — Shipped in 28 days; zero audit findings; playbook reused\n\n**Collaboration signals interviewers want:**\n- Named teams and interfaces — not 'other teams'\n- Escalated blockers early with options\n- Shared success metric visible to all\n- Teams as partners, not obstacles\n\n**Remote/async:** Mention tools if relevant — but focus on alignment mechanisms.\n\n**Probe prep:** 'Biggest conflict?' 'What would you do with unresponsive team?'",
      "Cross-team STAR is default architect behavioral — prove you ship through organizational complexity.",
      "Conflict in story? — Brief realistic resolution — shows emotional intelligence.",
      "You did all technical work? — Weak — show orchestration across teams.",
      "Teams portrayed as obstacles",
      "No deadline or compliance pressure",
      "Vague 'worked with stakeholders' without RACI"),
    q("Innovation STAR Format", "STAR Behavioral", "Common",
      "How tell an innovation STAR story that shows adoption and risk management — not just a clever idea?",
      "Innovation = new to organization, not necessarily invention. Show pilot, measured adoption, quantified impact, and how you contained blast radius.",
      "**STAR for innovation:**\n- **Situation** — Pain point (e.g., 4-hour deploys, teams afraid to ship)\n- **Task** — Introduce new approach (GitOps, progressive delivery, event-driven)\n- **Action** — Pilot with willing team; golden path template; measured DORA; expanded org-wide; feature flags + rollback\n- **Result** — Deploy frequency 2/week → 12/week; change failure rate 25% → 8%\n\n**Innovation signals:**\n- Started small — pilot before mandate\n- Adoption story — how holdouts converted\n- Risk mitigation — canary, flags, automated rollback\n- Buying managed service counts as innovation if new to org\n\n**Weak innovation:** Bleeding edge with no pilot; idea without adoption; cannot explain risk containment.\n\n**Probe prep:** 'Failed innovation?' — OK if small blast radius and learning.",
      "Innovation STAR must end in adoption and metrics — idea alone is insufficient for senior roles.",
      "Failed innovation story? — Acceptable if learning and limited blast radius.",
      "Buy vs build? — Adopting Azure managed service new to org is valid innovation.",
      "Bleeding edge with no pilot",
      "Innovation without adoption narrative",
      "Cannot explain risk mitigation approach"),
]

WEEK_52_Q001_Q005 = [
    q("Architecture Portfolio Essentials", "Graduation Capstone", "Very Common",
      "What essentials belong in an architecture portfolio for principal-level job search?",
      "3–5 deep case studies with context, your role, diagrams, trade-offs, and metrics; plus executive summary, principles, tech radar, and contact. Depth beats breadth — anonymize confidential data.",
      "**Portfolio essentials:**\n1. **Executive summary (1 page)** — Specialty, impact metrics, target role\n2. **Case studies (3–5)** — Each 3–5 pages:\n   - Business context and constraints\n   - Your role ('I' vs 'we' explicit)\n   - C4 L1–L2 diagrams\n   - ADR highlights\n   - Before/after metrics\n   - Lessons learned\n3. **Architecture principles** — 5–8 personal principles with examples\n4. **Tech radar** — Adopt/trial/assess/hold with rationale\n5. **References** — LinkedIn, GitHub, talks, blog\n\n**Format:** PDF primary; optional static site (GitHub Pages).\n\n**Privacy:** Anonymize employer; no confidential revenue or customer names.\n\n**Anti-patterns:** Resume paste; 7 shallow cases; diagrams with live confidential data.",
      "Portfolio essentials separate serious architect candidates from resume-only applicants.",
      "How many case studies? — 3 excellent beats 7 shallow — interviewers go deep on one.",
      "Redacted diagrams? — Generic boxes OK — structure and trade-offs matter most.",
      "Resume copied as portfolio",
      "No clarity on personal role in case studies",
      "Confidential numbers or customer names exposed"),
    q("Mock Interview Preparation", "Graduation Capstone", "Very Common",
      "What are the essentials of mock interview preparation before architect job search?",
      "Deliberate practice across system design, behavioral STAR, leadership, and estimation. Schedule peer mocks, record and review, track gaps in spreadsheet, simulate full loop in final week.",
      "**4-week essentials plan:**\n| Week | Focus | Activities |\n|------|-------|------------|\n| 1 | System design | 3 mocks: SaaS, payments, scale |\n| 2 | Behavioral | 2 STAR sessions; record and critique |\n| 3 | Leadership | Exec comms + conflict scenarios |\n| 4 | Full loop | 4-hour simulated loop + debrief |\n\n**Practice rules:**\n- Speak aloud — reading ≠ interviewing\n- Time-box answers (90 sec STAR, 45 min design)\n- Debrief every mock: gaps, filler words, diagram clarity\n- Max 2 mocks/day — quality degrades beyond that\n\n**Log:** Spreadsheet of missed questions; drill weak areas before next mock.\n\n**Logistics:** Test video, whiteboard tool (Excalidraw), quiet space.\n\n**Resources:** Peer architects, Pramp, optional coach for final polish.",
      "Mock prep is deliberate practice — schedule it like exam study, not optional cramming.",
      "Company-specific prep? — Final week tailor stories to target stack and values.",
      "Only reading — never practicing aloud? — #1 preparation failure.",
      "Skip behavioral and leadership mocks",
      "No debrief or gap tracking after sessions",
      "Cram 5 mocks day before interview"),
    q("Personal Architecture Principles", "Graduation Capstone", "Very Common",
      "How articulate personal architecture principles for portfolio and interviews?",
      "Define 5–8 principles from your experience; each with rationale, example, and trade-off awareness. Show you prioritize contextually — not parrot frameworks blindly.",
      "**Example personal principle set:**\n1. **Simplicity first** — Simplest design meeting NFRs (monolith before microservices)\n2. **Evolutionary architecture** — Decide at last responsible moment\n3. **Observability by default** — Can't operate what you can't see\n4. **Security embedded** — Not bolted on at end\n5. **Conway-aware boundaries** — Service splits match team ownership\n6. **Managed services** — Unless clear reason not to\n7. **Data as product** — Contracts and ownership explicit\n8. **Blameless learning** — Incidents improve systems\n\n**Interview use:**\n- 'Which principle would you violate here and why?' — show contextual judgment\n- Link principles to case studies in portfolio\n\n**Evolution:** Annual reflection — principles should mature with experience.\n\n**Avoid:** 10+ unfocused principles; buzzwords without examples; principles you contradict in stories.",
      "Personal principles show architectural maturity — not just Microsoft Well-Architected recitation.",
      "Principles in conflict? — Discuss prioritization by context — strong senior signal.",
      "Generic only? — Must connect each principle to real project example.",
      "Buzzword principles without examples",
      "10+ principles — unfocused philosophy",
      "Principles contradicted by your STAR stories"),
    q("Tech Radar Curation", "Graduation Capstone", "Common",
      "How curate a personal technology radar for architect portfolio and interviews?",
      "Use Adopt/Trial/Assess/Hold quadrants with brief rationale per technology. Personalize to your specialty and cloud; update quarterly — dated radar hurts credibility.",
      "**ThoughtWorks-style quadrants:**\n- **Adopt** — Production-ready in your context: K8s, OpenTelemetry, Terraform\n- **Trial** — Active POC: vector DBs for RAG, WASM on edge\n- **Assess** — Watching: eBPF networking, FinOps tooling maturity\n- **Hold** — Defer: unproven blockchain for enterprise ledger\n\n**Personalization examples:**\n| Specialty | Adopt emphasis | Hold example |\n|-----------|----------------|-------------|\n| Azure SA | AKS, APIM, Cosmos | Premature multi-cloud abstraction |\n| Fintech security | HSM, zero-trust patterns | Experimental crypto schemes |\n\n**Portfolio format:** One-page visual + paragraph on how you update (quarterly review).\n\n**Interview use:** 'Why is X in Trial not Adopt?' — shows judgment, not hype.\n\n**Employer radar conflict? — Personal radar can differ — explain thoughtfully.",
      "Tech radar shows continuous learning and judgment — not resume keyword stuffing.",
      "Hold vs reject? — Hold = not now; may revisit — different from permanent rejection.",
      "Everything in Adopt? — Signals lack of critical evaluation.",
      "Radar copied unchanged from ThoughtWorks",
      "No rationale for quadrant placement",
      "Radar not updated in 12+ months"),
    q("Career Planning for Architects", "Graduation Capstone", "Very Common",
      "What essentials belong in a 5-year career plan for solution or principal architect track?",
      "Define vision, skills roadmap, experiences, network, milestones, and contingency paths. Review annually — intentionality beats drifting on promotion titles alone.",
      "**5-year plan framework:**\n| Year | Focus |\n|------|-------|\n| 1 | Land role; establish credibility; 1 major delivery |\n| 2 | Lead tier-1 program; external visibility (talk/blog) |\n| 3 | Principal scope; architecture board; mentor 3+ |\n| 4 | Industry recognition; optional course or book |\n| 5 | CTO exploration or staff/principal depth |\n\n**Skills roadmap:** FinOps, security architecture, AI/LLM systems — align to market demand.\n\n**Experience targets:**\n- Tier-1 program leadership\n- Executive stakeholder management\n- Published ADRs, talks, or open source contributions\n\n**Contingency paths:**\n- IC vs management fork by year 2–3\n- Consulting or contracting if market downturn\n- Geographic or industry pivot triggers\n\n**Review:** Annual retrospective — adjust plan for life constraints and market shifts.\n\n**Interview use:** 'Where do you see yourself in 5 years?' — specific but flexible.",
      "Career planning shows intentionality — interviewers assess whether you own your trajectory.",
      "IC vs management? — Decide by year 2–3; both valid — document triggers for each path.",
      "Market downturn plan B? — Consulting, broaden stack, fractional architect roles.",
      "No written plan — drifting on promotions only",
      "Only title goals — no skill development",
      "Plan ignores life constraints and sustainability"),
]

ALL_WEEKS_49_52_Q001_Q005 = {
    49: WEEK_49_Q001_Q005,
    50: WEEK_50_Q001_Q005,
    51: WEEK_51_Q001_Q005,
    52: WEEK_52_Q001_Q005,
}
