"""Topic-specific concept banks for deepen_all_qa.py — architect interview content."""

# Each concept: (title, category, when_use, when_avoid, production_example)
# Scripts rotate templates to build 120+ unique questions per week.

WEEK_TOPICS = {
    1: ("C# Language Mastery", "C#"),
    2: (".NET Runtime & Ecosystem", ".NET"),
    3: ("SOLID & Clean Architecture", "Architecture"),
    4: ("Design Patterns", "Design Patterns"),
    5: ("Data Structures for System Design", "Data Structures"),
    6: ("Algorithms & Complexity", "Algorithms"),
    7: ("SQL Server Architecture", "SQL Server"),
    8: ("PostgreSQL & Polyglot Persistence", "Databases"),
    9: ("Azure Fundamentals & WAF", "Azure"),
    10: ("Azure Compute & App Services", "Azure Compute"),
    11: ("Azure Data Platform", "Azure Data"),
    12: ("Azure Identity", "Azure Identity"),
    13: ("Azure Networking", "Azure Networking"),
    14: ("Azure Security", "Azure Security"),
    15: ("Azure Integration & Messaging", "Azure Messaging"),
    16: ("Azure Production Capstone", "Azure Architecture"),
    17: ("AWS Fundamentals", "AWS"),
    18: ("AWS Compute & Serverless", "AWS Compute"),
    19: ("AWS Data & Networking", "AWS Networking"),
    20: ("Multi-Cloud Architecture", "Multi-Cloud"),
    21: ("Distributed Systems", "Distributed Systems"),
    22: ("Microservices Architecture", "Microservices"),
    23: ("Domain-Driven Design", "DDD"),
    24: ("Microservices Capstone", "Microservices"),
    25: ("Docker & Containers", "Docker"),
    26: ("Kubernetes Fundamentals", "Kubernetes"),
    27: ("Kubernetes Advanced", "Kubernetes"),
    28: ("Linux for Architects", "Linux"),
    29: ("DevOps Culture & DORA", "DevOps"),
    30: ("CI/CD Pipelines", "CI/CD"),
    31: ("Infrastructure as Code", "IaC"),
    32: ("Observability", "Observability"),
    33: ("System Design Methodology", "System Design"),
    34: ("Scalability & Caching", "Scalability"),
    35: ("Messaging & Events", "Messaging"),
    36: ("System Design Capstone", "System Design"),
    37: ("AI/ML Architecture", "AI Architecture"),
    38: ("RAG & Vector Search", "RAG"),
    39: ("LLMOps & Responsible AI", "LLMOps"),
    40: ("AI Architecture Capstone", "AI Architecture"),
    41: ("ADRs & Architecture Reviews", "Governance"),
    42: ("FinOps, DR & Performance", "FinOps"),
    43: ("Frontend Architecture", "Frontend"),
    44: ("Enterprise Case Studies", "Enterprise"),
    45: ("Interview .NET", "Interview"),
    46: ("Interview Cloud", "Interview"),
    47: ("Interview System Design", "Interview"),
    48: ("Whiteboard Mock 1", "System Design"),
    49: ("Whiteboard Mock 2", "System Design"),
    50: ("Leadership & Behavioral", "Behavioral"),
    51: ("STAR Behavioral", "Behavioral"),
    52: ("Graduation Capstone", "Career"),
}

CONCEPTS = {
    "C#": [
        ("Value vs reference types", "C# Type System", "High-throughput DTOs, money types", "Large structs, polymorphic entities", "record struct Money in payment API at 10K RPS"),
        ("Nullable reference types", "C# Type System", "All new enterprise projects", "Legacy without migration plan", "NRT enabled with warnings-as-errors in CI"),
        ("record vs class", "C# Types", "Immutable API contracts", "Entities with behavior and identity", "record OrderDto vs class Order aggregate"),
        ("async/await pitfalls", "Async", "I/O-bound ASP.NET handlers", "CPU-bound work on thread pool", "DbContext not thread-safe across parallel tasks"),
        ("Span and memory", "Performance", "Parsing, serialization hot paths", "Simple CRUD APIs", "ReadOnlySpan<char> for log parsing"),
        ("LINQ performance", "Performance", "Non-hot-path queries", "Request handler inner loops", "Materialize once; avoid repeated enumeration"),
        ("IDisposable pattern", "Resource Mgmt", "Unmanaged handles, large arrays", "DI singletons holding DbContext", "IAsyncDisposable for async cleanup"),
        ("Generics constraints", "Generics", "Reusable algorithms", "Over-constrained type parameters", "where T : IValidatable for pipeline"),
        ("Pattern matching", "Modern C#", "Type-safe branching", "Replacing all polymorphism", "switch on OrderStatus with exhaustiveness"),
        ("Source generators", "Modern C#", "Boilerplate reduction at scale", "Small teams without generator expertise", "Mapperly for DTO mapping"),
    ],
    "Distributed Systems": [
        ("CAP theorem", "Fundamentals", "Partition tolerance required in cloud", "Ignoring consistency needs", "Choose CP for ledger, AP for catalog"),
        ("Eventual consistency", "Consistency", "High-scale reads, async pipelines", "Financial invariants without compensation", "Read replica lag on product catalog"),
        ("Idempotency keys", "Reliability", "Payment and order APIs", "Read-only GET endpoints", "Idempotency-Key header with Redis dedup"),
        ("Two-phase commit", "Transactions", "Rare strong cross-DB needs", "Microservices default", "XA avoided; saga preferred"),
        ("Saga pattern", "Transactions", "Distributed business workflows", "Simple single-DB CRUD", "Order saga: reserve → pay → confirm"),
        ("Outbox pattern", "Messaging", "Atomic DB write + event publish", "Fire-and-forget after SaveChanges", "Transactional outbox table + relay"),
        ("Quorum consensus", "Consensus", "Leader election, distributed locks", "Single-region SQL", "etcd/Raft in K8s control plane"),
        ("Clock skew", "Time", "Designing TTL and ordering", "Assuming synchronized clocks", "Use logical clocks or versioning"),
        ("Split brain", "Failure", "HA cluster design", "Ignoring network partitions", "Redis sentinel with odd quorum"),
        ("Backpressure", "Resilience", "Stream and queue consumers", "Unbounded in-memory buffers", "Reactive Streams, KEDA scaling"),
    ],
    "Microservices": [
        ("Service boundaries", "Decomposition", "Independent deploy and scale", "Premature split of monolith", "Bounded context per team"),
        ("API gateway", "Gateway", "Single entry, auth, routing", "Direct client-to-10-services", "APIM/Ocelot with rate limits"),
        ("BFF pattern", "API Design", "Mobile vs web different shapes", "One API for all clients forever", "Mobile BFF aggregates 3 services"),
        ("Database per service", "Data", "Team autonomy, independent schema", "Reporting across services", "Order DB separate from Inventory DB"),
        ("Synchronous vs async", "Communication", "User waits → sync; else async", "Sync chains 5+ deep", "Checkout sync; notifications async"),
        ("Circuit breaker", "Resilience", "Unreliable downstream", "Every HttpClient call", "Polly opens after 50% failures"),
        ("Bulkhead isolation", "Resilience", "Thread pool per dependency", "Shared pool for all HTTP", "Separate HttpClient factory pools"),
        ("Strangler fig", "Migration", "Incremental monolith extraction", "Big-bang rewrite", "Route /orders/* to new service"),
        ("Service mesh", "Infrastructure", "mTLS, observability at 15+ services", "3-service system", "Istio for east-west traffic"),
        ("Contract testing", "Testing", "Consumer-driven contracts", "E2E only for integration", "Pact between Order and Payment"),
    ],
    "System Design": [
        ("RESHADED framework", "Methodology", "Every whiteboard interview", "Jumping to boxes", "Requirements before components"),
        ("Capacity estimation", "Estimation", "Back-of-envelope QPS/storage", "Exact numbers without assumptions", "100M users × 10KB = 1TB profile data"),
        ("Load balancing", "Scale", "Horizontal scale", "Single server wishful thinking", "L7 ALB with health checks"),
        ("Caching layers", "Caching", "Read-heavy, hot keys", "Cache everything including auth", "Redis cache-aside for product pages"),
        ("CDN", "Edge", "Static assets, global users", "Dynamic personalized API at edge", "CloudFront for SPA bundles"),
        ("Database sharding", "Data Scale", "Write scale beyond single node", "Day-one sharding for 100 users", "Shard by tenantId hash"),
        ("Read replicas", "Data Scale", "Read-heavy workloads", "Strong consistency on replicas", "5:1 read/write ratio to replicas"),
        ("Message queues", "Async", "Decouple producers/consumers", "Sync for fire-and-forget", "SQS between order and email"),
        ("Rate limiting", "Security", "Public APIs, abuse prevention", "Internal-only admin APIs", "Token bucket at API gateway"),
        ("Multi-region design", "Availability", "99.99% SLA, global users", "Cost-sensitive internal tools", "Active-passive with Traffic Manager"),
    ],
    "Azure": [
        ("Management groups", "Governance", "Enterprise hierarchy", "Single subscription forever", "Platform MG + Application MG"),
        ("Well-Architected pillars", "WAF", "Architecture reviews", "Security-only reviews", "Score reliability before cost on payments"),
        ("Availability zones", "Reliability", "99.99% zone-redundant services", "Dev sandboxes", "Zone-redundant App Service"),
        ("Azure Policy", "Governance", "Enforce tags, deny public SQL", "Manual compliance checks", "Deny public IP on storage accounts"),
        ("Landing zones", "CAF", "Enterprise cloud adoption", "Ad-hoc resource groups", "Platform subscription for connectivity"),
        ("RBAC design", "Security", "Least privilege per team", "Contributor on subscription", "Custom deploy-only role for CI"),
        ("Cost management", "FinOps", "Budgets and alerts", "Ignoring until bill arrives", "Budget at 80% on prod subscription"),
        ("Resource tagging", "FinOps", "Chargeback and automation", "Optional tags", "Environment, CostCenter, Owner mandatory"),
        ("Region selection", "Strategy", "Latency, compliance, services", "Random region", "EU data residency → West Europe"),
        ("Subscription strategy", "Governance", "Prod/nonprod isolation", "One sub for everything", "sub-prod-team-a, sub-nonprod-team-a"),
    ],
    "DevOps": [
        ("DORA metrics", "Culture", "Assess delivery maturity", "Vanity deploy counts", "Baseline CFR before adding services"),
        ("Trunk-based development", "Branching", "Microservice teams", "Versioned library releases", "Feature flags for incomplete work"),
        ("Feature flags", "Release", "Decouple deploy from release", "Long-lived release branches", "LaunchDarkly/App Config flags"),
        ("Blue-green deploy", "Deployment", "Zero-downtime swap", "Stateful single instance", "App Service slot swap"),
        ("Canary deployment", "Deployment", "Risk reduction on changes", "Every tiny config change", "10% traffic to new version"),
        ("GitOps", "Deployment", "K8s declarative desired state", "kubectl apply from laptop", "Argo CD sync from Git"),
        ("OIDC federation", "Security", "CI/CD to cloud without secrets", "Long-lived SP passwords in GitHub", "GitHub Actions → Entra federated cred"),
        ("Infrastructure as Code", "IaC", "Repeatable environments", "ClickOps production", "Bicep modules in PR with what-if"),
        ("OpenTelemetry", "Observability", "Vendor-neutral tracing", "Proprietary agent lock-in", "OTel SDK → App Insights exporter"),
        ("SLO and error budgets", "SLO", "Balance velocity and reliability", "100% uptime goal", "99.9% SLO → 43min/month budget"),
    ],
    "Data Structures": [
        ("Hash table", "Hash Tables", "O(1) key lookup caches and indexes", "Ordered range queries", "Redis key-value and consistent hashing rings"),
        ("B+ tree index", "Trees", "Disk-backed range queries in databases", "In-memory only workloads", "SQL Server clustered index leaf pages"),
        ("Trie prefix search", "Trees", "Autocomplete and IP routing tables", "Exact match only workloads", "Typeahead search over product catalog"),
        ("Min-heap priority queue", "Heaps", "Top-K and job scheduling", "Uniform priority workloads", "Redis ZSET for game leaderboards"),
        ("Bloom filter", "Probabilistic", "Cheap membership tests before DB lookup", "Exact membership required", "Cassandra negative lookup before disk read"),
        ("Consistent hashing", "Distributed", "Shard routing with minimal remapping", "Single-node stores", "Memcached client shard selection"),
        ("LRU cache structure", "Caching", "Bounded in-memory hot key cache", "Unbounded caching", "Hash map + doubly linked list → Redis LRU policy"),
        ("Graph dependency map", "Graphs", "Service blast-radius analysis", "Linear pipelines only", "DFS on microservice call graph during incidents"),
        ("Queue FIFO semantics", "Queues", "Async work distribution", "LIFO undo workflows", "Service Bus queue for order emails"),
        ("Ring buffer", "Arrays", "High-throughput streaming buffers", "Random access primary", "Disruptor pattern in low-latency pipelines"),
        ("Skip list", "Lists", "Ordered in-memory indexes", "Simple few-element lists", "Redis internal sorted set implementation concept"),
        ("Inverted index", "Search", "Full-text search token lookup", "Key-value only access", "Elasticsearch term → document IDs"),
        ("Count-min sketch", "Probabilistic", "Streaming frequency estimation", "Exact counts required", "Heavy hitter detection in CDN logs"),
        ("Union-find disjoint set", "Graphs", "Connected components grouping", "Strict hierarchy only", "Network connectivity grouping in topology tools"),
        ("Sliding window deque", "Queues", "Rate limiting time windows", "Stateless counting", "Requests-per-minute rolling window limiter"),
    ],
    "Algorithms": [
        ("Big O analysis", "Complexity", "Predict scaling breakpoints", "Premature micro-optimization", "O(n) table scan fails at 500M rows"),
        ("Binary search", "Search", "Sorted data O(log n) lookup", "Unsorted datasets", "B-tree index search on disk"),
        ("Merge sort external", "Sorting", "Large disk-backed sorts", "Small in-memory arrays", "MapReduce shuffle sort phase"),
        ("Dijkstra shortest path", "Graphs", "Weighted routing decisions", "Unweighted simple BFS enough", "CDN edge path selection concept"),
        ("Topological sort", "Graphs", "Build/deploy dependency ordering", "Cyclic workflows", "CI pipeline task DAG ordering"),
        ("Dynamic programming memoization", "DP", "Avoid redundant expensive computation", "Simple linear workflows", "Precomputed shipping rate matrix lookup"),
        ("Greedy heuristics", "Optimization", "Fast near-optimal routing/scheduling", "Proven global optimum required", "Bin packing for container placement"),
        ("Amortized analysis", "Complexity", "Explain rare latency spikes", "Average-only thinking", "Gen2 GC and log compaction spikes"),
        ("Two pointers technique", "Patterns", "Sorted array pair problems", "Unsorted random access", "Merge two sorted audit log streams"),
        ("Sliding window", "Patterns", "Streaming metrics and rate limits", "Batch offline only", "5-minute error rate rolling alert"),
        ("BFS vs DFS", "Graphs", "Shortest path vs cycle detection", "Same algorithm for everything", "BFS blast radius from failed payment service"),
        ("Backtracking with pruning", "Search", "Constraint satisfaction exploration", "Polynomial greedy sufficient", "Configuration validation with early exit"),
        ("NP-hard heuristics", "Optimization", "VRP and scheduling at scale", "Small n exact solve", "Delivery route OR-Tools heuristic"),
        ("Recursion depth limits", "Recursion", "Hierarchy and tree traversal", "Deep unbounded chains", "Org chart materialized path instead of deep recursion"),
        ("Parallel algorithm decomposition", "Parallel", "CPU-bound batch processing", "Tiny datasets", "Parallel LINQ on large batch validation"),
    ],
    "SQL Server": [
        ("Clustered index choice", "Indexing", "Primary access path row ordering", "Random GUID clustered PK", "Clustered on sequential OrderId not GUID"),
        ("Non-clustered covering index", "Indexing", "Eliminate key lookups on hot queries", "Write-heavy tables over-indexed", "INCLUDE columns for order list query"),
        ("Query execution plan", "Performance", "Diagnose scans and spills", "Guess without measuring", "Query Store finds top CPU queries"),
        ("Isolation levels", "Transactions", "Balance consistency and concurrency", "Serializable everywhere", "RCSI for read-heavy catalog"),
        ("Always On AG", "HA/DR", "HA and DR for SQL workloads", "Single instance production", "Sync replica same region RPO=0"),
        ("Partitioning", "Scale", "Archive and maintenance at 100M+ rows", "Small tables early partition", "Monthly SWITCH partition archive"),
        ("Tempdb contention", "Performance", "High concurrency sort and version store", "Ignore tempdb sizing", "Multiple tempdb files on multi-core"),
        ("Deadlock prevention", "Concurrency", "Ordered access and short transactions", "Long transactions with HTTP inside", "Consistent table lock order in SPs"),
        ("Columnstore analytics", "Analytics", "Large aggregation scans", "OLTP point lookups", "NCCI on OLTP for reporting offload"),
        ("Connection pooling", ".NET Integration", "Efficient SqlConnection reuse", "Pooling disabled", "Scoped DbContext per request"),
    ],
    "PostgreSQL": [
        ("MVCC and vacuum", "Concurrency", "Postgres concurrency model", "Ignoring autovacuum tuning", "autovacuum on high-update tables"),
        ("JSONB hybrid model", "Document", "Flexible attributes on relational core", "All data in JSONB", "product.metadata JSONB + GIN index"),
        ("GIN vs GiST indexes", "Indexing", "JSONB and full-text paths", "B-tree only mentality", "GIN on JSONB containment queries"),
        ("Streaming replication lag", "HA/Scale", "Read replica scaling", "Strong consistency on replica reads", "Lag-aware routing if replay_lag > 5s"),
        ("PgBouncer pooling", "Operations", "Multiplex client connections", "Thousands of direct connections", "Transaction pooling mode for web apps"),
        ("BRIN index", "Indexing", "Large append-only time-series", "Random access OLTP", "BRIN on created_at audit logs"),
        ("Expand-contract migration", "Migrations", "Zero-downtime schema change", "Breaking rename in one release", "Add column → backfill → enforce"),
        ("Polyglot with Redis", "Caching", "Cache-aside in front of Postgres", "Postgres as cache", "Redis product cache with TTL invalidation"),
        ("Postgres vs SQL Server", "Strategy", "Open source JSON and cost", "Ignoring team SQL Server skill", "Postgres for catalog microservice"),
        ("Row-level security", "Security", "Tenant isolation in shared DB", "App-only filtering", "RLS policy on tenant_id column"),
    ],
    "DDD": [
        ("Bounded context", "Strategic DDD", "Linguistic and model boundaries", "One enterprise data model", "Customer means different things in Billing vs Support"),
        ("Aggregate root", "Tactical DDD", "Consistency boundary per transaction", "Giant cross-entity transactions", "Order root controls OrderLines mutations"),
        ("Ubiquitous language", "Strategic DDD", "Shared business vocabulary in code", "Technical jargon in domain", "PlaceOrder not ProcessOrderDto"),
        ("Domain events", "Events", "Capture business facts in model", "Integration events in domain layer", "OrderPlaced raised inside Order aggregate"),
        ("Anti-corruption layer", "Integration", "Isolate legacy models", "Import ERP DTOs into domain", "ErpAdapter maps legacy XML to commands"),
        ("Context mapping", "Strategic DDD", "Document upstream/downstream", "Implicit coupling", "Payment upstream → Order downstream conformist"),
        ("CQRS logical split", "Patterns", "Different read/write shapes", "CQRS on day-one CRUD", "Separate query handlers before separate DBs"),
        ("Event storming", "Discovery", "Find boundaries and flows", "Skip discovery workshops", "Orange sticky events → bounded contexts"),
        ("Anemic domain model", "Anti-Pattern", "Rich behavior on entities", "God service with all logic", "order.Confirm() not service.SetStatus"),
        ("Shared kernel", "Strategic DDD", "Small shared model between contexts", "Large shared library coupling", "Shared Money value object only"),
    ],
    "Messaging": [
        ("At-least-once delivery", "Semantics", "Default distributed messaging", "Assume exactly-once without design", "Idempotent consumer + messageId dedup"),
        ("Dead letter queue", "Reliability", "Poison message isolation", "Infinite retry", "DLQ alert on payment queue depth > 0"),
        ("Outbox pattern", "Reliability", "Atomic DB write and publish", "Publish after SaveChanges only", "Transactional outbox relay to Service Bus"),
        ("Inbox deduplication", "Reliability", "Consumer-side duplicate protection", "Trust single delivery", "Inbox table unique on messageId"),
        ("Event choreography", "Architecture", "Decoupled pub/sub reactions", "Complex 8-step orchestration", "OrderPlaced → Inventory + Notification subscribers"),
        ("Saga orchestration", "Architecture", "Visible multi-step workflow", "Simple 2-step flows only", "Durable Functions orchestrates checkout"),
        ("Partition ordering", "Ordering", "Per-key ordered processing", "Global order requirement", "Kafka partition key = orderId"),
        ("Schema evolution", "Governance", "Backward compatible events", "Breaking field renames", "Additive fields only in OrderPlacedV1"),
        ("Service Bus sessions", "Azure", "Ordered processing per session", "Global ordering need", "SessionId = orderId for sequential handling"),
        ("Message size limits", "Design", "Reference large payloads", "10MB JSON in message body", "Blob URL in event + small metadata"),
    ],
    "Scalability": [
        ("Cache-aside", "Caching", "Read-heavy hot key workloads", "Write-through everything", "Redis cache-aside for product pages"),
        ("CDN edge caching", "CDN", "Static assets and global users", "Personalized API responses at edge", "CloudFront for SPA bundles versioned"),
        ("Horizontal autoscaling", "Compute", "Stateless web tier scale out", "Vertical scale only", "AKS HPA on RPS custom metric"),
        ("Database sharding", "Data Scale", "Write scale beyond single node", "Shard at 1000 users", "Shard orders by tenantId hash"),
        ("Read replica routing", "Data Scale", "Offload read traffic", "Strong consistency on all reads", "Catalog reads to replica with lag tolerance"),
        ("Rate limiting", "Protection", "Public API abuse prevention", "Internal admin APIs unlimited", "Token bucket in Redis at gateway"),
        ("Hot key mitigation", "Sharding", "Celebrity/skewed access patterns", "Uniform sharding assumption", "Dedicated cache tier for hot product"),
        ("Multi-region failover", "Availability", "99.99% regional outage survival", "Single region cost saving", "Traffic Manager active-passive failover"),
        ("Connection pool sizing", "Operations", "Prevent DB connection storms", "Unbounded connections", "Pool size × instances < SQL max connections"),
        ("Autoscale cooldown", "Operations", "Prevent scaling flapping", "Instant scale in/out", "5-minute cooldown after scale out"),
    ],
    "Architecture": [
        ("Single Responsibility Principle", "SOLID", "One reason to change per module", "God classes with 20 methods", "Separate OrderPricing from OrderPersistence"),
        ("Open/Closed Principle", "SOLID", "Extend via new types not edits", "Modify switch for every new discount", "IDiscountStrategy implementations"),
        ("Liskov Substitution Principle", "SOLID", "Subtypes honor contracts", "Square inherits Rectangle incorrectly", "NotSupportedException in override = smell"),
        ("Interface Segregation Principle", "SOLID", "Small focused interfaces", "IFatInterface with 30 methods", "IReadOrder vs IWriteOrder split"),
        ("Dependency Inversion Principle", "SOLID", "Depend on abstractions", "new SqlOrderRepository in service", "Inject IOrderRepository interface"),
        ("Clean Architecture layers", "Clean Arch", "Domain-centric dependency rule", "Domain references EF Core", "Domain has zero infrastructure refs"),
        ("Vertical Slice Architecture", "Architecture", "Feature-based folders", "Layer folders for 3 features", "Features/Orders/CreateOrder handler"),
        ("CQRS logical separation", "Patterns", "Different read/write models", "CQRS on day-one CRUD", "MediatR commands vs queries"),
        ("MediatR pipeline behaviors", "Patterns", "Cross-cutting in pipeline", "Duplicate validation per handler", "ValidationBehavior before handler"),
        ("Anemic domain model", "Anti-Pattern", "Rich entities with behavior", "All logic in OrderService", "order.Confirm() on aggregate"),
        ("Ports and Adapters", "Hexagonal", "Isolate infrastructure", "EF entities in domain", "IOrderPort implemented by SqlAdapter"),
        ("Application layer role", "Clean Arch", "Orchestrate use cases", "Business rules in controllers", "CreateOrderHandler coordinates"),
        ("Domain events", "DDD", "Capture business facts", "Integration events in domain", "OrderPlaced raised from aggregate"),
        ("Validation placement", "Design", "Input validation at boundary", "Validation scattered everywhere", "FluentValidation on commands"),
        ("Exception handling strategy", "Design", "Consistent error responses", "try/catch per controller", "Global exception middleware + ProblemDetails"),
        ("Mapping strategies", "Design", "DTO to domain mapping", "AutoMapper magic everywhere", "Explicit mapper for complex aggregates"),
        ("Feature folders", "Organization", "Co-locate feature code", "Giant Services folder", "Orders/Create/CreateOrder.cs"),
        ("Modular monolith", "Architecture", "Bounded modules in one deploy", "Microservices too early", "Separate modules with clear APIs"),
        ("Testing pyramid in clean arch", "Testing", "Unit domain, integration infra", "E2E only", "Domain unit tests without DB"),
        ("EF Core in infrastructure", "Persistence", "DbContext outside domain", "DbContext in domain layer", "Infrastructure project owns EF"),
        ("Specification pattern", "Patterns", "Composable query logic", "Copy-paste LINQ filters", "ActiveOrdersSpec for repository"),
        ("Unit of Work", "Patterns", "Atomic transaction boundary", "Multiple SaveChanges per request", "One UoW per request scope"),
        ("Options pattern", "Configuration", "Strongly typed settings", "magic strings for config", "IOptions<PaymentSettings>"),
        ("Cross-cutting logging", "Observability", "Structured logging pipeline", "Console.WriteLine debug", "Serilog with correlation ID"),
        ("Health checks design", "Operations", "Liveness vs readiness", "DB check in liveness", "Separate /health/live and /ready"),
        ("API versioning", "API Design", "Stable public contracts", "Breaking changes without version", "URL path versioning /v2/"),
        ("Authorization vs authentication", "Security", "AuthN identity AuthZ permissions", "Confuse the two", "Policy-based authorization on handlers"),
        ("When NOT Clean Architecture", "Pragmatism", "Simple CRUD internal tools", "CA for 5-endpoint admin", "Pragmatic layering for low complexity"),
        ("Onion vs Clean Architecture", "Terminology", "Same dependency rule", "Religious naming debates", "Focus dependency direction not name"),
        ("Request response vs domain model", "Design", "Separate API contracts", "Expose EF entities on API", "OrderDto vs Order entity"),
    ],
    "Design Patterns": [
        ("Singleton vs DI singleton", "Creational", "DI singleton lifetime", "Static singleton anti-pattern", "Register cache as singleton in DI"),
        ("Factory pattern", "Creational", "Encapsulate object creation", "new everywhere", "PaymentGatewayFactory by type"),
        ("Abstract Factory", "Creational", "Families of related objects", "One factory for everything", "UI theme factory family"),
        ("Builder pattern", "Creational", "Complex object construction", "20-parameter constructor", "OrderBuilder with fluent API"),
        ("Prototype pattern", "Creational", "Clone expensive objects", "Reconstruct from scratch", "Deep clone template document"),
        ("Adapter pattern", "Structural", "Legacy interface wrapper", "Change legacy API globally", "LegacyErpAdapter implements IOrders"),
        ("Decorator pattern", "Structural", "Add behavior dynamically", "Deep inheritance tree", "CachingDecorator on IProductService"),
        ("Facade pattern", "Structural", "Simplify complex subsystem", "Controller calls 8 services", "CheckoutFacade orchestrates"),
        ("Proxy pattern", "Structural", "Control access lazy load", "Direct expensive calls", "Lazy loading proxy for report"),
        ("Composite pattern", "Structural", "Tree structures uniform", "Special case leaf nodes", "Org chart component tree"),
        ("Bridge pattern", "Structural", "Decouple abstraction from impl", "Explosion of subclasses", "MessageSender bridge SMS/Email"),
        ("Strategy pattern", "Behavioral", "Interchangeable algorithms", "switch on type string", "IShippingStrategy implementations"),
        ("Observer and events", "Behavioral", "Publish-subscribe decoupling", "Tight callback chains", "Domain events to handlers"),
        ("Command pattern", "Behavioral", "Encapsulate requests", "God method DoEverything", "PlaceOrderCommand + handler"),
        ("State pattern", "Behavioral", "State-specific behavior", "switch on status everywhere", "IOrderState implementations"),
        ("Template Method", "Behavioral", "Algorithm skeleton subclass steps", "Duplicate algorithm steps", "BaseExporter defines flow"),
        ("Chain of Responsibility", "Behavioral", "Pipeline handlers", "Nested if validation", "Validation chain per request"),
        ("Mediator pattern", "Behavioral", "Reduce direct dependencies", "Spaghetti service calls", "MediatR as mediator"),
        ("Memento pattern", "Behavioral", "Undo state capture", "Expose internal state", "Audit snapshot memento"),
        ("Visitor pattern", "Behavioral", "Operations on hierarchy", "Pattern matching sufficient", "Visitor for complex tax calc tree"),
        ("Repository pattern", "Enterprise", "Persistence abstraction", "Repository on everything", "IOrderRepository meaningful aggregate"),
        ("Unit of Work pattern", "Enterprise", "Transaction coordination", "Per-repository transactions", "DbContext as UoW"),
        ("Outbox pattern", "Enterprise", "Reliable event publish", "SaveChanges then fire event", "Outbox table + relay worker"),
        ("Saga orchestration", "Enterprise", "Distributed workflow", "Saga for 2-step local TX", "Orchestrator for checkout steps"),
        ("CQRS with patterns", "Enterprise", "Separate read write stacks", "Separate DBs day one", "Logical CQRS first"),
        ("Anti-pattern God Object", "Anti-Pattern", "Split responsibilities", "ApplicationService 5000 lines", "Slice by feature command handlers"),
        ("Anti-pattern spaghetti callback", "Anti-Pattern", "Events or mediator", "Nested Action callbacks", "Async event driven flow"),
        ("Pattern selection framework", "Process", "Simplest pattern that works", "Pattern for every line", "Strategy when algorithms vary"),
        ("Visitor vs pattern matching", "Modern C#", "Pattern matching for simple", "Visitor for open hierarchy", "switch expression on types"),
        ("Enterprise vs GoF scope", "Terminology", "GoF tactical Enterprise integration", "Confuse categories", "GoF in code Enterprise in architecture"),
    ],
    ".NET": [
        ("GC generations tuning", "GC", "Monitor Gen2 collections", "Manual GC.Collect everywhere", "dotnet-counters % Time in GC"),
        ("Thread pool starvation", "Async", "Detect sync-over-async", "Ignore thread pool queue length", "Thread pool starvation events in logs"),
        ("HttpClientFactory", "HTTP", "Managed HttpClient lifetime", "new HttpClient per request", "IHttpClientFactory typed clients"),
        ("Polly resilience", "Resilience", "Retry circuit breaker timeout", "Infinite retry on 500", "Polly pipeline on Refit client"),
        ("OpenTelemetry .NET", "Observability", "Traces metrics logs", "Proprietary agent only", "OTel → Azure Monitor exporter"),
        ("Serilog structured logging", "Observability", "Structured properties", "String concat logs", "Serilog enrichers CorrelationId"),
        ("EF Core DbContext pooling", "EF Core", "High throughput contexts", "Pooling with stateful context", "AddDbContextPool for read API"),
        ("EF Core interceptors", "EF Core", "Cross-cutting data concerns", "Override SaveChanges everywhere", "Auditing interceptor"),
        ("Minimal API filters", "ASP.NET", "Cross-cutting on endpoints", "Duplicate middleware logic", "IEndpointFilter validation"),
        ("Rate limiting middleware", "ASP.NET", ".NET 7+ built-in limiter", "Custom broken limiter", "Fixed window on public API"),
        ("Output caching", "ASP.NET", "Cache GET responses", "Cache personalized responses", "Output cache on catalog GET"),
        ("Native AOT constraints", "Performance", "Startup and size wins", "AOT with heavy reflection", "AOT pilot on worker service"),
        ("Channels producer consumer", "Concurrency", "In-process async queues", "lock everywhere", "Channel<T> for in-proc pipeline"),
        ("IHostedService lifecycle", "Hosting", "Start stop cancellation", "Ignore stopping token", "BackgroundService with graceful drain"),
        ("Configuration providers chain", "Config", "Layered config sources", "Hardcoded prod strings", "Key Vault + App Configuration"),
        ("Data protection API", "Security", "Cookie encryption keys", "Custom crypto for cookies", "Data Protection shared key ring"),
        ("Authentication schemes", "Security", "JWT + cookies multi-scheme", "One scheme hack", "AddAuthentication multiple schemes"),
        ("Authorization policies", "Security", "Policy-based rules", "Role checks scattered", "RequireClaim policy handler"),
        ("ProblemDetails RFC7807", "API", "Standard error responses", "Custom error shapes per endpoint", "ProblemDetails middleware"),
        ("API versioning Asp.Versioning", "API", "Version discovery", "Break clients silently", "Asp.Versioning.Mvc package"),
    ],
    "AWS": [
        ("AWS Organizations SCPs", "Governance", "Org-wide guardrails", "IAM only no SCPs", "Deny unencrypted S3 buckets SCP"),
        ("IAM Identity Center", "Identity", "SSO for humans", "IAM users per person", "Identity Center permission sets"),
        ("CloudTrail organization trail", "Security", "Audit all API calls", "No trail in prod", "Org trail to centralized S3 bucket"),
        ("AWS Config rules", "Compliance", "Continuous compliance check", "Annual manual audit only", "Config rule required-tags"),
        ("VPC endpoints", "Networking", "Private AWS API access", "NAT for S3 access", "S3 gateway endpoint free"),
        ("Security groups vs NACLs", "Networking", "SG stateful primary defense", "NACL only no SG", "Least privilege SG per tier"),
        ("KMS encryption", "Security", "CMK for data at rest", "AWS managed keys only regulated", "CMK with key rotation annual"),
        ("Secrets Manager rotation", "Security", "Auto DB password rotate", "Password in parameter store plaintext", "Lambda rotation for RDS secret"),
        ("CloudWatch alarms", "Observability", "SLO breach alerts", "Alert on every metric", "Composite alarm on error rate + latency"),
        ("X-Ray tracing", "Observability", "Distributed trace AWS", "No tracing serverless", "X-Ray on API Gateway + Lambda"),
    ],
    "Multi-Cloud": [
        ("Primary cloud selection", "Strategy", "Workload fit assessment", "Religious single choice", "Decision matrix per workload"),
        ("Abstraction tax", "Strategy", "Cost of portability layer", "Abstract everything", "Portability where justified only"),
        ("Cross-cloud networking", "Networking", "VPN/DX + ExpressRoute", "Public internet replication", "Private link hybrid primary"),
        ("Identity federation", "Identity", "Central IdP both clouds", "Duplicate user stores", "Entra + IAM Identity Center SSO"),
        ("FinOps unified tagging", "FinOps", "Same tag keys both clouds", "Different tag standards", "Environment CostCenter Owner both"),
        ("DR cross-cloud", "DR", "Secondary region different cloud", "Untested DR", "Async replication with runbook"),
        ("Egress cost modeling", "FinOps", "Include in TCO", "Ignore data transfer", "Egress line item in architecture review"),
        ("Vendor lock-in ADR", "Governance", "Document accepted lock-in", "Deny all managed services", "ADR per critical PaaS choice"),
        ("Terraform multi-provider", "IaC", "Modules per cloud", "One module lowest common", "azure/ and aws/ module roots"),
        ("Kubernetes portability", "Containers", "Workloads portable on K8s", "K8s for 2 containers", "EKS and AKS similar deploy model"),
    ],
}

# Map week number → concept bank key (fallback to week topic category word)
WEEK_BANK = {
    1: "C#", 2: ".NET", 3: "Architecture", 4: "Design Patterns",
    5: "Data Structures", 6: "Algorithms", 7: "SQL Server", 8: "PostgreSQL",
    9: "Azure", 10: "Azure", 11: "Azure", 12: "Azure",
    13: "Azure", 14: "Azure", 15: "Messaging", 16: "Azure",
    17: "AWS", 18: "AWS", 19: "AWS", 20: "Multi-Cloud",
    21: "Distributed Systems", 22: "Microservices", 23: "DDD", 24: "Microservices",
    25: "DevOps", 26: "DevOps", 27: "DevOps", 28: "DevOps",
    29: "DevOps", 30: "DevOps", 31: "DevOps", 32: "DevOps",
    33: "System Design", 34: "Scalability", 35: "Messaging", 36: "System Design",
    37: "System Design", 38: "System Design", 39: "System Design", 40: "System Design",
    41: "System Design", 42: "Azure", 43: "System Design", 44: "Microservices",
    45: "C#", 46: "Azure", 47: "System Design", 48: "System Design",
    49: "System Design", 50: "C#", 51: "C#", 52: "C#",
}

QUESTION_FORMS = [
    ("Define and apply", "What is {title} and when would you apply it in {topic}?"),
    ("Trade-offs", "What are the trade-offs of {title} in a production {topic} system?"),
    ("Compare", "How does {title} compare to alternative approaches in {topic}?"),
    ("Failure modes", "What failure modes occur when {title} is misapplied in {topic}?"),
    ("Interview scenario", "In a {topic} interview, how would you explain {title} to a principal engineer?"),
    ("Stakeholder", "How do you justify {title} to non-technical stakeholders in a {topic} initiative?"),
    ("Migration", "When migrating a legacy system, where does {title} fit in {topic}?"),
    ("Cost", "How does {title} affect cost and operability in {topic}?"),
    ("Security", "What security implications does {title} have in {topic}?"),
    ("Scale", "At what scale does {title} become necessary in {topic}?"),
]

EXPERT_SCENARIOS = [
    ("Production incident", "A {topic} system experiences cascading failures. Walk through your response using concepts including {title}."),
    ("Architecture review", "Review a team's {topic} design that omits {title}. What risks do you flag?"),
    ("Build vs buy", "Leadership wants to build in-house vs buy SaaS for {topic}. How does {title} inform your recommendation?"),
    ("Regulatory audit", "Auditors question your {topic} architecture regarding {title}. How do you respond?"),
    ("Scale 10x", "Traffic will 10x in 6 months. What changes involving {title} do you prioritize in {topic}?"),
]
